### PR TITLE
[DowngradePhp80] Use ArgsAnalyzer for has named args check

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba I think we should back to "Squash and merge" as use "Merge commit" will took back and forth to rebase and restructure meaningfull commit as we have many CI that need to be verified.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
@samsonasik Allright, I thought we have some workflows agains that change. I've updated it back so we don't burry ourselves in extra work.

Thanks :+1:

**Comment by TomasVotruba** [comment]
The generated changelogs for new Rector release were also full of detailed commits after switch to "merge". It took much longer to go through with same repeated commits.

**Pull request merged**
