### PR TITLE
[PHPStanStaticTypeMapper] Reduce bool check on UnionTypeMapper

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Comment by TomasVotruba** [comment]
Very nice :+1:

**Comment by TomasVotruba** [comment]
Very nice :+1:

**Pull request merged**
