### PR TITLE
[Fix] use League\Flysystem\FilesystemInterface for RenameMethodRector

### LINKED ISSUE #6483: league/flysystem upgrade set not working
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.8             |

Upgrade set for league/flystem not working. I believe the reason is that class Filesystem has a parent FilesystemInterface and that's why rename method rules are not executed.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/54879889-2385-4f0f-a150-0010face86e2 - not working
https://getrector.org/demo/23bf620b-6a00-4f99-8485-937135df0388 - working

The only change is that in second demo Filesystem has no parent.

Is there any reason why RenameMethodRector checks if configured class has an interface or parent class?

https://github.com/rectorphp/rector-src/blob/1913747f014f5b4663dec6b32148a8d5046a74a5/rules/Renaming/Rector/MethodCall/RenameMethodRector.php#L86

## Expected Behaviour

Methods should be renamed also if the rector config contains non-top class or interface

### PR DESCRIPTION
**Pull request by lulco**
Resolves https://github.com/rectorphp/rector/issues/6483

### CODE REVIEW

**Comment by lulco** [comment]
Errors in CI don't seem to be related to this PR

**Comment by samsonasik** [comment]
ECS notice should be handled at https://github.com/symplify/symplify/pull/3262 that need new ECS released.

**Comment by samsonasik** [comment]
There is new ECS release, please run `composer update`, `rector`, `ecs check`, and `commit` like the following:

```bash
composer update && \
     bin/rector process src tests rules-tests packages packages-tests --ansi  && \ 
     vendor/bin/ecs check --match-git-diff --fix --ansi && \
     git commit -m 'rectify' -a && \
     git push origin fix-league-flysystem
```

If everything is ok ,the CI will be green.

**Comment by lulco** [comment]
@samsonasik @TomasVotruba done. It is green now. Please review

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
