### PR TITLE
ReturnNeverTypeRector: change return type to never for setters #8121

### PR DESCRIPTION
**Pull request by mkrauser**
Just a test-case for now

### CODE REVIEW

**Comment by staabm** [comment]
`ReturnNeverTypeRector`  is about adding the `never` type, see https://wiki.php.net/rfc/never_for_parameter_types

`void` is a different animal

**Comment by TomasVotruba** [comment]
As @staabm writes, the never and void types are different breed

**Comment by samsonasik** [comment]
@TomasVotruba based on https://getrector.com/demo/97fdb5ad-2afa-4182-9cc4-af4f4cb99403

It should be skipped as already return void. The issus is it adding never type when there is `@param`, it should be reopen

**Comment by TomasVotruba** [comment]
@samsonasik Ah, I see, I missunderstand the comment. Thanks for checking

**Comment by samsonasik** [comment]
@mkrauser you may need to remove vendor, clear composer cache and re-run composer update to handle `argument "$container" of method "__construct()" references class` issue.

```
rm -rf vendor
composer clear-cache
composer update
```

**Comment by samsonasik** [comment]
Also hard clean cache may help:

```
php -r 'shell_exec("rm -rf " . sys_get_temp_dir() . "/rector_cached_files");';
```

**Comment by samsonasik** [comment]
@mkrauser I cherry-picked your commit at PR https://github.com/rectorphp/rector-src/pull/4721

**Pull request closed without merging**
