### PR TITLE
added promoted property test for annotation to attribute rule

### PR DESCRIPTION
**Pull request by calvera**
https://github.com/rectorphp/rector/issues/6566

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the PR :+1: 

It seems the `Param` node is missing in the nodes to process:
https://github.com/rectorphp/rector-src/blob/fb9ad83c32770022a3816ee06c88d92cd84dc322/rules/Php80/Rector/Class_/AnnotationToAttributeRector.php#L111

Could you add it there?

**Comment by calvera** [comment]
it works after the fix (but the generated code is not formatted nicely)

**Comment by samsonasik** [comment]
Formatting seems needs to by coding standard.

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you @calvera for improvement :+1:

**Pull request merged**
