### PR TITLE
NodeNameResolver: faster isNames()

### PR DESCRIPTION
**Pull request by staabm**
prevent repeated calls to getName() in codeigniter4

grafik

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Just curious, could you share "after" screenshot too? So we can see the improvement :)

**Comment by TomasVotruba** [comment]
Thanks :wink:

**Comment by staabm** [comment]
I can share after merge. But I guess its pretty minor (at least in the codeignitor case). 

Maybe 1-2 seconds

**Comment by TomasVotruba** [comment]
You can easily test locally by changing the particular vendor file.

**Comment by staabm** [comment]
> You can easily test locally by changing the particular vendor file.

yeah, I do it like that for simple PRs. the more files are involved the less is it worth the effort :-)

in this case it works like that - you are right

**Comment by staabm** [comment]
in my measuring it indiciates only a subsecond improvement on a run which takes +55 seconds

**Pull request merged**
