### PR TITLE
[Downgrade PHP 8.1] Add DowngradeNewInInitializerRector

### PR DESCRIPTION
**Pull request by villfa**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba the upgrade rule https://github.com/rectorphp/rector-src/blob/main/rules/Php81/Rector/ClassMethod/NewInInitializerRector.php doesn't provide property promotion, in against the downgrade of this PR.

Ref fixture:

https://github.com/rectorphp/rector-src/blob/511d649e49b966abd5bf8c79f243cb8d4fe27792/rules-tests/Php81/Rector/ClassMethod/NewInInitializerRector/Fixture/some_class.php.inc#L24-L26


is that on purpose?

**Comment by TomasVotruba** [comment]
> is that on purpose?

No, it's a very fresh rule, so probably not covered yet. Could you handle it?

**Comment by samsonasik** [comment]
I will try.

**Comment by villfa** [comment]
I've converted this PR to draft because it only covers constructors while by reading the RFC again it appears it concerns any method or function.

**Comment by TomasVotruba** [comment]
Thanks 👍 

It seems ready now, doesn't it?

**Comment by villfa** [comment]
It is but I wanted to apply CS before review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
