### PR TITLE
[CodeQuality] Add support for (), {}, [], <> delimiter on RegexPatternDetector

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
Closing for now, as cause error on SimplifyRegexPatternRector

**Comment by samsonasik** [comment]
Re-open, direct square bracket handled with equal check https://github.com/rectorphp/rector-src/pull/5957/commits/4136ed504d2143d718bd3bb1dcdf88425d897b0a

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Comment by TomasVotruba** [comment]
Looks good :+1:

**Pull request merged**
