### PR TITLE
[CodeQuality] Skip multi params on method on on setValue($a, $b, $c ...) on ExplicitMethodCallOverMagicGetSetRector on assign

### LINKED ISSUE #6980: Incorrect behavior of ExplicitMethodCallOverMagicGetSetRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec840c3-3d5b-6b58-aaf0-0bf21a653446

```php
<?php

final class DemoFile
{
    private ?string $foo = null;

    public function setFoo(string $foo, string $bar): void
    {
        $this->foo = $foo;
    }
    
    public function __set($name, $value)
    {
        $this->$name = $value;
    }
}

$demoFile = new DemoFile();
$demoFile->foo = 'a';
```

### Responsible rules

* `ExplicitMethodCallOverMagicGetSetRector`

## Expected Behavior

Although the example above is not something I would write 😆  it is not logical for rector to produce code that has fatal errors.
Applying this rule would result in "Fatal error: Uncaught ArgumentCountError: Too few arguments to function DemoFile::setFoo(), 1 passed".
I think this should be skipped because `setFoo` requires more than one argument.

I found this issue because of a Laravel issue with models on which I would also suggest another change to `ExplicitMethodCallOverMagicGetSetRector`.
We have a model with an attribute 'relation'. Because the `HasRelationships`-trait has a method `setRelation` assigning a value to the relation-property is fixed to calling `setRelation`, which is not what we want. At the moment it is possible to skip applying rules to certain files, but normally in this case the rule should be skipped for a certain target. In a normal case we handle the model outside of the models directory. So we want to say "do not apply rule when the handled class is an instance of Model". Could the `ExplicitMethodCallOverMagicGetSetRector` be configured to skip certain classes? Should I open a separate issue for this?
I tried adding a `@noRector` annotation above the assignment, but this fails due to https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3611 and besides that, adding all this `@noRector` anotations above all assignments that conflict somehow, while we want to rely on the 'magic' of the Laravel model seems cumbersome. BTW, currently I fixed the issue in my code by calling `Model::setAttribute('relation', 'a value')`.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6980

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :ok:

**Comment by gisostallenberg** [comment]
Thanks!

**Pull request merged**
