### PR TITLE
allow compatible phpdoc-parser

### PR DESCRIPTION
**Pull request by TomasVotruba**
See https://github.com/rectorphp/rector-symfony/pull/307

### CODE REVIEW

**Comment by samsonasik** [comment]
The autoload just overlapped in `rector-symfony`, that can be tweaked by add the bootstrap via:

```php
    $rectorConfig->bootstrapFiles([
        __DIR__ . '/vendor/phpstan/phpdoc-parser/src/Ast/Type/GenericTypeNode.php',
    ]);
```

in rector.php, see that https://github.com/rectorphp/rector-symfony/pull/306#issuecomment-1337299686 make CI green

**Comment by TomasVotruba** [comment]
This is now breaking in every package. Untill new PHPStan is released, we need to use compatible phpdoc-parser here

**Comment by samsonasik** [comment]
Actually, the "preload.php" can be used like in here https://github.com/rectorphp/rector-src/blob/main/preload.php

Every packages can load it (with some enhancement) and it will working ok.

**Comment by TomasVotruba** [comment]
Not necessary, we can wait for PHPStan release. There is nothing from phpdoc-parser 1.14 we use, right?

**Comment by samsonasik** [comment]
Ok 👍

**Comment by samsonasik** [comment]
@TomasVotruba The preload.php need to be regenerated.

**Comment by TomasVotruba** [comment]
I've removed it in wrong repo, should be fixed now:
https://github.com/rectorphp/rector-src/commit/3149ea4ebb6e3ec324ebb0e9e58db0fef7e2a9a8 :+1:

**Pull request merged**
