### PR TITLE
Revert "[Printer] Remove AlwaysRememberedExpr check on BetterStandardPrinter"

### PR DESCRIPTION
**Pull request by samsonasik**
Reverts rectorphp/rector-src#6484

Ref https://github.com/rectorphp/rector/issues/8815#issuecomment-2503453191

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
This bug will return for sure if you don't do what I tell you:

> Class Rector\PhpParser\Printer\BetterStandardPrinter should extended PHPStan's Printer which has this method.

This is PHPStan's Printer class: https://github.com/phpstan/phpstan-src/blob/2.0.x/src/Node/Printer/Printer.php

**Comment by samsonasik** [comment]
@ondrejmirtes, @TomasVotruba don't want to extends PHPStan printer, see discussion of it https://github.com/rectorphp/rector-src/pull/4305#pullrequestreview-1488935215

**Comment by samsonasik** [comment]
Also, as `PHPStan` printer now final, so can't extends, so we can't do special node printing handling base on attribute kind that node have after node changed if we use PHPStan printer.

**Comment by ondrejmirtes** [comment]
I could un-final it in PHPStan. I want to be free to add more virtual nodes in PHPStan. Rector will inevitably break in the future because of this.

**Comment by samsonasik** [comment]
I will let @TomasVotruba decide, we have node visitor which unwrap `AlwaysRememberedExpr` (this node only)

https://github.com/rectorphp/rector-src/blob/8d33d50dfc383b2cd794c23596d4cefa65547762/src/PHPStan/NodeVisitor/WrappedNodeRestoringNodeVisitor.php#L15-L29

that called after `processNodes()`

https://github.com/rectorphp/rector-src/blob/8d33d50dfc383b2cd794c23596d4cefa65547762/src/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php#L297-L306

this works well, until on specific circumtance, it somehow overlapped with what PHPStan apply during scan process, so this failsafe check instanceof `AlwaysRememberedExpr`is needed in the `BetterStandardPrinter`:

https://github.com/rectorphp/rector-src/blob/8d33d50dfc383b2cd794c23596d4cefa65547762/src/PhpParser/Printer/BetterStandardPrinter.php#L117-L119

that's can't be tested with unit test unfortunatelly.

**Comment by TomasVotruba** [comment]
We can give it a try :) we'll choose whichever option causes less maintenance

**Comment by ondrejmirtes** [comment]
Done https://github.com/phpstan/phpstan-src/commit/1abeeb77771fc3fece5c7196f75dfc1478840515

**Comment by samsonasik** [comment]
@ondrejmirtes I tried it, it seems after `$this->nodeScopeResolver->processNodes()`, it seems still needs unwrap, otherwise, it will still got error:

```
Rector\Tests\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRector\OptionalParametersAfterRequiredRectorTest::test with data set #7 ('/Users/samsonasik/www/rector-...hp.inc')
assert($subStartPos >= 0 && $subEndPos >= 0)

/Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php:688
/Users/samsonasik/www/rector-src/src/PhpParser/Printer/BetterStandardPrinter.php:116
```

see PR:

- https://github.com/rectorphp/rector-src/pull/6518

**Comment by ondrejmirtes** [comment]
Sorry for mystifying here, the Printer class from PHPStan isn't usable for you. Making it final again.

**Pull request merged**
