### PR TITLE
[TypeDeclaration] Skip public method on AddMethodCallBasedStrictParamTypeRector

### LINKED ISSUE #8116: Incorrect behavior of AddMethodCallBasedStrictParamTypeRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/87060280-79c0-4bc6-b9de-30e2c749eae7

```php
<?php

/**
 * Clx_Model_Abstract.
 */

/**
 * Abstract model class
 * Accessable properties must be protected and must have Getter and Setter.
 *
 * @copyright  Copyright (c) 2011 Complex GmbH (http://www.complex-it.de)
 */
abstract class Clx_Model_Abstract
{
    /**
     * Return array of object for json use.
     *
     * @return array<string, mixed>
     */
    public function toJson()
    {
        return $this->toArray(true);
    }

    /**
     * Return string representation of object.
     *
     * @return string
     */
    public function __toString()
    {
        return implode(', ', $this->toArray());
    }
    
    /**
     * Returns array of object.
     *
     * @param bool|string[] $cols
     *
     * @return array<string, mixed>
     */
    final public function toArray($cols = false)
    {
        if ((! is_bool($cols)) && (! is_array($cols))) {
            throw new Exception('Invalid value cols');
        }
    }

}
```

### Responsible rules

* `AddMethodCallBasedStrictParamTypeRector`

## Expected Behavior

~~should be skipped because the method beeing worked on contains a `is_array()` check~~

hmm I think it should be skipped because its a `public` method

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8116

@staabm as protected with final class checked at PR:

- https://github.com/rectorphp/rector-src/pull/4611

let's exclude next public method.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Review by staabm — APPROVED** [review]
Thanks

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Comment by TomasVotruba** [comment]
Looks good :clap:

**Pull request merged**
