### PR TITLE
[Scoper] Try enable DowngradeArrayIsListRector

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
`array_is_list` can inside If, so that need to be handled first:

```
                if (!$value->isAutowired() && !\array_is_list($resolvedArguments)) {
```

**Comment by samsonasik** [comment]
Let's try again.

**Comment by samsonasik** [comment]
I removed `symfony/polyfill-php81` to verify if it currently working

**Comment by samsonasik** [comment]
@TomasVotruba it seems working ok now 👍 

Screen Shot 2023-06-07 at 06 14 04

Screen Shot 2023-06-07 at 06 15 36

**Comment by TomasVotruba** [comment]
Thanks a lot :partying_face:

**Pull request merged**
