### PR TITLE
[DX] Detach typo3 from core to allow stable growth of both packages

### PR DESCRIPTION
**Pull request by TomasVotruba**
Last 3 months I've been working on upgrade of Rector and it caused me to duplicate lot of work directly in typo3 Rector. The reason is typo3 Rector uses `rector/rector-src` dev-main. It is very unstable and any commit here can break it. And many times it did :(

On the otherside, the typo3 Rector depens on many external packages, that are not useful for the other rector/rector users. Because of current architecture, they're forced to download it and whole prefixed Rector is shipped with those.

That's stressful for both sides and shows bad architecture. 

<br>

Instead, external package like should use `rector/rector` and build on top of that. 

**There are many existing 3rd party extensions** that work well this way:

* https://github.com/FriendsOfShopware/shopware-rector
* https://github.com/craftcms/rector
* https://github.com/sulu/sulu-rector

Please follow their architecture for inspiration.

<br>

**How to change typo3-rector?** Basically it requires change of external dependency and updating related services:

```diff
 {
    "require": {
-         "rector/rector-src": "dev-main"
+         "rector/rector": "^0.13.4"
     }
 }
```

<br>

I belive this will allow both packages to grow closer to their domain and help their own communities closer, with their own specific problems :pray: :+1:

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@simonschaufi Hi, I believe you're now maintaining the project, so this is important to upgrade for your next release. 
It might require some work, but it will bring more stability for both packages. Let me know if you have some questions :+1:

**Comment by TomasVotruba** [comment]
I'm merging this, so you can use `rector/rector` without duplicating the classes.

**Comment by TomasVotruba** [comment]
As a unintentional side effect, Rector build now dropped from 4:50 to 3:40, that's 25 % faster :+1: 

<br>
  
### Before

image

<br>

### Now

image

**Comment by simonschaufi** [comment]
I'm just a contributor to the project like @helsner but @sabbelasichon is still the project lead. I didn't take over the project and I don't want that actually :smile:

**Pull request merged**
