### PR TITLE
[DowngradePhp80][DowngradePhp74] Handle DowngradeMatchToSwitchRector + DowngradeArraySpreadRector

### PR DESCRIPTION
**Pull request by samsonasik**
Fix #927 Closes rectorphp/rector#6708

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
Added more failing test case based on https://github.com/rectorphp/rector-src/pull/927#issuecomment-929035810 https://github.com/rectorphp/rector-src/pull/928/commits/824da0ac9ca437866351fae37f6e6fd2d1522ede

**Comment by samsonasik** [comment]
@leoloso should be fixed now.

**Comment by samsonasik** [comment]
The tests somehow show different result with my local dev:

```bash
1) Rector\Core\Tests\Issues\Issue6708\DowngradeMatchToSwitchAndArraySpreadRectorTest::test with data set #1 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
tests/Issues/Issue6708/Fixture/fixture2.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
     {
         switch ($operation) {
             case 'fruits':
-                $item2Unpacked = $this->getArray();
-                return array_merge(['banana', 'orange'], $item2Unpacked);
+                $item3Unpacked = $this->getArray();
+                return array_merge(['banana', 'orange'], $item3Unpacked);
         }
     }
 }

/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:151
/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:112
/home/runner/work/rector-src/rector-src/tests/Issues/Issue6708/DowngradeMatchToSwitchAndArraySpreadRectorTest.php:21

2) Rector\Core\Tests\Issues\Issue6708\DowngradeMatchToSwitchAndArraySpreadRectorTest::test with data set #2 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
tests/Issues/Issue6708/Fixture/fixture.php.inc
Failed asserting that string matches format description.
39
--- Expected
+++ Actual
@@ @@
 
     public function run($operation)
     {
-        $item2Unpacked = $this->getArray();
+        $item3Unpacked = $this->getArray();
         switch ($operation) {
             case 'fruits':
-                return array_merge(['banana', 'orange'], $item2Unpacked);
+                return array_merge(['banana', 'orange'], $item3Unpacked);
         }
     }
 }

/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:151
/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:112
/home/runner/work/rector-src/rector-src/tests/Issues/Issue6708/DowngradeMatchToSwitchAndArraySpreadRectorTest.php:21
```

**Comment by samsonasik** [comment]
@leoloso finally fixed now 🎉 I am really unsure about `iterator_to_array()` check on generating multiple value above switch when use both rules, but at least it works now.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by TomasVotruba** [comment]
I'm on it

**Comment by TomasVotruba** [comment]
Looks good, thank you :+1:

**Comment by leoloso** [comment]
Thanks @samsonasik 😄 I'll test it when released on 0.11.57

**Comment by TomasVotruba** [comment]
@leoloso  If you don't want to wait, we're using dev version for testing:

```json
{
    "require": {
        "rector/rector": "dev-main#c0c12d0"
    }
}
```

It's the last commit from https://github.com/rectorphp/rector

**Comment by leoloso** [comment]
Ok I tested it now. The issue is fixed, but I'm afraid that this solution could create another problem.

My original code is this one:

```php
public function getFilterInputModules(array $module): array
{
  $responseFilterInputModules = [
    ...$this->getIDFilterInputModules(),
    [CommonFilterInputModuleProcessor::class, CommonFilterInputModuleProcessor::MODULE_FILTERINPUT_SEARCH],
    [CommonFilterMultipleInputModuleProcessor::class, CommonFilterMultipleInputModuleProcessor::MODULE_FILTERINPUT_DATES],
    [FilterInputModuleProcessor::class, FilterInputModuleProcessor::MODULE_FILTERINPUT_COMMENT_TYPES],
  ];
  $customPostCommentFilterInputModules = [
    ...$responseFilterInputModules,
    [CommonFilterInputModuleProcessor::class, CommonFilterInputModuleProcessor::MODULE_FILTERINPUT_PARENT_ID],
    [CommonFilterInputModuleProcessor::class, CommonFilterInputModuleProcessor::MODULE_FILTERINPUT_PARENT_IDS],
    [CommonFilterInputModuleProcessor::class, CommonFilterInputModuleProcessor::MODULE_FILTERINPUT_EXCLUDE_PARENT_IDS],
  ];
  $rootCommentFilterInputModules = [
    ...$customPostCommentFilterInputModules,
    [FilterInputModuleProcessor::class, FilterInputModuleProcessor::MODULE_FILTERINPUT_CUSTOMPOST_ID],
    [FilterInputModuleProcessor::class, FilterInputModuleProcessor::MODULE_FILTERINPUT_CUSTOMPOST_IDS],
    [FilterInputModuleProcessor::class, FilterInputModuleProcessor::MODULE_FILTERINPUT_EXCLUDE_CUSTOMPOST_IDS],
    [CustomPostFilterInputModuleProcessor::class, CustomPostFilterInputModuleProcessor::MODULE_FILTERINPUT_UNIONCUSTOMPOSTTYPES],
  ];
  $adminCommentFilterInputModules = [
    [FilterInputModuleProcessor::class, FilterInputModuleProcessor::MODULE_FILTERINPUT_COMMENT_STATUS],
  ];
  return match ((string)$module[1]) {
    self::MODULE_FILTERINPUTCONTAINER_COMMENT_BY_ID_STATUS => [
      [CommonFilterInputModuleProcessor::class, CommonFilterInputModuleProcessor::MODULE_FILTERINPUT_ID],
      [FilterInputModuleProcessor::class, FilterInputModuleProcessor::MODULE_FILTERINPUT_COMMENT_STATUS],
    ],
    self::MODULE_FILTERINPUTCONTAINER_RESPONSECOUNT => $responseFilterInputModules,
    self::MODULE_FILTERINPUTCONTAINER_RESPONSES => [
      ...$responseFilterInputModules,
      ...$this->getPaginationFilterInputModules(),
    ],
    self::MODULE_FILTERINPUTCONTAINER_CUSTOMPOST_COMMENTCOUNT => $customPostCommentFilterInputModules,
    self::MODULE_FILTERINPUTCONTAINER_CUSTOMPOST_COMMENTS => [
      ...$customPostCommentFilterInputModules,
      ...$this->getPaginationFilterInputModules(),
    ],
    self::MODULE_FILTERINPUTCONTAINER_COMMENTCOUNT => $rootCommentFilterInputModules,
    self::MODULE_FILTERINPUTCONTAINER_COMMENTS => [
      ...$rootCommentFilterInputModules,
      ...$this->getPaginationFilterInputModules(),
    ],
    self::MODULE_FILTERINPUTCONTAINER_ADMINRESPONSECOUNT => [
      ...$responseFilterInputModules,
      ...$adminCommentFilterInputModules,
    ],
    self::MODULE_FILTERINPUTCONTAINER_ADMINRESPONSES => [
      ...$responseFilterInputModules,
      ...$this->getPaginationFilterInputModules(),
      ...$adminCommentFilterInputModules,
    ],
    self::MODULE_FILTERINPUTCONTAINER_CUSTOMPOST_ADMINCOMMENTCOUNT => [
      ...$customPostCommentFilterInputModules,
      ...$adminCommentFilterInputModules,
    ],
    self::MODULE_FILTERINPUTCONTAINER_CUSTOMPOST_ADMINCOMMENTS => [
      ...$customPostCommentFilterInputModules,
      ...$this->getPaginationFilterInputModules(),
      ...$adminCommentFilterInputModules,
    ],
    self::MODULE_FILTERINPUTCONTAINER_ADMINCOMMENTCOUNT => [
      ...$rootCommentFilterInputModules,
      ...$adminCommentFilterInputModules,
    ],
    self::MODULE_FILTERINPUTCONTAINER_ADMINCOMMENTS => [
      ...$rootCommentFilterInputModules,
      ...$this->getPaginationFilterInputModules(),
      ...$adminCommentFilterInputModules,
    ],
    default => [],
  };
}
```

It was transpiled like this:

```php
public function getFilterInputModules($module) : array
{
  $item0Unpacked = $this->getIDFilterInputModules();
  $responseFilterInputModules = \array_merge($item0Unpacked, [[CommonFilterInputModuleProcessor::class, CommonFilterInputModuleProcessor::MODULE_FILTERINPUT_SEARCH], [CommonFilterMultipleInputModuleProcessor::class, CommonFilterMultipleInputModuleProcessor::MODULE_FILTERINPUT_DATES], [FilterInputModuleProcessor::class, FilterInputModuleProcessor::MODULE_FILTERINPUT_COMMENT_TYPES]]);
  $customPostCommentFilterInputModules = \array_merge(\is_array($responseFilterInputModules) ? $responseFilterInputModules : \iterator_to_array($responseFilterInputModules), [[CommonFilterInputModuleProcessor::class, CommonFilterInputModuleProcessor::MODULE_FILTERINPUT_PARENT_ID], [CommonFilterInputModuleProcessor::class, CommonFilterInputModuleProcessor::MODULE_FILTERINPUT_PARENT_IDS], [CommonFilterInputModuleProcessor::class, CommonFilterInputModuleProcessor::MODULE_FILTERINPUT_EXCLUDE_PARENT_IDS]]);
  $rootCommentFilterInputModules = \array_merge(\is_array($customPostCommentFilterInputModules) ? $customPostCommentFilterInputModules : \iterator_to_array($customPostCommentFilterInputModules), [[FilterInputModuleProcessor::class, FilterInputModuleProcessor::MODULE_FILTERINPUT_CUSTOMPOST_ID], [FilterInputModuleProcessor::class, FilterInputModuleProcessor::MODULE_FILTERINPUT_CUSTOMPOST_IDS], [FilterInputModuleProcessor::class, FilterInputModuleProcessor::MODULE_FILTERINPUT_EXCLUDE_CUSTOMPOST_IDS], [CustomPostFilterInputModuleProcessor::class, CustomPostFilterInputModuleProcessor::MODULE_FILTERINPUT_UNIONCUSTOMPOSTTYPES]]);
  $adminCommentFilterInputModules = [[FilterInputModuleProcessor::class, FilterInputModuleProcessor::MODULE_FILTERINPUT_COMMENT_STATUS]];
  $item1Unpacked = $this->getPaginationFilterInputModules();
  $item2Unpacked = $this->getPaginationFilterInputModules();
  $item3Unpacked = $this->getPaginationFilterInputModules();
  $item4Unpacked = $this->getPaginationFilterInputModules();
  $item5Unpacked = $this->getPaginationFilterInputModules();
  $item6Unpacked = $this->getPaginationFilterInputModules();
  switch ((string) $module[1]) {
    case self::MODULE_FILTERINPUTCONTAINER_COMMENT_BY_ID_STATUS:
      return [[CommonFilterInputModuleProcessor::class, CommonFilterInputModuleProcessor::MODULE_FILTERINPUT_ID], [FilterInputModuleProcessor::class, FilterInputModuleProcessor::MODULE_FILTERINPUT_COMMENT_STATUS]];
    case self::MODULE_FILTERINPUTCONTAINER_RESPONSECOUNT:
      return $responseFilterInputModules;
    case self::MODULE_FILTERINPUTCONTAINER_RESPONSES:
      return \array_merge(\is_array($responseFilterInputModules) ? $responseFilterInputModules : \iterator_to_array($responseFilterInputModules), $item1Unpacked);
    case self::MODULE_FILTERINPUTCONTAINER_CUSTOMPOST_COMMENTCOUNT:
      return $customPostCommentFilterInputModules;
    case self::MODULE_FILTERINPUTCONTAINER_CUSTOMPOST_COMMENTS:
      return \array_merge(\is_array($customPostCommentFilterInputModules) ? $customPostCommentFilterInputModules : \iterator_to_array($customPostCommentFilterInputModules), $item2Unpacked);
    case self::MODULE_FILTERINPUTCONTAINER_COMMENTCOUNT:
      return $rootCommentFilterInputModules;
    case self::MODULE_FILTERINPUTCONTAINER_COMMENTS:
      return \array_merge(\is_array($rootCommentFilterInputModules) ? $rootCommentFilterInputModules : \iterator_to_array($rootCommentFilterInputModules), $item3Unpacked);
    case self::MODULE_FILTERINPUTCONTAINER_ADMINRESPONSECOUNT:
      return \array_merge(\is_array($responseFilterInputModules) ? $responseFilterInputModules : \iterator_to_array($responseFilterInputModules), $adminCommentFilterInputModules);
    case self::MODULE_FILTERINPUTCONTAINER_ADMINRESPONSES:
      return \array_merge(\is_array($responseFilterInputModules) ? $responseFilterInputModules : \iterator_to_array($responseFilterInputModules), $item4Unpacked, $adminCommentFilterInputModules);
    case self::MODULE_FILTERINPUTCONTAINER_CUSTOMPOST_ADMINCOMMENTCOUNT:
      return \array_merge(\is_array($customPostCommentFilterInputModules) ? $customPostCommentFilterInputModules : \iterator_to_array($customPostCommentFilterInputModules), $adminCommentFilterInputModules);
    case self::MODULE_FILTERINPUTCONTAINER_CUSTOMPOST_ADMINCOMMENTS:
      return \array_merge(\is_array($customPostCommentFilterInputModules) ? $customPostCommentFilterInputModules : \iterator_to_array($customPostCommentFilterInputModules), $item5Unpacked, $adminCommentFilterInputModules);
    case self::MODULE_FILTERINPUTCONTAINER_ADMINCOMMENTCOUNT:
      return \array_merge(\is_array($rootCommentFilterInputModules) ? $rootCommentFilterInputModules : \iterator_to_array($rootCommentFilterInputModules), $adminCommentFilterInputModules);
    case self::MODULE_FILTERINPUTCONTAINER_ADMINCOMMENTS:
      return \array_merge(\is_array($rootCommentFilterInputModules) ? $rootCommentFilterInputModules : \iterator_to_array($rootCommentFilterInputModules), $item6Unpacked, $adminCommentFilterInputModules);
    default:
      return [];
  }
}
```

So, as you can see from this example, the same function `$this->getPaginationFilterInputModules()` is being called multiple times. That wouldn't happen when the code is invoked within the `match` or the `switch`... If the function has side-effects, such as `$this->addCounterAndGetArray()`, then this will create a bug.

Shall I report a new issue?

**Comment by samsonasik** [comment]
@leoloso Feel free to create a patch if you found solution for that as well 👍

**Comment by leoloso** [comment]
I don't have a solution, only a problem 😭

**Comment by leoloso** [comment]
I have no clue why the original issue happens. From debugging I came to the impression that `addNodeBeforeNode` is failing when the node is added on a previous rule executed on that same run. As I don't have enough experience with Rector, I wouldn't know how to test it out.

If I'm right on this, then the issue is more important than solving this specific case, and it may be producing bugs somewhere else too.

**Comment by samsonasik** [comment]
That noted in https://github.com/rectorphp/rector-src/blob/1478d8eb78069114e5db2b4ac4ac429318690ff1/src/Application/FileProcessor.php#L32

**Comment by leoloso** [comment]
Well, then you know what the underlying problem is!

**Pull request merged**
