### PR TITLE
[Defluent] Skip mixin on FluentChainMethodCallToNormalMethodCallRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
/**
 * @mixin SkipMixin
 */
class SkipMixin
{
    public function someFunction()
    {
        $this->obj = $this;
        $this->obj->run()->execute();
    }

    public function run()
    {
        return $this;
    }

    public function execute()
    {
        return $this;
    }
}
```

It currently crash:

```bash
[1]    69072 segmentation fault  vendor/bin/phpunit 
```

Removing `@mixin` got normal output

### CODE REVIEW

**Comment by samsonasik** [comment]
The check seems need to be before `->refactor()` called, as if I add `die()` early:


```php
    public function refactor(Node $node): ?Node
    {
        die;
```

it still error:

```bash
[1]    69545 segmentation fault  vendor/bin/phpunit 
```

**Comment by samsonasik** [comment]
@TomasVotruba the crash seems on call the PHPStan's `NodeScopeResolver`

https://github.com/rectorphp/rector-src/blob/8240d3182aac5ded76ebd2a300164bdf7cb60174/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php#L106

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Review by TomasVotruba — APPROVED** [review]

**Pull request merged**
