### PR TITLE
[Php81] Skip named constructor on ReadOnlyPropertyRector

### LINKED ISSUE #8012: Incorrect behavior of ReadOnlyPropertyRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.17.1      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/71ddafa6-c5f7-49b7-a33f-a80fdb945510

```php
<?php

final class DemoFile
{
    private string $env;
    
    public function __construct()
    {
        $this->env = 'default';
    }
    
    public function getEnv(): string
    {
        return $this->env;
    }
    
    public static function create(string $env): self
    {
        $object = new self();
        $object->env = 'not default';
        return $object;
    }
}
```

### Responsible rules

* `ReadOnlyPropertyRector`

## Expected Behavior

The property `$env` should not be considered as `readonly` as it is modified in a specific method.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8012
Closes https://github.com/rectorphp/rector-src/pull/4356

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @Spomky @Jean85

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by TomasVotruba** [comment]
Thank you :clap:   :)

**Comment by Spomky** [comment]
Excellent! Many thanks 🎉

**Pull request merged**
