### PR TITLE
[TypeDeclaration] Skip set type by @param doc at TypedPropertyFromAssignsRector

### LINKED ISSUE #7007: Incorrect behavior of TypedPropertyFromAssignsRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec8f727-0af1-6508-bfc1-2fa5d8f64cf9

```php
<?php

final class DemoFile
{
    private $a;
    
    /**
     * @param int $a
     */
    public function __constructor($a)
    {
        $this->a = $a;
    }
}
```

### Responsible rules

* `TypedPropertyFromAssignsRector`

## Expected Behavior

Type `?int` was added based on doctype. But actually it might be incorrect. It would be nice if doctype-based types can be ignored to safely use this rule.

P.S.
I did some debug and found a workaround: https://twitter.com/xorik_dev/status/1494041577001521156
PHPStan can see both property type and phpdoc type, but in case of mixed property type, doctype type is chosen.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7007

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by xorik** [comment]
Cool, thanks so much, I'll test it!
Maybe it should be configurable? Something like `trustDoctype` true/false

**Comment by samsonasik** [comment]
I prefer to not make it configurable, make it as safe as possible, this check also happen on `RecastingRemovalRector` as well for direct param usage with no type, ref:

- https://github.com/rectorphp/rector-src/blob/4cf6522e7703687d7673d316ec60c5f21ec37dec/rules-tests/DeadCode/Rector/Cast/RecastingRemovalRector/Fixture/skip_non_typed_param.php.inc
- https://github.com/rectorphp/rector-src/blob/4cf6522e7703687d7673d316ec60c5f21ec37dec/rules/DeadCode/Rector/Cast/RecastingRemovalRector.php#L120

If we want to make property typed, we can update property with `@var type` and then use `\Rector\Php74\Rector\Property\TypedPropertyRector` so it will make it typed property.

**Comment by TomasVotruba** [comment]
Thank you @samsonasik :+1:

**Pull request merged**
