### PR TITLE
[DeadCode] Skip Array Callable dynamic method on RemoveUnusedPrivateMethodRector

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #908

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rolled back, it seems it needs to check second item value is not string:

https://github.com/rectorphp/rector-src/blob/3dd16b30e38c7ca4ee208e6ddde841cf4443d46b/packages/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php#L53

**Comment by samsonasik** [comment]
Fixed 🎉 , when `ValueResolver` tried to get values from `[$this, $other]`, it returns empty array, that's we catch it.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
I added another failing test case, this should be marked as normal array:

```php
final class NormalArray5
{
    public function go($a, $b)
    {
        return [$a, $b];
    }

    private function called()
    {
    }
}
```

but currently not

**Comment by samsonasik** [comment]
Finally Fixed 🎉

**Comment by samsonasik** [comment]
I added comment for when in the future, we look back on it, we know the reason why it returns array back https://github.com/rectorphp/rector-src/pull/909/commits/d79bff8a49a43a3fb359c61ad36d5f172136b204

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
