### PR TITLE
[Php80] Handle invalid change on extends PDO class on AddParamBasedOnParentClassMethodRector

### LINKED ISSUE #8053: Invalid identifier name "[]" with "extends PDO"
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | d78bfb44bebd32bd212a1f1ca43d2da51b22286d             |

Hello, I got an error on the latest version of Rector, trying to convert Doctrine/DBAL code.
Example: https://getrector.com/demo/625c2a10-39f4-48e7-98a1-44f5cc683c4b

Note that if you remove the "extends PDO" part, the problem is gone: https://getrector.com/demo/907df057-bf2c-4380-a356-7816224e390e

And if I replace "PDO" by "PDOx", the problem is also gone: https://getrector.com/demo/21c3a382-05dd-4f18-a767-f1df54bf0697

So the problem seems related to the word "PDO" himself?

Best regards
Jérémie

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8053
Ref https://getrector.com/demo/cb5b9b84-49ee-441e-bdd5-4efa7bd1a845

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed /cc @Worst45

**Comment by samsonasik** [comment]
It seems cause error , ref https://3v4l.org/fXhkv , it probably related with PHPStan signature about it...

**Comment by samsonasik** [comment]
It seems due to Jetbrain stubs define it:

https://github.com/JetBrains/phpstorm-stubs/blob/e2e898a29929d2f520fe95bdb2109d8fa895ba4a/PDO/PDO.php#L1096-L1097

so it based on what defined there, if the PDO class exists, it should works based on it.

**Comment by samsonasik** [comment]
So, jetbrains stubs has multiple `query()` functions defined:

so it fetch the first one 

https://github.com/JetBrains/phpstorm-stubs/blob/e2e898a29929d2f520fe95bdb2109d8fa895ba4a/PDO/PDO.php#L1096-L1126

**Comment by samsonasik** [comment]
TODO: make read attribute from parent stubs from JetBrain which detect target php version

```
#[PhpStormStubsElementAvailable(to: '7.4')]
```

or 

```
#[PhpStormStubsElementAvailable('8.0')]
```

**Comment by samsonasik** [comment]
It no longer crash, but still invalid change due to dupilcated methods with both has `#[PhpStormStubsElementAvailable]` attribute to point to php 7.4 and 8.0

https://getrector.com/demo/bbb3764c-fe9a-4d28-8d20-a1c5374f2226

https://github.com/JetBrains/phpstorm-stubs/blob/e2e898a29929d2f520fe95bdb2109d8fa895ba4a/PDO/PDO.php#L1096-L1126

The fixture need to be updated to use php 8.0 compat to show failing fixture.

**Comment by TomasVotruba** [comment]
I wonder what needs to be done here, or can we close it?

**Comment by samsonasik** [comment]
Not yet, read phpstorm stub need to verify `PhpStormStubsElementAvailable` first, if not at least current php version, move to next same method, it currently got first method found, see 

https://github.com/JetBrains/phpstorm-stubs/blob/e2e898a29929d2f520fe95bdb2109d8fa895ba4a/PDO/PDO.php#L1096-L1126

There are 2 methods named query, with different attribute , one for php 7.4, another for php 8.0

**Comment by TomasVotruba** [comment]
I'm checking update on this? :) 
I think we should either fix or close it, to avoid staling for months.

**Comment by TomasVotruba** [comment]
The demo link in original issue is now passing well https://getrector.com/demo/02bfa87c-eab8-43f6-aa73-f60ac41bbf27 :+1: 

Closing as solved.

**Comment by samsonasik** [comment]
It not yet resolved, It require check current PHP version.

Read phpstorm stub need to verify `PhpStormStubsElementAvailable` first, if not at least current php version, move to next same method, it currently got first method found, see 

https://github.com/JetBrains/phpstorm-stubs/blob/e2e898a29929d2f520fe95bdb2109d8fa895ba4a/PDO/PDO.php#L1096-L1126

There are 2 methods named query, with different attribute , one for php 7.4, another for php 8.0

**Comment by TomasVotruba** [comment]
I see.

The provided examle is passing. Let's move on to other issues now to avoid staling.
We can review if another report comes up :+1:

**Comment by samsonasik** [comment]
The demo site doesn't verify that transformation is a working code, which if run on php 8.1, the transformation will error, see issue:

- https://github.com/rectorphp/rector/issues/8332

The transformation only work on php 7.4

**Comment by TomasVotruba** [comment]
What action do you suggest to take?

**Comment by samsonasik** [comment]
My suggestion is to skip entirely on `PDO::query()`, so let user upgrade manually, as it will be different depends on php version used.

**Comment by samsonasik** [comment]
@TomasVotruba I created new PR to skip it:

- https://github.com/rectorphp/rector-src/pull/5313

**Pull request closed without merging**
