### PR TITLE
[DX] Add LevelSetList

### PR DESCRIPTION
**Pull request by TomasVotruba**
* Are you tired of registering all the PHP sets?
* Have you forget to register PHP 7.x and missed the features by accident?
* Do you want 1 configs to include-all-versions up to your current PHP?

We're adding solution just for you - new `LevelSetList New` class so you can level up your project in one line:

<br>

## `rector.php` Before :sleepy: 

```php
$containerConfigurator->import(SetList::PHP_52);
$containerConfigurator->import(SetList::PHP_53);
$containerConfigurator->import(SetList::PHP_54);
$containerConfigurator->import(SetList::PHP_55);
$containerConfigurator->import(SetList::PHP_56);
$containerConfigurator->import(SetList::PHP_70);
$containerConfigurator->import(SetList::PHP_71);
$containerConfigurator->import(SetList::PHP_72);
$containerConfigurator->import(SetList::PHP_73);
$containerConfigurator->import(SetList::PHP_74);
$containerConfigurator->import(SetList::PHP_80);
```

## `rector.php` Now :partying_face: 

```php
$containerConfigurator->import(LevelSetList::UP_TO_PHP80);
```

### CODE REVIEW

**Comment by TomasVotruba** [comment]
cc @matthiasnoback @lulco

**Comment by matthiasnoback** [comment]
Seems very useful! I'm not sure if the "MIN_" prefix is sufficiently self-documenting. Min means usually "at least", but the way this works is "everything less than, and including". Not sure what a good alternative is though.

**Comment by staabm** [comment]
Maybe `UPTO` or `UP_TO`instead of `MIN`

**Comment by TomasVotruba** [comment]
@matthiasnoback :+1: 

@staab Thanks for options! I like the `UP_TO` prefix :100:

**Comment by sabbelasichon** [comment]
@TomasVotruba Love it. Doing the same for TYPO3 right away. That´s what i mean with Developer Experience. A very important factor for successful packages.

**Comment by TomasVotruba** [comment]
Thanks everyone for feedback and tips to improve this feature :+1: 
Let's ship it to the code :rocket:

**Pull request merged**
