### PR TITLE
Skip namespaced use on removeUnusedImports() feature

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba per discussed at https://github.com/rectorphp/rector-src/pull/3364#pullrequestreview-1289471072

This namespaced use usage should be skipped, as namespaced use used.

```php
use Rector\Core\Tests\Issues\NamespacedUse\Source;

final class SkipNamespacedUse extends Source\SomeClass
{
}
```

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
I also added failing fixture namespaced use combined with auto import https://github.com/rectorphp/rector-src/pull/3365/commits/cb380b916a89b47c19e5732b57c26fda0397a462

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
