### PR TITLE
[Core] Fix undefined array key 0 on FormatPerservingPrinter

### LINKED ISSUE #6907: [BUG] FormatPerservingPrinter or BetterStandardPrinter - "Undefined offset: 0"
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | `fee8a47d1a627b01bfba2d85293c84692715506a` |

The script does its job, but while it should display a summary for a certain file, it does get errors:

```
 [ERROR] Could not process "/app/vendor/rector/rector/src/PhpParser/Printer/FormatPerservingPrinter.php"  
         file, due to:                                                                                                  
         "Undefined offset: 0". On line: 60                                                                             
                                                                                                                        
 [ERROR] Could not process "/app/vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php"    
         file, due to:                                                                                                  
         "Undefined offset: 0". On line: 363                                                                            
```

Methods: 
```
\Rector\Core\PhpParser\Printer\BetterStandardPrinter::resolveNewStmts()
\Rector\Core\PhpParser\Printer\FormatPerservingPrinter::resolveNewStmts()
```
check that the number of elements in the array is equal to 1, and get the element index 0, but in this case the only element is index 1, hence the error.

![image](https://user-images.githubusercontent.com/421597/147963268-32aff134-ef26-4e04-9f9f-580bef0f6ad6.png)
![image](https://user-images.githubusercontent.com/421597/147963303-a88f62b8-446c-42a2-aaff-e7718a79c5f0.png)


xdebug:
![rector-bug](https://user-images.githubusercontent.com/421597/147962883-f8dabaca-f9d3-4651-9d89-7fc65d48df62.png)


## Minimal PHP Code Causing Issue

**rector.php**
```php
<?php declare(strict_types=1);

use Rector\Laravel\Set\LaravelSetList;
use Rector\Core\Configuration\Option;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->import(LaravelSetList::LARAVEL_STATIC_TO_INJECTION);

    $parameters = $containerConfigurator->parameters();
    $parameters->set(Option::PATHS, [
        __DIR__ . '/routes/api.php',
    ]);
};
```
**routes/api.php**
```php
<?php

use Illuminate\Http\Request;

Route::middleware('something')->group(function () {
    Route::get('/some', 'SomeController@some');
    Route::get('/some/{id?}', 'SomeController@some');
});
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6907 Closes https://github.com/rectorphp/rector-src/pull/1618

### CODE REVIEW

**Comment by samsonasik** [comment]
Checking current stmts seems remove use statement:

```diff
1) Rector\Core\Tests\Issues\PrintStmtsIndex\PrintStmtsIndexTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
tests/Issues/PrintStmtsIndex/Fixture/fixture.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 <?php
 
-use Illuminate\Http\Request;
-
```

which should not.

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by gander** [comment]
I don't know what's going on in the code here. The new one looks like the old one.

**Comment by samsonasik** [comment]
@gander I updated the fixture to show the changed `Request` to `\Illuminate\Http\Request` https://github.com/rectorphp/rector-src/pull/1619/commits/0b9a68267f70db2664eb10f4cd83d7624e89702d

**Comment by samsonasik** [comment]
The configured config : 

```php
   $services->set(RenameClassRector::class)
        ->configure([
            'Request' => 'Illuminate\Http\Request',
        ]);
```

applied succesfully, but it still removes the use statement, which should not.

**Comment by samsonasik** [comment]
@gander I updated fixture config to show it change `Route` to `\Illuminate\Support\Facades\Route` as well https://github.com/rectorphp/rector-src/pull/1619/commits/29905df66423bb9a0778561b953a796c582266a3

**Comment by gander** [comment]
The code originally had unused `use`:
```php
use Illuminate\Http\Request;
```
and it was removed during the `process`, so there was no element with index `0`. I don't know if adding a use of this class will break the initialization code for this error?

**Comment by samsonasik** [comment]
I added fixtures for auto import enabled https://github.com/rectorphp/rector-src/pull/1619/commits/d6b626673e1a17f0196c1115b790bbd0522e4761 seems will make issue : 

```diff
1) Rector\Core\Tests\Issues\PrintStmtsIndexAutoImport\PrintStmtsIndexAutoImportTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
tests/Issues/PrintStmtsIndexAutoImport/Fixture/fixture_request_call.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 <?php
 
 use Illuminate\Support\Facades\Route;
-use Illuminate\Http\Request;
```

**Comment by samsonasik** [comment]
rolling back `FormatPerservingPrinter`, it possibly the change should be in `RenameClassRector`

**Comment by samsonasik** [comment]
Fixed 🎉 with ensure use name has `\` for short name use compare check https://github.com/rectorphp/rector-src/pull/1619/commits/6fd270ee69d9980276bcb00eea73abb87e614caa

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you, let's ship it

**Pull request merged**
