### PR TITLE
Add failing test fixture for ReturnTypeDeclarationRector

### PR DESCRIPTION
**Pull request by rodion-k**
# Failing Test for ReturnTypeDeclarationRector

Based on https://getrector.org/demo/a97ca4ba-526f-4d02-8e5c-c13cc7a82171

### CODE REVIEW

**Comment by samsonasik** [comment]
That's won't work since you define `@template T` at different class, even on phpstan.org demo 

https://phpstan.org/r/01f63b30-cd96-4f8a-b1e7-7afb8550e13a

For `@return TypedResponse<string>`, iirc, that's seems not supported yet.

**Comment by rodion-k** [comment]
Hi @samsonasik, thanks for the reply. For example, in [this case](https://getrector.org/demo/699aa2d0-e94e-407f-9865-711280dd0146), there is a generic type in the return type hint (in this case string). This makes me think that Rector knows the generic type, but ignores it in the first case.

**Comment by rodion-k** [comment]
Here is the case where you can see that phpstan knows the exact type. https://phpstan.org/r/0efd6b5f-cb60-41f5-8254-62628915f41d

**Comment by samsonasik** [comment]
`ReturnTypeDeclarationRector` purpose is to not add `@return` docblock, so the `@return` won't be added, different new rule for it may be needed.

**Comment by rodion-k** [comment]
> `ReturnTypeDeclarationRector` purpose is to not add `@return` docblock, so the `@return` won't be added, different new rule for it may be needed.

But in [this case](https://getrector.org/demo/699aa2d0-e94e-407f-9865-711280dd0146), `@return` docblock is added. What is the difference?

**Comment by samsonasik** [comment]
That's by  `AddArrayReturnDocTypeRector` see the Applied Rules part.

**Comment by rodion-k** [comment]
I see, I will try to implement the new rule using the `AddArrayReturnDocTypeRector` example.

**Comment by TomasVotruba** [comment]
Closing for lack of feedback last 3 months. Feel free to resend the test and fix to right location :+1:

**Pull request closed without merging**
