### PR TITLE
[DowngradePhp72] Allow empty config on DowngradeParameterTypeWideningRector

### PR DESCRIPTION
**Pull request by samsonasik**
- when no config, the safe type means false, which means it will be processed, per default config registered downgrade

https://github.com/rectorphp/rector-src/blob/b4fabbdebade5440ab2cc505426cd1d52cb446fc/config/set/downgrade-php72.php#L19

- the constant `UNSAFE_TYPES_TO_METHODS` is not needed as no other constant for compare, direct config in configure() should be ok: 

```php
    $services->set(DowngradeParameterTypeWideningRector::class)
        ->configure([
                ContainerInterface::class => ['set', 'get', 'has', 'initialized'],
                SomeContainerInterface::class => ['set', 'has'],
        ]);
```

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I added back fixtures that were removed at https://github.com/rectorphp/rector-src/commit/b4fabbdebade5440ab2cc505426cd1d52cb446fc so it make sense.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you

**Comment by samsonasik** [comment]
I am merging it ;)

**Pull request merged**
