### PR TITLE
[TypeDeclaration] Add return static property support on ReturnTypeFromStrictTypedPropertyRector

### LINKED ISSUE #8217: Infer return type based on static native type
# Feature Request

one of the rectors out of `SetList::TYPE_DECLARATION` should infer a native return type based on the static native type

https://getrector.com/demo/742d40d3-b05e-4d6e-ab2e-5658570bfef4

### PR DESCRIPTION
**Pull request by samsonasik**
Closes https://github.com/rectorphp/rector/issues/8217

### CODE REVIEW

**Comment by samsonasik** [comment]
implemented 🎉 /cc @staabm

**Comment by samsonasik** [comment]
Github action seems has pending commit :)

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by staabm** [comment]
ohh nice, that was fast. thank you 🙏

**Pull request merged**
