### PR TITLE
[Php81] NullToStrictStringFuncCallArgRector - Register more function

### PR DESCRIPTION
**Pull request by hungtrinh**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the feature.
What is the added value of per-function fixture files? It seems the name matching functions is always the same.

Could you keep just one?

**Comment by hungtrinh** [comment]
If keep just one, i think we can remove all fixture `non_string_param_type_2_*` in this PR  , `non string param type` case covered by https://github.com/rectorphp/rector-src/blob/main/rules-tests/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector/Fixture/non_string_param_type.php.inc

What is the added value of per-function fixture files? 
that to make sure each function in this list `ARG_POSITION_NAME_NULL_TO_STRICT_STRING ` covered by test `non_string_param_type_2_*` without throw exception  https://github.com/rectorphp/rector-src/blob/992d1efc7596864c960b3a9837ebf8ee04eb159d/rules/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector.php#L42-L49 

In the future if somebody add `'strtr' => ['string']` into `ARG_POSITION_NAME_NULL_TO_STRICT_STRING ` without test fixture `non_string_param_type_2_strtr.php.inc` => unit test pass but actual when run this rules in prod will raise exception 

`1) Rector\Tests\Php81\Rector\FuncCall\NullToStrictStringFuncCallArgRector\NullToStrictStringFuncCallArgRectorTest::test with data set #165 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
PHPStan\ShouldNotHappenException: Multiple variants - use selectFromArgs() instead.

phar:///Users/trinhhung/Projects/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ParametersAcceptorSelector.php:45
/Users/trinhhung/Projects/rector-src/rules/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector.php:474
/Users/trinhhung/Projects/rector-src/rules/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector.php:335
/Users/trinhhung/Projects/rector-src/src/Rector/AbstractRector.php:218
/Users/trinhhung/Projects/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:123
/Users/trinhhung/Projects/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:223
/Users/trinhhung/Projects/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:114
/Users/trinhhung/Projects/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:223
/Users/trinhhung/Projects/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:114
/Users/trinhhung/Projects/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:223
/Users/trinhhung/Projects/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:114
/Users/trinhhung/Projects/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:223
/Users/trinhhung/Projects/rector-src/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:91
/Users/trinhhung/Projects/rector-src/src/PhpParser/NodeTraverser/RectorNodeTraverser.php:33
/Users/trinhhung/Projects/rector-src/src/Application/FileProcessor.php:42
/Users/trinhhung/Projects/rector-src/src/Application/FileProcessor/PhpFileProcessor.php:103
/Users/trinhhung/Projects/rector-src/src/Application/FileProcessor/PhpFileProcessor.php:62
/Users/trinhhung/Projects/rector-src/src/Application/ApplicationFileProcessor.php:130
/Users/trinhhung/Projects/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:177
/Users/trinhhung/Projects/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:131
/Users/trinhhung/Projects/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:115
/Users/trinhhung/Projects/rector-src/rules-tests/Php81/Rector/FuncCall/NullToStrictStringFuncCallArgRector/NullToStrictStringFuncCallArgRectorTest.php:18`

https://www.php.net/manual/en/function.strtr

**Comment by TomasVotruba** [comment]
> If keep just one, i think we can remove all fixture 

Please go for it 👍 

The reason is tests should cover edge cases, e.g. one with position of 1, other with 0. Every other is just duplicate that makes them harder to read.

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
