### PR TITLE
Fix wrong copy paste define-constant test

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Btw, the /e2e tests should not run in the `rector/rector-src` repository. Now there are still here:

image

**Comment by samsonasik** [comment]
Ok, I think we can move to rector/rector 👍 , after we solve the bootstrapping issue

**Comment by TomasVotruba** [comment]
e2e test are for prefixed and compiled Rector, they do not test anything here.

**Comment by samsonasik** [comment]
we have e2e tests in rector-src to test diff on various tests, eg:

https://github.com/rectorphp/rector-src/blob/012e9ad5531af7165ebf21ad5027d78530d20a8d/e2e/e2eTestRunner.php#L51

**Comment by samsonasik** [comment]
For example, we test diff:

https://github.com/rectorphp/rector-src/blob/012e9ad5531af7165ebf21ad5027d78530d20a8d/e2e/applied-rule-change-docblock/expected-output.diff#L1-L40

so I think these e2e tests are needed in rector-src

**Comment by TomasVotruba** [comment]
Yea, I've checked yestereday they're testing something else. I'm sorry about the confusion, they're all right :+1:

**Pull request merged**
