### PR TITLE
[Renaming] Skip rename Name when parent is Namespace_ equal to target name on RenameClassRector

### PR DESCRIPTION
**Pull request by samsonasik**
Closes https://github.com/rectorphp/rector-src/pull/939

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
@vukanac this seems different behaviour with your test case on your other PR https://github.com/rectorphp/rector-src/pull/940 ? or do you prefer implementation of https://github.com/rectorphp/rector-src/pull/940 test ?

**Comment by vukanac** [comment]
I posted 2 test cases today for different Rector, one for each:

* _renaming classes_
* _renaming namespaces_

They look related, but I would say they are not.
I can provide you more details if needed.

**Comment by samsonasik** [comment]
Ok, so the "same namespace" from old to new changed need to be checked

**Comment by samsonasik** [comment]
I've updated handling to ensure target namespace is not equal with current namespace if the node parent that want to be changed is namespace https://github.com/rectorphp/rector-src/pull/942/commits/85a43d9c776036b82a865f18b25bc778125f67e0

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
I am merging it ;)

**Pull request merged**
