### PR TITLE
[Naming] Skip used by trait on RenamePropertyToMatchTypeRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
<?php

namespace Rector\Tests\Naming\Rector\Class_\RenamePropertyToMatchTypeRector\Fixture;

use Rector\Tests\Naming\Rector\Class_\RenamePropertyToMatchTypeRector\Source\EliteManager;
use Rector\Tests\Naming\Rector\Class_\RenamePropertyToMatchTypeRector\Source\UseEliteManagerTrait;

class SkipUsedByTrait
{
    use UseEliteManagerTrait;

    /**
     * @var EliteManager
     */
    private $eventManager;

    public function __construct(EliteManager $eventManager)
    {
        $this->eventManager = $eventManager;
    }
}
```

which class uses a trait that consume the property:

```php
<?php

declare(strict_types=1);

namespace Rector\Tests\Naming\Rector\Class_\RenamePropertyToMatchTypeRector\Source;

trait UseEliteManagerTrait
{
    public function trigger($name)
    {
        $this->eventManager->trigger($name);
    }
}
```

should be skipped.

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
I moved used by trait check to PropertyManipulator service for re-use the service.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
