### PR TITLE
tv debug downgrade

### PR DESCRIPTION
**Pull request by TomasVotruba**
- remove unused fixture source class
- remove update config, now we are on 11 together
- fix DowngradeParameterTypeWideningRector for missing parent parameter

### CODE REVIEW

**Comment by TomasVotruba** [comment]
cc @samsonasik FIY, I'm working on a fix for DowngradeParameterTypeWideningRector that is causing the fail on current rector/rector. Since we moved from `NodeRepository` to static reflection, there are some new bugs that needs to be fix.

**Comment by samsonasik** [comment]
@TomasVotruba thank you 👍

**Comment by samsonasik** [comment]
@TomasVotruba current build now got error when run downgrade: 

```bash
bin/rector process --dry-run src/Configuration/ConfigurationFactory.php -c build/config/config-downgrade.php --clear-cache
 0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%PHP Warning:  Undefined array key 2 in /Users/samsonasik/www/rector-src/rules/DowngradePhp80/Rector/MethodCall/DowngradeNamedArgumentRector.php on line 191
Warning: Undefined array key 2 in /Users/samsonasik/www/rector-src/rules/DowngradePhp80/Rector/MethodCall/DowngradeNamedArgumentRector.php on line 191
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 ```

**Comment by TomasVotruba** [comment]
@samsonasik I'll check it, thanks for exact location! :+1: 

I wish PHP would throw fatal error on undefined key index in array :/

**Comment by TomasVotruba** [comment]
This was split into few more smaller PRs

**Pull request closed without merging**
