### PR TITLE
Try pin PHPStan 1.7.1

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba @Wirone let's give it a try.

### CODE REVIEW

**Comment by samsonasik** [comment]
it seems still error:

```

2s
Run ../../bin/rector process --dry-run --ansi
  

                                                                                
 [ERROR] Could not process some files, due to:                                  
         "Child process error: PHP Fatal error:  Class 'ReflectionUnionType' not
         found in                                                               
         phar:///home/runner/work/rector/rector/vendor/phpstan/phpstan/phpstan.p
         har/vendor/ondrejmirtes/better-reflection/src/Reflection/Adapter/Reflec
         tionUnionType.php:12                                                   
         Fatal error: Class 'ReflectionUnionType' not found in                  
         phar:///home/runner/work/rector/rector/vendor/phpstan/phpstan/phpstan.p
         har/vendor/ondrejmirtes/better-reflection/src/Reflection/Adapter/Reflec
         tionUnionType.php:12                                                   
         ".             
```

https://github.com/rectorphp/rector/runs/6629500164?check_suite_focus=true

**Comment by samsonasik** [comment]
I tried locally, the bootstrap seems working ok, I will check on upstream ci4-album

**Comment by samsonasik** [comment]
Just re-check locally and it still error:

```bash
/opt/homebrew/Cellar/php@7.4/7.4.29/bin/php vendor/bin/rector --dry-run --clear-cache
 46/46 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
                                                                                                                        
 [ERROR] Could not process "test/Database/Infrastructure/Persistence/Track/SQLTrackRepositoryTest.php" file, due to:    
         "System error: "Class 'ReflectionUnionType' not found"                                                         
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
         line: 12                                                                                                       
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "test/Database/Infrastructure/Persistence/Album/SQLAlbumRepositoryTest.php" file, due to:    
         "System error: "Class 'ReflectionUnionType' not found"                                                         
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
         line: 12                                                                                                       
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process                                                                                              
         "test/Database/Infrastructure/Persistence/AlbumTrackSummary/SQLAlbumTrackSummaryRepositoryTest.php" file, due  
         to:                                                                                                            
         "System error: "Class 'ReflectionUnionType' not found"                                                         
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
         line: 12                                                                                                       
                                                       
```

**Comment by samsonasik** [comment]
it seems the bootstrap actually loaded, but too late.

**Comment by samsonasik** [comment]
it seems sometime working sometime not, which possibly a cache issue on early access.

**Comment by stof** [comment]
This pinning prevents installing rector when using the latest release of phpstan.

**Comment by samsonasik** [comment]
we are aware of it, and looking at it https://github.com/rectorphp/rector/issues/7191

**Comment by Wirone** [comment]
And this is exactly why I [said](https://github.com/rectorphp/rector/issues/6709#issuecomment-1117325856) that PHPStan should be prefixed in Rector, to not block usage of the latest version from static analysis perspective while maintaining latest _working_ version inside Rector 😉

**Pull request merged**
