### PR TITLE
Require-dev phpstan/phpstan-deprecation-rules to show list of deprecated

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://github.com/rectorphp/rector/issues/8815#issuecomment-2467753857

### CODE REVIEW

**Comment by samsonasik** [comment]
I am going to current change to `->is*` to separate PR since some check, like ObjectType needs special handling to verify

**Comment by samsonasik** [comment]
For PHPStan constant and get value, to ensure next `->getValue()` is detected, it needs check with get`$exprType->getConstantStrings()`:

```diff
-use PHPStan\Type\Constant\ConstantStringType;
 use PHPStan\Type\Generic\GenericClassStringType;
 use PHPStan\Type\ObjectType;
 use PHPStan\Type\StringType;
@@ -198,9 +197,11 @@ CODE_SAMPLE
             return $exprType->getGenericType();
         }
 
-        if ($exprType instanceof ConstantStringType) {
-            if ($this->reflectionProvider->hasClass($exprType->getValue())) {
-                return new ObjectType($exprType->getValue());
+        $constantStrings = $exprType->getConstantStrings();
+        if (count($constantStrings) === 1) {
+            $value = $constantStrings[0]->getValue();
+            if ($this->reflectionProvider->hasClass($value)) {
+                return new ObjectType($value);
             }
```

but that repetitive seems require special service to resolve it, to ease replace when there is regression and possibly multiple values usage, similar with what `PHPStan\\Type\\TypeWithClassName` over `getObjectClassNames()`, which probably have multiple values in it.

 I will create a service for that, and use each PR for it.

**Comment by samsonasik** [comment]
@TomasVotruba per your suggestion at https://github.com/rectorphp/rector-src/pull/6423#issuecomment-2470647123

I ignored deprecated notice of type instanceof check https://github.com/rectorphp/rector-src/pull/6415/commits/94ba30691a7488b5d6d12c4ffbd183347c29656d

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for merge 👍

**Comment by TomasVotruba** [comment]
Awesome, let's move on :+1:

**Pull request merged**
