### PR TITLE
[Core] Add $seconds, $maxNumberOfProcess, and $jobSize parameters to RectorConfig::parallel() method

### PR DESCRIPTION
**Pull request by samsonasik**
to handle use Option directly to increase parallel timeout like this https://github.com/codeigniter4/CodeIgniter4/pull/5931/commits/346c83ff7693520be63d5293e978645c571461fc#diff-d933a2ad57daa43419b483d3f1ddedaec7aa44933007fead9f9437390f596f4a

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I was thinking about that, but it might be more easier to find this under parallel() method. We needed this on previous parameters approach, but it was not possible.

Could you move it to parallel() method with optional params? Same for the other parallel parameter

**Comment by samsonasik** [comment]
I've moved to `parallel()` method.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
I've added more params for parallel job size and parallel max number of process, place in 2nd and 3rd param as most of the time, the changed part is the $second parameter.

**Review by TomasVotruba — APPROVED** [review]

**Pull request merged**
