### PR TITLE
[Php73] Skip JsonThrowOnErrorRector on passed exact value

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
function skipExactValue(){
    $jsonData = [
        'validation_messages' =>
        [
            'foo' => [
                'regexNotMatch' => 'The input does not match against pattern \'/^[a-zA-Z0-9 .\-]+$/\''
            ]
        ],
        'type' => 'http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html',
        'title' => 'Unprocessable Entity',
        'status' => 422,
        'detail' => 'Failed Validation'
    ];

    $response = json_encode($jsonData);
    assert(is_string($response));
}

function skipExactValue2(){
    $json = '{}';

    $response = json_decode($json);
    assert(is_array($response));
}
```

the `JSON_THROW_ON_ERROR` seems unneded, it mostly used on tests for testing exact value with the class that uses it. 

I think it will only make sense to pass consist of variable.

### CODE REVIEW

**Comment by samsonasik** [comment]
It seems it will cause mixed content:

```php
function processMixedContent(array $message, int $code, string $detail)
{
    $jsonData = [
        'validation_messages' => $message,
        'type' => 'http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html',
        'title' => 'Unprocessable Entity',
        'status' => $code,
        'detail' => $detail,
    ];

    $response = json_encode($jsonData);
}
```

not processed, closing for now.

**Comment by samsonasik** [comment]
Re-open, update `ValueResolver` to returns null when ConstantArrayType not sure about the value https://github.com/rectorphp/rector-src/pull/1051/commits/04342c1de0d0acf7dc59a23d7b1cc3d8e1a88016#diff-e8d39b18c808064651946f5daf0d52d8bdc6b67a6fbe165c466f5d6c24b9c894 for mixed data array:

```php
function processMixedContent(array $message, int $code, string $detail)
{
    $jsonData = [
        'validation_messages' => $message,
        'type' => 'http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html',
        'title' => 'Unprocessable Entity',
        'status' => $code,
        'detail' => $detail,
    ];

    $response = json_encode($jsonData);
}
```

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
