### PR TITLE
 [Dep] Update vendor patches files to vendor-patches repo path 

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba using raw url vendor-patches seems got error:

```bash
 patches/symfony-dependency-injection-loader-configurator-servicesconfigurator-php.patch (0)
   Could not apply patch! Skipping. The error was: The "patches/symfony-dependency-injection-loader-configurator-servicesconfigurator-php.patch" file could not be downloaded: Failed to open stream: No such file or directory

```

**Comment by samsonasik** [comment]
@TomasVotruba using patches-file to point to json seems still not working, this is strange as the not working part is the `symfony/dependency-injection` part only

**Comment by samsonasik** [comment]
I tried both config:

```javascript
{
	"patches": {
		"symfony/dependency-injection": [
			"https://raw.githubusercontent.com/rectorphp/vendor-patches/master/symfony-dependency-injection-loader-configurator-servicesconfigurator-php.patch"
		],
		"danielstjules/stringy": [
			"https://raw.githubusercontent.com/rectorphp/vendor-patches/master/danielstjules-stringy-src-stringy-php.patch"
		]
	}
}
```

or 

```javascript
{
    "patches": {
        "symfony/dependency-injection": {
            "symfony dependency injection": "https://raw.githubusercontent.com/rectorphp/vendor-patches/master/symfony-dependency-injection-loader-configurator-servicesconfigurator-php.patch"
        },
        "danielstjules/stringy": {
            "danielstjules stringy": "https://raw.githubusercontent.com/rectorphp/vendor-patches/master/danielstjules-stringy-src-stringy-php.patch"
        }
    }
}
```

both not working

**Comment by samsonasik** [comment]
@TomasVotruba the `symfony-dependency-injection-loader-configurator-servicesconfigurator-php.patch` somehow load different file, as `patches` directory no longer exists, but still pointed to the file, it maybe because of the `vendor/rector-*` still looking for `patches` directory ?

**Comment by samsonasik** [comment]
@TomasVotruba the solution seems keep patches/symfony-dependency-injection-loader-configurator-serviceconfigurator-php.patch until all dependencies resolved and tagged to the patches-file URL, with keep the file, it currently shows on composer update:

```bash
  - Applying patches for symfony/dependency-injection
    patches/symfony-dependency-injection-loader-configurator-servicesconfigurator-php.patch (0)

  - Applying patches for danielstjules/stringy
    https://raw.githubusercontent.com/rectorphp/vendor-patches/master/danielstjules-stringy-src-stringy-php.patch (0)
```

which it pointed to `patches` directory still.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

We seems need to update `rector-symfony/laravel/` etc and https://github.com/sabbelasichon/typo3-rector dependencies to use  `vendor-patches` apply with patches-file URL first, tag them, then we can completely remove `patches` directory.

**Comment by TomasVotruba** [comment]
Thank you :+1: 

What was the secret to success solution? Just so I know what to do next time :)

**Comment by samsonasik** [comment]
We currently still have 1 left `patches` file 

https://github.com/rectorphp/rector-src/tree/main/patches

as we have packages like `rector-laravel`, `rector-symfony`, etc which still uses `patches` pointed directory for usage of `vendor-patches`, so it seems still looking for `patches` directory ,which is a file `patches/symfony-dependency-injection-loader-configurator-servicesconfigurator-php.patch`

the `danielstjules/stringy` patch file seems working with `patches-file` URL because the packages like `rector-laravel`, `rector-symfony` doesn't have new release that uses it yet.

So, the `patches/symfony-dependency-injection-loader-configurator-servicesconfigurator-php.patch` will still needed until all packages in vendor which uses `vendor-patches` pointed to new `patches-file` config URL.

**Comment by TomasVotruba** [comment]
I see. So we need to migrate all repositories to single shared solution, then it will work as expected.

Thanks for exploring all these options :+1:

**Comment by samsonasik** [comment]
Oh, it seems latest build got error https://github.com/rectorphp/rector-src/runs/4436090270?check_suite_focus=true#step:5:417

```bash
 - Applying patches for danielstjules/stringy
    patches/danielstjules-stringy-src-stringy-php.patch (0)
   Could not apply patch! Skipping. The error was: The "patches/danielstjules-stringy-src-stringy-php.patch" file could not be downloaded: Failed to open stream: No such file or directory
```

it seems `patches/danielstjules-stringy-src-stringy-php.patch` needs to be added back until all packages deps apply with url patches.

**Comment by samsonasik** [comment]
oh, it seems because of tagged rector-symfony, while it not yet updated with vendor patch URL https://github.com/rectorphp/rector-symfony/commit/1c76befd5a64d57bd0732aad989b06fd3ed3cb33

**Pull request merged**
