### PR TITLE
Add test case for caching $rectorConfig->rules() changed

### PR DESCRIPTION
**Pull request by samsonasik**
Based on your PR:

- https://github.com/rectorphp/rector-src/pull/4902

this is failing test case that rules should be changed the hash insteaf of equal

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba I debugged `SimpleParameterProvider::hash()`, the `self::$parameters` is empty arrray.

**Comment by samsonasik** [comment]
@TomasVotruba using `AbstractLazyTestCase` seems got non-empty array, but still equal...

**Comment by samsonasik** [comment]
@TomasVotruba @staabm I got test case working ok now, ready for merge 👍

**Review by TomasVotruba — APPROVED** [review]
Thank you, go for merge when ready 👍

**Pull request merged**
