### PR TITLE
[AutoImport][Php70] Keep FQCN on conflict last name on TernaryToNullCoalescingRector

### LINKED ISSUE #8309: Incorrect behavior of TernaryToNullCoalescingRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/6129e6f8-3726-4d26-b961-306b42af6be6

```php
<?php

use shop\product\business\ProductFilter;

class ProductController
{
    private function sharedProductFilter(): void
    {
        $page = isset($_REQUEST['page']) ? $_REQUEST['page'] : 1;

        $this->brands = Hersteller::getListForProducts(new \ProductFilter());
    }

}
```

### Responsible rules

* `TernaryToNullCoalescingRector`

## Expected Behavior

the fqcn should not be modified, since it after the change collides with a same named class already imported

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8309

### CODE REVIEW

**Comment by samsonasik** [comment]
The issue seems only on no namespaced code, I added both namespaced and no namespaced fixture.

**Comment by samsonasik** [comment]
@staabm the issue seems happen on static call:

```php
Hersteller::getListForProducts(new \ProductFilter());
```

see https://getrector.com/demo/6129e6f8-3726-4d26-b961-306b42af6be6

when only use:

```php
new \ProductFilter();
```

it seems working ok https://getrector.com/demo/813692b7-8f7a-49ea-9d55-fd1750e24573

so, the namespaced name somehow overlap under static call

**Comment by samsonasik** [comment]
Finally fixed 🎉 /cc @staabm

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it to have faster feedback to test ;)

**Comment by samsonasik** [comment]
@staabm please try latest rector/rector:dev-main and verify if it working ok now :)

**Comment by staabm** [comment]
@samsonasik verified locally. looks great - I cannot reproduce the issue in our project anymore.

thank you

**Comment by staabm** [comment]
may I ask for another bugfix release? :)

**Comment by samsonasik** [comment]
@staabm sure :+1: , I just tagged 0.18.9

- https://github.com/rectorphp/rector-src/releases/tag/0.18.9
- https://github.com/rectorphp/rector/releases/tag/0.18.9

**Comment by samsonasik** [comment]
@staabm this will cause another bug on renaming FQN-ize name from no-namespace to namespace while auto import, see

- https://github.com/rectorphp/rector-src/pull/5256

I will look into the fix :)

**Pull request merged**
