### PR TITLE
[TypeDeclaration] Only apply false type on php 8.2+ configured on TypedPropertyFromAssignsRector

### LINKED ISSUE #7809: Incorrect behavior of TypedPropertyFromAssignsRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/73c31adc-d79d-4f13-addc-56997d5b749a

```php
<?php

final class DemoFile
{
    /**
     * @var bool
     *
     * @ORM\Column(name="requires_signup", type="boolean")
     * @Groups("agenda:export")
     */
    private $requiresSignup = false;
}
```

### Responsible rules

* `TypedPropertyFromAssignsRector`

## Expected Behavior

I believe Rector should rather set type to bool following the @var (and ORM) definition. Instead it sets it to false type.

### PR DESCRIPTION
**Pull request by samsonasik**
It currently apply `false` type on php <8.2, which should only apply when configured on php 8.2+ only, ref https://getrector.com/demo/2b9d1a69-3d9d-4293-8a3d-c93f47560bf0

Fixes https://github.com/rectorphp/rector/issues/7809

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @koko236

**Comment by samsonasik** [comment]
It seems cause error on pseudo false type test on union:

```diff
There was 1 failure:

1) Rector\Tests\Php80\Rector\FunctionLike\UnionTypesRector\UnionTypesRectorTest::test with data set #20
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 
 final class FalsePseudoType
 {
-    public function go($value): false|int
+    public function go($value): bool|int
     {
         return (int) $value ?? false;
```

which allowed on php < 8.2

**Comment by samsonasik** [comment]
Fixed with handle on `UnionTypeMapper` https://github.com/rectorphp/rector-src/pull/3422/commits/05f73b976d1cede9cc58f8e9ebf3db87ebc90281

**Comment by samsonasik** [comment]
Finally 🎉 🎉 🎉 , All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
Rebased.

**Comment by TomasVotruba** [comment]
I think there is some memory leak in paratest

**Comment by samsonasik** [comment]
Yes, seems happened this week. I restart the build, we can back to original phpunit if it keep happening.

**Comment by samsonasik** [comment]
Let's back to phpunit https://github.com/rectorphp/rector-src/pull/3422/commits/c282e627b9ca4228977dabcd5c2019e47e7d19d0

**Comment by TomasVotruba** [comment]
Feel free to merge when ready :+1:

**Pull request merged**
