### PR TITLE
Remove unused RectorServiceConfigurator, use RectorConfig instead

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@samsonasik Any ideas how to solve this? The `RectorServiceConfigurator` is no longer needed, but it still affects the rest of the code.

**Comment by samsonasik** [comment]
The `Symfony\Component\DependencyInjection\Loader\Configurator\ServicesConfigurator` probably need to be aliased into `Rector\Config\RectorConfig`

**Comment by samsonasik** [comment]
@TomasVotruba it seems `RectorServiceConfigurator` return still in vendor under:

- vendor/symfony/dependency-injection/Loader/Configurator/ServicesConfigurator.php

**Comment by samsonasik** [comment]
@TomasVotruba it still in vendor:

https://raw.githubusercontent.com/rectorphp/vendor-patches/main/patches/symfony-dependency-injection.patch

to be:

```diff

-    final public function set(?string $id, string $class = null): ServiceConfigurator
+    public function set(?string $id, string $class = null): \Rector\Core\DependencyInjection\Loader\Configurator\RectorServiceConfigurator
     {
         $defaults = $this->defaults;
         $definition = new Definition();
@@ -91,7 +91,7 @@
         $definition->setBindings(unserialize(serialize($defaults->getBindings())));
         $definition->setChanges([]);

-        $configurator = new ServiceConfigurator($this->container, $this->instanceof, true, $this, $definition, $id, $defaults->getTags(), $this->path);
+        $configurator = new \Rector\Core\DependencyInjection\Loader\Configurator\RectorServiceConfigurator($this->container, $this->instanceof, true, $this, $definition, $id, $defaults->getTags(), $this->path);
```

**Comment by TomasVotruba** [comment]
@samsonasik Oh, I removed the wrong patch file :D  thanks for checking. I think it's near now

**Comment by TomasVotruba** [comment]
The packages needs the patch to be coming from main, so the merge is needed

**Pull request merged**
