### PR TITLE
[Php80] Narrow bool|false to bool on UnionTypesRector

### LINKED ISSUE #7821: UnionTypesRector creates bool|false
1. Redundant types are not allowed
2. False as a standalone type is allowed only in php8.2, but I'm using LevelSetList::UP_TO_PHP_81

@@ @@
      * @param bool|FALSE $user_id
      * @return array
      */
-    public function build_acl(bool $user_id = FALSE)
+    public function build_acl(bool|false $user_id = FALSE)

Applied rules:
 * UnionTypesRector

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7821
Ref https://3v4l.org/4ZqL9

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed :tada: /cc @eugeniya-v

**Comment by samsonasik** [comment]
It somehow cause error on `DowngradeMatchToSwitchRectorTest`

https://github.com/rectorphp/rector-src/actions/runs/4374536269/jobs/7654085435

I will check more.

**Comment by samsonasik** [comment]
Finally 🎉 All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by samsonasik** [comment]
It somehow cause error on downgrade on tracy:

https://github.com/rectorphp/rector-src/actions/runs/4375224842/jobs/7655667800#step:15:70

I will check it.

**Comment by samsonasik** [comment]
https://github.com/rectorphp/rector-src/pull/3469

**Pull request merged**
