### PR TITLE
[Core] Refactor InfiniteLoopValidator

### PR DESCRIPTION
**Pull request by samsonasik**
- Refactor InfiniteLoopValidator with new behaviour to verify with check `process` to `isValid`

```diff
-    public function process(Node $node, Node $originalNode, string $rectorClass): void
+    public function isValid(Node|array $node, Node $originalNode, string $rectorClass): bool
```

when valid, it will be processed, when invalid, it will be skipped an return null, it verify current rector class against created by rule applied already.

The test case is already in `tests/Issues/InfiniteLoop/InfiniteLoopTest.php`, The `Exception` is no longer thrown, as it return node that has changed early when found repetitive inside.

- Reduce `AbstractRector` line of codes.
- Remove `CreatedByRuleNodeVisitor` service.
- Remove `InfiniteLoopTraversingException`
- Clean up manual check `AttributeKey::CREATED_BY_RULE)` on rector rules

```diff
-        $createdByRule = $node->getAttribute(AttributeKey::CREATED_BY_RULE) ?? [];
-        if (in_array(self::class, $createdByRule, true)) {
-            return null;
-        }
```
- added more fixture tests for node already transformed check.

### CODE REVIEW

**Comment by samsonasik** [comment]
Github seems down now https://www.githubstatus.com/

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

Note: There is currently 1 left `AttributeKey::CREATED_BY_RULE` check on individual rule that still need to be checked manually, on `DowngradeArrayFilterNullableCallbackRector`, which the change is on `Node`'s Args, which somehow not mark Node as changed:

https://github.com/rectorphp/rector-src/blob/aa4f45484afe2fed465946957a1dec9c38655c6b/rules/DowngradePhp80/Rector/FuncCall/DowngradeArrayFilterNullableCallbackRector.php#L104-L107

https://github.com/rectorphp/rector-src/blob/aa4f45484afe2fed465946957a1dec9c38655c6b/rules/DowngradePhp80/Rector/FuncCall/DowngradeArrayFilterNullableCallbackRector.php#L111-L114

https://github.com/rectorphp/rector-src/blob/aa4f45484afe2fed465946957a1dec9c38655c6b/rules/DowngradePhp80/Rector/FuncCall/DowngradeArrayFilterNullableCallbackRector.php#L121-L124

**Comment by TomasVotruba** [comment]
Thanks for thorough cleanup 👍 

Feel free to merge when ready 👌

**Comment by samsonasik** [comment]
@TomasVotruba finally, manual check of `AttributeKey::CREATED_BY_RULE` can be cleaned up by check early before refactor 🎉🎉🎉 https://github.com/rectorphp/rector-src/pull/1771/commits/b053a9c216b3a30b78c93015a7471e1b81f7658a

**Pull request merged**
