### PR TITLE
Add failing test fixture for RemoveAlwaysTrueIfConditionRector

### PR DESCRIPTION
**Pull request by Bl00D4NGEL**
# Failing Test for RemoveAlwaysTrueIfConditionRector

Based on https://getrector.com/demo/dad09538-58a1-4b17-9364-0906d49d03fe

### CODE REVIEW

**Comment by samsonasik** [comment]
Could you move the other classes under `Source` to be consumed in the fixture ? https://github.com/rectorphp/rector-src/tree/main/rules-tests/DeadCode/Rector/If_/RemoveAlwaysTrueIfConditionRector/Source

**Comment by samsonasik** [comment]
`$fooBar` somehow detected as `NullType`, so it possibly bug on type mapper.

**Comment by samsonasik** [comment]
It seems happen on intersection and false type as well https://getrector.com/demo/59ad2690-af37-447b-b1de-f735bbb6496e

**Comment by Bl00D4NGEL** [comment]
I closed the [linked issue](https://github.com/rectorphp/rector/issues/7850) as this was "intended" behaviour. Closing this PR as well.

**Pull request closed without merging**
