### PR TITLE
[DowngradePhp82] Add DowngradeReadonlyClassRector to downgrade  readonly class

### PR DESCRIPTION
**Pull request by samsonasik**
Try `nikic/php-parser` dev-master to add `DowngradeReadonlyClassRector` to downgrade  readonly class.

### CODE REVIEW

**Comment by samsonasik** [comment]
Added tests under `test/Issues` to ensure no add-remove-add back readonly property when downgrade to php 8.0 that remove readonly on properties, while its rule add readonly on properties.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I updated nikic/php-parser to ^4.14.0

**Review by TomasVotruba — APPROVED** [review]

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
