### PR TITLE
Accept multiline code snippet

### PR DESCRIPTION
**Pull request by ghostwriter**
This patch provides the following changes:

`rector detect-node` 
 - accept multiline code snippet

`rector detect-node —loop`
 -  accept multiline code snippet
 -  stop reading user input after receiving an **end-of-transmission** control character (`Ctrl-D` on Unix systems or `Ctrl-Z` on Windows).
 -  type `"!q”` to quit

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I'll review this today :pray:

**Comment by TomasVotruba** [comment]
Hi, I'm checking the controlling keys and it's counter intuitive.
The enter does not invoke response, that must be kept as that's how users expect bash to work.

Saying that, this is a simple command that should not be turned into REPL. The goal is to get fast and clear feedback on a single-line input.

For more complex AST traverser we're preparing interactive form on Rector website. It will be designed to something you present, multiline input and ability to see full tree.

**Comment by ghostwriter** [comment]
Hey @TomasVotruba,
 
> Hi, I'm checking the controlling keys and it's counter intuitive. The enter does not invoke response, that must be kept as that's how users expect bash to work.

Agreed, used what was available.

> Saying that, this is a simple command that should not be turned into REPL. The goal is to get fast and clear feedback on a single-line input.

Agreed.

> For more complex AST traverser we're preparing interactive form on Rector website. It will be designed to something you present, multiline input and ability to see full tree.

Okay.

—

I agree with everything you said, and the interactive site sounds great.

However, while currently working on a custom extension ,

I have been using `rector detect-node` command with and without `—loop`

when you `copy & paste` any code with `\n` newline,

it executes multiple separate line (often with partial code; errors)

and or breaks out of the command line, (continuing to write/execute the rest of the  `copy & paste`ed code)

image

This patch fixed that issue.

—

With that said, you are welcome to close this,

I have a local branch with the changes i need. 👍🏾

**Comment by TomasVotruba** [comment]
I see. We're actually working on a tool that would able to handle this in online way, like our Rector demo.
That's where full files would go :) 

https://twitter.com/VotrubaT/status/1759354858610844137


I'll close this one then, thanks for understanding :+1:

**Pull request closed without merging**
