### PR TITLE
Add failing test fixture for OptionalParametersAfterRequiredRector

### PR DESCRIPTION
**Pull request by lptn**
# Failing Test for OptionalParametersAfterRequiredRector

Based on https://getrector.org/demo/a6d8e258-b7a4-4fdd-9901-929d7bbf1ad8

bug report: #6506

### CODE REVIEW

**Comment by TomasVotruba** [comment]
It should be located in the `/Fixture` directory. How did you create this PR?

**Comment by TomasVotruba** [comment]
The "Create PR" button goes to correct directory:

image

**Comment by samsonasik** [comment]
Fixed at https://github.com/rectorphp/rector-src/pull/248

**Comment by alies-dev** [comment]
@TomasVotruba 

>It should be located in the /Fixture directory. How did you create this PR?

sorry, probably I've accidentally removed "fixture" dir when was editing fixture’s filename

**Comment by TomasVotruba** [comment]
Maybe that's some Github glitch. If the file gets modified, it will remove the slash. I've seen this couple of times.

The url link from the demo page should include encoded slash, that might help. But this Github feature is very limited, so I might be wrong :)

**Pull request closed without merging**
