### PR TITLE
[Strict] Allow check '0' empty zero on BooleanInTernaryOperatorRuleFixerRector on string type

### LINKED ISSUE #8137: STRICT_BOOLEANS and handling of 0-strings
This is more of a question rather than bug report. All rectors in STRICT_BOOLEANS set treat a boolean condition with strings as if it was checking for an empty string only. The rectors completely ignore 0-strings (i.e. `'0'`). I was wondering if this is by design?

I noticed it says this rule is configurable. I believe it can be used like this:
```
    $rectorConfig->ruleWithConfiguration(BooleanInIfConditionRuleFixerRector::class, [
        BooleanInIfConditionRuleFixerRector::TREAT_AS_NON_EMPTY => true,
    ]);
```

but I didn't notice any difference in output. 

I assume it's by design. Most often than not, people are unaware of the 0-strings and loose checking of strings leads to bugs. But this means that these rectors create a BC in code that may also go unnoticed by developers using them. 
----

Here's an example of what I mean:
```diff
- if ($str) { }
+ if ($str !== '') { }
```
instead of this

```diff
- if ($str) { }
+ if ($str !== '' && $str !== '0') { }
```

### PR DESCRIPTION
**Pull request by samsonasik**
@staabm  @TomasVotruba continue of PR:

- https://github.com/rectorphp/rector-src/pull/5296

this apply on only string type.

Fixes https://github.com/rectorphp/rector/issues/8137

### CODE REVIEW

**Comment by samsonasik** [comment]
see https://3v4l.org/JraQb

**Comment by TomasVotruba** [comment]
I see, looks good to me :+1:  Can you finish and merge this one?

**Comment by samsonasik** [comment]
I will try

**Comment by samsonasik** [comment]
@staabm @kamil-tekiela @TomasVotruba Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Pull request merged**
