### PR TITLE
[Scoped] Clean up bootstrap.php to load scoper autoload

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba @ondrejmirtes this PR cleanup bootstrap.php from scoped version of rector. In `rector.php`, I modified the sort autoload as follow:

1. Include preload.php and constant first for PHP-Parser Node definitions and internal PHP constants.
2. project autoload 
3. prefixed autoload
4. global autoload
5. command line autoload

prefixed autoload is included in bootstrap.php

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by ondrejmirtes** [comment]
I don’t understand how can this work if there’s no autoload section in the target repository composer.json. How do I autoload Rector classes for example when running unit tests of custom Rectors or when analysing custom Rectors with PHPStan?

**Comment by samsonasik** [comment]
@ondrejmirtes how about the `bootstrap.php` exists, but changed with:

```php
# ensure only loaded once
require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/vendor/scoper-autoload.php';
```

**Comment by samsonasik** [comment]
@ondrejmirtes I rolled back `bootstrap.php`, with updated to load prefixed `vendor/autoload.php` and `vendor/scoper-autoload.php`, do you think that will works?

**Comment by samsonasik** [comment]
Ok, with above change, and running scoper script and it cause error in my local dev:

```

verify scoped rector with specify PHP72_BIN_PATH env

                                                                                                                        
 [ERROR] Class 'Symplify\SmartFileSystem\SmartFileInfo' not found                                                       
                                                                                                                        
```

**Comment by samsonasik** [comment]
It seems broke the scoper when I run the full_build.sh, I am closing for now.

@ondrejmirtes feel free to create separate PR if you have better solution. To verify locally for updated code, you can run the following script:

```
export PHP72_BIN_PATH=/opt/homebrew/Cellar/php@7.2/7.2.34_4/bin/php PHP80_BIN_PATH=/opt/homebrew/Cellar/php@8.0/8.0.17/bin/php && sh ./full_build.sh
```

Update `PHP72_BIN_PATH` and `PHP80_BIN_PATH` with your local dev php location.

I am closing for now ;)

**Pull request closed without merging**
