### PR TITLE
[Core][CodingStyle][NodeManipulator] Improve Classes to use BetterNodeFinder instead of NodeFinder when BetterNodeFinder already injected

### PR DESCRIPTION
**Pull request by samsonasik**
- remove `NodeFinder` dependency as already injected with `BetterNodeFinder` in `AstResolver`
- remove `NodeFinder` dependency as already injected with `BetterNodeFinder` in `ShortNameResolver`
- remove `NodeFinder` dependency as already injected with `BetterNodeFinder` in `ClassMethodAssignManipulator`

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Review by TomasVotruba — APPROVED** [review]

**Comment by samsonasik** [comment]
@TomasVotruba it seems there is new symfony release or the deps that cause scoped build error:

https://github.com/rectorphp/rector-src/runs/4119669391?check_suite_focus=true#step:22:6

**Comment by samsonasik** [comment]
@TomasVotruba it seems the bare run test error happen in php <= 7.3

https://github.com/rectorphp/rector/actions/runs/1426679345

**Comment by samsonasik** [comment]
@TomasVotruba it seems because of new psr/container release https://github.com/php-fig/container/commit/c71ecc56dfe541dbd90c5360474fbc405f8d5963

**Comment by samsonasik** [comment]
@TomasVotruba we may need a new rector rule to downgrade from php 7.4 to avoid error : "cannot implement previously implemented interface Throwable"

**Comment by TomasVotruba** [comment]
> @TomasVotruba we may need a new rector rule to downgrade from php 7.4 to avoid error : "cannot implement previously implemented interface Throwable"

Intersting one, good catch :+1:  Could you add it?

**Comment by samsonasik** [comment]
@TomasVotruba I created PR for it https://github.com/rectorphp/rector-src/pull/1159

**Comment by TomasVotruba** [comment]
Awesome, I saw it right in my notifications after I've replied here :)

**Pull request merged**
