### PR TITLE
[CodingStyle] Handle inner closure on FuncGetArgsToVariadicParamRector

### LINKED ISSUE #7886: Incorrect behavior of FuncGetArgsToVariadicParamRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/97df0403-4660-48a8-9452-c109cf2abc47

```php
<?php

class Test {
    public function test() {
        $funcArgs = [];
        $a = function () use (&$funcArgs): void {
            $funcArgs[] = func_get_args();
        };
        $a(1, 2, 3);

        return $funcArgs;
    }
}

$t = new Test();

print_r($t->foo('hello world'));
```

### Responsible rules

* `FuncGetArgsToVariadicParamRector`

## Expected Behavior

This added the `...$args` to the function `tests`, not the the anonymous function stored in `$a`.

The code that was produced doesn't run (it has the error`Warning: Undefined variable $args`). If `$a` was changed to capture `$args` by changing it to `$a = function () use (&$funcArgs, $args)` then this would print the wrong result.

What is expected is that it adds `...$args` to the anonymous function stored in `$a`, that is, for the code to be `$a = function (...$args) use (&$funcArgs)`.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7886

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed :tada: /cc @aboyton

**Comment by aboyton** [comment]
Wow, that was fast. Thanks.

**Comment by samsonasik** [comment]
All checks have passed :tada: @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
