### PR TITLE
[Php81] Handle usage as arg by ref key on falsy ObjectType on ReadOnlyPropertyRector

### LINKED ISSUE #8696: ReadOnlyPropertyRector not detecting when property passed by reference
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | last dev-main             |

## Minimal PHP Code Causing Issue
See https://getrector.com/demo/5c08c3f0-8d7f-4b44-93e7-732a963c4df8

```
<?php

declare(strict_types=1);

namespace Rector\Tests\Php81\Rector\Property\ReadOnlyPropertyRector\Fixture;

use PDO;

class A
{
    public function __construct(
        private int $id
    ) {
    }

    public function prepare(): void
    {
        $dsn = 'mysql:dbname=testdb;host=127.0.0.1';
        $user = 'dbuser';
        $password = 'dbpass';

        $dbh = new PDO($dsn, $user, $password);
        $sth = $dbh->prepare('SELECT * FROM users WHERE id = :id');
        $sth->bindParam('id', $this->id, PDO::PARAM_INT);
        $sth->execute();
    }
}
```

## Expected Behaviour
Property should not be changed as it's passed by reference in the `bindParam` method call

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8696

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @nikolicaleksa

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Looks good, thanks :+1:

**Comment by nikolicaleksa** [comment]
> Fixed 🎉 /cc @nikolicaleksa

Awesome, thanks for the fast fix!

**Pull request merged**
