### PR TITLE
[CodingStyle] Refactor RemoveUnusedAliasRector

### PR DESCRIPTION
**Pull request by samsonasik**
removeUnusedAliasRector is no longer working since https://github.com/rectorphp/rector-src/pull/1087 . It may need to refactor to make it work again.

### CODE REVIEW

**Comment by samsonasik** [comment]
it actually remove the alias, but not remove the usage of it so when used, it can broke existing code.

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you for finishing these. I run out of energy yesterday after all the refactoring PRs, so you made my day 👍😎

**Pull request merged**
