### PR TITLE
fix: Add code as a named argument

### LINKED ISSUE #8698: ThrowWithPreviousExceptionRector not using named argument for code
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | last dev-main             |

See https://getrector.com/demo/8bb41109-893d-4232-a54d-d7b4d24eaba5
```
<?php

namespace Rector\Tests\CodeQuality\Rector\Catch_\ThrowWithPreviousExceptionRector\Fixture;

use LogicException;

class NamedArgumentForMessageAndPrevious
{
    public function run()
    {
        try {
            $this->run();
        }catch(\Throwable $throwable) {
            throw new LogicException(message: 'Some exception', previous: $throwable);
        }
    }
}

?>
```

## Expected Behaviour
Rector should add `code` argument as a named argument

### PR DESCRIPTION
**Pull request by nikolicaleksa**
Fixes https://github.com/rectorphp/rector/issues/8698

### CODE REVIEW

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
you can update PR description with 

```
Fixes https://github.com/rectorphp/rector/issues/8698
```

to automatically close the issue when PR got merged.

**Comment by TomasVotruba** [comment]
How would this work on PHP 7.4?

**Comment by nikolicaleksa** [comment]
> How would this work on PHP 7.4?

I think it should not be a problem as we are not always adding the named parameter, it's based on condition `$shouldUseNamedArguments = $messageArgument->name !== null;` which for PHP 7.4 would always evaluate to false

**Comment by TomasVotruba** [comment]
I see, looks good then :+1:

**Pull request merged**
