### PR TITLE
[Core] Fix fill nearest parent Scope on AbstractScopeAwareRector

### LINKED ISSUE #7203: Scope not available on MethodCall
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.3            |

```
❯ vendor/bin/rector process src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php --debug
src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\MethodCall\RenameMethodRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\MethodCall\RenameMethodRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php
[rule] Rector\Renaming\Rector\MethodCall\RenameMethodRector


                                                                                                                        
 [ERROR] Could not process "src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php" file, due to:          
         "System error: "Scope not available on "PhpParser\Node\Expr\MethodCall" node with parent node of               
         "PhpParser\Node\Expr\MethodCall", but is required by a refactorWithScope() method of                           
         "Rector\Renaming\Rector\MethodCall\RenameMethodRector" rule. Fix scope refresh on changed nodes first"         
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
         line: 27                                                                                                       
                        
```

## Minimal PHP Code Causing Issue

https://github.com/shopware/platform/blob/trunk/src/Core/Content/Test/MailTemplate/Api/MailActionControllerTest.php

## Expected Behaviour

Just works 🤔

### PR DESCRIPTION
**Pull request by samsonasik**
The issue is reproducible by remove guard on multiple rules applied on single node on `RectifiedAnalyzer` service:

```diff
--- a/src/ProcessAnalyzer/RectifiedAnalyzer.php
+++ b/src/ProcessAnalyzer/RectifiedAnalyzer.php
@@ -60,11 +60,6 @@ final class RectifiedAnalyzer
             return ! $this->nodeComparator->areNodesEqual($originalNode, $node);
         }
 
-        if ($rector instanceof AbstractScopeAwareRector) {
-            $scope = $node->getAttribute(AttributeKey::SCOPE);
-            return $scope instanceof Scope;
-        }
```

from https://github.com/rectorphp/rector-src/blob/10fd4c349828c2753b6cfa499f5c917cd8e0646e/src/ProcessAnalyzer/RectifiedAnalyzer.php#L63-L66

Then, run the downgrade command:

```bash
bin/rector process vendor/composer/pcre/src/Preg.php -c build/config/config-downgrade.php --dry-run --clear-cache -vvv
```

it will got error:

```bash
[file] vendor/composer/pcre/src/Preg.php
[rule] Rector\DowngradePhp81\Rector\FuncCall\DowngradeArrayIsListRector

 [ERROR] Could not process "vendor/composer/pcre/src/Preg.php" file, due to:                                            
         "System error: "Scope not available on "PhpParser\Node\Expr\FuncCall" node with parent node of                 
         "PhpParser\Node\Arg", but is required by a refactorWithScope() method of                                       
         "Rector\DowngradePhp81\Rector\FuncCall\DowngradeArrayIsListRector" rule. Fix scope refresh on changed nodes    
         first"                                                                                                         
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
         line: 36    
```

by update nearest parent Node scope, to fill its parent down until the node, it will make it working:

```bash
|[file] vendor/composer/pcre/src/Preg.php
[rule] Rector\DowngradePhp80\Rector\StaticCall\DowngradePhpTokenRector

[file] vendor/composer/pcre/src/Preg.php
[rule] Rector\DowngradePhp73\Rector\FuncCall\DowngradeTrailingCommasInFunctionCallsRector
                                                                                                                        
 [OK] Rector is done!                                                                                                   
```

Closes https://github.com/rectorphp/rector-src/pull/2493
Fixes https://github.com/rectorphp/rector/issues/7203

### CODE REVIEW

**Comment by samsonasik** [comment]
I tried downgrade script for it and it seems working ok 🎉 

```bash
export PHP72_BIN_PATH=/opt/homebrew/Cellar/php@7.2/7.2.34_4/bin/php && sh ./full_build.sh
```

Screen Shot 2022-06-15 at 15 16 30

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
We'll need exact test case from the reported issue: https://github.com/rectorphp/rector/issues/7203

This fix is hidding the place where we miss passing the scope to child nodes. We need to now exactly the nodes, that are skipped by PHPStan.

**Comment by samsonasik** [comment]
On `vendor/composer/pcre/src/Preg.php` use case, the issue is the `DowngradeArrayIsListRector` tried to look the `FuncCall` node which parent is `Arg`:

```bash
"Scope not available on "PhpParser\Node\Expr\FuncCall" node with parent node of "PhpParser\Node\Arg"
```

which if printed, it got on the following script:

```php
sprintf(static::INVALID_TYPE_MSG, gettype($subject))
```

https://github.com/rectorphp/rector/blob/80a3820ca7cf4cead269afd72267c7ae60b41cd7/vendor/composer/pcre/src/Preg.php#L104

while issue https://github.com/rectorphp/rector/issues/7203 is different which look up parent `MethodCall` (possibly fluent), it only applied when `Scope` is null on `AbstractScopeAwareRector` instance by looking at the error message, it should be fixed by this patch, which do:

- Lookup nearest parent Node with Scope (eg: in level 3).
- Got Scope? Then fill up Scope  from parent level 1, then parent level 2, then fill the Node Scope itself.

**Comment by TomasVotruba** [comment]
> Lookup nearest parent Node with Scope (eg: in level 3).

This could lead to very hard to discover bugs:

```php
// on this line, the value is mixed type
if ($value === 5) {
    // here we know the value is 5
    echo $value;
}
```

Using this technique, we might get a scope for `echo $value;` where `$value` is mixed, that is not true. That's why we have to use only the explicit known scope.

---


Could you add those failing case in a test case here so we have them covered?

**Comment by samsonasik** [comment]
It seems the `Scope` gone only happen on `Expr`, which when look up on parent scope, it got the first that has `Scope` is on the current `Stmt`,which, for example, on `vendor/composer/pcre/src/Preg.php` use case, it got the `Scope` on current stmt, the `Throw_` stmt:

```bash
PhpParser\Node\Stmt\Throw_ #31222
   expr: &1 PhpParser\Node\Expr\New_ #31223
   |  class: &2 PhpParser\Node\Name\FullyQualified #31224 ...
   |  args: &3 array (1) ...
   |  attributes: array (11) ...
   attributes: array (14)
   |  'startLine' => 118
   |  'startTokenPos' => 688
   |  'endLine' => 118
   |  'endTokenPos' => 707
   |  'parentStmtTypes' => array (4) ...
   |  'tryCatchTypes' => null
   |  'parent' => PhpParser\Node\Stmt\If_ #31204 ...
   |  'previous' => PhpParser\Node\Stmt\If_ #31210 ...
   |  'statementOrder' => 1
   |  'statementDepth' => 4
   |  'isUnreachable' => true
   |  'scope' => PHPStan\Analyser\MutatingScope #28573 ...
   |  'origNode' => PhpParser\Node\Stmt\Throw_ #15388 ...
   |  'php_doc_info' => Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfo #33028 ...
```

we can limit to up until current stmt if that needed. 

I added check to verify that parent node is not below current stmt  https://github.com/rectorphp/rector-src/pull/2492/commits/e1ffcc4ae91d971903740e417c361c302f2e4682

**Comment by samsonasik** [comment]
I also add verify if Node is an `Stmt` and not has Scope, then do not try to resolve Scope from Nearest parent and just throw the error as Scope result is null https://github.com/rectorphp/rector-src/pull/2492/commits/448308eaa6b4f1654ac6c180682d79241b0a7376

**Comment by samsonasik** [comment]
cleaned check with return null early on `parentNode === $currenStmt` as node instanceof Stmt already checked early on very first Stmt on `resolveScopeFromNearestParentNode()` method https://github.com/rectorphp/rector-src/pull/2492/commits/3ff9b692e5fb3e673d9e592ed6c65d0557b7a111

**Comment by samsonasik** [comment]
Summary:
----------

- Lookup Scope from parent Node limited only on non-Stmt (eg: Expr), so if Node already as `Stmt` and doesn't has `Scope`, then throw the Error as `Scope` still null.
- When lookup, check parent Node Scope, if found, then fill the `$scope` variable with nearest parent Scope.
- If still not found, verify that parent Node already a current Stmt, which for the following use case, will only lookup until the `Echo_` stmt, not the `If_` part .

```php
// on this line, the value is mixed type
if ($value === 5) {
    // here we know the value is 5
    echo $value;
}
```

- when `$scope` is null, then return null to throw the error.
- Otherwise, fill parent Node until it has Scope, then fill the Node scope itself.
- remove unneeded scope null check on RectifiedAnalyzer

**Comment by samsonasik** [comment]
I've added e2e test for it for applied rules:

```
Rector\DowngradePhp81\Rector\FuncCall\DowngradeArrayIsListRector;
Rector\DowngradePhp81\Rector\FuncCall\DowngradeFirstClassCallableSyntaxRector;
```

that demonstrate handle error on `Preg::replaceCallbackArray()` on parent of the `sprintf()` on the following commit:

https://github.com/rectorphp/rector-src/pull/2492/commits/f5d2bfa3073ec1798acff2a79dcda7512db1c6df 

that handled by this patch.

to reproduce the error:

**1. Run checkout and pull:**

 ```
 git checkout -b fill-nearest-parent-scope
 git pull origin fill-nearest-parent-scope
```

**2. comment the following line in this patch**

https://github.com/rectorphp/rector-src/blob/f5d2bfa3073ec1798acff2a79dcda7512db1c6df/src/Rector/AbstractScopeAwareRector.php#L28

to be:

```diff
-            $scope = $this->resolveScopeFromNearestParentNode($node, $scope);
+            //$scope = $this->resolveScopeFromNearestParentNode($node, $scope);
```

**3. change directory and run test:**

```
cd e2e/parent-arg-from-func-call
composer install
php ../e2eTestRunner.php
```

**4. it will got error:**

```bash
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%[ERROR] Could not process "src/Preg.php" file, due to:
         "System error: "Scope not available on "PhpParser\Node\Expr\FuncCall" node with parent node of
         "PhpParser\Node\Arg", but is required by a refactorWithScope() method of
         "Rector\DowngradePhp81\Rector\FuncCall\DowngradeArrayIsListRector" rule. Fix scope refresh on changed nodes
         first"
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On
         line: 39%                                                       

```

**5. rollback the uncomment part from step 2 and run test again**

```bash
git checkout ../../
php ../e2eTestRunner.php                                       

 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%[OK] Rector is done!%  
```

**7. Now, test is OK.**

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
@TomasVotruba same issue with https://github.com/rectorphp/rector-src/pull/2493, if looking up only until current Stmt, it will got error on downgrade, eg:

```bash
bin/rector process vendor/nette/neon/src/Neon/Parser.php --config build/config/config-downgrade.php --dry-run --clear-cache -vvv


[file] vendor/nette/neon/src/Neon/Parser.php
[rule] Rector\DowngradePhp81\Rector\FuncCall\DowngradeArrayIsListRector


                                                                                                                        
 [ERROR] Could not process "vendor/nette/neon/src/Neon/Parser.php" file, due to:                                        
         "System error: "Scope not available on "PhpParser\Node\Expr\FuncCall" node with parent node of                 
         "PhpParser\Node\Stmt\If_", but is required by a refactorWithScope() method of                                  
         "Rector\DowngradePhp81\Rector\FuncCall\DowngradeArrayIsListRector" rule. Fix scope refresh on changed nodes    
         first"                                                                                                         
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
         line: 39    
```

which can be resolved by lookup until Scope found, not only until current stmt is a parent.

```diff
-            if ($parentNode === $currentStmt) {
-                return null;
-            }
-
```

**Comment by samsonasik** [comment]
I removed lookup until Current Stmt limitation https://github.com/rectorphp/rector-src/pull/2492/commits/5b15495c00b89d6d7802b18e31307bb357ddbc0a so it will lookup parent Scope until found to avoid error like previous comment.

**Pull request closed without merging**
