### PR TITLE
[CodeQuality] Drop ArrayThisCallToThisMethodCallRector as changes behavior and better handled by FirstClassCallableRector

### LINKED ISSUE #7256: ArrayThisCallToThisMethodCallRector: System error: "Invalid value"
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.6             |

The `ArrayThisCallToThisMethodCallRector` rule fails to run with a system error when a method with parameters is referenced.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/ce8623be-aeb7-45f4-9bf3-ed307cae7e85

This code is almost identical to the sample code for this rule, except for the `$arg` parameter to `giveMeMore`. If I remove the parameter, the error does not occur.

## Expected Behaviour

I expect no error and for the code to remain unmodified. (I have to admit I don't really understand the purpose of this rule, but I think that's a separate issue.)

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes https://github.com/rectorphp/rector/issues/7256

### CODE REVIEW

**Comment by samsonasik** [comment]
Even without args, this should be skipped, as it need to be used as callable or self invoked, tried var_dump() the variable assign, the original got array, the transformed get string result of method call.

**Comment by TomasVotruba** [comment]
Yeah, thanks for feedback. I think I've used this rule for something else with change of behavior :thinking: 

This is the correct transformation:
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#firstclasscallablerector


Do you think it should be removed completely?

**Comment by edsrzf** [comment]
I agree, I found the sample very puzzling. Unless I'm missing something, it would change the code's behavior. The `FirstClassCallableRector` rule seems much more desirable.

**Comment by samsonasik** [comment]
That's seems depends of the usage, even `FirstClassCallableRector`, if the usage is only for data, then no need to change it, ref

https://3v4l.org/5muAo vs https://3v4l.org/6QVAn

once got array, second got Closure object.

there is also rule that change to `Closure`, like in `CallableThisArrayToAnonymousFunctionRector`, which the behaviour should be same, which should check if it is passed as callable, eg, on laminas-eventmanager:

https://github.com/laminas/laminas-eventmanager/blob/e45471d047146298c9074c188c149b77970d13b1/src/EventManagerInterface.php#L94

which it has parameter `callable $listener` which can pass `[$this, 'run']`, or `function () { return $this->run(); }`

**Comment by TomasVotruba** [comment]
> once got array, second got Closure object. 

That's actually what the first class callable PHP feature tries to fix, so the type change is expected there.

The problem here I see that array closure (not called) is changed to direct data call. In first case, it's still a closure. In 2nd case we actually the method and run it.

**Comment by samsonasik** [comment]
I think that will be only usable if called/returned/passed as callable, if not and used just as data, then it got error, eg, the following code:

```diff
final class SomeClass
 {
     public function run(): array
     {
-        $name = [$this, 'name'];
+        $name = $this->name(...);
        return $name;
     }

     public function name()
     {
         return 'test';
     }
 }
 
 (new SomeClass())->run();
```

ref https://3v4l.org/ht3ZJ

**Comment by TomasVotruba** [comment]
Yes, some case always depends on specifics of the code. In this case an upgrade of return is needed too - with developer supervision :)

**Pull request merged**
