### PR TITLE
[docker] remove docker building from release repository

### PR DESCRIPTION
**Pull request by TomasVotruba**
Some developers see Docker as default-to-use for Rector. Yet they struggle to run it successfuly with very basic changes like: https://twitter.com/frankdejonge/status/1419298126133927941 This cannot happen.

It's very frustrating for them and often end-up in removing the tool completely with bad feeling inside.

The core team around Rector is not using Docker for running, because there is no need for it. Saying that, current Docker version is naturally obsolete and lacking behind PHP code development. 

## Use Rector like PHPUnit

**With [downgrades](https://getrector.org/blog/2021/03/22/rector-010-released-with-php71-support) and [prefixed release](https://getrector.org/blog/prefixed-rector-by-default) repository, Rector can be easily installed on any project:**

```bash
composer require rector/rector --dev
```

Rector can save you hundrers hours on automated refactoring and instant upgrades. But main added features is in the longterm feedback and everyday work it resolves for you. With new rules and sets, you should never upgrade manualla again. How?

The same way PHPUnit checks your tests in CI, [the same way Rector works in CI for you](https://getrector.org/blog/2020/10/05/how-to-make-rector-contribute-your-pull-requests-every-day).

<br>

If PHP version is the limit, Docker would not help as Rector requires PHP 7.1 to run. There is PHP 5.6 sponsorware program for project who want to make it happen https://getrector.org/blog/rector-for-php56-native

<br>

Do you want to keep Docker for Rector alive? Community maintainer is welcomed :+1:

### CODE REVIEW

**Review by samsonasik — APPROVED** [review]

**Review by staabm — APPROVED** [review]

**Comment by JanMikes** [comment]
Its a pity. All i can say. 

Pls be aware that docker image https://hub.docker.com/r/rector/rector will immediately after merging this happen to be out of date. Do you want to delete it too?

**Review by JanMikes — APPROVED** [review]

**Comment by TomasVotruba** [comment]
> Pls be aware that docker image hub.docker.com/r/rector/rector will immediately after merging this happen to be out of date. Do you want to delete it too?

Based on community feedback it's been out of date for a while. See the linked tweets, I recall this worked ~ year ago. Deleting is good idea, otherwise it would be confusing.

**Comment by JanMikes** [comment]
> Based on community feedback it's been out of date for a while

It is not true, image was up to date all the time. Maybe they forget to `docker pull` 🤷 

> Deleting is good idea

Done, RIP

I am thinking of maintaining community docker image. Last pull was 2 hours ago and over the time, we had  overall 300k+ downloads of the docker images.

**Comment by TomasVotruba** [comment]
> It is not true, image was up to date all the time. Maybe they forget to docker pull 🤷

I mean the content was broken, the image was up to date :) see the linked tweet above for more.

> I am thinking of maintaining community docker image. Last pull was 2 hours ago and over the time, we had overall 300k+ downloads of the docker images.

That would be very helpful 🙂

**Pull request merged**
