### PR TITLE
[automated] Apply Coding Standard

### PR DESCRIPTION
**Pull request by TomasVotruba**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by staabm** [comment]
@TomasVotruba @samsonasik any plans for a new release? I would love to use this rector :)

**Comment by samsonasik** [comment]
I will let @TomasVotruba decide for creating new release ;)

**Comment by TomasVotruba** [comment]
No specific plans, but usually every 2-4 weeks :) if we'd release after every requested release after fix, we'd be doing 5 release a day :D  

I reckon using the dev branch, that's how we actually test Rector ourselves before letting it to the wild ;)

**Comment by samsonasik** [comment]
@staabm 1.0.4 is tagged https://github.com/rectorphp/rector/releases/tag/1.0.4

**Comment by staabm** [comment]
thank you guys :)

**Pull request merged**
