### PR TITLE
Test: `EncapsedStringsToSprintfRector` + `RemoveDeadInstanceOfRector`

### PR DESCRIPTION
**Pull request by Androbin**
Closes rectorphp/rector#6481
Fixed by #201 @samsonasik 
See nikic/PHP-Parser#780

### CODE REVIEW

**Comment by Androbin** [comment]
I don't understand the nature of this CI error, I can't even reproduce it locally.
```
 ------------------------------------------------------------------------
  rules/CodingStyle/Rector/Encapsed/EncapsedStringsToSprintfRector.php:124
 ------------------------------------------------------------------------
  - '#Missing sprintf\(\) function for a mask#'
 ------------------------------------------------------------------------
```

**Comment by Androbin** [comment]
@sabbelasichon @TomasVotruba PTAL

**Comment by samsonasik** [comment]
@Androbin that's handled at https://github.com/symplify/symplify/pull/3310 . For now, I think you can ignore it in `phpstan.neon` by add the following:

```neon
        -
            message: '#Missing sprintf\(\) function for a mask#'
            path: rules/CodingStyle/Rector/Encapsed/EncapsedStringsToSprintfRector.php #124
```

**Comment by Androbin** [comment]
@TomasVotruba Ready for review

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
