### PR TITLE
[AutoImport] Skip auto import on no namespace used class on auto import enabled

### PR DESCRIPTION
**Pull request by samsonasik**
It currently cause imported which make root class used invalid, see https://getrector.com/demo/25b150bf-d253-47ff-b1bc-b5456b520986

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it to have faster feedback to test ;)

**Comment by clxmstaab** [comment]
0.18.7 without this fix produces fatal wrong code. wdyt about a immediate bugfix release?

//cc @TomasVotruba

**Comment by samsonasik** [comment]
@clxmstaab just tagged 0.18.8 https://github.com/rectorphp/rector/releases/tag/0.18.8

**Comment by clxmstaab** [comment]
thx!

**Pull request merged**
