### PR TITLE
[Php81] Skip Encapsed on NullToStrictStringFuncCallArgRector

### PR DESCRIPTION
**Pull request by samsonasik**
Closes https://github.com/rectorphp/rector-src/pull/2742

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba CI error is possibly related to new phpstan-rules update:

```bash
There were 167 errors:

1) Rector\Doctrine\Tests\Rector\ClassMethod\MakeEntitySetterNullabilityInSyncWithPropertyRector\MakeEntitySetterNullabilityInSyncWithPropertyRectorTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
_PHPStan_9a6ded56a\Nette\DI\ServiceCreationException: Service (Symplify\PHPStanRules\Rules\RequireStringArgumentInConstructorRule::__construct()): Class 'Symplify\PHPStanRules\Rules\RequireStringArgumentInConstructorRule' not found.
```

it still error even require `"rector/phpstan-rules": "dev-main"`

**Review by lyrixx — APPROVED** [review]

**Comment by samsonasik** [comment]
Close-Reopen to restart build

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
rebased.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
