### PR TITLE
[TypeDeclaration] Remove NullType when already has mixed on ParamAnnotationIncorrectNullableRector

### PR DESCRIPTION
**Pull request by samsonasik**
@dorrogeray mixed can be anything and null type itself, so null addition is not needed when mixed already used. So given the following code:

```php
final class RemoveMixedWithNullable
{
    /**
     * @param mixed|null $default
     */
    public function getEnvVar(string $var, mixed $default = null): mixed
    {
        return $this->env[$var] ?? $default;
    }
}
```

should result:

```diff
-     * @param mixed|null $default
+     * @param mixed $default
```

### CODE REVIEW

**Comment by TomasVotruba** [comment]
👍

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I am merging it ;)

**Comment by TomasVotruba** [comment]
Fine with me :+1:

**Comment by dorrogeray** [comment]
Thanks, good catch! :+1:

**Pull request merged**
