### PR TITLE
[Core] Remove Current Statement check on RectifiedAnalyzer, use Original Node instead

### PR DESCRIPTION
**Pull request by samsonasik**
Remove check against `AttributeKey::CURRENT_STATEMENT` on `RectifiedAnalyzer`, use `AttributeKey::ORIGINAL_NODE` instead.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by TomasVotruba** [comment]
Ref https://github.com/rectorphp/rector/issues/7126

**Pull request merged**
