### PR TITLE
CI: make linting errors appear in PRs 'Files Changed' tab

### PR DESCRIPTION
**Pull request by staabm**
example (with phpunit error message):

phpunit-printer-context

using https://github.com/staabm/annotate-pull-request-from-checkstyle

### CODE REVIEW

**Comment by samsonasik** [comment]
@staabm PHPStan notice resolved at https://github.com/rectorphp/rector-src/pull/3730

**Comment by samsonasik** [comment]
@staabm please rebase

**Comment by staabm** [comment]
thanks. done.

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
