### PR TITLE
[Php71] Skip First Class Callable on RemoveExtraParametersRector

### LINKED ISSUE #7274: First-class callable rule is missing "..."
# Bug Report

| Subject        | Details                           |
| :------------- | :-------------------------|
| Rector version | Rector 0.13.7             |

The first-class callable syntax rule [#2544](https://github.com/rectorphp/rector-src/pull/2544) does not convert the callable as it should be. The three dots `...` are missing.

## Minimal PHP Code Causing Issue

```php
new TwigFunction('app_seo_title', [$this, 'getTitle'], [
    'is_safe' => ['html'],
]),
```

```php
new TwigFunction('app_seo_title', $this->getTitle(), [
    'is_safe' => ['html'],
]),
```

## Expected Behaviour

```php
new TwigFunction('app_seo_title', $this->getTitle(...), [
    'is_safe' => ['html'],
]),
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7274

### CODE REVIEW

**Comment by samsonasik** [comment]
Also found crash on direct call `First callable`, ref https://getrector.org/demo/bd3ea325-6755-45d8-8917-4155b90afd9e

```bash
There was 1 error:

1) Rector\Tests\Php71\Rector\FuncCall\RemoveExtraParametersRector\RemoveExtraParametersRectorTest::test with data set #12 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\ShouldNotHappenException: Node "PhpParser\Node\Expr\MethodCall" with parent of "PhpParser\Node\Stmt\Expression" is missing scope required for scope refresh.
```

ref https://github.com/rectorphp/rector-src/runs/7170118140?check_suite_focus=true#step:5:76

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @Spomky

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
