### PR TITLE
 [Php73] Skip Encapsed on StringifyStrNeedlesRector + Temporary Pin PHPStan 1.6.9

### LINKED ISSUE #7177: `StringifyStrNeedlesRector` unneededly runs with interpolated scalar string
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.23             |

## Minimal PHP Code Causing Issue

```php
<?php

$str = 'bar';

strpos('foo bar', " {$str}");
```

## Expected Behaviour

The needle should be unchanged as it already is a string.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7177

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @Blacksmoke16

**Comment by samsonasik** [comment]
PHPStan 1.7.0 seems cause errors in tests:

```
There were 3 failures:

1) Rector\Core\Tests\Issues\Issue6675\MysqlToMysqliRenameRemoveTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
tests/Issues/Issue6675/Fixture/no_namespace.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 <?php
 
 $db = mysqli_connect("server", "user", "password");
-echo mysqli_error($db);
+echo mysql_error();
 
 ?>

/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:154
/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:115
/home/runner/work/rector-src/rector-src/tests/Issues/Issue6675/MysqlToMysqliRenameRemoveTest.php:18

2) Rector\Core\Tests\Issues\Issue6675\MysqlToMysqliRenameRemoveTest::test with data set #1 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
tests/Issues/Issue6675/Fixture/bare_stmts.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 function someFunction()
 {
     $db = mysqli_connect("server", "user", "password");
-    echo mysqli_error($db);
+    echo mysql_error();
 }
 
 ?>

/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:154
/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:115
/home/runner/work/rector-src/rector-src/tests/Issues/Issue6675/MysqlToMysqliRenameRemoveTest.php:18

3) Rector\Core\Tests\Issues\Issue6675\MysqlToMysqliRenameRemoveTest::test with data set #2 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
tests/Issues/Issue6675/Fixture/fixture.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 namespace Rector\Core\Tests\Issues\Issue6675\Fixture;
 
 $db = mysqli_connect("server","user","password");
-echo mysqli_error($db);
+echo mysql_error();
 
 ?>

/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:154
/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:115
/home/runner/work/rector-src/rector-src/tests/Issues/Issue6675/MysqlToMysqliRenameRemoveTest.php:18
```

**Comment by samsonasik** [comment]
@TomasVotruba it seems PHPStan 1.7.0 cause `SetList::MYSQL_TO_MYSQLI` no longer work at all, as error above https://github.com/rectorphp/rector-src/pull/2352#issuecomment-1135008522, also other error in rules-tests

```

There was 1 failure:

1) Rector\Tests\DowngradePhp80\Rector\MethodCall\DowngradeReflectionPropertyGetDefaultValueRector\DowngradeReflectionPropertyGetDefaultValueRectorTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules-tests/DowngradePhp80/Rector/MethodCall/DowngradeReflectionPropertyGetDefaultValueRector/Fixture/pull_from_phpstan_reflection.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
     public function get(PhpPropertyReflection $phpPropertyReflection)
     {
         $reflectionProperty = $phpPropertyReflection->getNativeReflection();
-        return is_array($reflectionProperty->getDeclaringClass()->getDefaultProperties()[$reflectionProperty->getName()] ?? null);
+        return is_array($reflectionProperty->getDefaultValue());
     }
 }
```

**Comment by samsonasik** [comment]
Scope of 

```diff
-$db = mysql_connect("server","user","password");
+$db = mysqli_connect("server","user","password");
```

somehow no longer refreshed in PHPStan 1.7.0

**Comment by samsonasik** [comment]
@TomasVotruba let's temporary pin PHPStan to 1.6.9 as I tried PHPStan 1.7.0 in CodeIgniter project and cause infinite loop  endless progressbar. ref https://github.com/codeigniter4/CodeIgniter4/pull/6019#issuecomment-1135043018

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

Some notes:

- Temporary pin PHPStan to 1.6.9 temporary on purpose as PHPStan 1.7.0 cause errors with Scope somehow gone on Mysqli rule Set and `DowngradeReflectionPropertyGetDefaultValueRector` as above.
- PHPStan 1.7.0 seems cause infinite loop when used along in `CodeIgniter4` project with run `vendor/bin/rector`, I will debug if I can found something, ref https://github.com/codeigniter4/CodeIgniter4/pull/6019#issuecomment-1135043018

**Comment by samsonasik** [comment]
Let's merge for now ;)

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
