### PR TITLE
[Down_To_PHP71] Handle Downgrade Param Widening + Downgrade Reflection Get on DowngradeLevelSetList::DOWN_TO_PHP_71

### LINKED ISSUE #7546: Incorrect behavior of DowngradeParameterTypeWideningRector + DowngradeReflectionGetAttributesRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1fcc02fc-52f3-4ca2-bc4a-6117e00362b7

```php
<?php

class SomeClass
{
    public function run(ReflectionClass $reflectionClass)
    {
        if ($reflectionClass->getAttributes()) {
            return true;
        }
        return false;
    }
}
```

### Responsible rules

* `DowngradeParameterTypeWideningRector`

## Expected Behavior

When applying set `DowngradeLevelSetList::DOWN_TO_PHP_71`, rule `DowngradeReflectionGetAttributesRector`  should also be applied (in addition to `DowngradeParameterTypeWideningRector`), but it is not.

Check the same code but running the rule instead of the set, then that rule is applied:

https://getrector.org/demo/417e38a1-b75f-42e3-8998-b178bc5bf55f

Similarly, running `DowngradeLevelSetList::DOWN_TO_PHP_71` twice, the second time on the output from the first run, then `DowngradeReflectionGetAttributesRector` is applied:

https://getrector.org/demo/d849d04d-e35c-448d-aa49-c23a7423ceef

This may be the same issue as here? https://github.com/rectorphp/rector/issues/7452

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7546

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @leoloso

**Comment by samsonasik** [comment]
It seems cause error in other downgrade tests:

```

There were 5 failures:

1) Rector\Tests\DowngradePhp80\Rector\Expression\DowngradeMatchToSwitchRector\DowngradeMatchToSwitchRectorTest::test with data set #6 ('/home/runner/work/rector-src/...hp.inc')
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
     public function run($value)
     {
         static function (mixed $default) : mixed {
-            switch (true) {
-                case is_string($default):
-                    return sprintf('"%s"', $default);
-                default:
-                    return $default;
-            }
+            return match (true) {
+                    is_string($default) => sprintf('"%s"', $default),
+                    default => $default,
+                };
         };
     }
```

**Comment by leoloso** [comment]
That was soooooooooo quick!!!!!!! Thanks @samsonasik 💪

**Comment by samsonasik** [comment]
I tried manually check the `DowngradeReflectionGetAttributesRector`, it seems due to `$reflectionClass` no longer typed, and it got mixed type already.

It seems needs to use original node instead of latest changed type for this use case.

**Comment by samsonasik** [comment]
It seems can be resolved by lookup variable from Param when exists on `NodeTypeResolver->getType()` https://github.com/rectorphp/rector-src/pull/3001/commits/50f3a581896b21acb9f25b7cf66b7e7b9ad97356

**Comment by samsonasik** [comment]
Using find first previous to get first from param seems need another tweaking, as the following code will not be processed correctly:

```php
use ReflectionClass;

class DowngradeParamReflectionGetAttribute
{
    public function run(ReflectionClass $reflectionClass)
    {
        echo $reflectionClass->getFileName();

        if ($reflectionClass->getAttributes()) {
            return true;
        }
        return false;
    }
}
```

as first previous is:

```php
echo $reflectionClass->getFileName();
```

which will be mixed type already after downgrade parameter type widening.

**Comment by samsonasik** [comment]
I added check not param and stil mixed type https://github.com/rectorphp/rector-src/pull/3001/commits/0dd5c085a9e594cce2e4a5edc1163f7de8fff2c4

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
It seems it will make unreliable when it reassign or unset after pull from Param, marking back to draft.

**Comment by samsonasik** [comment]
Let's try tweak by [re-run refactor() when node is same and phpdoc info changed](https://github.com/rectorphp/rector-src/pull/3001/commits/3c035a1890eabe595552efa94c9dc4c4ee8384dc)

**Comment by samsonasik** [comment]
The issue seems when `PhpdocInfo->hasChanged()` is `true`, it is not immediatelly applied the information to the `Node` as comment, as if the node is printed, the comment still not shown, so it is late to get information of the PHPStan type.

**Comment by samsonasik** [comment]
Let's [try setDocComment() on phpdocInfo->markAsChanged()](https://github.com/rectorphp/rector-src/pull/3001/commits/9ac3242ff735fdd777f0a74ef8df25a6361f3251)

**Comment by samsonasik** [comment]
Let's try early refresh doc Node before refresh scope https://github.com/rectorphp/rector-src/pull/3001/commits/c81df9c79a65e3a9858234fa6eee1e30cb8f567f

**Comment by samsonasik** [comment]
Finally 🎉 🎉 🎉, All checks have passed 🎉 @TomasVotruba I think it is ready now 🎉 🎉 🎉

**Comment by samsonasik** [comment]
Rebased.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
