### PR TITLE
[Php72] Handle crash on Concat after FuncCall on CreateFunctionToAnonymousFunctionRector

### LINKED ISSUE #8682: Could not process "/home/pdavie/src2/html/includes/HTML/QuickForm/Rule/Compare.php"
I have inherited a horrendous old codebase and am trying to migrate it to PHP 8.3 (don't know if I am on a fool's errand)...  I have attached the problem file and the rector config file.

[rector.php.txt](https://github.com/user-attachments/files/15936284/rector.php.txt)
[Compare.php.txt](https://github.com/user-attachments/files/15936285/Compare.php.txt)

[ERROR] Could not process "/home/pdavie/src2/html/includes/HTML/QuickForm/Rule/Compare.php" file, due to:              
         "System error: "Syntax error, unexpected T_VARIABLE, expecting ';'1"                                           
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(146):                         
         PhpParser\ParserAbstract->doParse()                                                                            
         #1 vendor/rector/rector/src/PhpParser/Parser/SimplePhpParser.php(55): PhpParser\ParserAbstract->parse()        
         #2 vendor/rector/rector/src/PhpParser/Parser/InlineCodeParser.php(133):                                        
         Rector\PhpParser\Parser\SimplePhpParser->parseString()                                                         
         #3 vendor/rector/rector/src/PhpParser/Parser/InlineCodeParser.php(103):                                        
         Rector\PhpParser\Parser\InlineCodeParser->parseCode()                                                          
         #4 vendor/rector/rector/rules/Php72/Rector/FuncCall/CreateFunctionToAnonymousFunctionRector.php(150):          
         Rector\PhpParser\Parser\InlineCodeParser->parseString()                                                        
         #5 vendor/rector/rector/rules/Php72/Rector/FuncCall/CreateFunctionToAnonymousFunctionRector.php(109):          
         Rector\Php72\Rector\FuncCall\CreateFunctionToAnonymousFunctionRector->parseStringToBody()                      
         #6 vendor/rector/rector/src/Rector/AbstractRector.php(139):                                                    
         Rector\Php72\Rector\FuncCall\CreateFunctionToAnonymousFunctionRector->refactor()                               
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):                          
         Rector\Rector\AbstractRector->enterNode()                                                                      
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                          
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):                         
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #17 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):                         
         PhpParser\NodeTraverser->traverseNode()                                                                        
         #18 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):                          
         PhpParser\NodeTraverser->traverseArray()                                                                       
         #19 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(41):                              
         PhpParser\NodeTraverser->traverse()                                                                            
         #20 vendor/rector/rector/src/Application/FileProcessor.php(110):                                               
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()                                                 
         #21 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(204):                                    
         Rector\Application\FileProcessor->processFile()                                                                
         #22 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(159):                                    
         Rector\Application\ApplicationFileProcessor->processFile()                                                     
         #23 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(136):                                    
         Rector\Application\ApplicationFileProcessor->processFiles()                                                    
         #24 vendor/rector/rector/src/Console/Command/ProcessCommand.php(117):                                          
         Rector\Application\ApplicationFileProcessor->run()                                                             
         #25 vendor/rector/rector/vendor/symfony/console/Command/Command.php(327):                                      
         Rector\Console\Command\ProcessCommand->execute()                                                               
         #26 vendor/rector/rector/vendor/symfony/console/Application.php(960):                                          
         RectorPrefix202406\Symfony\Component\Console\Command\Command->run()                                            
         #27 vendor/rector/rector/vendor/symfony/console/Application.php(333):                                          
         RectorPrefix202406\Symfony\Component\Console\Application->doRunCommand()                                       
         #28 vendor/rector/rector/src/Console/ConsoleApplication.php(53):                                               
         RectorPrefix202406\Symfony\Component\Console\Application->doRun()                                              
         #29 vendor/rector/rector/vendor/symfony/console/Application.php(216):                                          
         Rector\Console\ConsoleApplication->doRun()                                                                     
         #30 vendor/rector/rector/bin/rector.php(130): RectorPrefix202406\Symfony\Component\Console\Application->run()  
         #31 vendor/rector/rector/bin/rector(5): require_once('...')                                                    
         #32 vendor/bin/rector(119): include('...')                                                                     
         #33 {main}". On line: 272

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8682

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @pdavie

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it to have faster feedback to test ;)

**Comment by pdavie** [comment]
Thank you very much for your prompt work!!

**Comment by samsonasik** [comment]
@pdavie looking again on the result, the result is different, see

- php 7.1 create_function  https://3v4l.org/GdOs2#v7.1.33 result is `3`
- php 7.2+ closure: https://3v4l.org/TVLbM result is "1+2"

the real value of `$operator` seems needs to be appended

**Comment by samsonasik** [comment]
Reverting at https://github.com/rectorphp/rector-src/pull/6020

**Pull request merged**
