### PR TITLE
[ECS] Import SetList ECS after Option Skip

### PR DESCRIPTION
**Pull request by samsonasik**
To avoid the Skip Option in imported Option Skip overriden by existing Skip option in current config.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I see. This should be handled directly in ECS if possible. It worked before IMO.

What do you think?

**Comment by samsonasik** [comment]
Yes, I think it should be handled by ECS to merge with existing skip option.

**Comment by samsonasik** [comment]
I created failing fixture PR to symplify for it https://github.com/symplify/symplify/pull/3536

**Comment by TomasVotruba** [comment]
After dicussion, we agreed this is Symfony feature. The last parameter in the main configuraiton file `rector.php` always wins. So it's important to use "SKIP" option there.

**Pull request merged**
