### PR TITLE
Remove deprecated and cleaned defluent config

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@samsonasik Hey, could you handle the new duplicated variable name rule? :) The one failing in PHPStan CI.

Basically it united variables names, to avoid possible casing bug on 2 similar but different named variables. The fix could look like:

```diff
-$realvalue = 100;
+$realValue = 100;

 $realValue = 500;
```

Basically all variable must have the same name casing.

**Comment by TomasVotruba** [comment]
Sets  were resolved in another PR

**Comment by samsonasik** [comment]
@TomasVotruba is the rule is https://github.com/symplify/symplify/pull/4230 ?

**Comment by TomasVotruba** [comment]
Yes :+1:  and duplciated constant regexes.

Basically to uncomment these 2 lines:
https://github.com/rectorphp/rector-src/blob/c3e31f067de83606b46188d26fcca61a3e89c3c8/phpstan.neon#L712-L714

**Comment by samsonasik** [comment]
I see https://github.com/rectorphp/rector-src/blob/c3e31f067de83606b46188d26fcca61a3e89c3c8/phpstan.neon#L713

**Comment by samsonasik** [comment]
It seems various cases actually valid, eg, the following:

```php
    private function storeConfigurationDataHash(string $filePath, string $configurationHash): void
    {
        $key = CacheKey::CONFIGURATION_HASH_KEY . '_' . Strings::webalize($filePath);
        $this->invalidateCacheIfConfigurationChanged($key, $configurationHash);

        $this->cache->save($key, CacheKey::CONFIGURATION_HASH_KEY, $configurationHash);
    }
```

**Comment by samsonasik** [comment]
Ok, it seems vaiable naming is check all places, not only current file.

**Pull request closed without merging**
