### PR TITLE
Remove e2e/finalize on rector/rector repo build

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba @staabm per https://github.com/rectorphp/rector-src/pull/4326#issuecomment-1608146737

the rector/rector e2e/finalize build is error: https://github.com/rectorphp/rector/actions/runs/5382084725/jobs/9767016438#step:5:1

The e2e/finalize on rector/rector no longer works, that's due to no path specified in config, even added, the test with `--dry-run` will make status 2 as show the diff, which means the CI will still stopped.

The e2e itself is old test which I think we can just remove it.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by staabm** [comment]
thanks for fixing

**Comment by samsonasik** [comment]
@staabm thank you for verify, @TomasVotruba I am merging it so we have green in rector/rector build ;)

**Comment by TomasVotruba** [comment]
Sure, seems good to me :)

**Pull request merged**
