### PR TITLE
[Reflection] Avoid error Call to a member function getType() on null on ReflectionResolver

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Could you provide the failing test case as well? Reflection is very sensistive part, so we better have it covered

**Comment by samsonasik** [comment]
I checked it in `CodeIgniter4` project that trigger the error. I will try.

**Comment by samsonasik** [comment]
For error shown in CI https://github.com/codeigniter4/CodeIgniter4/runs/2934093327#step:10:5

**Comment by samsonasik** [comment]
Failing test fixture added https://github.com/rectorphp/rector-src/pull/334/commits/4f71ba198519dcb5560224ef98ae9509c7d4cf1e

**Comment by samsonasik** [comment]
Fixed with include fixture tests 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :clap: :+1:

**Pull request merged**
