### PR TITLE
Add ReplaceUnnecessaryEmptyCallsWithNativeExpressionsRector

### PR DESCRIPTION
**Pull request by ostrolucky**
I've added this rector to https://github.com/ostrolucky/rector-rules, but I think it's a good fit to have it here instead

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, we already have such a rule: https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#disallowedemptyrulefixerrector


Instead, extend it's behavior to be as strict as possible.

Thank you

**Comment by ostrolucky** [comment]
This is a non-strict version though

**Comment by ostrolucky** [comment]
Can you clarify @TomasVotruba what do you propose? You want me to add config option in `Rector\Strict\Rector\Empty_\DisallowedEmptyRuleFixerRector` to make it non-strict?

**Comment by samsonasik** [comment]
@ostrolucky you can create your own custom rule for your use case.

**Pull request closed without merging**
