### PR TITLE
Remove removeNode() from RemoveDeadReturnRector, merge RemoveLastReturnRector to RemoveDeadReturnRector

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by clxmstaab** [comment]
the 0.17.1 release notes do not mention that RemoveLastReturnRector was removed and what todo instead

**Comment by TomasVotruba** [comment]
It was merged to RemoveDeadReturnRector, that should be used instead

**Comment by clxmstaab** [comment]
yeah, I found it thru research from this PR here, but it is not mentioned in the release notes ;-)

**Comment by TomasVotruba** [comment]
Good point :)


Added: https://github.com/rectorphp/rector/releases/tag/0.17.1

**Pull request merged**
