### PR TITLE
[Php81] Skip const Fetch non static method on FirstClassCallableRector

### LINKED ISSUE #7565: Incorrect behavior of FirstClassCallableRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/d88e0aa7-1e19-4877-98c0-b6a6feab8aec

```php
<?php

final class DemoFile
{
    public function provideListenerPriority(): array
    {          
         return [
             'listener' => [
                 [SessionListener::class, 'onKernelRequest'],
             ],       
         ];
    }
}
class SessionListener
{
    public function onKernelRequest(RequestEvent $event)
    {  
    }
}
```

### Responsible rules

* `FirstClassCallableRector`

## Expected Behavior

Skip this case

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
class SomeExternalObject
{
    public function sleepOver(){}
}

final class SkipNonStaticWithOtherObjectConstFetch
{
    public function provideListenerPriority(): array
    {
         return [
             'listener' => [
                 [SomeExternalObject::class, 'sleepOver'],
             ],
         ];
    }
}
```

should be skipped as the external object method call is not static, that cause error:

```
Fatal error: Uncaught Error: Non-static method SomeExternalObject::sleepOver() cannot be called statically in 
```

Ref https://3v4l.org/uUZCF
Fixes https://github.com/rectorphp/rector/issues/7565

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @alexey-rus

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
Rebased, also skipped external private method https://github.com/rectorphp/rector-src/pull/3183/commits/fac7bdd7ae6899540d33b6dc3fc8f970b3777e86

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
