### PR TITLE
Faking scope context for trait reflections

### PR DESCRIPTION
**Pull request by zingimmick**
Because PHPStan does not traverse trait without a class, Rector used class `Rector\Core\Stubs\DummyTraitClass` for faking class reflection for trait reflections. But this solution makes it impossible to get param php doc from the faked scope, which makes the param tags no longer useful in traits.

For example, in this example, because the param tag `@param string|null $column` can't get in the faked scope, the type of `$column` resolved from `NodeTypeResolver` will be `mixed` not `string|null` 
```php
trait ConstructInTrait
{
    /**
     * @var string
     */
    private $column;

    /**
     * @param string|null $column
     */
    public function __construct(string $property, $column = null)
    {
        // the type of parameter column will be mixed in the faked scope, which should be string|null
        $this->column = $column ?? $property;
    }
}
```

This PR changing the scope context in a crude way,  just for reference.

### CODE REVIEW

**Comment by zingimmick** [comment]
Resolved type of the coalesce operator

Class
```
array (1)
   0 => PHPStan\Type\UnionType #11869
   |  types: array (2)
   |  |  0 => PHPStan\Type\StringType #11803
   |  |  1 => PHPStan\Type\StringType #11805
```

Trait
```
array (1)
   0 => PHPStan\Type\UnionType #12816
   |  types: array (2)
   |  |  0 => PHPStan\Type\MixedType #12786
   |  |  |  isExplicitMixed: false
   |  |  |  subtractedType: null
   |  |  1 => PHPStan\Type\StringType #11728
```

**Comment by samsonasik** [comment]
@zingimmick could you update PR title and description with the changes/solution applied ? Thank you.

**Comment by zingimmick** [comment]
> @zingimmick could you update PR title and description with the changes/solution applied ? Thank you.

@samsonasik The title and description have been updated. The purpose of this changes is to resolve the method's PhpDoc from the scope.

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
