### PR TITLE
Update to PHPStan ^1.3

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba it seems it cause error:

```bash
 1) Rector\Core\Tests\Exclusion\ExclusionManagerTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Symplify\PHPStanRules\Exception\ShouldNotHappenException: 

/home/runner/work/rector-src/rector-src/vendor/symplify/package-builder/src/Reflection/PrivatesAccessor.php:43
/home/runner/work/rector-src/rector-src/vendor/symplify/package-builder/src/Reflection/PrivatesAccessor.php:21
/home/runner/work/rector-src/rector-src/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php:202
/home/runner/work/rector-src/rector-src/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php:107
/home/runner/work/rector-src/rector-src/packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php:36
/home/runner/work/rector-src/rector-src/src/Application/FileProcessor.php:34
/home/runner/work/rector-src/rector-src/src/Application/FileProcessor/PhpFileProcessor.php:128
/home/runner/work/rector-src/rector-src/src/Application/FileProcessor/PhpFileProcessor.php:52
/home/runner/work/rector-src/rector-src/src/Application/ApplicationFileProcessor.php:131
/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:177
/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:131
/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:115
/home/runner/work/rector-src/rector-src/tests/Exclusion/ExclusionManagerTest.php:21
```

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
