### PR TITLE
Revert "add DockerHub overview update workflow (#249)"

### PR DESCRIPTION
**Pull request by rajyan**
This reverts commit c2dbe67cb67e0e08e69029ba1516173723021d40.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@samsonasik Could you handle these Docker update PRs? I'm working on parallel run and need to focus on fully

**Comment by samsonasik** [comment]
@TomasVotruba ok, I prefer this revert one for now.

**Comment by samsonasik** [comment]
Thank you @rajyan

**Comment by rajyan** [comment]
sorry for the confusion

**Pull request merged**
