### PR TITLE
[Php74] Skip AddLiteralSeparatorToNumberRector on already formatted literals

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6188

### CODE REVIEW

**Review by lptn — APPROVED** [review]
@samsonasik

looks good, thanks a lot!

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Neat fix :) Thank you :+1:

**Pull request merged**
