### PR TITLE
[TypeDeclaration] Use native type detection instead of docblock on AssignToPropertyTypeInferer for TypedPropertyFromAssignsRector

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
closing for now as caused invalid tranformation on valid intersecton type expectation:

```diff

There were 2 failures:

1) Rector\Tests\TypeDeclaration\Rector\Property\TypedPropertyFromAssignsRector\TypedPropertyFromAssignsComplexTypesRectorTest::test with data set #3
Failed on fixture file "intersection_type_with_setup.php.inc"
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 
 class IntersectionTypeWithSetup extends TestCase
 {
-    private \DateTime&\PHPUnit\Framework\MockObject\MockObject $property;
+    /**
+     * @var DateTime&MockObject
+     */
+    private \PHPUnit\Framework\MockObject\MockObject $property;
```

**Comment by samsonasik** [comment]
Re-open, set type based on caller on this MockObject seems ok, with keep `@var DateTime&MockObject` usage

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Looks good, thank you :+1:

**Pull request merged**
