### PR TITLE
[Php55] Handle pre-slash string on StringClassNameToClassConstantRector

### PR DESCRIPTION
**Pull request by samsonasik**
String "\Rector\Tests\Php55\Rector\String_\StringClassNameToClassConstantRector\Source\AnotherClass" is different with `\Rector\Tests\Php55\Rector\String_\StringClassNameToClassConstantRector\Source\AnotherClass::class`

ref https://3v4l.org/6ZChM

so should be handled with add "\\" string prefix instead.

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
What about keeping the original value and making use of the `::class` reference?

```php
'\\' . SomeClass::class;
```

I think the goal here is to have a class reference for such strings too.

**Comment by samsonasik** [comment]
Ok, updated with add `"\\"` string prefix. https://github.com/rectorphp/rector-src/pull/2905/commits/a8b1fd3ec8fb080a2073d02bf9db79b0c215cd19

**Comment by samsonasik** [comment]
Ref https://3v4l.org/VJJ7u for new transformation

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
