### PR TITLE
[Core] Handle Scope not available on DowngradeArrayIsListRector+DowngradePregUnmatchedAsNullConstantRector

### LINKED ISSUE #7252: DowngradeArrayIsListRector: System error: "Scope not available on ..."
I upgraded to the latest version of Rector, and [now I'm getting an error](https://github.com/leoloso/PoP/runs/7016143666?check_suite_focus=true) when downgrading [Symfony String](https://symfony.com/doc/current/components/string):

```
[ERROR] Could not process "vendor/symfony/string/AbstractUnicodeString.php"    
         file, due to:                                                          
         "System error: "Scope not available on "PhpParser\Node\Expr\FuncCall"  
         node with parent node of "", but is required by a refactorWithScope()  
         method of                                                              
         "Rector\DowngradePhp81\Rector\FuncCall\DowngradeArrayIsListRector"     
         rule. Fix scope refresh on changed nodes first"                        
         Run Rector with "--debug" option and post the report here:             
        [ https://github.com/rectorphp/rector/i](https://github.com/rectorphp/rector/issues/new)
ssues/new". On line: 23  
 [ERROR] Could not process "vendor/symfony/string/ByteString.php" file, due to: 
         "System error: "Scope not available on "PhpParser\Node\Expr\FuncCall"  
         node with parent node of "", but is required by a refactorWithScope()  
         method of                                                              
         "Rector\DowngradePhp81\Rector\FuncCall\DowngradeArrayIsListRector"     
         rule. Fix scope refresh on changed nodes first"                        
         Run Rector with "--debug" option and post the report here:             
        [ https://github.com/rectorphp/rector/i](https://github.com/rectorphp/rector/issues/new)
ssues/new". On line: 23
```

The problem happens with the downgrade set:

```php
$rectorConfig->sets([
    DowngradeLevelSetList::DOWN_TO_PHP_71,
]);
```

But applying only that rule, then the problem does not happen:

```php
$rectorConfig->rule(DowngradeArrayIsListRector::class);
```

## Report

Command using `--debug` (using set `DowngradeLevelSetList::DOWN_TO_PHP_71`):

```
vendor/bin/rector --dry-run process vendor/symfony/string/AbstractUnicodeString.php vendor/symfony/string/ByteString.php --debug
```

Output:

```
[file] vendor/symfony/string/AbstractUnicodeString.php
[rule] Rector\DowngradePhp82\Rector\Class_\DowngradeReadonlyClassRector

[file] vendor/symfony/string/AbstractUnicodeString.php
[rule] Rector\Removing\Rector\Class_\RemoveInterfacesRector

[file] vendor/symfony/string/AbstractUnicodeString.php
[rule] Rector\DowngradePhp80\Rector\Class_\DowngradeAttributeToAnnotationRector

[file] vendor/symfony/string/AbstractUnicodeString.php
[rule] Rector\DowngradePhp80\Rector\Class_\DowngradePropertyPromotionRector

[file] vendor/symfony/string/AbstractUnicodeString.php
[rule] Rector\DowngradePhp81\Rector\ClassConst\DowngradeFinalizePublicClassConstantRector

[file] vendor/symfony/string/AbstractUnicodeString.php
[rule] Rector\DowngradePhp72\Rector\FuncCall\DowngradePregUnmatchedAsNullConstantRector

...

(And a lot like this... had to truncate because GitHub issue throws error: " There was an error creating your Issue: body is too long, body is too long (maximum is 65536 characters). ")
...

[file] vendor/symfony/string/ByteString.php
[rule] Rector\DowngradePhp73\Rector\String_\DowngradeFlexibleHeredocSyntaxRector

[file] vendor/symfony/string/ByteString.php
[rule] Rector\DowngradePhp80\Rector\Expression\DowngradeMatchToSwitchRector

[file] vendor/symfony/string/ByteString.php
[rule] Rector\DowngradePhp80\Rector\Expression\DowngradeThrowExprRector

[file] vendor/symfony/string/ByteString.php
[rule] Rector\DowngradePhp81\Rector\FuncCall\DowngradeFirstClassCallableSyntaxRector

[file] vendor/symfony/string/ByteString.php
[rule] Rector\DowngradePhp81\Rector\FuncCall\DowngradeArrayIsListRector


                                                                                                                        
 [ERROR] Could not process "vendor/symfony/string/AbstractUnicodeString.php" file, due to:                              
         "System error: "Scope not available on "PhpParser\Node\Expr\FuncCall" node with parent node of "", but is      
         required by a refactorWithScope() method of "Rector\DowngradePhp81\Rector\FuncCall\DowngradeArrayIsListRector" 
         rule. Fix scope refresh on changed nodes first"                                                                
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
         line: 23                                                                                                       
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "vendor/symfony/string/ByteString.php" file, due to:                                         
         "System error: "Scope not available on "PhpParser\Node\Expr\FuncCall" node with parent node of "", but is      
         required by a refactorWithScope() method of "Rector\DowngradePhp81\Rector\FuncCall\DowngradeArrayIsListRector" 
         rule. Fix scope refresh on changed nodes first"                                                                
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
         line: 23                                                                                                       
                                                                                                                        
```

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
function test()
{
        $match = ((\PREG_PATTERN_ORDER | \PREG_SET_ORDER) & $flags) ? 'preg_match_all' : 'preg_match';
        $match($regexp.'u', $this->string, $matches, $flags | \PREG_UNMATCHED_AS_NULL, $offset);
}
```

it currently make error:

```bash
There was 1 error:

1) Rector\Core\Tests\Issues\ScopeNotAvailable\PregUnmatchedTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\ShouldNotHappenException: Scope not available on "PhpParser\Node\Expr\FuncCall" node with parent node of "", but is required by a refactorWithScope() method of "Rector\DowngradePhp81\Rector\FuncCall\DowngradeArrayIsListRector" rule. Fix scope refresh on changed nodes first
```

Applied rules:

```php
Rector\DowngradePhp72\Rector\FuncCall\DowngradePregUnmatchedAsNullConstantRector;
Rector\DowngradePhp81\Rector\FuncCall\DowngradeArrayIsListRector;
```

Fixes https://github.com/rectorphp/rector/issues/7252

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @leoloso

**Comment by leoloso** [comment]
That was quick! Thanks @samsonasik 🙏

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I updated to always use `ChangedNodeScopeRefresher::refresh()` to refresh against added Node.

All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Let's ship it :)

**Pull request merged**
