### PR TITLE
[TypedPropertyFromAssignsRector] Handle parse_url() native function with second arg on TypedPropertyFromAssignsRector

### LINKED ISSUE #8928: Incorrect behavior of TypedPropertyFromAssignsRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 1.2.10     |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/a0c60c4c-6471-4028-bf9b-f1f1660ccdba

```php
<?php

final class DemoFile
{
    private $host = null;
    
    public function _cosntructor(string $url)
    {
        $this->host = parse_url($url, \PHP_URL_HOST);
    }
}
```

### Responsible rules

* `TypedPropertyFromAssignsRector`

## Expected Behavior

see https://www.php.net/manual/en/function.parse-url.php
When the component parameter is passed, `parse_url` returns `string|null` (or `int|null` for the specific `\PHP_URL_PORT` component)

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8928

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @yguedidi 

this is based on phpstan https://phpstan.org/r/09bc2166-3fc2-4f92-88f4-35e2e51d9e08

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by yguedidi** [comment]
Impressive!! So efficient, thank you @samsonasik ! 👍

**Comment by samsonasik** [comment]
@yguedidi it seems cause a bug when default value is part of the union, eg:

```
    private $host = true;
```

it cause invalid result:

```
    private string|false|null $host = null;
```

I will check if that possible to handle on new PR:

- https://github.com/rectorphp/rector-src/pull/6563

otherwise, I will just use `bool` over `false` as today is release day :)

**Pull request merged**
