### PR TITLE
[e2e] [printer] Fix short open tag mixed php+html cause surplus <?php 

### LINKED ISSUE #7789: Incorrect behavior of RemoveDeadStmtRector (and others?) with short echo tags
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/a7122f39-c255-4c56-908c-6f412f696ec4

```php
<?php
$args;
?>
<img src="<?= esc_url($image_src); ?>" alt="">
```

Additionally, from https://getrector.com/demo/f3d8ac7d-212b-4cff-86bd-5939a2ee338f ,

```php 
<?php
function test_callback() {
  // var_dump($output);
  ?>
  <div class="wrap">
    <img src="<?= escape('hi there'); ?>">
  </div>
  <?php
}
```

### Responsible rules

* `RemoveDeadStmtRector`
* No rules listed for second demo link

## Expected Behavior

For the first demo link, removing `$args;` and for the second either removing or ignoring the commented var_dump, but for both not also adding php open/close tags around otherwise functional short echo tag.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7789
Ref https://getrector.com/demo/a27a9525-7cb7-49dc-bea4-0fbd52c29e2c

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @bananastalktome

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Comment by bananastalktome** [comment]
@samsonasik Thank you! I can confirm that this fixes the issue I had in https://github.com/rectorphp/rector/issues/7789 .

**Comment by samsonasik** [comment]
@bananastalktome thank you for verify it 👍

**Pull request merged**
