### PR TITLE
[DowngradePhp80/72] Handle DowngradeTrailingCommasInParamUseRector+DowngradeParameterTypeWideningRector

### LINKED ISSUE #7423: Incorrect behavior of DowngradeTrailingCommasInParamUseRector + DowngradeParameterTypeWideningRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/03929096-8d31-4b8c-b0d1-2de10e4f19f9

```php
<?php

class ParentClass
{
    public function execute(
        string $param, // This code must be downgraded with 2 rules
    ): void {
    }
}

class ChildClass extends ParentClass
{
    public function execute(
        $param
    ): void {
    }
}
```

### Responsible rules

* `DowngradeTrailingCommasInParamUseRector`
* `DowngradeParameterTypeWideningRector`

## Expected Behavior

The PHP code `string $param,` above contains two features to downgrade:

- Removing the trailing comma
- Removing the `string` type

When running `DowngradeTrailingCommasInParamUseRector` alone, it works well (https://getrector.org/demo/c420a192-6e01-40ca-a7ac-a47a7bdc7c09).

When running `DowngradeParameterTypeWideningRector` alone, it works well (https://getrector.org/demo/89118419-e522-460b-8477-f219dd522a21).

But when running both `DowngradeTrailingCommasInParamUseRector` and `DowngradeParameterTypeWideningRector`, only `DowngradeTrailingCommasInParamUseRector` is applied (https://getrector.org/demo/8e7337b5-c0d4-49dd-8f3b-3491850a5d5f).

This is the diff with how the result should be:

```diff
class ParentClass
{
-    public function execute(string $param): void {
+    public function execute($param): void {
    }
}

class ChildClass extends ParentClass
{
    public function execute($param): void {
    }
}
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7423

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @leoloso

**Comment by leoloso** [comment]
As always, so quick!!!! 👏👏👏

**Comment by samsonasik** [comment]
I added failing fixture for multi rules for [DowngradeLevelSetList::DOWN_TO_PHP_71](https://github.com/rectorphp/rector-src/pull/2843/commits/4c07767610de2d5390b1dff8114f258e47a0e644)

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by TomasVotruba** [comment]
Thank you @samsonasik :clap:

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Pull request merged**
