### PR TITLE
 [DeadCode] Skip RemoveAssignOfVoidReturnFunctionRector on used in next statement

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
I added `ExprUsedInNextNodeAnalyzer` service to be re-used.

**Comment by samsonasik** [comment]
I added ExprUsedInNodeAnalyzer service to be re-used on find expr used in node re-used.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by TomasVotruba** [comment]
Is this ready to merge?
Have you run tests locally? 

I can merge it then :+1:

**Comment by samsonasik** [comment]
Yes, it is ready for merge, I tested locally in used in 3 rules:

Screen Shot 2021-07-15 at 15 15 11

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
