### PR TITLE
[Php81] Fix regression skip call by ref on ReadOnlyPropertyRector

### LINKED ISSUE #8082: Properties passed by reference are marked as read-only
# Bug Report

| Subject        | Details |
| :------------- | :-------|
| Rector version | v0.17.7 |

It seems that since rectorphp/rector-src#4429, properties that are not marked as readonly are now converted to readonly properties, even if they are passed around by reference later. PHPStan complains about it:

```
Parameter #1 $someArray is passed by reference so it does not accept readonly property Foo::$someArray.
```

(Taken from a `phpstan analyse` on the code example posted below.)

## Minimal PHP Code Causing Issue

https://getrector.com/demo/1a64b200-1b12-4023-8d4b-b8467282aff7

## Expected Behaviour

AFAICS, the property should not be changed to `readonly`, see https://3v4l.org/JA129.

---

Related PR: CPS-IT/project-builder#256

### PR DESCRIPTION
**Pull request by samsonasik**
The lower readonly complexity in PR:

- https://github.com/rectorphp/rector-src/pull/4429

cause regression issue : 

- https://github.com/rectorphp/rector/issues/8082

this PR try to fix it.

Fixes https://github.com/rectorphp/rector/issues/8082

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @eliashaeussler

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Comment by eliashaeussler** [comment]
Thanks @samsonasik 💛

**Comment by samsonasik** [comment]
@eliashaeussler yes :), for note, this only cover on `__construct()`.

For in usage on other method, this patch doesn't cover:

https://getrector.com/demo/51cb28b6-14bf-4d7e-9e23-e9b2f269cdb4

we may need a real use case if it going to be used in other method beside __construct :)

**Comment by eliashaeussler** [comment]
@samsonasik Our use case is as follows:

We have a property `$output` which is assigned in the constructor. This property is passed later in a method `prepare()` to a method of another class and it's passed by reference.

Here are the relevant cases for better understanding:

* Property: https://github.com/CPS-IT/project-builder/blob/2.3.0/src/Console/Simulation.php#L51
* Method call: https://github.com/CPS-IT/project-builder/blob/2.3.0/src/Console/Simulation.php#L93
* Called method (you can see that the parameter `$output` is passed by reference): https://github.com/CPS-IT/project-builder/blob/main/src/Resource/Local/Composer.php#L61

If you want, I can provide a (probably failing) test case for this scenario.

**Comment by samsonasik** [comment]
@eliashaeussler failing test case fixture PR would be great 👍

**Comment by eliashaeussler** [comment]
@samsonasik I created #4613 :)

**Pull request merged**
