### PR TITLE
removed unused class TypeWithClassNameTypeMapper

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by staabm** [comment]
@TomasVotruba all checks green, ready to remove the unused class

**Comment by TomasVotruba** [comment]
Thanks! How did you discover this one is unused?
What mapper handles conversion to `'string-class'`?

**Comment by staabm** [comment]
> Thanks! How did you discover this one is unused?

phpstorm reported the class beeing unused

> What mapper handles conversion to 'string-class'?

I have no idea.

**Comment by staabm** [comment]
its interessting.. phpstorm also reports `VoidTypeMapper` beeing unused.

same for `SelfObjectTypeMapper`, and `ObjectTypeMapper`, `IntersectionTypeMapper`

example:

grafik

**Comment by TomasVotruba** [comment]
> phpstorm reported the class beeing unused

I would not trust PHPStorm on unused elements :D it has no idea about interfaces, abstract classes, use in YAML/NEON/TWIG/LATTE/Doctrine magic. It burned me so many times.

**Comment by TomasVotruba** [comment]
This case is not tested, that's why CI passes. Could you add a test for this class to avoid the removal in the future?

**Comment by samsonasik** [comment]
This may be used by: 

https://github.com/rectorphp/rector-src/blob/dc056580e0deb1f6410757200f55e7c5a83cf97c/packages/PHPStanStaticTypeMapper/PHPStanStaticTypeMapper.php#L52

like `ObjectTypeMapper` used by `TypedPropertyRector` on call:

```php
$node->type = $this->staticTypeMapper->mapPHPStanTypeToPhpParserNode(
       $types[0]->getBound(),
       TypeKind::KIND_PROPERTY
);
```

**Comment by TomasVotruba** [comment]
Closing as class is used

**Pull request closed without merging**
