### PR TITLE
Move DoctrineRelationPropertyTypeInferer to rector-doctrine

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref https://github.com/rectorphp/rector/issues/6762

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba it seems make error on downgrade scoped:

```bash
 Parse error: rector-prefixed-downgraded/vendor/rector/rector-doctrine/src/NodeManipulator/ColumnPropertyTypeResolver.php:37
    35|      * @var array<string, \PHPStan\Type\Type>
    36|      */
  > 37|     private $doctrineTypeToScalarType = [
    38|         'tinyint' => new \PHPStan\Type\BooleanType(),
    39|         // integers
Constant expression contains invalid operations in rector-prefixed-
```

https://github.com/rectorphp/rector-src/runs/4537147879?check_suite_focus=true#step:14:77

**Comment by TomasVotruba** [comment]
We're missing new in initializers downagade rule for PHP 8.1

**Comment by samsonasik** [comment]
There is already https://github.com/rectorphp/rector-src/blob/main/rules/DowngradePhp81/Rector/FunctionLike/DowngradeNewInInitializerRector.php but missing new inside array

**Comment by samsonasik** [comment]
Fixed at https://github.com/rectorphp/rector-src/pull/1508

**Pull request merged**
