### PR TITLE
[Core] Remove unneeded ChangedNodeAnalyzer service

### PR DESCRIPTION
**Pull request by samsonasik**
It seems `ChangedNodeAnalyzer` is no longer needed

### CODE REVIEW

**Comment by samsonasik** [comment]
For only change docblock, there is already e2e test for it https://github.com/rectorphp/rector-src/tree/main/e2e/applied-rule-change-docblock

**Comment by samsonasik** [comment]
Also remove `HAS_PHP_DOC_INFO_JUST_CHANGED` attribute as when Rector rule returns Node, it will show the diff + rules applied when changed on Node with line.

**Comment by samsonasik** [comment]
I added e2e test for `RemoveUselessVarTagRector` to show that `HAS_PHP_DOC_INFO_JUST_CHANGED` no longer needed https://github.com/rectorphp/rector-src/pull/1868/commits/e850121e2e943035433241523dcaeaa11343fc70

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
