### PR TITLE
[DeadCode] Skip private dataProvider method on RemoveUnusedPrivateMethodRector

### LINKED ISSUE #8910: RemoveUnusedPrivateMethodRector removes PHPUnit data providers
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.2.6             |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/327f47bc-8129-4400-a71d-859fe94918c9

```php
<?php

class PaymentMethodTest
{
    /**
     * @dataProvider fooDataProvider
     */
    public function testFoo(): void
    {
        
    }

    private function fooDataProvider(): array
    {
        return [
            [],
        ];
    }
}
```

### Responsible rules

* `RemoveUnusedPrivateMethodRector`

## Expected Behavior

Data provider should not be removed.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8910

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @umpirsky

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by umpirsky** [comment]
Thanks!

I guess this will be released in 1.2.11? Any idea when?

**Comment by TomasVotruba** [comment]
This will be part of 2.0 upgrade, as we keep only single release line.

See https://github.com/rectorphp/rector/issues/8815#issuecomment-2493467044

**Pull request merged**
