### PR TITLE
[AutoImport] Handle case insensitive name collide on auto import

### LINKED ISSUE #8148: fatal error after importNames()
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main  |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/aa739bd2-ee2a-4e79-ae69-138c02e9f1ea

----

the error reported is not related to the rule configured, but running the sandbox without any rule leads to

grafik

therefore I picked a arbitrary rule

## Expected Behaviour

rector should not produce new code, which fatal errors - see https://3v4l.org/eAZRa

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8148

### CODE REVIEW

**Comment by samsonasik** [comment]
@staabm the issue seems when both class not yet imported, as the `UseImportsResolver->resolve()` not yet refreshed.

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @staabm

**Comment by samsonasik** [comment]
use const case insensitive is allowed, so I leave as is, see https://3v4l.org/lteVa

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba let's merge it to have faster feedback to test ;)

**Comment by staabm** [comment]
thanks!

**Comment by staabm** [comment]
do we have the same problem here?

- https://github.com/rectorphp/rector-src/blob/c03fd2ad2625f1a0cf6a02d9875078b7114381ad/packages/StaticTypeMapper/ValueObject/Type/AliasedObjectType.php#L54
- https://github.com/rectorphp/rector-src/blob/c03fd2ad2625f1a0cf6a02d9875078b7114381ad/packages/StaticTypeMapper/ValueObject/Type/FullyQualifiedObjectType.php#L26
- https://github.com/rectorphp/rector-src/blob/c03fd2ad2625f1a0cf6a02d9875078b7114381ad/rules/CodingStyle/ClassNameImport/ClassNameImportSkipVoter/FullyQualifiedNameClassNameImportSkipVoter.php#L36-L40

?

**Comment by samsonasik** [comment]
@staabm probably, could you create failing testcase at demo page  https://getrector.com/demo or probably new fixture on ?

https://github.com/rectorphp/rector-src/tree/main/tests/Issues/AutoImport/Fixture

thank you.

**Comment by staabm** [comment]
I think this one reproduces the problem: 

https://getrector.com/demo/4d8aeddb-8f37-4695-b322-491d4d719475

**Comment by staabm** [comment]
hmm no it doesn't. I guess my problem I see locally is caused, because the fix for this issue is not yet part of a release

**Comment by samsonasik** [comment]
@staabm 0.18.1 just tagged https://github.com/rectorphp/rector/releases/tag/0.18.1

**Pull request merged**
