### PR TITLE
[TypeDeclaration] Remove PhpDocTypeChanger->changeVarType() on TypedPropertyFromAssignsRector

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba per discussion on https://github.com/rectorphp/rector-src/pull/3161#discussion_r1040950002

This PR remove  `PhpDocTypeChanger->changeVarType()` without changing Property Type on `TypedPropertyFromAssignsRector`

The rule is also using:

```php
$this->propertyTypeDecorator->decoratePropertyUnionType($inferredType, $typeNode, $node, $phpDocInfo);
```

which chaning both type and docblock, but as the service is used in multiple rules in `vendor/`, so I added `$changeVarTypeFallback` for it, so it is safer.

so the usage can be:

```php
$this->propertyTypeDecorator->decoratePropertyUnionType($inferredType, $typeNode, $node, $phpDocInfo, false);
```

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
@TomasVotruba I added `$changeVarTypeFallback` flag param on `PropertyTypeDecorator->decoratePropertyUnionType()` as method re-use in vendor so it only apply typed strict on this rule only, as the method is used in `vendor/` as well to avoid broken test in vendor.

**Comment by samsonasik** [comment]
I rolled back add `$changeVarTypeFallback` flag param on `PropertyTypeDecorator->decoratePropertyUnionType()` as it cause error in `rules-tests`

**Comment by samsonasik** [comment]
Not sure why suddently the `rules-tests` error:

```bash

There were 2 errors:

1) Rector\Tests\PSR4\Rector\FileWithoutNamespace\NormalizeNamespaceByPSR4ComposerAutoloadRector\NormalizeNamespaceByPSR4ComposerAutoloadRectorTest::test with data set #10 ('/home/runner/work/rector-src/...hp.inc')
Error: Object of class PhpParser\Node\Stmt\Namespace_ could not be converted to string
```

**Comment by samsonasik** [comment]
CI finally green again 🎉 , let's add back `$changeVarTypeFallback` flag param on `PropertyTypeDecorator->decoratePropertyUnionType()`

**Comment by samsonasik** [comment]
I added back `$changeVarTypeFallback` flag param on `PropertyTypeDecorator->decoratePropertyUnionType()`  https://github.com/rectorphp/rector-src/pull/3163/commits/46c7d73db4fa8f5e8ef3d1ac5b6a36b8aa42d0bf

**Comment by samsonasik** [comment]
Close-ReOpen to restart build.

**Comment by samsonasik** [comment]
Finally 🎉 All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
