### PR TITLE
[Php56] Skip with coalesce assign on AddDefaultValueForUndefinedVariableRector

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I am merging it ;)

**Comment by TomasVotruba** [comment]
Nice catch :1st_place_medal: thank you

**Pull request merged**
