### PR TITLE
 [Core] [Printer] Ensure empty php tag init on original node not re-printed 

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba this is continue of PR:

- https://github.com/rectorphp/rector-src/pull/3283

Ensure empty php tag init on original node not re-printed which may was written on purpose on not re-print HTML.

### CODE REVIEW

**Comment by samsonasik** [comment]
Added test for addnode after node on before and after HTML

**Comment by samsonasik** [comment]
It still buggy on addnode before node:

```diff
There was 1 failure:

1) Rector\Core\Tests\Issues\AddNodeBeforeNodeStmt\AddNodeBeforeNodeStmtTest::test with data set #2 ('/Users/samsonasik/www/rector-...hp.inc')
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 <div>some text</div>
-<?php
-echo 'this is new stmt before if';
+
+echo 'this is new stmt before if';<?php
 if ($a === 1) {
```

**Comment by samsonasik** [comment]
[Fixed 🎉](https://github.com/rectorphp/rector-src/pull/3284/commits/8d1ba9ba49840d34d5307f8aecb3d0787eb1d662), it seems the issue is append to previous HTML, not next.

**Comment by samsonasik** [comment]
It seems cause error on After Node:

```diff
There was 1 failure:

1) Rector\Core\Tests\Issues\AddNodeAfterNodeStmt\AddNodeAfterNodeStmtTest::test with data set #2 ('/Users/samsonasik/www/rector-...hp.inc')
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
+?>
 <div>some text</div>
-<?php
+<?php <?php
 if ($a === 1) {
 }
```

**Comment by samsonasik** [comment]
Not sure about add node before node usage, closing for now.

**Comment by TomasVotruba** [comment]
Feel free to merge these as needed :+1:

**Pull request merged**
