### PR TITLE
[Transform][Php81] Add configurable ReturnTypeWillChangeRector

### LINKED ISSUE #6886: [Transform][Php81]: Add ReturnTypeWillChangeRector
# Feature Request

To allow add `#[\ReturnTypeWillChange]` so it can work on php php 8.1, eg: when original `mixed` return changed to docblock on downgrade rector rule from php 8.1 to php 7.1, then when downgraded version used in php 8.1, the deprecated notice will appear.

The use case is on https://github.com/symplify/symplify/issues/3850#issuecomment-998772731

Note: 

- make configurable for `class -> [...methods]`

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6886

### CODE REVIEW

**Comment by samsonasik** [comment]
I think we should has default values for known class -> methods as they are known class -> methods that needs it, eg: `'ArrayAccess' => ['offsetGet']` so we can implements `AllowEmptyConfigurableRectorInterface`.

When user add more config array, the array should be merged so it applied all default + custom config.

**Comment by TomasVotruba** [comment]
> I think we should has default values for known class -> methods as they are known class -> methods that needs it, eg: 'ArrayAccess' => ['offsetGet'] so we can implements AllowEmptyConfigurableRectorInterface.

Makes sense :+1:  It should contain use cases that we use over and over again.

What is missing here to finish it?

**Comment by samsonasik** [comment]
The missing functionality is the set default value to combine, I will make : 

https://github.com/rectorphp/rector-src/blob/889a682d12e870364e01c17c20e01fe81c368b8b/packages/BetterPhpDocParser/PhpDocParser/PhpDocFromTypeDeclarationDecorator.php#L41-L45

public for re-use here as default.

**Comment by samsonasik** [comment]
@TomasVotruba implemented, with functionality:

_1. with empty config,_ it will use this values as default config

https://github.com/rectorphp/rector-src/blob/889a682d12e870364e01c17c20e01fe81c368b8b/packages/BetterPhpDocParser/PhpDocParser/PhpDocFromTypeDeclarationDecorator.php#L41-L45

_2. with config applied_, it will merge default config + config applied.

The `configure()` method do not need type, only class -> methods

```php
    $services->set(ReturnTypeWillChangeRector::class)
        ->configure([
            'ArrayAccess' => ['offsetExists'],
        ]);
```

that's will result combined:

```php
'ArrayAccess' => ['offsetGet', 'offsetExists'],
```

**Comment by samsonasik** [comment]
@TomasVotruba it's implemented, Github is just so slow running CI, ref tweet https://twitter.com/Ocramius/status/1475394267279511552

**Comment by TomasVotruba** [comment]
Looks good, thank you :+1:

**Pull request merged**
