### PR TITLE
[CodeQuality] Skip increment variable on else on TernaryFalseExpressionToIfRector

### LINKED ISSUE #8630: Incorrect behavior of TernaryFalseExpressionToIfRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/b6276e67-7c57-40e6-ab3e-d57f1913a5e8

```php
<?php
$total = $sucess = $failed = 0;	
$this->handleMe($id) ? ++$success : ++$failed;
```

### Responsible rules

* `TernaryFalseExpressionToIfRector`

## Expected Behavior

Rector should skip it, as the proposed change is altering the code behavior by ignoring the `++$failed` increment.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8630

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @thePanz

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by thePanz** [comment]
Thanks @samsonasik ! Looking forward to the next release!

**Comment by samsonasik** [comment]
You can use `"rector/rector": "dev-main"` for now ;)

**Pull request merged**
