### PR TITLE
Revert [Core] No need reindex FileWithoutNamespace on AbstractRector::beforeTraverse

### PR DESCRIPTION
**Pull request by samsonasik**
Reverts rectorphp/rector-src#4043

### CODE REVIEW

**Comment by staabm** [comment]
how did you figure out this change is not correct (since the CI pipeline was green in the previous PR)?

anything we can do to add a test, or enhance the CI pipeline, so we get a failling CI instead of a false-positive green one?

**Comment by staabm** [comment]
we could e.g. run codeigniter4 in the CI pipeline to see how rector-src runs on it and how the results look like - like phpstan-src is running on community projects in CI

**Comment by samsonasik** [comment]
I will looking for better approach for it, for example, I set the target node as `If_`, which inside `FileWithoutNamespace_`, it means it doesn't has `stmt_key` yet, as `FileWithoutNamespace_` is always late detected, so it can't get previous or next node via BetterNodeFinder, ofcourse, better to use `FileWithoutNamepace_` to loop stmts itself.

**Comment by staabm** [comment]
my question was not about the change of the PR itself, but about improving the CI pipeline to get a better early feedback.

it looks like some things which get green in the rector CI need to be reverted shortly after because of some manual testing or similar. and I think it would be better we would catch these cases right in CI before the merge

**Comment by samsonasik** [comment]
Thank you, yes, sometime that hard to reproduce, I will add test case for it when possible.

**Pull request merged**
