### PR TITLE
[CodeQuality] Skip re use variable in assign Expr on InlineArrayReturnAssignRector

### LINKED ISSUE #7171: Incorrect behavior of InlineArrayReturnAssignRector, RemoveDuplicatedArrayKeyRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/519ebc53-584f-4f61-8e0e-aa966185bbd0

```php
<?php

final class DemoFile
{
    protected static function addContinuationChildren($pageUid, RenderingContextInterface $renderingContext)
    {
        $continuation = [];
        $continuation['descriptions'] = GetViewHelper::renderStatic(
            [
                'column' => 4,
                'order' => 'sorting',
                'sortDirection' => 'ASC',
                'limit' => '',
                'pageUid' => $pageUid,
                'contentUids' => null,
                'sectionIndexOnly' => false,
                'hideUntranslated' => false,
            ],
            function () {
            },
            $renderingContext
        );

        $continuation['descriptions'] = \array_map(function ($description) {
            $description['bullet_type'] = 'plus';
            return $description;
        }, $continuation['descriptions']);

        return $continuation;
    }
}
```

### Responsible rules

* `InlineArrayReturnAssignRector`

* `RemoveDuplicatedArrayKeyRector`

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7171

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @helsner

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I am merging it ;)

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
