### PR TITLE
Fix issue of parsing PHP 8 sources on PHP 7.x

### LINKED ISSUE #6779: RichParser error on dev-main on PHP 7.4
# Bug Report

<!-- First, thank you for reporting a bug. That takes time and we appreciate that! -->

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main            |

@TomasVotruba I tried rector dev-main on https://github.com/codeigniter4/CodeIgniter4/pull/5269 to test the compatibility with PHPStan 1.0, and this only show this error on PHP 7.4, ref https://github.com/codeigniter4/CodeIgniter4/runs/4066534747?check_suite_focus=true#step:10:5

```bash
➜  CodeIgniter4 git:(upgrade-to-phpstan1) ✗ /opt/homebrew/Cellar/php@7.4/7.4.24_1/bin/php vendor/bin/rector process tests/system/View/TableTest.php --clear-cache -vvv
[parsing] tests/system/View/TableTest.php

In RichParser.php line 38:
                                                                                                                                                                                         
  [PHPStan\Parser\ParserErrorsException]                                                                                                                                                 
  Syntax error, unexpected T_FUNCTION, expecting T_VARIABLE on line 117, Syntax error, unexpected '}', expecting T_VARIABLE on line 144, Syntax error, unexpected '}', expecting T_VARI  
  ABLE on line 167, Syntax error, unexpected '}', expecting T_VARIABLE on line 818, Syntax error, unexpected T_PUBLIC on line 1018     
```

while it is working ok on PHP 8.0. It seems there is invalid syntax in PHP 7.4 for PHPStan. 

/cc @ondrejmirtes do you think it is PHPStan issue on downgrading syntax ?

The trace exception message are like this:

```bash
[parsing] tests/system/View/TableTest.php

In RichParser.php line 38:
                                                                                                                                                                                         
  [PHPStan\Parser\ParserErrorsException]                                                                                                                                                 
  Syntax error, unexpected T_FUNCTION, expecting T_VARIABLE on line 117, Syntax error, unexpected '}', expecting T_VARIABLE on line 144, Syntax error, unexpected '}', expecting T_VARI  
  ABLE on line 167, Syntax error, unexpected '}', expecting T_VARIABLE on line 818, Syntax error, unexpected T_PUBLIC on line 1018                                                       
                                                                                                                                                                                         

Exception trace:
  at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Parser/RichParser.php:38
 PHPStan\Parser\RichParser->parseFile() at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Php/PhpMethodReflection.php:217
 PHPStan\Reflection\Php\PhpMethodReflection->isVariadic() at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Php/PhpMethodReflection.php:183
 PHPStan\Reflection\Php\PhpMethodReflection->getVariants() at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Php/UniversalObjectCratesClassReflectionExtension.php:50
 PHPStan\Reflection\Php\UniversalObjectCratesClassReflectionExtension->getProperty() at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php:377
 PHPStan\Reflection\ClassReflection->getProperty() at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php:121
 PHPStan\Type\ObjectType->getUnresolvedPropertyPrototype() at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Type/ObjectType.php:98
 PHPStan\Type\ObjectType->getProperty() at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php:2624
 PHPStan\Analyser\NodeScopeResolver->processAssignVar() at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php:1353
 PHPStan\Analyser\NodeScopeResolver->processExprNode() at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php:451
 PHPStan\Analyser\NodeScopeResolver->processStmtNode() at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php:249
 PHPStan\Analyser\NodeScopeResolver->processStmtNodes() at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php:414
 PHPStan\Analyser\NodeScopeResolver->processStmtNode() at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php:249
 PHPStan\Analyser\NodeScopeResolver->processStmtNodes() at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php:498
 PHPStan\Analyser\NodeScopeResolver->processStmtNode() at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php:249
 PHPStan\Analyser\NodeScopeResolver->processStmtNodes() at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php:464
 PHPStan\Analyser\NodeScopeResolver->processStmtNode() at phar:///Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php:217
 PHPStan\Analyser\NodeScopeResolver->processNodes() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php:152
 Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodesWithMixinHandling() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php:140
 Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/NodeTypeResolver/NodeScopeAndMetadataDecorator.php:81
 Rector\NodeTypeResolver\NodeScopeAndMetadataDecorator->decorateNodesFromFile() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Application/FileProcessor.php:44
 Rector\Core\Application\FileProcessor->parseFileInfoToLocalCache() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php:80
 Rector\Core\Application\FileProcessor\PhpFileProcessor->Rector\Core\Application\FileProcessor\{closure}() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php:144
 Rector\Core\Application\FileProcessor\PhpFileProcessor->tryCatchWrapper() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php:81
 Rector\Core\Application\FileProcessor\PhpFileProcessor->process() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Application/ApplicationFileProcessor.php:76
 Rector\Core\Application\ApplicationFileProcessor->processFiles() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Application/ApplicationFileProcessor.php:57
 Rector\Core\Application\ApplicationFileProcessor->run() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Console/Command/ProcessCommand.php:152
 Rector\Core\Console\Command\ProcessCommand->execute() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symfony/console/Command/Command.php:274
 RectorPrefix20211031\Symfony\Component\Console\Command\Command->run() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symfony/console/Application.php:870
 RectorPrefix20211031\Symfony\Component\Console\Application->doRunCommand() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symfony/console/Application.php:266
 RectorPrefix20211031\Symfony\Component\Console\Application->doRun() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Console/ConsoleApplication.php:71
 Rector\Core\Console\ConsoleApplication->doRun() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symfony/console/Application.php:162
 RectorPrefix20211031\Symfony\Component\Console\Application->run() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/bin/rector.php:63
 require_once() at /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/bin/rector:5

process [-n|--dry-run] [-a|--autoload-file AUTOLOAD-FILE] [-o|--output-format [OUTPUT-FORMAT]] [--no-progress-bar] [--no-diffs] [--clear-cache] [--] [<source>...]
```

### PR DESCRIPTION
**Pull request by ondrejmirtes**
This fixes https://github.com/rectorphp/rector/issues/6779

/cc @samsonasik @TomasVotruba

### CODE REVIEW

**Review by samsonasik — APPROVED** [review]
@ondrejmirtes I confirm that it works 🎉 Thank you 

Screen Shot 2021-11-08 at 15 21 53

**Comment by TomasVotruba** [comment]
Awesome, thank you :clap:

**Comment by TomasVotruba** [comment]
Related bug: https://github.com/rectorphp/rector/issues/6799

We'll need 2 parsers:

* one for user's code that respects their PHP version.
* one for the stubs parsing

**Comment by TomasVotruba** [comment]
@ondrejmirtes Any ideas how to make those 2 parser like PHPStan has? I'm trying to play with neon syntax, but I keep failing as I never used it without autowiring.

**Comment by ondrejmirtes** [comment]
@TomasVotruba You need a PathRoutingParser like PHPStan has (https://github.com/phpstan/phpstan-src/blob/master/src/Parser/PathRoutingParser.php), but probably not exactly the same one, but custom for your needs.

This is how it's configured: https://github.com/phpstan/phpstan-src/blob/ce0b04308d4761f6efd8ce3fec90be59e1197ced/conf/config.neon#L1744-L1750

**Comment by TomasVotruba** [comment]
Not sure how to configure it and how that would help.

So far I think the problem is the default parser is used for stubs that are in PHP 8.
But in analysis we need PHP based default rich parser.

**Comment by ondrejmirtes** [comment]
That's exactly how PathRoutingParser can help you.

**Comment by TomasVotruba** [comment]
Any ideas how exacly it should be configured? What does "path routing" mean?

This parses PHP 7.4 code, but fails to parse stubs:

```neon
#parameters:
#    phpVersion: 80100

services:
    defaultAnalysisParser:
        factory: @cachedRectorParser
        arguments!: []

    cachedRectorParser:
        class: PHPStan\Parser\CachedParser
        arguments:
            originalParser: @rectorParser
            cachedNodesByStringCountMax: %cache.nodesByStringCountMax%
        autowired: no

    rectorParser:
        class: PHPStan\Parser\RichParser
        arguments:
            parser: @currentPhpVersionPhpParser
            lexer: @currentPhpVersionLexer
        autowired: no

    pathRoutingParser:
        class: PHPStan\Parser\PathRoutingParser
        arguments:
            currentPhpVersionRichParser: @php8PhpParser
            currentPhpVersionSimpleParser: @php8PhpParser
            php8Parser: @php8Parser
        autowired: false
```

**Comment by ondrejmirtes** [comment]
This calls for a phone call again :) I have time on Friday.

**Comment by TomasVotruba** [comment]
It fails on `FileTypeMapper` that is using `defaultAnalysisParser` (PHP 7.4)  https://github.com/phpstan/phpstan-src/blob/ce0b04308d4761f6efd8ce3fec90be59e1197ced/conf/config.neon#L864-L867

But it seems Nette DI is unable to override anonymous services :/

```diff
	-
		class: PHPStan\Type\FileTypeMapper
		arguments:
-			phpParser: @defaultAnalysisParser
+			phpParser: @pathRoutingParser
```

↓

```bash
PHP Fatal error:  Uncaught _PHPStan_c862bb974\Nette\DI\ServiceCreationException: 
Multiple services of type PHPStan\Type\FileTypeMapper found: 0114, 0246 in phar:///var/www/rector-syntax-bug/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Autowiring.php:53
```

**Comment by ondrejmirtes** [comment]
The `defaultAnalysisParser` must be `pathRoutingParser`, that's the whole point. And you should use it to route parser requests either to current version PHP parser (analysed code, dependencies), or to PHP 8 parser (stubs).

**Comment by TomasVotruba** [comment]
I'd prefer to solve it now :D it seems extreemely hard for such a simple task.
I'll give it couple more hours. If I fail, we can call.

**Comment by TomasVotruba** [comment]
Something like this?

```neon
services:
    pathRoutingParser:
        class: PHPStan\Parser\PathRoutingParser
        arguments:
            currentPhpVersionRichParser: @rectorParser
            currentPhpVersionSimpleParser: @rectorParser
            php8Parser: @php8Parser
        autowired: false

    rectorParser:
        class: PHPStan\Parser\RichParser
        arguments:
            parser: @currentPhpVersionPhpParser
            lexer: @currentPhpVersionLexer
        autowired: no
```

**Comment by ondrejmirtes** [comment]
I'd prefer if you wrote your own PathRoutingParser, the one from PHPStan is too complex and unsuitable for your needs.

You also need to include:

```
    defaultAnalysisParser:
        factory: @pathRoutingParser
        arguments!: []
```

**Comment by TomasVotruba** [comment]
> I'd prefer if you wrote your own PathRoutingParser, the one from PHPStan is too complex and unsuitable for your needs.

If I understand what it does and why, I'll try :+1: 


It looks that this - https://github.com/rectorphp/rector-src/pull/1184#issuecomment-992945523 - works for both fixture and CI in this repository.

> You also need to include:

I'll try

**Comment by TomasVotruba** [comment]
The work is done in https://github.com/rectorphp/rector-src/pull/1480

**Comment by TomasVotruba** [comment]
Looks good, the tests pass here, the repository with bug is fixed too: https://github.com/cjunge-work/rector-syntax-bug/pull/3

Thanks @ondrejmirtes :+1: :clap: 

I can sleep in peace today :)

**Comment by cjunge-work** [comment]
Thank you @TomasVotruba!!! :beers:

**Pull request merged**
