### PR TITLE
[TypeDeclaration] Skip curly {@inheritdoc} on AddArrayReturnDocTypeRector

### LINKED ISSUE #7179: Incorrect behavior of AddArrayReturnDocTypeRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | Rector 0.13.0      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/a1be4c49-96db-450e-a69c-92ec6ad33d9b

```php
<?php

interface SomeCoolInterface
{
    /** @return int[] */
    public function run(): array;
}

final class DemoFile implements SomeCoolInterface
{
    /** {@inheritDoc} */
    public function run(): array
    {
        return [5];
    }
}
```

### Responsible rules

* `AddArrayReturnDocTypeRector`

## Expected Behavior

Since it's already declaring that it's inheriting the DocBlock from the interface I wonder it this Rector _should_ be applied?

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7179

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @ttomdewit

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
LGTM :+1:

**Comment by ttomdewit** [comment]
😍😍😍😍😘😘😘😘😘

**Pull request merged**
