### PR TITLE
[TypeDeclaration] handle explicit if else new on ReturnTypeFromReturnNewRector

### PR DESCRIPTION
**Pull request by samsonasik**
https://github.com/rectorphp/rector-src/pull/6102#pullrequestreview-2153906493

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review, for me, using `SilentVoidResolver` only is actually already enough, as that cover many edge cases already, but you decide ;)

**Comment by samsonasik** [comment]
Another more consist way is to rename `hasClassMethodRootReturn` to something else, eg: `hasOnlyReturnWithExpr`, then we traverse, exclude inner class/function/closure to get Return_.

If there is Return_ **without** Expr in collection, then return false, as possible void

Then, lastly, verify Silent Void to handle no return like current PR change as last resort, wdyt?

**Comment by TomasVotruba** [comment]
Neat solution, I like it :+1: 

> Another more consist way is to rename hasClassMethodRootReturn to something else, eg: hasOnlyReturnWithExpr, then we traverse, exclude inner class/function/closure to get Return_.

Agreed, the name deserves an improvement :)

**Comment by samsonasik** [comment]
implemented 👍

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
