### PR TITLE
clean up tweak package test workflow

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
Somehow still error:

```bash
/home/runner/work/rector-src/rector-src/vendor/rector/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:60
506) Rector\Tests\DowngradePhp80\Rector\Expression\DowngradeThrowExprRector\DowngradeThrowExprRectorTest::test with data set #8 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Symfony\Component\DependencyInjection\Exceptio
```

**Comment by samsonasik** [comment]
each test in rector-downgrade-php seems require include config:

```
$rectorConfig->import(__DIR__ . '/../../../../../../config/config.php');
```

**Comment by TomasVotruba** [comment]
> $rectorConfig->import(__DIR__ . '/../../../../../../config/config.php');

That is actually expected, as packages do no lot root `rector.php` magically. To avoid WTF of merging with "testing" `rector.php`

**Comment by samsonasik** [comment]
it works 🎉

**Comment by TomasVotruba** [comment]
:clap:

**Pull request merged**
