### PR TITLE
Fix ClassPropertyAssignToConstructorPromotionRector to skip properties that have attributes

### PR DESCRIPTION
**Pull request by Bl00D4NGEL**
# Fix ClassPropertyAssignToConstructorPromotionRector to skip properties that have attributes

Based on https://getrector.org/demo/1ebe95c8-2d22-6d0e-b6ff-7be843d783d4

The ClassPropertyAssignToConstructorPromotionRector should ignore properties that have properties linked to them. Looking at the demo it seems to have gotten rid of both properties, which I did not expect/want it to do.

Adding two test cases to test two scenarios:
- Class only has "attributed" properties => ignore file
- Class has some "attributes" properties => promote only the properties that are not "attributed"

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, thanks for the fix.

I wonder if moving the attribute above param would work. This way we could have both promoted property and attributes. What do you think?

**Comment by Bl00D4NGEL** [comment]
Hey :)
I will try that out tomorow for our codebase where I originally found this and see what I can do.
Will report back tomorow.

**Comment by TomasVotruba** [comment]
Good luck and thank you :)

**Comment by Bl00D4NGEL** [comment]
Update: It seems to be possible to move the attributes from the properties to the constructor like so:
```
    public function __construct(
        #[Immutable]
        public float $latitude,
        #[Immutable]
        public float $longitude
    ) {}
```

I will look into implementing this later today.

**Comment by TomasVotruba** [comment]
@Bl00D4NGEL Thank you :+1:

**Comment by Bl00D4NGEL** [comment]
@TomasVotruba tests are green and properties with attributes are now also correctly converted :) Feel free to review.

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Awesome, thank you!

**Pull request merged**
