### PR TITLE
[TypeDeclaration] Separate Closure return type

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
I removed failing fixtures for `Closure/ArrowFunction` add return https://github.com/rectorphp/rector-src/pull/6029/commits/6515c394647be9dbbe82c3a5df9e2c87a436285c, based on them, I think we can categorize by type, eg:

- AddClosureArrayReturnTypeRector
- AddClosureScalarReturnTypeRector
- AddClosureUnionReturnTypeRector
- etc

that can be in separate PRs to add first, before it can be merged so all features covered first...

existing rules for `Closure` are:

- AddClosureVoidReturnTypeWhereNoReturnRector

for ArrowFunction, we have already `AddArrowFunctionReturnTypeRector` ;)

**Comment by TomasVotruba** [comment]
Could you rebase this one? I want to merge it before I do some duplicated/conflicting changes in the set

**Comment by samsonasik** [comment]
I think I can close it for now, to revisit later for possible more by type improvement, as currently the left over is too detail and make it too much rules to extract...

**Comment by TomasVotruba** [comment]
I see, I'll look into it

**Pull request closed without merging**
