### PR TITLE
use rector/release-notes-generator:^0.3.0

### PR DESCRIPTION
**Pull request by samsonasik**
Either make new release of rector/release-notes-generator or use latest dev-main, ref

- https://github.com/rectorphp/release-notes-generator/pull/2

### CODE REVIEW

**Comment by samsonasik** [comment]
Ready to merge 👍

**Comment by TomasVotruba** [comment]
I think we can tag a new version 0.3. Do you have access there?

**Comment by samsonasik** [comment]
I don't have access, could you add me to have access? Thank you.

**Comment by TomasVotruba** [comment]
Done :+1:

**Comment by samsonasik** [comment]
Ok, 0.3.0 just tagged https://github.com/rectorphp/release-notes-generator/releases/tag/0.3.0

**Comment by TomasVotruba** [comment]
:partying_face:

**Pull request merged**
