### PR TITLE
[DeadCode] Skip nullable @ template on RemoveUselessReturnTagRector

### LINKED ISSUE #8883: False positive of RemoveUselessReturnTagRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/d61ce159-b0cf-463d-b1d9-77ca9272e5c9

```php
<?php

interface Performance {}

/**
 * @template TPerformance of Performance
 */
interface Task {
    /** @return TPerformance|null */
    public function performance(): Performance|null;
}
```

This is somehow related to https://github.com/rectorphp/rector/issues/8870

I have created 2 example for PHPStan output:
https://phpstan.org/r/afa02580-d14c-4e4c-bb06-c89f6f0a2566 (with the `@return` tag)
https://phpstan.org/r/ac59fd57-083b-4d14-a140-b03ec7eada3e (without the `@return` tag)

### Responsible rules

* `RemoveUselessReturnTagRector`

## Expected Behavior

Tag should not be removed

### LINKED ISSUE #8885: `RemoveUselessReturnTagRector` removes Template return type
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| 1.2.9 | Doesn't happen before 1.2.9 |

When upgrading to 1.2.9, Rector removes the return type docblock in the following example:

```php
/**
 * @template TModelClass of DatabaseModel
 */
final class ModelQueryBuilder
{
    /**
     * @return TModelClass|null
     */
    public function first(mixed ...$bindings)
    { /* … */ }

    // …
}
```

Since this docblock returns a template type, it definitely should not be removed. The rector that's removing it is `RemoveUselessReturnTagRector`.

```
vendor/bin/rector process --no-ansi
 1014/1014 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
1 file with changes
===================

1) src/Tempest/Database/src/Builder/ModelQueryBuilder.php:34

    ---------- begin diff ----------
@@ @@
         $this->modelDefinition = new ModelDefinition($this->modelClass);
     }

-    /** @return TModelClass|null */
     public function first(mixed ...$bindings): ?DatabaseModel
     {
         $query = $this->build($bindings);
@@ @@
         return $result[array_key_first($result)];
     }
```

## Minimal PHP Code Causing Issue

You can also reproduce it by cloning Tempest, updating Rector to 1.2.9 and then running it: https://github.com/tempestphp/tempest-framework

## Expected Behaviour

For the docblock to not be removed.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8883
Fixes https://github.com/rectorphp/rector/issues/8885

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @brendt @dragosprotung

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by TomasVotruba** [comment]
Woop :tada:

**Comment by brendt** [comment]
Nice, thanks for pining me :)

**Pull request merged**
