### PR TITLE
[Transform] Remove ArgumentFuncCallToMethodCallRector as never used

### PR DESCRIPTION
**Pull request by TomasVotruba**
I recall I added this rule for Laravel "functions to facades" article many years ago as a demo for Rector features.
In the end its hardly practical and never used in any communityset. Let's see if this assumption is true :)

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba it still used by rector-laravel https://github.com/driftingly/rector-laravel/blob/ea3b1da64bbd11146d3e2f3ccefbba1cef59dfd3/config/sets/laravel-static-to-injection.php#L8

/cc @driftingly you need to migrate the code

**Comment by yguedidi** [comment]
@TomasVotruba just curious, isn't the removal of a rule a BC break? as it may be used by end user configurations I think

**Comment by TomasVotruba** [comment]
@samsonasik I see. In that case should be ported there as better meets Laravel specific needs.

@driftingly Could you handle the copy of the rule?

**Comment by TomasVotruba** [comment]
@yguedidi It could be so, that's what we try to find out.

**Comment by driftingly** [comment]
Done in https://github.com/driftingly/rector-laravel/pull/108

**Pull request merged**
