### PR TITLE
[DowngradePhp80] Add DowngradeMixedTypeTypedPropertyRector

### LINKED ISSUE #7259: There's no DowngradeMixedTypedPropertyRector
# Feature Request

When going down from PHP 8.0 to 7.4, I'd expect this to happen:

```diff
-private mixed $prop;
+/** @var mixed */
+private $prop;
```
 
Thanks.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7259

### CODE REVIEW

**Comment by samsonasik** [comment]
implemented 🎉 /cc @ondrejmirtes

**Comment by ondrejmirtes** [comment]
Thank you! Looking forward to the release!

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you @samsonasik :+1:

**Pull request merged**
