### PR TITLE
[DX] Various config merge, improve RectorConfig methods

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba it somehow rector scoped got e2e error https://github.com/rectorphp/rector/runs/6626321496?check_suite_focus=true

**Comment by samsonasik** [comment]
Bootstrap files seems overlapped now, and stub rector not loaded for ReflectionUnionType

**Comment by TomasVotruba** [comment]
I got same effect with Rector on PHP 7.2 project yestereday.

Before we had `ReflectionUnionType` autoloaded directly in `rector.php`, right? I think it might be useful to have it there.

**Comment by samsonasik** [comment]
Previous build seems green https://github.com/rectorphp/rector/commit/7e46eb82674b02e37e82e1f9433e8ee75e401f5e

Moving to rector.php will make other aspect not working, eg create test for custom rule, so running test in custom rule will not working as not consum the rector.php

**Comment by TomasVotruba** [comment]
That's because now there is some union check, that PHPStan tries to resolve but fails.

> Moving to rector.php will make other aspect not working, eg create test for custom rule, so running test in custom rule will not working as not consum the rector.php

The same stub should be loaded in tests too.

**Comment by samsonasik** [comment]
I will check if I can found something, as `BootstrapFilesIncluder` should already handle after autoload on both command and test.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by samsonasik** [comment]
I can't reproduce locally, which is really strange:

```
➜  define-constant git:(main) ✗ /opt/homebrew/Cellar/php@7.2/7.2.34_4/bin/php ../../bin/rector process --dry-run --ansi


                                                                                                                        
 [OK] Rector is done! 
```

The `ReflectionUnionType` only exists in PHP 8+, which if it cause error, it should cause error in all php 7.x e2e tests, but it only in php 7.2, which it seems a Github CI issue.

I will check if `class_exists()` removal `false` argument can fix it.

**Pull request merged**
