### PR TITLE
[DowngradePhp80] Early Register DowngradeNamedArgumentRector then DowngradeAttributeToAnnotationRector

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba It seems make downgrade `vendor/symfony/dependency-injection/Attribute` can be by directory.

### CODE REVIEW

**Comment by samsonasik** [comment]
Cleaned up, now it seems no longer need manual run on  `vendor/symfony/dependency-injection/Attribute` directory.

**Comment by TomasVotruba** [comment]
Thanks, this look good :+1: 

How can we make it work regerdless the rule order? They should not depend on each other

**Comment by samsonasik** [comment]
I am not sure about that, it previously got error:

```bash
Uncaught TypeError: PhpParser\Internal\TokenStream::getIndentationBefore(): Return value must be of type int, null returned
```

which seems internal php-parser?

**Comment by TomasVotruba** [comment]
> which seems internal php-parser?

It looks like :+1: 

Could you create a test case that would throw the same error here? I would look into that

**Comment by samsonasik** [comment]
I will try, it possibly due directory named "Attribute" or namespace "Attribute"

**Comment by samsonasik** [comment]
It seems somehow on run `AutoconfigureTag.php` early, it got `IdentifierNotFound` from PHPStan: 

```
Symfony\Component\DependencyInjection\Attribute\Autoconfigure" could not be found
```

which the `Autoconfigure` is there:

```bash
 bin/rector process vendor/symfony/dependency-injection/Attribute/AutoconfigureTag.php --dry-run -c build/config/config-downgrade.php --debug
 0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0% < 1 sec/< 1 sec 46.5 MiB[parsing] vendor/symfony/dependency-injection/Attribute/AutoconfigureTag.php
PHP Fatal error:  Uncaught PHPStan\BetterReflection\Reflector\Exception\IdentifierNotFound: PHPStan\BetterReflection\Reflection\ReflectionClass "Symfony\Component\DependencyInjection\Attribute\Autoconfigure" could not be found in the located source in phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/Exception/IdentifierNotFound.php:24
Stack trace:
#0 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/ClassReflector.php(47): PHPStan\BetterReflection\Reflector\Exception\IdentifierNotFound::fromIdentifier(Object(PHPStan\BetterReflection\Identifier\Identifier))
#1 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/BetterReflection/Reflector/MemoizingClassReflector.php(29): PHPStan\BetterReflection\Reflector\ClassReflector->reflect('Symfony\\Compone...')
#2 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflection/ReflectionClass.php(649): PHPStan\Reflection\BetterReflection\Reflector\MemoizingClassReflector->reflect('Symfony\\Compone...')
```

```
ls -l vendor/symfony/dependency-injection/Attribute/Autoconfigure.php   
-rw-r--r--  1 samsonasik  staff  921 Jun 24 15:13 vendor/symfony/dependency-injection/Attribute/Autoconfigure.php
```

**Comment by samsonasik** [comment]
I can't reproduce via unit tests, it seems something is happen when command is running, possibly phpstan locate by its own vendor source.

**Comment by samsonasik** [comment]
I created failing PR for failure on `IdentifierNotFound`, somehow, unrelated with service order https://github.com/rectorphp/rector-src/pull/368

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
