### PR TITLE
static lambda

### PR DESCRIPTION
**Pull request by MathiasReker**
Lambdas not (indirect) referencing $this must be declared static.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you. Now it's the time to include Rector rule with this change :+1: 

How did you find these?

**Comment by MathiasReker** [comment]
I used https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by TomasVotruba** [comment]
Could you add the rule to `ecs.php`?

**Comment by MathiasReker** [comment]
I will see if I can find the time to do it in the upcoming weeks :-)

**Comment by TomasVotruba** [comment]
Thanks!
I've added rule to `ecs.php` and run again to resolve conflicts :+1:

**Pull request closed without merging**
