### PR TITLE
[Core][Printer] Re-use resolveNewStmts() from BetterStandardPrinter on FormatPerservingPrinter

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
The `BetterStandardPrinter::printFormatPreserving()` actually call `resolveNewStmts()` internally, which redundant, but can't work without double call from `FormatPerservingPrinter`.

**Comment by samsonasik** [comment]
Let's use `$newStmts` on `count()` compare instead of original `$stmts` https://github.com/rectorphp/rector-src/pull/3411/commits/b335cdd53aeee53ac235851c2b7f02adbdeee667

**Comment by samsonasik** [comment]
@TomasVotruba it works 🎉 

This also reduce `diff` on end `InlineHTML` on `e2e` test, shown below:

**Before**

Screen Shot 2023-02-25 at 04 53 20


**After**

Screen Shot 2023-02-25 at 04 53 33

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thanks 🙏👍

**Pull request merged**
