### PR TITLE
[Printer] Move handle mix php+html to BetterStandardPrinter

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba @staabm previously, I handle mix php+html in various locations:

- packages/PostRector/Rector/NodeAddingPostRector.php
- src/Rector/AbstractRector.php

which need back and forth in case of change in the future. 

This PR move it to centralize handling in `BetterStandPrinter`, with utilize simplified `MixPhpHtmlDecorator`.

### CODE REVIEW

**Comment by samsonasik** [comment]
It works 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
I also handle after `InlineHTML` https://github.com/rectorphp/rector-src/pull/3310/commits/b91243e23568ea008cf58ae485476174e9c4d8f5

**Comment by samsonasik** [comment]
I will add more tests.

**Comment by samsonasik** [comment]
I add test for return array node with after inlinehtml https://github.com/rectorphp/rector-src/pull/3310/commits/36070a0b8de378e6941fa75e32617ac997fec207

**Comment by samsonasik** [comment]
I found a bug on node with docblock addition before inlinehtml https://github.com/rectorphp/rector-src/pull/3310/commits/fee288fe4345ec2f7d843a4a77ff855c0e5f6ba7.

 I will check.

**Comment by samsonasik** [comment]
Add docblock statement before InlineHTML with `->addNodeBeforeNode()` seems working ok https://github.com/rectorphp/rector-src/pull/3310/commits/76cdc1d9585096ce30e191dfb76c7ade42c6e85d,

The issue is on return array before InlineHTML.

I will check more.

**Comment by samsonasik** [comment]
Fixed 🎉 with verify mirror comment in on existing node, not new added node with verify start token pos >= 0 https://github.com/rectorphp/rector-src/pull/3310/commits/22c0b179463cb816e948c80e22040fbae549193d

**Comment by samsonasik** [comment]
It seems cause error on `DowngradeKeysInListRectorTest`:

```diff
There was 1 failure:

1) Rector\Tests\DowngradePhp71\Rector\List_\DowngradeKeysInListRector\DowngradeKeysInListRectorTest::test with data set #1 ('/home/runner/work/rector-src/...hp.inc')
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
             ["id" => 1, "name" => 'Tom'],
             ["id" => 2, "name" => 'Fred'],
         ];
-        // a comment
         $id1 = $data[0]["id"];
         $name1 = $data[0]["name"];
```

checking mirror comment seems require more check. I will check.

**Comment by samsonasik** [comment]
Fixed 🎉 with verify old node is `InlineHTML` before skipping mirror comment https://github.com/rectorphp/rector-src/pull/3310/commits/312cded40f480496114459988857feb56b01a689

**Comment by samsonasik** [comment]
Finally 🎉 🎉 🎉 All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Review by staabm — COMMENTED** [review]
I can't judge all the impl details, but I like the cases covered by tests. ;)

**Pull request merged**
