### PR TITLE
[NodeAnalyzer] Remove parent attribute on ScopeAnalyzer

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed :tada: @TomasVotruba I am merging it to have faster feedback to test ;)

**Comment by samsonasik** [comment]
Tested on CodeIgniter4 project, now got error:

```
➜  CodeIgniter4 git:(develop) ✗ time vendor/bin/rector 
 603/790 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░]  76%
                                                                                
 [ERROR] Could not process                                                      
         "/home/abdul/www/CodeIgniter4/system/CLI/Commands.php" file, due to:   
         "System error: "Scope not available on                                 
         "PhpParser\Node\Name\FullyQualified" node with parent node of          
         "PhpParser\Node\Stmt\Catch_", but is required by a refactorWithScope() 
         method of "Rector\Renaming\Rector\Name\RenameClassRector" rule. Fix    
         scope refresh on changed nodes first"                                  
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line:
         53                                                                     
```

I will check check it.

**Comment by samsonasik** [comment]
https://github.com/rectorphp/rector-src/pull/4401

**Comment by staabm** [comment]
My unverified guess:

I think Scope instances are way heavier in memory than Ast-Nodes. This would mean that this patch might even worse memory use, as we are trading references to Ast Nodes with references to Scope objects.

After getting rid of the parent-AST-attribute we need to check these Scope attribute, as it is used so often. Maybe we can make use of WeakReference

**Comment by samsonasik** [comment]
@staabm it maybe due to stack nodes on ParentConnectingVisitor, I create an RFC for that, see https://github.com/rectorphp/rector/issues/8035

**Comment by samsonasik** [comment]
@staabm I will check if this can be reduced by using `$mutatingScope->enterXYZ()` method to fill inside instead of manually fill it, as it may goes out of control.

**Comment by samsonasik** [comment]
@TomasVotruba @staabm I am checking PHPStan source, and it seems `NodeScopeResolver->processNodes()` is called internally at `FileAnalyser::analyseFile()`

https://github.com/phpstan/phpstan-src/blob/762c8148ac9a6a66d3a513cbc52e5be1c2d75331/src/Analyser/FileAnalyser.php#L176

I am wondering if we can just use that method instead of manually fill the Scope in every use finding cases, I will lookup if that possible.

**Comment by staabm** [comment]
I don't know enough about the inner workings of rector to answer that question.

**Comment by samsonasik** [comment]
@staabm if we can get rid of "scope" attribute, and get the scope from its PHPStan node scope context, that probably will be a real solution. 

PHPStan has "Virtual" node, that probably a way to resolve Scope from that.

**Comment by samsonasik** [comment]
@TomasVotruba @staabm the most scope filling here is for `RenameClassRector` which tries to get scope from `Name` node, I will try if there is a way to refactor `RenameClassRector` to use its `ClassLike` or `TraitUse` or `Use_` instead of direct `Name` node, so `Scope` filling will be unneeded for name, as `Name` scope itself is "unrefreshable", see

https://github.com/rectorphp/rector-src/blob/77b0bb7080b3f3e01e1fc8cdac2908c7b490a9d0/src/Application/ChangedNodeScopeRefresher.php#L130-L139

**Comment by samsonasik** [comment]
@staabm @TomasVotruba I created PR https://github.com/rectorphp/rector-src/pull/4422 for it.

**Pull request merged**
