### PR TITLE
[CodingStyle] Add NewlineAfterStatementRector

### PR DESCRIPTION
**Pull request by samsonasik**
Sometime, when running rector, rector remove the line between statements, this new rector rule  `NewlineAfterStatementRector` ensure that there is a 1 line after statement if no new line for registered stmts: 

```
        ClassMethod::class,
        Function_::class,
        Property::class,
        If_::class,
        Foreach_::class,
        Do_::class,
        While_::class,
        For_::class,
        ClassConst::class,
```

I registered the rule to config set, for direct go to review, can direct check to https://github.com/rectorphp/rector-src/pull/787/files#diff-073196adc4979d1e1a3d5688fe95bb533bc4fdef1e86535001fa6fd15cc71fd9

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by Bl00D4NGEL** [comment]
In my opinion this honestly feels like something that a coding standard tool should handle and not rector.

**Comment by samsonasik** [comment]
This rule is categorized in `CodingStyle` rules, so I think it make sense. If user want to use coding-standard tools instead, user can just skip it via Option::SKIP.

**Comment by TomasVotruba** [comment]
> In my opinion this honestly feels like something that a coding standard tool should handle and not rector.

In theory yes and it would be great if such rule exists. But this is rather right tool for right job. If coding standard tool could do this, such rule would appear in last ~12 years.

> This rule is categorized in CodingStyle rules, so I think it make sense

I like the simple implementation, thank you :+1:

**Pull request merged**
