### PR TITLE
[Php80] Handle crash leaveNode() returned invalid value of type integer on TokenGetAllToObjectRector

### LINKED ISSUE #7892: TokenGetAllToObjectRector fails with "leaveNode() returned invalid value of type integer"
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.24             |

I'm upgrading a legacy system that was built with cakephp 2 to php 8.1. Rector was hanging and throwing errors sometimes, I was able to isolate this rule and file to reproduce one of the errors. There are other problems that I reported in other issues.

I'm not sure if this is an error in rector or in PhpParser, so I'm reporting it here, I think that the refactor messes up the node that it is changing, but I'm not sure because I don't fully understand how rector works.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/c6334ce9-fdf7-4bd0-9ed6-94ce626c3e28

## Expected Behaviour

The rule should not throw an error

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7892
Ref https://getrector.com/demo/c6334ce9-fdf7-4bd0-9ed6-94ce626c3e28

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed :tada: /cc @nerones

**Comment by samsonasik** [comment]
it seems cause error: Cannot use object of type PhpToken as array 

https://3v4l.org/veMeK

`$token[0]` seems need to be changed to `$token->is()`

**Comment by samsonasik** [comment]
Ref https://3v4l.org/Ma0RV

**Comment by samsonasik** [comment]
Finally Fixed :tada:

**Comment by samsonasik** [comment]
Finally :tada: All checks have passed :tada: @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
