### PR TITLE
[Php73] Handle named argument on JsonThrowOnErrorRector

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #1020 Fixes rectorphp/rector#6752

### CODE REVIEW

**Comment by samsonasik** [comment]
Oh, positional argument can't be after named argument https://3v4l.org/gE5AK

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Miss click :)
Thanks!

**Pull request merged**
