### PR TITLE
[TypeDeclaration] Skip nullable typed on AddArrayParamDocTypeRector

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #451 Fixes https://github.com/rectorphp/rector/issues/6567

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by Androbin** [comment]
I believe this introduces a regression:
https://getrector.org/demo/1ebe8b81-128c-6c70-9515-338e645e9149
https://getrector.org/demo/1ebe8b7e-f9e4-6166-b91a-7f0668b43d57

**Comment by Androbin** [comment]
The real issue seems to be with `$paramType->isArray()->maybe()`

**Comment by TomasVotruba** [comment]
@Androbin Nice catch, thanks! Could you send PR with failing test case to `AddArrayParamDocTypeRectorTest` so we have it covered?

**Comment by samsonasik** [comment]
@Androbin merged PR is not deployed to demo page directly, it wait for next release. Please provide failing fixture PR if you found a bug.

**Pull request merged**
