### PR TITLE
[Php80] Handle trailing comma on AnnotationToAttributeRector on Doctrine JoinColumn

### LINKED ISSUE #7372: AnnotationToAttribute trailing comma problem
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.13.10 (invoke `vendor/bin/rector --version`)             |

Before:
`* @ORM\JoinColumn(name="parent_id", referencedColumnName="id", nullable=true, )`

After:
`#[ORM\JoinColumn(name: 'parent_id', referencedColumnName: 'id', nullable: true, ')')]`

The "before" annotation although not perfectly valid however does not break the code. On the other hand the "after" attribute is a breaking one. 

Similar to https://github.com/rectorphp/rector/issues/7271

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7372

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @javaDeveloperKid

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by ghost** [comment]
You rock @samsonasik! You fix, Tomas asks for reproducer repos :smile:

**Comment by TomasVotruba** [comment]
We'll try to sync this approach :wink:

**Comment by TomasVotruba** [comment]
Thank you @samsonasik :+1:

**Pull request merged**
