### PR TITLE
[PHP 8.0] Remove NullsafeOperatorRector, as often breaking and promoting non-early returns and losen types

### PR DESCRIPTION
**Pull request by TomasVotruba**
This is similar to removal of `MoveVariableDeclarationNearReferenceRector` for high complexity and very unrealiable behavior in the practise https://github.com/rectorphp/rector-src/pull/587

Seeing history of `NullsafeOperatorRector`:
https://github.com/rectorphp/rector-src/commits/main/rules/Php80/Rector/If_/NullsafeOperatorRector.php, this rule is very often reported as breaking. That's because the AST domain is not even near deterministic here.

Running this rule on legacy code can break for many unknown ends. I'm thinking of other concerns, like promoting bad practise that is hard to understand by IDE and flow of code. E.g.

```php
if ($this->value === null) {
   return null;
}

return $this->value->getCall();
```

This code will keep knowledge about `$this->value` type hidden:

```php
return $this->value?->getCall();
```

Instead, the knowledge could be made explicit and 100 % in following line, easier to understand by IDE and AST:

```php
if (! $this->value instanceof SpecificType) {
   return null;
}

// here we know and can read the `$this->value` is SpecificType
return $this->value->getCall();
```

Saying that, this rule should be deprecated to keep Rector in more reliable scope and let users decide better, mabye with PHPStan rule, how such code should be refacoted.

---

This rule was not even registered in PHP 8.0 set, because we were not sure about its realiability.

### CODE REVIEW

**Comment by samsonasik** [comment]
The PR title should be "Remove" instead of "Deprecate" ? Looking at the diff, it is removal.

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
> This rule was not even registered in PHP 8.0 set, because we were not sure about its realiability.

Note: add possible Cİ check to avoid it.

**Comment by TomasVotruba** [comment]
:+1:

**Comment by enumag** [comment]
@TomasVotruba @samsonasik Understandable decision. The one case which I'm confident can be done reliably and which I'd very much appreciate if a rule existed would be changing this:

```php
$variable !== null ? $variable->method() : null
```

```php
$variable?->method()
```

**Comment by TomasVotruba** [comment]
That's how this rule started actually. But then it got more complex and started to break.

But feel free to copy this rule and tailor to your needs :+1:

**Pull request merged**
