### PR TITLE
[composer] require own rector packages in dev-main, to avoid endless tagging

### PR DESCRIPTION
**Pull request by TomasVotruba**
New features in rector-* packages now require to be tagged to get into Rector release.
It takes lot of time and energy to maintain it, but there is no reason not to use always the latest package version.

Requiring dev-main package version should improve relase and feature delivery as soon as possible :+1:

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba build scoped seems error now https://github.com/rectorphp/rector-src/runs/4468953091?check_suite_focus=true#step:14:77

```
Parse error: rector-prefixed-downgraded/vendor/symfony/console/EventListener/ErrorListener.php:25
    23| class ErrorListener implements \RectorPrefix20211209\Symfony\Component\EventDispatcher\EventSubscriberInterface
    24| {
  > 25|     private ?\RectorPrefix20211209\Psr\Log\LoggerInterface $logger;
    26|     public function __construct(\RectorPrefix20211209\Psr\Log\LoggerInterface $logger = null)
    27|     {
Unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in rector-prefixed-downgraded/vendor/symfony/console/EventListener/ErrorListener.php on line 25
------------------------------------------------------------
Parse error: rector-prefixed-downgraded/vendor/symfony/console/Event/ConsoleErrorEvent.php:23
    21| final class ConsoleErrorEvent extends \RectorPrefix20211209\Symfony\Component\Console\Event\ConsoleEvent
    22| {
  > 23|     private \Throwable $error;
    24|     private int $exitCode;
    25|     public function __construct(\RectorPrefix20211209\Symfony\Component\Console\Input\InputInterface $input, \RectorPrefix20211209\Symfony\Component\Console\Output\OutputInterface $output, \Throwable $error, \RectorPrefix20211209\Symfony\Component\Console\Command\Command $command = null)
Unexpected '\' (T_NS_SEPARATOR), expecting function (T_FUNCTION) or const (T_CONST) in rector-prefixed-downgraded/vendor/symfony/console/Event/ConsoleErrorEvent.php on line 23
------------------------------------------------------------
Parse error: rector-prefixed-downgraded/vendor/symfony/console/Event/ConsoleEvent.php:25
    23| {
    24|     protected $command;
  > 25|     private \RectorPrefix20211209\Symfony\Component\Console\Input\InputInterface $input;
    26|     private \RectorPrefix20211209\Symfony\Component\Console\Output\OutputInterface $output;
    27|     public function __construct(?\RectorPrefix20211209\Symfony\Component\Console\Command\Command $command, \RectorPrefix20211209\Symfony\Component\Console\Input\InputInterface $input, \RectorPrefix20211209\Symfony\Component\Console\Output\OutputInterface $output)
Unexpected '\' (T_NS_SEPARATOR), expecting function (T_FUNCTION) or const (T_CONST) in rector-prefixed-downgraded/vendor/symfony/console/Event/ConsoleEvent.php on line 25
------------------------------------------------------------
Parse error: rector-prefixed-downgraded/vendor/symfony/console/Event/ConsoleCommandEvent.php:27
    25|      * Indicates if the command should be run or skipped.
    26|      */
  > 27|     private bool $commandShouldRun = \true;
    28|     /**
    29|      * Disables the command, so it won't be run.
Unexpected 'bool' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in rector-prefixed-downgraded/vendor/symfony/console/Event/ConsoleCommandEvent.php on line 27
------------------------------------------------------------
Parse error: rector-prefixed-downgraded/vendor/symfony/console/Event/ConsoleSignalEvent.php:21
    19| final class ConsoleSignalEvent extends \RectorPrefix20211209\Symfony\Component\Console\Event\ConsoleEvent
    20| {
  > 21|     private int $handlingSignal;
    22|     public function __construct(\RectorPrefix20211209\Symfony\Component\Console\Command\Command $command, \RectorPrefix20211209\Symfony\Component\Console\Input\InputInterface $input, \RectorPrefix20211209\Symfony\Component\Console\Output\OutputInterface $output, int $handlingSignal)
    23|     {
Unexpected 'int' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in rector-prefixed-downgraded/vendor/symfony/console/Event/ConsoleSignalEvent.php on line 21
------------------------------------------------------------
Parse error: rector-prefixed-downgraded/vendor/symfony/console/Event/ConsoleTerminateEvent.php:23
    21| final class ConsoleTerminateEvent extends \RectorPrefix20211209\Symfony\Component\Console\Event\ConsoleEvent
    22| {
  > 23|     private int $exitCode;
    24|     public function __construct(\RectorPrefix20211209\Symfony\Component\Console\Command\Command $command, \RectorPrefix20211209\Symfony\Component\Console\Input\InputInterface $input, \RectorPrefix20211209\Symfony\Component\Console\Output\OutputInterface $output, int $exitCode)
    25|     {
Unexpected 'int' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in rector-prefixed-downgraded/vendor/symfony/console/Event/ConsoleTerminateEvent.php on line 23
------------------------------------------------------------
Parse error: rector-prefixed-downgraded/vendor/symfony/console/Tester/CommandTester.php:24
    22| {
    23|     use TesterTrait;
  > 24|     private \RectorPrefix20211209\Symfony\Component\Console\Command\Command $command;
    25|     public function __construct(\RectorPrefix20211209\Symfony\Component\Console\Command\Command $command)
    26|     {
Unexpected '\' (T_NS_SEPARATOR), expecting function (T_FUNCTION) or const (T_CONST) in rector-prefixed-downgraded/vendor/symfony/console/Tester/CommandTester.php on line 24
------------------------------------------------------------
Parse error: rector-prefixed-downgraded/vendor/symfony/console/Tester/ApplicationTester.php:28
    26| {
    27|     use TesterTrait;
  > 28|     private \RectorPrefix20211209\Symfony\Component\Console\Application $application;
    29|     public function __construct(\RectorPrefix20211209\Symfony\Component\Console\Application $application)
    30|     {
Unexpected '\' (T_NS_SEPARATOR), expecting function (T_FUNCTION) or const (T_CONST) in rector-prefixed-downgraded/vendor/symfony/console/Tester/ApplicationTester.php on line 28
------------------------------------------------------------
Parse error: rector-prefixed-downgraded/vendor/symfony/console/Tester/TesterTrait.php:24
    22| trait TesterTrait
    23| {
  > 24|     private \RectorPrefix20211209\Symfony\Component\Console\Output\StreamOutput $output;
    25|     private array $inputs = [];
    26|     private bool $captureStreamsIndependently = \false;
Unexpected '\' (T_NS_SEPARATOR), expecting function (T_FUNCTION) or const (T_CONST) in rector-prefixed-downgraded/vendor/symfony/console/Tester/TesterTrait.php on line 24
```

**Comment by TomasVotruba** [comment]
Seems the `vendor/symfony/console/Tester` can be excluded from linting. 
And `vendor/symfony/console/Event` should be included in downgrade paths.

**Comment by samsonasik** [comment]
I will try locally.

**Comment by samsonasik** [comment]
@TomasVotruba it seems because of `symfony/event-dispatcher` is not included, as it is require-dev, while the `ErrorListener` implements `Symfony\Component\EventDispatcher\EventSubscriberInterface`

**Comment by samsonasik** [comment]
this is strange, it still not working event require `symfony/event-dispatcher` and use it before `symfony/console` or / and regiter `vendor/symfony/console/Event` in downgrade paths.

**Comment by samsonasik** [comment]
On debugging, direct to single file seems make a change:

```diff
bin/rector process vendor/symfony/console/Event/ConsoleErrorEvent.php -c build/config/config-downgrade.php --dry-run

 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
1 file with changes
===================

1) vendor/symfony/console/Event/ConsoleErrorEvent.php:21

    ---------- begin diff ----------
@@ @@
  */
 final class ConsoleErrorEvent extends ConsoleEvent
 {
-    private \Throwable $error;
-    private int $exitCode;
+    /**
+     * @var \Throwable
+     */
+    private $error;
+    /**
+     * @var int
+     */
+    private $exitCode;

     public function __construct(InputInterface $input, OutputInterface $output, \Throwable $error, Command $command = null)
     {
@@ @@
         return $this->error;
     }

-    public function setError(\Throwable $error): void
+    /**
+     * @param \Throwable $error
+     */
+    public function setError($error): void
     {
         $this->error = $error;
     }

-    public function setExitCode(int $exitCode): void
+    /**
+     * @param int $exitCode
+     */
+    public function setExitCode($exitCode): void
     {
         $this->exitCode = $exitCode;
    ----------- end diff -----------

Applied rules:
 * DowngradeParameterTypeWideningRector (https://www.php.net/manual/en/migration72.new-features.php#migration72.new-features.param-type-widening)
 * DowngradeTypedPropertyRector
 * DowngradeAttributeToAnnotationRector (https://php.watch/articles/php-attributes#syntax)


                                                                                                                        
 [OK] 1 file would have changed (dry-run) by Rector                                                                     
                                                                                                                        
```

While when on directory, it not applied:

```diff
bin/rector process vendor/symfony/console/Event/ -c build/config/config-downgrade.php --dry-run 
    0 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]
                                                                                                                        
 [OK] Rector is done!                                                                                                   
                                                                                                                        
```

**Comment by samsonasik** [comment]
Oh, it currently skipped 

https://github.com/rectorphp/rector-src/blob/28352eee33963348a836ac137ea6b2bf140319b6/build/config/config-downgrade.php#L112-L113

it needs to be enabled.

**Comment by samsonasik** [comment]
@TomasVotruba I created PR https://github.com/rectorphp/rector-src/pull/1435 for it.

**Pull request merged**
