### PR TITLE
 [Removing] Add RemoveNamespaceRector 

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by TomasVotruba** [comment]
Hi @samsonasik , I'm getting to this rule now related with removing complex stmt attributes. I'm curious, what is the upgrade use case for this rule? Where is used? Maybe it should be part of PhpStorm refactoring scope.

**Comment by samsonasik** [comment]
Remove namespace can be used to simplify application which only for 1 purpose (1 module) which no need namespace, eg, a `bin/console` directory which a collection of console apps, which if previously has namespace, which no need as it only run once and not to be re-used.

**Comment by samsonasik** [comment]
The issue is with find and replace will cause issue on non-compount use statement after namespace removed, so this rule is used for it to handle it.

**Comment by TomasVotruba** [comment]
>  which if previously has namespace, which no need as it only run once and not to be re-used.

Such namespace is optional and it can be anything. It's not part of a framework upgrade.

> The issue is with find and replace will cause issue on non-compount use statement after namespace removed, so this rule is used for it to handle it.

I'm not sure I understand. Could you share an example? What framework/project is it related to?

**Comment by samsonasik** [comment]
I don't have example, just add it as there is RenameNamespaceRector rule, so I though it should be a remove namespace or clear namespace. 

I am fine if it is going to be removed.

**Comment by TomasVotruba** [comment]
I accepted this to quickly without proppery jugdment, my appology. Rector should help with automated and repeated tasks, this should be handled with PhpStorm or manually.

> I am fine if it is going to be removed.

:+1: 

Instead we should add configuration validation in RenameNamespaceRector to avoid empty namespaces.

**Comment by TomasVotruba** [comment]
Ref https://github.com/rectorphp/rector-src/pull/2133

**Pull request merged**
