### PR TITLE
[Php74] Add class-string to string support on TypedPropertyRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
final class ClassStringType
{
    /**
     * @var class-string
     */
    private $property = 'stdClass';
}
```

should changed to:

```diff
     /**
      * @var class-string
      */
-    private $property = 'stdClass';
+    private string $property = 'stdClass';
```

this PR try to add its support.

### CODE REVIEW

**Comment by samsonasik** [comment]
implemented 🎉

**Comment by samsonasik** [comment]
I will add more fixture for without default value.

**Comment by samsonasik** [comment]
Added without default value, will be transformed as is if no filler method https://github.com/rectorphp/rector-src/pull/2120/commits/a9908c271119066a83bef01d98d4f49d3bd3fc6d

**Comment by samsonasik** [comment]
I found a patch for unnecessary assign default to null when filled by `__construct` or `setUp()` https://github.com/rectorphp/rector-src/pull/2120/commits/c064299e2a533c659ffb6715082b15a340a628d5

**Comment by samsonasik** [comment]
It seems cause removal `class-string` doc in union type

```
rules-tests/TypeDeclaration/Rector/Property/TypedPropertyFromAssignsRector/FixtureInlinePublic/has_method_type.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 
 final class HasMethodType
 {
-    /**
-     * @var class-string|object|null
-     */
-    public $obj;
+    public string|object|null $obj = null;
```

I will check.

**Comment by samsonasik** [comment]
resolved test for Union with class-string that there is no doc var, so convert to string as is https://github.com/rectorphp/rector-src/pull/2120/commits/55d432b6a9a339fc4cfdfa825fc809e7a03b45f1

**Comment by samsonasik** [comment]
I added test for nullable class-string, for both `TypedPropertyRector` and `TypedPropertyFromAssignsRector`, the nullable on assign handled on `TypedPropertyFromAssignsRector` https://github.com/rectorphp/rector-src/pull/2120/commits/41bbc1fc5fccf72012faa93ac03639704ef8511e

**Comment by samsonasik** [comment]
This is the initial support, I think the following use case can be in separate PR (currently skipped on `TypedPropertyRector`)

```php
final class NullableClassString
{
    /**
     * @var class-string
     */
    private $property;

    public function fill()
    {
        $this->property = 'stdClass';
    }
}
```

or, we can rely on `TypedPropertyFromAssignsRector` for this task that already handle it, ref https://github.com/rectorphp/rector-src/commit/41bbc1fc5fccf72012faa93ac03639704ef8511e#diff-c123f412f77da6591c375e7486af4ed8aef5a2ac2b782d2415b340360ecf8381

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by TomasVotruba** [comment]
This looks very good, thank you :clap:

**Pull request merged**
