### PR TITLE
[Core] Merge Config instead of Replace on RectorConfig->ruleWithConfiguration()

### PR DESCRIPTION
**Pull request by samsonasik**
Closes https://github.com/rectorphp/rector-src/pull/2653

### CODE REVIEW

**Comment by samsonasik** [comment]
Merging config on `RenameMethodRector` seems got error:

```
There were 13 errors:

1) Rector\Tests\Renaming\Rector\MethodCall\RenameMethodRector\RenameMethodRectorTest::test with data set #3 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
TypeError: Symfony\Component\DependencyInjection\Loader\Configurator\InlineServiceConfigurator::__construct(): Argument #1 ($definition) must be of type Symfony\Component\DependencyInjection\Definition, null given

/Users/samsonasik/www/rector-src/vendor/symfony/dependency-injection/Loader/Configurator/InlineServiceConfigurator.php:39
```

I will check more.

**Comment by TomasVotruba** [comment]
I think this should be kept as it is. It's a common Symfony convention, that even Symfony does not handle. One has to be aware of that, like in using of Symfony :)

**Comment by samsonasik** [comment]
@TomasVotruba I just make it working :). I will create new PR for it.

**Comment by samsonasik** [comment]
https://github.com/rectorphp/rector-src/pull/2656

**Pull request closed without merging**
