### PR TITLE
[DeadCode] Add RemoveUnusedPublicMethodParameterRector

### PR DESCRIPTION
**Pull request by samsonasik**
Add rule to remove unused parameter in public method on final class without extends and interface

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
I'm concerned about side effects of this rule. What happens if this method is still called with an extra parameter?

```php
$this->someMethod(1, 2);

public function someMethod($firstArg)
{
     // ..
}
```

**Comment by samsonasik** [comment]
There is a rule to remove extra argument already, and it already only remove last parameters, see

https://getrector.com/demo/1918311b-dadd-4789-9381-55fb0e2e170e

and when it is on middle, it will be skipped, see 

https://github.com/rectorphp/rector-src/pull/5925/files#diff-a20a30da608a24fd191e2787230fafe78a56cc2e3b73a041c27ceed3671e7787

Of course, when named argument is used on the caller, and that's named arg no longer exist, it may cause invalid, but I think that need a different rule to handle :)

**Comment by TomasVotruba** [comment]
I see, lets ship this then :)

**Pull request merged**
