### PR TITLE
Add support for phpstan/phpstan 0.12.91

### PR DESCRIPTION
**Pull request by steveclifton**
### Changes
This update adds support for the recently released phpstan v0.12.91

### CODE REVIEW

**Comment by samsonasik** [comment]
please update https://github.com/rectorphp/rector-src/blob/main/build/target-repository/composer.json as well

**Comment by steveclifton** [comment]
> please update https://github.com/rectorphp/rector-src/blob/main/build/target-repository/composer.json as well

Thanks have done

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Looks good. Could you update php-parser too? So we have a phpstan that has the same version

**Comment by TomasVotruba** [comment]
...on other hand, let's take it step by step :) 

Thanks :+1:

**Pull request merged**
