### PR TITLE
Feature/fix class annotation bad print

### PR DESCRIPTION
**Pull request by etshy**
the command `composer complete-check` still throw 11 errors but not related to what i changed, so let me know if I have to fix these or not.

That's my first PR on a public repo so let me know if I messed something.

### CODE REVIEW

**Comment by samsonasik** [comment]
Looking at the errors, it seems your branch is not synced, you need to rebase to latest main branch

**Comment by etshy** [comment]
just did it.
I don't use rebase usually so i hope I didn't mess everything.

**Comment by samsonasik** [comment]
It seems cause error, see https://github.com/rectorphp/rector-src/actions/runs/6304413778/job/17115709880?pr=5081#step:7:173

**Comment by etshy** [comment]
I didn't see these tests while running `vendor/bin/phpunit`, how could I run the tests of the "subpackages" like `rector-doctrine` or `rector-symfony` ?

**Comment by samsonasik** [comment]
see https://github.com/rectorphp/rector-symfony

**Comment by etshy** [comment]
Finally good !
Sorry for the email/notif.

I finally reverted `DoctrineAnnotationTagValueNode`, the probleme didn't really came from here, but from `ArrayItemNode` with `DoctrineAnnotationTagValueNode` as `value`.

Edit: Ah but now the unit tests I added are not enough as I added them for `DoctrineAnnotationTagValueNode`...
I'll move these tests to `ArrayItemNodeTest`

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
