### PR TITLE
[Core] Early $smartFileInfo->getPathname() on NonPhpFileProcessor::supports()

### PR DESCRIPTION
**Pull request by samsonasik**
instead of call in loop.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hey, I'm cruious, what is the reason here?

The `getPathname()` is bare getter, so no logic needs to be cached here. Or isn't it?

image

**Comment by samsonasik** [comment]
that's faster to have outside, see the benchmark, method call in loop took 2x slower:

in loop: https://3v4l.org/FM3vY
outside loop: https://3v4l.org/JZW7b

**Comment by TomasVotruba** [comment]
Wow, that's crazy! Thanks for comparision

Could you link these 2 compares in the 2 cases you've changed? So the reasoning is right in the code. I imagine somebody in the future might be interested in this too.


These link are better as they focus on single result:

* https://3v4l.org/FM3vY#focus=8.0.7
* https://3v4l.org/JZW7b#focus=8.0.7

**Comment by samsonasik** [comment]
@TomasVotruba yes https://github.com/rectorphp/rector-src/pull/258

**Pull request merged**
