### PR TITLE
[PHPStan 1.11] Init PHPStanServicesFactory to load PHPStan ContainerFactory() early on LazyContainerFactory

### LINKED ISSUE #8641: Internal error when adding return types with an ObjectType
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.0.5              |

I'm using rector to add return types to methods and this used to work with phpstan 1.10.67

The problem lies within ReflectionProviderStaticAccessor::getInstance as the internal instance is null at this point

See also the reported issue on phpstan but they blame rector for the error: https://github.com/phpstan/phpstan/issues/11045

## Minimal PHP Code Causing Issue

https://getrector.com/demo/873bfbb1-5cbc-4311-8ee2-e4e3af16621f

## Expected Behaviour

It should not break

### PR DESCRIPTION
**Pull request by samsonasik**
Real Fixes https://github.com/rectorphp/rector/issues/8641

@simonschaufi based on @ondrejmirtes suggestion on https://github.com/rectorphp/rector/issues/8641#issuecomment-2115300157 , it seems on PHPStan 1.11, the PHPStan `ContainerFactory` need to be loaded early so :

```php
TypeCombinator::addNull()
```

can be used in the rector config.

**Before** (Internal error.)

```
➜  typo3-rector git:(bb) vendor/bin/rector process src/Helper --config templates/rector.php --dry-run --ansi --clear-cache

                                                                                                                        
 [ERROR] Internal error.                                                                                                                                                                                                                  
```

**After** (working ok)

```
➜  typo3-rector git:(bb) vendor/bin/rector process src/Helper --config templates/rector.php --dry-run --ansi --clear-cache
 4/4 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

                                                                                                                        
 [OK] Rector is done!                                                                                      
```

### CODE REVIEW

**Comment by samsonasik** [comment]
Hm.., it strange that when I create e2e test, it show diff when using `UnionType`, but not show the diff when using `TypeCombinator`

**With TypeCombinator**

```diff
➜  type-combinator-in-config git:(phpstan-service-factory-init) ✗ php ../e2eTestRunner.php 
 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%[OK] Rector is done!%  
```

**With UnionType**

```diff
➜  type-combinator-in-config git:(phpstan-service-factory-init) ✗ php ../e2eTestRunner.php
 3/3 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%1 file with changes
===================

1) src/NullWithObjectType.php:3

    ---------- begin diff ----------
@@ @@

 class NullWithObjectType implements FolderInterface
 {
-    public function create(string $fileName)
+    public function create(string $fileName): ?\App\FileInterface
     {

     }
    ----------- end diff -----------

Applied rules:
 * AddReturnTypeDeclarationRector


 [OK] 1 file would have changed (dry-run) by Rector%  
```

**Comment by samsonasik** [comment]
I added e2e test for it https://github.com/rectorphp/rector-src/pull/5897/commits/2aebf2328b5acb8fcb039fff2568902ce75e31d8

**Comment by samsonasik** [comment]
It seems due to overlapped config, and it loaded later, but because the rector config (cache path, etc) need to be loaded before it, it can't be flipped.

It seems using `UnionType` is the way to go for now.

Closing for now.

**Comment by simonschaufi** [comment]
Thank you for your attempt to fix it.

**Pull request closed without merging**
