### PR TITLE
[PHPStan] Clean up PHPStan ignore errors

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you :+1: 

I'm thinking... this is quite repeated operation across many projects. How can we automate with some CLI command (e.g. added into symplify/easy-ci) and auto-PR?

**Comment by samsonasik** [comment]
This check is by temporary comment out `reportUnmatchedIgnoredErrors` config, if its going to be automated, the check command may need to apply temporary comment out it and check errors with phrase "Ignored"

**Comment by TomasVotruba** [comment]
> if its going to be automated, the check command may need to apply temporary comment out it and check errors with phrase "Ignored"

That sound like a good start :+1: 

Could you come with such script in `bin/clean-phpstan.php`? I'll check and port it to EasyCI then

**Comment by samsonasik** [comment]
I will try.

**Pull request merged**
