### PR TITLE
[CodeQuality] Handle both ExplicitBoolCompareRector + CountArrayToEmptyArrayComparisonRector usage

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6561

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by freiondrej-economia** [comment]
@samsonasik thank you ❤️

**Pull request merged**
