### PR TITLE
[Php71] Skip CountOnNullRector on view files

### PR DESCRIPTION
**Pull request by samsonasik**
Most common usage for view that use data from controller can use the following code:

```
 echo 'Found' . count($this->data);
```

which can be skipped.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Hi, this seems like very custom and specific code. You see the added condition is pretty complex.
It would be better to skip it in your configuration for template files with `*`.

**Review by TomasVotruba — CHANGES_REQUESTED** [review]
Hi, this seems like very custom and specific code. You see the added condition is pretty complex.
It would be better to skip it in your configuration for template files with *.

**Comment by samsonasik** [comment]
Ok 👍 , I am closing it then

**Pull request closed without merging**
