### PR TITLE
[EarlyReturn] Handle Repetitive create If_ statement on use ChangeOrIfReturnToEarlyReturnRector+RemoveAlwaysElseRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
    public function run($a, $b, $c, $d)
    {
        if (($a && false === $b) || ! $c) {
            return '';
        } elseif ($d) {
            return '';
        }

        return $d;
    }
```

currently produces repetitive multiple ifs with same statement:

```diff
+        if ($a && false === $b) {
+            return '';
+        }
+        if (! $c) {
+            return '';
+        }
+        if ($a && false === $b) {
+            return '';
+        }
+        if (! $c) {
+            return '';
+        }
+        if ($a && false === $b) {
+            return '';
+        }
+        if (! $c) {
+            return '';
+        }
+        if ($a && false === $b) {
+            return '';
+        }
+        if (! $c) {
+            return '';
+        }
+        if ($a && false === $b) {
+            return '';
+        }
+        if (! $c) {
+            return '';
+        }
+        if ($a && false === $b) {
+            return '';
+        }
+        if (! $c) {
+            return '';
+        }
+        if ($a && false === $b) {
+            return '';
+        }
+        if (! $c) {
+            return '';
+        }
+        if (($a && false === $b) || ! $c) {
+            return '';
+        }
+        if ($d) {
+            return '';
+        }
+
         return $d;
```

For use rector rules combined:

```php
Rector\EarlyReturn\Rector\If_\ChangeOrIfReturnToEarlyReturnRector;
Rector\EarlyReturn\Rector\If_\RemoveAlwaysElseRector;
```

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba it seems due infinite loop with `do {  } while()` at `PhpFileProcessor`:

https://github.com/rectorphp/rector-src/blob/e00aa93d63b668f9d41cc73e5ec491e809603e93/src/Application/FileProcessor/PhpFileProcessor.php#L52-L58

If there is no `$loopCounter` to stop in 10, it will keep loop. 

I tried remove `printFile()` at last loop statement:

https://github.com/rectorphp/rector-src/blob/e00aa93d63b668f9d41cc73e5ec491e809603e93/src/Application/FileProcessor/PhpFileProcessor.php#L83

It make work, but it will broke other tests for Double Run test:

https://github.com/rectorphp/rector-src/blob/e00aa93d63b668f9d41cc73e5ec491e809603e93/tests/Issues/DoubleRun/Fixture/fixture.php.inc#L5-L21

**Comment by samsonasik** [comment]
Fixed 🎉 🎉 🎉

**Comment by samsonasik** [comment]
Check node stmt duplicate It seems cause erorr in `Ssch\TYPO3Rector` package tests:

```
1) Ssch\TYPO3Rector\Tests\Rector\Extensions\solr\v9\ApacheSolrDocumentToSolariumDocumentRector\ApacheSolrDocumentToSolariumDocumentRectorTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
tests/Rector/Extensions/solr/v9/ApacheSolrDocumentToSolariumDocumentRector/Fixture/fixture.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 namespace Ssch\TYPO3Rector\Tests\Rector\Extensions\solr\v9\ApacheSolrDocumentToSolariumDocumentRector\Fixture;
 
 use ApacheSolrForTypo3\Solr\System\Solr\Document\Document;
+use Apache_Solr_Document;
```

**Comment by samsonasik** [comment]
It seems cause error in rules-tests as well, it seems it affect node renaming.

**Comment by samsonasik** [comment]
@TomasVotruba the solution I found right now is to skip `RemoveAlwaysElseRector` when the if cond is a `BooleanOr`.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you for looking for the optimal solution. I like the way you fixed it 👍

**Pull request merged**
