### PR TITLE
[TypeDeclaration] Handle crash on object shape on ArrayShapeFromConstantArrayReturnRector

### LINKED ISSUE #8017: ArrayShapeFromConstantArrayReturnRector breaks when casting array to object
I'm using a trick to serialize empty associative arrays in JSON.
For that purpose I cast the array into an object before serializing it.

Here is an oversimplified example:
```php
<?php

final class Foo
{
    /**
     * @return array<string, stdClass>
     */
    public static function cleanup(?string $value): array
    {
        return [
            // Ensure empty metadata is serialized as `{}` and not `[]`
            'metadata' => (object) array_filter([
                'foo' => $value,
            ]),
        ];
    }
}

assert(json_encode(Foo::cleanup('c')) === '{"metadata":{"foo":"c"}}');
assert(json_encode(Foo::cleanup(null)) === '{"metadata":{}}');
```

It breaks the ArrayShapeFromConstantArrayReturnRector rule.

Here is the demo:
https://getrector.com/demo/ab809a74-239e-4b46-af98-b33a60643aa3

PS: Thanks for your amazing tool!

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8017

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @gitomato

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready ;)

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Comment by gitomato** [comment]
Thank you! The fix was insanely quick!

**Pull request merged**
