### PR TITLE
[Php54][Php80] Handle no scope on LongArrayToShortArrayRector+AnnotationToAttributeRector

### LINKED ISSUE #7349: `AnnotationToAttributeRector` fails when used with other sets
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.10             |

When using a big set of rules, an error occurs on various classes when have to be applied rules that use `AnnotationToAttributeRector`.

The error is reproduced in the demo.

Debugging the problem (activating sets one by one 😅🙅😫), I found the error may be caused by `AnnotationToAttributeRector`.

If the sets that use this class are removed from the configuration, Rector runs without errors.

If all sets are removed but the ones that use this class, Rector runs without errors and correctly changes the code base.

But if all sets are run together, then Rector crashes.

Honestly I don't know why, but I know this is the entry point to understand the problem.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/e4d999f2-425d-474d-af32-f8c5f7081c2f

## Expected Behaviour

Rector runs without errors.

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
use Doctrine\ORM\Mapping as ORM;

class ArrayInAttribtue
{
    public function __construct(
        /**
         * @ORM\ManyToOne(targetEntity=OfferPrice::class, inversedBy="myEntities", cascade={"persist"})
         */
        private OfferPrice $offerPrice
    )
    {
    }

}
```

It currently produce error:

```bash
There was 1 error:

1) Rector\Core\Tests\Issues\ArrayAnnotationToAttributeTest\ArrayAnnotationToAttributeTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\ShouldNotHappenException: Node "PhpParser\Node\Expr\Array_" with parent of "PhpParser\Node\Arg" is missing scope required for scope refresh.

/Users/samsonasik/www/rector-src/src/Application/ChangedNodeScopeRefresher.php:83
```

Applied rules:

```php
Rector\Php54\Rector\Array_\LongArrayToShortArrayRector
Rector\Php80\Rector\Class_\AnnotationToAttributeRector
```

Fixes https://github.com/rectorphp/rector/issues/7349

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @Aerendir

**Comment by samsonasik** [comment]
package-tests error is unrelated.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
