### PR TITLE
[DowngradePhp81] Handle crash parent Arg is missing scope on DowngradeFirstClassCallableSyntaxRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
use Exception;
use Symfony\Component\Config\Util\XmlUtils;

class SomeClass
{
    public function run(string $file)
    {
        try {
            $validateSchema = \Closure::fromCallable(array($this, 'validateSchema'));
            $dom = XmlUtils::loadFile($file, $validateSchema);
        } catch (Exception) {}
    }

    private function validateSchema(...$args) {}
}
```

currently cause crash:

```bash
There was 1 error:

1) Rector\Tests\DowngradePhp81\Rector\FuncCall\DowngradeFirstClassCallableSyntaxRector\DowngradeFirstClassCallableSyntaxRectorTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\ShouldNotHappenException: Node "PhpParser\Node\Expr\StaticCall" with parent of "PhpParser\Node\Arg" is missing scope required for scope refresh.
```

ref https://github.com/rectorphp/rector/issues/7193

### CODE REVIEW

**Comment by samsonasik** [comment]
The error seems happen when it is inside `try {} catch`

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
