### PR TITLE
[CodingStyle] Use alias name when exists on CatchExceptionNameMatchingTypeRector

### LINKED ISSUE #7047: Incorrect behavior of CatchExceptionNameMatchingTypeRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.12.17      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/175c6334-0093-41d2-b1ca-e8d7a1fbac08

```php
<?php
use Exception as TestException;

final class DemoFile
{
    public function run()
    {
        try {
            $a = 1;
        } catch (TestException $testException) {
        }
    }
}
```

### Responsible rules

* `CatchExceptionNameMatchingTypeRector`

## Expected Behavior

I think in this case the rule should not do anything as it should respect the import alias.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7047

### CODE REVIEW

**Comment by samsonasik** [comment]
implemented 🎉 /cc @freiondrej-lmc

**Comment by freiondrej-lmc** [comment]
@samsonasik thank you! It's really amazing to see how well Rector's code is written because something like this is so easy to implement. Seeing the code is a great inspiration for writing my own rules :)

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you @samsonasik

**Pull request merged**
