### PR TITLE
Test for method signatures with default value

### PR DESCRIPTION
**Pull request by norgeindian**

### CODE REVIEW

**Comment by samsonasik** [comment]
I checked locally, it seems it needs some tweak as there is internal php-parser error like at https://github.com/rectorphp/rector-src/pull/1431#discussion_r765431501

**Comment by samsonasik** [comment]
@norgeindian I cherry-picked your commit at PR https://github.com/rectorphp/rector-src/pull/1452

**Comment by TomasVotruba** [comment]
@norgeindian Thank you for the test fixture 👍

**Comment by norgeindian** [comment]
@TomasVotruba , @samsonasik , thanks, that seems to work perfectly.

**Pull request closed without merging**
