### PR TITLE
[Printer] Handle Add Node after Nop statement inlineHTML

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```
<?php

/** @var Zend_View $this */
?>
<div>
    <?php echo $this->filter ;?>
</div>
```

Add Node after `Nop` stmt got the following diff:

```diff
 <?php
 
 /** @var Zend_View $this */
 ?>
+
+echo 'this is new stmt after Nop';<div>
```

which invalid, This PR try to fix it.

### CODE REVIEW

**Comment by samsonasik** [comment]
The `Nop` seems need to marked as comment of next statement

**Review by staabm — APPROVED** [review]
I think it looks good. I am not much into the topic though

**Comment by samsonasik** [comment]
After marking Nop as comment, because of next stmt as InlineHTML has php tag inside, it got duplicated `<?php <?php` when reprinted:

```diff
 /** @var Zend_View $this */
 echo 'this is new stmt after Nop';?>
-<div><?php echo $this->filter ;?></div>
+<div><?php <?php echo $this->filter ;?></div>
```

**Comment by samsonasik** [comment]
Fixed with tweak double `<?php` when re-printed, I will create separate service as it used as well on return array of Nodes on `AbstractRector`.

**Comment by samsonasik** [comment]
I added another faling fixture for multiline php code on next InlineHTML https://github.com/rectorphp/rector-src/pull/3303/commits/b1c55325a8067d3200449f82d0f92faf2fe25f86, the unit test somehow printed 1 failure and next call 2 failure, somehow probably the printer cache due to same node print html.

**Comment by samsonasik** [comment]
It seems fixable by remove the cache refactor on test source https://github.com/rectorphp/rector-src/pull/3303/commits/fbd925d34deb30cad510514762e5cf8c07e94a71

**Comment by samsonasik** [comment]
Fixed 🎉 , this is not perfect, but at least no error :), @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Pull request merged**
