### PR TITLE
[Core][e2e] Do not reprint from PhpParser when no RectorWithLineChange or empty diff

### LINKED ISSUE #7748: Can we revert file changes if no rules applied?
# Question

I know that, due to AST, there is a small subset of files where lines are trimmed. 

This is not a problem if project is small and not if there are other changes in the file.

But I'm facing a huge >20k file project. Running a simple custom rule to do a name change to fix a typo,  I got over 2400 files changed, but only 24 with the fix applied.

So, I am asking if there is something like a 'postFileProcessing' hook where to count file changes, or verify if any rules applied, and then ask rector to simply NOT save the file. 

This avoid the problem of "useless" trimming of files. 

I also known is an already spoken question, but I'm posing it in a different way, to eventually ipotize a different solution.

Also, an hook fired after each file processed could be very usefull for A LOT of automations

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7748

### CODE REVIEW

**Comment by samsonasik** [comment]
It works 🎉 , by this, no need e2e expected output space removal from `e2e/plain-views` as just print the file content instead of print by PhpParser as no rule applied into the view files /cc @staabm

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Review by staabm — APPROVED** [review]

**Comment by samsonasik** [comment]
I found that when there is PostRector, eg: `importNames()`, the diff may not be shown with this tweak, I will re-check.

**Comment by samsonasik** [comment]
I added fixture to verify it, it seems working ok 🎉 , ref https://github.com/rectorphp/rector-src/pull/3403/commits/a037339938290360e84a28c3198550ed7de7025a

**Comment by samsonasik** [comment]
Ok, It was different file name for `e2e/plain-views/expected_output.diff` to be `e2e/plain-views/expected-output.diff`, the faiilng fixture for is now failure, I will check more.

**Comment by samsonasik** [comment]
Fixed with verify if there is PostRector change `$newStmts`, then allow reprint https://github.com/rectorphp/rector-src/pull/3403/commits/ff6015486a22fdfda59dc5b7185de40074d9eaa6

**Comment by samsonasik** [comment]
Finally 🎉🎉🎉 All checks have passed 🎉

Here the summary:

- On `PhpFileProcessor`, it was try to make a diff even no rule applied, which on view plains HTML case, it make space removal because of printing by PhpParser
- This PR make no add diff change when no rule change the file 
- The `PostRector` doesn't have `RectorWithLineChange`, so verify if no rule applied, then compare the new stmts result before and after `PostRector` to keep apply PostRector, eg: `importNames()` to verify there is change after refactored so it can show the diff of `PostRector`

@TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba this also fixes https://github.com/rectorphp/rector/issues/7748 to not apply change if no rule applied, I added fixture for it https://github.com/rectorphp/rector-src/pull/3403/commits/0ec65adc886908247d64adf6b338ca8ef6f11009 with whitespace is kept 👍 

/cc @realtebo

**Comment by TomasVotruba** [comment]
Go for the merge when ready :+1:

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by Mirko-Tebaldi** [comment]
If this works, you saved my life !

**Comment by samsonasik** [comment]
@Mirko-Tebaldi you can try dev-main for now:

```
composer config minimum-stability dev
composer config prefer-stable true
composer require --dev rector/rector:dev-main

**Comment by samsonasik** [comment]
Oh, without `--dry-run`, it keep changing the file, I will re-check on it :)

**Pull request merged**
