### PR TITLE
[DowngradePhp80] Skip remove self on DowngradeStaticTypeDeclarationRector

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #720

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by samsonasik** [comment]
It seems it somehow cause error on scoper builds 

https://github.com/rectorphp/rector/runs/3382501532

**Comment by samsonasik** [comment]
Fixed 🎉 🎉 🎉 

Screen Shot 2021-08-21 at 00 59 26

https://github.com/rectorphp/rector/commit/056fee1788d653f5ed87d1771c88650c66a9d3a2

**Pull request merged**
