### PR TITLE
[TypeDeclaration] Skip parameter string with default array on ParamTypeDeclarationRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
class SkipStringDefaultArray
{
    /**
     * @param string $value
     */
    public function someFunction($value = [])
    {
    }
}
```

It currently produce : 

```diff
+    public function someFunction(string $value = [])
```

which make fatal error: "Cannot use array as default value for parameter $value of type string" ref https://3v4l.org/FS8cm

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
