### PR TITLE
Failing Tests for DowngradeMatchToSwitchRector

### PR DESCRIPTION
**Pull request by jrstanley**
# Failing Tests for DowngradeMatchToSwitchRector

This PR adds two failing tests relating to unexpected behaviour with DowngradeMatchToSwitchRector.

## UseResult

This covers use of the return value of `match` e.g. `echo match...` in a way that is not currently catered for (only `return match...` and assignment `$result = match...` appear to be).

* [getrector.org demo: Current working example with assignment](https://getrector.org/demo/1a763da7-1263-4e28-9a3e-d000a51cf222).
* [getrector.org demo: Scenario that this test covers. Rector makes no changes](https://getrector.org/demo/92faf77f-1234-4b52-84bf-745ec7e89776).
* [PHP demo executing `match` in the way that this test covers](https://3v4l.org/hjIPg)
* [PHP demo executing `switch` as per the expected output covered by this test](https://3v4l.org/IWi0T)

## UnusedResult

This test covers `match` being called without the return value being 'used' (e.g. `echo match...` as the test above adds), or assigned or returned as Rector currently supports.

This is a [valid use-case for match according to the PHP docs](https://www.php.net/match#:~:text=Note%3A%20The%20result%20of%20a%20match%20expression%20does%20not%20need%20to%20be%20used.).

I'm unsure how values should be treated that are never 'used'. There are cases in a `match` where you might call a method as part of the branch. This test adds an example of this scenario. Perhaps the expected output would be different than what I have proposed, however I think that the current behaviour (no-op) is incorrect.

* [getrector.org demo: Scenario that this test covers. Rector makes no changes](https://getrector.org/demo/37208140-8b0e-435c-b97d-ddac64647d56)
* [PHP demo executing `match` in the way that this test covers](https://3v4l.org/WRjtr).
* [PHP demo executing `switch` as per the expected output covered by this test](https://3v4l.org/qPDSE).

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the failing test fixtures :+1: 
Could you come up with fix too?

**Comment by jrstanley** [comment]
> Thanks for the failing test fixtures :+1: 
> 
> Could you come up with fix too?

I'm happy to give it a go! I'll update this PR with my attempt.

**Comment by jrstanley** [comment]
Similar to https://github.com/rectorphp/rector/issues/7128 which discusses `switch`->`match` and equality, I wonder if we should be downgrading `match` to `switch` at all? This could cause a `switch` arm to execute where a `match` arm would not due to the loose equality check of a `switch` vs the strict equality check of the `match`.

Should we downgrade using something like an `if` statement instead?

**Comment by TomasVotruba** [comment]
> Should we downgrade using something like an if statement instead?

It could be a way to go. I think the best is to ask, how would you write the same code in PHP 7.4?

**Comment by jrstanley** [comment]
@TomasVotruba Proposed new fixtures in this PR are now passing.

I have not addressed [the comment around strict/loose equality checks](https://github.com/rectorphp/rector-src/pull/2114#issuecomment-1107635831) and I would also like to look at downgrading `match` when used in a method call.

If this looks good to you, perhaps this PR can be merged and I will file PR failing fixtures separately for the above and anything else?

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you, this looks very good 👍

I agree, let's take it one small PR at a time

**Pull request merged**
