### PR TITLE
 [Traverser] Introduce ImprovedParentConnectingVisitor 

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba @staabm this is an experiment for RFC:

- https://github.com/rectorphp/rector/issues/8035

which introduce most common parent attribute use with enter to node instead of stack the nodes from stmt depths.

### CODE REVIEW

**Comment by staabm** [comment]
I think to decide whether this makes sense or not, we should look into memory consumption before/after this PR.

maybe its also usefull to count the overall nodes in the AST and determine how many of the nodes have a parent attribute before/after this PR

**Comment by staabm** [comment]
are we already at a point, at which we know we can't drop parent attributes for the remaining classes?

**Comment by samsonasik** [comment]
This is experiment to test the memory consumption usage, whether it is worth or not is we can decide later.

Rector is rely on parent dynamically a lot, which we can reduce, but fill the node with attribute like: `is_arg_value`, `is_expr_from_param` will make too ugly imo, and at some point, we really need to fill `Expr` with `Stmt`, like detecting if variable from param, and try to traverse base on parent FunctionLike.

**Comment by samsonasik** [comment]
closing as parent attribute usages are removed.

**Pull request closed without merging**
