### PR TITLE
Apply rector to the self `.phpstorm.meta.php`

### PR DESCRIPTION
**Pull request by andrew-demb**
Extracted from https://github.com/rectorphp/rector-src/pull/6592

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I'm curious, what is a reason behind this change?

In the docs https://www.jetbrains.com/help/phpstorm/ide-advanced-metadata.html#expected-arguments, only static syntax is allowed.

Screenshot from 2024-12-15 19-18-12

**Comment by andrew-demb** [comment]
@TomasVotruba This is an automated change by Rector - after introducing "include dotfiles for `withRootFiles`" - Rector refactored this file.

Why rector refactored `\PHPStan\PhpDocParser\Ast\Node::getAttribute()` to the `(new Node())->getAttribute()` - because `getAttribute` is not a static method.

Should I add an ignore rule for `.phpstorm.meta.php` in `rector.php`?

**Comment by TomasVotruba** [comment]
I think we have to be more careful here.

How would this be handled in the wild? We don't want Rector breaking this file on next update.

**Comment by andrew-demb** [comment]
We can hardcode ignoring this filename in the `withRootFiles` to avoid applying rector to this file (which can not be interpreted by PHP)

**Comment by TomasVotruba** [comment]
Sounds good 👍

**Comment by andrew-demb** [comment]
Closed in favor https://github.com/rectorphp/rector-src/pull/6594

**Pull request closed without merging**
