### PR TITLE
[TypeDeclaration] Directly use ParametersAcceptorSelector::selectFromArgs() on AlwaysStrictScalarExprAnalyzer

### PR DESCRIPTION
**Pull request by samsonasik**
I think check variants count is not needed.

### CODE REVIEW

**Comment by samsonasik** [comment]
CI error on `rector-laravel` tests seems unrelated:

```bash

There were 4 errors:
1) Rector\Laravel\Tests\Rector\Class_\AddMockConsoleOutputFalseToConsoleTestsRector\AddMockConsoleOutputFalseToConsoleTestsRectorTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Symfony\Component\DependencyInjection\Exception\RuntimeException: Cannot autowire service "Rector\Laravel\Rector\Class_\AddMockConsoleOutputFalseToConsoleTestsRector": argument "$setUpClassMethodNodeManipulator" of method "__construct()" has type "Rector\PHPUnit\NodeManipulator\SetUpClassMethodNodeManipulator" but this class was not found.
```

**Comment by samsonasik** [comment]
@TomasVotruba it seems cause by removed `SetUpClassMethodNodeManipulator` from rector-phpunit https://github.com/rectorphp/rector-phpunit/pull/90/files#diff-2b1cd88a5ec839ec7292d94b565f906bb4d7595d3c35c258c9a758b191b2d955 that uses by rector-laravel.

**Comment by samsonasik** [comment]
https://github.com/rectorphp/rector-laravel/pull/56

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
I think the `selectFromArgs()` is less effective and requires more analysis of input data. That's why it's fallback in case of multi varians.

**Review by TomasVotruba — CHANGES_REQUESTED** [review]
I'd keep the original.

**Comment by samsonasik** [comment]
there are many places in rector-src for using `selectSingle()`, and that can cause a possible bug again in the future like in: 

- https://github.com/rectorphp/rector-src/pull/2494

due to multi variants. 

Except, we create a wrapper check for it to single service, eg: `ParametersAcceptorSelectorWrapper`, wdyt?

**Comment by samsonasik** [comment]
I created alternative PR for it 

- https://github.com/rectorphp/rector-src/pull/2607

**Comment by TomasVotruba** [comment]
> Except, we create a wrapper check for it to single service, eg: ParametersAcceptorSelectorWrapper, wdyt?

That seems as the best option :+1: 

I wonder how @ondrejmirtes would recommend to deal with multiple-variants.

**Comment by samsonasik** [comment]
https://github.com/rectorphp/rector-src/pull/2607

**Pull request closed without merging**
