### PR TITLE
[DeadCode] Using treatPhpDocTypesAsCertain: false in config/phpstan/better-infer.neon to avoid invalid result on RemoveUnreachableStatementRector

### PR DESCRIPTION
**Pull request by samsonasik**
Closes https://github.com/rectorphp/rector-src/pull/2130

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba the `treatPhpDocTypesAsCertain: false` seems the solution 🎉 .

It still not detect correctly for `@var` which exactly check of what its defined, but it is better than before, so user when define `@var Request|CliRequest` but check against `$obj instanceof Request`, it will return early, which user needs to add `null` when it can be null.

@TomasVotruba it is ready for merge ;)

**Comment by TomasVotruba** [comment]
Keep this open please, I'll check it next week.

**Comment by samsonasik** [comment]
@TomasVotruba yes, this is the step to reproduce the issue:

```
git clone git@github.com:samsonasik/framework-2.git framework-2
cd framework-2
git checkout update-rector-re-run 
composer config minimum-stability dev
composer config prefer-stable true
composer remove --dev rector/rector
composer require --dev rector/rector:dev-main
vendor/bin/rector --dry-run
```

The issue never happen in 0.12.21.

**Comment by samsonasik** [comment]
I created alternative and more robust PR https://github.com/rectorphp/rector-src/pull/2137

**Pull request closed without merging**
