### PR TITLE
make sure windows uses LF, for files, which we expect to always use LF, no matter the platform

### PR DESCRIPTION
**Pull request by staabm**
this change fixes the following test-errors on windows:

```
4) Rector\Tests\FileFormatter\Formatter\JsonFileFormatter\JsonFileFormatterTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
 #Warning: Strings contain different line endings!
-'{
-	"name": "foo/bar",
-	"description": "A foo bar baz extension",
-	"license": "GPL-2.0-or-later"
-}
+'{
+	"name": "foo/bar",
+	"description": "A foo bar baz extension",
+	"license": "GPL-2.0-or-later"
+}
 '

5) Rector\Tests\FileFormatter\Formatter\XmlFileFormatter\XmlFileFormatterTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
 #Warning: Strings contain different line endings!
-'<?xml version="1.0"?>
+'<?xml version="1.0"?>

 <catalog>
 	<book id="bk101">
 		<author>Gambardella, Matthew</author>
@@ @@
 		<description>An in-depth look at creating applications
 		with XML.</description>
 	</book>
-</catalog>
+</catalog>
 '

6) Rector\Tests\FileFormatter\Formatter\YamlFileFormatter\YamlFileFormatterTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
 #Warning: Strings contain different line endings!
-'martin:
-    name: Martin
-    job: Developer
-    skills:
-        - python
-        - perl
-        - pascal
+'martin:
+    name: Martin
+    job: Developer
+    skills:
+        - python
+        - perl
+        - pascal
 '

 7) Rector\Tests\FileFormatter\ValueObject\NewLineTest::testFromFiles with data set "Xml file with line feed" (Symplify\SmartFileSystem\SmartFileInfo Object (...), '\n')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
 #Warning: Strings contain different line endings!
-'
+'
 '
 ```

tested in https://github.com/rectorphp/rector-src/pull/99

see github-action logs
before: https://github.com/rectorphp/rector-src/pull/99/checks?check_run_id=2677137859
after: https://github.com/rectorphp/rector-src/pull/99/checks?check_run_id=2677399492

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks. Is this ready to merge?

**Comment by staabm** [comment]
yep.

**Comment by TomasVotruba** [comment]
Lets :ship: it!

**Comment by staabm** [comment]
Just fyi: this fix is not the best possible way, but I am still in the process of getting the test-suite green on windows. After we get thru this first round, we can revisit the changes from this PR and work on a better fix

**Comment by TomasVotruba** [comment]
That sound good enough to me. Unless it's breaks Linux tests and fixes the correct problem (line endins etc.) problem, I'm ok with that :+1:

**Pull request merged**
