### PR TITLE
[TypeDeclaration] Using negation on BinaryOr on BinaryOpNullableToInstanceofRector

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://github.com/rectorphp/rector-src/pull/3631#discussion_r1171190598
See phpstan https://phpstan.org/r/02f3d34b-8807-4c44-9a80-57005c09e19b

### CODE REVIEW

**Comment by TomasVotruba** [comment]
This should be a new fixture and old should be untouched. 
Both should be supported, as this only converts the `!== null` value to exact type check

**Comment by samsonasik** [comment]
Ok 👍

**Comment by samsonasik** [comment]
Reverted original fixture, I will add more fixture.

**Comment by samsonasik** [comment]
I added new fixture for negation https://github.com/rectorphp/rector-src/pull/3633/commits/e62a5e54b7f6b4d18dde6da0547263606f919142

**Comment by samsonasik** [comment]
implemented :tada:

**Comment by samsonasik** [comment]
All checks have passed :tada: @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Review by TomasVotruba — COMMENTED** [review]
Thanks 🙏

**Pull request merged**
