### PR TITLE
[Config] update duplicate Skip fixture config

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba the test error seems unrelated as it works in my local dev:

```bash
➜  rector-src git:(duplicate-fixture-skip) php80 vendor/bin/phpunit packages-tests                                         p 
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

...............................................................  63 / 237 ( 26%)
............................................................... 126 / 237 ( 53%)
............................................................... 189 / 237 ( 79%)
................................................                237 / 237 (100%)

Time: 00:00.896, Memory: 110.50 MB
```

**Comment by samsonasik** [comment]
I updated to use `'*/Fixture*/*',` to cover FixturePhp74 dir

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks

**Pull request merged**
