### PR TITLE
[TypeDeclaration] Skip Throw_ in construct and as Expr on ReturnNeverTypeRector

### LINKED ISSUE #6939: Incorrect behavior of ReturnNeverTypeRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec75420-68c4-6dd4-99cb-7fa782f409a8

```php
<?php

final class DemoFile
{
    private object $foo;
    
    public function __construct(SomeClass $someClass)
    {
        $this->foo = $someClass ?: throw new Exception('current request is null');
    }
}
```

### Responsible rules

* `ReturnNeverTypeRector`

## Expected Behavior

No change

The probem seems to be related to the `throw new Exception` call. In PHP 8.1 the above code results in the never typehint being added to the construct function which is wrong.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6939

### CODE REVIEW

**Comment by samsonasik** [comment]
It seems PHPStan 1.4.0 cause error:

```bash

  packages/PostRector/Collector/PropertyToAddCollector.php:72
 ------------------------------------------------------------------------
  - '#Property Rector\\PostRector\\Collector\\PropertyToAddCollector\:\:\$propertiesWithoutConstructorByClass \(array<string, array<string, PHPStan\\Type\\Type\>\>\) does not accept array<string, array<string, PHPStan\\Type\\Type\|null\>\>#'
 ------------------------------------------------------------------------

 ------------------------------------------------------------------------
  rules/DowngradePhp81/Rector/FunctionLike/DowngradeNewInInitializerRector.php:171
 ------------------------------------------------------------------------
  - '#Access to an undefined property PhpParser\\Node\\FunctionLike\:\:\$stmts#'
 ------------------------------------------------------------------------

 ------------------------------------------------------------------------
  rules/PhpSpecToPHPUnit/Rector/ClassMethod/PhpSpecMethodToPHPUnitMethodRector.php:81
 ------------------------------------------------------------------------
  - '#Property PhpParser\\Node\\Stmt\\ClassMethod\:\:\$stmts \(array<PhpParser\\Node\\Stmt\>\|null\) does not accept array<PhpParser\\Node\\Stmt\|null\>#'
  - ```

**Comment by samsonasik** [comment]
PHPStan notice resolved 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
