### PR TITLE
[FileProcessor] Add warning instead of skip InlineHTML on PhpFileProcessor

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://github.com/rectorphp/rector-src/pull/4055#pullrequestreview-1460397597

Instead of skip, better to show warning so user can just use it but need to verify manually the rectored file.

### CODE REVIEW

**Comment by samsonasik** [comment]
I [removed with inline html fixture](https://github.com/rectorphp/rector-src/pull/4058/commits/a7201699e779d774a5dbde85562e285e80eabe98) as `SymfonyStyle` warning seems not shown in unit test.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
@TomasVotruba here the output with warning instead of skip which fine on indirect change near InlineHTML:

```diff
➜  rector-src git:(add-warning) ✗ bin/rector process vendor/tracy/tracy/src/Tracy/BlueScreen/assets/section-stack-callStack.phtml --config build/config/config-downgrade.php --dry-run
 0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
 [WARNING] File vendor/tracy/tracy/src/Tracy/BlueScreen/assets/section-stack-callStack.phtml has InlineHTML node, this  
           may cause unexpected output, you may need to manually verify the changed file                                

 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
1 file with changes
===================

1) vendor/tracy/tracy/src/Tracy/BlueScreen/assets/section-stack-callStack.phtml:71

    ---------- begin diff ----------
@@ @@
                        try {
                                $r = isset($row['class']) ? new \ReflectionMethod($row['class'], $row['function']) : new \ReflectionFunction($row['function']);
                                $params = $r->getParameters();
-                       } catch (\Exception) {
+                       } catch (\Exception $exception) {
                                $params = [];
                        }
                        foreach ($row['args'] as $k => $v) {
    ----------- end diff -----------

Applied rules:
 * DowngradeNonCapturingCatchesRector (https://wiki.php.net/rfc/non-capturing_catches)
```

so this should good to have it processed 👍

**Review by Ocramius — APPROVED** [review]
Good idea to leave mixed HTML+PHP alone, but some more verification (test) would be a good idea 😁

**Comment by kenjis** [comment]
It seems better to support mixed HTML+PHP even if there are limitations.

**Comment by samsonasik** [comment]
@Ocramius the tests were on MixedPhpHtmlDecorator, since that decorator removed at PR:

- https://github.com/rectorphp/rector-src/pull/4054

so the tests not needed in here

**Review by kenjis — APPROVED** [review]

**Comment by samsonasik** [comment]
I enabled php-linter for tracy PHP+HTML file to be checked after downgrade for verifying on scoped build that the file still downgraded correctly 👍 https://github.com/rectorphp/rector-src/pull/4058/commits/e88a3c6e60e09177a320164380f94929256ab39e + https://github.com/rectorphp/rector-src/pull/4058/commits/d24dc9ff890efaa6482c54d989c13c98e96df9e2

**Comment by TomasVotruba** [comment]
Looks good, lets give it a try :+1: 

If the feedback is rather breaking code again, we'll disable it to avoid causing errors.

**Pull request merged**
