### PR TITLE
[Php80] Add typed property Closure support on ClassPropertyAssignToConstructorPromotionRector

### LINKED ISSUE #7723: `ClassPropertyAssignToConstructorPromotionRector` ignores `\Closure`
# Feature Request

`ClassPropertyAssignToConstructorPromotionRector` ignores my `\Closure` property. It works for `string` or `int`.

https://getrector.org/demo/f26b947d-4fc8-4ba4-b3dc-6d5b16827919

Thanks again for rector. It makes my life more awesome :heart: 
 
## Diff 

I would expect something like this:

```diff
 final class TestKernel
 {
-     private readonly \Closure $configureContainerBuilder; 

     public function __construct(
-         \Closure $configureContainerBuilder,
+         private readonly \Closure $configureContainerBuilder,
     ) {
-         $this->configureContainerBuilder = $configureContainerBuilder;
     }
 }
```

### PR DESCRIPTION
**Pull request by samsonasik**
Closes https://github.com/rectorphp/rector/issues/7723

### CODE REVIEW

**Comment by samsonasik** [comment]
implemented /cc @mvhirsch

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by mvhirsch** [comment]
Thank you!

**Pull request merged**
