### PR TITLE
[DeadCode][Defluent][NodeNameResolver] Using CallAnalyzer to check object call when possible

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
It may cause invalid result for in negation check. I am closing it for now.

**Comment by samsonasik** [comment]
Re-open, it should be ok actually, On : 

- NodeNameResolver, it check Method call or Static Call's name, which impossible to be BooleanNot or BinaryOp
- RemoveEmptyMethodCallRector, it check against Method call or Static Call's var ,which impossible to be BooleanNot or BinaryOp
- FluentChainMethodCallNodeAnalyzer, it check against Method call var, which imposible to be BooleanNot or BinaryOp

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks :+1: 

Is there some test fixture you could provide so it's easier to see what the change is related to?

**Comment by samsonasik** [comment]
- For NodeNameResolver test, it possibly need to be in PR https://github.com/rectorphp/rector-src/pull/458
- For RemoveEmptyMethodCallRector, it on the following fixures:

    * https://github.com/rectorphp/rector-src/blob/main/rules-tests/DeadCode/Rector/MethodCall/RemoveEmptyMethodCallRector/Fixture/skip_fluent_return_this.php.inc

    * https://github.com/rectorphp/rector-src/blob/main/rules-tests/DeadCode/Rector/MethodCall/RemoveEmptyMethodCallRector/Fixture/skip_fluent_return_this2.php.inc
    
- For FluentChainMethodCallNodeAnalyzer, it on the following fixture:

     * https://github.com/rectorphp/rector-src/blob/main/rules-tests/Defluent/Rector/Return_/DefluentReturnMethodCallRector/Fixture/skip_part_of_fluent_call.php.inc

**Comment by TomasVotruba** [comment]
I see, then it's well tested.

Thank you :+1:

**Pull request merged**
