### PR TITLE
Add remove parent call rector

### PR DESCRIPTION
**Pull request by jaapio**
This rector allows users to remove calls to the parent class, for example when a parent method is removed.

```diff
class SomeClass extends Other
{
   public function __construct() {
-     parent::__construct();
      /* ... */
   }

   public function other() {
-     parent::some();
      /* ... */
   }
}
```

- [ ] add tests

### CODE REVIEW

**Comment by jaapio** [comment]
@TomasVotruba this requires tests, but before I continue, I would like to know if this rector is something you would merge :-)

**Comment by jaapio** [comment]
```
 ------------------------------------------------------------------------
  rules/Removing/Rector/StaticCall/RemoveParentMethodCallRector.php:98
 ------------------------------------------------------------------------
  - '#Use separate function calls with readable variable names#'
 ------------------------------------------------------------------------
 ```
 
 I don't get this phpstan error.

**Comment by TomasVotruba** [comment]
Hey, this would be useful 👍

It reminds me https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#removeparentcallwithoutparentrector 

How it differs?

**Comment by jaapio** [comment]
It will fix this issue: https://3v4l.org/Zn7KK. 

The class has a parent, but the parent method doesn't exist.

**Comment by TomasVotruba** [comment]
I see :+1: Please go for it then :)

**Comment by samsonasik** [comment]
There is `RemoveDelegatingParentCallRector` and `RemoveParentCallWithoutParentRector` for that, if there is some improvement to do, I think it can be in there instead, ref 

- https://getrector.org/demo/ae00bdab-f6d7-40a8-b510-bc64b78b9c7e
- https://getrector.org/demo/bb10c4e4-e203-498a-b9ee-1b66bad6befb

**Comment by jaapio** [comment]
The improvements that are required in both rectors you mention is that we do have a parent class, but the method does not exist in the parent. Resulting in an error. 

The result is also different, we are just removing the call to the parent class and not the method itself. My example is a bit small, and I think we could detect this automatically when rector is able to find all methods in a inheritance tree. This would allow us to check if one of the parents has such method. 

```
class A { 
    public function AMethod() {}
}

class B extends A {
  
   public function BMethod();
}

class C extends B
{
   public function method1() {
     parent::AMethod(); //correct and works
   }

   public function method2 {
      parent::BMethod(); //correct and works
   }
  
  /** Method to be kept */
   public function AMethod() {
      parent::AMethod();
      $this->foo++;
   }

     /** Method to be removed by RemoveDelegatingParentCallRector  */
   public function AMethod2() {
      parent::AMethod();
   }

   public function AMethod3() {
      parent::CMethod();  //to be removed, by this new rector but requires config
      $this->foo++;
   }
}
```

**Comment by samsonasik** [comment]
@jaapio could you show in getrector.org/demo page that currently not working for `RemoveDelegatingParentCallRector` or/and `RemoveParentCallWithoutParentRector` and the expected output?

**Comment by TomasVotruba** [comment]
Closing for lack of feedback, to keep issue tracker focus on unclear issues that needs our attention.

Feel free to send PR with passing CI  :+1:

Thank you for understanding :slightly_smiling_face:

**Pull request closed without merging**
