### PR TITLE
[TypeDeclaration] Do not change more detailed return doc on ReturnTypeFromStrictNewArrayRector

### LINKED ISSUE #7280: Incorrect behavior of ReturnTypeFromStrictNewArrayRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.13.7      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/bd5eb529-b323-4d39-a18a-831de24b4ac5

```php
<?php

final class DemoFile
{
    /**
     * @param array<int|string, null|int|string> $ParameterArray
     *
     * @return array<string, string>
     */
    public function getFilterFromParameterArray2($ParameterArray) {

        $filter = [
            'where'  => '',
            'having' => '',
            'from'   => '',
        ];

        $where_filter_sql = '1=1';

        $where_filter_sql .= ' ... '; // sql stuff -> one line is working with reactor
        $where_filter_sql .= ' ... '; // sql stuff -> the next lines will break the phpdoc??

        $filter['where'] = $where_filter_sql;

        return $filter;
    }
}
```

### Responsible rules

* `ReturnTypeFromStrictNewArrayRector`

## Expected Behavior

do not use ```mixed``` as return

### LINKED ISSUE #7281: Incorrect behavior of ReturnTypeFromStrictNewArrayRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.17.3      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/0f8ccfef-0e40-4c43-913e-c7c155ea2b18

```php
<?php

final class DemoFile
{
 	/**
     * @return list<string>
     */
    public function getCsvHeaderArray() {
        $HeaderArray = [];

        $HeaderArray[] = i::_('Lager');
        $HeaderArray[] = i::_('Art.Nr.');
        $HeaderArray[] = i::_('Kontenplankonto');
        $HeaderArray[] = i::_('Lieferant');
        $HeaderArray[] = i::_('Artikel');
        $HeaderArray[] = i::_('Preis');
        $HeaderArray[] = i::_('Menge');
        $HeaderArray[] = i::_('Einheit');
        $HeaderArray[] = i::_('Wert');
        $HeaderArray[] = i::_('Mwst');

        return $HeaderArray;
    }
}

class i
{
    /**
	 * @param literal-string $input
     */
    public function _($input): string
    {
    	return (string)$input; // dummy oode
    }
}
```

### Responsible rules

* `ReturnTypeFromStrictNewArrayRector`

## Expected Behavior

Keep the correct phpdocs, maybe an option to change only more explicit phpdocs would help for such things?

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7280
Fixes https://github.com/rectorphp/rector/issues/7281

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @voku

**Comment by samsonasik** [comment]
it seems check sub type on `PhpDocTypeChanger::changeReturnType()` cause error in `ArrayShapeFromConstantArrayReturnRector`:

```bash

1) Rector\Tests\TypeDeclaration\Rector\ClassMethod\ArrayShapeFromConstantArrayReturnRector\ArrayShapeFromConstantArrayReturnRectorTest::test with data set #12 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules-tests/TypeDeclaration/Rector/ClassMethod/ArrayShapeFromConstantArrayReturnRector/Fixture/include_external_constants.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 final class IncludeExternalConstants
 {
     /**
-     * @return array{line: int, file: string}
+     * @return array<string, string|int>
      */
```

**Comment by samsonasik** [comment]
Fixed 🎉 by check sub type directly before `PhpDocTypeChanger::changeReturnType()` called https://github.com/rectorphp/rector-src/pull/2638/commits/d7906b3d91daf78ef7abe0c308ba1e136da981a6

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
