### PR TITLE
[CodeQuality][TypeDeclaration] Add string append support on ReturnTypeFromStrictScalarReturnExprRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
class StringAppendVariable
{
    public function resolve(array $data)
    {
        $content = '';

        foreach ($data as $value) {
            $content .= $value;
        }

        return $content;
    }
}
```

should result:

```diff
-    public function resolve(array $data)
+    public function resolve(array $data): string
```

as it returns appended from initialized string content variable.

### CODE REVIEW

**Comment by samsonasik** [comment]
implemented 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
