### PR TITLE
[DeadCode] Allow not has side effect duplicate assign on RemoveDoubleAssignRector

### PR DESCRIPTION
**Pull request by samsonasik**
- Using `SideEffectNodeDetector` service for function that not has side effect detection, eg: `strlen()`
- Add more function to `PureFunctionDetector:: IMPURE_FUNCTIONS` for functions with side effects:

```php
'array_pop', 'array_push', 'array_shift', 'array_pop', 'next', 'prev',
```

- Allow internal new `PhpParser` object to be detected as not has side effect.

### CODE REVIEW

**Comment by samsonasik** [comment]
Closing for now as it cause removing on different args, eg:

```php
$value = strlen('test');
$value = strlen('different-value');
```

**Comment by samsonasik** [comment]
Actually, for function that not has side effect, it actually fine to remove previous value assign, as the following will be skipped:

```php
$key = 'data';

$key = str_replace('a', 'b', $key);
$key = str_replace('b', 'c', $key);
```

The only issue is it is removing first comment:

```
// a comment
$value = strlen('test');
$value = strlen('different-value');
```

produce:

```diff
-// a comment
-$value = strlen('test');
 $value = strlen('different-value');
```

which may be needed.

**Comment by samsonasik** [comment]
Closing for now, the comment seems keep removed due previous statement removed after it, event the object is cloned.

**Comment by TomasVotruba** [comment]
> Closing for now, the comment seems keep removed due previous statement removed after it, event the object is cloned.

I think it's ok to remove the first comment :heavy_check_mark: 

Also, the comment locations are often opinionated, some should belong to first line and some to second line. Rector cannot know what is right or wrong, as the developer can chose differenly. We should pick saint defaults = when node is removed, so is the comments above, and work with it. That way we can deliver rule on code without comments.

**Comment by samsonasik** [comment]
Ok 👍 re-open

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I found a bug on variable changed on different deep location with self referenced in assign expr, eg:

```php
        foreach ($data as $key => $val) {

            if (rand(0, 1)) {
                // a comment
                $val = str_replace('a', 'b', $val);
                $val = str_replace('b', 'c', $val);
            }

            if (rand(0, 1)) {
                if (rand(0, 1)) {
                    // a comment
                    $val = str_replace('a', 'b', $val);
                    $val = str_replace('b', 'c', $val);
                }
            }
        }
```

which should be skipped entirely, but it removing comment:

```diff
             if (rand(0, 1)) {
-                // a comment
```

which should not removed as the variable never removed. It seems due scoping detection bug.

**Comment by samsonasik** [comment]
Fixed :tada: with flip the checks to: 

- early check self referencing, ensure that variable not re-used in assign expr
- detect call expression has side effect
- check scoping variable

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks

**Pull request merged**
