### PR TITLE
[Printer] Extends PHPStan printer on PHPStan 1.10.20

### PR DESCRIPTION
**Pull request by samsonasik**
Ref error:

- https://github.com/rectorphp/rector-src/actions/runs/5327620855/jobs/9651256936#step:11:28
- https://github.com/rectorphp/rector-downgrade-php/actions/runs/5322159313/jobs/9655820170?pr=133#step:5:19

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
That would be the extending I want to avoid. What is the failing test fixture causing it?

**Comment by TomasVotruba** [comment]
Reproducer:

```bash
bin/rector p --config build/config/config-downgrade.php vendor/symfony/config/Definition/Loader/DefinitionFileLoader.php -n --debug
```

**Comment by samsonasik** [comment]
NodeVisitor seems can not read Virtual node on some area, that only read by PHPStan processNodes() method.

**Comment by samsonasik** [comment]
Resolved at https://github.com/rectorphp/rector-src/pull/4310

**Pull request closed without merging**
