### PR TITLE
The ReturnTypeFromReturnNewRector must only handle new instances, to avoid leaking to everything

### PR DESCRIPTION
**Pull request by TomasVotruba**
I'm checking the most complex rules by `LongAndDependentComplexRectorRule` and narrow down the most complex ones.
This rules was cheking `new` and everything else using get type of expr. We had this leaking before and it lead to single huge rule that was very hard to debug/extend. Instead now I want to focus on very narrow type resolvers with single job, so we're 100 % sure they work. Thus narrowing down back to `new` only, as in the rule name and expectations :+1:

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba The rule already cover only single type

https://github.com/rectorphp/rector-src/blob/8cab945ae45b651cdf66c8bfbb1603c514733896/rules/TypeDeclaration/Rector/ClassMethod/ReturnTypeFromReturnNewRector.php#L190-L192

If fallback from param removed, I think we need new rule for general return object, eg: `ReturnTypeFromStrictReturnObjectRector` so we still have the functionality, wdyt?

**Comment by TomasVotruba** [comment]
I'd avoid adding any further generic type-declartion rules for now for reasons above. It's also easier to review rule by rule, rather than one giant PR with all possible return types, that can often backfire.

**Comment by samsonasik** [comment]
How to get the functionality back?

**Comment by TomasVotruba** [comment]
I'd go for custom rule if needed, but in my experience it's doable to reach 80-90 % type coverage with other rules.
Intead of making such rules more omnipotent, there is much more potential in writing collector-based rules. E.g. passed arguments from other method calls. That's where we can brand new value.

**Comment by samsonasik** [comment]
The fallback from Param is just an example, the actual usage can be something like this:

```php
class SomeClass
  public function run()
  {
        if (rand(0,1)) {
             return new SomeClass();
       }
  
       return $this->init();
  }
  
  public function init(): SomeClass
  {
        return $this;
  }
}
```

both types are equals, so I think it should have return type. 

I think @staabm opinion is needed since it used on his project :).

If the feature removed, I think generic one is needed or can be optionally activated

**Comment by staabm** [comment]
IMO cases like the example @samsonasik pointed out exist in regular projects. 

Whether the return type inference is done by a separate rule or is part of an existing rule is up to you guys

**Comment by TomasVotruba** [comment]
Feel free to port to project it for now or create an unofficial extension to try it out in the community.

**Pull request merged**
