### PR TITLE
[TypeDeclaration] Skip Type modified between Assign and Return_ on ReturnTypeFromReturnNewRector

### PR DESCRIPTION
**Pull request by samsonasik**
The following code should be skipped:

```php
final class SkipTypeModifiedBetweenAssignAndReturn
{
    public function action()
    {
        $response = new SomeResponse();

        $this->verify($response);

        return $response;
    }

    private function verify(SomeResponse &$someResponse): void
    {
        if (is_cli()) {
            $someResponse = new CLIResponse();
        }
    }
}
```

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I updated to verify with type change on next Stmt on pass by reference use case.

**Comment by samsonasik** [comment]
I found another use case to be skipped:

```php
final class SkipTypeModifiedBetweenAssignAndReturnWithIf
{
    public function action()
    {
        $response = new SomeResponse();

        if (is_cli()) {
            $response = new CLIResponse();
        }

        return $response;
    }
}
```

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
