### PR TITLE
[Php81] Skip ReadOnlyPropertyRector on read only class

### PR DESCRIPTION
**Pull request by samsonasik**
Based on tweet https://twitter.com/_Codito_/status/1605889532553052161

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by Wirone** [comment]
Currently rule only checks if `readonly` should be added to promoted properties, but that PR to Laminas had different scenario: promoted properties already had `readonly`.

There should be also fixture for scenario where class' promoted properties have `readonly` and class doesn't have it: when `readonly` is added on class level, properties' `readonly`s should be removed.

**Comment by samsonasik** [comment]
That already covered at `ReadonlyClassRector`, see this transformation

https://github.com/rectorphp/rector-src/blob/7f8f9f818e7abf6e55a10648440d4079b4f5803f/rules-tests/Php82/Rector/Class_/ReadOnlyClassRector/Fixture/only_readonly_property2.php.inc#L5-L20

the multi rules back to add readonly again on `ReadonlyPropertyRector` because found a readonly property, which was doesn't check the class already readonly so flip flop was happen ,this PR fix it :)

**Comment by Wirone** [comment]
Aaahhh, ok, so it was removed and added again, hence no diff 😅 Thanks for clarification!

**Review by TomasVotruba — APPROVED** [review]

**Pull request merged**
