### PR TITLE
[PostRector] Using NodesToAddCollector in Rector rules

### PR DESCRIPTION
**Pull request by samsonasik**
Direct `addNode(s)AfterNode()` and `addNode(s)BeforeNode()` are deprecated, use `NodesToAddCollector` instead in rector rules.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you ☺️

It would be even better to not to use any abstraction, but return those nodes in refactor method

**Review by TomasVotruba — APPROVED** [review]

**Comment by samsonasik** [comment]
is return array of nodes working when there is process after add node? eg: remove node

**Comment by TomasVotruba** [comment]
> is return array of nodes working when there is process after add node? eg: remove node

Depends on the use case. Ideally the returned array of nodes should be the final set of nodes

**Pull request merged**
