### PR TITLE
[TypeDeclaration] Add fallback return direct array support on ReturnTypeFromStrictNewArrayRector

### LINKED ISSUE #8185: ReturnTypeFromStrictNewArrayRector: missing array return type - part 2
# Bug Report

similar to https://github.com/rectorphp/rector/issues/8183 I would expect rector to add a `array` return type in

https://getrector.com/demo/aed924b0-d4e6-4522-a0f2-d8a5034ca416

only difference is the added block

```
        if (count($offers) == 0) {
            return [];
        }
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8185

### CODE REVIEW

**Comment by samsonasik** [comment]
implemented 🎉 /cc @staabm

**Comment by staabm** [comment]
Nice. Does it also support nullable array?
https://getrector.com/demo/c74af6a5-bc6a-479d-8469-cb3a2e56dd5a

**Comment by samsonasik** [comment]
nullable array = union, that's covered at `ReturnUnionTypeRector`, see https://getrector.com/demo/8154c1f5-8db4-4a8e-949a-b38b31042c9c

**Comment by staabm** [comment]
Awesome, thanks

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Pull request merged**
