### PR TITLE
[DeadCode] Handle skipped RemoveUnreachableStatementRector on MultiDirnameRector

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba this PR handle skipped RemoveUnreachableStatementRector on MultiDirnameRector on PR https://github.com/rectorphp/rector-src/pull/2125 https://github.com/rectorphp/rector-src/pull/2125/files#diff-d933a2ad57daa43419b483d3f1ddedaec7aa44933007fead9f9437390f596f4a

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 by compare current node with original node.

**Comment by samsonasik** [comment]
this is strange as it works locally, probably cache, I will re-check.

**Comment by samsonasik** [comment]
I am not sure about it, closing for now.

**Comment by samsonasik** [comment]
Re-open, it seems it can be handled by check last stmts that not exit,return,throw to have method call.

**Comment by samsonasik** [comment]
@TomasVotruba it fixed 🎉  by the following checks:

- Ensure last start - 1 of the removed keys is not `Throw_`, `Return_`, or `Exit_` stmt, if they are, that's it is unreachable exactly.
- check if there is side effect in previous stmts with loop back, if exists, than return null, otherwise, mark as unreacable stmt.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
