### PR TITLE
[DeadCode][EarlyReturn] Handle RemoveUnusedVariableAssignRector + RemoveAlwaysElseRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
final class Fixture
{
    public function run(Request $request)
    {
        $path = $request->get('path', null);
        $url  = $request->get('url', null);

        if (null !== $path) {
            return response()->file($path);
        } elseif (null !== $url) {
            return response()->getFile($url);
        }

        throw new \Exception('Error');
    }
}
```

It produce:

```diff
-        $path = $request->get('path', null);
+        $request->get('path', null);
```

which should not.

Applied rules:

```php
Rector\DeadCode\Rector\Assign\RemoveUnusedVariableAssignRector;
Rector\EarlyReturn\Rector\If_\RemoveAlwaysElseRector;
```

Fixes https://github.com/rectorphp/rector/issues/6819

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
@TomasVotruba it fixed 🎉 , the `rector-doctrine` package tests error is unrelated.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
@TomasVotruba using `p5` on paratest seems cause error again after rebase:

https://github.com/rectorphp/rector-src/runs/4273392519?check_suite_focus=true#step:5:64

```bash
In WorkerCrashedException.php line 36:
                                                                               
  The command "'/home/runner/work/rector-src/rector-src/vendor/phpunit/phpuni  
  t/phpunit' '--configuration' '/home/runner/work/rector-src/rector-src/phpun  
  it.xml' '--no-logging' '--no-coverage' '--printer' 'ParaTest\Runners\PHPUni  
  t\Worker\NullPhpunitPrinter' '--log-junit' '/tmp/PT_ta1J0d' '/home/runner/w  
  ork/rector-src/rector-src/rules-tests/TypeDeclaration/Rector/Property/Typed  
  PropertyFromStrictGetterMethodReturnTypeRector/TypedPropertyFromStrictGette  
  rMethodReturnTypeRectorTest.php'" failed.                                    
                                                                               
  Exit Code: 137(Kill (terminate immediately))   
```

**Comment by samsonasik** [comment]
@TomasVotruba using `p3` on parallel tests seems solve it 🎉 

All checks have passed 🎉 it is ready for review.

**Comment by samsonasik** [comment]
I am merging it ;)

**Comment by cavo789** [comment]
Just incredible 👌

**Pull request merged**
