### PR TITLE
[automated] Re-Generate Nodes/Rectors Documentation

### PR DESCRIPTION
**Pull request by TomasVotruba**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba phpstan error seems because of moved config on symplify:

https://github.com/symplify/symplify/commit/2f3f3ec9c930c0a207db1f6d90142be50d49bdc2

we may can solve it by:

1. Try directly change to remove `services-rules` and `string-to-constant-rules` seems make it work:

```diff
-    - vendor/symplify/phpstan-rules/config/services-rules.neon
     - vendor/symplify/phpstan-rules/config/static-rules.neon
-    - vendor/symplify/phpstan-rules/config/string-to-constant-rules.neon
```

2. The 1st method however,cause `string-to-constant-rules` will no longer included services (as removed and moved to `symplify-rules.neon` in symplify repo), except we manually add the service to phpstan.neon

```diff
-    - vendor/symplify/phpstan-rules/config/services-rules.neon
     - vendor/symplify/phpstan-rules/config/static-rules.neon
-    - vendor/symplify/phpstan-rules/config/string-to-constant-rules.neon
 
+services:
+    -
+        class: Symplify\PHPStanRules\Rules\Enum\RequireConstantInMethodCallPositionRule
+        tags: [phpstan.rules.rule]
+        arguments:
+            requiredConstantInMethodCall:
+                Symfony\Component\Console\Command\Command:
+                    addArgument: [0]
+                    addOption: [0]
+                Symfony\Component\Console\Input\InputInterface:
+                    getOption: [0]
+                    getArgument: [0]
+                PhpParser\Node:
+                    getAttribute: [0]
+                    setAttribute: [0]
``` 

3. The other solution is just use the `packages/phpstan-rules/config/symplify-rules.neon` directly, but that will cause various errors:

```
composer phpstan
> vendor/bin/phpstan analyse --ansi --error-format symplify --memory-limit 2G
Note: Using configuration file /Users/samsonasik/www/rector-src/phpstan.neon.
 1560/1560 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  rules/CodeQuality/Rector/FuncCall/ArrayKeysAndInArrayToArrayKeyExistsRector.php:132
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - '#Do not name "n", shorter than 2 chars#'
 rules/CodingStyle/Rector/Encapsed/EncapsedStringsToSprintfRector.php:35
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - '#Modifier "%s" is not matching passed variable type "array<int, string>"\. The "string" type is expected \- see https\://dibiphp\.com/en/documentation\#toc\-modifiers\-for\-arrays#'
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  rules/DeadCode/Rector/ConstFetch/RemovePhpVersionIdCheckRector.php:258
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - '#Content of method "processGreaterLeft\(\)" is duplicated with method "processGreaterOrEqualLeft\(\)" in "Rector\\DeadCode\\Rector\\ConstFetch\\RemovePhpVersionIdCheckRector" class\. Use unique content or service instead#'
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  rules/DeadCode/Rector/ConstFetch/RemovePhpVersionIdCheckRector.php:277
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - '#Content of method "processGreaterRight\(\)" is duplicated with method "processGreaterOrEqualRight\(\)" in "Rector\\DeadCode\\Rector\\ConstFetch\\RemovePhpVersionIdCheckRector" class\. Use unique content or service instead#'

  src/Application/VersionResolver.php:58
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - '#Instead of "DateTime" class/interface use "Nette\\Utils\\DateTime"#'
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  src/Application/VersionResolver.php:67
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - '#Instead of "DateTime" class/interface use "Nette\\Utils\\DateTime"#'
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  src/Console/ConsoleApplication.php:158
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - '#New expression argument on position 0 must use constant over value#'

  src/FileSystem/FilesFinder.php:113
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  - '#Instead of "Symfony\\Component\\Finder\\SplFileInfo" class/interface use "Symplify\\SmartFileSystem\\SmartFileInfo"#'  
```

what do you prefer?

**Comment by samsonasik** [comment]
Let's use option 2 for now, require manual register service `RequireConstantInMethodCallPositionRule` but nothing left behind ;)

**Comment by TomasVotruba** [comment]
The removal of deprecated configs is correct :+1: 

As for including rule, it was just moved to `symplify-rules.neon`, so we should include that (I though we already do :))
https://github.com/symplify/symplify/commit/2f3f3ec9c930c0a207db1f6d90142be50d49bdc2#diff-12c41bb894ebccfa4715410e98d31138331a053e0f88a4334a128fbc365dae22

**Comment by samsonasik** [comment]
direct use `symplify-rules.neon` cause many errors as option 3 above showed, so I use option 2 for now.

**Comment by TomasVotruba** [comment]
I see. Option 3. is actually correct and these errors should be fixed or ignored in case of simple object usage.

E.g the `src/Console/ConsoleApplication.php:158` should be replaced by constant.

**Pull request merged**
