### PR TITLE
[Defluent][Rector-Symfony] Handle TypeError on AddFlashRector

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6755 when root method call var is MixedType as from : 

```php
$session = $this->get('session');
```

which need to be skipped.

### CODE REVIEW

**Comment by Bilge** [comment]
Wow @samsonasik, you're really on it today! Appreciate that.

I can confirm it does not error. It does not make a fix, either, but maybe that's expected?

**Comment by samsonasik** [comment]
That's expected, as it needs to validate the Request object, while the code example is from `$this->get('session')` which the type is Mixed without `@var`, also, the rule is to change the call by `request->getSession()->getFlashBag()` which the code exampls is out of scope.

**Comment by samsonasik** [comment]
Thank you for verify, I am merging it  ;)

**Pull request merged**
