### PR TITLE
[Core] Replace deprecated $mutatingScope->enterCatch() with enterCatchType() in PHPStanNodeScopeResolver

### PR DESCRIPTION
**Pull request by samsonasik**
The `$mutatingScope->enterCatch($catch->types, $varName)` is deprecated, ref 

https://github.com/phpstan/phpstan-src/blob/e4a1b670be31d0ac48a1c6d857025727cc86421c/src/Analyser/MutatingScope.php#L3136-L3139

Updated to use `enterCatchType()` instead.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
rebased.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
