### PR TITLE
Remove CachedContainerBuilder

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba @staabm the Rector Kernel cache manual increase kernel cache key really slowing down the development, as we already have phpunit splitted into separate process, I think this can be removed.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by staabm** [comment]
I am fine with it

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Comment by TomasVotruba** [comment]
Perfect, I've had some issue with constant key renames as well. Thanks for handling this together :+1:

**Pull request merged**
