### PR TITLE
[Php72][TypeDeclaration] Fix infinite loop on ParseStrWithResultArgumentRector+DeclareStrictTypesRector

### LINKED ISSUE #8531: `DeclareStrictTypesRector::class`-rule with the `php83`-set can cause endless loop
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 1.0.2             |

Applying the `DeclareStrictTypesRector`-rule with the `php83`-set on a class without a namespace, will result into an endless loop adding multiple `declare(strict_types=1);`-statements to the file. The issue does not occur when the class has a namespace or without the `php83`-set.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/d48ae5c2-c537-445c-9555-4a76bbaf12c2

https://github.com/kapersoft/rector-endless-loop/

## Expected Behaviour

Single `declare(strict_types=1)`-statement added to the class.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8531

### CODE REVIEW

**Comment by samsonasik** [comment]
@kapersoft this should fix https://github.com/rectorphp/rector/issues/8531

**Comment by samsonasik** [comment]
@kenjis this probably should fix infinite loop on CodeIgniter4 project as well when running `DeclareStrictTypesRector`

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by kapersoft** [comment]
@samsonasik I have checked your fix with my codebase and the endless loops are gone 😄 

Thanks for quick response!  👍

**Comment by samsonasik** [comment]
@kapersoft you're welcome, I am actually not sure why `current()` don't work, while `$nodes[0]` fix it, and only reproducible via `vendor/bin/rector`, while it only run once on unit test, so kind of phpunit flow probably.

it may require `e2e` in the future.

**Comment by samsonasik** [comment]
The issue seems happen only on scoped code (php 7.2 compat), as can't be produced in rector-src on php 8.2, so array seems somewhere goes to `end()` of loop when downgraded, if the `current()` still needed, the `reset()` is needed first to ensure it start from the beginnning:

```diff
        // use 0 index to avoid infinite loop
-        $rootStmt = $newStmts[0] ?? null;
+        reset($newStmts);
+        $rootStmt = current($newStmts);        
        $stmt = $rootStmt;
        if ($rootStmt instanceof FileWithoutNamespace) {
            // use 0 index to avoid infinite loop
-            $currentStmt = $rootStmt->stmts[0] ?? null;
+            reset($rootStmt->stmts);
+            $currentStmt = current($rootStmt->stmts);
```

**Comment by samsonasik** [comment]
current solution with index 0 seems ok as is :)

**Comment by samsonasik** [comment]
I see, the issue is on `ParseStrWithResultArgumentRector`, which 

```php
$totalKeys = array_key_last($stmtsAware->stmts);
```

downgraded to 

```php
        \end($stmtsAware->stmts);
        $totalKeys = \key($stmtsAware->stmts);
```

which make it always goes to last stmts, then it never `resetted`, I think the proper solution is refactor `DowngradeArrayKeyFirstLastRector` to make call `reset($stmtsAware->stmts` after get the key:

```diff
        \end($stmtsAware->stmts);
        $totalKeys = \key($stmtsAware->stmts);
+        reset($stmtsAware->stmts);
```

**Comment by samsonasik** [comment]
I created PR 

- https://github.com/rectorphp/rector-downgrade-php/pull/214

for it.

**Pull request merged**
