### PR TITLE
[Core] Remove deprecated AbstractScopeAwareRector

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
This might cause few surprises, as class would be gone compleetely between 1.2.x an 2.x. 
Instead the `refactorWithScope()` should throw an exception and inform about way to upgrade. Could you update it so there is an information helpful message?

**Comment by samsonasik** [comment]
The upgrading note it as "removed" https://github.com/rectorphp/rector-src/blob/main/UPGRADING.md#1-abstractscopeawarerector-is-removed-use-abstractrector-instead

I am fine with as "deprecated" per now, but the upgrading note need to be updated as "deprecated"

**Comment by TomasVotruba** [comment]
It's "removed" in the upgrade guide, but we want to have a note for those who don't read upgrade notes. Me included :)

Seeing "class XYZ is missing" might not be helpful as "this is not supported anymore, see upgrade guide to fix it".

**Comment by samsonasik** [comment]
sure, I created new PR for that:

- https://github.com/rectorphp/rector-src/pull/6541

**Pull request closed without merging**
