### PR TITLE
[TypeDeclaration] Fix ReturnTypeAlreadyAddedChecker on return key of array

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba it fixes `ReturnTypeAlreadyAddedChecker` for return `int` detection for array key .

### CODE REVIEW

**Comment by samsonasik** [comment]
If return type removed, it seems still re-add `int|string`:

```diff
-    private function getArgumentPosition(FuncCall $funcCall, Arg $desiredArg)
+    private function getArgumentPosition(FuncCall $funcCall, Arg $desiredArg): int|string
```

**Comment by samsonasik** [comment]
I added failing fixture for no return type yet https://github.com/rectorphp/rector-src/pull/1571/commits/b3f671d1c8a588599ee35442cc4455e6659b56d9

**Comment by samsonasik** [comment]
Fixed 🎉 with BenevolentUnionType check

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Wow, big improvement! Thank you :clap: :+1: :tada:

**Pull request merged**
