### PR TITLE
Add failing test fixture for SwitchTrueToIfRector

### PR DESCRIPTION
**Pull request by pgr-dS**
# Failing Test for SwitchTrueToIfRector

Based on https://getrector.com/demo/4ea2ecee-99f7-474e-b74e-a2db47a1e1eb

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Test is passing. Is that intended? 

If code should change, it must look differently.

See point 5 here: https://getrector.com/documentation/reporting-issue-with-rector

**Comment by pgr-dS** [comment]
@TomasVotruba, no, that was not intended

the "Create Test" button on the getrector.com/demo page didn't include the `Fixture` folder in the path

I force-pushed with the fixture in the correct location (and gave it a more descriptive name), now the test fails as expected

**Comment by samsonasik** [comment]
That is strange, with prefix Fixture, it was create double `Fixture/Fixture` directory, probably github change back to original behaviour, see original fixture link factory generation patch:
https://github.com/rectorphp/getrector-com/pull/1205

**Comment by samsonasik** [comment]
@pgr-dS I cherry-picked your commit at PR https://github.com/rectorphp/rector-src/pull/3634

**Pull request closed without merging**
