### PR TITLE
Create preserve_quotes.php.inc for AnnotationToAttributeRector

### PR DESCRIPTION
**Pull request by yguedidi**
failing test for AnnotationToAttributeRector
see #7890

### CODE REVIEW

**Comment by TomasVotruba** [comment]
This discovered a different issue in Rector website :) 

The `namespace` is under the `use`, so the fixture crashes.

It should be fixed in the issue link code with a test here: https://github.com/rectorphp/getrector-com/blob/main/tests/GitHubMagicLink/LinkFactory/FixtureLinkFactory/FixtureLinkFactoryTest.php

**Comment by samsonasik** [comment]
@TomasVotruba This one is create correct path to Fixture directory, so this probably just miss type in url, not really an issue on create fixture under Fixture directory

**Comment by TomasVotruba** [comment]
@samsonasik  The path might be correct, but the contents are invalid:

```php
use Symfony\Component\Validator\Constraints as Assert;

namespace Rector\Tests\Php80\Rector\Class_\AnnotationToAttributeRector\Fixture;

final class MyEntity
```

Do you think it's manually copy-pasted wrong?


<br>

@yguedidi In that case we'll need a valid PHP syntax from you :)

**Comment by samsonasik** [comment]
@TomasVotruba that's seems old issue for content generation class has use statement, it moved to early stmt, probably issue on Fixture factory

**Comment by yguedidi** [comment]
@TomasVotruba to be honest I don't remember 😅 just fixed quickly with codespace :)

**Comment by samsonasik** [comment]
@yguedidi could you try provide a patch as well? Thank you.

**Comment by yguedidi** [comment]
@samsonasik on it

**Comment by TomasVotruba** [comment]
Surpassed by fix PR https://github.com/rectorphp/rector-src/pull/3645

**Pull request closed without merging**
