### PR TITLE
[Docs] Copy docs to rector-prefixed-downgraded/ as well

### PR DESCRIPTION
**Pull request by samsonasik**
ref https://github.com/rectorphp/rector-src/pull/33#issuecomment-841436746 to ensure new docs always added.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
This should be only in one place as this repository is only for development. Moved there here in repository, not on release.

**Comment by samsonasik** [comment]
Do you mean rector/rector's docs need to be removed or keep docs in this repo?

**Comment by TomasVotruba** [comment]
The `/docs` in this repository must be moved to `/build/target-repository/docs`

```diff
-/docs
+/build/target-repository/docs
```

The https://github.com/rectorphp/rector/pull/6417 is read-only, so all the work must happen here.
Basically what you put in `/build/target-repository` will apper in root of http://github.com/rectorphp/rector

**Comment by samsonasik** [comment]
Ok, implemented https://github.com/rectorphp/rector-src/pull/34/commits/eb79ed9198efdd97bd259dc585c06fe09d676e20

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Yes :+1:  Thank you

**Pull request merged**
