### PR TITLE
Add support for interface in AnnotationToAttributeRector rule

### LINKED ISSUE #7497: Incorrect behavior of AnnotationToAttributeRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/4aed0527-1eb1-420d-8af3-81de2423063a

```php
<?php
use Symfony\Component\Serializer\Annotation as Serializer;

/**
 * @Serializer\DiscriminatorMap(typeProperty = "type", mapping = {
 *     "FOO" : TestFoo::class,
 *     "BAR" : TestBar::class
 * })
 */
interface TInterface
{
}

/**
 * @Serializer\DiscriminatorMap(typeProperty = "type", mapping = {
 *     "FOO" : TestFoo::class,
 *     "BAR" : TestBar::class
 * })
 */
class TestFoo implements TInterface {
}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

Interfaces should also be supported by AnnotationToAttributeRector

### PR DESCRIPTION
**Pull request by astronom**
Fixes https://github.com/rectorphp/rector/issues/7497

### CODE REVIEW

**Comment by astronom** [comment]
@samsonasik ready for review

**Review by samsonasik — CHANGES_REQUESTED** [review]
`@param` in `refactor()` method needs addition `Interface_` in the docblock

**Comment by astronom** [comment]
> `@param` in `refactor()` method needs addition `Interface_` in the docblock

added

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
