### PR TITLE
[AutoImport] Allow auto import just renamed @var only docblock on RenameClassRector without removeUnusedImports() enabled

### PR DESCRIPTION
**Pull request by samsonasik**
When `importNames()` enabled, but `removeUnusedImports()` not enabled, the only renamed `@var` should be allowed t be imported.

### CODE REVIEW

**Comment by samsonasik** [comment]
Run Rector twice apply the change:

First: https://getrector.com/demo/bab1d1af-8d60-4203-8b0b-997ff7446690 (only rename docblock)
twice: https://getrector.com/demo/671bc700-bb1c-4e15-9f00-55e8b733d8c1 (apply auto import)

so it not priority right now.

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
Added another fixture for `@var` short class https://github.com/rectorphp/rector-src/pull/5220/commits/ca0571e3596a6daf8df5790cb069d09ce214f42c

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it to have faster feedback to test ;)

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
