### PR TITLE
Fixes descending order on IfToSpaceship

### LINKED ISSUE #7118: IfToSpaceshipRector sorts ASC instead of DESC
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.21             |
| PHP Version | PHP 7.4.27 (cli) (built: Dec 16 2021 18:14:46) ( NTS ) |

The original code sorts an array descending by count() of members. After running rector (see demo), the new code sorts the array in ascending order.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/d641f20a-4f8c-4824-be19-9e51bd4885d0

## Expected Behaviour

```php
usort($arr, function($a, $b) {
    if (count($a) === count($b)) {
        return 0;
    }

    return count($a) > count($b) ? -1 : 1;
});
```

turns into

```php
usort($arr, fn($a, $b) => count($a) <=> count($b));
```

but it should be

```php
usort($arr, fn($a, $b) => count($b) <=> count($a));
```

### PR DESCRIPTION
**Pull request by peterlupu**
Should fix [#7118](https://github.com/rectorphp/rector/issues/7118).

Please code review this, as I _think_ I found errors in the existing unit tests. 

Also, I had to jump through some hoops in order to please phpstan's cognitive complexity calculator.

### CODE REVIEW

**Comment by samsonasik** [comment]
could you rebase and amend commit with remove 'quote' in commit message? - it may make build stopped when merged

**Comment by peterlupu** [comment]
> could you rebase and amend commit with remove 'quote' in commit message? - it may make build stopped when merged

hi

sorry if this is offtopic but can't seem to be able to do this. a little help, please?

```sh
$ git checkout b3dda553a1f21c9b14c15b79a90b0fbb503eb3f1
$ git commit -m 'merge branch' --amend
$ git checkout -
$ git rebase ced947f001
$ git push
```

**Comment by samsonasik** [comment]
You should can do: 

```
#ensure base branch is PR branch
git checkout test/IfToSpaceshipRector-asc-desc 

# create a branch for backup
git checkout -b temp 

# back to branch PR
git checkout test/IfToSpaceshipRector-asc-desc 

git reset --hard HEAD~10 

git remote add upstream https://github.com/rectorphp/rector-src 

git pull upstream main
git cherry-pick 59bde137c23dbba32eaeb7df8d94e570aeff6996 

git push --force origin test/IfToSpaceshipRector-asc-desc
```

**Comment by peterlupu** [comment]
> You should can do:
> 
> ```
> #ensure base branch is PR branch
> git checkout test/IfToSpaceshipRector-asc-desc 
> 
> # create a branch for backup
> git checkout -b temp 
> 
> # back to branch PR
> git checkout test/IfToSpaceshipRector-asc-desc 
> 
> git reset --hard HEAD~10 
> 
> git remote add upstream https://github.com/rectorphp/rector-src 
> 
> git pull upstream main
> git cherry-pick 59bde137c23dbba32eaeb7df8d94e570aeff6996 
> 
> git push --force origin test/IfToSpaceshipRector-asc-desc
> ```

I think I managed to remove the quotes, thanks to you. 🎉

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @peterlupu

**Pull request merged**
