### PR TITLE
Add failing test fixture for TypedPropertyRector

### PR DESCRIPTION
**Pull request by rodion-k**
Related to https://github.com/rectorphp/rector/issues/6511

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the PR!

I'm looking at the code and it looks like impossible to use.
How does the value get to a private property? 

How do you make sure the property is not accessed before the property fetch? That would cause uninitialized exception. Rector should not create invalid code.

**Comment by rodion-k** [comment]
Fixtures were based on https://github.com/rectorphp/rector-src/blob/a8436c746ca107fc26176b6b29a5ff304ed31e5b/rules-tests/Php74/Rector/Property/TypedPropertyRector/FixtureDoctrine/doctrine_id.php.inc

In this case property is also private but it works.

**Comment by TomasVotruba** [comment]
That probably should not work either. 

Still, how would a value get there?

**Comment by TomasVotruba** [comment]
The added fixture is not valid as private property cannot be assigned value.
Closing for lack of feedback.

**Pull request closed without merging**
