### PR TITLE
[DeadCode] Skip used by get_object_vars() when implements JsonSerializable on RemoveUnusedPromotedPropertyRector

### LINKED ISSUE #8904: Private property gets removed despite being used by `get_object_vars`
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.2.10 |

Rector removes seemingly unused properties, but which are used by `get_object_vars`.

## Minimal PHP Code Causing Issue

```php
class Foo implements \JsonSerializable {
  public function __construct(private readonly string $foo) {
  }

  public function jsonSerialize(): array {
    return get_object_vars($this);
  }
}
```

## Expected Behaviour

Rector should not remove property `$foo` here.

-----

I would think that whenever there is a `get_object_vars($this)` in a class, rector should not remove any non-static properties or see them as used.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8904

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @uncaught

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by uncaught** [comment]
Oh, thanks for the quick PR!

However, the JsonSerializable implementation was only an example. We also use `get_object_vars` in other situations 🫣😄

**Comment by samsonasik** [comment]
well, check `JsonSerializable` is to ensure it only make sense to not remove it, too avoid too general check, per use case you reported :)

Feel free to provide test (and patch) if the issue persist, to not verify is object type of JsonSerializable

**Pull request merged**
