### PR TITLE
Prevent UnionTypes rule from removing literal value scalar types

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by simPod** [comment]
I'm not familiar with phpstan api, wonder whether I got it right.

**Comment by TomasVotruba** [comment]
The PHPStan CI error says the method is too complex. The extract method is needed to make it more readable.

**Comment by samsonasik** [comment]
Close-Reopen to restart CI

**Comment by simPod** [comment]
@TomasVotruba so the method is extracted but it still complains

**Comment by samsonasik** [comment]
You may need to reduce code complexity on `arePhpParserAndPhpStanPhpDocTypesEqual()` method, other code inside it with deep if can be moved to new method.

**Comment by simPod** [comment]
@samsonasik the method contains single simple condition, not sure how to reduce it further 🤔

**Comment by samsonasik** [comment]
You can create new method to be called for this code:

https://github.com/rectorphp/rector-src/blob/fda8d1af45875248ab46a5a97ad7d207823aaeba/packages/NodeTypeResolver/TypeComparator/TypeComparator.php#L106-L117

**Comment by simPod** [comment]
Hm, I removed that one in another PR 🤔 done

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
