### PR TITLE
[TypeDeclaration] Handle nullable intersection on TypedPropertyFromAssignsRector

### LINKED ISSUE #7692: TypedPropertyFromAssignsRector - intersection types PHP 7.4.30
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.1          |
| PHP version | 7.4.30         |
| Applied rules |  RenameClassRector, TypedPropertyFromAssignsRector|

```
<?php

declare(strict_types=1);

namespace Tests;

use DateTime;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class ExampleTest extends TestCase
{
    /**
     * @var DateTime&MockObject
     */
    private $property;

    public function testExample(): void
    {
        $this->property = $this->createMock(DateTime::class);
        $this->property->expects(self::once())->method('format');
        $this->property->format('Y');
    }
}

```

## Current modification
```
-    /**
-     * @var DateTime&MockObject
-     */
-    private $property;
+    private ?MockObject $property = null;
```

## Expected Behaviour

Rector should not change this file with this rules

### PR DESCRIPTION
**Pull request by samsonasik**
Closes https://github.com/rectorphp/rector-src/pull/3244
Fixes https://github.com/rectorphp/rector/issues/7692

- ~Use nullable MockObject on php 7.4~ Skip Intersection MockObject even nullable on php 7.4
- Use Union nullable with `MockObject&TargetType` => `(MockObject&TargetType)|null` on php 8.1
- Use Exact Intersection type `MockObject&TargetType` on property assigned in `setUp()` method on php 8.1

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
@VincentLanglet @puniserv after some thinking, I think it is indeed correct, that on php 7.4, the Mock object intersection can just be skipped, even nullable, then in php 8.1, real intersection type can be applied with include nullable if applicable 👍 

I applied the change so it skipped on php 7.4, and applied intersection on php 8.1, so the type will be applied when the language is actually ready.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thanks :clap:

**Pull request merged**
