### PR TITLE
[Php81] Skip ReadonlyProperty for class that consume Trait with Property

### LINKED ISSUE #7744: Skip ReadOnlyClassRector on has trait with non-readonly attributes
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/000f4580-7a5c-46d8-9f84-93f0169bd4bb

```php
<?php


trait A
{
    public string $value = 'D';
}

final class C
{
}

final class B
{
    use A;

    public function __construct(private C $c)
    {
    }

    public function __invoke()
    {
        return $this->c;
    }
}

$b = new B(new C());
```

### Responsible rules

* `ReadOnlyPropertyRector`

* `ReadOnlyClassRector`

## Expected Behavior

Rector should skip `ReadOnlyClassRector`  to avoid this error 
```
Readonly class B cannot use trait with a non-readonly property A::$value
```

Thanks !

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7744

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @Yoann-TYT

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by samsonasik** [comment]
@TomasVotruba the use case seems actually on ReadOnlyClassRector, as that mark class readonly, I will create new PR to move the check.

**Comment by samsonasik** [comment]
@TomasVotruba I created PR https://github.com/rectorphp/rector-src/pull/3316 for it.

**Pull request merged**
