### PR TITLE
Add failing test case for attribute downgrade

### PR DESCRIPTION
**Pull request by RikudouSage**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, thanks for real test fixture.

I wonder what should be behavior for such code. What is expected downgraded version?

```php
class WithAttributes
{
    public function __construct(
        #[\Deprecated] private int $property = 0
    ) {
    }
}
```

**Comment by RikudouSage** [comment]
I think the same as in my test, I can't find a use case for having a property not be available in pre php 8. And with these rules you want to get the same functionality as in php 8 for older versions.

**Comment by TomasVotruba** [comment]
The comment is extra clutter in PHP 7, so it should be removed.

If we keep it, the code after # will be invisible and broken, like here on Github

**Comment by RikudouSage** [comment]
But then you're also removing the features, for example PhpStorm understands attributes even if you're on a non-supported php version, it's very useful for example with `#[ExpectedValues]` attribute.

**Comment by TomasVotruba** [comment]
I see. So the idea is to keep PHPStorm features and separate PHP-runtime features?

**Comment by RikudouSage** [comment]
Pretty much. I mean, it's not necessary but it's nice to have especially with the `#[ExpectedValues]` and the like because the IDE will then provide hints to users of your class.

**Comment by samsonasik** [comment]
@RikudouSage I cherry-picked your commit at PR https://github.com/rectorphp/rector-src/pull/410

**Pull request closed without merging**
