### PR TITLE
[Testing] Use own FixtureFileFinder to keep dependency low

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Result in the Rector bulid: https://github.com/rectorphp/rector/commit/3a10283d3a1ec1ec362745667be60d8178dc4b40

image

:partying_face:

**Comment by samsonasik** [comment]
@TomasVotruba It seems cause error in other PR tests (rebased main) after it merged:

```bash

There were 8 errors:

1) Error
The data provider specified for Rector\Tests\Naming\Naming\UseImportsResolver\UseImportsResolverTest::testUsesFromProperty is invalid.
Error: Class "Symplify\EasyTesting\DataProvider\StaticFixtureFinder" not found
/home/runner/work/rector-src/rector-src/rules-tests/Naming/Naming/UseImportsResolver/UseImportsResolverTest.php:64
```

ref https://github.com/rectorphp/rector-src/runs/8107310730?check_suite_focus=true#step:5:76

**Comment by samsonasik** [comment]
@TomasVotruba the following changes seems needed in all tests sources?

```diff
+use Rector\Testing\Fixture\FixtureFileFinder;
use Rector\Testing\PHPUnit\AbstractTestCase;
-use Symplify\EasyTesting\DataProvider\StaticFixtureFinder;

    protected function yieldFilesFromDirectory(string $directory, string $suffix = '*.php'): Iterator
    {
-        return StaticFixtureFinder::yieldDirectory($directory, $suffix);
+        return FixtureFileFinder::yieldDirectory($directory, $suffix);
    }
}
```

**Comment by samsonasik** [comment]
@TomasVotruba another use case is, the `StaticFixtureUpdater` seems no class exists which from `Symplify\EasyTesting\DataProvider\StaticFixtureUpdater`:

https://github.com/rectorphp/rector-src/blob/86ccf3f6854c78c6b7b06b8471d922724cb6542b/packages/Testing/PHPUnit/AbstractRectorTestCase.php#L183

it cause error:

```bash
There were 2 errors:

1) Rector\Core\Tests\Issues\IssueReturnBeforeElseIf\IssueReturnBeforeElseIfAndTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Error: Class "Symplify\EasyTesting\DataProvider\StaticFixtureUpdater" not found
```

**Comment by samsonasik** [comment]
I create PR https://github.com/rectorphp/rector-src/pull/2864 to solve class not found from easy-testing error.

**Pull request merged**
