### PR TITLE
Add failing test fixture for ReturnTypeFromStrictTypedCallRector

### PR DESCRIPTION
**Pull request by canvural**
# Failing Test for ReturnTypeFromStrictTypedCallRector

Based on https://getrector.org/demo/1ec210d0-8d54-6ed0-9e71-813569ff2a89 and https://github.com/rectorphp/rector/issues/6711

### CODE REVIEW

**Comment by samsonasik** [comment]
Test seems green, could you remove the namespace like in the demo so the fixture equivalent?

**Comment by samsonasik** [comment]
It seems still green, could you try latest "rector/rector": "dev-main" ?

**Comment by canvural** [comment]
> It seems still green, could you try latest "rector/rector": "dev-main" ?

Doesn't demo page uses latest commit from main already?

**Comment by samsonasik** [comment]
No, demo page use latest tagged version

**Comment by canvural** [comment]
The [run](https://github.com/rectorphp/rector-src/runs/3743545656) looks ok.

In my project locally I did `composer require --dev rector/rector:dev-main` and it still refactors to `?false` instead of `?bool` 🤷🏽‍♂️

**Comment by canvural** [comment]
Anyway, this looks like it's working already. So I'll just ignore it locally for now and wait for the next release.

**Pull request closed without merging**
