### PR TITLE
[CodeQuality] Skip if else return on ExplicitReturnNullRector

### PR DESCRIPTION
**Pull request by samsonasik**
ref https://getrector.com/demo/5aece176-e316-4f8d-8d9c-69124edf6b6a

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
Try catch seems can always return inside If https://getrector.com/demo/25fe6ca5-f447-4ada-83c7-6a9c8d4bf692

We may need to use existing `SilentVoidResolver` for it.

**Comment by samsonasik** [comment]
I added another fixture in if else with try catch fixture https://github.com/rectorphp/rector-src/pull/5755/commits/67e848e68b3814bbe2cad93ba294e94e73c55950

**Comment by samsonasik** [comment]
The logic for it should like in `SilentVoidResolver`

https://github.com/rectorphp/rector-src/blob/b4eb883e9110f50607ce2eed629c237b5e7e7356/rules/TypeDeclaration/TypeInferer/SilentVoidResolver.php#L66-L78

the solution is either make that detection there, with if else check addition, and utilize `ReturnTypeInferer` to verify final type has `Void` type or check here more.

I will look more...

**Comment by samsonasik** [comment]
implemented 🎉 , I moved the functionality to `SilentVoidResolver::hasSilentVoid()` so it centralized for future improvement 👍

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by TomasVotruba** [comment]
Thank you :partying_face:

**Pull request merged**
