### PR TITLE
[DX] Add StmtsAwareInterface to catch node by type

### PR DESCRIPTION
**Pull request by TomasVotruba**
@todo consider proposing directly to php-parser to ease the node traversing

@todo move to to allow in Rector extensions https://github.com/rectorphp/vendor-patches

### CODE REVIEW

**Review by staabm — COMMENTED** [review]
Looks great.

Might it lead to incompatibilities with phpstan, which is not aware of such a patched PHPParser?

**Comment by TomasVotruba** [comment]
I thought of that and it's just a marker interface, with no logic nor methods, so should be ok. The `stmts` property always exists on those nodes. CI is passing as well.

**Comment by staabm** [comment]
Turned differently: Might it lead to problems when running rector in tandem with something bundling PHPParser (e.g. phpstan) and autoloading will not load the patched PHPParser classes shipped with rector, but different ones..?

Do we need to make sure, rector is working with the patched PHPParser version?

**Comment by TomasVotruba** [comment]
The rule would have to specifically require it. I'll update the patch paths and we can test it out :+1:

**Comment by TomasVotruba** [comment]
Ref https://github.com/rectorphp/vendor-patches/commit/08934a5cff96747b302610fdb87a3d30c8acd636

**Pull request merged**
