### PR TITLE
[DeadCode] Skip isset() from property fetch from docblock on RemoveAlwaysTrueIfConditionRector

### PR DESCRIPTION
**Pull request by samsonasik**
The following code should be skipped as rely to docblock

```php
class SkipPropertyFetchDoc
{
    /**
     * @var string
     */
    public $bodyFormat = '';

    public function run()
    {
        if (isset($this->bodyFormat) && $this->bodyFormat !== '') {
        }
    }

    public function reset()
    {
        $this->bodyFormat = null;
    }
}
```

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba using `Isset_` instance and `ArrayDimFetch` check seems the solution.

**Comment by samsonasik** [comment]
The left side can be also `empty()` check, so it seems need specific `Variable` node only check.

**Comment by samsonasik** [comment]
I tried the `BooleanAnd` new feature, and it seems cause many changes, that incorrect.

**Comment by samsonasik** [comment]
I think `BooleanAnd` should only check 2 things on the left:

- instanceof from typed param
- is_* from typed param

like https://github.com/rectorphp/rector-src/pull/5748, so correct native type will always guaranted.

I will look into it, also apply on `ReduceAlwaysFalseIfOrRector`

**Comment by samsonasik** [comment]
I added `SafeLeftTypeBooleanAndOrAnalyzer` so it can be improved over time in single location.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it to have faster feedback to test ;)

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
