### PR TITLE
DowngradeTrailingCommasInFunctionCallsRector - also applies to New_

### PR DESCRIPTION
**Pull request by ondrejmirtes**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
These failures are already on main branch I believe.

**Comment by TomasVotruba** [comment]
> These failures are already on main branch I believe.

Yes, I'm working on Doctrine annotation to attribute unwrapping, so the don't mind the doctrine package.
Main is fine now, could you rebase?

**Comment by ondrejmirtes** [comment]
Rebased

**Comment by TomasVotruba** [comment]
Awesome, thank you :+1:

**Pull request merged**
