### PR TITLE
[DeadCode] Handle RemoveDeadIfForeachForRector on if has no stmts with else 

### PR DESCRIPTION
**Pull request by samsonasik**
Closes https://github.com/rectorphp/rector/issues/6462

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased, phpunit error seems related with https://github.com/rectorphp/rector-doctrine/pull/9

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
