### PR TITLE
Simplify GenericClassStringTypeCorrector

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by staabm** [comment]
@samsonasik should be good to go

**Comment by samsonasik** [comment]
I can't merge unless all green, probably some test need to be tweak to make green

**Review by samsonasik — CHANGES_REQUESTED** [review]
It seems cause test error, see https://github.com/rectorphp/rector-src/actions/runs/4755759381/jobs/8450360876?pr=3638#step:5:77

**Comment by staabm** [comment]
it seems this class has some really suprising properties.

the `GenericClassStringTypeCorrector` does some "interessting" case-insensitive checks via `$classReflection->getName() !== $value` and this is required for a few rector classes to lead to a proper result. 

I wonder whether these "type-corrections" which atm happen at the very core of rector within `NodeTypeResolver` and therefore are involved with any type beeing resolved, is the right place to do this magic for just a few rectors:

```
1) Rector\Tests\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector\CompleteDynamicPropertiesRectorTest::test with data set #7
Failed on fixture file "class_string_case_insensitive.php.inc"
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 class ClassStringCaseInsensitive
 {
     /**
-     * @var string
+     * @var class-string<\classStringCaseInSensitive>
      */
     public $value;
     public function set()

/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:170
/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:128
/home/runner/work/rector-src/rector-src/rules-tests/CodeQuality/Rector/Class_/CompleteDynamicPropertiesRector/CompleteDynamicPropertiesRectorTest.php:16

2) Rector\Tests\Privatization\Rector\Class_\ChangeReadOnlyVariableWithDefaultValueToConstantRector\ChangeReadOnlyVariableWithDefaultValueToConstantRectorTest::test with data set #29
Failed on fixture file "class_constant_inside_array.php.inc"
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 class ConstantInsideArray
 {
     /**
-     * @var string[]
+     * @var array<class-string<\PHPUnit\Framework\TestCase\Notice>>
      */
     private const REPLACEMENTS = [
         \PHPUnit\Framework\TestCase\Notice::class

/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:170
/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:128
/home/runner/work/rector-src/rector-src/rules-tests/Privatization/Rector/Class_/ChangeReadOnlyVariableWithDefaultValueToConstantRector/ChangeReadOnlyVariableWithDefaultValueToConstantRectorTest.php:16
```

**Comment by samsonasik** [comment]
`ClassStringCaseInsensitive` is class name,
`classStringCaseInSensitive` is just string, so that expected to have `string` type

**Pull request closed without merging**
