### PR TITLE
Add failing test fixture for RemoveDeadStmtRector

### PR DESCRIPTION
**Pull request by kkmuffme**
# Failing Test for RemoveDeadStmtRector

Based on https://getrector.org/demo/a0eea85b-e17c-4bd5-851f-ba654335e096

Not sure if no change at all in this case or it should be removed. Ideally it would give an error, but that's not an option with rector. So I guess completely removing it maybe without leaving broken code?

### CODE REVIEW

**Comment by samsonasik** [comment]
It seems needs to be fixed in php-parser for format preserving, see https://github.com/nikic/PHP-Parser/pull/884

**Comment by TomasVotruba** [comment]
As @samsonasik says.
There is a test fixture PR in php-parser for this one: https://github.com/nikic/PHP-Parser/pull/884

**Comment by kkmuffme** [comment]
@samsonasik @TomasVotruba it seems fixed in PHP-Parser per the linked PR, but the issue is still there in rector

**Comment by samsonasik** [comment]
@kkmuffme that's on php-parser master branch, which may only land on next major version 5.0 of php-parser.

We currently use php-parser 4.x, that will wait for phpstan compatibility for next major version of php-parser bc break.

**Comment by TomasVotruba** [comment]
@kkmuffme In another words, PHPStan and Rector has to adapt the php-parser 5 stable first, before this fix can be propagated here. I'd expect that happen somewhere around Q2/Q3 2023.

Personally, I'd convert any PHP + HTML mix to either templating system or pure PHP. That's where the tooling we have can help today :)

**Pull request closed without merging**
