### PR TITLE
[TypeDeclaration] Add new return type rule which handles literal scalars

### PR DESCRIPTION
**Pull request by RobertMe**
Add a new return type rule which only adds return types for literal scalar returns. All return points must match this type, as no unions will be created. Operations on two literals, like string concat, or calculations with integers / floats are also ignored. The only special cases that are handling are true/false/null. This as these aren't actual scalar values but constants.

This follows on discussion: https://github.com/rectorphp/rector/discussions/8362. Not sure if you do want it, as it's functionality will be a 100% subset of `ReturnTypeFromStrictScalarReturnExprRector`, so enabling the latter will do the same, and more, compared to this rule. That's also why I opted not to add it to the `TYPE_DECLARATION` set, as `ReturnTypeFromStrictScalarReturnExprRector` already is in there and it would just "waste" resources on running both.

### CODE REVIEW

**Comment by RobertMe** [comment]
> That's also why I opted not to add it to the TYPE_DECLARATION set, as ReturnTypeFromStrictScalarReturnExprRector already is in there and it would just "waste" resources on running both.

Which apparently leads to a build failure 😅 . So please let me know if you do actually want to have the rule, and whether it must be added to the the set. (I guess so, unless some exclusion is made for this rule specifically)

**Comment by samsonasik** [comment]
You can register to MissingInSetCommand exclude:

https://github.com/rectorphp/rector-src/blob/589bda6cd1eb7bc6cdc68313facc02cae41ba628/utils/Command/MissingInSetCommand.php#L28

**Comment by RobertMe** [comment]
@samsonasik thank you, I added it to the list 👍🏻

**Comment by TomasVotruba** [comment]
It should be mutually exclusive with `ReturnTypeFromStrictScalarReturnExprRector`, otherwise we'll get confused which rule does what. "Scalar" and "literals" are synonymous here.

How would you modify `ReturnTypeFromStrictScalarReturnExprRector` to make this happen?

**Comment by samsonasik** [comment]
@TomasVotruba if `ReturnTypeFromStrictScalarReturnExprRector` need only literal, the non-literal rule should exist imo to keep the type coverage functionality by type declaration set, eg on if else return scalar by caller, otherwise by literal:

```php
function foo()
{
    if (rand(0,1))  {
         return execute();
    }

   return false;
}

function execute(): bool
{
    return true;
}

**Comment by TomasVotruba** [comment]
I'm not sure what "literal" means here, and it's getting pretty confusing to me. 
Rule must be easy to unerstand and mutually exclusive. That's why we refactored from "one rule to return all return types" that yielded many false postives and was ignored.

How are these 2 rules different and what they share?
They both have to have only 1 job, otherwise we're adding a second rule to do one job.

**Comment by samsonasik** [comment]
What I mean is, if `ReturnTypeFromStrictScalarReturnExprRector` need only non-dynamic scalar, then we need another new rule, so 2 rules need to exists:

- ReturnTypeFromStrictScalarReturnExprRector
- ReturnTypeFromComplexScalarReturnExprRector

The "complex" one need to accomodate dynamic return, eg: by caller

**Comment by RobertMe** [comment]
> I'm not sure what "literal" means here, and it's getting pretty confusing to me.

The way I implemented it it is meant like "hardcoded". So like the example of @samsonasik above: https://github.com/rectorphp/rector-src/pull/5361#issuecomment-1858799956 `foo()` has two return statements, one is a literal/hardcoded value (`false`), and the other is based on something else (a method call, with strict return type, in this case). So my rule would ignore this method. While the existing rule would still set the return type, (based on the fact that both return expressions are of type bool).

I started creating this rule because I'm working on a big (10+ year old) code base. So running `ReturnTypeFromStrictScalarReturnExprRector` makes _a lot_ of changes, of which some are very easy to validate, like:
```php
public function getName()
{
    return 'foo';
}
```
where it thus adds a `: string`, but others are (a lot) harder to validate because there may be multiple exit points (/return statements), all being based on (combinations of) method calls or calculations etc.. So _for me_ it would be nice to have a rule which only makes the very straightforward changes where a method only has hardcoded return values so when reviewing the changes it is instantly clear what the return type needs to be (and there thus shouldn't even be the need for a review).
This contrary to `ReturnTypeFromStrictScalarReturnExprRector` where it is more complex (because it is smarter) and it sometimes leads to undesired results (like `return ceil(...)` adding a `float` return type while in a case I've noticed while going over the made changes that was undesirable and I thus had to change it to `int` / add an explicit `(int)` cast).

**Comment by RobertMe** [comment]
So, I already made the changes when I caught up with your discussion. But I checked here to ask a question myself 😄

Wouldn't it make more sense to drop my rule, and add an optional option to `ReturnTypeFromStrictScalarReturnExprRector`? So something like `literal_only` / `hardcoded_only` which defaults to `false` (not only for BC, but because it's awesome to see what Rector can do), but still gives the choice to only add return types to these "simple" methods where only hardcoded values are returned. For those (like me) who would like to add return types in two passes. First the "easy" changes which hardly need any reviewing / validation and a second pass (or multiple, per directory, passes) where manual reviewing is desirable.

Furthermore my reasoning for this is also that with the request to make them mutually exclusive it IMO is getting a bit "strange" on the implementation side as well. The code then actually reads like "it is possible to determine the return type in this case, but we don't want to because (this case is too easy and) another rule already does that for us". So having an option (instead of two separate rules) to switch between the "smart" and the "dumbed down" version IMO makes more sense than having the "smart" version not handle the extremely easy case(s).

**Comment by samsonasik** [comment]
Make configurable seems can be win-win solution, something like in PR:

- https://github.com/rectorphp/rector-src/pull/5354

**Comment by RobertMe** [comment]
> Rule must be easy to unerstand and mutually exclusive. That's why we refactored from "one rule to return all return types" that yielded many false postives and was ignored.

I think that's also partially the case for `ReturnTypeFromStrictScalarReturnExprRector`? As I wrote in the discussion leading to this PR:
> Furthermore it makes me wonder what the other mentioned rules like ReturnTypeFromStrictParamRector, ReturnTypeFromStrictTypedCallRector and ReturnTypeFromStrictTernaryRector will do, as the things I would expect them to do based on the name, are already involved by the ReturnTypeFromStrictScalarReturnExprRector rule. This is also confirmed by for example using the example for [ReturnTypeFromStrictTernaryRector](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#returntypefromstrictternaryrector) in the [demo with ReturnTypeFromStrictScalarReturnExprRector](https://getrector.com/demo/655568a4-7837-47ad-8474-08dc7a6043f1), the result is identical 😄

While I do understand the reasoning for it, the `ReturnTypeFromStrictScalarReturnExprRector` rule already handles _a lot_ of (complex) scenarios. The only "condition" which limits this rule is the actual determined return type. It must be a (single, non-nullable) scalar type. And the code can be very complex, including conditions (if/else), ternaries, native calls, calls to (user defined) strict typed functions / methods. Which seems like a lot of those rules I mentioned 😅

**Comment by RobertMe** [comment]
> Make configurable seems can be win-win solution, something like in PR:
> 
>     * [[Php55] Make StringClassNameToClassConstantRector configurable to keep first pre-backslash string configurable #5354](https://github.com/rectorphp/rector-src/pull/5354)

Thanks for the example 👍🏻

@TomasVotruba if you agree feel free to close this PR (as I think it's kinda odd to fully rewrite this PR and push a new branch based on main over it), with a comment to make such a change. Then I will make a PR for this solution.

**Comment by TomasVotruba** [comment]
Configurable seems as best option 👍

**Pull request closed without merging**
