### PR TITLE
[CodeQuality] Handle negative and positive int/float on InlineConstructorDefaultToPropertyRector

### LINKED ISSUE #8261: InlineConstructorDefaultToPropertyRector doesn't move signed numbers
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.18.5             |

`InlineConstructorDefaultToPropertyRector` doesn't move statements setting signed numbers class property defaults.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/3415d3c0-d878-4fc7-96d9-74e55553e37f

## Expected Behaviour

Both numeric property initialisations in the constructor should have been moved to the properties.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8261

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @JulianCBC

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba let's merge it ;)

**Comment by JulianCBC** [comment]
Is this actually enough to fully handle `UnaryMinus` and `UnaryPlus`? Am I right that, for the purposes of determining whether an expression is dynamic, the unary plus and unary minus don't matter? I.e. should something like:

```php
class Test {
    public $thing;
    public function __construct() {
        $this->thing = -CONSTANT;
    }
}
```

should also get moved?

**Comment by samsonasik** [comment]
Accessing constant on property default value can be dangerous that cause compile time error, see https://3v4l.org/W8Epd

I think exact int and float value is the safest :)

**Comment by JulianCBC** [comment]
I'm not disagreeing that it's the safest.

I think that something like this would cover almost all possible scenarios:

```php
            if ($expr instanceof UnaryPlus || $expr instanceof UnaryMinus) {
                return $this->isDynamicExpr($expr->expr);
            }
```

**Comment by samsonasik** [comment]
I see, yes, it seems can be covered with:

```diff
             if ($expr instanceof UnaryPlus || $expr instanceof UnaryMinus) {
-                return ! $expr->expr instanceof LNumber && ! $expr->expr instanceof DNumber;
+                return $this->isDynamicExpr($expr->expr);
+            }
```




@JulianCBC could you create a PR improvement for it with add fixture for possible constants ? Thank you.

**Comment by JulianCBC** [comment]
Can do! PR incoming...

**Comment by JulianCBC** [comment]
Done: #5177

**Pull request merged**
