### PR TITLE
[Defluent] Skip FluentChainMethodCallToNormalMethodCallRector inside ternary else

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
        $obj = new FluentInterfaceClass();

        return rand(0, 1)
            ? 1
            : $obj->someFunction()->otherFunction();
```

Currently got error:

```bash
1) Rector\Tests\Defluent\Rector\MethodCall\FluentChainMethodCallToNormalMethodCallRector\FluentChainMethodCallToNormalMethodCallRectorTest::test with data set #18 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
LogicException: leaveNode() returned invalid value of type integer
```

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
Moved the check handling to `MethodCallSkipAnalyzer` so can be re-used by other Defluent rules.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
