### PR TITLE
[PhpParser] Reduce AstResolver complexity by move check fileName is null to parseFileNameToDecoratedNodes()

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
I also removed `ClassLikeAstResolver` as used internally by `AstResolver` by move the code block to `AstResolver` itself, and remove useless empty stmts result on a File as lessly happen.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Amazing cleanup, thanks a lot :clap:

**Pull request merged**
