### PR TITLE
[DeadCode] Skip used after next statement on RemoveNonExistingVarAnnotationRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
        $options = [
            'a' => 'value a',
            'b' => 'value b',
            'c' => 'value c',
        ];

        extract($options);
        /**
         * @var string $a
         * @var string $b
         * @var string $c
         */
        $callback = function ($var1, $var2, $var3) {
            return $var1 . $var2 . $var3;
        };

        $callback($a, $b, $c);
```

It currently remove the `@var`, which should be skipped, remove the `@var` will make phpstan error, ref https://phpstan.org/r/1fb8ba90-c6e2-45a8-ba98-e278ba95cb85

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 , I updated for subcontent to be skipped to make it relevant:

```php
class SkipSubcontent
{
    public function get()
    {
        /** @var int $trainings */
        $trainingsLonger = $this->getAnotherData();

        return $trainings;
    }
}
```

**Comment by samsonasik** [comment]
Oh, sub content with never defined variable seems fine to be removed.

**Comment by samsonasik** [comment]
Currently cause issue on never defined variable in next statement:

```diff
1) Rector\Tests\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector\RemoveNonExistingVarAnnotationRectorTest::test with data set #2 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules-tests/DeadCode/Rector/Node/RemoveNonExistingVarAnnotationRector/Fixture/subcontent.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 {
     public function get()
     {
+        /** @var int $trainings */
         $trainingsLonger = $this->getAnotherData();
 
         return $trainings;
```

**Comment by samsonasik** [comment]
Fixed 🎉 It needs to check used variable, but with `extract()` func call previously called.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Looks good, thank you :+1:

**Pull request merged**
