### PR TITLE
[Defluent] Skip ReturnFluentChainMethodCallToNormalMethodCallRector on possibly not return $this

### PR DESCRIPTION
**Pull request by samsonasik**
By using existing `ReturnTypeInferer` service.

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba packages tests error seems unrelated as I tested with revert change and it keep get same error:

```bash
97) Rector\Nette\Tests\Rector\Property\NetteInjectToConstructorInjectionRector\NetteInjectToConstructorInjectionRectorTest::test with data set #7 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
4735
RangeException: The lexer returned an invalid token (id=38, value=&)
```

**Comment by TomasVotruba** [comment]
I think it might be broken by new phpstan - https://github.com/phpstan/phpstan/releases/tag/0.12.92


Could you lock it in `composer.json` to 0.12.91?

Downgrade to 0.12.91 in rector-symfony helped tests to pass

**Comment by samsonasik** [comment]
@TomasVotruba thank you, it seems pin to phpstan 0.12.91 make it works 🎉 , I temporary set CI packages test to use "rector/rector-src:dev-skip-possibly-not-return-this as 0.11.15" to make CI run https://github.com/rectorphp/rector-src/pull/418/files#diff-390c8e75450c4c39e24e2e9df7686f35822b34b1eec6832aa3a8f415614773f9R50

**Comment by samsonasik** [comment]
packages_tests.yaml needs to be reverted after merge.

All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Done :+1:

**Comment by samsonasik** [comment]
Reverting packages_tests.yaml at https://github.com/rectorphp/rector-src/pull/419

**Pull request merged**
