### PR TITLE
SelfType and StaticType are now handled in ObjectTypeSpecifier

### PR DESCRIPTION
**Pull request by TomasVotruba**
Thanks to https://github.com/rectorphp/rector-src/pull/1071, "self" and "static" are now handled on type parsing.

Thanks to that we can cleanup ad-hoc ifs from https://github.com/rectorphp/rector-src/pull/603

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba the error at rector build is about `return parent` type hint, so it seems unrelated to DowngradeParameter ref https://github.com/rectorphp/rector/commit/86233317979324e340e5fabf3d42f5a4a9f9796b#diff-f9c768134fc847864065551b3ec17bf045c658c4c88044f1334234afb19e6a1d

**Comment by TomasVotruba** [comment]
I see, thanks for reporting :+1: 

Could you come up with test case PR in the correct rule so we can reproduce it?

**Comment by samsonasik** [comment]
I will try.

**Comment by TomasVotruba** [comment]
Just for reference, this commit broke the build: https://github.com/rectorphp/rector/commit/86233317979324e340e5fabf3d42f5a4a9f9796b

Screenshot from 2021-10-27 11-19-13

**Comment by samsonasik** [comment]
@TomasVotruba that's seems unrelated with the following rules:

```diff
-    public function upper(): parent
+    /**
+     * @return mixed
+     */
+    public function upper()
     {
         $str = clone $this;
         $str->string = mb_strtoupper($str->string, 'UTF-8');
    ----------- end diff -----------

Applied rules:
 * DowngradePregUnmatchedAsNullConstantRector
 * DowngradeCovariantReturnTypeRector (https://www.php.net/manual/en/migration74.new-features.php#migration74.new-features.core.type-variance)
 * DowngradeAttributeToAnnotationRector (https://php.watch/articles/php-attributes#syntax)
 * DowngradeMixedTypeDeclarationRector
```

I tried to use above rules, but cannot reproduce it:

Given the following class:

```php
class SkipReturnParent
{
    public function run(): self
    {
        return $this;
    }
}

class AChild extends SkipReturnParent
{
    public function run(): parent
    {
        $str = clone $this;
        return $str;
    }
}
```

Got:

```diff
-    public function run(): parent
+    /**
+     * @return parent
+     */
+    public function run(): \Rector\Tests\DowngradePhp74\Rector\ClassMethod\DowngradeCovariantReturnTypeRector\Fixture\SkipReturnParent
     {
         $str = clone $thi
```

**Comment by samsonasik** [comment]
Actually, the `parent` need to be kept while it different use case.

**Comment by TomasVotruba** [comment]
I tried to isolated the bug in a fixture:
https://github.com/rectorphp/rector-src/pull/1081

What do you think?

**Pull request merged**
