### PR TITLE
Fix BleedingEdgeIncludePurifier to use random value on temporary file to avoid crash

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
New PHPStan 1.10.0 https://github.com/phpstan/phpstan/releases/tag/1.10.0 seems cause some notice, I ignored on phpstan.neon

**Comment by samsonasik** [comment]
New test error is due to new phpstan 1.10:

```diff
There was 1 failure:

1) Rector\Tests\TypeDeclaration\Rector\ClassMethod\AddMethodCallBasedStrictParamTypeRector\IntersectionTest::test with data set #1
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
         return [];
     }
 
-    private function removeEmptyValues($input): array
+    private function removeEmptyValues(array $input): array
```

**Comment by samsonasik** [comment]
Fixed 🎉 by check recursive call https://github.com/rectorphp/rector-src/pull/3396/commits/b8d4dcd83676b1813bc485583d43105e81ded664

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Go for merge when ready :+1:

**Pull request merged**
