### PR TITLE
Deprecate few option constants

### PR DESCRIPTION
**Pull request by TomasVotruba**
See https://github.com/rectorphp/rector-src/pull/1703

### CODE REVIEW

**Comment by sabbelasichon** [comment]
@TomasVotruba I would like to keep this option, because in some cases it is convenient to disallow symlinks following. Please don´t remove it.

**Comment by TomasVotruba** [comment]
I'll get back to it tomorrow. I think we're introducing too much detailed configuration, that can be handled by saint default.

Could you share such cases?

**Comment by sabbelasichon** [comment]
Before i introduced this option the symlinks were followed per default, but someone was trying to use the . as paths option for a TYPO3 Extension. In TYPO3 those setups are creating recursive symlinks (hard to explain) and using the skip option does not work because the skipper comes in place at a later time. 
see also https://github.com/rectorphp/rector/issues/6950

I can totally understand if you don´t like to support it, but for some it is very convenient. I am using an explicit paths configuration instead. I would be fine with it. But if you could make to support it, it would be nice.

**Comment by TomasVotruba** [comment]
I'm merging just the constant depreciations.
The symlinks are in another PR now to keep it separated.

I'm on phone now, but I'll check the examples during day. Thanks :)

**Pull request merged**
