### PR TITLE
[Renaming][PostRector] Handle skip path after defined at RenameClassRector

### LINKED ISSUE #7417: Incorrect behavior of RenameClassRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/224e1a17-d4f4-4d71-bafe-f1d4cf129846

```php
<?php

final class DemoFile extends Demo
{
    /**
     * @var int
     */
    private $test = 5;
    
    public function run()
    {
        $demo = new Demo();
        return 5;

        // we never get here
        return 10;
    }
}

final class Demo {
}

final class Demo2 {
}
```

### Responsible rules

```php
<?php

use Rector\Config\RectorConfig;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Set\ValueObject\SetList;
use Rector\Renaming\Rector\Name\RenameClassRector;
use Rector\DeadCode\Rector\Stmt\RemoveUnreachableStatementRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->skip([
        TypedPropertyRector::class => ['/*'], 
        RenameClassRector::class => ['/*']
    ]);
    
    $rectorConfig->rule(TypedPropertyRector::class);
    $rectorConfig->rule(RemoveUnreachableStatementRector::class);
    $rectorConfig->ruleWithConfiguration(RenameClassRector::class, [
        Demo::class => Demo2::class,
    ]);
};

```

## Expected Behavior

Rector should skip RenameClassRector rule (same as TypedPropertyRector was skipped)

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following config in tests:

```php
use Rector\Config\RectorConfig;
use Rector\Renaming\Rector\Name\RenameClassRector;
use Rector\Tests\Renaming\Rector\Name\RenameClassRector\Source\NewClass;
use Rector\Tests\Renaming\Rector\Name\RenameClassRector\Source\OldClass;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig
        ->ruleWithConfiguration(RenameClassRector::class, [
            OldClass::class => NewClass::class,
        ]);

    // skip the path after defined
    $rectorConfig->skip([
        RenameClassRector::class => [sys_get_temp_dir() . '/rector/tests_fixture_'],
    ]);
};
```

It not properly skipped, as there are 2 services:

- RenameClassRector
- ClassRenamingPostRector

The `ClassRenamingPostRector` apply the change already before it actually skipped because that read the configs:

https://github.com/rectorphp/rector-src/blob/3c168f03d38bb967a5e65e453f82adf120ef4eba/packages/PostRector/Rector/ClassRenamingPostRector.php#L27-L35

This PR try to fix it with add new interface: `PostRectorDependencyInterface` to define the dependencies of the PostRector when needed.

Fixes https://github.com/rectorphp/rector/issues/7417

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @grandmaster44

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
Rebased.

**Comment by samsonasik** [comment]
All checks have passed :tada: @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
