### PR TITLE
[CodeQuality] Skip dynamic second arg or has uppercase second arg on SimplifyStrposLowerRector

### LINKED ISSUE #8618: SimplifyStrposLowerRector isn't safe and should be removed
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.0.4             |

SimplifyStrposLowerRector underlying assumption is wrong, and the rule should be deprecated
https://getrector.com/demo/fbdf29d5-c428-498f-aead-30ad8e600f61

## Minimal PHP Code Causing Issue

```
final class DemoFile
{
    public function run(string $param, string $param2)
    {	
        if (strpos(strtolower($param), $param2) !== false) {
         	return 'hello';
        }
        
        return 'world';
    }
    
    public function runI(string $param, string $param2)
    {	
        if (stripos($param, $param2) !== false) {
         	return 'hello';
        }
        
        return 'world';
    }
}

$demo_file = new DemoFile();
echo $demo_file->run('Abc', 'aBc') . PHP_EOL;
echo $demo_file->runI('Abc', 'aBc');
```

This will result in 

```
world
hello
```

## Expected Behaviour

Using strpos with strtolower is not the same as stripos. Therefore changes done by SimplifyStrposLowerRector are not correct in many cases (= all cases where the 2nd argument may contain any non-lowercase characters)

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8618

### CODE REVIEW

**Comment by samsonasik** [comment]
@kkmuffme this should fix https://github.com/rectorphp/rector/issues/8618

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by kkmuffme** [comment]
@samsonasik thanks, but I'm not sure that's a good fix.
https://getrector.com/demo/27617834-bf9d-4730-881d-af84e759161b is only lowercase, so this should be changed according to what you said?

Also what if the uppercase letters are non-latin A-Z, e.g. cyrillic then this fix still has the same bug as before I guess?

**Comment by samsonasik** [comment]
direct string is safer for this, if you mean non-latin got unicode, that still correct, as strtolower only transform non-unicode to lower, so comparison will still correct.

**Pull request merged**
