### PR TITLE
Update rector_rules_overview.md

### PR DESCRIPTION
**Pull request by Lenny4**

### CODE REVIEW

**Comment by samsonasik** [comment]
docs is generated weekly

https://github.com/rectorphp/rector-src/blob/67ce52f0a8d6fff37ca569deba67c5635684dde6/.github/workflows/weekly_pull_requests.yaml#L23

**Comment by Lenny4** [comment]
@samsonasik how am I suppose to edit the doc ?
I tried to do it here https://github.com/rectorphp/rector/pull/7917 but:

> This repository content is generated by rectorphp/rector-src. Please open pull request to [rectorphp/rector-src](https://github.com/rectorphp/rector-src).

**Comment by samsonasik** [comment]
You can run:

```
composer docs
```

If the result is different with the expected, it may be bug on rule doc generator or code example in specific rule.

**Comment by Lenny4** [comment]
Ok so it seems like we will never be able to change `'alphabetically'` to `OrderAttributesRector::ALPHABETICALLY` as I'm assuming that it takes the value of `OrderAttributesRector::ALPHABETICALLY`.

It's just that I think it would be prettier to write `OrderAttributesRector::ALPHABETICALLY` instead of `'alphabetically'`.

**Comment by Lenny4** [comment]
@samsonasik 
Ok so it seems like my modification will never occurs because if I modify `[OrderAttributesRector::ALPHABETICALLY]` to `['OrderAttributesRector::ALPHABETICALLY']` the generated doc is:
```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->ruleWithConfiguration(OrderAttributesRector::class, [
        'OrderAttributesRector::ALPHABETICALLY',
    ]);
};
```
While I would like to be:
```php
return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->ruleWithConfiguration(OrderAttributesRector::class, [
        OrderAttributesRector::ALPHABETICALLY,
    ]);
};
```
It's a pity that we can't do this.

Do you think I could create a merge request to change `Symplify\RuleDocGenerator\ValueObject\CodeSampleConfiguredCodeSample` in order to specify if the `$configuration` is a "raw" string or simply a string (with no break change) ?

This way you can specify to write `OrderAttributesRector::ALPHABETICALLY` without the simple quote.

**Comment by samsonasik** [comment]
That possibly bug on symplify/rule-doc-generator, feel free to provide a patch there https://github.com/symplify/rule-doc-generator/

**Pull request closed without merging**
