### PR TITLE
[CodeQuality] ForeachItemsAssignToEmptyArrayToAssignRector skip classes that implement IteratorAggregate

### PR DESCRIPTION
**Pull request by Bl00D4NGEL**
# Failing Test for ForeachItemsAssignToEmptyArrayToAssignRector

Based on https://getrector.org/demo/1ec0351f-7789-6576-bb02-3bbbd8617543

refs https://github.com/rectorphp/rector/issues/6643
closes https://github.com/rectorphp/rector/issues/6643

### CODE REVIEW

**Comment by Bl00D4NGEL** [comment]
All checks passed @TomasVotruba feel free to review :)

**Comment by TomasVotruba** [comment]
Thank you :+1: 

Could you update the title to is matches your fix? It would be easier to find in the future in case of git blame on this PR

**Comment by Bl00D4NGEL** [comment]
Like that? :)

**Comment by TomasVotruba** [comment]
Perfect 👍 thank you

**Pull request merged**
