### PR TITLE
use type-safe private-property accessors

### PR DESCRIPTION
**Pull request by staabm**
utlitize https://github.com/symplify/symplify/pull/3860/

this PR requires a update of the package-builder lib, which I am an not able todo, as described in https://github.com/rectorphp/rector-src/pull/1590#issuecomment-1007410110

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I've released Symplify 10.0.9 few minutes ago, so you can use new version.

**Comment by staabm** [comment]
I tried updating the dependencies. I don't know wich combination of the requirements will make composer happy..

**Comment by TomasVotruba** [comment]
The issue was with stuck upgrade of https://packagist.org/packages/symplify/symfony-php-config
For some reason, packagist does not pick up new released tags and it always have to be done manually. The setup in Github repository is identical with other Symplify packages.

I've just bumped the version in packagist.

**Comment by TomasVotruba** [comment]
Cherry picked manually with CS fixes and composer.json tuning in: https://github.com/rectorphp/rector-src/pull/1660

**Pull request closed without merging**
