### PR TITLE
[Core] Fix undefined constant ReflectionClassConstant::IS_PUBLIC in php 7.x

### LINKED ISSUE #6864: v0.12.7 breaks compatibility with PHP 7.4 in ConfigureCallValuesCollector
[7e7a90f28649e8be78c0b77efb404dd2a62f157f](https://github.com/rectorphp/rector-src/pull/1443/commits/7e7a90f28649e8be78c0b77efb404dd2a62f157f) started using `ReflectionClassConstant::IS_PUBLIC` in `Rector\Core\DependencyInjection\Collector\ConfigureCallValuesCollector` which is not available prior to PHP 8.0.

This leads to the following error when running rector on PHP 7.4:

```
[ERROR] Undefined class constant 'IS_PUBLIC'
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6864 that the issue happen since rector 0.12.7 in php 7.x

Ref https://github.com/laminas/laminas-servicemanager-migration/runs/4485249466?check_suite_focus=true#step:3:213

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by W0rma** [comment]
@samsonasik Thank you very much! :+1:

**Pull request merged**
