### PR TITLE
Rollback ClassRenamePhpDocNodeVisitor to use clone $node to avoid unnecessary touch Identifier when no change

### LINKED ISSUE #7636: Known bug print format on ClassRenamePhpDocNodeVisitor
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |

## Minimal PHP Code Causing Issue

The change of PR:

- https://github.com/rectorphp/rector-src/pull/3149

can cause may cause unnecessary touch docblock on rename that can make invalid indentation:

```diff
1) system/Database/Config.php:36

    ---------- begin diff ----------
@@ @@
     protected static $factory;

     /**
-     * Creates the default
-     *
+    * Creates the default
+    *
      * @param array|BaseConnection|string|null $group The name of the connection group to use,
-     *                                                or an array of configuration settings.
+                                              or an array of configuration settings.
      * @phpstan-param array|BaseConnection|non-empty-string|null $group
-     * @param bool $getShared Whether to return a shared instance of the connection.
-     *
+    * @param bool $getShared Whether to return a shared instance of the connection.
+    *
      * @return BaseConnection
-     */
+    */
```

while fixable with coding standard tool, should be better if no touch at all. 

## Expected Behaviour

should not touch identifier when no change. I will look into it.

### PR DESCRIPTION
**Pull request by samsonasik**
Try to fix https://github.com/rectorphp/rector/issues/7636 while keep the existing functionality.

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 https://github.com/rectorphp/rector-src/pull/3154/commits/1e7f20aa92b4a3f7724d9a6f6583661a7410fa50

**Comment by samsonasik** [comment]
I added add auto import fqcn conflict same namespace fixture to prove that rename docblock keep working while importing the identifier https://github.com/rectorphp/rector-src/pull/3154/commits/d61fb302eaf4ba2b5097e0550afdfda4c82ee4a6

**Comment by samsonasik** [comment]
I added add  deep namespace inside fixture with union conflict last name https://github.com/rectorphp/rector-src/pull/3154/commits/f695a7fdda4fd73707c489724e3f8b197a27e46d

**Comment by samsonasik** [comment]
I am merging it ;)

**Review by TomasVotruba — COMMENTED** [review]
Great job 🙏👍

**Pull request merged**
