### PR TITLE
[CodingStyle] Skip comment after @var on InlineSimplePropertyAnnotationRector

### PR DESCRIPTION
**Pull request by samsonasik**
@dorrogeray This PR fix issue like in https://github.com/rectorphp/rector-src/pull/2072/files/3f788294918b1def03b74a15f0acab58d7c9e1cd#diff-eba629d378e644f5b16b35c4544953d32fddc8e3bdbcff7eeeadb1d0c3dce893

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by dorrogeray** [comment]
You were quicker. :smile: I was just installing xdebug in the container for this occasion..

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I am merging it to keep sync with https://github.com/rectorphp/rector-src/pull/2074 ;)

**Comment by samsonasik** [comment]
I am merging it to keep sync with https://github.com/rectorphp/rector-src/pull/2074 ;)

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
