### PR TITLE
Remove `ArraySpreadInsteadOfArrayMergeRector` from `LevelSetList::UP_TO_PHP_74`

### LINKED ISSUE #8292: move ArraySpreadInsteadOfArrayMergeRector out of `LevelSetList::UP_TO_PHP_74`
`ArraySpreadInsteadOfArrayMergeRector ` is a cosmetic rector, which is not necessary for 7.4 transition.

could it be removed from `LevelSetList::UP_TO_PHP_74`?

my personal feeling is, that it creates code which is less readable then a regular `array_merge()`

### PR DESCRIPTION
**Pull request by staabm**
closes https://github.com/rectorphp/rector/issues/8292

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by samsonasik** [comment]
The `missing-in-set` somehow not show an error:

```
➜  rector-src git:(main) bin/rector missing-in-set --ansi

                                                                                                                        
 [OK] All 53 sets contains the rules from their category                                                                
```                                                                                                                   

which should error and the rule should be registered in skipped rule constant:

https://github.com/rectorphp/rector-src/blob/0a2594d5569028d436e08738fe10d4edb16d61a7/utils/Command/MissingInSetCommand.php#L29

**Comment by samsonasik** [comment]
Ok, missing in set command seems detected on CI on rectify PR https://github.com/rectorphp/rector-src/actions/runs/6786798139/job/18448139153?pr=5229

**Comment by samsonasik** [comment]
@TomasVotruba I am thinking that `ArraySpreadInsteadOfArrayMergeRector` can be moved to coding style set, as it matter of preference

**Comment by TomasVotruba** [comment]
@samsonasik  Agreed :+1:

**Comment by staabm** [comment]
We should have these CI checks here at rector-src

**Comment by samsonasik** [comment]
https://github.com/rectorphp/rector-src/pull/5230

**Pull request merged**
