### PR TITLE
[Test] Re-try paratest

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba with various performance improvement and fixes for duplicate fixtures, let's try bring back paratest to speed up running test

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba it seems happen again in 98% run test:

https://github.com/rectorphp/rector-src/actions/runs/4907301256/jobs/8762329713

I will rollback

**Comment by samsonasik** [comment]
https://github.com/rectorphp/rector-src/pull/3754

**Comment by staabm** [comment]
does it always die at the same test-cases.. maybe we can put these in a group and let them run in serial fashion?

**Comment by samsonasik** [comment]
Probably using --debug or --v can see the actual test that error, that error is on random run, so not always shown, @TomasVotruba suggest to not use it at all at https://github.com/rectorphp/rector-src/pull/3754

**Pull request merged**
