### PR TITLE
[DeadCode] Add RemoveUselessReturnExprInConstructRector

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba @staabm here new rule to remove useless Return Expr in construct:

```diff
 class SomeClass
 {
     public function __construct()
     {
         if (rand(0, 1)) {
             $this->init();
-            return true;
+            return;
         }

         if (rand(2, 3)) {
-            return parent::construct();
+            parent::construct();
+            return;
         }

         $this->execute();
     }
 }
```

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Review by staabm — APPROVED** [review]
awesome

**Comment by samsonasik** [comment]
It seems it can cause a bug if it call a method call, eg:

```
return parent::__construct();
```

which should be :

```diff
-return parent::__construct();
+parent::__construct();
+return;
```

so use its Expr to Expression for that case

**Comment by TomasVotruba** [comment]
Looks good :+1:  Feel free to merge when ready

**Comment by samsonasik** [comment]
I added fixture for return dynamic Expr https://github.com/rectorphp/rector-src/pull/5158/commits/1e79d54e4f429825e69d23acd8da0e9d9f355ac5

**Comment by samsonasik** [comment]
Implemented, I added ability to `CallableNodeVisitor` to allow return array of `Node` (it `Stmt[]` obviously, but mark as `Node[]` to ensure same signature with what in `AbstractRector`), to allow replace single node to multi nodes on usage:

```diff
-return parent::__construct();
+parent::__construct();
+return;
```

with `SimpleCallableNodeTraverser` https://github.com/rectorphp/rector-src/pull/5158/commits/c1f0717b7938eb9d33037ace005ee0d4fd3da685

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it to have faster feedback to test ;)

**Comment by TomasVotruba** [comment]
:clap:

**Pull request merged**
