### PR TITLE
[Renaming] Keep comment on RenameClassRector

### LINKED ISSUE #7208: Regression from 0.13.3 -> 0.13.4 with RenameClassRector. Doc comments removed.
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.4            |

Some random comments gets removed.

#### Source
```php
<?php

namespace CompanyA;

class Foo
{
    public function foo()
    {
        $formula = [
        ]; // A fine comment sir
        $context = "foo";

        /** @var null|string $definition */
        $definition = null;

        // Some random comment here
        $engine = null;
    }

    public function bar(
    ) {
        /** @var null|string $definition */
        $definition = null;
    }
}


``` 

#### Config
```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Renaming\Rector\Name\RenameClassRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/app'
    ]);

    $rectorConfig->ruleWithConfiguration(RenameClassRector::class, [
        \App::class => Illuminate\Support\Facades\App::class,
    ]);
};
``` 

### 0.13.3
No changes

### 0.13.4
```diff
    ---------- begin diff ----------
@@ @@
     public function foo()
     {
         $formula = [
-        ]; // A fine comment sir
-        $context = "foo";
+        ]; $context = "foo";

-        /** @var null|string $definition */
         $definition = null;

-        // Some random comment here
         $engine = null;
     }

    ----------- end diff -----------

 [OK] 1 file would have changed (dry-run) by Rector 
```

## Some interesting notes:
- If you remove the `bar` method, or make it empty, will rector do nothing. 
- RenameClassRector must be used. Though no renaming is actually necessary
- Tried `dev-main`, same issue.

## Expected Behaviour

No changes

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7208

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @eigan

**Comment by samsonasik** [comment]
it seems it cause error in doctrine packages test:

https://github.com/rectorphp/rector-src/runs/6742172295?check_suite_focus=true#step:7:19

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
