### PR TITLE
[Php81] Skip static property on ReadOnlyPropertyRector

### LINKED ISSUE #7050: Incorrect behavior of ReadOnlyPropertyRector: tries to set static property to readonly
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/8cef18b3-c224-49f6-872e-128119d4855b

```php
<?php

declare(strict_types=1);

final class A
{
    private static stdClass $x;

    public function __construct(stdClass $x)
    {
        self::$x = $x;
    }

    public static function x(): stdClass
    {
        return self::$x;
    }
}
```

### Responsible rules

* `ReadOnlyPropertyRector`

## Expected Behavior

no change

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7050

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉  /cc @simPod

**Comment by samsonasik** [comment]
rectify's fix-cs seems make inlined method's opening `{`, seems due to latest symplify.

```diff
5) src/Exception/Template/TemplateTypeNotFoundException.php

    ---------- begin diff ----------
@@ -11,8 +11,7 @@
     /**
      * @param string[] $availableTypes
      */
-    public function __construct(string $type, array $availableTypes)
-    {
+    public function __construct(string $type, array $availableTypes) {
         $availableTypesAsString = implode("', ", $availableTypes);

         $message = sprintf('No template found for type "%s". Possible values are "%s"', $type, $availableTypesAsString);
    ----------- end diff -----------


Applied checkers:

 * PhpCsFixer\Fixer\Basic\BracesFixer
 * PhpCsFixer\Fixer\Phpdoc\PhpdocNoEmptyReturnFixer
 * Symplify\CodingStandard\Fixer\LineLength\LineLengthFixer
 * Symplify\CodingStandard\Fixer\Spacing\StandaloneLineConstructorParamFixer
 * 
 ```

**Comment by simPod** [comment]
Thanks! I'm kind of overwhelmed by OSS work elsewhere rn thus not provided patch right away. Appreciated.

**Comment by samsonasik** [comment]
I skipped `PhpCsFixer\Fixer\Basic\BracesFixer` in `ecs.php` as it now cause `{` in methods inlined

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
