### PR TITLE
[DowngradePhp74] various fixes and improvements

### PR DESCRIPTION
**Pull request by Lctrs**
Last commit is expected to fail. I couldn't find why it drops phpdoc.

@TomasVotruba May you help please ?

### CODE REVIEW

**Comment by samsonasik** [comment]
2 things:

- please describe what various fixes and improvements is
- please don't change existing fixture to avoid regression, add new one instead.

**Comment by Lctrs** [comment]
>     * please describe what various fixes and improvements is

The commits' messages aren't enough ?

>     * please don't change existing fixture to avoid regression, add new one instead.

Will do.

**Comment by samsonasik** [comment]
Not enough, also better to provide per-single thing in one PR to ease to revert by per-bug/feature provided.

**Comment by Lctrs** [comment]
Will come back to this.

**Pull request closed without merging**
