### PR TITLE
[Experiment][Naming] Keep GroupUse Stmt on UseImportsResolver::resolveForNode()

### PR DESCRIPTION
**Pull request by samsonasik**
Continue of https://github.com/rectorphp/rector-src/pull/2348 with keep `GroupUse` Stmt as is so it flexible for user to use it.

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba @dritter this is continue of https://github.com/rectorphp/rector-src/pull/2348 which keep `GroupUse` Stmt as is, so the `UseImportsResolver::resolveForNode()` can result collection of `Use_[]` and/or `GroupUse[]` so the usage will depends on the user that use it, eg: `GroupUse` manipulation/deletion.

**Comment by samsonasik** [comment]
I am closing for now, it needs to verify with existing codebase with use the `->name` directly without prefix, so converting to `Use_` statement with `prefix` addition on https://github.com/rectorphp/rector-src/pull/2348 probably better for now.

**Comment by samsonasik** [comment]
Re-open, re-tried to applied in the code base with add prefix for name retrieval.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Let's :ship: it :+1:

**Pull request merged**
