### PR TITLE
Fix regression in scalar type comparison

### PR DESCRIPTION
**Pull request by TomasVotruba**
Fixes regression from https://github.com/rectorphp/rector-src/pull/3573

### CODE REVIEW

**Comment by samsonasik** [comment]
This possibly somehow cause a bug on remove unused use on const fetch:

https://github.com/rectorphp/rector-src/blob/e66317aeb276bb0b544e7b4b55057c9dab5fbb73/packages/PostRector/Rector/UnusedImportRemovingPostRector.php#L163-L164

**Comment by TomasVotruba** [comment]
Fix regression from other types too: https://github.com/rectorphp/rector-src/pull/3571

**Comment by TomasVotruba** [comment]
@samsonasik Yeah, because integer type and generic integer type are both different types of integers.

**Comment by TomasVotruba** [comment]
@samsonasik It seems there is regression everywhere now. It's hard to find out with exactl lines are responsible.

Could you revert all of those PRs and include test fixtures from this PR? I gotta run now.

**Comment by samsonasik** [comment]
I will 👍

**Comment by yguedidi** [comment]
@TomasVotruba sorry for the extra work! 🙁 
How you catched those regressions?

**Comment by samsonasik** [comment]
@yguedidi you can run bin/rector like this : 

```diff
bin/rector process rules/Php70/Rector/MethodCall/ThisCallOnStaticMethodToStaticCallRector.php --dry-run
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
1 file with changes
===================

1) rules/Php70/Rector/MethodCall/ThisCallOnStaticMethodToStaticCallRector.php:132

    ---------- begin diff ----------
@@ @@
         return $this->nodeFactory->createStaticCall($objectReference, $methodName, $node->args);
     }

-    /**
-     * @return ObjectReference::STATIC|ObjectReference::SELF
-     */
     private function resolveClassSelf(MethodCall $methodCall): string
     {
         $classLike = $this->betterNodeFinder->findParentType($methodCall, Class_::class);
    ----------- end diff -----------

Applied rules:
 * UnionTypesRector
 * AddParamTypeSplFixedArrayRector
 * 
```

**Comment by yguedidi** [comment]
@samsonasik thanks! I realize I was to focused on running tests that didn't run rector itself... very sorry! I can open revert PRs if you want?

**Comment by samsonasik** [comment]
Resolved by revert all is* changes at https://github.com/rectorphp/rector-src/pull/3584, I will copy your fixture manually on separate PR.

**Pull request closed without merging**
