### PR TITLE
[Parallel] Improve tests to use file processor over file analyzer + fix missing RectorWithLineChange de/serialization

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref https://github.com/rectorphp/rector/issues/2971

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba the ` note [skip ci] ` message seems make scoped build not started, could you create an empty commit to push to main branch to trigger build? 

```bash
git checkout main
git commit --allow-empty -m "Trigger notification"
git push origin main
```

**Comment by samsonasik** [comment]
@TomasVotruba the scoped build seems still error on latest build on parallel lint, ref https://github.com/rectorphp/rector-src/runs/4649685575?check_suite_focus=true#step:14:79

                              
```bash

Parse error: rector-prefixed-downgraded/vendor/rector/rector-nette/src/FileProcessor/NeonFileProcessor.php:44
    42|     {
    43|         if ($this->neonRectors === []) {
  > 44|             return;
    45|         }
    46|         $fileContent = $file->getFileContent();
A function with return type must return a value in rector-prefixed-downgraded/vendor/rector/rector-nette/src/FileProcessor/NeonFileProcessor.php on line 44
```

**Comment by samsonasik** [comment]
@TomasVotruba I created PR https://github.com/rectorphp/rector-nette/pull/53 for it.

**Comment by samsonasik** [comment]
@TomasVotruba it works 🎉 

Screen Shot 2021-12-28 at 19 09 01

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
