### PR TITLE
[PhpDocInfo] Fixes Partial value update got duplicated on DoctrineAnnotationTagValueNode change

### LINKED ISSUE #7020: Changing PHPDoc with phpdoc return typehint duplicates Annotation
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | bc0eac36f4eece9f824efdb71c55ae59355d6a09             |

### Code

```php
<?php

use Shopware\Core\Framework\Context;
use Shopware\Core\Framework\Routing\Annotation\Since;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

class Test {
    /**
     * @Since("6.4.0.1")
     * @Route("/api/_admin/reset-excluded-search-term", name="api.admin.reset-excluded-search-term", methods={"POST"})
     *
     * @return JsonResponse
     */
    public function resetExcludedSearchTerm(Context $context)
    {

    }
}
```

### Rector

```php
<?php

namespace Shopware\Core\DevOps\Rector;

use PhpParser\Node;
use PhpParser\Node\Stmt\ClassMethod;
use Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfo;
use Rector\BetterPhpDocParser\PhpDocManipulator\PhpDocTagRemover;
use Rector\BetterPhpDocParser\ValueObject\PhpDoc\DoctrineAnnotation\CurlyListNode;
use Rector\Core\Rector\AbstractRector;
use Rector\Php80\NodeFactory\AttrGroupsFactory;
use Symplify\RuleDocGenerator\ValueObject\RuleDefinition;

class TestRector extends AbstractRector
{
    public function __construct(
        private AttrGroupsFactory $attrGroupsFactory,
        private PhpDocTagRemover $phpDocTagRemover,
    ) {
    }

    public function getRuleDefinition(): RuleDefinition
    {
        return new RuleDefinition('uff', []);
    }

    public function getNodeTypes(): array
    {
        return [
            ClassMethod::class,
        ];
    }

    public function refactor(Node $node)
    {
        $phpDocInfo = $this->phpDocInfoFactory->createFromNode($node);
        if (!$phpDocInfo instanceof PhpDocInfo) {
            return null;
        }

        $route = $phpDocInfo->getByName('Route');

        $defaults = $route->value->getValue('defaults');

        if ($defaults === null) {
            $defaults = new CurlyListNode();
        }

        $route->value->changeValue('defaults', $defaults);
    }
}
```

## Expected Behaviour

The route just gets an additional "defaults" and not be duplicated

```
1) class.php:7

    ---------- begin diff ----------
@@ @@
 class Test {
     /**
      * @Since("6.4.0.1")
+     * @Route("/api/_admin/reset-excluded-search-term", name="api.admin.reset-excluded-search-term", methods={"POST"}, defaults={})
      * @Route("/api/_admin/reset-excluded-search-term", name="api.admin.reset-excluded-search-term", methods={"POST"})
      *
      * @return JsonResponse
    ----------- end diff -----------

                                                                                                                        
 [OK] 1 file would have changed (dry-run) by Rector                                                                     
                                                                                                                        

```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7020

### CODE REVIEW

**Comment by samsonasik** [comment]
It seems happen because before `@Route`, there is `SpacelessPhpDocTagNode`

```
     * @Since("6.4.0.1")
```

which a annotation class `use Shopware\Core\Framework\Routing\Annotation\Since;`, so the duplication happen when there is multiple annotation class, changed after 1 annotation class, so it possibly cause parent -> child duplication.

**Comment by TomasVotruba** [comment]
Just checking, is this still valid? What is a blocker here to move it forward?

**Comment by samsonasik** [comment]
@TomasVotruba it is, it somehow duplicated when 2 `SpacelessPhpDocTagNode` exists, when next is changed

**Comment by samsonasik** [comment]
Finally 🎉 All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
it seems duplicating again when changing below `DoctrineAnnotationTagValueNode`:

```php
     * @required
     * @Route("/api/_admin/reset-excluded-search-term", name="api.admin.reset-excluded-search-term", methods={"POST"})
     *
```

it got :

```diff
      * @Route("/api/_admin/reset-excluded-search-term", name="api.admin.reset-excluded-search-term", methods={"POST"}, defaults={})
+     * @Route("/api/_admin/reset-excluded-search-term", name="api.admin.reset-excluded-search-term", methods={"POST"})
```

**Comment by samsonasik** [comment]
mark as draft again, it seems need to check against non `SpacelessPhpDocTagNode` too.

**Comment by samsonasik** [comment]
Finally Fixed 🎉🎉🎉 All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I am merging it ;)

**Comment by TomasVotruba** [comment]
:+1:

**Comment by samsonasik** [comment]
New downgrade error seems unrelated, symfony cache trait and test http client can be ignored from parallellint check.

**Pull request merged**
