### PR TITLE
[CodeQuality] Allow transform return; to return null; when there is other return with Expr on ExplicitReturnNullRector

### PR DESCRIPTION
**Pull request by samsonasik**
@staabm here it is for https://github.com/rectorphp/rector/issues/8349 ;)

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by staabm** [comment]
Awesome thank you. I will try it on monday and report back

**Comment by staabm** [comment]
no problem until now. thank you

**Comment by samsonasik** [comment]
@staabm Thank you for the verify 👍

**Pull request merged**
