### PR TITLE
[Php80] Normalize Class Const Fetch as array key on AnnotationToAttributeRector

### LINKED ISSUE #6985: Incorrect behavior of AnnotationToAttributeRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

When a constant is used to define an array key inside an annotation, Rector wraps it with quotes when converting to attributes (ie: `AbstractObjectNormalizer::SKIP_NULL_VALUES` becomes `'AbstractObjectNormalizer::SKIP_NULL_VALUES'`).

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec85a79-2b52-641e-89af-8128ec1e3b09

```php
<?php

use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer;

/**
 * @ApiResource(
 *     itemOperations={
 *         "get" = {
 *             "normalization_context" =  {
 *                 AbstractObjectNormalizer::SKIP_NULL_VALUES = true
 *             }
 *         }
 *     }
 * )
 */
final class DemoClass
{
}
```

### Responsible rules

* `AnnotationToAttributeRector`

## Expected Behavior

The constant used as an array key is kept as is.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6985
Closes https://github.com/rectorphp/rector-src/pull/1766

### CODE REVIEW

**Comment by TomasVotruba** [comment]
This cannot be resolved by regex, but on Attribute factory level. I'm looking into this

**Comment by samsonasik** [comment]
ok 👍

**Comment by samsonasik** [comment]
I keep it open as alternative

**Comment by TomasVotruba** [comment]
Replaced by https://github.com/rectorphp/rector-src/pull/1766

**Pull request closed without merging**
