### PR TITLE
Add failing test fixture for AnnotationToAttributeRector

### PR DESCRIPTION
**Pull request by TomasVotruba**
Based on https://getrector.org/demo/4c7348a5-8a07-4f85-aa4d-e462f672dae8

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@stephanvierkant I've rebased your fixture and fixed incorrect namespace possition and it is passing :heavy_check_mark: 
Probably fixed already :) 

Thank you for the PR :+1:

**Comment by stephanvierkant** [comment]
This rector still doesn't work properly. It replaces `\Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity` by `\Doctrine\ORM\Mapping\Entity`

```diff
-/**
- * @UniqueEntity(
- *     fields={"parent", "code"},
- *     errorPath="code",
- *     message="Already exists!",
- *     ignoreNull=false,
- *     groups={"default", "update"}
- * )
- */
 #[Table('Foo')]
-#[Entity]
+#[Entity]
+#[\Doctrine\ORM\Mapping\Entity(fields: ['parent', 'code'], errorPath: 'code', message: 'Already exists!', ignoreNull: false, groups: ['default', 'update'])]
 class Foo
-{}
+{}
```
(same demo link)

**Comment by samsonasik** [comment]
@stephanvierkant could you try `"rector/rector": "dev-main"` ?

**Comment by stephanvierkant** [comment]
I'm using the demo site. Or is it not running on dev-main?

**Comment by samsonasik** [comment]
demo site is not running latest dev-main, demo site is running latest release. The check of latest release is per-3 days, see:

https://github.com/rectorphp/getrector.org/blob/18a090dd6d3376f928df7cb353d4d9e18d4228df/composer.json#L16

https://github.com/rectorphp/getrector.org/blob/18a090dd6d3376f928df7cb353d4d9e18d4228df/.github/workflows/per_three_day_pull_request_automatic_update.yaml#L7

**Comment by stephanvierkant** [comment]
Tried on dev-main. Now `@Gedmo\SortablePosition` (which doesn't support attributes) got replaced by `\Doctrine\ORM\Mapping\Table` 

```diff
-    /**
-     * @Gedmo\SortablePosition
-     */
     #[Column('position', type: 'integer')]
+    #[\Doctrine\ORM\Mapping\Table]
     protected int $position = 0;
```

**Comment by samsonasik** [comment]
@stephanvierkant please create failing fixture for that, thank you.

**Pull request merged**
