### PR TITLE
Update test fixture: Do not remove `true|T` from phpdoc as it cannot be narrowed to native `bool|T` type hint

### PR DESCRIPTION
**Pull request by simPod**
Original code does not compile

https://3v4l.org/klALN

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, I'm not sure what is the issue here. Could you elaborate more?

**Comment by TomasVotruba** [comment]
Hi, I'm not sure what is the issue here. Could you elaborate more?

**Comment by simPod** [comment]
Oh wait, native return typehint `:false` is valid? 😮

**Comment by simPod** [comment]
In that case, I have to rephrase it into `true` type hint https://3v4l.org/7PYjDY

**Comment by TomasVotruba** [comment]
Yes, since union types you can use `false` as part of union. Not standalone.

The `true` is never part of PHP native type in the snippet you provided. That behavior is correct.

**Comment by simPod** [comment]
> That behavior is correct.

https://github.com/rectorphp/rector-src/pull/1662/files#diff-f3d0ea097fa32b9c2f428814dd887106a6ee7f837615e008bcb7ee219c01e301R27

the type should be converted into `:bool|int` but is wrongly converted to `:true|int`. Thus the test is failing.

**Comment by TomasVotruba** [comment]
Where do you see `true|int`? In CI here is `int|bool`

image

https://github.com/rectorphp/rector-src/runs/4787682009?check_suite_focus=true#step:5:85

**Comment by simPod** [comment]
The `true|int` should be kept but rector tries to remove it.

**Comment by simPod** [comment]
I confused myself here a bit. Will rephrase. 🤯

**Comment by simPod** [comment]
So this removal is the issue

image

I know the method does not return `false` so I use `true` instead of `bool`.

**Comment by TomasVotruba** [comment]
Yeah, union types can get little crazy in nestings. Been there.

Good, the last error makes sense. The comment should remain 👍

**Comment by samsonasik** [comment]
@simPod I cherry-picked your commit at PR https://github.com/rectorphp/rector-src/pull/1715

**Pull request closed without merging**
