### PR TITLE
[DX] Remove PARENT_NODE from AnonymousFunctionFactory

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref https://github.com/rectorphp/rector/issues/7947

### CODE REVIEW

**Comment by samsonasik** [comment]
It used by ArrowFunctionToAnonymousFunctionRector to save parent Closure, so if parent going to be removed, the new Visitor is needed to save existing variable into inner Closure

**Comment by TomasVotruba** [comment]
Gotta go now, will check later :+1:

**Comment by samsonasik** [comment]
Let's rebase this

**Comment by samsonasik** [comment]
It still cause error on `ArrowFunctionToAnonymousFunctionRectorTest`: 

```diff
There were 5 failures:

1) Rector\Tests\DowngradePhp74\Rector\ArrowFunction\ArrowFunctionToAnonymousFunctionRector\ArrowFunctionToAnonymousFunctionRectorTest::test with data set #0
Failed on fixture file "no_use_foreach.php.inc"
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 {
     public function duplicate()
     {
-        $callable = function () {
+        $callable = function () use ($iterator, $foo) {
             return function (Iterator $iterator) {
```

**Comment by samsonasik** [comment]
I will try handle in separate PR https://github.com/rectorphp/rector-src/pull/4443

**Pull request closed without merging**
