### PR TITLE
[e2e] Handle $rectorConfig->paths() with wilcards * config

### LINKED ISSUE #8127: "[ERROR] The given paths do not match any files" when using wildcards in the paths
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.12            |

I'm using wildcards in the paths to process my files, such as:

```php
    $paths = [
            $this->rootDirectory . '/layers/Engine/packages/*/src/*',
            $this->rootDirectory . '/layers/Engine/packages/*/tests/*',
    ];
    $rectorConfig->paths($paths);
```

This had so far been supported by Rector, however now I get an error:

```
[ERROR] The given paths do not match any files
```

## Potential source of the issue

@staabm I assume the issue was introduced in this PR: https://github.com/rectorphp/rector-src/pull/4326

Checking the source code for method `addPaths` in `src/StaticReflection/DynamicSourceLocatorDecorator.php`:

```php
    public function addPaths(array $paths) : void
    {
        if ($paths === []) {
            return;
        }
        $files = $this->fileAndDirectoryFilter->filterFiles($paths);
        $this->dynamicSourceLocatorProvider->addFiles($files);
        $directories = $this->fileAndDirectoryFilter->filterDirectories($paths);
        foreach ($directories as $directory) {
            $filesInDirectory = $this->phpFilesFinder->findInPaths([$directory]);
            $this->dynamicSourceLocatorProvider->addFilesByDirectory($directory, $filesInDirectory);
        }
    }
```

and following to methods `filterDirectories` and `filterFiles` in `src/FileSystem/FileAndDirectoryFilter.php`, I can see that these do not support wildcards:

```php
    public function filterDirectories(array $filesAndDirectories) : array
    {
        $directories = \array_filter($filesAndDirectories, static function (string $path) : bool {
            return \is_dir($path);
        });
        return \array_values($directories);
    }

    public function filterFiles(array $filesAndDirectories) : array
    {
        $files = \array_filter($filesAndDirectories, static function (string $path) : bool {
            return \is_file($path);
        });
        return \array_values($files);
    }
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8127

@leoloso @staabm lets' see if it fixable ...

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @leoloso @staabm

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Comment by staabm** [comment]
Thanks 🙏

**Comment by leoloso** [comment]
Thanks @samsonasik 👏

**Pull request merged**
