### PR TITLE
[Php74] Add MoneyFormatToNumberFormatRector

### LINKED ISSUE #7334: [PHP 7.4] Replace deprecated money_format() with number_format()/NumberFormatter
This function was deprecatedin PHP 7.4

* https://github.com/php/php-src/commit/b1cdf06673789cf5c379e7af88c5af98bd06735c

This is tested and values are identical 1:1 in both version.

```diff
-            $value = money_format('%i', $value);
+            $roundedValue = round($value, 2, PHP_ROUND_HALF_ODD);
+            $value = number_format($roundedValue, 2, '.', '');
```

Another way is using `NumberFormatter`, but I could not figure it out:

* https://benedikt.gr/posts/2019-12-01-php-money-format-to-number_formatter/

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7334

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I'd like to merge this to have at least some verison to test out in the wild. We can iterate on it later with better version based on feedback from community :)

What needs to be done here to finish it?

**Comment by samsonasik** [comment]
I was waiting for @clarkphp implementation since he wanted to do it... 

I will try copy @clarkphp implementation at https://gist.github.com/clarkphp/b2643a4c4a16cafd02bd85eba18a72dd to use InlineParser with invokable function except he sent PR first

**Comment by samsonasik** [comment]
Ref https://github.com/rectorphp/rector/issues/7334#issuecomment-1213049981

**Comment by TomasVotruba** [comment]
I think that's the issue. It's a blocker for last couple of weeks and we need the rule on one project to try out.
I'd prefer to go with simple implementation and then iterate the one you linked, if needed.

**Comment by samsonasik** [comment]
@TomasVotruba ok, applied basic functionalty

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :+1: :clap:

**Pull request merged**
