### PR TITLE
[Scope] Pull Scope from Node instead of origNode on Abstract*Rector take 2

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba @staabm here I pull Scope on `AbstractRector`,  `AbstractScopeAwareRector` `ClassRenamingPostRector` from Node instead of origNode.

The docblock renamer seems still require it, so move the scope from origNode only on there :)

### CODE REVIEW

**Comment by samsonasik** [comment]
Ready to merge 👍

**Comment by staabm** [comment]
Looks like it is missing a test?

**Comment by samsonasik** [comment]
The failing check is waiting for PR:

- https://github.com/rectorphp/rector-src/pull/4534

to be merged first so CI can green. 

Docblock may read origNode due to PhpDocInfo cache, that can be next investigation after this got merged.

**Comment by TomasVotruba** [comment]
Lets go for it :)

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
