### PR TITLE
[Php80] Keep numeric string as is on StringAnnotationToAttributeMapper

### LINKED ISSUE #8941: Incorrect behavior of TestWithAnnotationToAttributeRector with integers
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/322b336f-f232-4614-a264-6077e0a8f206

```php
<?php

class UserControllerTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @testWith ["2"]
     *           ["benjamin.sisko@ds9.example.com"]
     */
    public function testSomething(string $userId): void
    {
    }
}
```

### Responsible rules

* `TestWithAnnotationToAttributeRector`

## Expected Behavior

I'd expect `#[TestWith('2')]` as the annotation was using a string, but somehow it thinks it is smart to convert that to an int because I guess the string is numeric. Anyway this breaks the test as the $userId param requires a string.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8941

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @Seldaek

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by Seldaek** [comment]
Thanks for the quick fix, are you sure this isn't gonna cause regressions like will it still treat `2` as int now? Maybe not but I wonder if all the other checks in that file make any sense then.

If you look at this https://getrector.com/demo/ae99daee-198a-4d2c-b948-d9788b3c25b2 - I also don't see why `"true"` gets turned into `true`.

Basically if something was a quoted string it should remain so as far as I can tell, not sure why all this magic in StringAnnotationToAttributeMapper was added in the first place.

**Comment by samsonasik** [comment]
@Seldaek I see, special decorator seems needed for `@TestWith` to avoid regression, like doctrine decorator

https://github.com/rectorphp/rector-src/blob/72c537af546dae8970b6db5f79f2a1e617db7f61/rules/Php80/AttributeDecorator/DoctrineConverterAttributeDecorator.php#L37

I will check

**Comment by samsonasik** [comment]
I am going to revert it for now, the fix should be in a single PR to ease rollback.

**Comment by samsonasik** [comment]
Reverted at https://github.com/rectorphp/rector-src/pull/6609

**Pull request merged**
