### PR TITLE
[CodingStyle] Handle nested breaks in BinarySwitchToIfElseRector and SingularSwitchToIfRector

### PR DESCRIPTION
**Pull request by rajyan**
fixes https://github.com/rectorphp/rector/issues/6458

### CODE REVIEW

**Comment by rajyan** [comment]
@TomasVotruba 
HI, I tried to fix #6458.
PHPStan job is failing, but I think it's not related to my changes. Do you have any suggestions how to fix it?

**Comment by samsonasik** [comment]
@rajyan that's handled at https://github.com/symplify/symplify/pull/3310 . For now, I think you can ignore it in `phpstan.neon` by add the following:

```neon
        -
            message: '#Missing sprintf\(\) function for a mask#'
            path: rules/CodingStyle/Rector/Encapsed/EncapsedStringsToSprintfRector.php #124
```

**Comment by samsonasik** [comment]
@rajyan please rebase against latest main, should be green now

**Comment by rajyan** [comment]
@samsonasik 
Thanks!

@TomasVotruba
I'm ready for review now!

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
