### PR TITLE
Added fixture for CallableThisArrayToAnonymousFunctionRector

### PR DESCRIPTION
**Pull request by stephanvierkant**
See https://github.com/rectorphp/rector/issues/6540

### CODE REVIEW

**Comment by samsonasik** [comment]
test need to be failure for failing test case.

**Comment by stephanvierkant** [comment]
I don't get it. This exact same code is failing in the demo and in my project, but this test doesn't fail. Any idea why?

**Comment by TomasVotruba** [comment]
The first obvious idea is that Rector version is probably different. Repository is always ahead of last tagged version

**Comment by stephanvierkant** [comment]
How can I see what version is used on the demo site?

Can't test against dev-main (or >0.11.32) in my project due to https://github.com/rectorphp/rector/issues/6543. I'll wait on that fix.

**Comment by TomasVotruba** [comment]
Demo site is just for trying Rector out, not for contributing.
To contribute, you should run this repository locally on your machine and work with its tests. That's the only way to ensure you're using the latest code base :)

**Comment by TomasVotruba** [comment]
The rule you've chosen is refactoring `[$this, 'method']`, see https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#callablethisarraytoanonymousfunctionrector

I can't see anything like this in a the fixture. Are you sure the fixture/rule is correct match?

**Comment by stephanvierkant** [comment]
Nope, I'm not sure. I was expecting it based on the stacktrace (rector v0.11.32):

```
[refactoring] src/EventListener/TaggableListener.php
[applying] Rector\CodeQuality\Rector\Name\FixClassCaseSensitivityNameRector
[applying] Rector\CodeQuality\Rector\Class_\CompleteDynamicPropertiesRector
[applying] Rector\Transform\Rector\Class_\AddInterfaceByTraitRector
[applying] Rector\CodeQuality\Rector\FunctionLike\RemoveAlwaysTrueConditionSetInConstructorRector
[applying] Rector\CodeQuality\Rector\ClassMethod\DateTimeToDateTimeInterfaceRector
[applying] Rector\CodeQuality\Rector\ClassMethod\NarrowUnionTypeDocRector
[applying] Rector\CodingStyle\Rector\ClassMethod\FuncGetArgsToVariadicParamRector
[applying] Rector\Php70\Rector\ClassMethod\Php4ConstructorRector
[applying] Rector\Php70\Rector\FunctionLike\ExceptionHandlerTypehintRector
[applying] Rector\CodeQuality\Rector\Return_\SimplifyUselessVariableRector
[applying] Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector
[applying] Rector\CodeQuality\Rector\Array_\ArrayThisCallToThisMethodCallRector
[applying] Rector\CodeQualityStrict\Rector\Variable\MoveVariableDeclarationNearReferenceRector
[applying] Rector\Php70\Rector\Variable\WrapVariableVariableNameInCurlyBracesRector
[applying] Rector\CodeQuality\Rector\Expression\InlineIfToExplicitIfRector
[applying] Rector\CodeQuality\Rector\Assign\CombinedAssignRector
[applying] Rector\CodeQuality\Rector\Assign\SplitListAssignToSeparateLineRector
[applying] Rector\MysqlToMysqli\Rector\Assign\MysqlAssignToMysqliRector
[applying] Rector\Php70\Rector\Assign\ListSplitStringRector
[applying] Rector\Php70\Rector\Assign\ListSwapArrayOrderRector
[applying] Rector\Php71\Rector\Assign\AssignArrayToStringRector
[applying] Rector\Php71\Rector\FuncCall\RemoveExtraParametersRector
[applying] Rector\CodingStyle\Rector\MethodCall\UseMessageVariableForSprintfInSymfonyStyleRector
[applying] Rector\Php70\Rector\MethodCall\ThisCallOnStaticMethodToStaticCallRector
[applying] Rector\Php70\Rector\FuncCall\NonVariableToVariableOnFunctionCallRector
[applying] Rector\CodeQuality\Rector\If_\SimplifyIfNotNullReturnRector
[applying] Rector\CodeQuality\Rector\If_\SimplifyIfReturnBoolRector
[applying] Rector\CodeQuality\Rector\If_\SimplifyIfElseToTernaryRector
[applying] Rector\CodeQuality\Rector\If_\ConsecutiveNullCompareReturnsToNullCoalesceQueueRector
[applying] Rector\CodeQuality\Rector\If_\SimplifyIfIssetToNullCoalescingRector
[applying] Rector\CodeQuality\Rector\If_\ExplicitBoolCompareRector
[applying] Rector\CodeQuality\Rector\If_\CombineIfRector
[applying] Rector\CodeQuality\Rector\If_\ShortenElseIfRector
[applying] Rector\CodeQuality\Rector\If_\SimplifyIfNullableReturnRector
[applying] Rector\Php70\Rector\If_\IfToSpaceshipRector
[applying] Rector\CodeQuality\Rector\Identical\SimplifyConditionsRector
[applying] Rector\CodeQuality\Rector\BooleanNot\SimplifyDeMorganBinaryRector
[applying] Rector\CodeQuality\Rector\Identical\BooleanNotIdenticalToNotIdenticalRector
[applying] Rector\CodingStyle\Rector\FuncCall\CountArrayToEmptyArrayComparisonRector
[applying] Rector\CodeQuality\Rector\Concat\JoinStringConcatRector
[applying] Rector\Php71\Rector\BinaryOp\BinaryOpBetweenNumberAndStringRector
PHP Fatal error:  Uncaught TypeError: PHPStan\Reflection\ReflectionProvider\MemoizingReflectionProvider::hasClass(): Argument #1 ($className) must be of type string, int given, called in {projectDir}/vendor/rector/rector/packages/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php on line 109 and defined in phar://{projectDir}/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/MemoizingReflectionProvider.php:25
Stack trace:
#0 {projectDir}/vendor/rector/rector/packages/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php(109): PHPStan\Reflection\ReflectionProvider\MemoizingReflectionProvider->hasClass()
#1 {projectDir}/vendor/rector/rector/packages/NodeCollector/NodeAnalyzer/ArrayCallableMethodMatcher.php(68): Rector\NodeCollector\NodeAnalyzer\ArrayCallableMethodMatcher->resolveClassConstFetchType()
#2 {projectDir}/vendor/rector/rector/rules/CodeQuality/Rector/Array_/CallableThisArrayToAnonymousFunctionRector.php(96): Rector\NodeCollector\NodeAnalyzer\ArrayCallableMethodMatcher->match()
#3 {projectDir}/vendor/rector/rector/src/Rector/AbstractRector.php(254): Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector->refactor()
#4 {projectDir}/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113): Rector\Core\Rector\AbstractRector->enterNode()
#5 {projectDir}/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode()
#6 {projectDir}/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray()
#7 {projectDir}/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133): PhpParser\NodeTraverser->traverseNode()
#8 {projectDir}/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode()
#9 {projectDir}/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray()
#10 {projectDir}/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode()
#11 {projectDir}/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray()
#12 {projectDir}/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode()
#13 {projectDir}/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray()
#14 {projectDir}/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode()
#15 {projectDir}/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray()
#16 {projectDir}/vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(46): PhpParser\NodeTraverser->traverse()
#17 {projectDir}/vendor/rector/rector/src/Application/FileProcessor.php(53): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
#18 {projectDir}/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(162): Rector\Core\Application\FileProcessor->refactor()
#19 {projectDir}/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(175): Rector\Core\Application\FileProcessor\PhpFileProcessor->Rector\Core\Application\FileProcessor\{closure}()
#20 {projectDir}/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(161): Rector\Core\Application\FileProcessor\PhpFileProcessor->tryCatchWrapper()
#21 {projectDir}/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(106): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors()
#22 {projectDir}/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(65): Rector\Core\Application\FileProcessor\PhpFileProcessor->process()
#23 {projectDir}/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(51): Rector\Core\Application\ApplicationFileProcessor->processFiles()
#24 {projectDir}/vendor/rector/rector/src/Console/Command/ProcessCommand.php(121): Rector\Core\Application\ApplicationFileProcessor->run()
#25 {projectDir}/vendor/rector/rector/vendor/symfony/console/Command/Command.php(262): Rector\Core\Console\Command\ProcessCommand->execute()
#26 {projectDir}/vendor/rector/rector/vendor/symfony/console/Application.php(828): RectorPrefix20210630\Symfony\Component\Console\Command\Command->run()
#27 {projectDir}/vendor/rector/rector/vendor/symfony/console/Application.php(255): RectorPrefix20210630\Symfony\Component\Console\Application->doRunCommand()
#28 {projectDir}/vendor/rector/rector/src/Console/ConsoleApplication.php(67): RectorPrefix20210630\Symfony\Component\Console\Application->doRun()
#29 {projectDir}/vendor/rector/rector/vendor/symfony/console/Application.php(153): Rector\Core\Console\ConsoleApplication->doRun()
#30 {projectDir}/vendor/rector/rector/bin/rector.php(47): RectorPrefix20210630\Symfony\Component\Console\Application->run()
#31 {projectDir}/vendor/rector/rector/bin/rector(5): require_once('...')
#32 {main}
thrown in phar://{projectDir}/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/MemoizingReflectionProvider.php on line 25

```

**Comment by TomasVotruba** [comment]
That's a good approach :+1: 

<br>

The last running rule seems `BinaryOpBetweenNumberAndStringRector`

image


To be sure what rule it is, I always run exactly 1 rule in `rector.php`. Using [narrow scoping](https://tomasvotruba.com/blog/2021/02/01/effective-debug-tricks-narrow-scoping/).

That way I know which rule cause the error 100 %

**Comment by stephanvierkant** [comment]
I've created a fixture in `rules-tests/Php71/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/Fixture`, but even that test isn't failing. I really don't know.

**Comment by TomasVotruba** [comment]
How do you know its the responsible rule? What is in your `rector.php`? 
There should be only 1 rule and Rector should be failing.

**Comment by stephanvierkant** [comment]
I don't know which rules is causing this issue. See https://getrector.org/demo/1ebdd6d7-d305-6bfa-aa66-e9270fcce247 for an example: it looks like `CallableThisArrayToAnonymousFunctionRector` is causing this issue, but I can't reproduce it in this repo.

**Comment by TomasVotruba** [comment]
Try it locally first, before sending and demo/PR tests.
Your `rector.php` must contain only 1 rule and `vendor/bin/rector` must fail. 

Without knowing responsible rule, this is like shooting in a dark :)

**Pull request closed without merging**
