### PR TITLE
ExplicitMethodCallOverMagicGetSetRector fix

### PR DESCRIPTION
**Pull request by MartinMystikJonas**
Fix for https://github.com/rectorphp/rector/issues/7325

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks! Could you add the failing test fixture, so we have feature covered?

**Comment by MartinMystikJonas** [comment]
@TomasVotruba I can try

**Comment by MartinMystikJonas** [comment]
OK it seems fix would be more complicated than I thought. For objects with magic methods `hasProperty` always returns `maybe` so we cannot check for property existence

**Comment by MartinMystikJonas** [comment]
I see three options:

1) Use try/catch and skip rule if `getProperty` fails
2) Skip rule even for `hasProperty()->maybe()`
3) apply rule even for unknown properties by ignoring impossible check of types by 

```
if (! $propertyType->isSuperTypeOf($returnType)->yes()) {
    continue;
}
```
because it is only place where it is used.

I would go for option 2 but I am not sure it is right way.

**Comment by TomasVotruba** [comment]
> I would go for option 2 but I am not sure it is right way.

Seems the most valid way :+1: 

How the test perform with this solution?

**Comment by MartinMystikJonas** [comment]
Pushed option 2. Old tests passes and new test works with this.

**Comment by TomasVotruba** [comment]
LGTM :+1:  Thank you

**Pull request merged**
