### PR TITLE
[PostRector] Remove CurrentFileProvider on PostFileProcessor

### PR DESCRIPTION
**Pull request by samsonasik**
Directly pass file name from FileProcessor.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
This also reduce repetitive `$file->getFilePath()` 👍

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Looks good :clap:

**Pull request merged**
