### PR TITLE
[TypeDeclaration] Handle infinite loop on type recursive itself on ReturnTypeFromStrictTypedCallRector

### LINKED ISSUE #7846: stuck on some code
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.17  |
| PHP version | 8.1.15 |

Code check takes an infinitely long time, even with the --dry-run option

## Minimal PHP Code Causing Issue

https://getrector.com/demo/73b798f8-7b03-48a7-a158-f29d96a7ae10

## Expected Behaviour

Expected any output to the console in a reasonable amount of time (for example, a message about recursion)

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7846

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @pilot114

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Comment by pilot114** [comment]
awesome, thnx

**Pull request merged**
