### PR TITLE
[Tests] Speed up tests with brianium/paratest

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
**Before on rules-tests** 

Screen Shot 2021-07-30 at 20 45 41

ref https://github.com/rectorphp/rector-src/runs/3200977790?check_suite_focus=true#step:5:58

**After on rules-tests**

Screen Shot 2021-07-30 at 21 14 47

ref https://github.com/rectorphp/rector-src/pull/551/checks?check_run_id=3202468751#step:5:60

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review. I think it improve speed tests.

**Comment by samsonasik** [comment]
Tested locally.

**Before** ( from PR https://github.com/rectorphp/rector-src/pull/539#issuecomment-888931949 ) which uses swap already.

Screen Shot 2021-07-30 at 21 19 06

**After** (now with paratest)

Screen Shot 2021-07-30 at 21 18 25

**Comment by TomasVotruba** [comment]
Thanks for the improvement!

How can we get on the CI the same speed you have locally? Seems the initial time is locally even higher and gets lower.

It seems your local run has some bug. 38 MB per full tests suite is impossible number.

**Comment by samsonasik** [comment]
I am not sure about that, possibly need PR https://github.com/rectorphp/rector-src/pull/550 for that, actualy, it previously different is 1 minute+ on CI:

up

 which I force push for retry auto-number of processes, which make it slower, so I rolled back.
 
 The memory calculation PHP process seems like average number, I actually have it splitted for multi php process:
  
Screen Shot 2021-07-30 at 21 33 19

which if I count, it calculated as 785.29 MB, which very little compared to 10.35GB

**Comment by samsonasik** [comment]
Let's try only run paratest on rules-tests which take longest time.

**Comment by samsonasik** [comment]
Using `--runner=WrapperRunner` with 4 processes seems faster 🎉 

```bash
Time: 02:47.928
```

Let's try back p8

**Comment by samsonasik** [comment]
Using `p8` with `--runner=WrapperRunner` seems error, let's try `p6`, if still error, we will use `p4` as fast enough.

**Comment by samsonasik** [comment]
`p6` seems slower than `p4`, let's back to `p4`

**Comment by samsonasik** [comment]
@TomasVotruba we now get 2 minutes 48 seconds with `-p4 --runner=WrapperRunner`

Screen Shot 2021-07-30 at 23 15 58

ref https://github.com/rectorphp/rector-src/runs/3203715907#step:5:60

I think it is ready 🎉 🎉 🎉

**Comment by TomasVotruba** [comment]
> p6 seems slower than p4, let's back to p4

Thanks for investigation of the ideal number! This is very handy :+1: 

Could you add a comment about your investigation to the workflow file? Just in case someone would love to use as many cores as possible.

**Comment by samsonasik** [comment]
Comment added https://github.com/rectorphp/rector-src/pull/551/commits/d9339839e4d3a661f6599b364bcd80fd863322df

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by staabm** [comment]
Great job!

> How can we get on the CI the same speed you have locally? Seems the initial time is locally even higher and gets lower.

i had the same peoblems locally. Running tests more then once is faster because of caches beeing built in the background and re-used on subsequent runs.

we can get this kind of speed only by re-storing caches between ci-jobs. But this could also harm re-produciability or introduce hard to debug/re-produce bugs

**Pull request merged**
