### PR TITLE
[CodeQuality] Handle crash attribute used on trait on CallableThisArrayToAnonymousFunctionRector

### LINKED ISSUE #7303: System error: Scope not available
Got the following error:
```
michael@michael-HP-EliteBook-830-G5:/var/www/facdocs$ vendor/bin/rector --dry-run
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 [ERROR] Could not process "src/Entity/MultiTenenacy/HasPublicIdTrait.php" file, due to:
         "System error: "Scope not available on "PhpParser\Node\Expr\Array_" node with parent node of
         "PhpParser\Node\Arg", but is required by a refactorWithScope() method of
         "Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector" rule. Fix scope refresh on
         changed nodes first"
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On
         line: 47


michael@michael-HP-EliteBook-830-G5:/var/www/facdocs$
```

Class in question is below and error is caused by adding the attribute the trait.
```php
<?php

declare(strict_types=1);

namespace App\Entity\MultiTenenacy;

use Doctrine\ORM\Mapping as ORM;


#[ORM\UniqueConstraint(columns: ['public_id', 'tenant_id'])]
trait HasPublicIdTrait
{
}
```

Output with --debug:
```
michael@michael-HP-EliteBook-830-G5:/var/www/facdocs$ vendor/bin/rector --dry-run --debug
src/Entity/MultiTenenacy/HasPublicIdTrait.php
[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Php74\Rector\LNumber\AddLiteralSeparatorToNumberRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Assign\RemoveDoubleAssignRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Renaming\Rector\Name\RenameClassRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Php81\Rector\Array_\FirstClassCallableRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\Php54\Rector\Array_\LongArrayToShortArrayRector

[file] src/Entity/MultiTenenacy/HasPublicIdTrait.php
[rule] Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector



 [ERROR] Could not process "src/Entity/MultiTenenacy/HasPublicIdTrait.php" file, due to:
         "System error: "Scope not available on "PhpParser\Node\Expr\Array_" node with parent node of "PhpParser\Node\Arg", but
         is required by a refactorWithScope() method of
         "Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector" rule. Fix scope refresh on changed nodes
         first"

         Stack trace:
         #0 vendor/rector/rector/src/Rector/AbstractRector.php(210): Rector\Core\Rector\AbstractScopeAwareRector->refactor()
         #1 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):
         Rector\Core\Rector\AbstractRector->enterNode()
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #9 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray()
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode()
         #11 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):
         PhpParser\NodeTraverser->traverseArray()
         #12 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42): PhpParser\NodeTraverser->traverse()
         #13 vendor/rector/rector/src/Application/FileProcessor.php(61):
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse()
         #14 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(126):
         Rector\Core\Application\FileProcessor->refactor()
         #15 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(93):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors()
         #16 vendor/rector/rector/packages/Parallel/WorkerRunner.php(99):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process()
         #17 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}()
         #18 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(110):
         RectorPrefix202207\Evenement\EventEmitter->emit()
         #19 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         RectorPrefix202207\Clue\React\NDJson\Decoder->handleData()
         #20 vendor/rector/rector/vendor/react/stream/src/Util.php(62): RectorPrefix202207\Evenement\EventEmitter->emit()
         #21 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         RectorPrefix202207\React\Stream\Util::RectorPrefix202207\React\Stream\{closure}()
         #22 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):
         RectorPrefix202207\Evenement\EventEmitter->emit()
         #23 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):
         RectorPrefix202207\React\Stream\DuplexResourceStream->handleData()
         #24 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):
         RectorPrefix202207\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
         #25 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):
         RectorPrefix202207\React\EventLoop\StreamSelectLoop->run()
         #26 vendor/rector/rector/vendor/symfony/console/Command/Command.php(307):
         Rector\Core\Console\Command\WorkerCommand->execute()
         #27 vendor/rector/rector/vendor/symfony/console/Application.php(891):
         RectorPrefix202207\Symfony\Component\Console\Command\Command->run()
         #28 vendor/rector/rector/vendor/symfony/console/Application.php(310):
         RectorPrefix202207\Symfony\Component\Console\Application->doRunCommand()
         #29 vendor/rector/rector/src/Console/ConsoleApplication.php(49):
         RectorPrefix202207\Symfony\Component\Console\Application->doRun()
         #30 vendor/rector/rector/vendor/symfony/console/Application.php(208): Rector\Core\Console\ConsoleApplication->doRun()
         #31 vendor/rector/rector/bin/rector.php(128): RectorPrefix202207\Symfony\Component\Console\Application->run()
         #32 vendor/rector/rector/bin/rector(5): require_once('...')
         #33 vendor/bin/rector(120): include('...')
         #34 {main}". On line: 47


michael@michael-HP-EliteBook-830-G5:/var/www/facdocs$
```

### PR DESCRIPTION
**Pull request by samsonasik**
It currently make crash:

```bash
There was 1 error:

1) Rector\Tests\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector\CallableThisArrayToAnonymousFunctionRectorTest::test with data set #9 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\ShouldNotHappenException: Scope not available on "PhpParser\Node\Expr\Array_" node with parent node of "PhpParser\Node\Arg", but is required by a refactorWithScope() method of "Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector" rule. Fix scope refresh on changed nodes first
```

Fixes https://github.com/rectorphp/rector/issues/7303

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @NotionCommotion

**Comment by samsonasik** [comment]
PHPStan relative path notice is unrelated:

```bash

 ------------------------------------------------------------------------
  bin/rector.php:72
 ------------------------------------------------------------------------
  - '#Relative file path "vendor/autoload\.php" is not allowed, use absolute one with __DIR__#'
 ```

I added to ignoreErrors list.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
