### PR TITLE
[EarlyReturn] Skip else has inline html on RemoveAlwaysElseRector

### LINKED ISSUE #7441: Incorrect behavior of RemoveAlwaysElseRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/eb0f5c8f-86e3-40ed-bb38-86675496f0c8

```php
<?php

final class DemoFile
{
    public function run()
    {
        if ( rand( 0, 5 ) > 2 ) {
 	       return;
		} else { ?>
			this is <?php echo "hello"; ?> world
		<?php }
    }
}
```

### Responsible rules

* `RemoveAlwaysElseRector`

## Expected Behavior

Not create a fatal error

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #2867 Fixes https://github.com/rectorphp/rector/issues/7441

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
🥳

**Comment by kkmuffme** [comment]
Afaik this is wrong, bc now it does nothing, even though this could easily be optimized.
From:
https://getrector.org/demo/8ddb0bc5-8835-4c7a-bd2c-fe60b908282e
to:
https://getrector.org/demo/9b1b3305-acf9-4a08-a295-c4880cfd3f9a

**Comment by samsonasik** [comment]
Feel free to provide patch if you have different solution :)

Pada tanggal Sen, 5 Sep 2022 10.43, kkmuffme ***@***.***>
menulis:

**Comment by samsonasik** [comment]
Feel free to provide patch if you have different solution :)

**Comment by kkmuffme** [comment]
Just brainstorming: if there are any PHP closing/opening tags we just need to keep them instead of removing them?

Is there a way on the "demo" to load an older version of rector, to play around with the rule so I can check various cases?

**Comment by samsonasik** [comment]
Rector is using nikic/php-parser, which replacing html+php may overap the index.

Still, feel free to provide patch if you found a solution, otherwise, you can use `$rectorConfig->skip()` option to skip the rule.

Feel free to contribute by create PR to https://github.com/rectorphp/getrector.org if you have want to provide PR to improve demo page.

**Comment by kkmuffme** [comment]
How about we just report it instead of auto-fixing it?

**Pull request merged**
