### PR TITLE
Performance: Early return in PhpDocNode refactoring for class renames

### PR DESCRIPTION
**Pull request by keulinho**
Another micro optimization bringing ~3% in our case: https://blackfire.io/profiles/compare/92f9a385-14c9-496c-8351-7be1d348e0bf/graph

image

### CODE REVIEW

**Review by samsonasik — CHANGES_REQUESTED** [review]
The origNode only be updated after node refactored, so it may be overlapped with "just updated" node.

"origNode" attribute usually used to verify node just reprinted.

I think it should be node, if it broke the test, something may happen in the middle.

**Comment by keulinho** [comment]
Using node does not work here, because of your internal caching in `\Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfoFactory::createFromNode` 

Because there you cache the phpDocInfo by node, even if the node by have changed:
```php
        $objectHash = spl_object_hash($node);
        if (isset($this->phpDocInfosByObjectHash[$objectHash])) {
            return $this->phpDocInfosByObjectHash[$objectHash];
        }
```

What happened in the case of the failed test was:
1. the return type of the method was renamed and the doc comment removed
2. the refactor php doc was called and it was running into the early return because the changed node doesn't have a doc comment anymore, thus the doc comment was removed instead of changed to the new class name

The current implementation in the class renamer relies on the following workflow:
1. The return type is renamed and doc comment removed
2. The `createFromNodeOrEmpty` call returns the phpDocInfo the node had **before** step 1 (because of the caching)
3. then the doc comment was correctly changed

As the code currently relies on the underlying caching mechanism i didn't want to change the behaviour of how that all works to much

My current approach here is that when a node did not have a doc comment in the original source code, it also never needs to be refactored so we can do a early return here which is a lot faster, so i think checking the original node is a valid approach

Does that make sense?

**Comment by samsonasik** [comment]
I will let @TomasVotruba decide on this then

**Comment by TomasVotruba** [comment]
The code is very hard to read and understand. 
I'm sure well remove it in the future, even with comments.

We can improve the performance here, but I'd prefer more clear and self-explanatory code.

**Comment by keulinho** [comment]
I clearified the code by extracting the multiple if check to it's own method and gave it a better name and added some explanatory comments

**Comment by TomasVotruba** [comment]
Thanks for the update, this looks good :+1:

**Comment by samsonasik** [comment]
@keulinho @TomasVotruba it cause error in latest main tests unfortunatelly, it needs to be reverted

https://github.com/rectorphp/rector-src/actions/runs/4902565356/jobs/8754485599#step:5:78

**Comment by TomasVotruba** [comment]
I see :+1:  Thanks @samsonasik

**Pull request merged**
