### PR TITLE
Add failing test fixture for `RemoveUnusedPrivatePropertyRector`

### PR DESCRIPTION
**Pull request by leighman**

### CODE REVIEW

**Comment by leighman** [comment]
https://getrector.org/demo/06ba00ff-38bb-4c35-add7-775f20e6cd7b
Another similar case

**Comment by samsonasik** [comment]
It seems split multi assign can be extracted with `SplitDoubleAssignRector`

https://github.com/rectorphp/rector-src/blob/53013b6a2956a04fdec16a32b34f8c54f188b23f/rules/CodingStyle/Rector/Assign/SplitDoubleAssignRector.php#L19

so this need to be skipped, let the `SplitDoubleAssignRector` extract assign first, then the assign can be safely removed.

**Comment by leighman** [comment]
Thanks for the pointer.
The example in the link is still a bug, I think.
The possibly-side-effecting function should be preserved as with unused variable.

**Comment by TomasVotruba** [comment]
@leighman Yes, this rule should evaluate variable as used one.

**Comment by samsonasik** [comment]
Your example in the link seems different use case for assign with side effect.

@leighman I created PR https://github.com/rectorphp/rector-src/pull/1944 for this case first, the multi assign need to be skipped for RemoveUnusedPrivatePropertyRector, then let SplitDoubleAssignRector if need to extract, run twice will make it safely removed.

**Pull request closed without merging**
