### PR TITLE
Fix some minor misprints

### PR DESCRIPTION
**Pull request by bocharsky-bw**

### CODE REVIEW

**Comment by samsonasik** [comment]
Thank you @bocharsky-bw

**Comment by TomasVotruba** [comment]
@bocharsky-bw Hi Victor, btw, do you need some help with acomodation or transfer to the west? I can help with something in Prague.

**Comment by bocharsky-bw** [comment]
Hi @TomasVotruba , thank you for asking! Personally, I don't need any help right now. We stay in Ukraine because I can't leave the country due to the military state here. I hope Ukraine will win and this all will end soon.

Cheers!

**Comment by TomasVotruba** [comment]
@bocharsky-bw I'm glad to hear you're safe. 

> I hope Ukraine will win and this all will end soon.

I hope in this scenario too :muscle: :+1: 

Just in case something escaltes or somebody close to you will need help from Czechia, don't hesitate to ping me on https://tomasvotruba.com/contact
I'll help.

**Comment by bocharsky-bw** [comment]
@TomasVotruba Thank you a lot! ❤️

**Pull request merged**
