### PR TITLE
[Core] Fixes Cache in FilesFinder

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6389
Closes https://github.com/rectorphp/rector/pull/6398

### CODE REVIEW

**Comment by samsonasik** [comment]
needs re-check on `FilesFinder` after rebase.

**Comment by samsonasik** [comment]
@TomasVotruba it is implemented. Rules test error seems unrelated as happen in `main` branch as well.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by TomasVotruba** [comment]
Fixed in https://github.com/rectorphp/rector-src/pull/270

**Pull request merged**
