### PR TITLE
Failing test for `SwitchNegatedTernaryRector` + `RemoveDeadInstanceOfRector`

### PR DESCRIPTION
**Pull request by Androbin**
# Failing Test for SwitchNegatedTernaryRector

Based on https://getrector.org/demo/aa60d2e0-33c8-4f1b-b01f-cff35ff084ff

### CODE REVIEW

**Comment by Androbin** [comment]
See https://github.com/rectorphp/rector/issues/6480

**Comment by Androbin** [comment]
@TomasVotruba How to set up a test that depends on two rectors?

**Comment by TomasVotruba** [comment]
> @TomasVotruba How to set up a test that depends on two rectors?

We put them both in `rector.php` config.

Here is nice example of such test: https://github.com/rectorphp/rector-src/tree/main/tests/Issues/Issue6420

**Comment by samsonasik** [comment]
@Androbin I cherry-picked your commit at PR https://github.com/rectorphp/rector-src/pull/201

**Pull request closed without merging**
