### PR TITLE
Add failing test fixture for AnnotationToAttributeRector

### PR DESCRIPTION
**Pull request by stephanvierkant**
See https://github.com/rectorphp/rector-src/pull/225#issuecomment-861237156

### CODE REVIEW

**Comment by stephanvierkant** [comment]
Well, that wasn't expected. I'll wait for an updated demo site so I can figure out what's going wrong.

**Comment by TomasVotruba** [comment]
There is only entry code. What should happen with it?

The test passing correctly as expected now.

**Comment by stephanvierkant** [comment]
Nothing should happen. But in my application, the Gedmo annotation is replaced by a Doctrine Table attribute.

**Comment by samsonasik** [comment]
Checked in https://getrector.org/demo/7c620883-1cb9-4fec-a687-41f96e632acf and it seems working as expected, @stephanvierkant could you try verify if latest version fixed it?

**Comment by stephanvierkant** [comment]
Nope. I've updated the test.

edit: aha, file was in wrong directory.

**Comment by stephanvierkant** [comment]
Hmm, don't understand why this test isn't failing. See https://getrector.org/demo/82b952ab-c4e1-4fab-a9d2-6781816db1cc

**Comment by TomasVotruba** [comment]
Maybe add some code to actually make the fixture change. E.g. `@Entity` instead of `#[Entity]`

**Comment by stephanvierkant** [comment]
I don't get it. In the demo I can reproduce it, but I can't with this test.

**Comment by TomasVotruba** [comment]
Do you have the same version?
https://github.com/rectorphp/getrector.org/commit/a818cb8e1bd9d9d0adeb8ddf63656a4e8d817146

This repository is more up to date, so it has higher priority.

**Comment by stephanvierkant** [comment]
I don't know what you mean. I'm using the demo site?

**Comment by TomasVotruba** [comment]
See the demo site version: https://github.com/rectorphp/getrector.org/commit/a818cb8e1bd9d9d0adeb8ddf63656a4e8d817146

Is it the same that tests are running on?

**Comment by stephanvierkant** [comment]
I'm using the online demo site here: https://getrector.org/demo/82b952ab-c4e1-4fab-a9d2-6781816db1cc.

**Comment by TomasVotruba** [comment]
Good :+1: 

I talk about the version is uses. You can find it here: https://github.com/rectorphp/getrector.org/blob/main/composer.lock

In short, it works in tests, so it works in Rector. The demo is behind this repository and should not be used for testing.

@samsonasik Could we automated updates of version on daily basis to avoid these confusions?
Ideally with some automerge, so we don't have an extra work with it everyday :)

**Comment by TomasVotruba** [comment]
Closing as test passes as expected :+1:

**Comment by samsonasik** [comment]
@TomasVotruba I created PR https://github.com/rectorphp/getrector.org/pull/382 for that.

**Pull request closed without merging**
