### PR TITLE
[DeadCode] Skip remove variable on switch use return after break on RemoveUnusedVariableAssignRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
final class SkipRemoveVariableOnNextReturnAfterBreakInCase
{
    public function run($a)
    {
        switch ($a)
        {
            case 'A':
                $x = 'a';
                break;
                return;
        }

        echo $x;
    }
}
```

The assignment of `$x = 'a'` is removed:

```diff
             case 'A':
-                $x = 'a';
```

which should not, as `$x` is used, ref https://3v4l.org/9llPU

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
Fixed 🎉, for `return` removal itself, the `RemoveUnreachableStatementRector` already handle it https://github.com/rectorphp/rector-src/pull/2145/commits/9ed7c879163dc2af9562cda7ca77e5c7f08aef7b

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
👍

**Pull request merged**
