### PR TITLE
Add failing test fixture for TypedPropertyRector

### PR DESCRIPTION
**Pull request by YetiCGN**
Based on https://getrector.org/demo/1ec4dd88-537f-662e-b7b2-df863ca6ed34

### CODE REVIEW

**Comment by samsonasik** [comment]
it already covered at latest main with the similar fixture use case:

https://github.com/rectorphp/rector-src/blob/76e0c15e4888980a4f8f4db53915a9b98d110e13/rules-tests/Php74/Rector/Property/TypedPropertyRector/FixtureClassLikeTypeOnly/nulllable_collection.php.inc#L36

Your fixture has invalid extension so it cause invalid test result.

I tried your fixture locally and it is working ok, please use latest rector version. 

Demo site is not using latest rector version, or may need a real class name exists when dealing with external class.

**Comment by YetiCGN** [comment]
Did you check the difference between `$users` and `$moodImage` in my example https://getrector.org/demo/1ec4d5b4-8951-6fd0-ae3f-410987af81e1? 

I think the "add" and "remove" methods are confusing Rector for which your test case doesn't provide coverage. See https://github.com/rectorphp/rector/issues/6832#issuecomment-978935450

**Comment by samsonasik** [comment]
Please provide new failing test case so we can take a look, please also run the test locally first to avoid double check.

**Comment by YetiCGN** [comment]
I think I have provided enough information for you to be able to fix this bug in your code.

**Comment by TomasVotruba** [comment]
@YetiCGN Looks like the CI failed not for the incorrect Rector change, but for other reasons https://github.com/rectorphp/rector-src/runs/4332006436?check_suite_focus=true#step:5:69
It should be fixed before review.

**Comment by YetiCGN** [comment]
> @YetiCGN Looks like the CI failed not for the incorrect Rector change, but for other reasons https://github.com/rectorphp/rector-src/runs/4332006436?check_suite_focus=true#step:5:69 It should be fixed before review.

Ouch. I missed the file extension. Had "bug6832.php.inc" correctly before, then decided to rename it but PhpStorm must have dropped the ".php" and I didn't see it. Fixed!

**Comment by TomasVotruba** [comment]
Can you push it? I can't see it here.

**Comment by samsonasik** [comment]
@YetiCGN as I said, I already tried your fixture locally, it already covered, then if you have different use case, please create new pull request with new test case.

**Pull request closed without merging**
