### PR TITLE
[Arguments] Allow no default value on ArgumentAdderRector

### LINKED ISSUE #8350: can't set a new parameter to have no default value
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |0.18.12            |

## Minimal PHP Code Causing Issue

There doesn't seem to be a way to add a new method or function parameter without a default value. E.g.

```
    $rectorConfig->ruleWithConfiguration(
      ArgumentAdderRector::class,
      [
        new ArgumentAdder(
          $class,
          'addToGeneratorDefinition',
          0,
          'definition',
          NULL,
          new ObjectType(PropertyDefinition::class),
        ),
      ],
    );
```

produces this change:

```
-  public static function addToGeneratorDefinition(): PropertyDefinition {
+  public static function addToGeneratorDefinition(PropertyDefinition $definition = null): PropertyDefinition {
```

If I remove the type and the NULL like this:

```
    $rectorConfig->ruleWithConfiguration(
      ArgumentAdderRector::class,
      [
        new ArgumentAdder(
          $class,
          'addToGeneratorDefinition',
          0,
          'definition',
        ),
      ],
    );
```

 it still gets a default:

```
-  public static function addToGeneratorDefinition(): PropertyDefinition {
+  public static function addToGeneratorDefinition($definition = null): PropertyDefinition {
```

### PR DESCRIPTION
**Pull request by samsonasik**
@joachim-n this should handle https://github.com/rectorphp/rector/issues/8350
Closes https://github.com/rectorphp/rector/issues/8350

with add `ArgumentAdderWithoutDefaultValue` value object for it.

### CODE REVIEW

**Comment by samsonasik** [comment]
@joachim-n it is implemented 🎉 

For note, since no default value configured via `ArgumentAdderWithoutDefaultValue`, it can't fill gap on method call or static call, eg:

```
$obj = new SomeClass();
$obj->execute(); // can't fill here with default value.
```

as no value to refer since value is always required, so you need to fill manually yourself on the method call or static call after it fill the method itself.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Looks good, thank you :+1:

**Comment by samsonasik** [comment]
@TomasVotruba  @joachim-n I am thinking that default value for method/static call is still needed, to init the method arg after parameter added, I guess it can be:

```diff
$obj = new SomeClass();
-$obj->execute();
+$obj->execute([]);
```

so fatal error won't be shown, to differentiate, we probably need `defaultArgOnCall` property, wdyt?

**Pull request merged**
