### PR TITLE
[Core] Apply Scope refresh for Namespace_ and FileWithoutNamespace

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
implemented 🎉 with check:

- has no `Scope` 
- Node is `Namespace_` or `FileWithoutNamespace`

then fallback to use Scope from ScopeFactory:

```php
$mutatingScope = $this->scopeFactory->createFromFile($smartFileInfo);
```

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
I wonder, there should be also some test to cover this fix. To make sure it will not be regressed in the future.

**Comment by samsonasik** [comment]
The test already exists, when only unregister `Namespace_` and `FileWithoutNamespace`, it will got error:

```bash

There were 4 errors:
1) Rector\Tests\PSR4\Rector\FileWithoutNamespace\NormalizeNamespaceByPSR4ComposerAutoloadRector\NormalizeNamespaceByPSR4ComposerAutoloadRectorTest::test with data set #3 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\ShouldNotHappenException: Node "PhpParser\Node\Stmt\Namespace_" with parent of "" is missing scope required for scope refresh.
```

https://github.com/rectorphp/rector-src/runs/7058239145?check_suite_focus=true#step:5:87

On first commit https://github.com/rectorphp/rector-src/pull/2569/commits/e5941ba08aa5a851c4256ff29b439e276d77a9f9

**Comment by TomasVotruba** [comment]
I see it now, thank you :+1:

**Pull request merged**
