### PR TITLE
 [e2e] Add e2e parent is BinaryOp from FuncCall with No Scope 

### PR DESCRIPTION
**Pull request by samsonasik**
Continue of https://github.com/rectorphp/rector-src/pull/2495, add handling on parent is BinaryOp from FuncCall with no scope.

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed :tada: with check:

- is UnreachableNode node?
- if yes, lookup parent Node until the Scope attribute value is a Scope instance https://github.com/rectorphp/rector-src/pull/2500/commits/7e4b79425a83c889cb3ba5604dfb84db4f426692

**Comment by samsonasik** [comment]
I tried downgrade script and it cause error:

```bash
 3438/3438 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
                                                                                                                        
 [ERROR] Could not process "rector-build/vendor/react/event-loop/src/Loop.php" file, due to:                            
         "System error: "Scope not available on "PhpParser\Node\Expr\FuncCall" node with parent node of                 
         "PhpParser\Node\Expr\Assign", but is required by a refactorWithScope() method of                               
         "Rector\DowngradePhp81\Rector\FuncCall\DowngradeArrayIsListRector" rule. Fix scope refresh on changed nodes    
         first"                                                                                                         
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
         line: 43                                                                                                       
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "rector-build/vendor/symfony/contracts/Service/ServiceLocatorTrait.php" file, due to:        
         "System error: "Scope not available on "PhpParser\Node\Expr\FuncCall" node with parent node of                 
         "PhpParser\Node\Stmt\Return_", but is required by a refactorWithScope() method of                              
         "Rector\DowngradePhp81\Rector\FuncCall\DowngradeArrayIsListRector" rule. Fix scope refresh on changed nodes    
         first"                                                                                                         
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
         line: 43   
```

Let's rollback the guard so we can continue to next iteration check https://github.com/rectorphp/rector-src/pull/2500/commits/7b5e0facf40d71df994911fcffb7108569f0c56f

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
rebased.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
