### PR TITLE
[Core][DeadCode] Skip remove Node as Stmt when has @phpstan-ignore-next-line on DeadCode rules

### PR DESCRIPTION
**Pull request by samsonasik**
Rector is based on phpstan, so if phpstan mark the statement as ignored to be check, I think the stmt should not be removed, eg:

```php
final class SkipUsePhpstanIgnoreNextLine
{
    // @phpstan-ignore-next-line
    public function run()
    {
    }

    /**
     * @phpstan-ignore-next-line
     */
    public function run2()
    {
    }
}
```

with applied rule : `RemoveEmptyClassMethodRector`, it should be skipped.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
👍

**Comment by samsonasik** [comment]
I applied check only when rule start with `Rector\DeadCode` to avoid invalid transformation, eg: on Downgrade strict declaration https://github.com/rectorphp/rector-src/pull/2484/files#diff-aa078dfd3fb4ea1cb991a8a17c40c0ee5151a5530566750e0c10f08bc7216e14 which need to make compatible with previous version.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
Closing for now, it possibly may cause issue when one stmt not removed, but not other.

**Pull request closed without merging**
