### PR TITLE
[Core] Override pModifiers() method to set final and abstract modifiers early on BetterStandardPrinter

### PR DESCRIPTION
**Pull request by samsonasik**
ref https://github.com/rectorphp/rector/issues/6963
ref https://github.com/nikic/PHP-Parser/pull/826

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1: 

cc @Bl00D4NGEL

**Comment by Bl00D4NGEL** [comment]
Do we want to keep track of when this is merged in PHP Parser and remove the override in rector?

**Comment by TomasVotruba** [comment]
Not necessary, there is not that many news in php-parser, and this will be coming only in a BC break version, like 5.0. So we won't miss it :)

I'm just thinking about `readonly`, if it's in a `final`, `abstract` family, or the last 3rd group.

**Pull request merged**
