### PR TITLE
Bump to Symfony 6.2

### PR DESCRIPTION
**Pull request by TomasVotruba**
- require symfony 6.2
- use Symfony 6.2 generic config patcher

### CODE REVIEW

**Comment by samsonasik** [comment]
packages-tests workflow need updato to remove this lines

https://github.com/rectorphp/rector-src/blob/22b612ef79a1437b891d94154285ad4a2a3e0576/.github/workflows/packages_tests.yaml#L53-L54

**Comment by TomasVotruba** [comment]
Let's see how it goes :)

**Comment by samsonasik** [comment]
@TomasVotruba it seems cause error on downgrade build:

```
Run php -d memory_limit=-1 bin/rector process rector-build/bin rector-build/config rector-build/src rector-build/packages rector-build/rules rector-build/vendor --config build/config/config-downgrade.php --ansi --no-diffs

   20/2989 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
  300/2989 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]  10%
  900/2989 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  30%
 1460/2989 [▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░]  48%
 2100/2989 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░]  70%
 2640/2989 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░]  88%
 2900/2989 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░]  97%

                                                                                
 [ERROR] Could not process                                                      
         "/home/runner/work/rector-src/rector-src/rector-build/vendor/symfony/de
         pendency-injection/ParameterBag/ParameterBag.php" file, due to:        
         "System error:                                                         
         "Rector\PHPStanStaticTypeMapper\PHPStanStaticTypeMapper::mapToPHPStanPh
         pDocTypeNode for PHPStan\Type\ConditionalType"                         
         Run Rector with "--debug" option and post the report here: 
https://github.com/rectorphp/rector/issues/new
". On line:
         54                                                                     
```

ref https://github.com/rectorphp/rector-src/actions/runs/3593930507/jobs/6051531769#step:10:21

like reported at https://github.com/rectorphp/rector/issues/7632

**Comment by TomasVotruba** [comment]
Working on it: https://github.com/rectorphp/rector-src/commit/4f358d29e0f9bd7184c3cd3eff3d444c12001356

**Pull request merged**
