### PR TITLE
[BetterPhpDocParser] Run PhpDocNodeTraverser->traverse() once take 2

### PR DESCRIPTION
**Pull request by samsonasik**
Continue of PR:

- https://github.com/rectorphp/rector-src/pull/4822

use only single `PhpDocNodeTraverser` to traverse all registered visitors.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba the pending CI may need to be enabled:

```
 PHP 8.1 tests Expected — Waiting for status to be reported 
```

**Comment by samsonasik** [comment]
I see, that's wait for PR:

- https://github.com/rectorphp/rector-src/pull/4827

to be merged first.

**Comment by samsonasik** [comment]
Rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba let's merge it ;)

**Comment by TomasVotruba** [comment]
Awesome :+1:

**Pull request merged**
