### PR TITLE
[TypeDeclaration] Skip intersection with iterable on ReturnTypeDeclarationRector on php 8.1 feature enabled

### LINKED ISSUE #7562: Rector creates Collection&iterable as return type
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.14.6             |

I've got a problem with a Doctrine entity in my Symfony application. Unfortunately, I haven't found a way to create a simple reproducible example, so I need some help.

## Minimal PHP Code Causing Issue
```
    /** @var \Doctrine\Common\Collections\Collection<\App\Entity\User\UserSocialAccount> */
    #[OneToMany('user', targetEntity: UserSocialAccount::class)]
    private Collection $socialAccounts;

-    public function getMemberships() : Collection
+    public function getMemberships() : \Doctrine\Common\Collections\Collection&iterable
     {
         return $this->memberships;
     }

Applied rules:
 * ReturnTypeDeclarationRector (https://wiki.php.net/rfc/scalar_type_hints_v5)

```

This creates a `Type 'iterable' cannot be part of an intersection type` error.

Any idea?

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
final class SkipIntersectionIterable
{
    /** @var \Doctrine\Common\Collections\Collection<\stdClass> */
    private \Doctrine\Common\Collections\Collection $socialAccounts;

    public function __construct()
    {
        $this->socialAccounts = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /** @return \Doctrine\Common\Collections\Collection<\stdClass> */
    public function getSocialAccounts() : \Doctrine\Common\Collections\Collection
    {
        return $this->socialAccounts;
    }
}
```

It currently produce return type declaration with intersection consist of iterable:

```diff
-    public function getSocialAccounts() : \Doctrine\Common\Collections\Collection
+    public function getSocialAccounts() : \Doctrine\Common\Collections\Collection&iterable
```

which invalid.

This PR try to fix it. Fixes https://github.com/rectorphp/rector/issues/7562

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @stephanvierkant

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you, looks good :+1:  Feel free to merge when ready

**Pull request merged**
