### PR TITLE
[Scoped] Fix exclude symfony/console/Tester

### PR DESCRIPTION
**Pull request by samsonasik**
Continue of https://github.com/rectorphp/rector-src/pull/1437

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba Scoped build green, but now in `rector/rector`, the `standalone_rule_test` got error https://github.com/rectorphp/rector/runs/4470779068?check_suite_focus=true#step:6:4

```bash
Run vendor/bin/phpunit
  vendor/bin/phpunit
  shell: /usr/bin/bash -e {0}
PHP Fatal error:  Declaration of RectorPrefix20211209\Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::hasChildren(bool $allowLinks = false): bool must be compatible with RecursiveDirectoryIterator::hasChildren($allow_links = NULL) in /home/runner/work/rector/rector/vendor/rector/rector/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php on line 137
Error: Process completed with exit code 255.
```

**Comment by samsonasik** [comment]
@TomasVotruba the following code seems error on php <= 7.4

```php
class RecursiveDirectoryIteratorChild extends \RecursiveDirectoryIterator
{
    public function hasChildren(bool $allowLinks = false): bool
    {
        return true;
    }    
}
```

https://3v4l.org/kXTag

**Comment by TomasVotruba** [comment]
The `bool` type declaration must be removed probably: https://3v4l.org/GSgZG
Maybe we'll need specific rule to handle this one.

**Comment by TomasVotruba** [comment]
On the other hand, it would be better to avoid event dispatcher at all. The more classes we scope and downgrade, the more problems we have to handle.

**Comment by TomasVotruba** [comment]
Where was the issue/build with missing event dispatcher? Maybe there is better fix

**Comment by samsonasik** [comment]
That's on this CI build https://github.com/rectorphp/rector-src/runs/4470336303?check_suite_focus=true#step:9:12337

If `symfony/console/Event` and `symfony/console/EventDispatcher` is skipped as previously before this https://github.com/rectorphp/rector-src/pull/1435

then `symfony/console/Event` and `symfony/console/EventDispatcher` needs to be skipped from `parallel-lint`

**Comment by TomasVotruba** [comment]
> If symfony/console/Event and symfony/console/EventDispatcher is skipped as previously before this #1435
> then symfony/console/Event and symfony/console/EventDispatcher needs to be skipped from parallel-lint

That would the best solution IMO :+1:

**Comment by samsonasik** [comment]
Ok, I created PR https://github.com/rectorphp/rector-src/pull/1439 for that.

**Pull request merged**
