### PR TITLE
Revert Add class-string typehint to MethodCallRename

### PR DESCRIPTION
**Pull request by TomasVotruba**
Reverts rectorphp/rector-src#2726

### CODE REVIEW

**Comment by TomasVotruba** [comment]
We have to revert, otherwise PHPStan reports strings as missing classes. The class actually does not have to exists, so the only valid type is `string`
See https://github.com/rectorphp/rector-src/pull/2726#issuecomment-1207231582

**Comment by samsonasik** [comment]
Please remove double quote in commit message

**Comment by TomasVotruba** [comment]
Done :+1:

**Comment by samsonasik** [comment]
double quote "" in commit message can cause build failure

**Pull request merged**
