### PR TITLE
[Strict] Add support string|null|false on BooleanInBooleanNotRuleFixerRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
class StringNullAndFalse
{
    public function run(string|null|false $name)
    {
        if (! $name) {
            return 'no name';
        }

        return 'name';
    }
}
```

it currently produce:

```diff
-        if (! $name) {
+        if ($name === '' || $name === false) {
```

which `null` is not checked, which will got next return instead. This PR add this support so it will be:

```diff
-        if (! $name) {
+        if ($name === '' || $name === false || $name === null) {
```

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
Also update for `DisallowedEmptyRuleFixerRector` test: https://github.com/rectorphp/rector-src/pull/2035/commits/1ec2ff1f04c11d35c4103b261e154d73d9f7e555

```php
final class MultiUnionTypes
{
    /**
     * @param int|int[]|null|string $id
     */
    public function get($id)
    {
        return empty($id);
    }
}
```

to 

```diff
-        return empty($id);
+        return $id === [] || $id === 0 || $id === '' || $id === null;
```

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I am merging it ;)

**Comment by TomasVotruba** [comment]
👍

**Pull request merged**
