### PR TITLE
DependencyClassMethodDecorator: Prevent duplication of arguments

### LINKED ISSUE #7286: ClassDependencyManipulator inserts duplicate constructor argument
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.8|

When parent class has a constructor-injected dependency and `ClassDependencyManipulator` tries to add a constructor for the child class for the same dependency, the new constructor will have two such parameters.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/2b5d2da3-f97e-48aa-ab52-97268718bb40

## Expected Behaviour

The constructor argument should be reüsed.

### PR DESCRIPTION
**Pull request by jtojnar**
Fixes: https://github.com/rectorphp/rector/issues/7286

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you :+1: 

We'll need a test fixture that cover this.

**Comment by jtojnar** [comment]
Do you have an example of a test I can use as a template? Or would covering it using an ad-hoc rule as in https://getrector.org/demo/2b5d2da3-f97e-48aa-ab52-97268718bb40 be okay?

**Comment by TomasVotruba** [comment]
You can add it to https://github.com/rectorphp/rector-src/blob/main/rules-tests/DependencyInjection/Rector/ClassMethod/AddMethodParentCallRector/AddMethodParentCallRectorTest.php → `/Fixture` directory. There you'll find other tested cases

**Comment by jtojnar** [comment]
`AddMethodParentCallRector` does not look like uses `DependencyClassMethodDecorator`. But I looked for  `DependencyClassMethodDecorator` and it is only used by `ClassDependencyManipulator`, which is solely used by `PropertyAddingPostRector`. And that in turn uses `PropertyToAddCollector` so I checked its uses and `NewToConstructorInjectionRector` fits the use case.

**Comment by jtojnar** [comment]
Seems to pass now.

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
