### PR TITLE
[Defluent] Skip DefluentReturnMethodCallRector on return clone object

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://3v4l.org/KGZWe vs https://3v4l.org/eYMH1

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
tests error notice `rectorphp/rector-symfony`, `rectorphp/rector-doctrine`, and `rectorphp/rector-symfony` seems unrelated.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
Added handle clone directly, and new $this, new static as well 🎉

**Comment by samsonasik** [comment]
actually, `return new Anything()` means different existing object so should be skipped.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
