### PR TITLE
Remove resolveFromNodeWithScopeCountAndFallbackName() as unused

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by staabm** [comment]
Since you are removing methods, please make sure the next release will be 0.18.0 :-)

**Comment by TomasVotruba** [comment]
There are most likely only internals :) also, this is not neccessary in semver. See https://semver.org/#spec-item-4

The versioning in 0.x reflects mix of BC changes, new features and time to upgrade.

**Comment by staabm** [comment]
While you might be right from a theoretical standpoint, your users will thank you for communicating clearly when introducing BC breaks. 

Otherwise they might get frustrated

**Comment by TomasVotruba** [comment]
I agree. For more common methods we do it, yet the `resolveFromNodeWithScopeCountAndFallbackName()` is quite niche and only useful for downgrade cases.

Also bumping version could backfire, jumping from 0.17 to e.g. 0.22 in a month could discourage people from using new version, as they will not keep up the pace.

**Pull request merged**
