### PR TITLE
Include typo3 rector in scoped version follow up

### PR DESCRIPTION
**Pull request by sabbelasichon**

### CODE REVIEW

**Comment by sabbelasichon** [comment]
Some things i have done. You can see them already in the commits:

- I have excluded the vendor prefix Ssch from scoping
- Exclude ssch/typo3-rector from packages testing (not accessible yet)
- Exclude some templates in ssch/typo3-rector from the linting

**Comment by sabbelasichon** [comment]
@TomasVotruba Everything went fine regarding the downgrading / scoping. Yeah.

**Comment by sabbelasichon** [comment]
But for accessible reasons the version could not be pushed to the other repository.

**Comment by TomasVotruba** [comment]
I'm looking into this

**Comment by TomasVotruba** [comment]
Ah, I probably see why the token was not found. This pull-request is send from your work - an external repository where you would have to setup tokens first.

To make it work the PR must be created in this repository.

**Comment by TomasVotruba** [comment]
I'll send the PR, to see how it helps :+1:

**Comment by TomasVotruba** [comment]
Replaced by https://github.com/rectorphp/rector-src/pull/71 with local scope

**Pull request closed without merging**
