### PR TITLE
[Windows] Rework add windows support on tests CI

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
Finally 🎉 🎉 🎉 All checks have passed 🎉 @TomasVotruba @staabm it is ready for review.

**Comment by samsonasik** [comment]
I tried enable e2e test, it seems cause invalid result

```diff

Run php ../e2eTestRunner.php
  
 0/2 [>---------------------------]   0%
    ---------- begin diff ----------
@@ @@
 #Warning: Strings contain different line endings!
-2 files with changes
-====================
-
-1) src/MultiRules.php:5
-
-    ---------- begin diff ----------
-@@ @@
-     {
-         if (true === false) {
-             return -1;
--        } else {
--            echo 'a statement';
-         }
--    }
--
--    private function notUsed()
--    {
-+        echo 'a statement';
-     }
- }
-    ----------- end diff -----------
-
-Applied rules:
- * RemoveUnusedPrivateMethodRector
- * RemoveAlwaysElseRector
-
```

`ConsoleDiffer` seems need to be updated.

**Comment by samsonasik** [comment]
@TomasVotruba @staabm I am going to merge as is for now, e2e test seems another challenge that require tweak on **ConsoleDiffer** ;). This PR catch some bug fix:

- Fix keep original new line replacer on BetterPhpDocParser
- Fix keep original new line replacer on PhpDocInfoPrinter

**Comment by TomasVotruba** [comment]
Awesome work Abdul :rocket: , thanks for pushing this :+1:

**Pull request merged**
