### PR TITLE
[CodeQuality][TypeDeclaration] Handle ExplicitBoolCompareRector + ReturnTypeDeclarationRector on auto import return

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
use PhpParser\Node\Expr;
use PhpParser\Node\Expr\BinaryOp\BooleanAnd;
use PhpParser\Node\Expr\BinaryOp\BooleanOr;

final class Anything
{
    public function run(Expr $expr, Expr $expr2): BooleanAnd | BooleanOr
    {
        return rand(0, 1)
            ? new BooleanAnd($expr, $expr2)
            : new BooleanOr($expr, $expr2);
    }
}
```

It currently produce:

```diff
-    public function run(Expr $expr, Expr $expr2): BooleanAnd | BooleanOr
+    public function run(Expr $expr, Expr $expr2): \BooleanAnd|\BooleanOr
```

which add backslash is invalid. 

Using rector rules:

```
use Rector\CodeQuality\Rector\If_\ExplicitBoolCompareRector;
use Rector\TypeDeclaration\Rector\FunctionLike\ReturnTypeDeclarationRector;
```

with auto import enabled.

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
still needs check on null ternary if

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
@TomasVotruba I am at Google meet if you want to talk

**Review by TomasVotruba — APPROVED** [review]

**Pull request merged**
