### PR TITLE
[DeadCode] Skip non typed param numeric check on RecastingRemovalRector

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://github.com/rectorphp/rector-src/pull/4389#issuecomment-1615835849

### CODE REVIEW

**Comment by samsonasik** [comment]
let's try with equal check if not mixed https://github.com/rectorphp/rector-src/pull/4390/commits/5a2a1cf817e7f69b87fe5f82f94910bf91e1f459

**Comment by samsonasik** [comment]
still error, let's give a try with super type check https://github.com/rectorphp/rector-src/pull/4390/commits/e6f41242b57efcd0a0278461fcf407ee685ec7d3

**Comment by samsonasik** [comment]
@TomasVotruba fixed ;), I am merging it ;)

@staabm I may need your help to verify this in other projects usage ;), the change was from removing parent lookup on https://github.com/rectorphp/rector-src/pull/4389 which cause issue on `is_numeric()` check against `(int)` cast so need to verify type equality on Union type. Thank you ;)

**Comment by staabm** [comment]
> I may need your help to verify this in other projects usage

could  you get more precise how I can help you?

**Comment by samsonasik** [comment]
@staabm that's what you tried on https://github.com/rectorphp/rector-src/pull/4380#discussion_r1249686269 , it seems working ok 👍

**Pull request merged**
