### PR TITLE
[Defluent] Handle casted return value on FluentChainMethodCallToNormalMethodCallRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
class CastedReturnValue
{
    public function getCastedValue(DifferentReturnValues $differentReturnValues)
    {
        return (int) $differentReturnValues->someFunction()->otherFunction();
    }
}
```

Currently got error:

```bash
1) Rector\Tests\Defluent\Rector\MethodCall\FluentChainMethodCallToNormalMethodCallRector\FluentChainMethodCallToNormalMethodCallRectorTest::test with data set #15 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
LogicException: leaveNode() returned invalid value of type integer
```

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
Strange error test in CI even test moved to different class test: 

```bash
1) Rector\Tests\Defluent\Rector\MethodCall\FluentChainMethodCallToNormalMethodCallRector\CastedValueTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
65
LogicException: leaveNode() returned invalid value of type integer
```

**Comment by samsonasik** [comment]
Change to `FluentNodeRemover` somehow not detected by Git

**Comment by samsonasik** [comment]
Ok, so `FluentNodeRemover` is on Symfony package which is in vendor. It then need to be tweaked in current rector rule directly.

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Review by TomasVotruba — APPROVED** [review]

**Pull request merged**
