### PR TITLE
[DeadCode] Handle @return $this on final class method return type self on RemoveUselessReturnTagRector

### PR DESCRIPTION
**Pull request by samsonasik**
@staabm this is to remove `@return $this` on method that has return self.

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixture on `UnionTypeRector` need updated for it https://github.com/rectorphp/rector-src/pull/3480/commits/ab7ef1bafcfc3df315a80fd65160b3b2e6af04cc

**Comment by samsonasik** [comment]
I added fixture to skip on abstract class https://github.com/rectorphp/rector-src/pull/3480/commits/8ad1cd6211346ce6b27ac7c8db7cf402678e98c5

**Comment by staabm** [comment]
Thanks!

I am not 100% sure, `return $this` and `:self` are semantically identical in all cases.   

We should ask for more opinions on this one

**Comment by samsonasik** [comment]
Keeping `@return $this` is from PR:

- https://github.com/rectorphp/rector-src/pull/1665

from @simPod , probably has opinion on this #

**Comment by simPod** [comment]
Yup, those are different things, similar case like keeping `@return non-empty-string`

$this returns the same instance while self does not say anything about that.

**Comment by samsonasik** [comment]
@simPod on final class, `$this` and `self` should be same, and `@return $this` can be removed?

**Comment by simPod** [comment]
not really, it depends on whether you write

```php
public function returnThis(): self {
    return $this;
}
```

```php
public function returnSelf(): self {
    return new self();
}
```

`final` is not relevant.

**Comment by staabm** [comment]
at this point I think we can stop here. @samsonasik thanks for the effort and sorry for the noise.

it seems I did not had a full picture of all this :-/

**Comment by samsonasik** [comment]
Ok, I am closing it then ;) Thanks @simPod @staabm for verify

**Pull request closed without merging**
