### PR TITLE
[Experiment] [NodeTypeResolver] Remove no longer needed deep Expr visitor ExprScopeFromStmtNodeVisitor

### PR DESCRIPTION
**Pull request by samsonasik**
It seems deep expr scope visitor no longer needed. This PR remove it.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

For note: this can be reverted in the future if there  is code with deep Expr that phpstan can't locate, and that will require new fixture to proof. I will also check on some projects in case of regression in other projects.

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Lets try  this in the wild 👌

**Comment by shutnic** [comment]
Hello, after deleting this piece of code, I encountered issues with using the match operator. Here is a link to the demo https://getrector.com/demo/4750277e-8fdc-4a2f-8bf0-b6aa76090e8f

**Comment by samsonasik** [comment]
@shutnic I will look into that,note to myself: in phpstan 1.11+, `expressionDepth` attribute no longer exists, so can't rely on it again

**Pull request merged**
