### PR TITLE
[TypeDeclaration] Skip mixed as on right of and on ParamTypeByMethodCallTypeRector

### LINKED ISSUE #8872: Incorrect behavior of ParamTypeByMethodCallTypeRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/08d68709-877e-4905-a393-ba6faea77000

```php
<?php

namespace shop\basket\viewmodel;

use Webmozart\Assert\Assert;

/**
 * @immutable
 */
final class TestObj
{
    public string $code;

    public function __construct(string $code)
    {
        $this->code = $code;
    }

    public static function tryFromUntrusted($code): ?self
    {
        $ok = \is_string($code) && self::isCodeOk($code);
        if (! $ok) {
            return null;
        }

        return new self($code);
    }

    private static function isCodeOk(string $code): bool
    {
        return true;
    }
}
```

### Responsible rules

* `ParamTypeByMethodCallTypeRector`

## Expected Behavior

rector should not infer `string` param type, because the code is meant to work for anything (on a php version which does not support a `mixed` param type)

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8872

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @staabm

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
I think this is rather specific fix that will fail for slightly different code syntax. There should be check for first type of `$code` or if the value type changed.

How would this behave with negated value?

```php
$ok = ! \is_string($code) && self::isCodeOk($code);
```

**Comment by samsonasik** [comment]
negation check is invalid and will cause fatal error on the first place, since it typed param string on caller, see:

https://3v4l.org/Ouift

**Comment by TomasVotruba** [comment]
Let's ship it and see how to goes :+1:

**Pull request merged**
