### PR TITLE
[DX] Add MissedRectorDueVersionChecker

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/rector/issues/6563#issuecomment-883395434 - implements

**Comment by TomasVotruba** [comment]
cc @NotionCommotion Here is the prototype PR for the notification about PHP version missed rules. What do you think about the implementation?

**Comment by NotionCommotion** [comment]
Hi Tomas.  Looks like you've been busy!  Like the use of the MinPhpVersionInterface interface.

**Comment by TomasVotruba** [comment]
Let's ship it and test in practise then :) thanks for feedback! :+1:

**Pull request merged**
