### PR TITLE
[Downgrade PHP 8.0] Add DowngradeDereferenceableOperationRector

### PR DESCRIPTION
**Pull request by villfa**

### CODE REVIEW

**Comment by samsonasik** [comment]
is naming should be   dereferenceable instead of dereferencable? Ref: https://en.m.wiktionary.org/wiki/dereferenceable#English

**Comment by villfa** [comment]
TBH I don't know. I've just kept the same spelling than the RFC: https://wiki.php.net/rfc/variable_syntax_tweaks

**Review by samsonasik — APPROVED** [review]
Ok :+1:

**Comment by villfa** [comment]
FYI I'm renaming everything since it looks indeed like a misspelling. I'll commit these changes soon.

**[EDIT]** Done

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
