### PR TITLE
[EasyTesting] dogfood next iteration

### PR DESCRIPTION
**Pull request by clxmstaab**
to dogfood https://github.com/symplify/symplify/pull/3440#issuecomment-889390020

### CODE REVIEW

**Comment by clxmstaab** [comment]
after looking at the CI times it looks like a median improvement of 10-15secs (even on linux)

**Comment by TomasVotruba** [comment]
Depends if the suite goes from 6:00 to 5:45 or 1:15 to 1:00. Not sure if worth the effort in first case. Second case? Take my money :) 

Current container rebuilds as whole for every test case, not if for single data provider item. Maybe there is a better way like using own container cache that rebuils only rector service rule dumps. There we could save 60-70 % performance.

**Comment by staabm** [comment]
> Currenct container rebuilds as whole for every test case, not if for single data provider item. Maybe there is a better way like using own container cache that rebuils only rector service rule dumps. There we could save 60-70 % performance.

hmm I think https://github.com/rectorphp/rector-src/pull/550 kind of does it like that (re-use the container for test-cases with a data provider)

**Comment by TomasVotruba** [comment]
That actually creates a new container per config:
https://github.com/rectorphp/rector-src/pull/550/files#diff-42c9f7fb9d75c70447757e107f0b6d551bc2dcf541e91f37192cf2c1ec16fea3R30

What we want to do is create one container for all the tests and data providers,
and then only switch the Rector services in provided config.

**Comment by clxmstaab** [comment]
> What we want to do is create one container for all the tests and data providers,
> and then only switch the Rector services in provided config.

I guess this would mean some tests would inherit config from other tests and might need adjustment to handle the addtional unrelated config?

**Comment by TomasVotruba** [comment]
> I guess this would mean some tests would inherit config from other tests and might need adjustment to handle the addtional unrelated config?

The configs setup should remain the same. They should be idempotent and mutualy independent.

Only the way container is created should be more effective and replace only the changing scope.

**Pull request merged**
