### PR TITLE
[Php 81] Add Php81ResourceReturnToObjectRector

### PR DESCRIPTION
**Pull request by samsonasik**
for php 8.1 Resolve https://github.com/rectorphp/rector/issues/6749

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba it is implemented 🎉 , the CI error is unrelated.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
