### PR TITLE
[NodeTypeResolver] Handle infinite loop on 2 layers deep anonymous class inside Trait 

### LINKED ISSUE #7913: 2 layer deep Anonymous class trait usage infinite loop
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector versions | 0.14.8 , 0.15.23             |
| Php version |8.0.28             |

## Minimal PHP Code Causing Issue
With the default generated rector.php:
```php
<?php

declare(strict_types=1);

use Rector\CodeQuality\Rector\Class_\InlineConstructorDefaultToPropertyRector;
use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/src',
    ]);

    // register a single rule
    $rectorConfig->rule(InlineConstructorDefaultToPropertyRector::class);

    // define sets of rules
    //    $rectorConfig->sets([
    //        LevelSetList::UP_TO_PHP_80
    //    ]);
};

```
and a valid php file of the form of test.php:

```php
<?php
// test.php
trait RectorTest {
    public function blah()
    {
        return (new class() {
            public function foo()
            {
                return (new class() {
                    use RectorTest;
                });
            }
        });
    }
}
```

when running rector process against the aformentioned test.php with the default configuration:
```shell
rector process test.php

```
the rector process hangs until operating system oomkills it

## Expected Behaviour

that rector processes the file successfully (ok rector is done message)

## Additional notes
* If you comment out the line `use RectorTest;` of test.php, and re-run, rector is able to successfully process the nodes.
* `use RectorTest;` also doesn't trip up rector if it's used in the first anonymous class returned, unlike test.php which is one layer of depth deeper (a trait that returns an anonymous class that uses the original trait, vs a trait that returns an anonymous class that has a method that returns ANOTHER anonymous class that uses the original trait) maybe just read the code  :joy: 
* `phpstan-1.10.7.phar` and `phpstan-1.10.14.phar` have no issue when `analyze test.php` is ran,  we thus far suspect that perhaps the callback in https://github.com/rectorphp/rector/blob/main/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php#L134-L145 that is given to phpstans `processStmtNode` method of `phpstan/phpstan/modified/src/Analyser/NodeScopeResolver.php` to play a role. or perhaps something in https://github.com/ondrejmirtes/BetterReflection :thinking: :shrug:

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7913
Ref https://getrector.com/demo/938b616e-f5ff-4317-ab85-0493dcdec722

### CODE REVIEW

**Comment by samsonasik** [comment]
@jgedarovich let's try if it can solve https://github.com/rectorphp/rector/issues/7913

**Comment by samsonasik** [comment]
It seems cause error on, `DowngradeParentTypeDeclarationRectorTest`:


```diff
There were 3 failures:

1) Rector\Tests\DowngradePhp70\Rector\ClassMethod\DowngradeParentTypeDeclarationRector\DowngradeParentTypeDeclarationRectorTest::test with data set #4
Failed on fixture file "in_trait.php.inc"
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 
 trait SomeTrait
 {
-    /**
-     * @return parent
-     */
-    public function run()
+    public function run(): parent
```

I will re-check...

**Comment by samsonasik** [comment]
Not sure about it, closing for now.

**Comment by samsonasik** [comment]
Re-open, remove trait use during resolving class scope somehow resolving it https://github.com/rectorphp/rector-src/pull/3725/commits/896ccf76b33baf7bf69dccf8826477f3fa6cda53

**Comment by samsonasik** [comment]
Ok, it seems due to it locate a same trait on parent, while it loaded, if it goes to use different trait, it will working as expected, see https://getrector.com/demo/f6a66003-bc0a-41c3-b00b-851ebaa044fb

**Comment by samsonasik** [comment]
Finally Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by jgedarovich** [comment]
@samsonasik thank you for your lightning fast fix, i'm super impressed!  

I'm very new to rector and want to make sure i understand the fix. Is it that when rector encounters an anonymous class, it  checks that anonymous classes statements, and if it finds one that contains identical trait usage from the outer scope it unsets that trait in the anonymous classes statements?

**Comment by samsonasik** [comment]
I myself don't really understand why inside trait, it make infinite loop, it somehow auto load trait when defined in parent.

My patch probably cause another bug in the future, but can't imagine right now why these use case actually exists.

Rule of thumb: don't use trait actually, as it will scoping really hard to resolve.

**Comment by samsonasik** [comment]
@jgedarovich btw, what kind of use case you have 2 layer anonymous class inside trait, and last anonymous class consume parent trait?

While this hack patch it, I am thinking you can create dedicated class for that use case, so it will normally processable.

**Comment by samsonasik** [comment]
I create alternative solution for it https://github.com/rectorphp/rector-src/pull/3728

**Comment by samsonasik** [comment]
@jgedarovich I am thinking that this is very rare use case, see this that I can only imagine  https://3v4l.org/FMgS1 .

Even this code exists, this seems really hard to understand, probably better to be refactored instead

**Comment by jgedarovich** [comment]
>  what kind of use case you have 2 layer anonymous class inside trait,

Looking at the code this pattern came from - I'm finding it hard to justify it's usage of this pattern. 

> Even this code exists, this seems really hard to understand, probably better to be refactored instead

I completely agree. thank you for looking into this!

**Comment by samsonasik** [comment]
Thank you for clarify. Rector scoping is rely on PHPStan, and as this usage is very rare, and this patch probably cause another issue as it removing node data on process of filling scope, I think it should not be handled by Rector, instead, try refactor your code instead or just skip via:

```php
$rectorConfig->skip(...)
```

https://getrector.com/documentation/ignoring-rules-or-paths

Thank you for understanding.

**Comment by jgedarovich** [comment]
> Thank you for clarify. Rector scoping is rely on PHPStan, and as this usage is very rare, and this patch probably cause another issue as it removing node data on process of filling scope, I think it should not be handled by Rector, instead, try refactor your code instead or just skip via:
> 
> ```
> $rectorConfig->skip(...)
> ```
> 
> https://getrector.com/documentation/ignoring-rules-or-paths
> 
> Thank you for understanding.

interesting! I tried skipping the specific file a few ways but was unable to prevent rector from trying to parse the file with phpstan! Does skip actually prevent phphstan analysis of files (where the infinite loop issue seems to occur), or does it just skip running configured rules against the phpstan analyzed files?

**Comment by samsonasik** [comment]
I can't reproduce, it properly skip the file provided:

```php
    $rectorConfig->skip([
        __DIR__ . '/src/a.php',
    ]);
```

**Comment by jgedarovich** [comment]
hrmm - what am i doing wrong here :thinking: 
https://github.com/jgedarovich/rector-issue-7913

**Comment by samsonasik** [comment]
Not sure, I think you better refactor it, move to different trait will make always work

**Pull request closed without merging**
