### PR TITLE
Only import docblock if import name enabled on PostFileProcessor

### LINKED ISSUE #8756: Rector imports classes used in PHPDoc (ignores `AUTO_IMPORT_DOC_BLOCK_NAMES`)
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.2.2 |

I have a config like:

```php
return static function (\Rector\Config\RectorConfig $rectorConfig): void {
    $rectorConfig->importNames(false);
    $rectorConfig->importShortClasses(false);
    $rectorConfig->parallel(
        50 * 60,
        32, // Safe to set a high number, it will be reduced to a number of CPU cores anyway, @see https://github.com/rectorphp/rector-src/pull/3184#issuecomment-1365041469
        40
    );
...
```

In previous Rector versions, it respected these settings and didn't import classes declared in PHPDoc. After one of recent releases (between 1.0.3 and 1.2.0) and started to import all classes (incl. PHPDoc and ones from root namespace). Additionally it's stopped displaying applied rule in output, so it looks like this:
image

## Expected Behaviour
1. Respect AUTO_IMPORT_DOC_BLOCK_NAMES value set by importNames
2. Respect AUTO_IMPORT_NAMES value set by importNames
3. Show applied Rector rules in output

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8756

### CODE REVIEW

**Comment by samsonasik** [comment]
@alies-dev this should fix it

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by alies-dev** [comment]
I'm confirming, it fixes an issue https://github.com/rectorphp/rector/issues/8756

**Comment by TomasVotruba** [comment]
Thanks @samsonasik :+1:

**Pull request merged**
