### PR TITLE
[Php81] Skip with next required on NewInInitializerRector

### LINKED ISSUE #8939: Incorrect behavior of NewInInitializerRector with required parameters
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/f7fb5830-c267-47d9-a857-78423b88b478

```php
<?php

class VO {
}

class Foo {
    private VO $a;
    
    public function __construct(
        ?VO $a,
    	private string $b
    ) {
    	$this->a = $a ?? new VO;
    }
    
    public static function create() {
        return new Foo(null, '');
    }
}

Foo::create();
```

### Responsible rules

* `NewInInitializerRector`

## Expected Behavior

Two issues here with NewInInitializerRector which may be linked.

The replaced parameter is before a required one, and its ends up with an optional parameter before a reqiured one (deprecated in php).

Also, the old code implied that the constructor was explicitly called with a null value wich is not replaced and generate a TypeError (must be of type VO, null given)

Expectation:
If there is required parameters after the parameter to replace, to rule should be skipped
If the rule is applied, it should remove explicit null calls to the constructor

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8939

### CODE REVIEW

**Comment by samsonasik** [comment]
Test notice on `ReturnTypeFromStrictNewArrayRector` is due to new phpstan 2.0.4 https://github.com/phpstan/phpstan/releases/tag/2.0.4

I updated the fixture https://github.com/rectorphp/rector-src/pull/6599/commits/977c71e013cf2094dd703b024106cba3ab0f087d

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @NicoImparfait

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by NicoImparfait** [comment]
@samsonasik thank you !

**Pull request merged**
