### PR TITLE
[DeadCode] Skip count() on mixed on RemoveUnusedNonEmptyArrayBeforeForeachRector

### LINKED ISSUE #8265: RemoveUnusedNonEmptyArrayBeforeForeachRector: removal of count() without array type
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/1411b26e-488c-41a8-8bc3-e2bc8a1757cf

```php
<?php

final class DemoFile
{
    public static function doFoo($vars): void
    {
        if (count($vars) > 0) {
            foreach ($vars as $key => $val) {
                echo "hello";
            }
        }

        return [];
    }
}
```

### Responsible rules

* `RemoveUnusedNonEmptyArrayBeforeForeachRector`

## Expected Behavior

I think the code should be skipped because we don't know the type of `$vars`.
it could be `array`, `iterable`, `stdClass` or any `Traversable` object, or even a `string` or similar

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8265

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @staabm

**Comment by samsonasik** [comment]
@staabm while it fixed the issue, could you create a https://3v4l.org/ demo for how it can cause invalid usage without skipping?

Otherwise, the patch is useless :)

**Comment by staabm** [comment]
see https://3v4l.org/bavqQ where we get fatal errors on the `count` variant, but not the `foreach` variant

**Comment by samsonasik** [comment]
The error is exists on the first place, so removing `count()` actually unrelated to side effect.

see https://3v4l.org/eGBHn

when no change yet, it already fatal error.

In real app, actually, removing `count()` should never used when only used on loop next.

**Comment by staabm** [comment]
> when no change yet, it already fatal error.

I don't get your point. IMO we can't change code which fatal errors (so from a runtime perspective will stop execution and will not proceed) with a different code which no longer fatal errors and keeps executing.

sure the code not running into fatal errors sounds better but if rector is doing such change it completely changes the code beeing executed and because of procssing is not running into a fatal error anymore it might lead to e.g. other serious problem in code after that, which was never executed before rector did the change

**Comment by samsonasik** [comment]
That seems just hiding the real issue then. If the code after that must not be executed, then code should be modified to fix that.

The `TypeError` check will need to be catched on the first place, and user should see that.

**Comment by staabm** [comment]
back to square one: the only thing I am saying is, that rector cannot do a change which fundamentally changes the execution path.

of course such a code should be fixed by a human. 

the `RemoveUnusedNonEmptyArrayBeforeForeachRector` can of course remove e.g. a `count()` statement if it knows whatever passed to it is countable.

**Comment by samsonasik** [comment]
Ok, the rule is named `RemoveUnusedNonEmptyArrayBeforeForeachRector`, so it should only care about `ArrayType`, so your reason is reasonable.

I am merging it then ;)

**Pull request merged**
