### PR TITLE
Remove deprecated @noRector warning

### PR DESCRIPTION
**Pull request by samsonasik**
It's been a while, I think `@noRector` warning can be removed.

### CODE REVIEW

**Comment by samsonasik** [comment]
Github seems down now: https://www.githubstatus.com/

Raw url on vendor patches seems just got error:

https://github.com/rectorphp/rector-src/actions/runs/4515258029/jobs/7952332086?pr=3518#step:4:341

this is unrelated with this PR.

**Comment by samsonasik** [comment]
Close-Reopen to restart build

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks 👍

**Pull request merged**
