### PR TITLE
[DowngradePhp80] Handle DowngradeUnionTypeDeclarationRector on closure

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by leoloso** [comment]
@samsonasik Thanks.

Also for `mixed` is missing: 

```php
$foo = array_filter(
  $list,
  // This needs be removed for PHP 7.1, currently it is not
  function (mixed $fieldArgValue) {
    return is_null($fieldArgValue);
  }
);
```

**Comment by samsonasik** [comment]
@leoloso what rule that handle downgrade mixed ?

**Comment by leoloso** [comment]
@samsonasik  [`DowngradeMixedTypeDeclarationRector.php`](https://github.com/rectorphp/rector/blob/main/rules/DowngradePhp80/Rector/FunctionLike/DowngradeMixedTypeDeclarationRector.php)

**Comment by samsonasik** [comment]
@leoloso thank you, I created PR https://github.com/rectorphp/rector-src/pull/106 for that.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
