### PR TITLE
[Naming] Handle used in arrow function param, then used again outer ArrowFunction on RenameParamToMatchTypeRector

### LINKED ISSUE #8693: Incorrect behavior of RenameParamToMatchTypeRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

When param name used as ArrowFunction param, it should be skipped.

See https://getrector.com/demo/14b8b5f1-05ee-4ecb-9d84-973ddc5297a4

```php
<?php

use PhpParser\Node\Stmt\Foreach_;
use PhpParser\Node\Expr\Variable;

final class DemoFile
{
    public function run(Foreach_ $node)
    {
      array_map(
          fn (Variable $node) 
          => $node,
          []
          );
    }
}
```

### Responsible rules

* `RenameParamToMatchTypeRector`

## Expected Behavior

Should be skipped, ref rectify error at https://github.com/rectorphp/rector-src/pull/6045/commits/33ddf96050a1f96f91df42aca410038d509e53e9

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8693
Ref rectify error https://github.com/rectorphp/rector-src/pull/6045/commits/33ddf96050a1f96f91df42aca410038d509e53e9
Ref https://3v4l.org/Ba9fQ

### CODE REVIEW

**Comment by samsonasik** [comment]
It seems happen on closure as well https://getrector.com/demo/94516435-ab7a-4928-aae4-310f5fde630b

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
LGTM :+1:

**Pull request merged**
