### PR TITLE
[Defluent] Skip mixin in source on FluentChainMethodCallToNormalMethodCallRector

### PR DESCRIPTION
**Pull request by samsonasik**
Continue of https://github.com/rectorphp/rector-src/pull/688 , the `@mixin` can make crash when the class used as source to be called.

```bash
.............[1]    4044 segmentation fault  vendor/bin/phpunit 
```

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
It seems cause error in another rules-tests, possibly need to be handled in internal PHPStan, closing for now.

Possibly related to this issue in PHPStan https://github.com/phpstan/phpstan/issues/5390 .

**Comment by samsonasik** [comment]
I found a fix with check FullyQualified function first as mixin mostly happen in class. Re-open.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
