### PR TITLE
[Performance][BetterPhpDocParser] Unset NameScope object creation after used on ConstExprClassNameDecorator

### PR DESCRIPTION
**Pull request by samsonasik**
@staabm could you verify this change can improve performance improvement? Thank you.

### CODE REVIEW

**Comment by staabm** [comment]
hey. looking at the profile it looks like the actual traversal is slow, not the name-scope creation.

grafik

refs https://github.com/rectorphp/rector/issues/8079

**Comment by staabm** [comment]
maybe we can drop `ConstExprClassNameDecorator` and move setAttribute into `NameNodeVisitor`?

I think the most problematic thing is that we invoke the `ConstExprClassNameDecorator` for a lot of nodes and do a deep traversal for each one

**Comment by samsonasik** [comment]
Ok, closing it then.

Could you try create PR for that and ensure everything still green? Thank you.

**Comment by staabm** [comment]
but still thank you for looking into it. I profilled it locally with your change and it did not yield improvements

> Could you try create PR for that and ensure everything still green? Thank you.

I will have a look, thx

**Comment by staabm** [comment]
> maybe we can drop `ConstExprClassNameDecorator` and move setAttribute into `NameNodeVisitor`?

just realized that this doesn't make sense as `NameNodeVisitor` is iterating the AST and `ConstExprClassNameDecorator` is iterating PHPDocs

**Pull request closed without merging**
