### PR TITLE
[Scoper 7.0] run scoper 70

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba I created pull request with branch named "php70-scoped" in my fork repo based on this check:

https://github.com/rectorphp/rector-src/blob/8ce853d8ff7a264909f59b7cf7909ed82e0bf310/.github/workflows/build_scoped_rector_php70.yaml#L12

but it seems the github action is not started. 

Do you think I need to create branch in this repo instead of my fork repo? If yes, I probably need a push access to create a "php70-" prefixed branch in this repository. Thank you.

**Comment by TomasVotruba** [comment]
I'm not sure how the naming branch works exactly. Maybe Github docs is needed.

**Comment by samsonasik** [comment]
based on the doc, it seems needs "branches" key, and value seems target branch, not the source branch ref https://docs.github.com/en/actions/reference/events-that-trigger-workflows#example-using-multiple-events-with-activity-types-or-configuration

**Comment by TomasVotruba** [comment]
I see. Feel free to create temporary php70 branch 👍

**Comment by samsonasik** [comment]
I don't have access to create a branch/push to this repo 😁

**Comment by TomasVotruba** [comment]
Ah, we should fix that :) what about now? I sent you invitation to collaborators

**Comment by samsonasik** [comment]
thank you 👍 , I should be able to create branch/push to this repo now

**Pull request closed without merging**
