### PR TITLE
[Twitter API] Remove tweet_release workflow

### PR DESCRIPTION
**Pull request by samsonasik**
Twitter API no longer free at 2023-02-09 so I think it can be removed.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
How can we tweet the released then? :cry: 

@ondrejmirtes Hi Ondra, how did you solve the Twitter API behind paywall?

**Comment by ondrejmirtes** [comment]
I didn't yet, I'm gonna go look into it when it breaks.

**Comment by samsonasik** [comment]
Probably with a "license key" from Twitter. Context: https://twitter.com/TwitterDev/status/1621026986784337922

**Comment by ondrejmirtes** [comment]
It might continue working fine: https://www.theverge.com/2023/2/5/23586577/elon-musk-bots-good-content-twitters-api-free

**Comment by ratenfanger** [comment]
[As long as we don't have 1500 releases per month 😉](https://twitter.com/TwitterDev/status/1623467618400374784?s=20&t=f018R2cWzaN1OSak5JV9jQ)

**Pull request closed without merging**
