### PR TITLE
[Php74] Handle conflict with alias on TypedPropertyRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
use Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Source\AnotherClass;
use Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Source\AnotherClass as Alias;

final class ConflictWithAlais
{
    /**
     * @var Alias
     */
    private $anotherClass;

    public function __construct(AnotherClass $anotherClass)
    {
        $this->anotherClass = $anotherClass;
    }
}
```

It currently produce union type:

```diff
+    private Alias|\Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Source\AnotherClass $anotherClass;
```

which invalid, and it will error even on php 8:

```bash
Fatal error: Duplicate type Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Source\AnotherClass is redundant
```

and in php 7.4, it will error:

```bash
Parse error: syntax error, unexpected '|', expecting variable 
```

ref https://3v4l.org/cMjlj

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I added a failing test case when aliased never used, current patch make:

```php
use Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Source\AnotherClass;
use Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Source\AnotherClass as Alias;

final class ConflictWithAlias2
{
    /**
     * @var AnotherClass
     */
    private $anotherClass;

    public function __construct(AnotherClass $anotherClass)
    {
        $this->anotherClass = $anotherClass;
    }
}
```

produce:

```diff
+    private Alias $anotherClass;
```

which should be:

```diff
+    private AnotherClass $anotherClass;
```

by use as defined.

**Comment by samsonasik** [comment]
Fixed 🎉 with note on auto import enabled, and alias exists:

on the following code:

```php
use Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Source\AnotherClass;
use Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Source\AnotherClass as Alias;

final class ConflictWithAlias2
{
    /**
     * @var AnotherClass
     */
    private $anotherClass;

    public function __construct(AnotherClass $anotherClass)
    {
        $this->anotherClass = $anotherClass;
    }
}
```

It will still be changed to fqcn:

```diff
+    private \Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Source\AnotherClass $anotherClass;
```

that seems need to be handled in coding standard instead. 

If no alias of it, it will use short name, like in existing fixture:

https://github.com/rectorphp/rector-src/blob/3ff17513c47ace5c6a71ef4f918f33a8fa183a7b/rules-tests/Php74/Rector/Property/TypedPropertyRector/FixtureImported/already_imported_short_name.php.inc#L32

**Comment by samsonasik** [comment]
There is another use case for union type, eg:

```php
use Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Source\AnotherClass;
use Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Source\AnotherClass as Alias;

final class ConflictWithAlias2
{
    /**
     * @var AnotherClass|\stdClass
     */
    private $anotherClass;

    public function __construct(AnotherClass $anotherClass)
    {
        $this->anotherClass = $anotherClass;
    }

    public function setStdClass()
    {
        $this->anotherClass = new \stdClass;
    }
}
```

It will be changed to:

```diff
+ private Alias|stdClass|\Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Source\AnotherClass $anotherClass;
```

which will error again, it can happen ref https://3v4l.org/Rt3iA

**Comment by samsonasik** [comment]
I added another failing test for union types with alias.

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
It seems make constructor with param aliased in `PropertyTypeDeclarationRector` error:

```bash
1) Rector\Tests\TypeDeclaration\Rector\Property\PropertyTypeDeclarationRector\PropertyTypeDeclarationRectorTest::test with data set #8 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules-tests/TypeDeclaration/Rector/Property/PropertyTypeDeclarationRector/Fixture/constructor_param_with_aliased_param.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 
 class ConstructorParamWithAliasedParam
 {
-    /**
-     * @var Aliased
-     */
     private $aliasedParam;

     public function __construct(Aliased $aliasedParam)
```

**Comment by samsonasik** [comment]
I found another error on class nullable when alias exists:

```php
use Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Source\AnotherClass;
use Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Source\AnotherClass as Alias;

final class InvalidVarNullableValue
{
    /**
     * @var ?AnotherClass|\stdClass
     */
    private $anotherClass;

    public function __construct(AnotherClass $anotherClass)
    {
        $this->anotherClass = $anotherClass;
    }

    public function setStdClass()
    {
        $this->anotherClass = new \stdClass;
    }
}
```

It produce:

```diff
+    private Alias|\stdClass|\Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Source\AnotherClass $anotherClass;
```

which cause Parse error as well.

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
I added more fixture for skip nullable var union as existing functionailty, same functionality even without this patch https://github.com/rectorphp/rector-src/pull/899/commits/0032db7703c5d96078631a125d948247921662f8

**Comment by samsonasik** [comment]
I am merging it ;)

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
