### PR TITLE
Add failing test fixture for ClassPropertyAssignToConstructorPromotionRector

### PR DESCRIPTION
**Pull request by enumag**
# Failing Test for ClassPropertyAssignToConstructorPromotionRector

Based on https://getrector.org/demo/1ec00eec-bff3-666c-97f9-a71a05b309ed

### CODE REVIEW

**Comment by enumag** [comment]
hmm? something is wrong... this case is broken on demo https://getrector.org/demo/1ec00eec-bff3-666c-97f9-a71a05b309ed - both properties should be promoted... but somehow it doesn't fail as a test? was it fixed in master in the meantime? or is the new test ignored for some reason? :thinking:

**Comment by TomasVotruba** [comment]
The file must be in "Fixture" directory. İt seems this happens when you refresh page when creating a fixture.

**Comment by enumag** [comment]
@TomasVotruba Thanks! It's failing as intended now.

**Comment by enumag** [comment]
I tried to debug it myself. Wasn't able to fix it but I guess I can share my findings.

The property gets skipped because the types [here](https://github.com/rectorphp/rector-src/blob/d635cd54052cacd59f14ff78259db4434ed40639/rules/Php80/NodeAnalyzer/PromotedPropertyCandidateResolver.php#L186) are not equal.

`$matchedParamType` is `Y` while `$propertyType` is `UnionType` of `X` and `Y`.

Not sure if the problem is that these types should be considered as equal but aren't or if the UnionType wasn't supposed to get here.

**Comment by samsonasik** [comment]
It seems needs to loop the params to check coflict param type.

**Comment by enumag** [comment]
Well it seems to be analyzing the methods for some reason because the type X is apparently from the getX method. So one way to think about it is that X should not have been added to the union if it's a supertype of the property typehint. Another way to think about it is why are the methods even checked when the property already has a type given? I'm leaning towards saying that X shouldn't be in the Union at this point. Though how exactly to fix it I'm unsure.

**Comment by samsonasik** [comment]
@enumag  I cherry-picked your commit at PR https://github.com/rectorphp/rector-src/pull/722

**Pull request closed without merging**
