### PR TITLE
[Php80] Fix multiple cases and case mix up default for ChangeSwitchToMatchRector

### PR DESCRIPTION
**Pull request by samsonasik**
- fix add one more case on 2 cases with no stmt switch case.
- Also Closes https://github.com/rectorphp/rector-src/pull/230 Fixes https://github.com/rectorphp/rector/issues/6508

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by tuandp** [comment]
thanks @samsonasik

**Comment by TomasVotruba** [comment]
Thank you both :clap:

**Pull request merged**
