### PR TITLE
[EarlyReturn] Skip ReturnEarlyIfVariableRector with @var doc

### PR DESCRIPTION
**Pull request by samsonasik**
The following code should be skipped:

```php
final class SkipWithVarDoc
{
    public function run(int $value): int|string
    {
        if ($value === 50) {
            /** @var string $value */
            $value = execute();
        }

        return $value;
    }
}
```

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
:+1:

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
