### PR TITLE
[Php80] Handle crash Property ReflectionEnum::$betterReflectionClass does not exist on AddParamBasedOnParentClassMethodRector on Enum usage

### LINKED ISSUE #8126: [0.17.11] Issue with Enums
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.11            |

After upgrading to latest Rector version I'm getting this error related to Enums that I have in my codebase:
```
Could not process "<file-name>" file, due to:
ReflectionEnum::$betterReflectionClass does not exist
```

## Minimal PHP Code Causing Issue

Just have any kind of Enum in scanned files...

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8126
Ref https://getrector.com/demo/a1fd1e68-ba6b-4114-be3e-b2bd6932b018

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @rcerljenko @KennedyTedesco

**Comment by rcerljenko** [comment]
That was fast! Thanks!

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by KennedyTedesco** [comment]
Nice! Thank you.

**Pull request merged**
