### PR TITLE
[Php70] Fix delimiter in the middle on EregToPregMatchRector

### LINKED ISSUE #8850: EregToPcreTransformer won't work when string contains preg delimiter
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 1.2.6            |

I am new to Rector, reading the code rule by rule from Php70 to Php83 in order to understand how it performs migration, comparing Rector implementation with PHP migration notes, step by step.

First, I want to express my gratitude for this awesome work, second, I want to contribute.

## Minimal PHP Code Causing Issue

PHP file to migrate:

```PHP
<?php

final class DemoFile
{
    public function hasAnchors($text)
    {
        return (bool) ereg('Look for #anchors', $text);
    }
}
```

`Rectop.php`:

```PHP

<?php
use Rector\Config\RectorConfig;
use Rector\Php70\Rector\FuncCall\EregToPregMatchRector;

return RectorConfig::configure()
    ->withRules([
        EregToPregMatchRector::class,
    ]);
```

## Expected Behaviour

```diff
 {
     public function hasAnchors($text)
     {
-        return (bool) ereg('Look for #anchors', $text);
+        return (bool) preg_match('#Look for \#anchors#m', $text);
     }
 }
```

## Actual Behaviour

```diff
{
     public function hasAnchors($text)
     {
-        return (bool) ereg('Look for #anchors', $text);
+        return (bool) preg_match('#Look for #anchors#m', $text);
     }
 }
```

## Explanation

Having a doubt regarding `EregToPcreTransformer::transform()` ability to handle a string containing a preg delimiter, I added two basic cases in `EregToPcreTransformerTest::provideDataDropping()`:

```PHP
public static function provideDataDropping(): Iterator
{
    // missing previous code
    yield 'Simple string contains default delimiter' => ['#anchor', '#\#anchor#m'];
    yield 'Regexp string contains default delimiter' => ['A# (minor|major)', '#A\# (minor|major)#m'];
}
```

Below is the PHPUnit log, showing expected VS actual result of the method.

```bash
Failed asserting that two strings are identical.
Expected :'#\#anchor#m'
Actual   :'##anchor#m'
<Click to see difference>

/Users/corentin/localhost/sandbox/rector-src/rules-tests/Php70/EregToPcreTransformerTest.php:26

Failed asserting that two strings are identical.
Expected :'#A\# (minor|major)#m'
Actual   :'#A# \(minor\|major\)#m'
<Click to see difference>

/Users/corentin/localhost/sandbox/rector-src/rules-tests/Php70/EregToPcreTransformerTest.php:26
```

## Fixing attempt (and failure)

At first I thought a slight modification to `EregToPcreTransformer::transform()` would fix the issue:

```PHP
    public function transform(string $ereg, bool $isCaseInsensitive): string
    {
        // Case where delimiter would be escaped for a reason in original string still needs to be addressed.
        if (\str_contains($ereg, $this->pcreDelimiter)) {
            $ereg = str_replace($this->pcreDelimiter, '\\' . $this->pcreDelimiter, $ereg);
        }

        return $this->ere2pcre($ereg, $isCaseInsensitive);
    }
```

it appears it won't... And now, I understand that I will have to fully introspect `EregToPcreTransformer::_ere2pcre()` which is rather complex, so that I decided to report the bug instead of providing an actual PR, to avoid others to run into this case.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8850

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @corentin-larose

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it to have faster feedback to test ;)

**Comment by samsonasik** [comment]
@corentin-larose please try latest `"rector/rector": "dev-main"` and verify if it works and no regression ;)

**Comment by corentin-larose** [comment]
Seems to fix the problem indeed (tested on several fixtures I made locally), thanks.

**Pull request merged**
