### PR TITLE
[CS] Cs Fix config Skip AssignmentInConditionSniff FoundInWhileCondition

### PR DESCRIPTION
**Pull request by samsonasik**
Currently, the weekly cs fix github action got error:

```bash
------------------------------------------------------------------------
 packages/NodeNestingScope/FlowOfControlLocator.php:21
 ------------------------------------------------------------------------
 Variable assignment found within a condition. Did you mean to do a
comparison ?
 Reported by: "FoundInWhileCondition"
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 packages/NodeNestingScope/ParentFinder.php:37
 ------------------------------------------------------------------------
 Variable assignment found within a condition. Did you mean to do a
comparison ?
 Reported by: "FoundInWhileCondition"
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 rules/CodeQuality/Rector/Return_/SimplifyUselessVariableRector.php:111
 ------------------------------------------------------------------------
 Variable assignment found within a condition. Did you mean to do a
comparison ?
 Reported by: "FoundInWhileCondition"
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 rules/CodingStyle/Rector/Assign/ManualJsonStringToJsonEncodeArrayRector.php:188
 ------------------------------------------------------------------------
 Variable assignment found within a condition. Did you mean to do a
comparison ?
 Reported by: "FoundInWhileCondition"
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 rules/Php70/Rector/FuncCall/MultiDirnameRector.php:59
 ------------------------------------------------------------------------
 Variable assignment found within a condition. Did you mean to do a
comparison ?
 Reported by: "FoundInWhileCondition"
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 src/Application/FileProcessor.php:43
 ------------------------------------------------------------------------
 Variable assignment found within a condition. Did you mean to do a
comparison ?
 Reported by: "FoundInWhileCondition"
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 src/PhpParser/Node/BetterNodeFinder.php:66
 ------------------------------------------------------------------------
 Variable assignment found within a condition. Did you mean to do a
comparison ?
 Reported by: "FoundInWhileCondition"
 ------------------------------------------------------------------------
 [ERROR] Found 7 errors that need to be fixed manually.                         
```

which need to be skipped in the `ecs.php` config.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Do you know which set is causing it? It should be ignored directly in native ecs sets:
https://github.com/symplify/symplify/tree/main/packages/easy-coding-standard/config/set

So it does not bother users.

**Comment by samsonasik** [comment]
It seems skipped in control structur config:

https://github.com/symplify/symplify/blob/97b9107c69f15464a6dc5b4b3e801f3a3d699179/packages/easy-coding-standard/config/set/common/control-structures.php#L69-L71

Do you think the ecs.php need to import it?

**Comment by samsonasik** [comment]
I tried include `$containerConfigurator->import(SetList::CONTROL_STRUCTURES);` in ecs.php seems make error again

**Comment by samsonasik** [comment]
It seems importing `$containerConfigurator->import(SetList::CONTROL_STRUCTURES);` needs to be after Option Skip. I created PR https://github.com/rectorphp/rector-src/pull/774 for it.

**Pull request merged**
