### PR TITLE
Create do_not_duplicate_annotations.php.inc

### PR DESCRIPTION
**Pull request by mkrauss**
https://github.com/rectorphp/rector/issues/8101

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@samsonasik Could you look into this one?

**Comment by samsonasik** [comment]
@TomasVotruba this looks like related with duplicate when partial update, like in PR:

- https://github.com/rectorphp/rector-src/pull/1862

but on this case, on deletion annotation, I will check.

**Comment by samsonasik** [comment]
There was a patch for it, but removed 

https://github.com/rectorphp/rector-src/commit/e5d927505714bcffd0d8a1a334bd07aa6361ed1c

due to removal of rule `RemoveRedundantDefaultPropertyAnnotationValuesRector`

**Comment by samsonasik** [comment]
I see, the issue is new line after before closing parentheses on `@ApiDoc()` usage:

```php
    /**
     * @ApiDoc(
     *   description = "Some Description"
     *
     * )
```

changing to no new line before closing parentheses resolve it:

https://getrector.com/demo/2e89fc6c-4795-428d-8080-6d73692310f1

**Comment by samsonasik** [comment]
@TomasVotruba add new line before closing parentheses seems like a non standard way of annotation definition:

```php
    /**
     * @ApiDoc(
     *   description = "Some Description"
     *
     * )
```

with new line ( **not working** ): https://getrector.com/demo/ccf6adb1-c29a-46aa-97df-98fe051d5fd7
without new line ( **working** ): https://getrector.com/demo/2e89fc6c-4795-428d-8080-6d73692310f1

I will look more if it fixable.

**Comment by samsonasik** [comment]
@mkrauss I cherry-picked your commit at PR https://github.com/rectorphp/rector-src/pull/4795

**Pull request closed without merging**
