### PR TITLE
Create a test for the observed `IfToSpaceshipRector ` side effect

### PR DESCRIPTION
**Pull request by johnbillion**
For https://github.com/rectorphp/rector/issues/6937

### CODE REVIEW

**Comment by samsonasik** [comment]
@johnbillion CI seems all green, it can be various possibilties:

1. already resolved in `"rector/rector": "dev-main"`, could you try in case it already resolved?
2. possibly related with other rules applied, as in rector demo, you're using 

```php
$containerConfigurator->import(LevelSetList::UP_TO_PHP_72);
```

could you narrow down the rules applied via `--debug` or `-vvv` ?

**Comment by samsonasik** [comment]
@johnbillion ok, it seems you put the `sideeffect.php.inc` in an invalid location, you put in root directory instead of `rules-tests/Php70/Rector/If_/IfToSpaceshipRector/Fixture`

**Comment by samsonasik** [comment]
I copied your fixture at https://github.com/rectorphp/rector-src/pull/1696 to correct location

**Comment by johnbillion** [comment]
Thanks!

**Pull request closed without merging**
