### PR TITLE
[Php74] Skip TypedPropertyRector on final class by @final docblock

### LINKED ISSUE #7289: Add a way to ignore `@final` annotation.
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/752f2105-4970-4967-8a66-3e0636a6f39e

```php
<?php

/**
 * @final
 */
class DemoFile
{
    /** @var DemoFile */
    protected $foo;
}
```

### Responsible rules

* `TypedPropertyRector`

## Expected Behavior

Adding `@final` annotation doesn't forbid user to still extends the class. Also, the `@final` annotation might be added recently to a file and it will require a new major to declare the class final. Until this, adding the property typehint is still a BC-break.

So it would be helpful to have a way to not consider `@final` class as final. This way rector won't create BC break.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7289

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @VincentLanglet

**Comment by VincentLanglet** [comment]
Big thanks @samsonasik

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
