### PR TITLE
[Core] Remove deprecated addNodes?(?:Before|After)Node method on AbstractRector

### PR DESCRIPTION
**Pull request by samsonasik**
The methods are deprecated and the recommended way is to return array of nodes or use directly `$this->nodesToAddCollector->()` call.

### CODE REVIEW

**Comment by samsonasik** [comment]
it seems needs to be updated for sabbelasichon/typo3-rector that use it directly.

**Comment by samsonasik** [comment]
I created PR https://github.com/sabbelasichon/typo3-rector/pull/2818 for it.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by TomasVotruba** [comment]
Thank you for cleaning :slightly_smiling_face:

**Pull request merged**
