### PR TITLE
[Renaming] Handle crash on RenameFunctionRector with die() and $_SESSION usage

### LINKED ISSUE #8501: System error: "Node "PhpParser\Node\Expr\FuncCall" with is missing scope required for scope refresh
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |  1.0.1             |
| PHP version | 7.4.33

## Minimal PHP Code Causing Issue
https://getrector.com/demo/0dd1b8b2-9b6e-4268-8c3e-1129386afd4d

#### Code to be refactored:
```php
<?php

if ($_SESSION['order_in_progress'] != 1) {
    $isNewUIEnabled = true;

    if ($isNewUIEnabled) {
        if (
            isset($deliveryRequestResponse) &&
            !preg_match('/^Error/m', $deliveryRequestResponse) &&
            !empty($deliveryRequestResponse->delivery_tracking_url)
        ) {
            $trackingUrl = $deliveryRequestResponse->delivery_tracking_url;
            $_SESSION['checkout_success_tracking_url'] = $trackingUrl;
        }
        return;
    }
} else {
    die('Sorry, this order may already have been placed. If you did not receive a confirmation email, please give us a call to confirm your order.');
}

function insertorder()
{

    $result = abc('');
    if (!$result) {
        die(abc2());
    }
}

unset($_SESSION['cart']);
```

#### rector config:
```php
<?php

use Rector\Config\RectorConfig;
use Rector\TypeDeclaration\Rector\Property\TypedPropertyFromAssignsRector;
use Rector\Rector\AbstractRector;
use PhpParser\Node;
use Symplify\RuleDocGenerator\ValueObject\RuleDefinition;


class ChangeTest extends AbstractRector
{

    public function getRuleDefinition(): RuleDefinition
    {
        return new RuleDefinition(
            'qwertyuio', [
                new CodeSample(
                // code before
                    'qwerty',
                    // code after
                    'zxcvbn'
                ),
            ]
        );
    }

    public function getNodeTypes(): array
    {
        return [Node\Expr\FuncCall::class];
    }

    public function refactor(Node $node)
    {
        $functionCallName = $this->getName($node->name);
        if ($functionCallName === 'abc2') {
            $newFunName = 'abc';
            $node->name = new Node\Name($newFunName);
            return $node;
        }
        return null;
    }
}

return RectorConfig::configure()
    // A. whole set
    //->withPreparedSets(typeDeclarations: true)
    // B. or few rules
    //->withPaths([ __DIR__.'/test1.php',])
    ->withRules([
        //TypedPropertyFromAssignsRector::class
        ChangeTest::class
    ]);
```

It works on my local, when ...:
I remove `unset($_SESSION['cart']);`
I remove `die('Sorry, this order may already have been placed. If you did not receive a confirmation email, please give us a call to confirm your order.');`

On the demo portal, I see 500 error

### Terminal output:
[OK] 1 file has been changed by Rector

### Code change:
every function call named `abc2` to be changed to `abc`

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://getrector.com/demo/97f400c9-f64d-4adb-8c33-887d27af6360
Fixes https://github.com/rectorphp/rector/issues/8501

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @ahmadasjad

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by ahmadasjad** [comment]
Despite passing the given case, my content still shows the same error. Additional keywords may be causing it. I will keep you posted.

**Comment by samsonasik** [comment]
The website is updated per 6 hours, that will be shown green on next deploy, you can try `"rector/rector:"dev-main"` for now :)

**Comment by ahmadasjad** [comment]
Yeah, I tested after that. Also verified the code change in the `vendor` before testing

**Comment by samsonasik** [comment]
If you just want to rename func call, no need to create custom rule, you can use existing `RenameFunctionRector`:

```php
return RectorConfig::configure()
    ->withConfiguredRule(
        \Rector\Renaming\Rector\FuncCall\RenameFunctionRector::class,
        [
            'abc2' => 'abc',
        ]
    );
```

**Comment by ahmadasjad** [comment]
Thanks for the suggestion, but the actual requirement is not only renaming.

```php
<?php

if ($_SESSION['order_in_progress'] != 1) {

    $isNewUIEnabled = true;

    if ($isNewUIEnabled) {
        header('Location: /storefront/checkout/success');
        return;  // works if commented
    }
} else {
    die('Sorry, ');  // works if commented
}

function insertorder() {
    if (!empty($orderTaxDetails)) {

        abc($orderTaxQuery);
        if (abc2()) {
            return false;
        }
    }
}

echo $_SESSION['facebook_app_id']; // works if commented
```

In this case, it works if I comment out any of the below, not all.

- `return;`
- `die('Sorry, ');`
- `echo $_SESSION['facebook_app_id'];`

**Comment by samsonasik** [comment]
Could you reproduce at https://getrector.com/demo ? Thank you.

**Comment by ahmadasjad** [comment]
https://getrector.com/demo/2926e4e6-267f-4494-9925-cd1ec547d4dc

If anyone is commented out, it works.

**Comment by samsonasik** [comment]
Ok, I created PR https://github.com/rectorphp/rector-src/pull/5647 for it.

**Pull request merged**
