### PR TITLE
[Php80] Preserve int key defined not start from 0 on AnnotationToAttributeRector

### LINKED ISSUE #7345: Doctrine Annotation to Attributes - DiscriminatorMap: index for int should be preserved
Hi, Thanks a lot for your work.

Rector version: 80bfee9

Int-Indexed DiscriminatorMap lose there index after the conversion.

DoctrineSetList::ANNOTATIONS_TO_ATTRIBUTES,
SymfonySetList::ANNOTATIONS_TO_ATTRIBUTES

The index is getting lost. It starts with 0.
Problem: Doctrine does not find the entites anymore.

Before:
```
/** 
 * @ORM\Entity
 * @ORM\Table(name="tour_rbgl_billing")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="item_type", type="integer")
 * @ORM\DiscriminatorMap({ "1" = "CostDetailEntity" })
 */
```

After:

```
#[ORM\Entity]
#[ORM\Table(name: 'tour_rbgl_billing')]
#[ORM\InheritanceType('SINGLE_TABLE')]
#[ORM\DiscriminatorColumn(name: 'item_type', type: 'integer')]
#[ORM\DiscriminatorMap(['CostDetailEntity'])]

```

## Expected Behaviour

The index should be preserved.

```
#[ORM\DiscriminatorMap([1 => 'CostDetailEntity'])]
```

Special Case would be 0,1,2...N with increment by 1. In this case the actual behaviour is correct.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7345

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @Chris53897

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
:+1:

**Comment by Chris53897** [comment]
Thanks @samsonasik

**Pull request merged**
