### PR TITLE
[Php73] Add closure bindings for SimplifyForeachToArrayFilterRector.

### LINKED ISSUE #7594: Incorrect behavior of SimplifyForeachToArrayFilterRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |
| PHP | 7.3 |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/91353eb4-621a-42a9-89f2-a45f7605b514

```php
<?php

class FilterDefaultValue
{
    public function filter(array $records, $defaultValue): array
    {
        $nonDefault = [];
        foreach ($records as $key => $value) {
            if ($defaultValue !== $value) {
                $nonDefault[$key] = $value;
            }
        }

        return $nonDefault;
    }
}
```

### Responsible rules

* `SimplifyForeachToArrayFilterRector`

## Expected Behavior

The refactored code will work with PHP >= 7.4
https://3v4l.org/CHTtV

But for PHP 7.3, which don't support arrow function, the use statement for `$defaultValue` is missing
https://3v4l.org/1ORPl

### PR DESCRIPTION
**Pull request by Wohlie**
Fix https://github.com/rectorphp/rector/issues/7594

### CODE REVIEW

**Comment by samsonasik** [comment]
Could you fix the tests as well? `disableImportNames()` can be replaced with `importNames(false, false)`

**Comment by samsonasik** [comment]
@Wohlie I create PR

-  https://github.com/rectorphp/rector-src/pull/3147

to fix test error, please rebase after that PR merged.

**Comment by samsonasik** [comment]
Please rebase

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thanks

**Pull request merged**
