### PR TITLE
Added (failing) test for issue #6708

### PR DESCRIPTION
**Pull request by leoloso**
As requested in https://github.com/rectorphp/rector/issues/6708

### CODE REVIEW

**Comment by samsonasik** [comment]
I looked into this, somehow, the `DowngradeMatchToSwitchRector` doesn't know that the `expr` in `match` already changed by `DowngradeArraySpreadRector`.

 Feel free to patch if you found a way to fix it.

**Comment by samsonasik** [comment]
@leoloso I cherry-picked your commit at PR https://github.com/rectorphp/rector-src/pull/928 . The `$item2Unpacked` is go to before `switch` on this case.

**Comment by leoloso** [comment]
> The $item2Unpacked is go to before switch on this case.

That will not work, because the match can have many cases, and the vars may be called the same and override each other:

```php
public function run($operation)
{
    return match ($operation) {
        'fruits' => ['banana', 'orange', ...$this->getFirstArray()],
        'veggies' => ['tomato', 'lettuce', ...$this->getSecondArray()],
    };
}
```

would produce:

```php
public function run($operation)
{
    $item2Unpacked = $this->getFirstArray();
    $item2Unpacked = $this->getSecondArray();
    switch ($operation) {
        case 'fruits':
            return array_merge(['banana', 'orange'], $item2Unpacked);
        case 'veggies':
            return array_merge(['tomato', 'lettuce'], $item2Unpacked);
    }
}
```

**Comment by samsonasik** [comment]
Thank you, I added more test case https://github.com/rectorphp/rector-src/pull/928/commits/824da0ac9ca437866351fae37f6e6fd2d1522ede

**Pull request closed without merging**
