### PR TITLE
[TypeDeclaration] Skip anonymous class and other object on ReturnUnionTypeRector

### PR DESCRIPTION
**Pull request by samsonasik**
The following code should be skipped:

```php
final class SkipAnonymousClassAndOtherObject
{
    public function run()
    {
        if (rand(0,1)) {
            return new SkipAnonymousClassAndOtherObject();
        }

        return new class {};
    }
}
```

as it will cause fatal error even with `object|SkipAnonymousClassAndOtherObject` see https://3v4l.org/TFnZj

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 , I reverted `ReturnTypeInferer` native usage as seems already cover docblock already 

- https://github.com/rectorphp/rector-src/pull/4648

**Comment by samsonasik** [comment]
Ok, reverting `ReturnTypeInferer` to use `getType()` instead of `getNativeType()` cause invalid result on docblock

https://github.com/rectorphp/rector-src/actions/runs/5775375225/job/15653289866?pr=4670#step:5:39

I will check if it can be tweaked for special `New_` usage

**Comment by samsonasik** [comment]
Fixed 🎉 with class name anonymous detection https://github.com/rectorphp/rector-src/pull/4670/commits/69e2b41f3ca6469ec998d022344b352230debc99 in ClassAnalyzer

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
Also handled anonymous class with parent https://github.com/rectorphp/rector-src/pull/4670/commits/e16b7626b79697047c184d863d32d6dd98fc02b7 that covered by `NewTypeResolver`

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
