### PR TITLE
include typo3 rector in scoped version

### PR DESCRIPTION
**Pull request by TomasVotruba**
I had to create a new branch because you contributed from a fork.

Do you have access to create PRs locally in Rector right here? It would be easier to juggle PR next time
If not, we should fix it :)

### CODE REVIEW

**Comment by sabbelasichon** [comment]
Ups. That´s on my side. Regarding the tests. The stubs folder is missing intentionally. But still referenced in the extension.neon. Gonna fix it.

**Comment by TomasVotruba** [comment]
Yea, the phpstan config cannot be reference for public `config.php`
https://github.com/sabbelasichon/typo3-rector/pull/2354

I had to solve something similar today for Nette package:
- https://github.com/rectorphp/rector-nette/commit/f09392930bec2389eebb85636a665200d5b71e4e
- https://github.com/rectorphp/rector-nette/commit/69ea2b05552b5a29ffdc087d417d5bb768759537

**Comment by sabbelasichon** [comment]
I think i have no access for the rector-src repository.

**Comment by sabbelasichon** [comment]
I have created a new release 0.11.3. Hope this is working now.

**Comment by sabbelasichon** [comment]
Let´s call it a day. My eyes are falling down. Thanks a lot.

**Comment by TomasVotruba** [comment]
Same here :+1: :sleeping: 

We'll make this happen next week :) thank you for your pro-active pushing forward. It's amazing what you can do with your passionated mindset :fire:

**Comment by sabbelasichon** [comment]
I am on it.

**Comment by sabbelasichon** [comment]
Sorry for the all ping pong of the branches here. But i moved it to here: https://github.com/rectorphp/rector-src/pull/55

So you can close this branch.

**Comment by sabbelasichon** [comment]
@TomasVotruba Could you close this branch.

**Comment by TomasVotruba** [comment]
Sure :+1:

**Pull request closed without merging**
