### PR TITLE
[CodeQuality] Skip fluent call from FuncCall crash on OptionalParametersAfterRequiredRector

### LINKED ISSUE #8063: Call to undefined method BetterStandardPrinter::pPHPStan_Node_AlwaysRememberedExpr()
After running rector over my code I get the error
```
 [ERROR] Could not process "/var/www/html/app/JsonApi/Compare.php" file, due to:                                        
         "System error: "Call to undefined method                                                                       
         Rector\Core\PhpParser\Printer\BetterStandardPrinter::pPHPStan_Node_AlwaysRememberedExpr()"                     
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 483
                                                                                                                        
```

Running with debug-options returns the log:
```
                                                                                                                       
 [ERROR] Could not process "/var/www/html/app/JsonApi/Compare.php" file, due to:                                        
         "System error: "Call to undefined method                                                                       
         Rector\Core\PhpParser\Printer\BetterStandardPrinter::pPHPStan_Node_AlwaysRememberedExpr()"                     
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(504):                  
         PhpParser\PrettyPrinterAbstract->pFallback()                                                                   
         #1 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                  
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                  
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #3 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                  
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                  
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #5 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                  
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                  
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #7 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                  
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                  
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #9 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                  
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #10 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #11 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #12 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #13 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #15 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #17 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #18 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #19 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #20 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #21 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #22 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #23 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #24 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #25 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #26 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #27 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #28 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(616):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #29 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #30 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #31 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #32 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #33 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #34 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #35 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #36 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #37 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #38 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #39 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #40 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(538):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #41 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(140):                                 
         PhpParser\PrettyPrinterAbstract->p()                                                                           
         #42 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(801):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->p()                                                       
         #43 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(207):                                 
         PhpParser\PrettyPrinterAbstract->pArray()                                                                      
         #44 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(471):                 
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray()                                                  
         #45 vendor/rector/rector/src/PhpParser/Printer/BetterStandardPrinter.php(101):                                 
         PhpParser\PrettyPrinterAbstract->printFormatPreserving()                                                       
         #46 vendor/rector/rector/src/PhpParser/Printer/FormatPerservingPrinter.php(44):                                
         Rector\Core\PhpParser\Printer\BetterStandardPrinter->printFormatPreserving()                                   
         #47 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(192):                              
         Rector\Core\PhpParser\Printer\FormatPerservingPrinter->printParsedStmstAndTokensToString()                     
         #48 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(122):                              
         Rector\Core\Application\FileProcessor\PhpFileProcessor->printFile()                                            
         #49 vendor/rector/rector/packages/Parallel/WorkerRunner.php(136):                                              
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process()                                              
         #50 vendor/rector/rector/packages/Parallel/WorkerRunner.php(107): Rector\Parallel\WorkerRunner->processFile()  
         #51 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}()                                                      
         #52 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):                                        
         RectorPrefix202307\Evenement\EventEmitter->emit()                                                              
         #53 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202307\Clue\React\NDJson\Decoder->handleData()                                                     
         #54 vendor/rector/rector/vendor/react/stream/src/Util.php(62):                                                 
         RectorPrefix202307\Evenement\EventEmitter->emit()                                                              
         #55 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):                   
         RectorPrefix202307\React\Stream\Util::RectorPrefix202307\React\Stream\{closure}()                              
         #56 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):                                
         RectorPrefix202307\Evenement\EventEmitter->emit()                                                              
         #57 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):                                
         RectorPrefix202307\React\Stream\DuplexResourceStream->handleData()                                             
         #58 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):                                
         RectorPrefix202307\React\EventLoop\StreamSelectLoop->waitForStreamActivity()                                   
         #59 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):                                            
         RectorPrefix202307\React\EventLoop\StreamSelectLoop->run()                                                     
         #60 vendor/rector/rector/vendor/symfony/console/Command/Command.php(325):                                      
         Rector\Core\Console\Command\WorkerCommand->execute()                                                           
         #61 vendor/rector/rector/vendor/symfony/console/Application.php(944):                                          
         RectorPrefix202307\Symfony\Component\Console\Command\Command->run()                                            
         #62 vendor/rector/rector/vendor/symfony/console/Application.php(326):                                          
         RectorPrefix202307\Symfony\Component\Console\Application->doRunCommand()                                       
         #63 vendor/rector/rector/src/Console/ConsoleApplication.php(54):                                               
         RectorPrefix202307\Symfony\Component\Console\Application->doRun()                                              
         #64 vendor/rector/rector/vendor/symfony/console/Application.php(212):                                          
         Rector\Core\Console\ConsoleApplication->doRun()                                                                
         #65 vendor/rector/rector/bin/rector.php(132): RectorPrefix202307\Symfony\Component\Console\Application->run()  
         #66 vendor/rector/rector/bin/rector(5): require_once('...')                                                    
         #67 vendor/bin/rector(119): include('...')                                                                     
         #68 {main}". On line: 483                                                                                      
                               
```

The Compare-File:
```PHP
<?php

namespace App\JsonApi;

use App\JsonApi\Types\BaseItem;
use Exception;
use GuzzleHttp\Exception\GuzzleException;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use JsonException;

class Compare
{
    protected Client $client;

    public string $itemClassName;

    public string $modelClassName;

    public string $tableName;

    public string $model;

    /**
     * @throws GuzzleException
     */
    public function __construct($model, public ?string $endpointName = null)
    {
        $this->client = new Client($endpointName);
        $this->model = Str::of($model)->singular()->snake()->__toString();
        $this->modelClassName = Str::of($this->model)->studly()->prepend('App\\Models\\')->__toString();
        $this->itemClassName = Str::of($this->model)->studly()->prepend('App\\JsonApi\\Types\\')->append('Item')->__toString();
        $this->tableName = Str::of($this->model)->plural()->snake()->__toString();
    }

    public function databaseColumns(): array
    {
        return Schema::getColumnListing($this->tableName);
    }

    public function modelClassExists(): bool
    {
        return class_exists($this->modelClassName);
    }

    public function itemClass(): ?BaseItem
    {
        return class_exists($this->itemClassName) ? new ($this->itemClassName)() : null;
    }

    public function itemRegistered(): bool
    {
        return $this->client->hasModel($this->itemClassName);
    }

    public function itemClassExists(): bool
    {
        return class_exists($this->itemClassName);
    }

    public function getDefinedType(): ?string
    {
        try {
            return $this->client->getTypeByModel($this->model);
        } catch (Exception $e) {
            return null;
        }
    }

    public function getType(): ?string
    {
        $type = $this->getDefinedType();

        if (! $type) {
            $types = array_keys($this->client->call('/jsonapi')->getLinks()->toArray());
            $type = Arr::first($types, fn ($type) => Str::of($type)->endsWith($this->model));
        }

        return $type;
    }

    /**
     * @throws GuzzleException
     * @throws JsonException
     */
    public function getMissingDatabaseColumns(): array
    {
        $columns = $this->databaseColumns() ?? [];
        $creator = new Creator($this->getType(), $this->endpointName);
        $cleanedList = ['id' => true, ...$creator->getSchemaCleanedAttributes(), ...$creator->getSchemaCleanedRelations()];
        $ignoreList = $this->itemClass()?->ignoredAttributes() ?? [];
        $missingCleanedColumns = array_diff_key($cleanedList, array_flip($columns), array_flip($ignoreList));

        return collect($missingCleanedColumns)
            ->map(function ($column, $key) {
                switch ($key) {
                    case 'id':
                        return "{$key}:id";
                    case 'uuid':
                        return "{$key}:uuid:unique";
                    case 'uri':
                        return "{$key}:string:unique";
                    default:
                        if (! empty($column['asJson'])) {
                            return "{$key}:json:nullable";
                        }
                        $tableName = Str::of($key)->plural()->snake()->__toString();

                        return match ($column['type']) {
                            'array', 'object' => "{$key}:json:nullable",
                            'boolean' => "{$key}:boolean:default(".(empty($column['default']) ? 'false' : 'true').')',
                            'hasOne'  => "{$key}_id:foreignId:nullable:constrained({$tableName}):nullOnDelete",
                            'morphTo' => "{$key}:morphs",
                            'hasMany', 'morphToMany' => null,
                            default   => "{$key}:{$column['type']}:nullable",
                        };
                }
            })
            ->filter()
            ->all();
    }

    /**
     * @throws GuzzleException
     * @throws JsonException
     */
    public function modifyDatabase()
    {
        $mode = $this->databaseColumns() ? 'add' : 'create';
        $schema = $this->getMissingDatabaseColumns();

        Artisan::call('make:migration:schema', [
            'name'     => "{$mode}_{$this->tableName}_table",
            '--schema' => implode(',', $schema),
        ]);

        if (! $this->databaseColumns()) {
            Artisan::call('make:model', [
                'name' => basename($this->modelClassName),
            ]);
        }

        $creator = new Creator($this->getType(), $this->endpointName);
        $relations = $creator->getSchemaCleanedRelations();
        foreach ($relations as $key => $relation) {
            if ('hasMany' === $relation['type']) {
                Artisan::call('make:migration:pivot', [
                    'tableOne' => $this->tableName,
                    'tableTwo' => Str::of($key)->plural()->snake(),
                ]);
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8063
Ref https://getrector.com/demo/576513b9-85eb-48d8-88db-1e3507857c19

### CODE REVIEW

**Comment by samsonasik** [comment]
@Kauto this should fix https://github.com/rectorphp/rector/issues/8063, I tried in getrector.org server :)

**Comment by samsonasik** [comment]
@TomasVotruba the following use case need to be covered https://github.com/rectorphp/rector-src/pull/4533/commits/8009b39cc09e8f93cc882111658e09eab6e05290

```php
final class UpdateMethodCallByFluent
{
    public function run($optional = 1, $required)
    {
        return $this;
    }

    public function execute()
    {
    }

    public function process()
    {
        $this->run(1, 5)
             ->execute();
    }
}
```

The original functionality actually not working yet for above case even the hack reverted.

**Comment by samsonasik** [comment]
@TomasVotruba it seems actually working on proper fluent call return `$this` 

https://github.com/rectorphp/rector-src/pull/4533/commits/af5c351022fe09ab4038963508d2e779cd41bf24

👍

**Comment by samsonasik** [comment]
The buggy part will be on second part as fluent:

```php
final class UpdateMethodCallByFluent2
{
    public function execute()
    {
        return $this;
    }

    public function run($optional = 1, $required)
    {
        return $this;
    }

    public function process()
    {
        $this->execute()
             ->run(1, 5);
    }
}
```

**Comment by samsonasik** [comment]
Really unsure how to cover this, some process probably overlapped when tested in server

https://getrector.com/demo/576513b9-85eb-48d8-88db-1e3507857c19

@TomasVotruba probably the best way is to extends PHPStan printer ?

**Comment by TomasVotruba** [comment]
> Really unsure how to cover this, some process probably overlapped when tested in server

It might need some cache clearing, e.g. `/tmp/rector` and `/tmp/phpstan`

**Comment by samsonasik** [comment]
@TomasVotruba I tried that, not working, the issue is happen only on fluent call:

- fluent call (crash) https://getrector.com/demo/a8587d19-4108-4db8-ac90-fc80afae71ec
- non-fluent call (working ok) https://getrector.com/demo/dd9e789f-ce8d-4c33-962e-5e03f63c6165

**Comment by samsonasik** [comment]
Closing as resolved at PR:

- https://github.com/rectorphp/rector-src/pull/4629

**Pull request closed without merging**
