### PR TITLE
Add option to configure followLinks of finder

### LINKED ISSUE #6950: Make followLinks for finder configurable
In some cases it is really convenient if __DIR__ is used as the PATHS option. So basically take everything in this directory. 
In TYPO3-Context this is useful i.e. for standalone extensions, but this leads to an infinite loop.
Full explanation is here: https://github.com/rectorphp/rector/issues/6712

What i would like to have is at least the possibility to disable the follow symlink configuration for the finder via an option. 
Will provide a MR for that.

### PR DESCRIPTION
**Pull request by sabbelasichon**
Resolves: https://github.com/rectorphp/rector/issues/6950

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the PR 👍 

What happen when the parameter is set to false?
Could you provide simple test to confirm symlinks are disabled/enabled? Just in case the parameter service or finder change.

**Review by samsonasik — APPROVED** [review]

**Comment by sabbelasichon** [comment]
@TomasVotruba I have added two simple tests for that

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Comment by TomasVotruba** [comment]
I've noticed the PHPStan has this enabled by default: https://github.com/phpstan/phpstan-src/commit/0c356a4d5dd9496c1d55909df1de87d823e53e3b

So I think it's a way to go to enable it here too :+1:

**Comment by sabbelasichon** [comment]
@TomasVotruba It is enabled by default if the option does not exist. Maybe it is too hard to read

**Comment by TomasVotruba** [comment]
I see. Even better then 👍

**Comment by TomasVotruba** [comment]
Ref https://github.com/rectorphp/rector-src/pull/2112

**Pull request merged**
