### PR TITLE
[TypeDeclaration] Remove AddClosureReturnTypeRector

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba @staabm the `AddClosureReturnTypeRector` use docblock from method caller as return type, which invalid.

I think this rule can be removed and use more specific return type rules instead.

see https://getrector.com/demo/d2f40f82-855f-4414-adb5-7ae99cfc7ce0

### CODE REVIEW

**Comment by samsonasik** [comment]
see https://getrector.com/demo/d2f40f82-855f-4414-adb5-7ae99cfc7ce0

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by staabm** [comment]
don't we have a ReturnType*FromStrict rule which works on the same cases but with a native return type?

if so, maybe some of the test-cases can be moved into that rule

**Comment by samsonasik** [comment]
`ReturnTypeFromStrictTypedCallRector` already cover that, here the test:

- with only docblock (skipped) https://getrector.com/demo/3df87ced-340d-4355-bfe5-cbd9750c6a82
- with return type (applied) https://getrector.com/demo/1ee6c000-5afe-4681-aef2-d4a3a0edf963

**Comment by samsonasik** [comment]
@staabm I added test case by docblock for ReturnTypeFromStrictTypedCallRector https://github.com/rectorphp/rector-src/pull/4637/commits/7bf8ea1f4933d45f8aa97321250f760ff5f2e570

**Comment by TomasVotruba** [comment]
Awesome cleanup :tada: :+1:

**Pull request merged**
