### PR TITLE
add details about node traversal order 

### PR DESCRIPTION
**Pull request by rajyan**
Adding document for order of rectors, about node traversal order.

related
https://github.com/rectorphp/rector/issues/6472
https://github.com/rectorphp/rector/issues/5962

### CODE REVIEW

**Comment by rajyan** [comment]
@TomasVotruba 
I tried to create a PR. How is this?

**Comment by TomasVotruba** [comment]
Looks good, thanks :+1:

**Comment by samsonasik** [comment]
type hint need to be updated to fix PHPStan notice, you can cherry pick my commit at https://github.com/rectorphp/rector-src/pull/130/commits/2277ecd71e8ce450da6fda1f21e3a20b62d747ee

**Comment by rajyan** [comment]
thank you!

**Pull request merged**
