### PR TITLE
Update PHPDoc with missing type

### PR DESCRIPTION
**Pull request by villfa**

### CODE REVIEW

**Comment by samsonasik** [comment]
@villfa please rebase to make CI green for parallel tests.

**Comment by villfa** [comment]
Done

**Comment by villfa** [comment]
FYI now when I run `bin/rector process <my file>` I get this error:
````
 [ERROR] Call to undefined method
         "Symfony\Component\DependencyInjection\Loader\Configurator\ServiceConfigurator::configure()".
```

**Comment by samsonasik** [comment]
@villfa you need to remove `vendor` directory first and run `composer update`:

```bash
rm -rf vendor
composer update
```

**Comment by samsonasik** [comment]
Thank you @villfa

**Pull request merged**
