### PR TITLE
[StaticTypeMapper] Avoid error Rector\StaticTypeMapper\PhpDocParser\IdentifierTypeMapper::mapStatic() must implement interface PHPStan\Analyser\Scope, null given

### PR DESCRIPTION
**Pull request by samsonasik**
ref https://github.com/codeigniter4/CodeIgniter4/runs/4207582199?check_suite_focus=true#step:10:14

### CODE REVIEW

**Comment by TomasVotruba** [comment]
This should not be skipped, instead we have to find out why the scope is not present. Using nodes without scope randomly would break many rules. The scope must be always present.

Could you add reproducible test case?

**Comment by samsonasik** [comment]
I will try.

**Comment by samsonasik** [comment]
@TomasVotruba that seems happen on `clone $this` usage:

```bash
    [applying] Rector\CodeQuality\Rector\FuncCall\SimplifyRegexPatternRector
[post rectors] system/HTTP/Request.php
    [post rector] Rector\PostRector\Rector\NodeToReplacePostRector
    [post rector] Rector\PostRector\Rector\NodeAddingPostRector
    [post rector] Rector\PostRector\Rector\PropertyAddingPostRector
    [post rector] Ssch\TYPO3Rector\Rector\PostRector\FullQualifiedNamePostRector
    [post rector] Rector\PostRector\Rector\NodeRemovingPostRector
    [post rector] Rector\PostRector\Rector\ClassRenamingPostRector
PHP Fatal error:  Uncaught TypeError: Rector\StaticTypeMapper\PhpDocParser\IdentifierTypeMapper::mapStatic(): Argument #1 ($scope) must be of type PHPStan\Analyser\Scope, null given, called in /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/StaticTypeMapper/PhpDocParser/IdentifierTypeMapper.php on line 92 and defined in /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/StaticTypeMapper/PhpDocParser/IdentifierTypeMapper.php:132
Stack trace:
#0 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/StaticTypeMapper/PhpDocParser/IdentifierTypeMapper.php(92): Rector\StaticTypeMapper\PhpDocParser\IdentifierTypeMapper->mapStatic(NULL)
#1 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/StaticTypeMapper/PhpDoc/PhpDocTypeMapper.php(39): Rector\StaticTypeMapper\PhpDocParser\IdentifierTypeMapper->mapToPHPStanType(Object(PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode), Object(PhpParser\Node\Identifier), Object(PHPStan\Analyser\NameScope))
#2 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/StaticTypeMapper/StaticTypeMapper.php(97): Rector\StaticTypeMapper\PhpDoc\PhpDocTypeMapper->mapToPHPStanType(Object(PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode), Object(PhpParser\Node\Identifier), Object(PHPStan\Analyser\NameScope))
#3 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/NodeTypeResolver/PhpDocNodeVisitor/ClassRenamePhpDocNodeVisitor.php(52): Rector\StaticTypeMapper\StaticTypeMapper->mapPHPStanPhpDocTypeNodeToPHPStanType(Object(PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode), Object(PhpParser\Node\Identifier))
#4 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symplify/simple-php-doc-parser/src/PhpDocNodeTraverser.php(102): Rector\NodeTypeResolver\PhpDocNodeVisitor\ClassRenamePhpDocNodeVisitor->enterNode(Object(PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode))
#5 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symplify/simple-php-doc-parser/src/PhpDocNodeTraverser.php(123): RectorPrefix20211110\Symplify\SimplePhpDocParser\PhpDocNodeTraverser->traverseNode(Object(PHPStan\PhpDocParser\Ast\PhpDoc\ReturnTagValueNode))
#6 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symplify/simple-php-doc-parser/src/PhpDocNodeTraverser.php(175): RectorPrefix20211110\Symplify\SimplePhpDocParser\PhpDocNodeTraverser->traverseNode(Object(PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocTagNode))
#7 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symplify/simple-php-doc-parser/src/PhpDocNodeTraverser.php(97): RectorPrefix20211110\Symplify\SimplePhpDocParser\PhpDocNodeTraverser->traverseArray(Array)
#8 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symplify/simple-php-doc-parser/src/PhpDocNodeTraverser.php(74): RectorPrefix20211110\Symplify\SimplePhpDocParser\PhpDocNodeTraverser->traverseNode(Object(PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode))
#9 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/NodeTypeResolver/PhpDoc/NodeAnalyzer/DocBlockClassRenamer.php(35): RectorPrefix20211110\Symplify\SimplePhpDocParser\PhpDocNodeTraverser->traverse(Object(PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode))
#10 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/rules/Renaming/NodeManipulator/ClassRenamer.php(125): Rector\NodeTypeResolver\PhpDoc\NodeAnalyzer\DocBlockClassRenamer->renamePhpDocType(Object(Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfo), Array)
#11 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/rules/Renaming/NodeManipulator/ClassRenamer.php(103): Rector\Renaming\NodeManipulator\ClassRenamer->refactorPhpDoc(Object(PhpParser\Node\Stmt\ClassMethod), Array, Array)
#12 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/PostRector/Rector/ClassRenamingPostRector.php(37): Rector\Renaming\NodeManipulator\ClassRenamer->renameNode(Object(PhpParser\Node\Stmt\ClassMethod), Array)
#13 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): Rector\PostRector\Rector\ClassRenamingPostRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#14 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#15 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#16 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#17 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#18 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#19 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/PostRector/Application/PostFileProcessor.php(62): PhpParser\NodeTraverser->traverse(Array)
#20 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(94): Rector\PostRector\Application\PostFileProcessor->traverse(Array)
#21 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(144): Rector\Core\Application\FileProcessor\PhpFileProcessor->Rector\Core\Application\FileProcessor\{closure}(Object(Rector\Core\ValueObject\Application\File))
#22 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(97): Rector\Core\Application\FileProcessor\PhpFileProcessor->tryCatchWrapper(Object(Rector\Core\ValueObject\Application\File), Object(Closure), Object(Rector\Core\Enum\ApplicationPhase))
#23 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(76): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#24 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(57): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#25 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Console/Command/ProcessCommand.php(152): Rector\Core\Application\ApplicationFileProcessor->run(Array, Object(Rector\Core\ValueObject\Configuration))
#26 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symfony/console/Command/Command.php(274): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20211110\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211110\Symfony\Component\Console\Output\ConsoleOutput))
#27 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symfony/console/Application.php(870): RectorPrefix20211110\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20211110\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211110\Symfony\Component\Console\Output\ConsoleOutput))
#28 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symfony/console/Application.php(266): RectorPrefix20211110\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20211110\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211110\Symfony\Component\Console\Output\ConsoleOutput))
#29 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Console/ConsoleApplication.php(71): RectorPrefix20211110\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20211110\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211110\Symfony\Component\Console\Output\ConsoleOutput))
#30 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symfony/console/Application.php(162): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20211110\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211110\Symfony\Component\Console\Output\ConsoleOutput))
#31 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/bin/rector.php(63): RectorPrefix20211110\Symfony\Component\Console\Application->run()
#32 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/bin/rector(5): require_once('/Users/samsonas...')
#33 {main}
  thrown in /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/StaticTypeMapper/PhpDocParser/IdentifierTypeMapper.php on line 132

Fatal error: Uncaught TypeError: Rector\StaticTypeMapper\PhpDocParser\IdentifierTypeMapper::mapStatic(): Argument #1 ($scope) must be of type PHPStan\Analyser\Scope, null given, called in /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/StaticTypeMapper/PhpDocParser/IdentifierTypeMapper.php on line 92 and defined in /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/StaticTypeMapper/PhpDocParser/IdentifierTypeMapper.php:132
Stack trace:
#0 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/StaticTypeMapper/PhpDocParser/IdentifierTypeMapper.php(92): Rector\StaticTypeMapper\PhpDocParser\IdentifierTypeMapper->mapStatic(NULL)
#1 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/StaticTypeMapper/PhpDoc/PhpDocTypeMapper.php(39): Rector\StaticTypeMapper\PhpDocParser\IdentifierTypeMapper->mapToPHPStanType(Object(PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode), Object(PhpParser\Node\Identifier), Object(PHPStan\Analyser\NameScope))
#2 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/StaticTypeMapper/StaticTypeMapper.php(97): Rector\StaticTypeMapper\PhpDoc\PhpDocTypeMapper->mapToPHPStanType(Object(PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode), Object(PhpParser\Node\Identifier), Object(PHPStan\Analyser\NameScope))
#3 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/NodeTypeResolver/PhpDocNodeVisitor/ClassRenamePhpDocNodeVisitor.php(52): Rector\StaticTypeMapper\StaticTypeMapper->mapPHPStanPhpDocTypeNodeToPHPStanType(Object(PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode), Object(PhpParser\Node\Identifier))
#4 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symplify/simple-php-doc-parser/src/PhpDocNodeTraverser.php(102): Rector\NodeTypeResolver\PhpDocNodeVisitor\ClassRenamePhpDocNodeVisitor->enterNode(Object(PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode))
#5 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symplify/simple-php-doc-parser/src/PhpDocNodeTraverser.php(123): RectorPrefix20211110\Symplify\SimplePhpDocParser\PhpDocNodeTraverser->traverseNode(Object(PHPStan\PhpDocParser\Ast\PhpDoc\ReturnTagValueNode))
#6 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symplify/simple-php-doc-parser/src/PhpDocNodeTraverser.php(175): RectorPrefix20211110\Symplify\SimplePhpDocParser\PhpDocNodeTraverser->traverseNode(Object(PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocTagNode))
#7 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symplify/simple-php-doc-parser/src/PhpDocNodeTraverser.php(97): RectorPrefix20211110\Symplify\SimplePhpDocParser\PhpDocNodeTraverser->traverseArray(Array)
#8 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symplify/simple-php-doc-parser/src/PhpDocNodeTraverser.php(74): RectorPrefix20211110\Symplify\SimplePhpDocParser\PhpDocNodeTraverser->traverseNode(Object(PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode))
#9 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/NodeTypeResolver/PhpDoc/NodeAnalyzer/DocBlockClassRenamer.php(35): RectorPrefix20211110\Symplify\SimplePhpDocParser\PhpDocNodeTraverser->traverse(Object(PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocNode))
#10 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/rules/Renaming/NodeManipulator/ClassRenamer.php(125): Rector\NodeTypeResolver\PhpDoc\NodeAnalyzer\DocBlockClassRenamer->renamePhpDocType(Object(Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfo), Array)
#11 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/rules/Renaming/NodeManipulator/ClassRenamer.php(103): Rector\Renaming\NodeManipulator\ClassRenamer->refactorPhpDoc(Object(PhpParser\Node\Stmt\ClassMethod), Array, Array)
#12 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/PostRector/Rector/ClassRenamingPostRector.php(37): Rector\Renaming\NodeManipulator\ClassRenamer->renameNode(Object(PhpParser\Node\Stmt\ClassMethod), Array)
#13 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(176): Rector\PostRector\Rector\ClassRenamingPostRector->enterNode(Object(PhpParser\Node\Stmt\ClassMethod))
#14 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#15 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#16 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105): PhpParser\NodeTraverser->traverseArray(Array)
#17 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#18 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#19 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/PostRector/Application/PostFileProcessor.php(62): PhpParser\NodeTraverser->traverse(Array)
#20 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(94): Rector\PostRector\Application\PostFileProcessor->traverse(Array)
#21 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(144): Rector\Core\Application\FileProcessor\PhpFileProcessor->Rector\Core\Application\FileProcessor\{closure}(Object(Rector\Core\ValueObject\Application\File))
#22 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(97): Rector\Core\Application\FileProcessor\PhpFileProcessor->tryCatchWrapper(Object(Rector\Core\ValueObject\Application\File), Object(Closure), Object(Rector\Core\Enum\ApplicationPhase))
#23 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(76): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\File), Object(Rector\Core\ValueObject\Configuration))
#24 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Application/ApplicationFileProcessor.php(57): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\Core\ValueObject\Configuration))
#25 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Console/Command/ProcessCommand.php(152): Rector\Core\Application\ApplicationFileProcessor->run(Array, Object(Rector\Core\ValueObject\Configuration))
#26 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symfony/console/Command/Command.php(274): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20211110\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211110\Symfony\Component\Console\Output\ConsoleOutput))
#27 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symfony/console/Application.php(870): RectorPrefix20211110\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20211110\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211110\Symfony\Component\Console\Output\ConsoleOutput))
#28 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symfony/console/Application.php(266): RectorPrefix20211110\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20211110\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211110\Symfony\Component\Console\Output\ConsoleOutput))
#29 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/src/Console/ConsoleApplication.php(71): RectorPrefix20211110\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20211110\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211110\Symfony\Component\Console\Output\ConsoleOutput))
#30 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/vendor/symfony/console/Application.php(162): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20211110\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20211110\Symfony\Component\Console\Output\ConsoleOutput))
#31 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/bin/rector.php(63): RectorPrefix20211110\Symfony\Component\Console\Application->run()
#32 /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/bin/rector(5): require_once('/Users/samsonas...')
#33 {main}
  thrown in /Users/samsonasik/www/CodeIgniter4/vendor/rector/rector/packages/StaticTypeMapper/PhpDocParser/IdentifierTypeMapper.php on line 132
```

Looking at the node:

```bash
PhpParser\Node\Stmt\ClassMethod #32216
   flags: 1
   byRef: false
   name: PhpParser\Node\Identifier #32217
   |  name: 'withMethod'
   |  attributes: array (12) ...
   params: array (1)
   |  0 => PhpParser\Node\Param #32218 ...
   returnType: null
   stmts: array (3)
   |  0 => PhpParser\Node\Stmt\Expression #32220 ...
   |  1 => PhpParser\Node\Stmt\Expression #32225 ...
   |  2 => PhpParser\Node\Stmt\Return_ #32231 ...
   attrGroups: array (0)
   attributes: array (16)
   |  'startLine' => 121
   |  'startTokenPos' => 288
   |  'comments' => array (1) ...
   |  'endLine' => 128
   |  'endTokenPos' => 322
   |  'parent' => PhpParser\Node\Stmt\Class_ #32025 ...
   |  'previous' => PhpParser\Node\Stmt\ClassMethod #32203 ...
   |  'statementOrder' => 8
   |  'statementDepth' => 2
   |  'next' => PhpParser\Node\Stmt\ClassMethod #32233 ...
   |  'scope' => PHPStan\Analyser\MutatingScope #27239 ...
   |  'origNode' => PhpParser\Node\Stmt\ClassMethod #11842 ...
   |  'useNodes' => array (1) ...
   |  'previousExpression' => PhpParser\Node\Stmt\ClassMethod #32203 ...
   |  'currentExpression' => PhpParser\Node\Stmt\ClassMethod #32216 RECURSION
   |  'php_doc_info' => Rector\BetterPhpDocParser\PhpDocInfo\PhpDocInfo #41418 ...
```

The `withMethod()` call `clone $this;`, need to find out what rule that call it.

**Comment by samsonasik** [comment]
@TomasVotruba it seems there is issue on `RenameClassRector`, on debugging, I can see it error on rector-phpunit phpunit80 set list on changing:

```php
'PHPUnit_Framework_MockObject_MockObject' => 'PHPUnit\Framework\MockObject\MockObject',
```

https://github.com/rectorphp/rector-phpunit/blob/42663b3b206449c4b8271f3be80d73b42763052f/config/sets/phpunit80.php#L40

which seems looking at `PHPUnit_Framework_MockObject_MockObject` Object Type.

I still can't found a reproducible via test case yet. It seems due to multiple rules applied.

ref for github action that show the error https://github.com/codeigniter4/CodeIgniter4/runs/4207582199?check_suite_focus=true#step:10:12

**Comment by samsonasik** [comment]
@TomasVotruba I created PR https://github.com/rectorphp/rector-src/pull/1243 for it.

**Pull request merged**
