### PR TITLE
[Core] BetterStandardPrinter performance improvement: avoid regex check on no Closure Uses and no ClassMethod ReturnType

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
typo3-rector installation error seems unrelated:

```bash
Error: Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires rector/rector-src dev-main#4711b33cdcd5b092503857477801cba9d2c00313 -> satisfiable by rector/rector-src[dev-main].
    - rector/rector-src dev-main requires composer/xdebug-handler ^2.0 -> satisfiable by composer/xdebug-handler[2.0.0, ..., 2.0.x-dev].
    - You can only install one version of a package, so only one of these can be installed: composer/xdebug-handler[2.0.0, ..., 2.0.x-dev, 3.0.0, 3.0.1].
    - friendsofphp/php-cs-fixer dev-master requires composer/xdebug-handler ^3.0 -> satisfiable by composer/xdebug-handler[3.0.0, 3.0.1].
    - Root composer.json requires friendsofphp/php-cs-fixer dev-master as 3.3 -> satisfiable by friendsofphp/php-cs-fixer[dev-master].


  Problem 1
    - Root composer.json requires rector/rector-src dev-main#4711b33cdcd5b092503857477801cba9d2c00313 -> satisfiable by rector/rector-src[dev-main].
    - rector/rector-src dev-main requires composer/xdebug-handler ^2.0 -> satisfiable by composer/xdebug-handler[2.0.0, ..., 2.0.x-dev].
    - You can only install one version of a package, so only one of these can be installed: composer/xdebug-handler[2.0.0, ..., 2.0.x-dev, 3.0.0, 3.0.1].
    - friendsofphp/php-cs-fixer dev-master requires composer/xdebug-handler ^3.0 -> satisfiable by composer/xdebug-handler[3.0.0, 3.0.1].
    - Root composer.json requires friendsofphp/php-cs-fixer dev-master as 3.3 -> satisfiable by friendsofphp/php-cs-fixer[dev-master].
    -
```

**Comment by samsonasik** [comment]
@sabbelasichon rector-src require-dev friendsofphp/php-cs-fixer: ^3.4:

https://github.com/rectorphp/rector-src/blob/3fd890bd89401bfe84259501a2b6e6ae90539399/composer.json#L66

while `ssch/typo3-rector` require `friendsofphp/php-cs-fixer": "dev-master as 3.3` 

https://github.com/sabbelasichon/typo3-rector/blob/0005a2ae25a5445471d8127571f7edfaa7b836ff/composer.json#L19

**Comment by samsonasik** [comment]
@sabbelasichon I created PR https://github.com/sabbelasichon/typo3-rector/pull/2774 for using php-cs-fixer ^3.4

**Comment by samsonasik** [comment]
I set require --dev php-cs-fixer ^3.4 in packages-tests for typo3-rector workflow while wait for https://github.com/sabbelasichon/typo3-rector/pull/2774 to be merged.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
I've just merged the typo3 PR. Could you rebase?

**Comment by samsonasik** [comment]
@TomasVotruba rebased.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
