### PR TITLE
[CodeQuality] Remove DateTimeToDateTimeInterfaceRector as mostly opinionated and way too much generics

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by samsonasik** [comment]
Various tests directories can be removed as was only happen when `DateTimeToDateTimeInterfaceRector` exists:

```bash
rm -rf tests/Issues/IssueChangeAndIfAndDateTimeAndDeMorgan
rm -rf tests/Issues/IssueChangeAndIfReturnContinueDateTime
rm -rf tests/Issues/IssueEarlyReturnAndOrDatetime
```

**Comment by TomasVotruba** [comment]
Awesome, thank you :+1:

**Comment by norberttech** [comment]
hey @TomasVotruba is there any chance this could get back? I have been using it here: 
https://github.com/amazon-php/sp-api-sdk

Code of this SDK is autogenerated, it accepts \DateTime as API endpoint/models arguments, instead of \DateTimeInterface. 

Unless there is any other way to achieve what I need without knowing every single occurance of DateTime in the codebase?

**Comment by TomasVotruba** [comment]
Hi, it's great to hear the interest. The DateTime is actually big topic in PHP community. We won't put it back for reasons above, but this would deserve own community extension :). 
Ideally by someone who use it and has experience with it. Do you take the leap?

**Comment by norberttech** [comment]
Sorry Tomas, I would love to take it over but the frequency of BC breaks in rector is so high that maintaining anything outside of the main repo is a suicide mission. I will look for some other solution, anyway thanks for the answer!

**Comment by TomasVotruba** [comment]
It might have been in the past but we got pretty stable, also thanks to stable PHPStan type resolving.
This rule in particular only depends on PHPStan types to resolve, so it's safe to just copy paste the code here.

**Pull request merged**
