### PR TITLE
[TypeDeclaration] Handle return self on TypedPropertyFromStrictGetterMethodReturnTypeRector on php 8.0 feature enabled

### PR DESCRIPTION
**Pull request by samsonasik**
Closes https://github.com/rectorphp/rector-src/pull/3085

### CODE REVIEW

**Comment by samsonasik** [comment]
It seems cause error on `DowngradeSelfTypeDeclarationRector`:

```bash
 2) Rector\Tests\DowngradePhp70\Rector\ClassMethod\DowngradeSelfTypeDeclarationRector\DowngradeSelfTypeDeclarationRectorTest::test with data set #1 ('/home/runner/work/rector-src/...hp.inc')
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 
 class Fixture
 {
-    /**
-     * @return $this
-     */
-    public function getSelf()
+    public function getSelf(): self
     {
         return $this;
     }
```

The at least php version check possibly needed.

**Comment by samsonasik** [comment]
@TomasVotruba the patch seems needs to be in both here and `rector-downgrade-php`'s `PhpDocFromTypeDeclarationDecorator::decorateReturnWithSpecificType()`  which verify `SelfStaticType`

https://github.com/rectorphp/rector-downgrade-php/blob/d5a52d643513c66fc23270aa4748a564508ccc1d/src/PhpDocDecorator/PhpDocFromTypeDeclarationDecorator.php#L155

due to the mapper used in both:

- rector-src
- rector-downgrade-php

**Comment by samsonasik** [comment]
@TomasVotruba I created PR to rector-downgrade-php that required for it:

- https://github.com/rectorphp/rector-downgrade-php/pull/28

that need to be merged first **before this**.

**Comment by samsonasik** [comment]
Build restarted

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
Let's merge and verify scoped build

**Comment by samsonasik** [comment]
@TomasVotruba it works 🎉 

Screen Shot 2022-11-23 at 17 15 13

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
