### PR TITLE
[Renaming] Skip renaming method call on RenameMethodRector when both old and new exists, which implements interface as config

### LINKED ISSUE #7155: Error RenameMethodRector for symfony
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |

## Minimal PHP Code Causing Issue

Rector rename the function `getUsername` to `getUserIdentifier` while it should not:

```php
<?php

use Symfony\Component\Security\Core\User\UserInterface;

class User implements UserInterface
{
    private ?string $username = null;
    private ?array $roles = [];

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): void
    {
        $this->username = $username;
    }

    public function getRoles(): array
    {
        return $this->roles;
    }

    public function setRoles(?array $roles): void
    {
        $this->roles = $roles;
    }

    public function eraseCredentials(): void
    {
        // do nothing
    }

    public function getUserIdentifier(): string
    {
        return 'somethingElse';
    }
}

class UserUtils
{
    public static function updateIdentifier(User $user): void
    {
        if (!empty($user->getUsername())) {
            // something
        }
    }
}
```
```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Symfony\Set\SymfonySetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
        SymfonySetList::SYMFONY_60,
    ]);
};

```
Output:
```
    ---------- begin diff ----------
@@ @@
 {
     public static function updateIdentifier(User $user): void
     {
-        if (!empty($user->getUsername())) {
+        if (!empty($user->getUserIdentifier())) {
             // something
         }
     }
    ----------- end diff -----------

Applied rules:
 * RenameMethodRector
 * AddParamTypeDeclarationRector
 * AddReturnTypeDeclarationRector
```

I couldn't reproduce the error on https://getrector.org/demo as the error occur only when the class implements `Symfony\Component\Security\Core\User\UserInterface`.

I created this repository to reproduce: https://github.com/Lenny4/RenameMethodRectorError

```bash
git clone git@github.com:Lenny4/RenameMethodRectorError.git
composer install
vendor/bin/rector process src --dry-run
```

## Expected Behaviour

The function `getUsername` should not be rename.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7155

Same like `ClassMethod` skipper behaviour, when `MethodCall` or `StaticCall` called while both of source of `ClassmeMethod` old and new exists which implements interface s configuration, it should be skipped.

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @Lenny4

**Comment by samsonasik** [comment]
@Lenny4 it seems cause error on typo3 package

```
There was 1 failure:

1) Ssch\TYPO3Rector\Tests\Rector\v10\v0\DatabaseRecordListRector\DatabaseRecordListRectorTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
tests/Rector/v10/v0/DatabaseRecordListRector/Fixture/database_record_list_renaming.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 $databaseRecordList = GeneralUtility::makeInstance(DatabaseRecordList::class);
 $thumbCode = BackendUtility::thumbCode([], 'foo', 'bar');
 
-$uri = $databaseRecordList->listURL();
+$uri = $databaseRecordList->requestUri();
```

which seems both old and new one exists, it seems it needs to be skipped only when applied to interface.

**Comment by samsonasik** [comment]
I updated to verify that caller is a class that implements interface, which both old and new method exists, and the configured rule is by interface.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I am merging it ;)

**Review by TomasVotruba — COMMENTED** [review]
Very good 😊

**Pull request merged**
