### PR TITLE
[NodeTypeResolver] Handle crash after next exit() on no namespaced code after removal next attribute

### LINKED ISSUE #7972: Scope not available on "PhpParser\Node\Name\FullyQualified" node
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector c9fc74baf53ce9104403c492fcd13dec435dad9c           |

This only started erroring recently, Ive ignored it because the MLYMMFMSr6.php file is not part of my project - its the Opcache Control Panel file from https://gist.github.com/ck-on/4959032/?ocp.php but Im guessing you would like rector to not fail on such code 

```
[ERROR] Could not process "/Users/phil/Sites/manage.mysites.guru/public/MLYMMFMSr6.php" file, due to:
         "System error: "Scope not available on "PhpParser\Node\Name\FullyQualified" node with parent node of
         "PhpParser\Node\Expr\ConstFetch", but is required by a refactorWithScope() method of
         "Rector\Renaming\Rector\Name\RenameClassRector" rule. Fix scope refresh on changed nodes first"

         Stack trace:
         #0 vendor/rector/rector/src/Rector/AbstractRector.php(234):
         Rector\Core\Rector\AbstractScopeAwareRector->refactor(Object(PhpParser\Node\Name\FullyQualified))
         #1 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113):
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Name\FullyQualified))
         #2 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(133):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\ConstFetch))
         #3 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Param))
         #4 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #5 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Function_))
         #6 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(105):
         PhpParser\NodeTraverser->traverseArray(Array)
         #7 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(196):
         PhpParser\NodeTraverser->traverseNode(Object(Rector\Core\PhpParser\Node\CustomNode\FileWithoutNamespace))
         #8 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85):
         PhpParser\NodeTraverser->traverseArray(Array)
         #9 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(42):
         PhpParser\NodeTraverser->traverse(Array)
         #10 vendor/rector/rector/src/Application/FileProcessor.php(60):
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
         #11 vendor/rector/rector/src/Application/FileProcessor/PhpFileProcessor.php(115):
         Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration))
         #12 vendor/rector/rector/packages/Parallel/WorkerRunner.php(144):
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\Fil
         e), Object(Rector\Core\ValueObject\Configuration))
         #13 vendor/rector/rector/packages/Parallel/WorkerRunner.php(114):
         Rector\Parallel\WorkerRunner->processFile(Object(Rector\Core\ValueObject\Application\File),
         Object(Rector\Core\ValueObject\Configuration), Array)
         #14 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)
         #15 vendor/rector/rector/vendor/clue/ndjson-react/src/Decoder.php(117):
         RectorPrefix202306\Evenement\EventEmitter->emit('data', Array)
         #16 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         RectorPrefix202306\Clue\React\NDJson\Decoder->handleData(Array)
         #17 vendor/rector/rector/vendor/react/stream/src/Util.php(62):
         RectorPrefix202306\Evenement\EventEmitter->emit('data', Array)
         #18 vendor/rector/rector/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
         RectorPrefix202306\React\Stream\Util::RectorPrefix202306\React\Stream\{closure}('{"action":"main...')
         #19 vendor/rector/rector/vendor/react/stream/src/DuplexResourceStream.php(154):
         RectorPrefix202306\Evenement\EventEmitter->emit('data', Array)
         #20 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(201):
         RectorPrefix202306\React\Stream\DuplexResourceStream->handleData(Resource id #3035)
         #21 vendor/rector/rector/vendor/react/event-loop/src/StreamSelectLoop.php(173):
         RectorPrefix202306\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
         #22 vendor/rector/rector/src/Console/Command/WorkerCommand.php(63):
         RectorPrefix202306\React\EventLoop\StreamSelectLoop->run()
         #23 vendor/rector/rector/vendor/symfony/console/Command/Command.php(325):
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202306\Symfony\Component\Console\Input\A
         rgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
         #24 vendor/rector/rector/vendor/symfony/console/Application.php(944):
         RectorPrefix202306\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202306\Symfony\Component\
         Console\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
         #25 vendor/rector/rector/vendor/symfony/console/Application.php(326):
         RectorPrefix202306\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Work
         erCommand), Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvInput),
         Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
         #26 vendor/rector/rector/src/Console/ConsoleApplication.php(49):
         RectorPrefix202306\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202306\Symfony\Component\Co
         nsole\Input\ArgvInput), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
         #27 vendor/rector/rector/vendor/symfony/console/Application.php(212):
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202306\Symfony\Component\Console\Input\ArgvIn
         put), Object(RectorPrefix202306\Symfony\Component\Console\Output\ConsoleOutput))
         #28 vendor/rector/rector/bin/rector.php(132): RectorPrefix202306\Symfony\Component\Console\Application->run()
         #29 vendor/rector/rector/bin/rector(5): require_once('/Users/phil/Sit...')
         #30 vendor/bin/rector(119): include('/Users/phil/Sit...')
         #31 {main}". On line: 53
```

## Minimal PHP Code Causing Issue

Run rector on this file https://gist.github.com/ck-on/4959032/?ocp.php

using any one of these set lists will cause the issue

```
    $rectorConfig->sets(
        [
// Choose one of the following
            SwiftmailerSetList::SWIFTMAILER_TO_SYMFONY_MAILER,
            TwigSetList::TWIG_240,
            SymfonySetList::SYMFONY_62,
            LevelSetList::UP_TO_PHP_82,
        ]
    );
```

## Expected Behaviour

Not to crash :)

### PR DESCRIPTION
**Pull request by samsonasik**
After removal of `next` attribute, on no namespaced code, the stmts collected via `FileWithoutNamespaceNodeTraverser` which seems late detect the `UnreachableStatementNode` next stmt handling cause crash.

This PR try to fix https://github.com/rectorphp/rector/issues/7972

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @PhilETaylor

**Comment by PhilETaylor** [comment]
Confirmed this PR works - thanks. 🎉

# Before

ScreenShot-2023-06-05-09 50 15

# After manually applying change to packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php only 

ScreenShot-2023-06-05-09 48 52

**Comment by samsonasik** [comment]
@PhilETaylor thank you for verify, PHPStan notice seems unrelated, I will fix that in separate PR.

**Comment by samsonasik** [comment]
Restart build.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
