### PR TITLE
[CodeQuality][EarlyReturn] Handle DateTimeToDateTimeInterfaceRector + ChangeAndIfToEarlyReturnRector + ChangeOrIfContinueToMultiContinueRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
class Fixture
{
    public $data = [];

    public function get(array $data, $a, $b, $c, $result): string
    {
        foreach ($data as $value) {
            if ($a || ($b && $c)) {
                continue;
            }

            $this->data[$result] = $value;
        }

        if (! isset($this->data[$result])) {
            return 'a';
        }

        return $this->data[$result];
    }
}
```

It produce repetitive ifs and continue:

```diff
-
+            if (!$b) {
+                continue;
+            }
+            if (!$c) {
+                continue;
+            }
+            if (!$b) {
+                continue;
+            }
+            if (!$c) {
+                continue;
+            }
+            if (!$b) {
+                continue;
+            }
+            if (!$c) {
+                continue;
+            }
+            if (!$b) {
+                continue;
+            }
+            if (!$c) {
+                continue;
+            }
+            if (!$b) {
+                continue;
+            }
+            if (!$c) {
+                continue;
+            }
+            if (!$b) {
+                continue;
+            }
+            if (!$c) {
+                continue;
+            }
+            if (!$b) {
+                continue;
+            }
+            if (!$c) {
+                continue;
+            }
+            if (!$b) {
+                continue;
+            }
+            if (!$c) {
+                continue;
+            }
+            if ($b && $c) {
+                continue;
+            }
+            continue;
+            continue;
+            continue;
+            continue;
+            continue;
+            continue;
+            continue;
+            continue;
```

rules applied:

```php
Rector\CodeQuality\Rector\ClassMethod\DateTimeToDateTimeInterfaceRector;
Rector\EarlyReturn\Rector\If_\ChangeAndIfToEarlyReturnRector;
Rector\EarlyReturn\Rector\If_\ChangeOrIfContinueToMultiContinueRector;
```

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you!

**Comment by TomasVotruba** [comment]
Btw, you can merge these loop bugs yourself 👍

**Comment by samsonasik** [comment]
Ok 👍

**Pull request merged**
