### PR TITLE
 [DeadCode] Skip fluent no return type on RemoveUnusedPrivateMethodRector take 2

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://github.com/rectorphp/rector-src/pull/6108#issuecomment-2208470144

- [x] skip called on last
- [x] allow remove if never called on fluent

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by OA** [comment]
Hey @samsonasik thanks for fixing this! Any ETA when this will be released? 😄

**Comment by samsonasik** [comment]
You can use `"rector/rector": "dev-main"` for now ;)

**Comment by TomasVotruba** [comment]
@OA We usually do release once 2-3 weeks, once few more fixes pile up :)

**Pull request merged**
