### PR TITLE
[ReturnTypeDeclarationRector] Prevent object&mixed intersection type

### PR DESCRIPTION
**Pull request by Bl00D4NGEL**
# Failing Test for ReturnTypeDeclarationRector

Based on https://getrector.org/demo/1ec7d498-839c-6cee-a374-593f1a1ffe03

solves https://github.com/rectorphp/rector/issues/6966

### CODE REVIEW

**Comment by samsonasik** [comment]
It seems needs to be moved to FixtureForPhp81 dir https://github.com/rectorphp/rector-src/tree/main/rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp81

**Comment by Bl00D4NGEL** [comment]
> It seems needs to be moved to FixtureForPhp81 dir https://github.com/rectorphp/rector-src/tree/main/rules-tests/TypeDeclaration/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp81

Renamed the file to PreventObjectIntersectionType

**Comment by samsonasik** [comment]
The fixture file need to be moved to directory `FixtureForPhp81` to show the Intersection type

**Comment by Bl00D4NGEL** [comment]
> The fixture file need to be moved to directory `FixtureForPhp81` to show the Intersection type

Absolutely right, I should start properly reading, my bad :)

**Comment by samsonasik** [comment]
@Bl00D4NGEL I cherry-picked your commit at PR https://github.com/rectorphp/rector-src/pull/1727

**Pull request closed without merging**
