### PR TITLE
Add class-string typehint to MethodCallRename

### PR DESCRIPTION
**Pull request by alexander-schranz**
Avoid problem like: https://github.com/rectorphp/rector-symfony/pull/209 via phpstan static code analyzer.

### CODE REVIEW

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thanks 👍

Could ypu update other value objects that take class string as input?

**Comment by alexander-schranz** [comment]
@TomasVotruba done!

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you @alexander-schranz :clap:

**Comment by TomasVotruba** [comment]
I just realized why we avoided this one :D 
https://github.com/rectorphp/rector-symfony/runs/7705700412?check_suite_focus=true

The PHPStan now reports hundreds false positives everywhere.
The class does not have to exist during writing the configuration. We have to revert this one.

**Comment by alexander-schranz** [comment]
Okay make sense 🙈

**Pull request merged**
