### PR TITLE
[Scoped] Update to symfony 6.1.* and symfony/contracts 3.1.*

### LINKED ISSUE #7193: Update to Symfony 6.1
# Feature Request

We currently use symfony 6.0.* in rector-src, when upgrading to 6.1.* with the following steps:

1. Update symfony 6.0.* to 6.1.*

```diff
-        "symfony/console": "6.0.*",
+        "symfony/console": "6.1.*",
```

2. run the following command:

```bash
bin/rector process vendor/symfony/dependency-injection/Loader/XmlFileLoader.php --config build/config/config-downgrade.php --dry-run -vvv --clear-cache
```

the downgrade symfony/dependency-injection will get the following error:

```bash

[file] vendor/symfony/dependency-injection/Loader/XmlFileLoader.php
[rule] Rector\DowngradePhp73\Rector\FuncCall\DowngradeTrailingCommasInFunctionCallsRector

[file] vendor/symfony/dependency-injection/Loader/XmlFileLoader.php
[rule] Rector\DowngradePhp81\Rector\FuncCall\DowngradeFirstClassCallableSyntaxRector


In ChangedNodeScopeRefresher.php line 59:
                                                                                                                          
  [Rector\Core\Exception\ShouldNotHappenException]                                                                        
  Node "PhpParser\Node\Expr\StaticCall" with parent of "PhpParser\Node\Arg" is missing scope required for scope refresh.  
                                                                                                                          

Exception trace:
  at /Users/samsonasik/www/rector-src/src/Application/ChangedNodeScopeRefresher.php:59
```

Looking at the error, it seems happen on `DowngradeFirstClassCallableSyntaxRector`, on debugging, it error on the following part:

https://github.com/rectorphp/rector-src/blob/be3e2e1f9bad07daafa43189fdfcf31ab8579465/src/Application/ChangedNodeScopeRefresher.php#L51-L59

which means:

```php
\Closure::fromCallable(array($this, 'validateSchema'))
```

has parent `Arg`, which it seems need to be moved to a dedicated stmt instead:

```diff
-$dom = XmlUtils::loadFile($file, $this->validateSchema(...));
+$validateSchema = \Closure::fromCallable(array($this, 'validateSchema'));
+$dom = XmlUtils::loadFile($file, $validateSchema);
```

### PR DESCRIPTION
**Pull request by samsonasik**
This PR Update to symfony 6.1.* and symfony/contracts 3.1.* with updated scoped script:

- [x] Update `symfony/*` components to `6.1.*`
- [x] Update `symfony/contracts` components to `3.1.*`
- [x] early downgrade individual function `vendor/symfony/string/Resources/functions.php` as like `src/functions`, it just bypassed without early execute
- [x] skip `vendor/symfony/contracts/Cache` from `parallel-lint` check as skipped in `downgrade-config.php`
- [x] Update `full_build.sh` script to verify with run locally.

I tested in locally and it seems working ok:

Screen Shot 2022-06-02 at 22 23 33

Fixes https://github.com/rectorphp/rector/issues/7193

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba PHPStan error seems from symplify `SingleNetteInjectMethodRule`:

On debugging, it got error:
 
 ```bash
 vendor/bin/phpstan analyse bin/rector.php --ansi --error-format symplify --debug
 
Note: Using configuration file /Users/samsonasik/www/rector-src/phpstan.neon.
/Users/samsonasik/www/rector-src/bin/rector.php
Uncaught Error: Call to a member function toString() on null in /Users/samsonasik/www/rector-src/vendor/symplify/phpstan-rules/packages/nette/src/Rules/SingleNetteInjectMethodRule.php:109
#0 /Users/samsonasik/www/rector-src/vendor/symplify/phpstan-rules/packages/nette/src/Rules/SingleNetteInjectMethodRule.php(43): Symplify\PHPStanRules\Nette\Rules\SingleNetteInjectMethodRule->resolveClassMethodNames(Object(PHPStan\Node\ClassMethodsNode))
#1 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(102): Symplify\PHPStanRules\Nette\Rules\SingleNetteInjectMethodRule->processNode(Object(PHPStan\Node\ClassMethodsNode), Object(PHPStan\Analyser\MutatingScope))
#2 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(555): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PHPStan\Node\ClassMethodsNode), Object(PHPStan\Analyser\MutatingScope))
#3 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(296): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#4 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(189): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#5 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(61): PHPStan\Analyser\FileAnalyser->analyseFile('/Users/samsonas...', Array, Object(PHPStan\Rules\Registry), NULL)
#6 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(62): PHPStan\Analyser\Analyser->analyse(Array, Object(Closure), NULL, true, Array)
#7 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(141): PHPStan\Command\AnalyserRunner->runAnalyser(Array, Array, Object(Closure), NULL, true, true, '/Users/samsonas...', NULL, NULL, Object(_PHPStan_1d2f63169\Symfony\Component\Console\Input\ArgvInput))
#8 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(66): PHPStan\Command\AnalyseApplication->runAnalyser(Array, Array, true, '/Users/samsonas...', Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), Object(_PHPStan_1d2f63169\Symfony\Component\Console\Input\ArgvInput))
#9 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(168): PHPStan\Command\AnalyseApplication->analyse(Array, true, Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), false, true, '/Users/samsonas...', Array, Object(_PHPStan_1d2f63169\Symfony\Component\Console\Input\ArgvInput))
#10 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_1d2f63169\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_1d2f63169\Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(856): _PHPStan_1d2f63169\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_1d2f63169\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_1d2f63169\Symfony\Component\Console\Output\ConsoleOutput))
#12 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(259): _PHPStan_1d2f63169\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_1d2f63169\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_1d2f63169\Symfony\Component\Console\Output\ConsoleOutput))
#13 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_1d2f63169\Symfony\Component\Console\Application->doRun(Object(_PHPStan_1d2f63169\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_1d2f63169\Symfony\Component\Console\Output\ConsoleOutput))
#14 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(120): _PHPStan_1d2f63169\Symfony\Component\Console\Application->run()
#15 phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(121): _PHPStan_1d2f63169\{closure}()
#16 /Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan(8): require('phar:///Users/s...')
#17 /Users/samsonasik/www/rector-src/vendor/bin/phpstan(117): include('/Users/samsonas...')
#18 {main}
```

**Comment by TomasVotruba** [comment]
See https://github.com/phpstan/phpstan-src/commit/d0a9d084ea66be4afdf965dd51e1b6d91d36c6b7#r75178623

**Comment by samsonasik** [comment]
@TomasVotruba thank you 👍 , we can retry phpstan build after https://github.com/symplify/symplify/pull/4110 applied.

**Comment by samsonasik** [comment]
Temporary pin phpstan to 1.7.8 based on https://github.com/rectorphp/rector-src/pull/2420/commits/7dc28854da8896f5fc0c35c3c8a8bec34e86f602

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you 👍

**Comment by samsonasik** [comment]
It s seems `rector-prefixed-downgraded/vendor/symfony/contracts/HttpClient` need to be skipped from parallel lint as well.

**Pull request merged**
