### PR TITLE
Use new type isser from PHPStan

### PR DESCRIPTION
**Pull request by yguedidi**
inspired by #3568

It may help Rector refactor more code :)

### CODE REVIEW

**Comment by yguedidi** [comment]
@TomasVotruba @samsonasik I need guidance on the right way to fix the few `instanceof ArrayType` marked as `@todo` in the fixup commit.
Migrating them to `isArray()` breaks the tests, as it allows an `UnionType` of arrays (e.g. `array<Foo>|array<Bar>`) pass the `isArray()->yes()` check.

**Comment by staabm** [comment]
I also had a look at these in the past. I think rector really want to detect just native arrays and not unions in the sense PHPStan interprets it.

I am not sure the isXX api works for these things here as rector needs it

**Comment by samsonasik** [comment]
@yguedidi you can extract to multiple PRs per type, that will be easy review/merge 👍

**Comment by yguedidi** [comment]
> that will be easy review/merge

@samsonasik I thought a review by commit was enough to be easy

> I am not sure the isXX api works for these things here as rector needs it

@staabm but I think I saw that using `instanceof *Type` will be deprecated and Type object inheritance removed one day, so better migrate asap IMO

**Comment by samsonasik** [comment]
Smaller PR with all green CI is always on finished state, that can be on continuation with merge immediatelly without slowing down

**Comment by yguedidi** [comment]
Fine by me, will follow your recommandation

**Comment by yguedidi** [comment]
closed in favor of multiple specific PRs

**Pull request closed without merging**
