### PR TITLE
[Core] Remove RectifiedNode value object for RectifiedAnalyzer

### PR DESCRIPTION
**Pull request by samsonasik**
With consecutive last passed Rector rule correctly handled at PR:

- https://github.com/rectorphp/rector-src/pull/3078

The `RectifiedNode` value object that previously used to save last previously run Rector rule no longer needed, so it can be removed 
https://github.com/rectorphp/rector-src/pull/3079/files#diff-5c5469b5b3ba8256b58b9d9bf66fe5873b03597965174036968f5b0d1513a565

~~It require verify phpstan_cache_printer attribute exists to decorate attribute CREATED_BY_RULE when refactor() call returns null.~~
It require connect refactored Node with existing `Node`s for previous and next node.

By this, we finally get rid of unnecessary save `Node` and `Rector` rule into object as it already in `CREATED_BY_RULE` :tada: 🎉 🎉

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
Rebased.

**Comment by samsonasik** [comment]
PHPStan notice is unrelated;

```bash
Run vendor/bin/phpstan
Note: Using configuration file /home/runner/work/rector-src/rector-src/phpstan.neon.
   0/394 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
 394/394 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

Error: Ignored error pattern #Parameter \#1 \$class of method Rector\\BetterPhpDocParser\\PhpDocInfo\\PhpDocInfo<PHPStan\\PhpDocParser\\Ast\\Node\>\:\:(.*?)\(\) expects class\-string, string given# was not matched in reported errors.
 -- --------------------------------------------------------------------------- 
     Error                                                                      
 -- --------------------------------------------------------------------------- 
     Ignored error pattern #Parameter \#1 \$class of method                     
     Rector\\BetterPhpDocParser\\PhpDocInfo\\PhpDocInfo<PHPStan\\PhpDocParser\  
     \Ast\\Node>\:\:(.*?)\(\) expects class\-string, string given# was not      
     matched in reported errors.      
```

**Comment by samsonasik** [comment]
Ok, the PHPStan notice seems can be ignored.

**Comment by samsonasik** [comment]
It seems the PHPStan notice in rector-symfony:

```bash
➜  rector-symfony git:(main) composer phpstan
> vendor/bin/phpstan analyse --ansi --error-format symplify

 ! [NOTE] The Xdebug PHP extension is active, but "--xdebug" is not used. This may  
 !        slow down performance and the process will not halt at breakpoints.       

Note: Using configuration file /Users/samsonasik/www/rector-symfony/phpstan.neon.
 394/394 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


                                                                                    
 [WARNING] Ignored error pattern #Parameter \#1 \$class of method                   
           Rector\\BetterPhpDocParser\\PhpDocInfo\\PhpDocInfo<PHPStan\\PhpDocParser\</>
           Ast\\Node>\:\:(.*?)\(\) expects class\-string, string given# was not     
           matched in reported errors.                                              
                                                                                    

Script vendor/bin/phpstan analyse --ansi --error-format symplify handling the phpstan event returned with error code 1
```

**Comment by samsonasik** [comment]
PHPStan notice fixed at https://github.com/rectorphp/rector-symfony/pull/277

**Comment by samsonasik** [comment]
Restart build.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
I found that phpstan_cache_printer check not really needed, only verify against Expr is enough 👍 https://github.com/rectorphp/rector-src/pull/3079/commits/099c91422232cb5c720f43be8f6b4a73a39b8f0d

**Comment by samsonasik** [comment]
@TomasVotruba Finally 🎉 🎉 🎉 , I found the real solution, after `refactor()`, the refactored Node need to immediatelly connected with its existing Node previous and next node. https://github.com/rectorphp/rector-src/pull/3079/commits/5cbe7a95d26e293d67948f2393085089695f41fb

**Comment by samsonasik** [comment]
All checks have passed 🎉 🎉 🎉 @TomasVotruba I think it is ready 🎉 🎉 🎉

**Comment by samsonasik** [comment]
I added test to prove that existing `addNodeBeforeNode()` on a rule usage keep working 👍 https://github.com/rectorphp/rector-src/pull/3079/commits/a165e83087a9dae473c0e6a32a9dd766b2566ba5

**Comment by samsonasik** [comment]
I also added test fixture to prove `addNodeAfterNode()` on Next Stmt when there is already another stmt already, which the next stmt will be inserted between node and existing next node https://github.com/rectorphp/rector-src/pull/3079/commits/9561e665de577baddbec57b7afa92e857166caf3 👍

**Comment by samsonasik** [comment]
All checks have passed 🎉 🎉 🎉 @TomasVotruba I think it is ready 🎉 🎉 🎉

**Comment by TomasVotruba** [comment]
Thank you 👍😊 It looks like a lot of effort, great job 👌

Feel free to merge when ready 👍

**Pull request merged**
