### PR TITLE
Enable auto-merge on weekly pull request

### PR DESCRIPTION
**Pull request by samsonasik**
To make auto-merge like in getrector.org repo. It needs to use `secrets.ACCESS_TOKEN` in create pull request to make CI run and `id` to make auto-merge merge the pr from create pull request steps.

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba the error seems on symplify's part:

```bash
PHP Fatal error:  Uncaught _HumbugBox2acd634d137b\Nette\DI\ServiceCreationException: Service '0236': 
Class Symplify\PHPStanRules\Rules\PreferredMethodCallOverIdenticalCompareRule not found. in phar:///home/runner/work/rector-src/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php:110
```

**Comment by samsonasik** [comment]
It seems the PHPStan rules service are not found:

```
- PreferredMethodCallOverIdenticalCompareRule
- OnlyOneClassMethodRule
- RequireClassTypeInClassMethodByTypeRule
```

**Comment by samsonasik** [comment]
rebased, PHPStan seems working now.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thanks, let's give this a try!

**Comment by TomasVotruba** [comment]
The "close button" position moves exactly to "comment" button position and I clickem both very quickly :D  sry

**Pull request merged**
