### PR TITLE
[Renaming] Skip docblock rename different namespace on RenameClassRector

### LINKED ISSUE #7201: RenameClassRector: Replaces in docblock before looking at imported classes
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.3             |

Rector does not look on imported classes when using RenameClassRector and seems to just replace the import because it has the same name.

## Minimal PHP Code Causing Issue
https://getrector.org/demo/7c97f090-6514-40bf-ade6-a47357542830
https://getrector.org/demo/e5a7803d-a357-4d91-8d08-e44a8e07a4a7

## Expected Behaviour

Nothing should be replaced here.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7201

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @eigan

**Comment by samsonasik** [comment]
Temporary pin phpstan to 1.7.8 based on https://github.com/rectorphp/rector-src/pull/2420/commits/7dc28854da8896f5fc0c35c3c8a8bec34e86f602

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
rebased.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by eigan** [comment]
That was fast! Thanks @samsonasik 😃

**Pull request merged**
