### PR TITLE
[Php81] Skip override abstract method on NewInInitializerRector

### PR DESCRIPTION
**Pull request by samsonasik**
when in __construct, there is abstract method __construct, it will cause error:

```bash
Fatal error: Declaration of SkipOverrideAbstractMethod::__construct(DateTime $dateTime = <expression>) must be compatible with OverrideAbstractMethod::__construct(?DateTime $dateTime = null)
```

ref https://3v4l.org/FdaVl

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1: Interesting use case. 

I've never seen `abstract` constructor :) where have you found it?

**Comment by samsonasik** [comment]
I can't remember where the actual use case is, but I ever seen @ezimuel use it (it possibly in interface) for constuctor enforcement, ref for use case https://3v4l.org/WaAqn

We may need to handle in override construct from interface as well.

**Comment by ezimuel** [comment]
@samsonasik I'm sorry but I don't remember where I used. Anyway, I think it's an interesting pattern, even if today I would prefer to use more an interface/trait to achieve the same result.

**Pull request merged**
