### PR TITLE
Added failling declare-strict test

### PR DESCRIPTION
**Pull request by staabm**
currently declare-strict is added twice

see https://getrector.com/demo/8f12e669-40a2-406e-aea8-0067d8418876

### CODE REVIEW

**Comment by samsonasik** [comment]
That's seems only on FileWithoutNamespace, with next InlineHTML node, as detecting first node is first node stmts itself, on namespace, it works as expected https://getrector.com/demo/28f3b784-3697-4578-94d5-8e3452f9b3c5

**Comment by samsonasik** [comment]
I will look into it

**Comment by samsonasik** [comment]
@staabm I cherry-picked your commit at PR https://github.com/rectorphp/rector-src/pull/3648

**Comment by staabm** [comment]
thank you

**Pull request closed without merging**
