### PR TITLE
[DowngradePhp80] Add DowngradeReflectionClassGetConstantsFilterRector

### LINKED ISSUE #6877: Add Downgrade ReflectionClassConstant::IS_* on get constant name and value from ReflectionClass
# Feature Request

Given the following code: 

```php
class A
{
    public const A1 = 'A1 Value';
    protected const A2 = 'A2 Value';
    private const A3 = 'A3 Value';
}

```

in PHP 8.0+, we can code:

```diff
$reflectionClass = new ReflectionClass('A');
+var_dump($reflectionClass->getConstants(ReflectionClassConstant::IS_PUBLIC));
```

It stil no downgrade rule to downgrade it to be like this in PHP 7.x:

```diff
$reflectionClass = new ReflectionClass('A');
+$reflectionClassConstants = $reflectionClass->getReflectionConstants();
+$result = [];
+array_walk($reflectionClassConstants, function ($value) use (&$result) {
+    if ($value->isPublic()) {
+       $result[$value->getName()] = $value->getValue();
+    }
+});
+var_dump($result);
```

Ref https://github.com/rectorphp/rector/issues/6864 which currently manually fixed by downgrade to php 7.x compatible syntax at https://github.com/rectorphp/rector-src/pull/1474

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6877

### CODE REVIEW

**Comment by samsonasik** [comment]
implemented 🎉

**Comment by samsonasik** [comment]
I reverted temporary patch on https://github.com/rectorphp/rector-src/pull/1474 that's use php 7.x compatible code to use php 8.0 code https://github.com/rectorphp/rector-src/pull/1529/commits/82e7863ffe542a27f36c552ad010492e8566f7d9, and try downgrade it: 

```
bin/rector process src/DependencyInjection/Collector/ConfigureCallValuesCollector.php -c build/config/config-downgrade.php --dry-run
```

and it seems working ok 🎉 

Screen Shot 2021-12-19 at 23 55 42

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks :clap: :+1:

**Pull request merged**
