### PR TITLE
Remove RemoveMethodCallParamRector, as unused

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by brandonkelly** [comment]
@TomasVotruba We were using this in [craftcms/rector](https://github.com/craftcms/rector). Can you please bring it back?

**Comment by TomasVotruba** [comment]
Thanks for getting back with usage feedback, I'll rever this one :+1:

**Comment by TomasVotruba** [comment]
Ref https://github.com/rectorphp/rector-src/pull/4244

**Comment by ericanderson-artisandm** [comment]
Is there a planned date for the release including this fix?

**Comment by samsonasik** [comment]
@ericanderson-artisandm 0.17.2 just released https://github.com/rectorphp/rector/releases/tag/0.17.2

**Pull request merged**
