### PR TITLE
Temporary pin to phpstan 1.10.30

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba here lets try.

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba the downgrade seems cause syntax error

https://github.com/rectorphp/rector-src/actions/runs/5966007434/job/16184720897#step:14:64

```
------------
Parse error: rector-prefixed-downgraded/vendor/rector/rector-symfony/rules/CodeQuality/Rector/BinaryOp/ResponseStatusCodeRector.php:135
    133|         return $this->literalCallLikeConstFetchReplacer->replaceArgOnPosition(
    134|             $methodCall,
  > 135|             new  (ObjectType, ), }),
```

I will check.

**Comment by samsonasik** [comment]
@TomasVotruba this is strange, the error is another error:

```
"System error: "Trying to replace statement (Stmt_Namespace) with      
         expression (Expr_MethodCall). Are you missing a Stmt_Expression        
         wrapper?"          
```

https://github.com/rectorphp/rector-src/actions/runs/5966007434/job/16185421625#step:10:21

it probably another issue in other area: eg: github memory issue or other dependency.

**Comment by TomasVotruba** [comment]
Indeed. This used to happen in the past, when error was somewhere else. 
Some stmts are re-printed with old stmts. Not sure where to look.

Let's try lower PHPStan version for now.

**Comment by TomasVotruba** [comment]
Ha, 3rd time the charm :) seems good now :laughing:

**Comment by samsonasik** [comment]
Ok, let's enable `NewOptimizedDirectorySourceLocator` again at https://github.com/rectorphp/rector-src/pull/4846

**Comment by TomasVotruba** [comment]
So the code deployed Rector has a bug here: https://github.com/rectorphp/rector/commit/562d3d830d0b55338210a34afb0d987a13371d73#diff-c585c0ab75fb4772ba1c57880f79ddba43d8adff91c47cd7a33be753beb4f7a2

**Comment by samsonasik** [comment]
Let's rebuild again, as everything rolled back, as last working is 6 hours ago

https://github.com/rectorphp/rector-src/commit/21f33de2b90c0e63d42c3ebebef7cf4415191a21

**Comment by samsonasik** [comment]
@TomasVotruba working ok now 

https://github.com/rectorphp/rector/commit/a28209cafca193c82d252654eff6e2b18d4443c8#diff-c585c0ab75fb4772ba1c57880f79ddba43d8adff91c47cd7a33be753beb4f7a2

so it definatelly github glich :)

**Pull request merged**
