### PR TITLE
[DeadCode] Skip using coealesce assign operator on return on RemoveUnusedPrivatePropertyRector

### PR DESCRIPTION
**Pull request by samsonasik**
The following code should be skipped:

```php
final class SkipUsingCoalesceAssignOperator
{
    private SomeService $someService;

    private array $types = [];

    public function __construct(SomeService $someService)
    {
        $this->someService = $someService;
    }

    public function get(string $key)
    {
        return $this->types[$key] ??= $this->someService->resolve();
    }
}
```

### CODE REVIEW

**Comment by samsonasik** [comment]
Using coealesce assign operator can be used to cache value to no need refill when already filled.

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
The next check possibly need check because `AssignOp` is part of `self::MODIFYING_NODE_TYPES`

```
        if ($parent !== null && $this->typeChecker->isInstanceOf($parent, self::MODIFYING_NODE_TYPES)) {
            return true;
        }
```

**Comment by samsonasik** [comment]
it seems can be handled by check current stmt is Expression

**Comment by samsonasik** [comment]
that seems cause invalid result:

```diff
+    /**
+     * @var int
+     */
+    private const I = 0;
     public function __construct(
         private readonly TypeFactory $typeFactory,
@@ @@
         $unionedTypes = [];
         foreach ($collectedNestedArrayTypes as $collectedNestedArrayType) {
             $arrayType = $collectedNestedArrayType->getType();
-            for ($i = 0; $i < $collectedNestedArrayType->getArrayNestingLevel(); ++$i) {
+            for (; self::I < $collectedNestedArrayType->getArrayNestingLevel(); ++self::I) {
                 $arrayType = new ArrayType($collectedNestedArrayType->getKeyType(), $arrayType);
             }
    ----------- end diff -----------
Applied rules:
 * ChangeReadOnlyVariableWithDefaultValueToConstantRector
 [ERROR] Could not process "rules/Arguments/ArgumentDefaultValueReplacer.php"   
         file, due to:                                                          
         "System error: "Syntax error, unexpected ')', expecting '[' or         
         T_OBJECT_OPERATOR or T_NULLSAFE_OBJECT_OPERATOR or '{':184"            
         Run Rector with "--debug" option and post the report here:             
        [ https://github.com/rectorphp/rector/i](https://github.com/rectorphp/rector/issues/new)
ssues/new". On line: 54
```

**Comment by samsonasik** [comment]
Let's [locate AssignOp in current stmt](https://github.com/rectorphp/rector-src/pull/2476/commits/88f1674fa6bd07279f9d2f6331b39aa1f11a61e2)

**Comment by samsonasik** [comment]
it seems cause error in other rule:

```diff

There was 1 failure:
1) Rector\Tests\Php81\Rector\Property\ReadOnlyPropertyRector\ReadOnlyPropertyRectorTest::test with data set #6 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules-tests/Php81/Rector/Property/ReadOnlyPropertyRector/Fixture/skip_array_dim_fetch_from_array_object_in_assign_var.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 final class SkipArrayDimFetchFromArrayObjectInAssignVar
 {
-    private ArrayObject $array;
+    private readonly ArrayObject $array;
```

**Comment by samsonasik** [comment]
Fixed by verify class constains local property fetch  https://github.com/rectorphp/rector-src/pull/2476/commits/fd3542a1bb8b77597735f166e87759313a663d82 , set flag to removed on removal property fetch

**Comment by samsonasik** [comment]
it seems cause another error:

```diff
There was 1 failure:
1) Rector\Core\Tests\Issues\SplitMultiAssignRemovePrivate\SplitMultiAssignRemovePrivateTest::test with data set #1 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
tests/Issues/SplitMultiAssignRemovePrivate/Fixture/multi_assign_extract.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 final class MultiAssignExtract
 {
-    private $content_type;
-
     public function run()
```

**Comment by samsonasik** [comment]
fixed with check total property fetch that removed goes to 0 before removing property https://github.com/rectorphp/rector-src/pull/2476/commits/1e505645cff5da53be6e4029679f825967659c64

**Comment by samsonasik** [comment]
it seems it cause error in other rules:

```diff
There were 2 failures:
1) Rector\Tests\Naming\Rector\Class_\RenamePropertyToMatchTypeRector\RenamePropertyToMatchTypeRectorTest::test with data set #18 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules-tests/Naming/Rector/Class_/RenamePropertyToMatchTypeRector/Fixture/skip_used_by_trait.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
     /**
      * @var EliteManager
      */
-    private $eventManager;
+    private $eliteManager;
     public function __construct(EliteManager $eventManager)
     {
-        $this->eventManager = $eventManager;
+        $this->eliteManager = $eventManager;
     }
 }
/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:154
/home/runner/work/rector-src/rector-src/packages/Testing/PHPUnit/AbstractRectorTestCase.php:115
/home/runner/work/rector-src/rector-src/rules-tests/Naming/Rector/Class_/RenamePropertyToMatchTypeRector/RenamePropertyToMatchTypeRectorTest.php:18
2) Rector\Tests\Php74\Rector\Property\TypedPropertyRector\TypedPropertyRectorTest::test with data set #52 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules-tests/Php74/Rector/Property/TypedPropertyRector/Fixture/static_property_filled_by_trait.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 {
     use FillerTrait;
-    /**
-     * @var AnotherClass
-     */
-    private static $someStaticProperty;
+    private static \Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Source\AnotherClass $someStaticProperty;
 }
```

**Comment by samsonasik** [comment]
it seems property fetch in trait can't get parent ClassLike, resolved by count as is https://github.com/rectorphp/rector-src/pull/2476/commits/5e3643ba80fde0c33e8e6d0cbbbe16a804bd8215

**Comment by samsonasik** [comment]
Fixed 🎉 phpstan notice is unrelated.

```bash
Run vendor/bin/phpstan analyse --ansi --error-format symplify
Note: Using configuration file /home/runner/work/rector-src/rector-src/phpstan.neon.
Config file /home/runner/work/rector-src/rector-src/vendor/symplify/phpstan-rules/packages/symfony/config/services.neon does not exist or isn't readable
Error: Process completed with exit code 1.
```

**Comment by samsonasik** [comment]
re-trigger CI

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
