### PR TITLE
Remove SmartFileInfo registration in bootstrap.php

### PR DESCRIPTION
**Pull request by samsonasik**
ref https://github.com/rectorphp/rector-src/pull/2586#issuecomment-1169811258

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by sabbelasichon** [comment]
FYI: I realized now that the SmartFileInfo and the ComposerJson are actually prefixed, but a class_alias is defined. 
Before this change at least the SmartFileInfo was not prefixed. 
I don´t know if this is intended behaviour. In order to make i.e. phpstan happy i had to include both files in our bootstrap file from the rector vendor folder to make phpstan aware of it.

**Comment by sabbelasichon** [comment]
https://github.com/sabbelasichon/typo3-rector/runs/7111613059?check_suite_focus=true

**Comment by sabbelasichon** [comment]
https://github.com/sabbelasichon/typo3-rector/pull/3047/files#diff-6230d62c4bb49b5825f9ebdc87d35d948c02214aa6cc05440cc949cfc429e93bR7-R8

**Comment by samsonasik** [comment]
class_exists possibly can handle that in phpstan bootstrap without include:

```php
class_exists(\Symplify\SmartFileSystem\SmartFileInfo::class);
```

**Comment by sabbelasichon** [comment]
Tried it, doesn´t work for me.

**Comment by samsonasik** [comment]
then possibly include in phpstan bootstrap is the way to go

**Pull request merged**
