### PR TITLE
[Php55] Clean up FullyQualified assigned to FullyQualified on StringClassNameToClassConstantRector

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by staabm** [comment]
@samsonasik @TomasVotruba is it worth supporting php5 rules?

**Comment by samsonasik** [comment]
@staabm we use `LevelSetList::UP_TO_PHP_82` which from php 5.2

**Comment by staabm** [comment]
So, we know of projects still running on php5 which use rector to upgrade to php7/8?

**Comment by samsonasik** [comment]
On downgrade, we removing support to downgrade to php 5, but for upgrade, I think that's still a good to have and improve code quality and reduce error prone, eg: on add default value to undefined variable from php 5.6, or make long array syntax short, or remove continue to break syntax;

The "error warning" probably can be hidden, but can be fixed by upgrade the code to remove the limitation of old behaviour via `LevelSetList`.

**Comment by TomasVotruba** [comment]
> So, we know of projects still running on php5 which use rector to upgrade to php7/8?

Yes, 90 % our private clients start on PHP 5.3-5.6 :smile:

**Pull request merged**
