### PR TITLE
[psr-4] Move group of classes from Rector\\Core to Rector namespace

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by samsonasik** [comment]
packages-tests error seems expected, due to `--no-update`

https://github.com/rectorphp/rector-src/blob/595086559f9ed5196d53c6dbea907043153bda61/.github/workflows/packages_tests.yaml#L55

so it late sync

**Comment by TomasVotruba** [comment]
Let's ship it :wink:

**Comment by staabm** [comment]
huhu,

in the release notes it is mentioned, that this change is motivated by a perf background

> In this release we merged 2 directories into /src to speed up class loading

do you have any numbers on that? I wonder why moving classes into a separate folder would have a speed impact?

**Comment by TomasVotruba** [comment]
Not really. The main reason is to fix granulated source core over too many directories. 
I realized it makes working with code like jumping on a hot tin roof :)

**Comment by staabm** [comment]
just a note, as I am currently updating rector in our projects:

I can't even count anymore how often BC breaks happen which require manual intervention.
In this case it was e.g. `use Rector\Core\ValueObject\PhpVersion;` beeing moved to a new namespace.
it means nearly every project I own needs to be adjusted because of things like `$rectorConfig->phpVersion(PhpVersion::PHP_81);` used in rector config.

these rector upgrades are super frustrating for the rector user and have no obvious value for the end user. in PHPStan we prevent such kind of changes and did not have a single one in years. I can totally see why the new structure is cleaner, but please also keep in mind you are loosing/playing with trust of your users

**Comment by TomasVotruba** [comment]
Thanks for feedback. The upgrade should be as easy as replace 1 string with another.

As for best practise, the `$rectorConfig->phpVersion(PhpVersion::PHP_81);` should not be used in project, unless you're doing the upgrade and need to fake different than `composer.json` version. I recommend removing it competelly :+1:

**Comment by staabm** [comment]
> Thanks for feedback. The upgrade should be as easy as replace 1 string with another.

sure. but if I don't need todo this step I can upgrade all our projects in 30 min. when I need this manual stept it takes me a whole day to update all of them

its 

"just merge a dependabot PR" 
  vs. 
"checkout all the projects; make the change and bring it thru the dev process; maybe even merge the change thru branches; do that in every project"


> As for best practise, the `$rectorConfig->phpVersion(PhpVersion::PHP_81);` should not be used in project, unless you're doing the upgrade and need to fake different than `composer.json` version. I recommend removing it competelly 👍

I agree that in a perfect world this would be possible. when working with dozens of projects its not possible to always run every project in a separat php version.

please see e.g. https://github.com/search?q=%22%24rectorConfig-%3EphpVersion%22&type=code which shows this config is really required for hundreds of projects and can't oftentimes not be dropped

**Pull request merged**
