### PR TITLE
[CodingStyle] Fix newline before new assign set

### PR DESCRIPTION
**Pull request by rajyan**
fixes https://github.com/rectorphp/rector/issues/6501

I just changed the way to add newlines, because adding newlines directly to `$node->stmts` inside foreach loop was breaking the loop (and logic).

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, CI needs to pass before review. Could you check it?

**Comment by rajyan** [comment]
@TomasVotruba 
👍 
I'll try to fix it somewhere today.

**Comment by rajyan** [comment]
@TomasVotruba 
fixed! ready for review now.
It was a very good catch!

P.S.
I misunderstood from [here](https://github.com/rectorphp/rector/blob/main/CONTRIBUTING.md) that `composer complete-check` is nearly equal to the ci, 
and took me a long time to notice there is a [run rector process](https://github.com/rectorphp/rector-src/blob/main/.github/workflows/rector.yaml#L57) before ecs. 😢

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
> I misunderstood from here that composer complete-check is nearly equal to the ci,
and took me a long time to notice there is a run rector process before ecs. cry

Ah, I personally don't use it because it takes lot of time. CI is faster for me.

But if you use it and it can be improved, could you send PR to avoid this frustration in the future?

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Comment by rajyan** [comment]
> Ah, I personally don't use it because it takes lot of time. CI is faster for me.

I see.

> But if you use it and it can be improved, could you send PR to avoid this frustration in the future?

👍

**Pull request merged**
