### PR TITLE
[PHPStan] Run PHPStan rich parser in tests to know the types + process code with tolerant parses on 1st run

### PR DESCRIPTION
**Pull request by TomasVotruba**
Mirror to fix in PHPStan https://github.com/phpstan/phpstan-src/commit/433511a3eb526b0a340277aeb48ff20f292922d1

Ref https://github.com/rectorphp/rector/issues/6970

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba it seems cause error on downgrade process

**Comment by TomasVotruba** [comment]
I see :+1:

**Comment by TomasVotruba** [comment]
I'm exploring it and there is infinite loop. 
When I exclude the `DowngradeJsonDecodeNullAssociativeArgRector` the downgrade continues well.

The file it fail on is: `vendor/clue/ndjson-react/src/Decoder.php`

```bash
bin/rector p vendor/clue/ndjson-react/src/Decoder.php -c build/config/config-downgrade.php -n --clear-cache --debug
```

**Comment by samsonasik** [comment]
I tried rollback `config/phpstan/parser.neon` locally and it works again for this by this PR https://github.com/rectorphp/rector-src/pull/1789

```
# see original config.neon in phpstan.neon - https://github.com/phpstan/phpstan-src/blob/386eb913abb6ac05886c5642fd48b5d99db66a20/conf/config.neon#L1582
# this file overrides definitions from the config above
services:
    defaultAnalysisParser:
        factory: @pathRoutingParser
        arguments!: []

    cachedRectorParser:
        class: PHPStan\Parser\CachedParser
        arguments:
            originalParser: @rectorParser
            cachedNodesByStringCountMax: %cache.nodesByStringCountMax%
        autowired: false

    cachedRectorSimpleParser:
        class: PHPStan\Parser\CachedParser
        arguments:
            originalParser: @rectorSimpleParser
            cachedNodesByStringCountMax: %cache.nodesByStringCountMax%
        autowired: false

    pathRoutingParser:
        class: PHPStan\Parser\PathRoutingParser
        arguments:
            currentPhpVersionRichParser: @cachedRectorParser
            currentPhpVersionSimpleParser: @cachedRectorSimpleParser
            php8Parser: @php8Parser
        autowired: false

    rectorParser:
        class: PHPStan\Parser\RichParser
        arguments:
            parser: @currentPhpVersionPhpParser
            lexer: @currentPhpVersionLexer
        autowired: no

    rectorSimpleParser:
        class: PHPStan\Parser\SimpleParser
        arguments:
            parser: @currentPhpVersionPhpParser
```

**Comment by TomasVotruba** [comment]
That only hides the bug. There is infinite loop with if condition.

This is the reproducer:

```bash
vendor/bin/phpunit rules-tests/DowngradePhp72/Rector/FuncCall/DowngradeJsonDecodeNullAssociativeArgRector/DowngradeJsonDecodeNullAssociativeArgRectorTest.php --filter test#3
```

**Comment by samsonasik** [comment]
I can't reproduce it:

```
 vendor/bin/phpunit rules-tests/DowngradePhp72/Rector/FuncCall/DowngradeJsonDecodeNullAssociativeArgRector/DowngradeJsonDecodeNullAssociativeArgRectorTest.php --filter test#3
PHPUnit 9.5.13 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 00:00.973, Memory: 82.50 MB

OK (1 test, 2 assertions)
```

and for already transformed, there is already test for it:

https://github.com/rectorphp/rector-src/blob/main/rules-tests/DowngradePhp72/Rector/FuncCall/DowngradeJsonDecodeNullAssociativeArgRector/Fixture/skip_possibly_null_already_transformed.php.inc

**Pull request merged**
