### PR TITLE
Add option of case-insensitive ReplaceStringWithClassConstantRector

### PR DESCRIPTION
**Pull request by wkania**
Add [feature](https://github.com/rectorphp/rector/issues/6692)

I want to use it in the https://github.com/rectorphp/rector-doctrine/blob/main/config/sets/doctrine-code-quality.php 
It's very common to just use 'asc'/'desc' instead of 'ASC'/'DESC'.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, thanks for the feature. 

I think it would make sense to make this behavior default. In the end the ASC/asc has the same meaning. 

What do you think?

**Comment by samsonasik** [comment]
@TomasVotruba I prefer to not change existing behaviour so will safe for existing user that for whatever reason has different string case usage.

**Comment by TomasVotruba** [comment]
@samsonasik Ah, I got confused by different linked rule in the config and different rule with new test fixture. I agree with you

@wkania Hi, the linked rule is not the one here. It should be in `AttributeKeyToClassConstFetchRector`: https://github.com/rectorphp/rector-doctrine/blob/343fb259ba7f696f22057c0266b95e58db20563a/config/sets/doctrine-code-quality.php?rgh-link-date=2021-10-14T21%3A15%3A05Z#L39

Could you update that one with default behavior like you describe?

**Comment by wkania** [comment]
@TomasVotruba I added the link to the file with a set of rules, not any particular rule. Here is the [line](https://github.com/rectorphp/rector-doctrine/blob/main/config/sets/doctrine-code-quality.php#L72) with the rule.
No it's not about `AttributeKeyToClassConstFetchRector`.
In the related issue, I described why this should not be the default behavior.

Apologies for any confusion.

**Comment by TomasVotruba** [comment]
Ah, I see. It's 2 different places with similar logic.

I understand now :) 

Thanks for the improvement!

**Pull request merged**
