### PR TITLE
Add new method createFromClassWithItems in PhpAttributeGroupFactory

### PR DESCRIPTION
**Pull request by romainallanot**
I need this new method to be able to explode one annotation into multiple attributes.

### CODE REVIEW

**Comment by samsonasik** [comment]
It needs a use case, for example, you may try apply configurable of `AnnotationToAttributeRector`, eg new configurable:

https://github.com/rectorphp/rector-src/blob/d34b8469aa1eafe0f41138a0aa03f61e2a996b03/rules/Php80/Rector/Class_/AnnotationToAttributeRector.php#L82-L87

with fallback config, like this:

https://github.com/rectorphp/rector-src/blob/d34b8469aa1eafe0f41138a0aa03f61e2a996b03/rules/Php80/Rector/Class_/AnnotationToAttributeRector.php#L137

I guess will need default to `false` for this case.

Then, you can create new test under https://github.com/rectorphp/rector-src/tree/main/rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector , for example: `MultipleAttributesAnnotationToAttributeRectorTest` with new `FixtureMultipleAttributes` directory, and new `config/multiple_attributes.php`

**Comment by romainallanot** [comment]
For example, I need to transform this annotation 

```php
/**
 * @ApiResource(
 *     attributes={"access_control"="is_granted('ROLE_USER')"},
 *     collectionOperations={
 *         "get",
 *         "post"={"access_control"="is_granted('ROLE_ADMIN')"}
 *     },
 *     itemOperations={
 *         "get"={"access_control"="is_granted('ROLE_USER') and object.getOwner() == user"},
 *         "put"={"access_control"="is_granted('ROLE_USER') and previous_object.getOwner() == user"}
 *     },
 *     graphql={
 *         "item_query"={"access_control"="is_granted('ROLE_USER') and object.getOwner() == user"},
 *         "delete"={},
 *         "update"={"access_control"="is_granted('ROLE_USER') and previous_object.getOwner() == user"},
 *         "create"={"access_control"="is_granted('ROLE_ADMIN')", "access_control_message"="Only admins can create a secured dummy."}
 *     }
 * )
 */
```
into
```php
#[Resource(attributes: ['access_control' => 'is_granted(\'ROLE_USER\')'], graphql: ['item_query' => ['access_control' => 'is_granted(\'ROLE_USER\') and object.getOwner() == user'], 'delete' => [], 'update' => ['access_control' => 'is_granted(\'ROLE_USER\') and previous_object.getOwner() == user'], 'create' => ['access_control' => 'is_granted(\'ROLE_ADMIN\')', 'access_control_message' => 'Only admins can create a secured dummy.']])]
#[GetCollection]
#[Post(operationName: 'post', accessControl: 'is_granted(\'ROLE_ADMIN\')')]
#[Get(operationName: 'get', accessControl: 'is_granted(\'ROLE_USER\') and object.getOwner() == user')]
#[Put(operationName: 'put', accessControl: 'is_granted(\'ROLE_USER\') and previous_object.getOwner() == user')]
```
So i make my own rule inspired by AnnotationToAttributeRector. 
In this rule, i extract collectionOperations and itemOperations from the annotation values and i add a new attribute for each operations. To do that i need the new method i create in this PR.

**Comment by samsonasik** [comment]
We need test case for new addition method, that's why it need to be implemented in one of the rules, and have unit test for it, or at least, have unit test at https://github.com/rectorphp/rector-src/tree/main/packages-tests .

**Comment by romainallanot** [comment]
Hi @samsonasik, i added unit tests yesterday. Tell me if you need somethong else.

**Review by samsonasik — APPROVED** [review]

**Pull request merged**
