### PR TITLE
Add ParametersAcceptorSelectorVariantsWrapper to handle selectFromArgs() on multi variants, fallback to selectSingle

### PR DESCRIPTION
**Pull request by samsonasik**
Alternative for https://github.com/rectorphp/rector-src/pull/2606
Closes https://github.com/rectorphp/rector-src/pull/2606

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
@TomasVotruba I replaced existing direct `selectFromArgs()` to use `ParametersAcceptorSelectorVariantsWrapper` so make `selectSingle` when possible.

I will update use `selectSingle` to use the wrapper as well.

**Comment by samsonasik** [comment]
On `selectSingle()` usage, it seems mostly pull from `Reflection`, so cannot get `Args[]` without `AstResolver`, so I think it is ok for the start.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Review by TomasVotruba — APPROVED** [review]

**Pull request merged**
