### PR TITLE
[Php 8] Enable ClassOnObjectRector

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by samsonasik** [comment]
It seems cause a downgrade error, it seems we need a `DowngradeClassOnObjectRector` rule.

**Comment by samsonasik** [comment]
It seems there is `DowngradeClassOnObjectToGetClassRector.php` that seems not works on property fetch.

**Comment by samsonasik** [comment]
resolved at https://github.com/rectorphp/rector-src/pull/195

**Pull request merged**
