### PR TITLE
[AutoImport] Add support use existing imported short name

### LINKED ISSUE #7544: importNames doesn't use fqn when already class imported
# Bug Report

When you already use a class then rector will still use fully qualified namespace see example: https://getrector.org/demo/82ff7f68-5947-496b-ac17-e82a6f87b555 i expect the `\DateTime` to change to `DateTime

## Minimal PHP Code Causing Issue
https://getrector.org/demo/82ff7f68-5947-496b-ac17-e82a6f87b555

## Expected Behaviour

```diff
<?php

use DateTime;

final class DemoFile
{
    public function run()
    {
-       return new \DateTime();
+       return new DateTime();
    }
}
```

### PR DESCRIPTION
**Pull request by samsonasik**
1 - On `$rectorConfig->importNames()` enabled:
----

- inside namespace, when there is `use DateTime`, `\DateTime` will be changed to use `DateTime` as is
- in no namespace, no need to import, as it `non-compound name`, directly change to `DateTime` as is, see https://3v4l.org/N8K7U
- inside namespace, when not imported yet, it will add: `use DateTime` in use statement.

2 - On `$rectorConfig->importShortClasses(false)`
---

it will skip the import `\DateTime`, even it has namespace or not.

Fixes https://github.com/rectorphp/rector/issues/7544

### CODE REVIEW

**Comment by samsonasik** [comment]
implemented 🎉 /cc @johanadivare

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
Rebased, I added fixture for skip same last name for short name with different namespace when imported https://github.com/rectorphp/rector-src/pull/3005/commits/4b9b42c7115293883d8ac56e80f11ab85df5373d

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Comment by ghost** [comment]
@samsonasik nice man! Thanks for the fix

**Pull request merged**
