### PR TITLE
[DeadCode] Skip fluent no return type on RemoveUnusedPrivateMethodRector

### LINKED ISSUE #8711: CRITICAL: Rector removes methods that are in use
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 1.1.1             |

Rector removes a private method that's in use when no return types are defined.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/8987b947-4c63-489c-8d0d-037c93652d85

## Expected Behaviour

`baz` should not be removed.

Rector should act the same way it does when return types are defined.

https://getrector.com/demo/f681ab05-6751-4475-8b8c-747b6ef0562c

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8711

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @OA

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Looks good, thanks :+1:

**Comment by samsonasik** [comment]
It seems still invalid when called on last

https://getrector.com/demo/99fb53f2-c573-4d87-8c6b-403d92eeb5e5

I will check more

**Comment by samsonasik** [comment]
https://github.com/rectorphp/rector-src/pull/6116

**Pull request merged**
