### PR TITLE
[EarlyReturn] Handle mirror comments before elseif on RemoveAlwaysElseRector

### PR DESCRIPTION
**Pull request by samsonasik**
Closes https://github.com/rectorphp/rector-src/pull/224 Fixes https://github.com/rectorphp/rector/issues/6505

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
It seems it cause a bug when last else has `else` with comment in `elseif` above https://github.com/rectorphp/rector-src/pull/234/commits/8daeb5f6ff89aa0b79de8a693e0bb54c982ea3b0

**Comment by samsonasik** [comment]
Fixed 🎉 . The new line on last `else` seems due to append on add node after node last `elseif` statement https://github.com/rectorphp/rector-src/pull/234/commits/1f6000c18e7475621e87fd403dc3c655cf9b84a8 .

All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :clamp:

**Comment by staabm** [comment]
Thanks 🙏

**Comment by staabm** [comment]
Please note, that the initiaL complex case of https://getrector.org/demo/395775cb-d18b-4fc1-b968-c8152a9585b5 still looses a comment before the `else` when using the demo.

**Pull request merged**
