### PR TITLE
[Core] Enable back cache in FilesFinder

### PR DESCRIPTION
**Pull request by samsonasik**
ref https://github.com/rectorphp/rector/pull/6398#issuecomment-865029593

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba if there is a new file to directory, it seems indeed not detected before the cache is cleared, eg via `--clear-cache`. Do yout think we need to compare count() of files?

**Comment by TomasVotruba** [comment]
> Do yout think we need to compare count() of files?

What if 5 files are removed and 5 different files are added?
I don't think this method call should be cached at all. That's why we need failing test case first, to see where exactly is the problem (if there is any).

**Comment by samsonasik** [comment]
Its result is collection of files information. Yes, compare count seems will not work work that case. The nearest possible solution seems compare the directory size, before and after cached. I am not sure with performance for loop with `RecursiveIteratorIterator`, as `$source` is array that need another loop first. 

Possiblly, a `du -h -s` can be used:

```php
foreach ($source as $s) {
  passthru('du -h -s ' . $source);
}
```

that will need verify in different Operating system's. 

I am closing for now.

**Comment by TomasVotruba** [comment]
This method should not be cached at all. Finder is not a bottle neck.

The cache is there to skip files that have not change since last run. E.g. if finder finds 5 files, it will look into cache, what was the file's last checksum. If nothing changed, Rector will skip it.

**Comment by TomasVotruba** [comment]
This is the propper fix: [`df4df74` (#270)](https://github.com/rectorphp/rector-src/pull/270/commits/df4df74a998364122816d71fa1affdab8d118283#diff-c1b4d526cfa7d17990bde4cf0146bcf748e35382d13d14ca350a21820d2df256)


`FileFinder` was ignoring unchaged files and always return full list. Now it's returning only changed files.

I've also changed cache to enable by default, to have just one behavior. It was available for quite a long time, so it's time to upgrade Rector :)

**Comment by mssimi** [comment]
@TomasVotruba Updated to latest packageist version **0.11.21**, cache is still not working.

**Comment by TomasVotruba** [comment]
@mssimi We'll need a test case for that, to avoid fixing something else :D

**Comment by mssimi** [comment]
Still reproducing, it does not work for just some files and only if inside docker.

**Comment by mssimi** [comment]
@TomasVotruba provided failing test https://github.com/rectorphp/rector-src/pull/346

**Pull request closed without merging**
