### PR TITLE
[Privatization] Handle numeric string on RepeatedLiteralToClassConstantRector

### LINKED ISSUE #6897: Fatal error using `SetList::PRIVATIZATION` and numeric strings
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.12.9             |

A fatal error occurs related to [numeric-strings](https://github.com/rectorphp/rector/issues/6896) but not bcmath this time.

When using the `RepeatedLiteralToClassConstantRector::class` rule, numbers as strings are causing an exception, e.g.:
```
bcdiv($money->getAmount(), '100', 2);
bcdiv($totalMoney->getAmount(), '100', 2);
bcdiv($taxMoney->getAmount(), '100', 2);
```

causes:
```
PHP Fatal error:  Uncaught TypeError: Rector\Privatization\Rector\Class_\RepeatedLiteralToClassConstantRector::createConstName(): Argument #1 ($value) must be of ty
pe string, int given, called in .../vendor/rector/rector/rules/Privatization/Rector/Class_/RepeatedLiteralToClassCon
stantRector.php on line 194 and defined in .../vendor/rector/rector/rules/Privatization/Rector/Class_/RepeatedLitera
lToClassConstantRector.php:224
```

## Minimal PHP Code Causing Issue

Demo: https://getrector.org/demo/1ec68e87-7306-68ec-b90c-872844867fb8

## Expected Behaviour

No fatal error should occur

### PR DESCRIPTION
**Pull request by internalsystemerror**
Fixes https://github.com/rectorphp/rector/issues/6897

### CODE REVIEW

**Comment by samsonasik** [comment]
@internalsystemerror could you update PR title? thank you.

**Comment by internalsystemerror** [comment]
@samsonasik sure, but to what?

**Comment by samsonasik** [comment]
something like : [Privatization] Handle numeric string on RepeatedLiteralToClassConstantRector

**Comment by internalsystemerror** [comment]
@samsonasik Ah I get you now. Done.

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you

**Comment by samsonasik** [comment]
Thank you @internalsystemerror

**Pull request merged**
