### PR TITLE
Update phpdoc-parser to ^1.20.3

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba let's try this to ensure no error :

```
Call to undefined method                               
         Rector\BetterPhpDocParser\ValueObject\Parser\BetterTokenIterator::getTokens()
```

if the issue persist, inner dependency probably cause to load old phpdoc-parser.

https://github.com/rectorphp/rector-symfony/actions/runs/4808249189/jobs/8557993664?pr=394#step:5:14

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I think it's related to this one:
https://github.com/rectorphp/rector-src/commit/f26a47636a3bb0b63d16dc6c3bde36406fbfd393

**Comment by samsonasik** [comment]
Yesterday is working ok, that change was 5 days ago, test failure like that may due to duplicated fixture

**Comment by samsonasik** [comment]
@TomasVotruba fixed :tada:

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
