### PR TITLE
Missing brackets in CombineIfRector

### PR DESCRIPTION
**Pull request by staabm**
refs https://github.com/phpstan/phpstan/issues/9987

### CODE REVIEW

**Comment by staabm** [comment]
hmm I need to double check what the real world code did look like, but I don't have access atm.

will update in the next few days

**Comment by samsonasik** [comment]
The PR title "Missing brackets" but it seems bracket already added?

**Comment by staabm** [comment]
Yeah, as I wrote above. It seems I am missing something and I need to look into the real code where it happened. 

Stay tuned

**Comment by staabm** [comment]
this snippet reproduces the problem:

https://getrector.com/demo/d4e1041b-4fb5-4563-8902-ab452190ac32

the code before rector transformed it, did not need additionaly brackets, but the after code would need them to not trigger a "undefined variable" warning at runtime

see https://3v4l.org/v5paW

**Comment by staabm** [comment]
@samsonasik could you look into a fix?

**Comment by samsonasik** [comment]
@staabm I cherry-picked your commit at PR https://github.com/rectorphp/rector-src/pull/5151

**Pull request closed without merging**
