### PR TITLE
[EarlyReturn] Handle crash on RemoveAlwaysElseRector+ReturnEarlyIfVariableRector

### LINKED ISSUE #7557: System error: "PhpParser\\Internal\\TokenStream::getIndentationBefore()
https://getrector.org/demo/214db20a-2710-4424-ae1f-0165576834f5

```
Rector could not run due to error: {
"totals": {
"changed_files": 0,
"removed_and_added_files_count": 0,
"removed_node_count": 0,
"errors": 1
},
"errors": [
{
"message": "System error: \"PhpParser\\Internal\\TokenStream::getIndentationBefore(): Return value must be of type int, null returned\"\nRun Rector with \"--debug\" option and post the report here: https://github.com/rectorphp/rector/issues/new",
"file": "/var/www/var/demo/0kszlexuy9m9eukgctpi/rector_analyzed_file.php",
"line": 205
}
]
}
```

with sample code

```php
<?php

final class DemoFile
{
	public function get( $a, $b = false ) {
		if ( $b !== true ) {
			$value = $a * 5;

			if ( $value === 'hello' ) {
				$value = false;
			}

			return $value;
		} elseif ( $a === true ) {
			return false;
		}

		return true;
	}
}
```

and config:

```php
<?php

use Rector\Config\RectorConfig;

return static function (RectorConfig $rectorConfig): void {
	$rectorConfig->rule( \Rector\EarlyReturn\Rector\If_\RemoveAlwaysElseRector::class );
	$rectorConfig->rule( \Rector\EarlyReturn\Rector\StmtsAwareInterface\ReturnEarlyIfVariableRector::class );
};
```

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
final class Fixture
{
    public function get($a, $b = false)
    {
        if ($b !== true) {
            $value = $a * 5;

            if ($value === 'hello') {
                $value = false;
            }

            return $value;
        } elseif ($a === true) {
            return false;
        }

        return true;
    }
}
```

It currently cause crash:

```bash
There was 1 failure:

1) Rector\Core\Tests\Issues\IssueRemoveAlwaysElseReturnEarlyIfVariable\IssueRemoveAlwaysElseReturnEarlyIfVariableTest::test with data set #0 ('/Users/samsonasik/www/rector-...hp.inc')
assert($itemStartPos >= 0 && $itemEndPos >= 0 && $itemStartPos >= $pos) in /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php:759

Caused by
AssertionError: assert($itemStartPos >= 0 && $itemEndPos >= 0 && $itemStartPos >= $pos) in /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php:759
```

ref https://getrector.org/demo/214db20a-2710-4424-ae1f-0165576834f5

Fixes https://github.com/rectorphp/rector/issues/7557

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @kkmuffme

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
[Verify parent node original node seems working](https://github.com/rectorphp/rector-src/pull/3011/commits/129b4fe40cf77105edbdfcd1672c68af72e484e9) 🎉 , The `RectifiedAnalyzer` is now simplified.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
