### PR TITLE
[CodeQuality] Handle crash on BinaryOp/Mul and variable variable: $$name on IntvalToTypeCastRector

### LINKED ISSUE #7875: every time crashes on single file both single and parallel mode
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.15.24         |
| Php version | 7.3.33        |

`IntvalToTypeCastRector` causes unrecoverable failure on bellow code that works fine.

```
% ../php_interface/vendor/bin/rector process --clear-cache --debug
../../bitrix/modules/main/filter_tools.php
[file] ../../bitrix/modules/main/filter_tools.php
[rule] Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector

[file] ../../bitrix/modules/main/filter_tools.php
[rule] Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector

[file] ../../bitrix/modules/main/filter_tools.php
[rule] Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector

[file] ../../bitrix/modules/main/filter_tools.php
[rule] Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector

[file] ../../bitrix/modules/main/filter_tools.php
[rule] Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector

[file] ../../bitrix/modules/main/filter_tools.php
[rule] Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector

[file] ../../bitrix/modules/main/filter_tools.php
[rule] Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector

[file] ../../bitrix/modules/main/filter_tools.php
[rule] Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector

[file] ../../bitrix/modules/main/filter_tools.php
[rule] Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector

[file] ../../bitrix/modules/main/filter_tools.php
[rule] Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector

[file] ../../bitrix/modules/main/filter_tools.php
[rule] Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector

[file] ../../bitrix/modules/main/filter_tools.php
[rule] Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector

[file] ../../bitrix/modules/main/filter_tools.php
[rule] Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector

[file] ../../bitrix/modules/main/filter_tools.php
[rule] Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector

[file] ../../bitrix/modules/main/filter_tools.php
[rule] Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector

PHP Fatal error:  Uncaught Rector\Core\Exception\ShouldNotHappenException: Node "PhpParser\Node\Expr\Cast\Int_" with parent of "PhpParser\Node\Expr\BinaryOp\Mul" is missing scope required for scope refresh. in /Users/holdmann/Documents/Projects/******/local/php_interface/vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php:85
Stack trace:
#0 /Users/holdmann/Documents/Projects/******/local/php_interface/vendor/rector/rector/src/Rector/AbstractRector.php(342): Rector\Core\Application\ChangedNodeScopeRefresher->refresh(Object(PhpParser\Node\Expr\Cast\Int_), NULL, '/Users/holdmann...')
#1 /Users/holdmann/Documents/Projects/******/local/php_interface/vendor/rector/rector/src/Rector/AbstractRector.php(253): Rector\Core\Rector\AbstractRector->refreshScopeNodes(Object(PhpParser\Node\Expr\Cast\Int_), '/Users/holdmann...', NULL)
#2 /Users/holdmann/Documents/Projects/******/local/php_interface/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113): Rector\Core\Rector\Ab in /Users/holdmann/Documents/Projects/******/local/php_interface/vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php on line 85
Fatal error: Uncaught Rector\Core\Exception\ShouldNotHappenException: Node "PhpParser\Node\Expr\Cast\Int_" with parent of "PhpParser\Node\Expr\BinaryOp\Mul" is missing scope required for scope refresh. in /Users/holdmann/Documents/Projects/******/local/php_interface/vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php:85
Stack trace:
#0 /Users/holdmann/Documents/Projects/******/local/php_interface/vendor/rector/rector/src/Rector/AbstractRector.php(342): Rector\Core\Application\ChangedNodeScopeRefresher->refresh(Object(PhpParser\Node\Expr\Cast\Int_), NULL, '/Users/holdmann...')
#1 /Users/holdmann/Documents/Projects/******/local/php_interface/vendor/rector/rector/src/Rector/AbstractRector.php(253): Rector\Core\Rector\AbstractRector->refreshScopeNodes(Object(PhpParser\Node\Expr\Cast\Int_), '/Users/holdmann...', NULL)
#2 /Users/holdmann/Documents/Projects/******/local/php_interface/vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(113): Rector\Core\Rector\Ab in /Users/holdmann/Documents/Projects/******/local/php_interface/vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php on line 85
```

## Minimal PHP Code Causing Issue

```php
$isParallel = true;

return static function (RectorConfig $rectorConfig) use ($isParallel): void {

    $rectorConfig->parallel(600, 3, 3);

    if (!$isParallel)
    {
        $rectorConfig->disableParallel();
    }

    $rectorConfig->paths([__DIR__ . '/../../bitrix/modules/main/filter_tools.php']);
    $rectorConfig->skip([
        // crashes rector w/o any obviously reason
        //__DIR__ . '/../../bitrix/modules/main/filter_tools.php'
    ]);

    $rectorConfig->rule(IntvalToTypeCastRector::class);

};
```
for source code see [attached file](https://disk.yandex.ru/d/nlyiR3umOt_CKQ)
## Expected Behaviour

should work as expected

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7875
Ref https://getrector.com/demo/938a84a5-ae9c-474a-95f3-9c7e0f827e77

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @holdmann

**Comment by samsonasik** [comment]
@TomasVotruba I fixed it by set fallback Scope on `ScopeAnalyzer::resolveScope()` to always return `Scope` by using 

```php
return $this->scopeFactory->createFromFile($filePath);
```

https://github.com/rectorphp/rector-src/pull/3608/commits/93f62197fe92611eeac7835650c9f0bb2b045fcd , this is the solution I can found for now.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by yguedidi** [comment]
@samsonasik why not getting the scope from the first ancestor that has a scope? here maybe the parameter Expr or the MethodCall

**Comment by samsonasik** [comment]
I tried that, not working, there is nearest scope filling handle for that, see

https://github.com/rectorphp/rector-src/blob/54a340ce750f48aa3e09f65e02df9dc6fa2206a0/packages/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php#L59

but can't get the solution yet for this

**Comment by samsonasik** [comment]
I found a better solution, I check against node just reprinted on `ScopeAnalyzer` https://github.com/rectorphp/rector-src/pull/3608/commits/ed898fa7b53db07d4ff245d9913478a065fd3e89

**Comment by samsonasik** [comment]
Finally 🎉 🎉 🎉 All checks have passed 🎉 , the solution is handle by check that node is just re-printed along with parent re-print on ScopeAnalyzer.

@TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Pull request merged**
