### PR TITLE
Various type fixes

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref https://github.com/rectorphp/rector-src/pull/1052

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba the return parent at https://github.com/rectorphp/rector/runs/4020140134?check_suite_focus=true seems still error, do we need e2e bare run rector build in this repo?

**Comment by TomasVotruba** [comment]
This is not related to the `parent` bug. It's cleanup of types before PHPStan upgdate.

> do we need e2e bare run rector build in this repo?

That might be useful to discover bug earlier :+1:

**Comment by samsonasik** [comment]
@TomasVotruba added at https://github.com/rectorphp/rector-src/pull/1082 , shown the error at https://github.com/rectorphp/rector-src/runs/4020885462?check_suite_focus=true#step:18:11

**Comment by TomasVotruba** [comment]
Thank you, this one is very helpful, as we can see failing build here right at the commit it happens :+1: 

I've moved it after the push to repository, so we can we see the commit diff in `rector/rector` like and look easier for bugs: https://github.com/rectorphp/rector/commit/0c20321ff63d0569bcef2d7548dd2e5343279a02

**Pull request merged**
