### PR TITLE
Try Update to symfony ^6.1 and symfony-contract ^3.1

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba symfony-contract's Cache seems skipped in downgrade config so I think we can ignore it from parallel lint

https://github.com/rectorphp/rector-src/blob/ba8e4879a212671966073d28c5f9b7e249e2dcb5/build/config/config-downgrade.php#L47-L48

Let's give it  a try.

### CODE REVIEW

**Comment by samsonasik** [comment]
also ignore `vendor/symfony/contracts/HttpClient/Test` as we don't use it.

**Comment by TomasVotruba** [comment]
Allright, let's give it a go :)

I want to have Rector deploy under control now, as we're doing big changes, so please don't merge any PRs this week.

**Comment by TomasVotruba** [comment]
@samsonasik https://github.com/rectorphp/rector-src/pull/2390#issuecomment-1140766482

**Comment by samsonasik** [comment]
I am trying to resolve it at https://github.com/rectorphp/rector-src/pull/2392, I can revert to symfony 6.0.* back if you want. 

Do you want me to revert this?

**Comment by samsonasik** [comment]
Oh, commit can't contain "" as the scoped build will failure.

**Comment by samsonasik** [comment]
Revert commit https://github.com/rectorphp/rector-src/commit/b91e7079963118503bac7dad9ca4dc7764f922bb has "" in commit so the build will failure.

**Comment by TomasVotruba** [comment]
@samsonasik Do not merge anything now. Symfony 6.1 is does not add anything valuable at the moment.

**Comment by samsonasik** [comment]
ok 👍

**Pull request merged**
