### PR TITLE
[DowngradePhp80] Handle match inside ArrowFunction on DowngradeMatchToSwitchRector

### LINKED ISSUE #7173: Combination of ArrowFunctionToAnonymousFunctionRector and DowngradeMatchToSwitchRector partially faulty
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main            |

It seems like I found a little "edge case bug".
If I combine the `ArrowFunctionToAnonymousFunctionRector` and `DowngradeMatchToSwitchRector` and have some code which is nested into array_map, arrow function and match which are assigned to an variable. Rector creates code incorrect.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/b948c953-6744-43aa-92ab-17ffcc65682d

## Expected Behaviour

```diff
- $mapped = array_map(
-     static fn (mixed $default): mixed => match (true) {
-         is_string($default) => sprintf('"%s"', $default),
-         default => $default,
-     }, $defaults
- );
+ $mapped =  array_map(
+     static function (mixed $default): mixed {
+         switch (true) {
+             case is_string($default):
+                 $default = sprintf('"%s"', $default);
+                 break;
+             default:
+                 $default = $default;
+                 break;
+         }
+ 
+         return $default;
+     }, $defaults
+ );
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7173

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @malteschlueter

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by malteschlueter** [comment]
Nice, thank you very much @samsonasik for the fast support :)

**Review by malteschlueter — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you @samsonasik

**Pull request merged**
