### PR TITLE
Improve CI

### PR DESCRIPTION
**Pull request by yguedidi**
Avoid very long jobs, like in #3672 when infinite loop

concurrency snippet comes from https://exercism.org/docs/building/github/gha-best-practices

### CODE REVIEW

**Comment by yguedidi** [comment]
I have no idea why [this job](https://github.com/rectorphp/rector-src/actions/runs/4781056079/jobs/8499165889?pr=3673) fails after 3 minutes while the configured time out is 10 minutes... 😕

**Comment by samsonasik** [comment]
You need to rebase, that seems a paratest bug, we now use directly phpunit

**Comment by yguedidi** [comment]
@samsonasik rebased

**Comment by TomasVotruba** [comment]
To be honest, I find this more complex and unclear to read. Moreover debugging detailed settings of Github can take days, because of unclear enum variables. We've been there many times :) so the simpler the better, so we can enjoy its maintenance. 

Thanks for understanding :+1:

**Comment by yguedidi** [comment]
@TomasVotruba would you accept at least the commit about timeouts? I see there ar already use in some workflows, but not all of them.
I'd like to avoid blocking a job for 6h in case of infinite loop

**Comment by TomasVotruba** [comment]
> would you accept at least the commit about timeouts?

Yes, that makes sense :+1:

**Comment by yguedidi** [comment]
@TomasVotruba here it is #3689

**Pull request closed without merging**
