### PR TITLE
[Renaming] Do not rename docblock same name not found in use inside namespace 

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #2468

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
phpstan notice is unrelated:

```bash

Run vendor/bin/phpstan analyse --ansi --error-format symplify
Note: Using configuration file /home/runner/work/rector-src/rector-src/phpstan.neon.
Config file /home/runner/work/rector-src/rector-src/vendor/symplify/phpstan-rules/packages/symfony/config/services.neon does not exist or isn't readable
```

**Comment by samsonasik** [comment]
re-trigger CI

**Comment by TomasVotruba** [comment]
Missclick :)

Thanks :+1:

**Pull request merged**
