### PR TITLE
[Php80] Fix add default nullable type on ClassPropertyAssignToConstructorPromotionRector

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://github.com/rectorphp/rector-src/pull/4090#pullrequestreview-1463810926

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
I think we need more general solution, eg param string default false, transformed to param bool|string.

**Comment by samsonasik** [comment]
I added string default false fixture https://github.com/rectorphp/rector-src/pull/4091/commits/e5d98625ca57c845558d389304aa7edd3109743e

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
