### PR TITLE
[MysqlToMysqli] Deprecate set, as mostly breakingcode, rather handle upgrade manually

### LINKED ISSUE #7533: mysql_to_mysqli does not swap arguments but overwrites
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.14.5 |

Using `mysql_to_mysqli` the parameters don't swap but overwrite.

```                                                                                                                                                                                                                                 
-               mysql_set_charset('UTF8', $this->conn);
-               mysql_select_db($this->db_database, $this->conn);
+               mysqli_set_charset($this->conn, $this->conn);
+               mysqli_select_db($this->conn, $this->conn);
```

## Minimal PHP Code Causing Issue

[https://getrector.org/demo/245c21af-da24-4ddf-a448-169126ed6e90](https://getrector.org/demo/245c21af-da24-4ddf-a448-169126ed6e90)

## Expected Behaviour

Expected: swap arguments
```
+               mysqli_set_charset($this->conn, 'UTF8');
+               mysqli_select_db($this->conn, $this->db_database);
```

### LINKED ISSUE #7793: Incorrect behavior of MysqlQueryMysqlErrorWithLinkRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.14.8    |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/0fa9f37c-349b-4d95-81e3-e057b757b975

```php
<?php

$prova = mysql_real_escape_string($periodo_en, $link);
```

### Responsible rules

* `MysqlQueryMysqlErrorWithLinkRector`

## Expected Behavior

I was expecting this

```php
<?php

$prova = mysql_real_escape_string($link, $periodo_en);
```

Instead I loose the 2nd argument, `$periodo_en`

The incriminated row is 

`   $rectorConfig->rule(MysqlQueryMysqlErrorWithLinkRector::class);
`
Removing this rule (that should not be apply, I suppose) , I got right behaviour

See right behaviour without this call here: https://getrector.com/demo/db4033c5-187c-4a23-b4d9-f52423f66804

### PR DESCRIPTION
**Pull request by TomasVotruba**
Mysql to Mysqli migration is based in procedural historical code. Based on your feedback in Stackoverflow comments, it causes more confusion and harm of false positive:

* https://stackoverflow.com/questions/1390607/how-to-change-mysql-to-mysqli
* https://github.com/kamil-tekiela/mysql-to-mysqli

As much as we'd like to set this reliable and working, it's not ready yet to be helpful now and we better withdraw it.

<br>

## How to refactor in more reliable way?

* use tutorial https://www.phpclasses.org/blog/package/9199/post/3-Smoothly-Migrate-your-PHP-Code-using-the-Old-MySQL-extension-to-MySQLi.html
* https://github.com/kamil-tekiela/mysql-to-mysqli

Closes https://github.com/rectorphp/rector/issues/7793, closes https://github.com/rectorphp/rector/issues/7533

### CODE REVIEW

**Comment by Worst45** [comment]
To my mind, you should have left the code, but disabled by default in the sets. People activating it should them be aware that this is a dangerous feature.
It was very usefull for me to upgrade some basic code. And it had no side effect.

**Comment by TomasVotruba** [comment]
Ideally, this set should be extract by someone, who is handling such migrations more than once and can put experience.
It's quite a big domain that requires an experienced database migrator.

**Comment by kamil-tekiela** [comment]
Thank you for deprecating this feature. I am 200% on board with this. I tried this multiple times and it never worked properly for me. It could work on some very limited code bases, but even then, replacing mysql_* functions with mysqli_* functions is a bad idea. They are not comparable and are not 1-to-1 replacements. The mysqli rectors were a bad mark on an otherwise fantastic tool that rector is.

**Comment by TomasVotruba** [comment]
@kamil-tekiela Thanks for such a detailed feedback :pray:  I had similar feeling, that this migration is faster done with manual migration with careful step-by-step descitions.

**Pull request merged**
