### PR TITLE
[Testing] Make temp fixture file names exposed next to the fixture file, to make easier fixes and path resolvements

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Seems like e2e test is waiting for the merge to `main`. I tried locally and it works well

**Comment by TomasVotruba** [comment]
Seems like e2e test is waiting for the merge to `main`. I tried locally and it works well

**Comment by samsonasik** [comment]
The e2e got different indentation between local and CI, that's may just adjust by make equal to CI

**Comment by samsonasik** [comment]
@TomasVotruba I fixed the expected diff

**Comment by samsonasik** [comment]
@TomasVotruba should be fixed now.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you 😊

**Pull request merged**
