### PR TITLE
Upgrade deprecated set-*

### LINKED ISSUE #7555: Update deprecated set-output to GITHUB_OUTPUT
# Feature Request

Currently, scoped build is using deprecated set-output

https://github.com/rectorphp/rector-src/blob/b4c0637b1f59b5110a41205df6af51105bee7520/.github/workflows/build_scoped_rector.yaml#L108

Ref

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

 it should be updated

### PR DESCRIPTION
**Pull request by rez1dent3**
Closes https://github.com/rectorphp/rector/issues/7555

### CODE REVIEW

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @rez1dent3

**Comment by samsonasik** [comment]
Ref for escaping issue that may need update after updating phpstan-src workflow today: https://github.com/phpstan/phpstan-src/pull/1910

@rez1dent3 could you verify if something needs update for it? Thank you

**Comment by samsonasik** [comment]
@rez1dent3 I just re-started the scoped build and it seems still working ok https://github.com/rectorphp/rector-src/actions/runs/3314844962/jobs/5489279164

**Comment by rez1dent3** [comment]
@samsonasik This is good. But there are special characters that need to be escaped. Apparently these special characters are not used in the rector. And here with phpstan an ambush, of course. 

https://github.com/actions/runner/issues/2225

**Pull request merged**
