### PR TITLE
Add failing test fixture for `ReadOnlyClassRector` 

### PR DESCRIPTION
**Pull request by TomasVotruba**
- Add failing test fixture for ReadOnlyClassRector
- fix cs

### CODE REVIEW

**Comment by samsonasik** [comment]
Test failure on `RenameClassRector` is caused by https://github.com/rectorphp/rector-src/actions/runs/4902565356/jobs/8754485599, I will revert that first

**Comment by TomasVotruba** [comment]
@samsonasik Thanks :+1:

**Comment by samsonasik** [comment]
https://github.com/rectorphp/rector-src/pull/3744

**Comment by TomasVotruba** [comment]
I'll update the PR here

**Comment by samsonasik** [comment]
The only way to make it multi line is by reprint the `Class_` node, as attribute line and class line information is equal if printed, but that will cause possible unrelated diff on the class itself.

**Comment by samsonasik** [comment]
same with my comment at https://github.com/rectorphp/rector-src/pull/3727#discussion_r1182876633 , the same line is actualy "fine"

**Comment by samsonasik** [comment]
imo, this needs to be solved in nikic/php-parser itself, like this similar patch https://github.com/nikic/PHP-Parser/commit/4bcdf74b8b65b172417ea40b99320faacff94a24 for static format printing that seems only will happen in php-parser 5.x.

**Comment by TomasVotruba** [comment]
Solved with class reprint, as the only way at the moment: https://github.com/rectorphp/rector-src/pull/3743#issuecomment-1537183721

**Pull request closed without merging**
