### PR TITLE
[Defluent] Skip create variable from not PropertyFetch on ReturnFluentChainMethodCallToNormalMethodCallRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
function helper(): FluentInterfaceClass
{
    return new FluentInterfaceClass();
}

class ReturnBasicDoubleFluent
{
    public function someFunction()
    {
        return helper()->someFunction()->otherFunction();
    }
}
```

It currently generate:

```diff
+        $fluentInterfaceClass = $fluentInterfaceClass->someFunction();
         $fluentInterfaceClass->someFunction();
         $fluentInterfaceClass->otherFunction();
         return $fluentInterfaceClass;
```

which `$fluentInterfaceClass` variable is never defined before, and it will make error undefined variable `fluentInterfaceClass`.

### CODE REVIEW

**Comment by samsonasik** [comment]
I think it should be skipped as `FluentMethodCalls` only accept MethodCall as root method call.

**Comment by samsonasik** [comment]
It seems needs to skip variable as well.

**Comment by samsonasik** [comment]
It seems there is bug in getting root method call as it not work on static property fetch as well. Given this:

```php
        self::$someClass = new FluentInterfaceClass();

        return self::$someClass->someFunction()
                        ->otherFunction();
```

got 

```diff
+        self::$someClass = new FluentInterfaceClass();
+        $fluentInterfaceClass = $fluentInterfaceClass->someFunction();
```

which `fluentInterfaceClass` never defined as well.

**Comment by samsonasik** [comment]
I am skipping MethodCall->var not property fetch for now.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
