### PR TITLE
[Php74] Add ParenthesizeNestedTernaryRector

### LINKED ISSUE #7432: Nested ternary expressions are depreceted since 7.4
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.12            |

We're trying to upgrade  a project from PHP 7.4 to 8.1 and came across a nested ternary expression which will error out in later PHP versions (8.0+)

## Minimal PHP Code Causing Issue
```php
    function nested_ternary()
    {
      $a = 1;
      $b = 2
      $value = $a ? $b : $a ?: null;
   }
```
## Expected Behaviour

Since the interpreter used to have some sort of handling it. It might be right to assume the previous working and give some sort of notice to recheck it manually? but also change it according to the previous handling (by adding parathesis RTL):
```php
    function nested_ternary()
    {
      $a = 1;
      $b = 2
      $value = ($a ? $b : $a) ?: null;
   }
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7432

### CODE REVIEW

**Comment by samsonasik** [comment]
implemented 🎉 /cc @fruitl00p

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased and regenerate docs

**Comment by samsonasik** [comment]
@TomasVotruba tests error seems related with removal of `symplify/easy-testing` at PR:

- https://github.com/rectorphp/rector-src/pull/2858

which cause error:
```bash

There were 8 errors:

1) Error
The data provider specified for Rector\Tests\Naming\Naming\UseImportsResolver\UseImportsResolverTest::testUsesFromProperty is invalid.
Error: Class "Symplify\EasyTesting\DataProvider\StaticFixtureFinder" not found
/home/runner/work/rector-src/rector-src/rules-tests/Naming/Naming/UseImportsResolver/UseImportsResolverTest.php:64
```

ref https://github.com/rectorphp/rector-src/runs/8107310730?check_suite_focus=true#step:5:76

**Comment by TomasVotruba** [comment]
Thank you 👍 


,I'm merging the PR as tests are in another PR

**Pull request merged**
