### PR TITLE
Fix stub PHPUnit\Framework\TestCase

### PR DESCRIPTION
**Pull request by samsonasik**
- [x] Fix stub conflict with PHPStan bootstrap Fixes https://github.com/rectorphp/rector/issues/7064
- [x] Fix preload.php generation weekly that scan `in($vendorDir . '/symplify/symfony-php-config')` that no longer exists, ref failure github action https://github.com/rectorphp/rector-src/runs/5614358700?check_suite_focus=true
- [x] Clean up unsused stub files as to be generated into preload.php

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
@TomasVotruba placing in `preload.php` seems make it checked too early for used as `composer require rector/rector`, which make not load original `PHPUnit\Framework\TestCase` when exists, while technically doesn't make error on rector run, should it be better place after 

https://github.com/rectorphp/rector-src/blob/e7c028396bdd50b7cdbb765cdadab6878730295e/bin/rector.php#L42

another possible location is place at include bootstrap file, at 

https://github.com/rectorphp/rector-src/blob/e7c028396bdd50b7cdbb765cdadab6878730295e/src/Autoloading/BootstrapFilesIncluder.php#L37

what do you think?

**Comment by TomasVotruba** [comment]
@samsonasik  Personally I'd go with 1:1 setup to PHPStan, so this file should be included in bootstrap files. Avoding any mock magic.
By keeping this standard, we'll have the same standardized solution for future cases.

**Comment by samsonasik** [comment]
@TomasVotruba ok, I updated to load in `BootstrapFilesIncluder` after all bootstrap file loaded https://github.com/rectorphp/rector-src/pull/1954/commits/8978258aff073bd58636d6b4dc7d98639e11edee with the following steps:

- check if `__DIR__ . '/../../stubs-rector/PHPUnit/Framework/TestCase.php'` exists, load
- copy `stubs-rector/PHPUnit/Framework/TestCase.php'` on build scoped

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
I moved to target-repository for use it only in scoped.

**Comment by samsonasik** [comment]
Let's give it a try ;)

**Comment by samsonasik** [comment]
@TomasVotruba it works 🎉 , tested in 2 repositories:

- https://github.com/bocharsky-bw/no-phpunit-rector-reproducer
- https://github.com/fancyweb/rector-7064/tree/master

**Pull request merged**
