### PR TITLE
Fix typo github worklfow

### PR DESCRIPTION
**Pull request by alamirault**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
The original text is correct. It's a single ramsey/composer package.

**Comment by alamirault** [comment]
Not sure to understand, PR add missing "a", not plural. But if it's ok no problem

**Comment by samsonasik** [comment]
@TomasVotruba the text is missing `a` character then:

```diff
-packges
+package
```

**Comment by TomasVotruba** [comment]
@samsonasik I see :+1: 

@alamirault I only looked at the last letter, my bad. The "a" is missing, and also plural is wrong.

**Pull request merged**
