### PR TITLE
MyCLabs enum equals + keeping methods 

### LINKED ISSUE #8051: MyCLabsClassToEnumRector: keeping methods in PHP Enums
# Feature Request

It should be possible to keep class methods from classes extending \MyCLabs\Enum\Enum in native PHP Enumerations
 
Unfortunately I wasnt able to reproduce it in demo 
https://getrector.com/demo/048e2209-68e7-48b0-abba-0d31c854eaeb

_______
Just out of curisoity I added `$enum->stmts = array_merge($enum->stmts, $class->getMethods());` to `\Rector\Php81\NodeFactory\EnumFactory::createFromClass` method and It "worked". But I dont have such experience with Rector so I dont know if this is the right solution or not.

### PR DESCRIPTION
**Pull request by K0nias**
Unfortunately I'm not sure of purpose of rules-tests/Php81/Rector/MethodCall/MyCLabsMethodCallToEnumConstRector/Fixture/usage_of_constant.php.inc and rules-tests/Php81/Rector/MethodCall/MyCLabsMethodCallToEnumConstRector/Fixture/usage_of_constant.php.inc test cases.

Why it should be possible to refactor non existing constants to native enum when this enum will not have those cases?

Closes https://github.com/rectorphp/rector/issues/8051

### CODE REVIEW

**Comment by samsonasik** [comment]
failing test case need to be updated, FQCN result seems expected

**Comment by K0nias** [comment]
I know that test cases need to be resolved. But I dont know how at this moment. In my opinion they are useless and can be deleted. But I am not author of thoses tests so maybe I dont see the proper use case for them.

**Comment by K0nias** [comment]
I removed that failing tests cases because I think that they were usesless. There is no need to refactor non existing enum constatns to new native cases. If there is use case for them please let me know. I will restore them and properly fix code to pass tests

**Comment by K0nias** [comment]
I cant figure out why this job https://github.com/rectorphp/rector-src/actions/runs/6013250808/job/16310321369?pr=4645 failing when my changes arent relevent to this check.

**Comment by samsonasik** [comment]
@K0nias I restarted CI build

**Comment by TomasVotruba** [comment]
CI looks good now :+1:  Is this ready to merge or something missing?

**Comment by K0nias** [comment]
From me it is ready to merge

**Comment by TomasVotruba** [comment]
Thank you 👍

**Pull request merged**
