### PR TITLE
[Php80] Handle crash after transform with trait-string on UnionTypesRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
class SkipUnionTraitString
{
    /**
     * @param string|trait-string $fromId
     */
    public function withFromId(string $fromId): static
    {
        return $this;
    }
}
```

It currently produce:

```diff
-    public function withFromId(string $fromId): static
+    public function withFromId(string|\trait-string $fromId): static
```

which cause error:

```
Parse error: syntax error, unexpected token "-", expecting variable
```

see 

- https://getrector.org/demo/44ae214d-d91b-4525-9b89-acc30728eea1
- https://3v4l.org/h0oG0

This PR try to fix it.

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
It require update on TypedPropertyRector to point the existing object type https://github.com/rectorphp/rector-src/pull/2985/commits/c441cf7533ba49a9b15ddc39e8da39ed6ed4b4cd so only apply intersection type when object types defined exists.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
