### PR TITLE
[Core] Use PropertyFetchAnalyzer::isFilledViaMethodCallInConstructStmts() in ConstructorAssignDetector::isPropertyAssigned()

### LINKED ISSUE #7176: Incorrect behavior of InitializeDefaultEntityCollectionRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.12.23      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/f657bbe9-7436-4a7d-b842-42e8c55441ab

```php
<?php

declare(strict_types=1);

namespace My\Ns;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\UuidInterface;

#[ORM\Entity]
class A
{
    /** @var Collection<int, stdClass> */
    #[ORM\ManyToMany(targetEntity: stdClass::class)]
    private Collection $labels;

    /** @param array<stdClass> $labels */
    public function __construct(
        array $labels,
    ) {
        $this->refreshLabels($labels);
    }

    /** @param array<stdClass> $labels */
    final public function refreshLabels(array $labels): void
    {
        $this->labels = new ArrayCollection($labels);
    }
}
```

### Responsible rules

* `InitializeDefaultEntityCollectionRector`

## Expected Behavior

It should initialize collection since it's initialized in a method called within final public method called in construcotr

### PR DESCRIPTION
**Pull request by samsonasik**
Check the property assigned via method call like in `CountOnNullRector` also happen in issue https://github.com/rectorphp/rector/issues/7176 which property fetch filled via method call.

This PR make the `PropertyFetchAnalyzer::isFilledViaMethodCallInConstructStmts()` called in `ConstructorAssignDetector::isPropertyAssigned()` to reduce repetitive check in multi rules usage, also:

- refactored to check only in inline Stmt for Expression
- refactored to check this/self/static check on current class or parent class that call it so object is belong to current class.

Fixes https://github.com/rectorphp/rector/issues/7176

### CODE REVIEW

**Comment by samsonasik** [comment]
@simPod should resolve https://github.com/rectorphp/rector/issues/7176 as use `ConstructorAssignDetector::isPropertyAssigned()` check in the Doctrine `InitializeDefaultEntityCollectionRector`

https://github.com/rectorphp/rector-doctrine/blob/4a907ede0f35a562aadc63eebadf34e8d3d3d388/src/Rector/Class_/InitializeDefaultEntityCollectionRector.php#L124

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
Also update reference for `static` as local property fetch scope for parent-current filling ability.

https://github.com/rectorphp/rector-src/pull/2351/files#diff-8aaa77d0dfff0b00613882023d59d4c5ad88d6cd8427341501c951ff78c4a962

**Comment by TomasVotruba** [comment]
Go for merge when ready :+1:

**Pull request merged**
