### PR TITLE
[TypeDeclaration] Skip void on BoolReturnTypeFromBooleanStrictReturnsRector

### LINKED ISSUE #8717: Rector adds bool return type to void functions/methods
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | dev-main             |

## Minimal PHP Code Causing Issue

https://getrector.com/demo/299253f8-253d-4782-955c-7f2444906bc7

## Expected Behaviour

Rector should add void/never return types to these functions/methods (if applicable)

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8717
Ref https://getrector.com/demo/299253f8-253d-4782-955c-7f2444906bc7

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @OA

**Comment by samsonasik** [comment]
I moved possible void check into `BetterNodeFinder::findReturnsScoped()`

**Comment by samsonasik** [comment]
Moving check into BetterNodeFinder seems cause cycling dependency, due to SilentVoidResolver require `BetterNodeFinder` so cause flip flop...

**Comment by samsonasik** [comment]
The solution for now is verify :

```php
if (! $this->returnAnalyzer->hasOnlyReturnWithExpr($functionLike)) {
    return null;
}
```

into each type declaration rules, since has a way to verify possible void

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it to have faster feedback to test ;)

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by OA** [comment]
looks good on our side!

**Pull request merged**
