### PR TITLE
[Php74] Add GetCalledClassToSelfClassRector

### PR DESCRIPTION
**Pull request by samsonasik**
There is already `GetCalledClassToStaticClassRector` rule, but it change to `static::class`even on final class, which can be `self::class` instead.

This PR add `GetCalledClassToSelfClassRector` for final class and skip `GetCalledClassToStaticClassRector` for final class so the change can work together if both rules used:

- [x] mark self::class for final class with `GetCalledClassToSelfClassRector`
- [x] mark static::class for non-final class with `GetCalledClassToStaticClassRector`

### CODE REVIEW

**Comment by samsonasik** [comment]
skip trait for GetCalledClassToSelfClassRector, lets GetCalledClassToStaticClassRector handle to use static::class

**Comment by samsonasik** [comment]
use self::class on GetCalledClassToSelfClassRector for anonymous class as the anonymous class is not to be extended.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks for this one :+1:

**Pull request merged**
