### PR TITLE
[Scoped] Add e2e define constant error on php 7.x

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba this is e2e test for scoped with define constant like in https://github.com/rectorphp/rector/issues/6779#issuecomment-959945807

- Sample reproduced repo https://github.com/samsonasik/rector-issue-php74
- Sample code that reproduce it:

https://github.com/samsonasik/rector-issue-php74/blob/0b470358cb120f0f452b1bd55885d64edd6cbbd1/src/Test.php#L3-L5
```php
if (! defined('APPPATH')) {
    define('APPPATH', realpath(rtrim($paths->appDirectory, '\\/ ')) . DIRECTORY_SEPARATOR);
}
```

Github action that show the error on php 7.4:

https://github.com/samsonasik/rector-issue-php74/runs/4097757321?check_suite_focus=true#step:5:6

This should error on scoped build at rector/rector if merged.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Looks good. It should be failing here, right?

**Comment by samsonasik** [comment]
No, it will only fail on "rector/rector" with php 7.x only after it merged and pushed to rector/rector:

https://github.com/rectorphp/rector/blob/8db8a4be7b606e491ba74f706965b946f7c9c9e8/.github/workflows/e2e.yaml#L18

should it be merged to test?

**Comment by TomasVotruba** [comment]
Ah, I see. In that case we'll merge it first then.

It would be better to have this feedback as soon as possible. The downgrade build takes too much time to test it effectively now. Maybe we!ll should focus on parallel run.

**Comment by samsonasik** [comment]
Ok, I am merging it, for scoped process, currently stopped as code "137" 

https://github.com/rectorphp/rector-src/runs/4104416921?check_suite_focus=true#step:9:15037

which means memory is not enough on CI.

It runs ok on my local dev. I will try to split long listed directory at :

https://github.com/rectorphp/rector-src/blob/e64cf0569dbda54212196b0d42ca19e8be2bb1fe/utils/compiler/src/Command/DowngradePathsCommand.php#L47

and try locally first to see if that works to reduce memory usage on build scoped.

**Comment by samsonasik** [comment]
the `e2e/define-constant` is displayed error on:

https://github.com/rectorphp/rector/runs/4106986477?check_suite_focus=true#step:5:7

for PHP 7.x

**Pull request merged**
