### PR TITLE
[Differ] Remove DefaultDiffer, use ConsoleDiffer instead to avoid double diffing process

### PR DESCRIPTION
**Pull request by samsonasik**
@staabm this is the rework effort from your original PR:

- https://github.com/rectorphp/rector-src/pull/3705

to avoid double diffing process.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

@staabm if this get accepted, it needs verify to real dedicated under windows tho in case of change.

**Comment by TomasVotruba** [comment]
The clean diff for json output should remain.

**Comment by samsonasik** [comment]
I see, it seems they are different now:

```
➜  rector-src git:(remove-default-differ) ✗ bin/rector process src/Console/Formatter/ColorConsoleDiffFormatter.php --output-format json 
{
    "totals": {
        "changed_files": 1,
        "errors": 0
    },
    "file_diffs": [
        {
            "file": "src/Console/Formatter/ColorConsoleDiffFormatter.php",
            "diff": "<comment>    ---------- begin diff ----------</comment>\n<fg=cyan>@@ @@</fg=cyan>\n\n     private string $template;\n\n<fg=red>-    private string $unused;</fg=red>\n<fg=red>-</fg=red>\n     public function __construct()\n     {\n         $this-\\>template = sprintf(\n<comment>    ----------- end diff -----------</comment>\n",
            "applied_rectors": [
                "Rector\\DeadCode\\Rector\\Property\\RemoveUnusedPrivatePropertyRector"
            ]
        }
    ],
    "changed_files": [
        "src/Console/Formatter/ColorConsoleDiffFormatter.php"
    ]
}


➜  rector-src git:(remove-default-differ) git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
➜  rector-src git:(main) bin/rector process src/Console/Formatter/ColorConsoleDiffFormatter.php --output-format json
{
    "totals": {
        "changed_files": 1,
        "errors": 0
    },
    "file_diffs": [
        {
            "file": "src/Console/Formatter/ColorConsoleDiffFormatter.php",
            "diff": "--- Original\n+++ New\n@@ -36,8 +36,6 @@\n \n     private string $template;\n \n-    private string $unused;\n-\n     public function __construct()\n     {\n         $this->template = sprintf(\n",
            "applied_rectors": [
                "Rector\\DeadCode\\Rector\\Property\\RemoveUnusedPrivatePropertyRector"
            ]
        }
    ],
    "changed_files": [
        "src/Console/Formatter/ColorConsoleDiffFormatter.php"
    ]
}
```

**Comment by samsonasik** [comment]
Closing for now.

**Pull request closed without merging**
