### PR TITLE
[CodeQuality] Handle possible crash on ParametersAcceptorSelector::selectSingle() on OptionalParametersAfterRequiredRector

### LINKED ISSUE #7660: OptionalParametersAfterRequiredRector fails with `use selectFromArgs() instead.`
# Bug Report

Very similar to Issue #7297 I suppose. So maybe it is also related to Windows.

It is from a rule included in \Rector\Set\ValueObject\SetList::CODE_QUALITY

The mentioned PackageOptions.php is sadly 1000 lines long, and it doesn't indicate anywhere to look. So I'm not sure how to minimize.

<!-- First, thank you for reporting a bug. That takes time and we appreciate that! -->

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Rector 0.15.0             |

output from `php.exe .\vendor\bin\rector process --dry-run --debug app\Product\PackageOptions.php`

```
[file] app\Product\PackageOptions.php
[rule] Rector\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRector


                                                                                                                        
                                                  .php" file, due to: 
                                             use selectFromArgs() instead."
                                                                                                               
                                                                                                   
         #0 C:\H\product_api\vendor\rector\rector\rules\Php80\NodeResolver\RequireOptionalParamResolver.php(16):            
         PHPStan\Reflection\ParametersAcceptorSelector::selectSingle(Array)                                             
         #1                                                                                                             
         C:\H\product_api\vendor\rector\rector\rules\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRector.ph
         p(168):                                                                                                        
         Rector\Php80\NodeResolver\RequireOptionalParamResolver->resolveFromReflection(Object(PHPStan\Reflection\Native 
         \NativeMethodReflection))                                                                                      
         #2                                                                                                             
         C:\H\product_api\vendor\rector\rector\rules\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRector.ph
         p(122):                                                                                                        
         Rector\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRector->resolveExpectedArgParamOrderIfDif 
         ferent(Object(PHPStan\Reflection\Native\NativeMethodReflection), Object(PhpParser\Node\Expr\New_))             
         #3                                                                                                             
         C:\H\product_api\vendor\rector\rector\rules\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRector.ph
         p(93):                                                                                                         
         Rector\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRector->refactorNew(Object(PhpParser\Node 
         \Expr\New_))                                                                                                   
         #4 C:\H\product_api\vendor\rector\rector\src\Rector\AbstractRector.php(216):                                       
         Rector\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRector->refactor(Object(PhpParser\Node\Ex 
         pr\New_))                                                                                                      
         #5 C:\H\product_api\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(113):             
         Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\New_))                                 
         #6 C:\H\product_api\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(133):             
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))                                      
         #7 C:\H\product_api\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):             
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))                                  
         #8 C:\H\product_api\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):             
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #9 C:\H\product_api\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):             
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))                                 
         #10 C:\H\product_api\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):            
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #11 C:\H\product_api\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):            
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))                                      
         #12 C:\H\product_api\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(105):            
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #13 C:\H\product_api\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(196):            
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))                                  
         #14 C:\H\product_api\vendor\rector\rector\vendor\nikic\php-parser\lib\PhpParser\NodeTraverser.php(85):             
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #15 C:\H\product_api\vendor\rector\rector\src\PhpParser\NodeTraverser\RectorNodeTraverser.php(42):                 
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #16 C:\H\product_api\vendor\rector\rector\src\Application\FileProcessor.php(60):                                   
         Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                       
         #17 C:\H\product_api\vendor\rector\rector\src\Application\FileProcessor\PhpFileProcessor.php(133):                 
         Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File),              
         Object(Rector\Core\ValueObject\Configuration))                                                                 
         #18 C:\H\product_api\vendor\rector\rector\src\Application\FileProcessor\PhpFileProcessor.php(101):                 
         Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Object(Rector\Core\ValueObjec 
         t\Application\File), Object(Rector\Core\ValueObject\Configuration))                                            
         #19 C:\H\product_api\vendor\rector\rector\packages\Parallel\WorkerRunner.php(98):                                  
         Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Object(Rector\Core\ValueObject\Application\Fil 
         e), Object(Rector\Core\ValueObject\Configuration))                                                             
         #20 C:\H\product_api\vendor\rector\rector\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(97):      
         Rector\Parallel\WorkerRunner->Rector\Parallel\{closure}(Array)                                                 
         #21 C:\H\product_api\vendor\rector\rector\vendor\clue\ndjson-react\src\Decoder.php(110):                           
         RectorPrefix202212\Evenement\EventEmitter->emit('data', Array)                                                 
         #22 C:\H\product_api\vendor\rector\rector\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(97):      
         RectorPrefix202212\Clue\React\NDJson\Decoder->handleData(Array)                                                
         #23 C:\H\product_api\vendor\rector\rector\vendor\react\stream\src\Util.php(62):                                    
         RectorPrefix202212\Evenement\EventEmitter->emit('data', Array)                                                 
         #24 C:\H\product_api\vendor\rector\rector\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(97):      
         RectorPrefix202212\React\Stream\Util::RectorPrefix202212\React\Stream\{closure}('{"action":"main...')          
         #25 C:\H\product_api\vendor\rector\rector\vendor\react\stream\src\DuplexResourceStream.php(154):                   
         RectorPrefix202212\Evenement\EventEmitter->emit('data', Array)                                                 
         #26 C:\H\product_api\vendor\rector\rector\vendor\react\event-loop\src\StreamSelectLoop.php(201):                   
         RectorPrefix202212\React\Stream\DuplexResourceStream->handleData(Resource id #2842)                            
         #27 C:\H\product_api\vendor\rector\rector\vendor\react\event-loop\src\StreamSelectLoop.php(173):                   
         RectorPrefix202212\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                               
         #28 C:\H\product_api\vendor\rector\rector\src\Console\Command\WorkerCommand.php(63):                               
         RectorPrefix202212\React\EventLoop\StreamSelectLoop->run()                                                     
         #29 C:\H\product_api\vendor\rector\rector\vendor\symfony\console\Command\Command.php(311):                         
         Rector\Core\Console\Command\WorkerCommand->execute(Object(RectorPrefix202212\Symfony\Component\Console\Input\A 
         rgvInput), Object(RectorPrefix202212\Symfony\Component\Console\Output\ConsoleOutput))                          
         #30 C:\H\product_api\vendor\rector\rector\vendor\symfony\console\Application.php(898):                             
         RectorPrefix202212\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202212\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202212\Symfony\Component\Console\Output\ConsoleOutput))           
         #31 C:\H\product_api\vendor\rector\rector\vendor\symfony\console\Application.php(319):                             
         RectorPrefix202212\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\Work 
         erCommand), Object(RectorPrefix202212\Symfony\Component\Console\Input\ArgvInput),                              
         Object(RectorPrefix202212\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #32 C:\H\product_api\vendor\rector\rector\src\Console\ConsoleApplication.php(49):                                  
         RectorPrefix202212\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202212\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202212\Symfony\Component\Console\Output\ConsoleOutput))             
         #33 C:\H\product_api\vendor\rector\rector\vendor\symfony\console\Application.php(206):                             
         Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix202212\Symfony\Component\Console\Input\ArgvIn 
         put), Object(RectorPrefix202212\Symfony\Component\Console\Output\ConsoleOutput))                               
         #34 C:\H\product_api\vendor\rector\rector\bin\rector.php(128):                                                     
         RectorPrefix202212\Symfony\Component\Console\Application->run()                                                
         #35 C:\H\product_api\vendor\rector\rector\bin\rector(4): require_once('C:\\H\\product_api\\ve...')                     
         #36 C:\H\product_api\vendor\bin\rector(115): include('C:\\H\\product_api\\ve...')                                      
         #37 {main}". On line: 58                                                                                       
```

## Minimal PHP Code Causing Issue

<!-- Reproduce the issue using https://getrector.org/demo/ and post the URL here. -->

## Expected Behaviour

<!-- How should Rector change the code? Or should Rector skip it? -->

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7660

### CODE REVIEW

**Comment by samsonasik** [comment]
@HenkPoley  this should fix https://github.com/rectorphp/rector/issues/7660

**Comment by samsonasik** [comment]
PHPStan notice seems due to new PHPStan release:

https://github.com/phpstan/phpstan/releases/tag/1.9.3

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
The error in `DowngradeMatchToSwitchRectorTest` seems unrelated:

```
There was 1 error:

1) Rector\Tests\DowngradePhp80\Rector\Expression\DowngradeMatchToSwitchRector\DowngradeMatchToSwitchRectorTest::test with data set #10 ('/home/runner/work/rector-src/...hp.inc')
LogicException: Trying to replace expression (Expr_ConstFetch) with statement (Stmt_Switch)
```

I will look in `AbstractRector` if there is something can be fixed.

**Comment by samsonasik** [comment]
It seems fixed by always save `$this->nodesToReturn[$originalNodeHash]` on `AbstractRector`: https://github.com/rectorphp/rector-src/pull/3192/commits/f6164f0cd6a4fe0cca0d767212f02c2b2b8e0e1f

On result, the Rector will need double run on `NewlineAfterStatementRector` after PhpDocInfo changed by other rule https://github.com/rectorphp/rector-src/pull/3192/commits/ea22a735867613fc663152668052340c6f1db409 , which seems reasonable :)

**Comment by samsonasik** [comment]
Finally 🎉 All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you for all the related improvements as well :+1:

**Pull request merged**
