### PR TITLE
TASK: Do not prefix ComposerJson class

### LINKED ISSUE #6405: Do not prefix Symplify\ComposerJsonManipulator\ValueObject\ComposerJson?
The class Symplify\ComposerJsonManipulator\ValueObject\ComposerJson is part of the public API of Rector because it is required by the ComposerRectorInterface. I think it should not be prefixed.

### PR DESCRIPTION
**Pull request by sabbelasichon**
Resolves: https://github.com/rectorphp/rector/issues/6405

### CODE REVIEW

**Comment by samsonasik** [comment]
How about register to scoper config?

https://github.com/rectorphp/rector-src/blob/1d037d151f713a2568159a3aad82121cbd076883/scoper.php#L45

**Comment by sabbelasichon** [comment]
@samsonasik I don´t really know to be honest. I have basically done it the way how SmartFileInfo is configured. https://github.com/rectorphp/rector-src/blob/1d037d151f713a2568159a3aad82121cbd076883/scoper.php#L67

**Review by samsonasik — APPROVED** [review]
Ok 👍

**Review by TomasVotruba — CHANGES_REQUESTED** [review]
This way is wrong, as it skip classes that are prefixed. See https://github.com/rectorphp/rector-src/pull/2586#issuecomment-1169197056

It must be resolved in `scoper.php` with exclude/expose.

**Comment by sabbelasichon** [comment]
Could you explain why SmartFileInfo is not prefixed but is not in exclude-classes?

**Comment by samsonasik** [comment]
Current `SmartFileInfo` class is registered in bootstrap.php too, which iirc, if it removed, it will got error class not found in phpunit custom rector rule, that was on scoper 0.14.

I will check if it still issue if we remove it from bootstrap.php

**Comment by samsonasik** [comment]
@sabbelasichon @TomasVotruba I just tried latest `rector/rector:dev-main` on https://github.com/laminas/laminas-servicemanager-migration for custom rule:

```bash
git clone https://github.com/laminas/laminas-servicemanager-migration.git
cd laminas-servicemanager-migration && composer require rector/rector:dev-main
```

and removed the `Symplify\SmartFileSystem\SmartFileInfo` registration from `bootstrap.php`:

https://github.com/rectorphp/rector-src/blob/d1807682bf00aeb1cbe87756a897b7ff77bd2bf5/build/target-repository/bootstrap.php#L27-L33

and it seems working ok:

```bash
vendor/bin/phpunit 
PHPUnit 9.5.20 #StandWithUkraine

...................                                               19 / 19 (100%)

Time: 00:03.214, Memory: 148.50 MB

OK (19 tests, 38 assertions)
```

both `SmartFileInfo` and `ComposerJson` are already registered in `scoper.php` config:

https://github.com/rectorphp/rector-src/blob/d1807682bf00aeb1cbe87756a897b7ff77bd2bf5/scoper.php#L64-L69

so it should be working without adding it, it mapped in `rector/rector` prefixed in result:

https://github.com/rectorphp/rector/blob/6f73a90692f25f2a245a44579580899fa0b8d3d4/vendor/scoper-autoload.php#L9-L14

@sabbelasichon could you try latest `rector/rector:dev-main` and verify if it is working ok without registering in bootstrasp.php ?

**Comment by sabbelasichon** [comment]
Sorry for the noise, you are absolutely right. It works in dev-main, but i was requiring 0.13.35.

**Pull request closed without merging**
