### PR TITLE
[DX] Check only for current scope in RemoveUnusedVariableInCatchRector, as magic exception use is bad practise and should be avoided

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref https://github.com/rectorphp/rector/issues/7947

### CODE REVIEW

**Comment by samsonasik** [comment]
This cause invalid change on my `ErrorHeroModule`:

```diff
➜  ErrorHeroModule git:(master) time bin/rector 
 58/58 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
2 files with changes
====================

1) src/Middleware/Mezzio.php:55

    ---------- begin diff ----------
@@ @@
             $this->request = $serverRequest;
             $this->phpError();
             return $requestHandler->handle($serverRequest);
-        } catch (Throwable $throwable) {
+        } catch (Throwable) {
         }

         return $this->exceptionError($throwable);
    ----------- end diff -----------

Applied rules:
 * RemoveUnusedVariableInCatchRector (https://wiki.php.net/rfc/non-capturing_catches)


2) src/Command/BaseLoggingCommand.php:45

    ---------- begin diff ----------
@@ @@
         try {
             $this->phpError();
             return parent::run($input, $output);
-        } catch (Throwable $throwable) {
+        } catch (Throwable) {
         }

         return $this->exceptionError($throwable);
    ----------- end diff -----------

Applied rules:
 * RemoveUnusedVariableInCatchRector (https://wiki.php.net/rfc/non-capturing_catches)


                                                                                                                        
 [OK] 2 files have been changed by Rector                                                                               
                                                                                                                        

bin/rector  16.78s user 0.67s system 177% cpu 9.853 total
```

I will check if it can be refactored with `StmtsAwareInterface` instead to get `Variable` scope.

**Comment by samsonasik** [comment]
I created PR https://github.com/rectorphp/rector-src/pull/4459 for it.

**Comment by TomasVotruba** [comment]
Such practise should be still avoided in any code. The optional variable are dangerous.

**Comment by samsonasik** [comment]
I see, but breaking change should be avoided as well ;), imagine we see that in thousands of files, manually check should be avoided.

**Comment by TomasVotruba** [comment]
Good point :)

**Pull request merged**
