### PR TITLE
[Renaming] Remove RenameClassRector::processCleanUpUse() as already covered on ClassRenamingPostRector

### PR DESCRIPTION
**Pull request by samsonasik**
- Process clean up use is covered on `ClassRenamingPostRector` after rename
- Process add use statement for new name covered on `UseAddingPostRector` after cleaned up

so it can be removed.

### CODE REVIEW

**Comment by samsonasik** [comment]
it seems cause error on `DowngradeMatchToSwitchRectorTest` https://github.com/rectorphp/rector-src/actions/runs/4355251432/jobs/7611617002#step:7:31

Closing for now.

**Comment by samsonasik** [comment]
Re-open, let's check with verify `Use_` already empty on `UnusedImportRemovingPostRector`

**Comment by samsonasik** [comment]
It works 🎉 All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
