### PR TITLE
[TASK] Split up different phases for PhpFileProcessor

### PR DESCRIPTION
**Pull request by sabbelasichon**
Relates: rectorphp/rector#6380

### CODE REVIEW

**Comment by sabbelasichon** [comment]
This is the first refactoring step in order to get to a global ProgressBar for every FileProcessor

**Comment by sabbelasichon** [comment]
Is the error related to my change? Not sure.

**Comment by samsonasik** [comment]
@sabbelasichon please rebase in favor of https://github.com/rectorphp/rector-src/pull/43

**Comment by sabbelasichon** [comment]
Didn´t read the message. Sorry for asking.

**Comment by sabbelasichon** [comment]
Maybe it is useful to solve the priority thingy in a compiler pass.

**Comment by sabbelasichon** [comment]
So we can use it in different places.

**Comment by samsonasik** [comment]
@sabbelasichon it needs rebase

**Pull request closed without merging**
