### PR TITLE
Revert all is* changes

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba @yguedidi let's try revert all is* changes.

### CODE REVIEW

**Comment by samsonasik** [comment]
It seems working ok now, let's merge 👍

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by yguedidi** [comment]
Thank you @samsonasik and again sorry for the extra work!
So if I understood correctly both tests and rector run on rector must be green to be OK?
I'll opens some PRs again! :)

**Comment by samsonasik** [comment]
I already start with most safe type: void https://github.com/rectorphp/rector-src/pull/3586

You can see the rector and cs run on the workflow https://github.com/rectorphp/rector-src/blob/main/.github/workflows/rector.yaml#L12

You can run:

```
bin/rector src tests rules-tests packages packages-tests
bin/rector rules
 bin/rector config utils
```

**Comment by yguedidi** [comment]
@samsonasik perfect! thank you! I'll make sure to open PRs for the others running all those checks!

**Pull request merged**
