### PR TITLE
[CodingStyle] Do not escape expression on ConsistentPregDelimiterRector with double quote

### PR DESCRIPTION
**Pull request by samsonasik**
If `$` is an end anchor, it should not be escaped. Given the following code:

```php
preg_match("/^value$/", $value);
```

it currently produce:

```diff
+ preg_match("#^value\$#", $value);
```

which should be fine to be:

```diff
+ preg_match("#^value$#", $value);
```

### CODE REVIEW

**Review by TomasVotruba — APPROVED** [review]

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
After delimiter, there is possible modifier, eg, `/u` that seems need to be handled as well.

**Comment by samsonasik** [comment]
updated to allow modifier

**Comment by samsonasik** [comment]
It seems it is not about `$` anchor, but about double quoted regex, when we have regex:

```php
$specs = preg_match("/(?:\.['\p{L}-]+|\s\.|^\.)/u", $value);
```

it changed to:

```diff
+        $specs = preg_match("#(?:\\.['\\p{L}-]+|\\s\\.|^\\.)#u", $value);
```

which actually, without `\` escape is fine for `\p{L}`, or `\.`

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
