### PR TITLE
Adjust downgrade config for rector build

### PR DESCRIPTION
**Pull request by sabbelasichon**
Resolves: https://github.com/rectorphp/rector/issues/6624

### CODE REVIEW

**Comment by samsonasik** [comment]
Thank you @sabbelasichon

**Comment by samsonasik** [comment]
It seems not resolved yet 

https://github.com/rectorphp/rector/blob/33fe0e38c0d2eba9227a5d6a5448fa10085f46a6/vendor/ssch/typo3-rector/src/FileProcessor/TypoScript/Rector/AbstractTypoScriptRector.php#L23

**Comment by TomasVotruba** [comment]
Probably aim the highest interface(s):

```php
... implements \RectorPrefix20210811\Helmich\TypoScriptParser\Parser\Traverser\Visitor, 
\Ssch\TYPO3Rector\Contract\FileProcessor\TypoScript\TypoScriptRectorInterface
{
```

**Comment by samsonasik** [comment]
@TomasVotruba I tried locally and it seems using : 

```php
\Helmich\TypoScriptParser\Parser\Traverser\Visitor::class
```

solve it.

**Comment by samsonasik** [comment]
I created PR https://github.com/rectorphp/rector-src/pull/646 for it

**Pull request merged**
