### PR TITLE
Add failing test fixture for ClassPropertyAssignToConstructorPromotio…

### PR DESCRIPTION
**Pull request by berezuev**
…nRector

# Failing Test for ClassPropertyAssignToConstructorPromotionRector

Based on https://getrector.org/demo/1ec791b9-a03d-67f8-9c5f-591c1ce23882

### CODE REVIEW

**Comment by berezuev** [comment]
Related to https://github.com/rectorphp/rector/issues/6949

**Comment by samsonasik** [comment]
CI seems green, it possibly already resolved or related with multiple rules applied, could you try `"rector/rector": "dev-main"` or narrow down rules in the SetList? Using `-vvv` possibly can show the rules applied.

**Comment by samsonasik** [comment]
It seems because of combination between 2 rules:

```php
Rector\Php80\Rector\Class_\ClassPropertyAssignToConstructorPromotionRector
Rector\Php80\Rector\Class_\AnnotationToAttributeRector
```

**Comment by samsonasik** [comment]
I copied your fixture at PR https://github.com/rectorphp/rector-src/pull/1712 as test fixture need to be in `test/Issues` for multiple rules applied.

**Pull request closed without merging**
