### PR TITLE
[DI] Remove symfony/dependency-injection dependency

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref https://github.com/rectorphp/rector-src/pull/4698

## Before

Screenshot from 2023-08-16 01-30-37

## After

Screenshot from 2023-08-16 01-31-15

↓

From 2 686 to 2 394 classes :partying_face:

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Resulting build - dropped 32 000 lines :muscle:  https://github.com/rectorphp/rector/commit/acc38e22159d5c5a00abb0f0b927ec6fdd1416df

Screenshot from 2023-08-16 01-38-06

**Comment by TomasVotruba** [comment]
Ref https://github.com/rectorphp/rector/commit/acc38e22159d5c5a00abb0f0b927ec6fdd1416df#diff-6b8788a9ad06a4eec447e0adb401c73abf6b9855c9cf778a26e4c0d9bb189d33

**Comment by rvanlaak** [comment]
In order to determine the diff; given this PR solely is because of the removal, do we also have any idea how many lines were added because of the Laravel container?

**Comment by TomasVotruba** [comment]
Depends what you try to compare. The Laravel container package was added in https://github.com/rectorphp/rector-src/pull/4106, 1,5 month ago. This PR results in this diff: https://github.com/rectorphp/rector/commit/9e103260ecc8f90fb3e4da3b30fd98028eb4bb57

The container package itself:

```bash
 vendor/bin/lines measure vendor/illuminate/container --short
```

Shows 1090 lines of code:

```bash
 ------------------------------ --------------------- 
  Metric                                       Count  
 ------------------------------ --------------------- 
  Directories                                      0  
  Files                                            6  
 ------------------------------ --------------------- 

 ------------------------------ ---------- ---------- 
  Lines of code                     Count   Relative  
 ------------------------------ ---------- ---------- 
  Code                              1 090       56 %  
  Comments                            855       44 %  
  Total                             1 945      100 %  
 ------------------------------ ---------- ---------- 

```

**Comment by TomasVotruba** [comment]
The same for Symfony would be:

```bash
vendor/bin/lines measure vendor/symfony/dependency-injection --short
```

↓

```bash
  Filesystem                                         count  
  Directories ......................................... 14  
  Files .............................................. 186  

  Lines of code                           count / relative  
  Code ................................... 17 694 /   79 %  
  Comments ................................ 4 698 /   21 %  
  Total .................................. 22 392 /  100 %  
```

**Pull request merged**
