### PR TITLE
Run tests on macos

### PR DESCRIPTION
**Pull request by staabm**
I would love to also add tests for windows, but atm the test-suite contains lots of errors on windows

### CODE REVIEW

**Comment by staabm** [comment]
the macos builds are slower but I think still worth it

**Comment by samsonasik** [comment]
@TomasVotruba the 

```
 PHP 8.1 tests Expected — Waiting for status to be reported 
```

need to be enabled.

**Comment by TomasVotruba** [comment]
@samsonasik Done :+1: 

@staabm Thanks! I thought some would be failing :clap:  I'm happy you've managed to handle fixes to ship it.

**Comment by staabm** [comment]
Kudos to @samsonasik who fixed those I didn't catch :-)

**Pull request merged**
