### PR TITLE
[PSR4] Add configurable migrateInnerClassReference to NormalizeNamespaceByPSR4ComposerAutoloadRector

### LINKED ISSUE #7232: NormalizeNamespaceByPSR4ComposerAutoloadRector does not update references
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version |   0.13.5          |

I am trying to migrate some very old projects (e.g. https://github.com/RSS-Bridge/rss-bridge) to PSR-4 and `NormalizeNamespaceByPSR4ComposerAutoloadRector` adds the namespaces correctly but it does not seem to update the references to the moved classes, not even with `ClassRenamingPostRector`.

```
2 files with changes
====================

1) src/Foo/Foo.php:0

    ---------- begin diff ----------
@@ @@
 <?php

+namespace Test\Foo;
+
 class Foo {
-    public function test(): Bar {
-        return new Bar;
+    public function test(): \Bar {
+        return new \Bar;
     }
 }
    ----------- end diff -----------

Applied rules:
 * NormalizeNamespaceByPSR4ComposerAutoloadRector


2) src/Bar.php:0

    ---------- begin diff ----------
@@ @@
 <?php

+namespace Test;
+
 class Bar {
-    public function test(): Foo {
-        return new Foo;
+    public function test(): \Foo {
+        return new \Foo;
     }
 }
    ----------- end diff -----------

Applied rules:
 * NormalizeNamespaceByPSR4ComposerAutoloadRector
```

## Minimal PHP Code Causing Issue

TBD

## Expected Behaviour

The references should be updated appropriately.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7232

### CODE REVIEW

**Comment by jtojnar** [comment]
Looks like it goes too much to the other direction and changes references to classes that are not moved around:

```patch
34) app/Router/RouterFactory.php:1

    ---------- begin diff ----------
@@ @@

 declare(strict_types=1);

-namespace App;
+namespace App\Router;

-use Nette\Application\Routers\Route;
-use Nette\Application\Routers\RouteList;
+use \App\Router\Nette\Application\Routers\Route;
+use \App\Router\Nette\Application\Routers\RouteList;

 class RouterFactory {
-	public function createRouter(): RouteList {
+	public function createRouter(): \App\Router\Nette\Application\Routers\RouteList {
    ----------- end diff -----------

Applied rules:
 * NormalizeNamespaceByPSR4ComposerAutoloadRector
```

**Comment by jtojnar** [comment]
Also it seems to duplicate some in-app namespaces:

```patch

33) app/Model/Orm/PostRevision/PostRevisionMapper.php:1

    ---------- begin diff ----------
@@ @@

 declare(strict_types=1);

-namespace App\Model;
+namespace App\Model\Orm\PostRevision;

-class PostRevisionMapper extends BaseMapper {
+class PostRevisionMapper extends \App\Model\Orm\PostRevision\App\Model\BaseMapper {
…
Applied rules:
 * NormalizeNamespaceByPSR4ComposerAutoloadRector

18) app/Model/Orm/BaseMapper.php:1

    ---------- begin diff ----------
@@ @@

 declare(strict_types=1);

-namespace App\Model;
+namespace App\Model\Orm;

-use Nextras\Orm\Mapper\Mapper;
+use \App\Model\Orm\Nextras\Orm\Mapper\Mapper;

-class BaseMapper extends Mapper {
+class BaseMapper extends \App\Model\Orm\Nextras\Orm\Mapper\Mapper {
…

Applied rules:
 * NormalizeNamespaceByPSR4ComposerAutoloadRector
```

**Comment by samsonasik** [comment]
I am aware of it, that's why I created a failing test case to use fqcn from use statement when found in use statement https://github.com/rectorphp/rector-src/pull/2480/files#diff-17eb97e1d714a541337e050b5918c863083702dc9e353e3bb4c687a2b1db8a9c

**Comment by jtojnar** [comment]
I am starting to think this might be impossible to do in a single pass and we will need something like `ClassRenamingPostRector`. Though the simplest reliable design I can come up with requires three passes:

1. Run `NormalizeNamespaceByPSR4ComposerAutoloadRector` modified to only collect the class renames, without any AST modification.
2. Update all references that match what was collected.
3. Run `NormalizeNamespaceByPSR4ComposerAutoloadRector` for real.

**Comment by samsonasik** [comment]
Feel free to create separate PR if you have different solution, thank you.

**Comment by samsonasik** [comment]
implemented 🎉

**Comment by jtojnar** [comment]
That still does not seem to work for the example from https://github.com/jtojnar/repro/tree/8c7abd821775fa2d1071a2e98c8207b6132ad4da/rector-7232:

```patch
2 files with changes
====================

1) src/Foo/Foo.php:0

    ---------- begin diff ----------
@@ @@
 <?php

-namespace Test;
+namespace Test\Foo;

 class Foo {
-    public function test(): Bar {
-        return new Bar;
+    public function test(): \Test\Bar {
+        return new \Test\Bar;
     }
 }
    ----------- end diff -----------

Applied rules:
 * NormalizeNamespaceByPSR4ComposerAutoloadRector


2) src/Bar/Bar.php:0

    ---------- begin diff ----------
@@ @@
 <?php

-namespace Test;
+namespace Test\Bar;

 class Bar {
-    public function test(): Foo {
-        return new Foo;
+    public function test(): \Test\Foo {
+        return new \Test\Foo;
     }
 }
    ----------- end diff -----------

Applied rules:
 * NormalizeNamespaceByPSR4ComposerAutoloadRector
```

**Comment by jtojnar** [comment]
Nor with the [simpler one](https://github.com/jtojnar/repro/tree/f0bf15d733116050f1526140c6b9210b5beeea87/rector-7232):

```patch
2 files with changes
====================

1) src/Foo/Foo.php:0

    ---------- begin diff ----------
@@ @@
 <?php

+namespace Test\Foo;
+
 class Foo {
-    public function test(): Bar {
-        return new Bar;
+    public function test(): \Test\Foo\Bar {
+        return new \Test\Foo\Bar;
     }
 }
    ----------- end diff -----------

Applied rules:
 * NormalizeNamespaceByPSR4ComposerAutoloadRector


2) src/Bar.php:0

    ---------- begin diff ----------
@@ @@
 <?php

+namespace Test;
+
 class Bar {
-    public function test(): Foo {
-        return new Foo;
+    public function test(): \Test\Foo {
+        return new \Test\Foo;
     }
 }
    ----------- end diff -----------

Applied rules:
 * NormalizeNamespaceByPSR4ComposerAutoloadRector
```

**Comment by jtojnar** [comment]
> Feel free to create separate PR if you have different solution, thank you.

I would but it is not even clear to me how to create a test case that tests multiple interdependent files. I have only seen fixtures that check individual files using `doTestFileInfo`.

**Comment by samsonasik** [comment]
That's because it is base on assumption like I wrote at https://github.com/rectorphp/rector/issues/7232#issuecomment-1153064891 .  

We can't detect if the new class is autoloaded during migration :), so just guessing it is on same namespace.

I am closing it as I can't find a possible solution for now ;)

**Pull request closed without merging**
