### PR TITLE
[Php74] Skip parenthesized ternary if on ParenthesizeNestedTernaryRector

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://github.com/rectorphp/rector-src/pull/3974#issuecomment-1565060424

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
@TomasVotruba I am merging it ;)

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
