### PR TITLE
[Renaming] Do not rename class with same name inside different namespace on RenameClassRector

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #2452

### CODE REVIEW

**Comment by samsonasik** [comment]
@eigan I am not sure yet about it, feel free to provide a patch if you found a solution first.

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
