### PR TITLE
[Rectify] [Php81] Enable Rectify for finalize public class constant only

### PR DESCRIPTION
**Pull request by samsonasik**
split of https://github.com/rectorphp/rector-src/pull/1364 by enable FinalizePublicClassConstantRector only.

### CODE REVIEW

**Comment by samsonasik** [comment]
I set up to php 80 on level setlist with add service php 8.1 FinalizePublicClassConstantRector

**Comment by samsonasik** [comment]
I temporary skip ArraySpreadInsteadOfArrayMergeRector::class as it make change for string key array unpack on php 8.1 which unrelated with this PR.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
rebased.

**Comment by TomasVotruba** [comment]
Thank you, needs to rebase but feel free to merge 👍

**Comment by samsonasik** [comment]
`DowngradeFinalizePublicClassConstantRector` somehow seems not applied on downgrade on build scoped process, I will check.

**Pull request merged**
