### PR TITLE
[CI] Enable zend.assertions=1 on CI

### PR DESCRIPTION
**Pull request by samsonasik**
To show assert warning early when found, eg on direct `getArgs()` usage on PR:

- https://github.com/rectorphp/rector-src/pull/3822#discussion_r1193003535

### CODE REVIEW

**Comment by samsonasik** [comment]
See https://github.com/driftingly/rector-laravel/pull/65#issuecomment-1298631856 why zend.assertions setting is needed to ensure no warning when enabled.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you, could you add also a comment there? So we know why we have those enabled in the future :)

**Comment by samsonasik** [comment]
I [Added comment](https://github.com/rectorphp/rector-src/pull/3823/commits/8d6032bbf47bff043d7a19aeb50fd276d2506404) for example usage.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
