### PR TITLE
[CodingStyle] Handle crash on pass args on CallUserFuncToMethodCallRector

### LINKED ISSUE #8938: System error: "Call to a member function getAttribute() on null
Getting this error after upgrading `rector/rector (1.2.6 => 2.0.3)`:

```
                                                                                                                       
 [ERROR] Could not process "src/My/CoreBundle/Job/AbstractJob.php" file, due to:     
         "System error: "Call to a member function getAttribute() on null"                                              
                                                                                                                        
         Stack trace:                                                                                                   
         #0 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3697):                            
         PHPStan\Reflection\ParametersAcceptorSelector::selectFromArgs(Object(PHPStan\Analyser\MutatingScope), Array,   
         Array, NULL)                                                                                                   
         #1 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1493):                            
         PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\IntersectionType), 'args',            
         Object(PhpParser\Node\Expr\MethodCall))                                                                        
         #2 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1499):                            
         PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()                                                   
         #3 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(549):                             
         PHPStan\Analyser\MutatingScope->resolveType('$this->args($ar...', Object(PhpParser\Node\Expr\MethodCall))      
         #4 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1751):                        
         PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))                                
         #5 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(688):                         
         PHPStan\Analyser\NodeScopeResolver->findEarlyTerminatingExpr(Object(PhpParser\Node\Expr\MethodCall),           
         Object(PHPStan\Analyser\MutatingScope))                                                                        
         #6 phar://vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(390):                         
         PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression),                    
         Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))            
         #7 vendor/rector/rector/src/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(402):                  
         PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope),                
         Object(Closure))                                                                                               
         #8 vendor/rector/rector/src/NodeTypeResolver/PHPStan/Scope/PHPStanNodeScopeResolver.php(341):                  
         Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->nodeScopeResolverProcessNodes(Array,           
         Object(PHPStan\Analyser\MutatingScope), Object(Closure))                                                       
         #9 vendor/rector/rector/src/Application/ChangedNodeScopeRefresher.php(68):                                     
         Rector\NodeTypeResolver\PHPStan\Scope\PHPStanNodeScopeResolver->processNodes(Array, '/www/sites/my...',      
         Object(PHPStan\Analyser\MutatingScope))                                                                        
         #10 vendor/rector/rector/src/Rector/AbstractRector.php(278):                                                   
         Rector\Application\ChangedNodeScopeRefresher->refresh(Object(PhpParser\Node\Expr\MethodCall),                  
         '/www/sites/my...', Object(PHPStan\Analyser\MutatingScope))                                                  
         #11 vendor/rector/rector/src/Rector/AbstractRector.php(268):                                                   
         Rector\Rector\AbstractRector->refreshScopeNodes(Object(PhpParser\Node\Expr\MethodCall), '/www/sites/my...',  
         Object(PHPStan\Analyser\MutatingScope))                                                                        
         #12 vendor/rector/rector/src/Rector/AbstractRector.php(139):                                                   
         Rector\Rector\AbstractRector->postRefactorProcess(Object(PhpParser\Node\Expr\FuncCall),                        
         Object(PhpParser\Node\Expr\FuncCall), Object(PhpParser\Node\Expr\MethodCall), '/www/sites/my...')            
         #13 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(99):                          
         Rector\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Expr\FuncCall))                                  
         #14 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(121):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\Assign))                                      
         #15 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(192):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))                                  
         #16 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(90):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #17 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(192):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\If_))                                         
         #18 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(90):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #19 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(192):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))                                 
         #20 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(90):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #21 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(192):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))                                      
         #22 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(90):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #23 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(192):                         
         PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))                                  
         #24 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(71):                          
         PhpParser\NodeTraverser->traverseArray(Array)                                                                  
         #25 vendor/rector/rector/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(49):                              
         PhpParser\NodeTraverser->traverse(Array)                                                                       
         #26 vendor/rector/rector/src/Application/FileProcessor.php(95):                                                
         Rector\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)                                            
         #27 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(174):                                    
         Rector\Application\FileProcessor->processFile(Object(Rector\ValueObject\Application\File),                     
         Object(Rector\ValueObject\Configuration))                                                                      
         #28 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(151):                                    
         Rector\Application\ApplicationFileProcessor->processFile(Object(Rector\ValueObject\Application\File),          
         Object(Rector\ValueObject\Configuration))                                                                      
         #29 vendor/rector/rector/src/Application/ApplicationFileProcessor.php(128):                                    
         Rector\Application\ApplicationFileProcessor->processFiles(Array, Object(Rector\ValueObject\Configuration),     
         Object(Closure), Object(Closure))                                                                              
         #30 vendor/rector/rector/src/Console/Command/ProcessCommand.php(157):                                          
         Rector\Application\ApplicationFileProcessor->run(Object(Rector\ValueObject\Configuration),                     
         Object(RectorPrefix202412\Symfony\Component\Console\Input\ArgvInput))                                          
         #31 vendor/rector/rector/vendor/symfony/console/Command/Command.php(285):                                      
         Rector\Console\Command\ProcessCommand->execute(Object(RectorPrefix202412\Symfony\Component\Console\Input\ArgvI 
         nput), Object(RectorPrefix202412\Symfony\Component\Console\Output\ConsoleOutput))                              
         #32 vendor/rector/rector/vendor/symfony/console/Application.php(900):                                          
         RectorPrefix202412\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix202412\Symfony\Component\ 
         Console\Input\ArgvInput), Object(RectorPrefix202412\Symfony\Component\Console\Output\ConsoleOutput))           
         #33 vendor/rector/rector/vendor/symfony/console/Application.php(279):                                          
         RectorPrefix202412\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Console\Command\ProcessCo 
         mmand), Object(RectorPrefix202412\Symfony\Component\Console\Input\ArgvInput),                                  
         Object(RectorPrefix202412\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #34 vendor/rector/rector/src/Console/ConsoleApplication.php(53):                                               
         RectorPrefix202412\Symfony\Component\Console\Application->doRun(Object(RectorPrefix202412\Symfony\Component\Co 
         nsole\Input\ArgvInput), Object(RectorPrefix202412\Symfony\Component\Console\Output\ConsoleOutput))             
         #35 vendor/rector/rector/vendor/symfony/console/Application.php(162):                                          
         Rector\Console\ConsoleApplication->doRun(Object(RectorPrefix202412\Symfony\Component\Console\Input\ArgvInput), 
         Object(RectorPrefix202412\Symfony\Component\Console\Output\ConsoleOutput))                                     
         #36 vendor/rector/rector/bin/rector.php(130): RectorPrefix202412\Symfony\Component\Console\Application->run()  
         #37 vendor/rector/rector/bin/rector(5): require_once('/www/sites/my...')                                     
         #38 bin/rector(119): include('/www/sites/my...')                                                             
         #39 {main}". On line: 73                 
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8938

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @umpirsky

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by umpirsky** [comment]
Thanks, still no new release?

**Comment by samsonasik** [comment]
@umpirsky 2.0.4 just tagged https://github.com/rectorphp/rector/releases/tag/2.0.4

**Comment by umpirsky** [comment]
Thanks!

**Pull request merged**
