### PR TITLE
Compatibility with Enums

### LINKED ISSUE #7370: Cannot process backed Enums - "Not implemented"
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.10 |

Rector fails with `Could not process "[file]" file, due to: "System error: "Not implemented"` in the case of a backed enum.

I believe this is because the fork of better-reflection used by phpstan is out of date from upstream.

See https://github.com/ondrejmirtes/BetterReflection/blob/5.3.x/src/Reflection/Adapter/ReflectionClassConstant.php#L47 (forked) compared to https://github.com/Roave/BetterReflection/blob/5.8.x/src/Reflection/Adapter/ReflectionClassConstant.php#L41 (upstream.)

## Minimal PHP Code Causing Issue

https://getrector.org/demo/3872d465-cf35-420e-8907-128b13ac6969

## Expected Behaviour

Rector need not change this code but should be able to analyze and ignore it.

### PR DESCRIPTION
**Pull request by bradjones1**
Fixes https://github.com/rectorphp/rector/issues/7370

### CODE REVIEW

**Comment by TomasVotruba** [comment]
The tests are failing on this one.

**Comment by bradjones1** [comment]
> The tests are failing on this one.

Yes... I suspect this is a regression from using the new method that Ondrej suggested?

**Comment by TomasVotruba** [comment]
Could you update the test to pass again? :)

**Comment by samsonasik** [comment]
@bradjones1 I cherry-picked your commit at PR https://github.com/rectorphp/rector-src/pull/2815

**Pull request closed without merging**
