### PR TITLE
[Strict] Skip stripos on BooleanInIfConditionRuleFixerRector

### PR DESCRIPTION
**Pull request by samsonasik**
Closes https://github.com/rectorphp/rector-src/pull/963 Fixes https://github.com/rectorphp/rector/issues/6727 avoid fatal error

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by janedbal** [comment]
Wouldnt it be better to produce proper replacement instead of skipping that?

**Comment by samsonasik** [comment]
The result of 0 or false is based on assumption, while apply that cause invalid result to different use cases in existing fixtures, so I skip it as the safest to do.

**Comment by janedbal** [comment]
You can say that about any other fix, even replacing `if ($stringOrNull)` to `if ($stringOrNull !== null && $stringOrNull !== '')`. I thought you want to replace it with equivalent condition. 

The same issue is in https://github.com/rectorphp/rector-src/runs/3824568448

**Comment by samsonasik** [comment]
We want replacing code don't cause a fatal error, and if the desired change is cause a different fixtures failure, we can just skip that, and we can improve later, unless you have better fix, feel free to create a better PR or improvement next.

**Comment by samsonasik** [comment]
I am merging it ;)

**Comment by TomasVotruba** [comment]
@janedbal Reading this I think the reason for confusion was created in the fixture you provided in https://github.com/janedbal/rector-src/commit/2808d7818aa1f32cf83057fa71c73fae513c3e25

That was invalid in the first place, so I understand why @samsonasik decided to skip it.
Could you provide the correct one in new PR? Also with fix so we can merge it :+1:

**Comment by janedbal** [comment]
Yeah, that fixture did not contain equivalent condition (it contained the proper solution for specific function which should not be solved by rector), my bad.

**Pull request merged**
