### PR TITLE
[DeadCode] Skip used in Closure use on RemoveUnusedConstructorParamRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
final class SkipUsedInClosureUse
{
    public function __construct($hey, $man)
    {
        echo $hey . ' ';

        (function () use ($man) {
            echo $man;
        })();
    }
}
```

currently produce:

```diff
-    public function __construct($hey, $man)
+    public function __construct($hey)
```

which should be skipped as used in closure use.

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
Use case https://github.com/CuyZ/Valinor/blob/5a50baed864007e9c4f56ad46d7dc5d19fdcb8e2/src/Mapper/Object/Exception/CannotFindObjectBuilder.php#L30-L34

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
