### PR TITLE
[CodeQuality] Handle not identical return false then true on SimplifyIfReturnBoolRector

### PR DESCRIPTION
**Pull request by samsonasik**
Currently, the following code is skipped:

```php
        $docToken = new Token([]);
        if (strpos($docToken->getContent(), "\n") !== false) {
            return false;
        }

        return true;
```

which should be transformed to:

```diff
-        if (strpos($docToken->getContent(), "\n") !== false) {
-            return false;
-        }

-        return true;
+        return strpos($docToken->getContent(), "\n") === false;
```

### CODE REVIEW

**Comment by samsonasik** [comment]
implemented 🎉

**Comment by samsonasik** [comment]
It seems make invalid for the following condition:

```

        if ($firstChar !== $lastChar) {
            return false;
        }

        return in_array($firstChar, self::POSSIBLE_DELIMITERS, true);
```

I will check.

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
