### PR TITLE
[DeadCode] Ensure has stmts on RemoveDeadInstanceOfRector

### PR DESCRIPTION
**Pull request by samsonasik**
ref https://github.com/rectorphp/rector-src/pull/2251#discussion_r867330370

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba the PR https://github.com/rectorphp/rector-src/pull/2251 cause error when no stmts:

```
Time: 00:02.010, Memory: 100.50 MB

There was 1 error:

1) Rector\Tests\DeadCode\Rector\If_\RemoveDeadInstanceOfRector\RemoveDeadInstanceOfRectorTest::test with data set #14 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Rector\Core\Exception\ShouldNotHappenException: Array of nodes cannot be empty. Ensure "Rector\DeadCode\Rector\If_\RemoveDeadInstanceOfRector->refactor()" returns non-empty array for Nodes.

A) Return null for no change:

    return null;

B) Remove the Node:

    $this->removeNode($node);
    return $node;
```

This PR try to fix it.

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
@TomasVotruba it seems cause error on different rule:

```
➜  rector-src git:(ensure-has-stmts) bin/rector process rules/DeadCode/Rector/If_/RemoveDeadInstanceOfRector.php --dry-run
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
                                                                                                                        
 [ERROR] Could not process "rules/DeadCode/Rector/If_/RemoveDeadInstanceOfRector.php" file, due to:                     
         "System error: "Scope not available on "PhpParser\Node\Expr\Array_" node with parent node of                   
         "PhpParser\Node\Expr\BinaryOp\NotIdentical", but is required by a refactorWithScope() method of                
         "Rector\CodeQuality\Rector\Array_\CallableThisArrayToAnonymousFunctionRector" rule. Fix scope refresh on       
         changed nodes first"                                                                                           
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On 
         line: 36    
```

somehow the Scope is related

**Comment by samsonasik** [comment]
Resolved by compare `$if->stmts` against `[]` https://github.com/rectorphp/rector-src/pull/2252/commits/7dd50734611b83419010b8bc5d4c23231c3af4dc

**Comment by TomasVotruba** [comment]
👍

**Pull request merged**
