### PR TITLE
[Php81] Handle crash on Crypt() single arg on NullToStrictStringFuncCallArgRector

### LINKED ISSUE #7373: System error: "Rector\NodeTypeResolver\NodeTypeResolver::getType(): Argument #1 ($node) must be of type PhpParser\Node, null given
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.10             |

Hi there. First, thanks for the great work put in this project!

While trying to run rector on an old project, i encoutered the following error: 

> System error: "Rector\NodeTypeResolver\NodeTypeResolver::getType(): Argument #1 ($node) must be of type PhpParser\Node, null given

## Minimal PHP Code Causing Issue

You can reproduce the issue using the following link: https://getrector.org/demo/dabca986-73d1-4391-95eb-3650654bb966

## Expected Behaviour

I'm just starting with rector but this doesn't seem like the appropriate behaviour.

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
final class CryptOneArg
{
    public function run($subject)
    {
        crypt($subject);
    }
}
```

It currently crash:

```bash
There was 1 error:

1) Rector\Tests\Php81\Rector\FuncCall\NullToStrictStringFuncCallArgRector\NullToStrictStringFuncCallArgRectorTest::test with data set #10 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Undefined array key 1
```

Fixes https://github.com/rectorphp/rector/issues/7373

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @petitj . This PR make it skipped instead. 

It may need different PR for `crypt()` single arg transformation, but need different PR with seems require more research since we need to find the equal for transformation for pass 2nd arg that need to be generated salt.

**Comment by samsonasik** [comment]
Only convert 1st arg is possible actually...

**Comment by samsonasik** [comment]
Applied to only change 1st arg, 2nd arg will need different rule to apply it.

**Comment by samsonasik** [comment]
I added comment to the fixture for future reference:

```
/**
 * Crypt requires 2 args since php 5.6, when it only fill 1st arg, it will only change 1st arg
 *
 * Note: Filling 2nd arg will require different Rule to match the salt algorithm.
 */
```

https://github.com/rectorphp/rector-src/pull/2767/commits/50d58e4bddb67477a5de79f19afd0084502157f7

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
