### PR TITLE
[NodeTypeResolver] Using instanceof instead of is_string() check on Node visitors

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by staabm** [comment]
is_string() and instanceof are both cheap operations. 

I don't think these PRs are usefull as far as performance is concerned.

Performance PRs should mainly be driven by evidence, e.g. a finding in a profilers' measurement or similar

**Comment by samsonasik** [comment]
@staabm thank you, I still prefer instanceof check for this, as it show the precise exclusive type to check.

Using `is_string()` will get name, and args check which cause verify first callable too, so on process on various rules, instanceof is faster.

**Comment by staabm** [comment]
I am fine with the change itself, as long as it is not tagged as "performance improvemnt" :)

**Comment by samsonasik** [comment]
Ok, I removed `Performance` from PR title ;)

**Pull request merged**
