### PR TITLE
Do not run `ChangeReadOnlyPropertyWithDefaultValueToConstantRector` on properties with attributes

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by simPod** [comment]
Seems like I'm responsible for tests failure, investigating

**Comment by TomasVotruba** [comment]
It rather looks like bug between Symfony and Paratest with color string: https://github.com/rectorphp/rector-src/runs/4850475081?check_suite_focus=true#step:5:88

**Comment by simPod** [comment]
Yup, I noticed that but master is green 🤔 

I'm waiting for test suite to finish on my local machine.

**Comment by simPod** [comment]
There are ~3 test failures that are hidden in the output by the paratest bug you referenced.

**Comment by TomasVotruba** [comment]
> Yup, I noticed that but master is green thinking

That usually means new version (of paratest) was release since last PR was merged.

**Comment by TomasVotruba** [comment]
You can lock the paratest to last lower version in this PR to see if it affects result on CI.

**Comment by simPod** [comment]
Last release was in December :D never mind, I'll try to fix that one too.

**Comment by TomasVotruba** [comment]
That can be allowed by another dependency in another package. With composer you never know what you get :)

**Comment by simPod** [comment]
True true

**Comment by TomasVotruba** [comment]
Hm, the last passing PR (https://github.com/rectorphp/rector-src/pull/1669) had:

Locking brianium/paratest (v6.4.1)

This one has the same:

Installing brianium/paratest (v6.4.1): Extracting archive

**Comment by simPod** [comment]
IMO the bug is there for a while already but I've just found it.

I'm getting closer

image

**Comment by TomasVotruba** [comment]
I see...

When I check out this PR and run:

```bash
pu rules-tests/Privatization/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector/ChangeReadOnlyPropertyWithDefaultValueToConstantRectorTest.php
```

The test fails.

The paratest has some bug to interpret these changes correctly, that we discovered by accident.

**Comment by TomasVotruba** [comment]
Without your change, only the added fixture fails.

**Comment by simPod** [comment]
Yup

**Comment by TomasVotruba** [comment]
I think I know :)

**Comment by simPod** [comment]
My condition is wrong

**Comment by TomasVotruba** [comment]
It's the naming issue. In 2011, when the php-parser was born, nobody knew the native annotations will come to PHP and will be called attributes.So Nikita used "attributes" name for the metadata informations.

Now we have native `#[attributes]`, so to differentiate, they are called `attrGroup` in php-parser node.

I'd prefer to name first to "metadata" and second to "attributes", but in 2025 we might have native "metadata " feature in PHP and we're in the same position :) 

https://github.com/rectorphp/rector-src/pull/1695

**Comment by TomasVotruba** [comment]
Feel free to update this PR, I can merge it then. Thanks :+1:

**Comment by simPod** [comment]
Cool. Was not familiar with the API so thanks for pointer.

**Comment by TomasVotruba** [comment]
Thanks for the improvement :clap: 

I got burned this ~5 times already :laughing:

**Comment by simPod** [comment]
I tried to fix the paratest as well https://github.com/paratestphp/paratest/pull/650

**Comment by TomasVotruba** [comment]
@simPod That's amazing, thank you :+1:

**Pull request merged**
