### PR TITLE
[TypeDeclaration] Skip AddArrayReturnDocTypeRector on custom phpstan type

### LINKED ISSUE #7215: Custom phpstan types are ignored
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.4             |

When setting a custom phpstan type (e.g. setting a reusable array shape), this is ignored by rector.

## Minimal PHP Code Causing Issue

https://getrector.org/demo/87f196eb-c31b-468a-9e52-f16491dee9df

In the above demo, a few issues present themselves, however it is my intention that only 1 is addressed by this particular github issue.

1) The `@return InputSpecification` is removed from `InputInterface`, which does not occur for me when these are in separate files, so I would think that issue can be ignored.
2) The `@var non-empty-string` annotation is replaced by `@var string`, but there is an open (and possibly already fixed) issue for that here: https://github.com/rectorphp/rector/issues/7214.
3) The `@return InputSpecification` is removed from `UriInput`. This is the issue I wish to address here.

## Expected Behaviour

I'm certain this will be a complicated issue to address/fix, so I'm unsure what the expected behaviour should be, however personally I would expect that the custom type is read and if valid, no change would be made.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7215
ref https://phpstan.org/r/e00906e5-7f3f-4562-878b-8ffc17347653

### CODE REVIEW

**Comment by samsonasik** [comment]
@internalsystemerror the custom phpstan type seems detected as `NonExistingObjectType`, while checking against it make other fixture skipped if only rely on it:

```diff
class WithComment
{
    /**
     * @var int[]
     */
    private $values;

    /**
-     * @return somethign some integer values
+     * @return int[] some integer values
     */
    public function getValues()
    {
        return $this->values;
    }
}
```

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @internalsystemerror , I created `CustomPHPStanDetector` service for it https://github.com/rectorphp/rector-src/pull/2608/commits/7444e5b39d06e463fbf5912f253d100aab85d699

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Review by TomasVotruba — APPROVED** [review]

**Comment by internalsystemerror** [comment]
@samsonasik sorry I'm late to this one, thank you! very much!

**Pull request merged**
