### PR TITLE
[DeadCode] Remove RemoveCodeAfterReturnRector, already handled at RemoveUnreachableStatementRector

### PR DESCRIPTION
**Pull request by samsonasik**
there is already RemoveUnreachableStatementRector that already handle it, ref 

https://github.com/rectorphp/rector-src/blob/6063b59cde02c08a540ba18ab90d69ab8ba8acc7/rules-tests/DeadCode/Rector/Stmt/RemoveUnreachableStatementRector/Fixture/after_return.php.inc#L5-L27

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
I am merging it ;)

**Comment by TomasVotruba** [comment]
Yes :+1:

**Pull request merged**
