### PR TITLE
[PHPStanStaticTypeMapper] Handle Nullable Type on UnionType on UnionTypeMapper when possible

### PR DESCRIPTION
**Pull request by samsonasik**
Make `NullableType` correctly applied when possible.

On `TypedPropertyFromAssignsRector` use case, it correctly apply type use `?DateTime` instead of `DateTime|null` when types keys are not sorted (ensure sort after check types only 2, and one of them is null).

### CODE REVIEW

**Comment by samsonasik** [comment]
The test error on `AddFalseDefaultToBoolPropertyRector` is caused by overlapped merged PR:

- https://github.com/rectorphp/rector-src/pull/3171
- https://github.com/rectorphp/rector-src/pull/3172

```bash
There was 1 failure:

1) Rector\Tests\CodingStyle\Rector\Property\AddFalseDefaultToBoolPropertyRector\AddFalseDefaultToBoolPropertyRectorTest::test with data set #4 ('/Users/samsonasik/www/rector-...hp.inc')
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
     /**
      * @var bool
      */
-    private $property;
+    private $property = false;
 
     public function __construct(bool $property)
```

which the property is in `Trait_`, which actually, the `__construct()` is overrideable from class that consume it, see https://3v4l.org/hsB8k1#v7.0.28

**Comment by samsonasik** [comment]
I fixed the test for `__construct` in trait usage, as the `__construct` can be overridden by class that consume it, https://3v4l.org/MZFmT#v7.0.28

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Looks good, thank you :+1:

**Pull request merged**
