### PR TITLE
[MysqlToMySqli][DeadCode] Handle MYSQL_TO_MYSQLI and DEAD_CODE SetList usage

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6675

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I am merging it ;)

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by mirhunter** [comment]
Thanks, Sorry I did not get back to this in a timely fashion... got pulled in a diff direction at work...

**Pull request merged**
