### PR TITLE
[DowngradePhp70] Handle DowngradeScalarTypeDeclarationRector on Closure

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6451

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by leoloso** [comment]
@samsonasik The same issue also happens with union types and `mixed`: https://github.com/rectorphp/rector/issues/5989

Would you like to handle it also? Should I reopen that bug report?

**Comment by samsonasik** [comment]
@leoloso I created PR https://github.com/rectorphp/rector-src/pull/105 for that.

**Pull request merged**
