### PR TITLE
[Parallel] Fix --debug not working in parallel

### PR DESCRIPTION
**Pull request by samsonasik**
**Before**

```
bin/rector process src/Config/  --clear-cache --debug

                                                                                                                        
 [OK] Rector is done!                                                                                                                                                                                                                    
```

**After**

```
bin/rector process src/Config/  --clear-cache --debug

src/Config/Loader/ConfigureCallMergingLoaderFactory.php
[file] src/Config/Loader/ConfigureCallMergingLoaderFactory.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Config/Loader/ConfigureCallMergingLoaderFactory.php
[rule] Rector\CodingStyle\Rector\Stmt\NewlineAfterStatementRector

[file] src/Config/Loader/ConfigureCallMergingLoaderFactory.php
[rule] Rector\DeadCode\Rector\Node\RemoveNonExistingVarAnnotationRector

[file] src/Config/Loader/ConfigureCallMergingLoaderFactory.php
[rule] Rector\CodingStyle\Rector\Stmt\NewlineAfterStatementRector
```

ref https://github.com/rectorphp/rector/discussions/7164#discussioncomment-2744314

### CODE REVIEW

**Comment by samsonasik** [comment]
It seems make test error:

```


There were 2 errors:

1) Rector\Tests\Parallel\Command\WorkerCommandLineFactoryTest::test with data set #0 (array('process', array('src')), ''/usr/bin/php8.1' 'main_scrip...o-ansi')
Symfony\Component\Console\Exception\InvalidArgumentException: The "debug" option does not exist.
```

while registering to `AbstractProcessCommand` make it not displayed.

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I am merging it ;)

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
