### PR TITLE
[DowngradePhp80] Add DowngradeNamedArgumentRector

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6473

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba using `NodeRepository` to find `ClassMethod` in `Source` directory seems not works, only inside the current file.

**Comment by samsonasik** [comment]
@TomasVotruba it works with fallback to use `ReflectionProvider` when not found by `NodeRepository` 🎉

**Comment by samsonasik** [comment]
I tried running against `vendor` directory to update symfony's AutoconfigureTag class and it seems got error: 

```bash
~ bin/rector process vendor/symfony/dependency-injection/Attribute/AutoconfigureTag.php -c config/set/downgrade-php80.php --dry-run --debug

[parsing] vendor/symfony/dependency-injection/Attribute/AutoconfigureTag.php
PHP Fatal error:  Uncaught PHPStan\BetterReflection\Reflector\Exception\IdentifierNotFound: 
PHPStan\BetterReflection\Reflection\ReflectionClass 
 "Symfony\Component\DependencyInjection\Attribute\Autoconfigure" could not be found 
 in the located source in phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/Exception/IdentifierNotFound.php:24
```

**Comment by samsonasik** [comment]
It seems the error is because of Attribute, I remove the line:

```php
#[\Attribute(\Attribute::TARGET_CLASS | \Attribute::IS_REPEATABLE)]
```

in `vendor/symfony/dependency-injection/Attribute/AutoconfigureTag.php` and it seems running ok: 

Screen Shot 2021-06-01 at 14 04 54

**Comment by samsonasik** [comment]
I tried add `DowngradeAttributeToAnnotationRector` to `downgrade-php80` config: 

```php
    $services->set(DowngradeAttributeToAnnotationRector::class)
        ->call('configure', [[
            DowngradeAttributeToAnnotationRector::ATTRIBUTE_TO_ANNOTATION => ValueObjectInliner::inline([
                new DowngradeAttributeToAnnotation(
                    'Attribute',
                    'Attribute'
                ),
            ]),
        ]]);
        
    $services->set(DowngradeNamedArgumentRector::class);
```

before add `DowngradeNamedArgumentRector` but it seems not affected.

**Comment by samsonasik** [comment]
In https://github.com/rectorphp/rector-src/pull/133/commits/9cf3abbee022686c9aab27f8b634618c87a232f4 ,  I added test fixture for Downgrade `Attribute` and it seems changed from : 

```php
#[\Attribute(\Attribute::TARGET_CLASS | \Attribute::IS_REPEATABLE)]
```

to 

```php
/**
 * @Attribute
 */
```

while the value of attribute passed need to be improved, the `DowngradeAttributeToAnnotationRector` is applied for `Attribute` in the tests.

Next, in https://github.com/rectorphp/rector-src/pull/133/commits/c2253bd1edc3df4c3bda10159e429d4acb138b0e , I tried apply to `downgrade-php80` config set and it not applied when running : 

```bash
$  bin/rector process vendor/symfony/dependency-injection/Attribute/AutoconfigureTag.php -c config/set/downgrade-php80.php --dry-run --clear-cache 
 
  [OK] Rector is done! 
```

Tried running with debug mode, it got error:

```bash
$  bin/rector process vendor/symfony/dependency-injection/Attribute/AutoconfigureTag.php -c config/set/downgrade-php80.php --dry-run --clear-cache --debug

[parsing] vendor/symfony/dependency-injection/Attribute/AutoconfigureTag.php
PHP Fatal error:  Uncaught PHPStan\BetterReflection\Reflector\Exception\IdentifierNotFound: PHPStan\BetterReflection\Reflection\ReflectionClass "Symfony\Component\DependencyInjection\Attribute\Autoconfigure" could not be found in the located source in phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/ondrejmirtes/better-reflection/src/Reflector/Exception/IdentifierNotFound.php:24
```

**Comment by samsonasik** [comment]
Using 2 files call seems got different error to process parent class first, child class later:

```bash
bin/rector process \
        vendor/symfony/dependency-injection/Attribute/Autoconfigure.php \
        vendor/symfony/dependency-injection/Attribute/AutoconfigureTag.php \
        -c config/set/downgrade-php80.php --dry-run --clear-cache --debug

PHP Warning:  Undefined array key 99 in phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php on line 205
Warning: Undefined array key 99 in phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php on line 205
PHP Fatal error:  Uncaught TypeError: PhpParser\Internal\TokenStream::getIndentationBefore(): Return value must be of type int, null returned in phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php:205
Stack trace:
#0 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(551): PhpParser\Internal\TokenStream->getIndentationBefore(99)
#1 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(33): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Expr\ConstFetch))
#2 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(505): PhpParser\PrettyPrinter\Standard->pArg(Object(PhpParser\Node\Arg))
#3 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(527): PhpParser\PrettyPrinterAbstract->pFallback(Object(PhpParser\Node\Arg))
#4 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(892): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Arg), true)
#5 /Users/samsonasik/www/rector-src/src/PhpParser/Printer/BetterStandardPrinter.php(202): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 87, 0, 'Expr_StaticCall', 'args', NULL)
#6 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(574): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray(Array, Array, 87, 0, 'Expr_StaticCall', 'args', NULL)
#7 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(670): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Expr\StaticCall), true)
#8 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(892): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\Expression), true)
#9 /Users/samsonasik/www/rector-src/src/PhpParser/Printer/BetterStandardPrinter.php(202): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 59, 0, 'Stmt_ClassMetho...', 'stmts', NULL)
#10 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(574): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray(Array, Array, 59, 0, 'Stmt_ClassMetho...', 'stmts', NULL)
#11 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(293): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\ClassMethod))
#12 /Users/samsonasik/www/rector-src/src/PhpParser/Printer/BetterStandardPrinter.php(318): PhpParser\PrettyPrinterAbstract->pStmts(Array, true)
#13 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(965): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pStmts(Array)
#14 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(738): PhpParser\PrettyPrinter\Standard->pClassCommon(Object(PhpParser\Node\Stmt\Class_), ' AutoconfigureT...')
#15 /Users/samsonasik/www/rector-src/src/PhpParser/Printer/BetterStandardPrinter.php(353): PhpParser\PrettyPrinter\Standard->pStmt_Class(Object(PhpParser\Node\Stmt\Class_))
#16 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(505): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pStmt_Class(Object(PhpParser\Node\Stmt\Class_))
#17 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(577): PhpParser\PrettyPrinterAbstract->pFallback(Object(PhpParser\Node\Stmt\Class_))
#18 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(892): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\Class_), true)
#19 /Users/samsonasik/www/rector-src/src/PhpParser/Printer/BetterStandardPrinter.php(202): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 7, 0, 'Stmt_Namespace', 'stmts', NULL)
#20 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(574): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray(Array, Array, 7, 0, 'Stmt_Namespace', 'stmts', NULL)
#21 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(892): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\Namespace_), true)
#22 /Users/samsonasik/www/rector-src/src/PhpParser/Printer/BetterStandardPrinter.php(202): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 0, 0, 'File', 'stmts', NULL)
#23 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(492): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray(Array, Array, 0, 0, 'File', 'stmts', NULL)
#24 /Users/samsonasik/www/rector-src/src/PhpParser/Printer/BetterStandardPrinter.php(100): PhpParser\PrettyPrinterAbstract->printFormatPreserving(Array, Array, Array)
#25 /Users/samsonasik/www/rector-src/src/PhpParser/Printer/FormatPerservingPrinter.php(47): Rector\Core\PhpParser\Printer\BetterStandardPrinter->printFormatPreserving(Array, Array, Array)
#26 /Users/samsonasik/www/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(196): Rector\Core\PhpParser\Printer\FormatPerservingPrinter->printParsedStmstAndTokensToString(Object(Rector\Core\ValueObject\Application\File))
#27 /Users/samsonasik/www/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(103): Rector\Core\Application\FileProcessor\PhpFileProcessor->printFile(Object(Rector\Core\ValueObject\Application\File))
#28 /Users/samsonasik/www/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(165): Rector\Core\Application\FileProcessor\PhpFileProcessor->Rector\Core\Application\FileProcessor\{closure}(Object(Rector\Core\ValueObject\Application\File))
#29 /Users/samsonasik/www/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(104): Rector\Core\Application\FileProcessor\PhpFileProcessor->tryCatchWrapper(Object(Rector\Core\ValueObject\Application\File), Object(Closure), 'printing')
#30 /Users/samsonasik/www/rector-src/src/Application/ApplicationFileProcessor.php(52): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Array)
#31 /Users/samsonasik/www/rector-src/src/Application/ApplicationFileProcessor.php(35): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array)
#32 /Users/samsonasik/www/rector-src/src/Console/Command/ProcessCommand.php(135): Rector\Core\Application\ApplicationFileProcessor->run(Array)
#33 /Users/samsonasik/www/rector-src/vendor/symfony/console/Command/Command.php(288): Rector\Core\Console\Command\ProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(974): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(291): Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /Users/samsonasik/www/rector-src/src/Console/ConsoleApplication.php(79): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(167): Rector\Core\Console\ConsoleApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /Users/samsonasik/www/rector-src/bin/rector.php(60): Symfony\Component\Console\Application->run()
#39 /Users/samsonasik/www/rector-src/bin/rector(4): require_once('/Users/samsonas...')
#40 {main}
  thrown in phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php on line 205
Fatal error: Uncaught TypeError: PhpParser\Internal\TokenStream::getIndentationBefore(): Return value must be of type int, null returned in phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php:205
Stack trace:
#0 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(551): PhpParser\Internal\TokenStream->getIndentationBefore(99)
#1 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(33): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Expr\ConstFetch))
#2 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(505): PhpParser\PrettyPrinter\Standard->pArg(Object(PhpParser\Node\Arg))
#3 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(527): PhpParser\PrettyPrinterAbstract->pFallback(Object(PhpParser\Node\Arg))
#4 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(892): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Arg), true)
#5 /Users/samsonasik/www/rector-src/src/PhpParser/Printer/BetterStandardPrinter.php(202): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 87, 0, 'Expr_StaticCall', 'args', NULL)
#6 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(574): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray(Array, Array, 87, 0, 'Expr_StaticCall', 'args', NULL)
#7 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(670): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Expr\StaticCall), true)
#8 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(892): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\Expression), true)
#9 /Users/samsonasik/www/rector-src/src/PhpParser/Printer/BetterStandardPrinter.php(202): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 59, 0, 'Stmt_ClassMetho...', 'stmts', NULL)
#10 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(574): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray(Array, Array, 59, 0, 'Stmt_ClassMetho...', 'stmts', NULL)
#11 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(293): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\ClassMethod))
#12 /Users/samsonasik/www/rector-src/src/PhpParser/Printer/BetterStandardPrinter.php(318): PhpParser\PrettyPrinterAbstract->pStmts(Array, true)
#13 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(965): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pStmts(Array)
#14 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinter/Standard.php(738): PhpParser\PrettyPrinter\Standard->pClassCommon(Object(PhpParser\Node\Stmt\Class_), ' AutoconfigureT...')
#15 /Users/samsonasik/www/rector-src/src/PhpParser/Printer/BetterStandardPrinter.php(353): PhpParser\PrettyPrinter\Standard->pStmt_Class(Object(PhpParser\Node\Stmt\Class_))
#16 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(505): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pStmt_Class(Object(PhpParser\Node\Stmt\Class_))
#17 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(577): PhpParser\PrettyPrinterAbstract->pFallback(Object(PhpParser\Node\Stmt\Class_))
#18 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(892): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\Class_), true)
#19 /Users/samsonasik/www/rector-src/src/PhpParser/Printer/BetterStandardPrinter.php(202): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 7, 0, 'Stmt_Namespace', 'stmts', NULL)
#20 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(574): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray(Array, Array, 7, 0, 'Stmt_Namespace', 'stmts', NULL)
#21 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(892): PhpParser\PrettyPrinterAbstract->p(Object(PhpParser\Node\Stmt\Namespace_), true)
#22 /Users/samsonasik/www/rector-src/src/PhpParser/Printer/BetterStandardPrinter.php(202): PhpParser\PrettyPrinterAbstract->pArray(Array, Array, 0, 0, 'File', 'stmts', NULL)
#23 /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php(492): Rector\Core\PhpParser\Printer\BetterStandardPrinter->pArray(Array, Array, 0, 0, 'File', 'stmts', NULL)
#24 /Users/samsonasik/www/rector-src/src/PhpParser/Printer/BetterStandardPrinter.php(100): PhpParser\PrettyPrinterAbstract->printFormatPreserving(Array, Array, Array)
#25 /Users/samsonasik/www/rector-src/src/PhpParser/Printer/FormatPerservingPrinter.php(47): Rector\Core\PhpParser\Printer\BetterStandardPrinter->printFormatPreserving(Array, Array, Array)
#26 /Users/samsonasik/www/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(196): Rector\Core\PhpParser\Printer\FormatPerservingPrinter->printParsedStmstAndTokensToString(Object(Rector\Core\ValueObject\Application\File))
#27 /Users/samsonasik/www/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(103): Rector\Core\Application\FileProcessor\PhpFileProcessor->printFile(Object(Rector\Core\ValueObject\Application\File))
#28 /Users/samsonasik/www/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(165): Rector\Core\Application\FileProcessor\PhpFileProcessor->Rector\Core\Application\FileProcessor\{closure}(Object(Rector\Core\ValueObject\Application\File))
#29 /Users/samsonasik/www/rector-src/src/Application/FileProcessor/PhpFileProcessor.php(104): Rector\Core\Application\FileProcessor\PhpFileProcessor->tryCatchWrapper(Object(Rector\Core\ValueObject\Application\File), Object(Closure), 'printing')
#30 /Users/samsonasik/www/rector-src/src/Application/ApplicationFileProcessor.php(52): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Array)
#31 /Users/samsonasik/www/rector-src/src/Application/ApplicationFileProcessor.php(35): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array)
#32 /Users/samsonasik/www/rector-src/src/Console/Command/ProcessCommand.php(135): Rector\Core\Application\ApplicationFileProcessor->run(Array)
#33 /Users/samsonasik/www/rector-src/vendor/symfony/console/Command/Command.php(288): Rector\Core\Console\Command\ProcessCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(974): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(291): Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /Users/samsonasik/www/rector-src/src/Console/ConsoleApplication.php(79): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /Users/samsonasik/www/rector-src/vendor/symfony/console/Application.php(167): Rector\Core\Console\ConsoleApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /Users/samsonasik/www/rector-src/bin/rector.php(60): Symfony\Component\Console\Application->run()
#39 /Users/samsonasik/www/rector-src/bin/rector(4): require_once('/Users/samsonas...')
#40 {main}
  thrown in phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nikic/php-parser/lib/PhpParser/Internal/TokenStream.php on line 205
```

**Comment by samsonasik** [comment]
It seems need to one by one, `vendor/symfony/dependency-injection/Attribute/Autoconfigure.php` first, then `vendor/symfony/dependency-injection/Attribute/AutoconfigureTag.php` with early downgrade, I tried locally https://github.com/rectorphp/rector-src/pull/133/commits/f7290b7eb2741d19c4a8d0f68e2bc82f7112f17b and it seems both files applied.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review. 

This is for fix build scoped https://github.com/rectorphp/rector/issues/6473 . It still needs improvement for function call.

**Comment by TomasVotruba** [comment]
Awesome, thank you :+1:

**Comment by TomasVotruba** [comment]
This is the first PR that broke the build. Could you check it?
http://github.com/rectorphp/rector

**Comment by samsonasik** [comment]
@TomasVotruba previously, the error is on rector-src build scoped https://github.com/rectorphp/rector-src/runs/2710700928#step:11:101  that seems due to update to symfony 5.3 so the `rector/rector` repo was having 1 day off not sync. 

This rule is changing `MethodCall` and `StaticCall` arguments, not `ClassMethod` parameters signature.

I will check if it related with other downgrade rules.

**Comment by samsonasik** [comment]
@TomasVotruba it seems it caused by `DowngradeParameterTypeWideningRector` that remove nullable string from external source. I created a new PR for failing fixture for it at https://github.com/rectorphp/rector-src/pull/135

**Pull request merged**
