### PR TITLE
 [Transform] Add RectorConfigBuilderRector 

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
Implemented for `withRules()` usage, @TomasVotruba I think we can run it and implement one by one on rector-src code base, eg on test configs.

Ready to merge 👍

**Review by TomasVotruba — APPROVED** [review]
Looks good to me🙏
 lets merge and iterate next rule 👍

**Comment by sebastiaanluca** [comment]
Is there an example of how to use this to convert an old-style config file (because I think that's the intent of this rule?)? I've set it up like in the changed files, but it doesn't change my old rector.php file.

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Transform\Rector\FileWithoutNamespace\RectorConfigBuilderRector;

return RectorConfig::configure()->withRules([RectorConfigBuilderRector::class]);
```

Then just `vendor/bin/rector`. Even putting it in a directory and using `withPaths()` doesn't work.

**Comment by samsonasik** [comment]
@sebastiaanluca this is just the starter to convert `rule` to `withRules()`, the other methods still to be implemented, no worries, the old style is still works

**Comment by sebastiaanluca** [comment]
Ah ok, thanks for clarifying :)

Already changed to the new configuration builder format, because the old config file didn't work after upgrading the package itself. Gave an error that it couldn't find any directories and exited.

**Comment by samsonasik** [comment]
what old config you refer? If you use this config, it should still works as `RectorConfigBuilder` is syntax sugar:

```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\SetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([__DIR__.'/src']);

    $rectorConfig->sets([SetList::PHP_53]);
};

```

**Comment by sebastiaanluca** [comment]
Below is the config we had. Ran `composer require rector/rector=~0.19.6 --dev` and reran `vendor/bin/rector` which gave an error about it not finding any directories to scan (I don't have a screenshot of it or anything). Paths/directories didn't change, and didn't take time to properly debug it. Upgrading to the new format works fine, so not going to open an issue since it's resolved on our end.

While we're at it, thanks for writing and providing such a great tool ;) Saves us a lot of time upgrading old legacy code.

```php
<?php

declare(strict_types=1);

use Rector\CodeQuality\Rector\FuncCall\BoolvalToTypeCastRector;
use Rector\CodeQuality\Rector\FuncCall\FloatvalToTypeCastRector;
use Rector\CodeQuality\Rector\FuncCall\IntvalToTypeCastRector; 
use Rector\CodeQuality\Rector\FuncCall\StrvalToTypeCastRector;
use Rector\CodingStyle\Rector\Catch_\CatchExceptionNameMatchingTypeRector;
use Rector\CodingStyle\Rector\Closure\StaticClosureRector;
use Rector\CodingStyle\Rector\FuncCall\ArraySpreadInsteadOfArrayMergeRector;
use Rector\CodingStyle\Rector\FuncCall\CountArrayToEmptyArrayComparisonRector;
use Rector\CodingStyle\Rector\Stmt\NewlineAfterStatementRector;
use Rector\Config\RectorConfig;
use Rector\DeadCode\Rector\Foreach_\RemoveUnusedForeachKeyRector;
use Rector\DeadCode\Rector\If_\RemoveAlwaysTrueIfConditionRector;
use Rector\EarlyReturn\Rector\If_\ChangeAndIfToEarlyReturnRector;
use Rector\EarlyReturn\Rector\If_\ChangeOrIfContinueToMultiContinueRector;
use Rector\EarlyReturn\Rector\Return_\ReturnBinaryOrToEarlyReturnRector;
use Rector\Php74\Rector\Closure\ClosureToArrowFunctionRector;
use Rector\Php80\Rector\Class_\ClassPropertyAssignToConstructorPromotionRector;
use Rector\Php81\Rector\Array_\FirstClassCallableRector;
use Rector\Php81\Rector\Property\ReadOnlyPropertyRector;
use Rector\Php82\Rector\Class_\ReadOnlyClassRector;
use Rector\Php83\Rector\ClassMethod\AddOverrideAttributeToOverriddenMethodsRector;
use Rector\PHPUnit\Set\PHPUnitSetList;
use Rector\Privatization\Rector\Class_\FinalizeClassesWithoutChildrenRector;
use Rector\Set\ValueObject\LevelSetList;
use Rector\Set\ValueObject\SetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->parallel();

    $rectorConfig->paths([
        __DIR__.'/app',
        __DIR__.'/config',
        __DIR__.'/database',
        __DIR__.'/Domain',
        __DIR__.'/Interfaces',
        __DIR__.'/modules',
        __DIR__.'/operations',
        __DIR__.'/tests',
    ]);

    $rectorConfig->importNames(importDocBlockNames: false);
    $rectorConfig->importShortClasses();

    $rectorConfig->sets([
        SetList::CODING_STYLE,
        SetList::DEAD_CODE,
        SetList::EARLY_RETURN,
        SetList::PRIVATIZATION,
        SetList::STRICT_BOOLEANS,
        SetList::TYPE_DECLARATION,
        PHPUnitSetList::PHPUNIT_100,
        LevelSetList::UP_TO_PHP_70,
        LevelSetList::UP_TO_PHP_71,
        LevelSetList::UP_TO_PHP_72,
        LevelSetList::UP_TO_PHP_73,
        LevelSetList::UP_TO_PHP_74,
        LevelSetList::UP_TO_PHP_80,
        LevelSetList::UP_TO_PHP_81,
        LevelSetList::UP_TO_PHP_82,
        // LevelSetList::UP_TO_PHP_83,
    ]);

    $rectorConfig->rules([
        BoolvalToTypeCastRector::class,
        FloatvalToTypeCastRector::class,
        IntvalToTypeCastRector::class,
        StrvalToTypeCastRector::class,
        ReadOnlyClassRector::class,
        ReadOnlyPropertyRector::class,
    ]);

    $rectorConfig->skip([
        AddOverrideAttributeToOverriddenMethodsRector::class,
        ArraySpreadInsteadOfArrayMergeRector::class,
        CatchExceptionNameMatchingTypeRector::class,
        ChangeAndIfToEarlyReturnRector::class,
        ChangeOrIfContinueToMultiContinueRector::class,
        ClassPropertyAssignToConstructorPromotionRector::class,
        ClosureToArrowFunctionRector::class,
        CountArrayToEmptyArrayComparisonRector::class,
        FinalizeClassesWithoutChildrenRector::class,
        FirstClassCallableRector::class,
        NewlineAfterStatementRector::class,
        RemoveAlwaysTrueIfConditionRector::class,
        RemoveUnusedForeachKeyRector::class,
        ReturnBinaryOrToEarlyReturnRector::class,
    ]);

    $rectorConfig->skip([
        StaticClosureRector::class => [
            __DIR__.'/**/*Provider.php',
            __DIR__.'/database/factories',
        ],
    ]);
};
```

**Pull request merged**
