### PR TITLE
[Performance][AutoImport] Verify already use last name usage on long name on NameImportingPostRector

### PR DESCRIPTION
**Pull request by samsonasik**
It got **5 seconds faster** on rector-src itself:

**Before**

```
➜  rector-src git:(main) time bin/rector process --clear-cache
 2269/2269 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

                                                                                                                        
 [OK] Rector is done!                                                                                                   
                                                                                                                        
bin/rector process --clear-cache  243.43s user 13.41s system 700% cpu 36.678 total
```

**After**

```
➜  rector-src git:(performance-early-already-last-name-usage) time bin/rector process --clear-cache                 
 2269/2269 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

                                                                                                                        
 [OK] Rector is done!                                                                                                   
                                                                                                                        
bin/rector process --clear-cache  223.70s user 10.11s system 734% cpu 31.843 total
```

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it to have faster feedback to test ;)

**Comment by samsonasik** [comment]
Tested in CodeIgniter 4 project, **3 seconds faster**:

**Before**

```
➜  CodeIgniter4 git:(develop) time vendor/bin/rector process --clear-cache
 956/956 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

                                                                                                                        
 [OK] Rector is done!                                                                                                   
      
vendor/bin/rector process --clear-cache  317.14s user 8.81s system 713% cpu 45.694 total
```

**After**

```
➜  CodeIgniter4 git:(develop) time vendor/bin/rector process --clear-cache
 956/956 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

                                                                                                                        
 [OK] Rector is done!                                                                                                   
                                                                                                                        
vendor/bin/rector process --clear-cache  296.78s user 7.59s system 716% cpu 42.456 total
```

**Comment by samsonasik** [comment]
Tested in a project with **4869 files**, got **87 seconds** faster, a clear win 🎉 🎉 🎉 

**Before**

```
vendor/bin/rector process --clear-cache  1452.18s user 38.23s system 624% cpu 3:58.81 total
```

**After**

```
vendor/bin/rector process --clear-cache  1084.33s user 37.76s system 741% cpu 2:31.29 total
```

**Comment by TomasVotruba** [comment]
Crazy improvement in such a small place. Great work :clap:

**Pull request merged**
