### PR TITLE
Update rector_rules_overview.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by samsonasik** [comment]
the doc is generated by command:

```
composer docs 
```

The file that can be updated is the `TypedPropertyFromStrictGetterMethodReturnTypeRector::getRuleDefinition()` example before/after.

ref

https://github.com/rectorphp/rector-src/blob/73bf29c279191373755f08c2fdff45c013443c37/rules/TypeDeclaration/Rector/Property/TypedPropertyFromStrictGetterMethodReturnTypeRector.php#L58

**Comment by samsonasik** [comment]
Thank you @javaDeveloperKid

**Comment by ghost** [comment]
Thank you for the information. Updated TypedPropertyFromStrictGetterMethodReturnTypeRector.php. Should I revert change in .md file? If the docs is updated by composer command why is it commited to the repository? Just wonder how it works.

**Comment by samsonasik** [comment]
The doc generation is by weekly basis, see 

https://github.com/rectorphp/rector-src/blob/6cb95c1be3852a2d3295837320335104f0a24438/.github/workflows/weekly_pull_requests.yaml#L23

we can running manually when necessary. No need to revert .md file, it is ok.

**Pull request merged**
