### PR TITLE
[CodeQuality] Skip static::class on InlineConstructorDefaultToPropertyRector

### LINKED ISSUE #7415: Incorrect behavior of InlineConstructorDefaultToPropertyRector
# Bug Report

'static::' is not allowed in compile-time constants

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/0254bb0e-0e7e-4d4d-85ed-70b16a9dc751

```php
<?php

final class DemoFile
{
    private string $currentClassName;
    
    public function __construct()
    {
        $this->currentClassName = static::class;
    }
}
```

becomes

```php
<?php

final class DemoFile
{
    private string $currentClassName = static::class;
}
```

### Responsible rules

* `InlineConstructorDefaultToPropertyRector`

## Expected Behavior

Should ignore static:: and parent:: assignments.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7415

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @gregor-tb

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
👍

**Pull request merged**
