### PR TITLE
[deprecated] Remove deprecated properties from AbstractRector

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba `__get()` method in `AbstractRector` need to be removed as well as no longer working

**Comment by TomasVotruba** [comment]
It should stay for now, as we'll deprecate few more deps soon

**Comment by samsonasik** [comment]
It cause fatal error only show once, then exit, 

For multi properties, eg: foo and bar, it only show foo that error see https://3v4l.org/nsEZZ because fatal error show error and then exit.

**Comment by TomasVotruba** [comment]
I see. Could you fix it for now, but not remove the code? I'll use it soon for other dependencies

**Comment by samsonasik** [comment]
There are 2 options imo:

- Completely remove `__get()` as it no longer usefull
- rollback the deprecated notice functionality, until you think that it cleaned up and ready to remove the propreties and the `__get()`

**Comment by TomasVotruba** [comment]
Let's remove for now then

**Comment by samsonasik** [comment]
https://github.com/rectorphp/rector-src/pull/5245

**Pull request merged**
