### PR TITLE
[CodeQuality] Skip from non typed param on UseIdenticalOverEqualWithSameTypeRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
class SkipFromNonTypedParam
{
    /**
     * @param int $firstValue
     * @param int $secondValue
     */
    public function run($firstValue, $secondValue)
    {
         $isSame = $firstValue == $secondValue;
         $isDiffernt = $firstValue != $secondValue;
    }
}
```

should be skipped as value is from param that non-typed.

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Review by TomasVotruba — APPROVED** [review]

**Pull request merged**
