### PR TITLE
Disallow overwrite of rule with configuration by adding same rule again with different config

### PR DESCRIPTION
**Pull request by MartinMystikJonas**
As discussed in [#7288](https://github.com/rectorphp/rector/issues/7288)

### CODE REVIEW

**Comment by MartinMystikJonas** [comment]
@TomasVotruba I did not find a proper way to display this error as warning so I throw exception instead. If you preffer warning can you give me  a hint how it should be implemented?

**Comment by MartinMystikJonas** [comment]
It seems it already discovered bug in https://github.com/rectorphp/rector-symfony/blob/main/config/sets/symfony/symfony52.php

Rule https://github.com/rectorphp/rector-symfony/blob/d4e61a176e612818a15ebb832369dcde9641df76/config/sets/symfony/symfony52.php#L37

is overwritten by 

https://github.com/rectorphp/rector-symfony/blob/d4e61a176e612818a15ebb832369dcde9641df76/config/sets/symfony/symfony52.php#L60

**Comment by samsonasik** [comment]
Overwite configuration is expected, for example, you are trying to update codebase to php 7.4 with allow public property to be typed, you can use `LevelSetList::UP_TO_PHP_74` but override the `TypedPropertyRector` to set `INLINE_PUBLIC` to be true, like this:

```php

use Rector\Config\RectorConfig;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Set\ValueObject\LevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
        LevelSetList::UP_TO_PHP_74,
    ]);
    
    $rectorConfig->ruleWithConfiguration(
        TypedPropertyRector::class,
        [
            TypedPropertyRector::INLINE_PUBLIC => true,
        ]
    );
};
```

ref https://getrector.org/demo/77971aba-a2b2-41bd-8077-d9b5d18b88aa

Above, we only need to overwrite what we need.

By disallow overwrite, you will need to manually register all rules instead of just use the `SetList` or `LevelSetList` and override with what we need.

**Comment by samsonasik** [comment]
For RenameMethodRector, the new added config is added in the rule:

https://github.com/rectorphp/rector-src/blob/b1ae9a141523ee35af1f63aab39d945e8df03275/rules/Renaming/Rector/MethodCall/RenameMethodRector.php#L122

so it merged to existing config.

https://github.com/rectorphp/rector-src/blob/b1ae9a141523ee35af1f63aab39d945e8df03275/rules/Renaming/Collector/MethodCallRenameCollector.php#L21

**Comment by MartinMystikJonas** [comment]
@samsonasik I discussed this with @TomasVotruba in #7288 and he said that configs are merged only between different configs. But when same same configured rule is added in single config it is overwritted. This behaviour for RenameClassRector caused bug for us - first added class renames were ignored and only last one were used. 

So overwritte should be disabled inside single config where merging does not work. Or we can make merging work even when same rule is added multiple times in same config.

**Comment by MartinMystikJonas** [comment]
Check this examples.

1) When RenameClassRector is added twice no change is made because only last config is used:

https://getrector.org/demo/89a53ff2-ec12-4f8d-8ab6-36d6723b7806

2) When we keep only first version. Changes are applied:

https://getrector.org/demo/05cff601-7166-4b26-ba72-b12fd46ae44d

**Comment by samsonasik** [comment]
I think the configuration should be merged instead of disallow, so, if we have configuration:

```php
    $rectorConfig->ruleWithConfiguration(RenameClassRector::class, [
      'DemoFile' => 'RenamedDemoFile'
    ]);
    $rectorConfig->ruleWithConfiguration(RenameClassRector::class, [
      'NewDemoFile' => 'RenamedDemoFile'
    ]);
```

The result should be a merged config:

```php
    [
        'DemoFile' => 'RenamedDemoFile',
        'NewDemoFile' => 'RenamedDemoFile'
    ];
```

**Comment by MartinMystikJonas** [comment]
@samsonasik Agreed. But @TomasVotruba said this is just how used DI container works. So I drafted PR to prevent this error go unnoticed.

**Comment by samsonasik** [comment]
@MartinMystikJonas I created alternative PR for it at https://github.com/rectorphp/rector-src/pull/2655

**Comment by MartinMystikJonas** [comment]
@samsonasik great!

**Comment by TomasVotruba** [comment]
I think this should be kept as it is. It's a common Symfony convention, that even Symfony does not handle. One has to be aware of that, like in using of Symfony :)

In your case, just merge these together to single rule. The same way you'd register service once.

**Comment by MartinMystikJonas** [comment]
@TomasVotruba Well current situation can cause unnoticed and easy to made errors (like one just doscovered in rector-symfony). I think it would be better to at least notify user that this is not allowed. Config can be easily merged but it is quite easy to overlook it if you use bigger set of rules.

**Comment by samsonasik** [comment]
@MartinMystikJonas is disable overwrite will work with the following config? Manually configure existing config may needed to ensure that config exist as it uses allow empty config:

```php

use Rector\Config\RectorConfig;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Set\ValueObject\LevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->sets([
        LevelSetList::UP_TO_PHP_74,
    ]);
    
    $rectorConfig->ruleWithConfiguration(
        TypedPropertyRector::class,
        [
            TypedPropertyRector::INLINE_PUBLIC => true,
        ]
    );
};
```

**Comment by samsonasik** [comment]
`TypedPropertyRector` is use allow empty config, to test, manually configure in the setlist may needed to ensure 2nd config replaced when using SetList and override in rule call.

**Comment by MartinMystikJonas** [comment]
@samsonasik It should work because TypedPropertyRector is not added by calling ruleWithConfiguration on same RectorConfig object in this case. Not sure what exactly this config should do but it does not raise exception so it should behave exactly as before.

**Comment by samsonasik** [comment]
Another way to test it doesn't break the functionality is for example: import coding-style set list and override the 

https://github.com/rectorphp/rector-src/blob/b1ae9a141523ee35af1f63aab39d945e8df03275/config/set/coding-style.php#L37

after import.

**Comment by samsonasik** [comment]
For config both exists, something like this should keep working:

```php
<?php

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\SetList;

return static function (RectorConfig $rectorConfig): void {
    
    $rectorConfig->sets([
        SetList::CODING_STYLE
    ]);
    
    $rectorConfig
        ->ruleWithConfiguration(Rector\Transform\Rector\FuncCall\FuncCallToConstFetchRector::class, [
            'php_sapi_name' => 'PHP_SAPI',
            'pi' => 'M_PI',
        ]);

    };

**Comment by samsonasik** [comment]
I re-create PR https://github.com/rectorphp/rector-src/pull/2656 for merge config.

**Comment by MartinMystikJonas** [comment]
@TomasVotruba Should I add test coverage for reconfiguring tests from sets (as @samsonasik suggested)? Or do you really want this kind of usage error to remain silent and keep this PR closed?

**Pull request closed without merging**
