### PR TITLE
Use better composer-unused

### PR DESCRIPTION
**Pull request by TomasVotruba**
See https://github.com/composer-unused/composer-unused by @icanhazstring :sunglasses:

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba it seems cause github report warning:

```
Check warning on line 24 in composer.json
GitHub Actions / Detect unused dependencies

rector/extension-installer is invalid
```

https://github.com/rectorphp/rector-src/pull/2972/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34

**Comment by TomasVotruba** [comment]
Yeah, that's annoying as false positive. 
I use the tool first time... how can we turn it off?

**Comment by samsonasik** [comment]
it possibly reported by `GithubFormatter`

https://github.com/composer-unused/composer-unused/blob/d1d0c6707215767ca423c44b6ea954025c0feab3/src/OutputFormatter/GithubFormatter.php#L12

/cc @icanhazstring any way to not show github report when ignored by PatternFilter?

**Comment by icanhazstring** [comment]
> it possibly reported by `GithubFormatter`
> 
> https://github.com/composer-unused/composer-unused/blob/d1d0c6707215767ca423c44b6ea954025c0feab3/src/OutputFormatter/GithubFormatter.php#L12
> 
> /cc @icanhazstring any way to not show github report when ignored by PatternFilter?

Can you give an example? Or just create a ticket and we can check 🙂

**Comment by samsonasik** [comment]
@icanhazstring Yes, I created issue for it https://github.com/composer-unused/composer-unused/issues/397

**Pull request merged**
