### PR TITLE
[Cache] Avoid to remove non empty cache directories on cache clearing

### PR DESCRIPTION
**Pull request by bertrandjamin**
Those deletions could remove already existant cached files notably the "configuration_hash" file

Fixes https://github.com/rectorphp/rector/issues/6731

### CODE REVIEW

**Comment by bertrandjamin** [comment]
@TomasVotruba do I need to add anything before it can be merged ?
Do you have any visibility on the delay before this can be released ? 

Thanks !

**Comment by TomasVotruba** [comment]
Hi, thanks. I was waiting for CI to run and after I clicked I never got notification from @github again (most hated feature :D) 

It looks good, lets ship it :+1:

**Comment by samsonasik** [comment]
@bertrandjamin this seems cause error when run rector-src from parent dir, eg:

```bash
../rector-src/bin/rector process some-lib/src                                     

In FileCacheStorage.php line 99:
                                                                                                                                                                    
  FilesystemIterator::__construct(/var/folders/dv/m3gvpzh94t59l94qz3w2dgfr0000gn/T/rector_cached_files/a4/20): Failed to open directory: No such file or directory  
                                                                                                                                                                    

process [-n|--dry-run] [-a|--autoload-file AUTOLOAD-FILE] [-o|--output-format [OUTPUT-FORMAT]] [--no-progress-bar] [--no-diffs] [--clear-cache] [--] [<source>...]
``` 

could you verify ? Thank you.

**Comment by samsonasik** [comment]
directory not exists seems need to be handled:

Screen Shot 2021-10-14 at 21 11 11

**Comment by TomasVotruba** [comment]
@samsonasik Thanks! Let's revert for now - https://github.com/rectorphp/rector-src/pull/1000. Can we include this in CI somehow?

@bertrandjamin Could you prepare PR with fix?

**Comment by samsonasik** [comment]
@TomasVotruba that seems reproducible by run inside the repo itself, eg, run against `src/Enum`:

```bash
➜  rector-src git:(main) bin/rector process src/Enum --clear-cache --dry-run

In FileCacheStorage.php line 99:
                                                                                                                                                                    
  FilesystemIterator::__construct(/var/folders/dv/m3gvpzh94t59l94qz3w2dgfr0000gn/T/rector_cached_files/1a/41): Failed to open directory: No such file or directory  
                                                                                                                                                                    

process [-n|--dry-run] [-a|--autoload-file AUTOLOAD-FILE] [-o|--output-format [OUTPUT-FORMAT]] [--no-progress-bar] [--no-diffs] [--clear-cache] [--] [<source>...]
```

the CI somehow still running

**Comment by bertrandjamin** [comment]
My bad... I will take a look on this as soon as I have time (hopefully tomorrow). 

Thanks for reporting @samsonasik

**Comment by TomasVotruba** [comment]
@samsonasik Ideally in GitHub Actoin workflow, so we have it covered :+1: Could you add it?

@bertrandjamin No worries, it happens. Thanks for taking care :+1:

**Comment by samsonasik** [comment]
@TomasVotruba the currect rectify CI command I tried run in my local dev already happen show error by run: 

`bin/rector process rules --ansi --no-progress-bar`

Screen Shot 2021-10-14 at 21 52 00

which run in CI, but somehow it run ok on CI.

**Pull request merged**
