### PR TITLE
[CodeQuality][EarlyReturn] Handle crash Replace Stmt to Expr on FlipTypeControlToUseExclusiveTypeRector+FlipTypeControlToUseExclusiveTypeRector+ReturnBinaryOrToEarlyReturnRector

### LINKED ISSUE #8044: `System error: "Trying to replace statement (Stmt_Return) with expression (Expr_BooleanNot). Are you missing a Stmt_Expression wrapper?`
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.17.3            |

Not sure which rule it is exactly. But the following snippet causes an internal PHPParser error.

```php
<?php

namespace App;

use Illuminate\Support\Facades\Auth;
use User;

class Foo
{
    public function getUser(?User $user = null): ?User
    {
        return $user ?? (Auth::check() ? Auth::user() : null);
    }


    public function doFoo(
        ?User $user = null
    ): bool {
        $user = $this->getUser($user);

        if (!$user) {
            return false;
        }

        return $user->isFoo() || $user->isBar();
    }

}
```

Error: `System error: "Trying to replace statement (Stmt_Return) with expression (Expr_BooleanNot). Are you missing a Stmt_Expression wrapper?`

## Minimal PHP Code Causing Issue

https://getrector.com/demo/44c449cb-8ecf-420a-b7ef-00018292a101

## Expected Behaviour

No errors.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8044

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the test fixture :+1: 

Seems the fix commit is missing. Or still WIP? :)

**Comment by samsonasik** [comment]
I am still looking for the solution 👍

**Comment by TomasVotruba** [comment]
I can check if you want. It will be some rule returning expr instead of stmt. Not directly in the refactor() method, but in one of nested nodes IMO.

**Comment by samsonasik** [comment]
That seems due to refactor return array of nodes, which inside the nodes doesn't have origNode yet/overlapped on multi rules

**Comment by samsonasik** [comment]
It seems can be tweaked on `RectifiedAnalyzer`, wait a minute ...

**Comment by TomasVotruba** [comment]
> That seems due to refactor return array of nodes, which inside the nodes doesn't have origNode yet/overlapped on multi rules

That should be ok, untill all those arrays contain only stmts.

**Comment by samsonasik** [comment]
Fixed with verify on re-print has empty origNode, that's means the node is on nested Expr https://github.com/rectorphp/rector-src/pull/4474/commits/d0e6a732d6f18c5db39bbb19222728985012f86d

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba let's give it a try to have faster feedback to test ;)

**Comment by samsonasik** [comment]
It seems cause error on downgrade:

```


------------------------------------------------------------
Parse error: rector-prefixed-downgraded/packages/BetterPhpDocParser/PhpDocParser/BetterPhpDocParser.php:55
    53|     public function __construct(TypeParser $typeParser, ConstExprParser $constExprParser, CurrentNodeProvider $currentNodeProvider, TokenIteratorFactory $tokenIteratorFactory, iterable $phpDocNodeDecorators, PrivatesAccessor $privatesAccessor = null)
    54|     {
  > 55|         $privatesAccessor ??= new PrivatesAccessor();
    56|         $this->currentNodeProvider = $currentNodeProvider;
    57|         $this->tokenIteratorFactory = $tokenIteratorFactory;
Unexpected '=' in rector-prefixed-downgraded/packages/BetterPhpDocParser/PhpDocParser/BetterPhpDocParser.php on line 55
------------------------------------------------------------
Parse error: rector-prefixed-downgraded/vendor/rector/rector-doctrine/src/NodeManipulator/ColumnPropertyTypeResolver.php:59
    57|     public function __construct(PhpDocInfoFactory $phpDocInfoFactory, TypeFactory $typeFactory, AttributeFinder $attributeFinder, array $doctrineTypeToScalarType = null)
    58|     {
  > 59|         $doctrineTypeToScalarType ??= [
    60|             'tinyint' => new BooleanType(),
    61|             'boolean' => new BooleanType(),
Unexpected '=' in rector-prefixed-downgraded/vendor/rector/rector-doctrine/src/NodeManipulator/ColumnPropertyTypeResolver.php on line 59
```

https://github.com/rectorphp/rector-src/actions/runs/5518361429/jobs/10062204998#step:15:23

I will check 👍

**Comment by canvural** [comment]
Thank you @samsonasik 🎉 

BTW I also get a similar error `Trying to replace statement (Stmt_If) with expression (Expr_Instanceof). Are you missing a Stmt_Expression wrapper?`

But I could not reproduce this one in the playground. Just writing it here in case it rings a bell for you. Or maybe it'll also be fixed with this PR because both are `Stmt`

**Comment by samsonasik** [comment]
@canvural yes, that should be resolved in core instead of individual rule to avoid similar issue happen again.

I am looking into it, as current solution cause error on downgrade

**Comment by TomasVotruba** [comment]
I'll tag a new version :+1:

**Comment by samsonasik** [comment]
@TomasVotruba it not yet resolved, so new tag won't be applied to downgrade as downgrade build error

**Comment by TomasVotruba** [comment]
Ah, I see :)

**Pull request merged**
