### PR TITLE
Add failing test fixture for RenamePropertyRector

### PR DESCRIPTION
**Pull request by zingimmick**
Ref: https://github.com/rectorphp/rector/issues/6678

### CODE REVIEW

**Comment by samsonasik** [comment]
@zingimmick I cherry-picked your commit at PR https://github.com/rectorphp/rector-src/pull/821

**Comment by zingimmick** [comment]
> @zingimmick I cherry-picked your commit at PR #821

It seems a bit strange, if the property fetch is in another class, the test still fails.
```php
class ClassWithOldProperty
{
    public $oldProperty;
}

class OtherClass
{
    public ClassWithOldProperty $classWithOldProperty;

    public function run()
    {
        return $this->classWithOldProperty->oldProperty;
    }
}
```

**Comment by samsonasik** [comment]
@zingimmick could you add failing test case and or fix for it? Thank you.

**Comment by zingimmick** [comment]
> @zingimmick could you add failing test case and or fix for it? Thank you.

@samsonasik Failing test case added at PR #824

**Pull request closed without merging**
