### PR TITLE
Add failing test fixture for AddArrayParamDocTypeRector

### PR DESCRIPTION
**Pull request by Androbin**
# Failing Test for AddArrayParamDocTypeRector

Based on https://getrector.org/demo/1ebe342e-0c71-646c-a841-fb613cac70c0

### CODE REVIEW

**Comment by Androbin** [comment]
See https://github.com/rectorphp/rector/issues/6567

**Comment by samsonasik** [comment]
@Androbin I cherry-picked your commit at PR https://github.com/rectorphp/rector-src/pull/455

**Comment by samsonasik** [comment]
After re-check, actually, the fixture is invalid, it will got error on execution, see https://3v4l.org/GDB59 . 

The correct fixture must be has parameter handle see https://github.com/rectorphp/rector-src/commit/61725e41395f8ae02cf0be91923f504f2bdad39b

**Comment by samsonasik** [comment]
I updated fixture with param handling https://github.com/rectorphp/rector-src/pull/455/commits/61725e41395f8ae02cf0be91923f504f2bdad39b

**Pull request closed without merging**
