### PR TITLE
[WIP] Symplify removing unreachable node

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by samsonasik** [comment]
FYI, this may broke downgrade build, please run:

```
export PHP72_BIN_PATH=/path/to/php7.2/php && sh ./full_build.sh
```

first before merging, there are parts after unreachable code that the syntax need to be downgraded that need scope to apply change, we no longer have "parent" node so we don't know what code tied to, so filling scope for them is needed to avoid syntax error caused by skipping of no scope.

**Comment by TomasVotruba** [comment]
@samsonasik I'll check it, thanks :+1:

**Comment by samsonasik** [comment]
I am thinking that it should be kept, PHPStan is stopping analyzing code when reach Unreachable (which may on purpose, eg; extension not exists, or trait or if else variable scopped on do while), then after that, the node never checkable, and on in class/trait scope, that can't have access to the scope anymore. 

That will cause a bug later if after or inside unreachable stmt never filled.

**Comment by samsonasik** [comment]
Please don't remove this, after then after UnreachableStmt no longer has Scope, the downgrade will error, then if Scope need to be pulled, it error.

**Comment by TomasVotruba** [comment]
Looks like so. I'm exploring way to make it simpler. Ideally PHPStan should provide scope even on unreachable nodes.

/cc @ondrejmirtes

**Comment by samsonasik** [comment]
@TomasVotruba on PHPStan, the UnreachableStmtNode is stopped analyzed after found, that means after that Stmt, and after that again, no longer has Scope, and it can't be validated anymore, that will cause random error in the future, see


https://github.com/phpstan/phpstan-src/blob/5813d9239d84165c8537dc07a96d48293624d7fd/src/Analyser/NodeScopeResolver.php#L273-L274

**Comment by TomasVotruba** [comment]
I'm aware. Just looking into options to make Rector rules work without scope if possible.

**Comment by TomasVotruba** [comment]
In some rules, it might be worth it to downgrade with polyfill recommendation:
https://github.com/symfony/polyfill-php81/blob/1.x/composer.json

They provide better support and avoid copy-pasting code.

**Comment by samsonasik** [comment]
The problem is we provide AbstractScopeAwareRector, when no scope, it will make error at "after" UnreachableStmt as already stopped in previous Stmt, except, PHPStan don't stop loop on found UnreachableStmt node.

**Comment by samsonasik** [comment]
Moving to AbstractRector is not solution, as if the unreachableSmt handling removed, the feature will no longer working after UnreachableSmt node

**Comment by TomasVotruba** [comment]
That's best practice in general, as many rule have been crashing because of lack of scope. We should avoid scope if possible, but only if possible :) similar to parent node, that is also not required.

This is probing PR and has discovered 3 cases to improve, good enough. Let's close now :+1:

**Pull request closed without merging**
