### PR TITLE
[CodingStyle] Handle Interface suffix on CatchExceptionNameMatchingTypeRector

### LINKED ISSUE #7046: Incorrect behavior of CatchExceptionNameMatchingTypeRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.12.17      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/cdac23de-108b-431c-b06f-74b194c7c42f

```php
<?php

final class DemoFile
{
    public function run()
    {
        try {
            $a = 1;
        } catch (ExceptionInterface $exception) {
        }
    }
}
```

### Responsible rules

* `CatchExceptionNameMatchingTypeRector`

## Expected Behavior

I would like to have the option to omit the Interface suffix (that's how Phpstorm behaves when suggesting an automatic variable name).

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7046

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉  /cc @freiondrej-lmc

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by freiondrej-lmc** [comment]
@samsonasik wow guys, you really rock! 🚀 🐎 thanks

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
