### PR TITLE
[Php82] Add Utf8DecodeEncodeToMbConvertEncodingRector

### LINKED ISSUE #7658: PHP 8.2 Add utf8_decode -> mb_convert_encoding
# Feature Request

New rule seems needed to update deprecated uf8_decode to mb_convert_encoding

## Diff 

```diff
-$diff = utf8_decode($value);
+$diff = mb_convert_encoding($value, 'ISO-8859-1');
```

Ref 

- https://github.com/kahlan/kahlan/issues/406
- https://github.com/kahlan/kahlan/pull/407
- https://stitcher.io/blog/new-in-php-82#utf8_encode()-and-utf8_decode()-deprecations-rfc

Demo compare equal result : https://3v4l.org/ZuZl5

### PR DESCRIPTION
**Pull request by samsonasik**
This is to fix https://github.com/rectorphp/rector/issues/7658

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
It seems ut8_encode -> mb_convert_encoding can be applied as well with pass 2 and 3 arguments https://3v4l.org/WkmFR

**Comment by samsonasik** [comment]
implemented 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Review by TomasVotruba — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thanks

**Pull request merged**
