### PR TITLE
Added failing test for symfony validator

### PR DESCRIPTION
**Pull request by TNAJanssen**
Closes https://github.com/rectorphp/rector/issues/6555

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Possible fixed already https://github.com/rectorphp/rector-src/pull/361/files

**Comment by TNAJanssen** [comment]
@TomasVotruba appears to be so, is there an ETA for releasing that fix?

**Comment by TomasVotruba** [comment]
It would be out already, but release is stuck last 3 days because of https://github.com/rectorphp/rector/issues/6543

We're refactoring globally parsed services to more cleaner static reflection in few code smelling parts and it's a bit more challenging than we expected :)

**Comment by TomasVotruba** [comment]
Merging, so we have this covered for the future :+1: Thank you!

**Pull request merged**
