### PR TITLE
Handle nested arrays in CurlyListNode

### PR DESCRIPTION
**Pull request by lukasluecke**
**Source**
```php
/**
 * @ApiResource(
 *      mercure=true,
 *      graphql={
 *         "item_query",
 *         "update",
 *         "transition"={
 *             "denormalization_context"={"groups"={"transition"}},
 *             "security"="is_granted('transition',object)",
 *             "mutation"=VmTransitionResolver::class,
 *             "deserialize"=false,
 *             "args"={"id"={"type"="ID!"}, "state"={"type"="String!"}}
 *         }
 *     }
 * )
 */
```

**Result**

- Incorrect  _(before this change)_
  ```php
  /**
   * @ApiResource(mercure=true, graphql={"item_query", "update", "transition"=Array, "is_granted('transition',object)", VmTransitionResolver::class, false, Array})
   */
  ```

- Correct  _(after this change)_
  ```php
  /**
   * @ApiResource(mercure=true, graphql={"item_query", "update", "transition"={"denormalization_context"={"groups"={"transition"}}, "security"="is_granted('transition',object)", "mutation"=VmTransitionResolver::class, "deserialize"=false, "args"={"id"={"type"="ID!"}, "state"={"type"="String!"}}}})
   */
  ```

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, thanks for the fix!
Could you check the failing CI?

**Comment by lukasluecke** [comment]
> Hi, thanks for the fix!
> Could you check the failing CI?

@TomasVotruba You're welcome. I fixed the PHPStan issue, but I'm not sure what's wrong with the nette-to-symfony test - don't really understand what it's even doing, or how it's related to my change here 🙈

**Comment by TomasVotruba** [comment]
> but I'm not sure what's wrong with the nette-to-symfony test - don't really understand what it's even doing, or how it's related to my change here see_no_evil

That's my fault, I broke test suffix pasing from config :face_with_head_bandage:   Don't worry about it, I'll fix it :+1:

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Pull request merged**
