### PR TITLE
[Php74] Add ternary for if return early on ClosureToArrowFunctionRector

### PR DESCRIPTION
**Pull request by samsonasik**
The following code:

```php
        return array_filter($meetups, function (?Meetup $meetup) {
            if (is_object($meetup)) {
                return true;
            }

            return false;
        });
```

can be transformed to:

```php
        return array_filter($meetups, fn(?Meetup $meetup) => is_object($meetup) ? true : false);
```

### CODE REVIEW

**Comment by samsonasik** [comment]
implemented 🎉

**Comment by TomasVotruba** [comment]
In case of one condition this make sense, but constructions like `&& x && y &&` are not readable.

**Comment by samsonasik** [comment]
ok 👍 , I am closing it then ;)

**Comment by samsonasik** [comment]
multiple condition seems caused by other rule.

**Comment by samsonasik** [comment]
I re-create PR for it https://github.com/rectorphp/rector-src/pull/2271

**Pull request closed without merging**
