### PR TITLE
[PHP 7.4] Remove TypedPropertyFromAssignsRector from default set, as could break types

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by samsonasik** [comment]
I think this is the safest type declaration to include in php74 config set, which one that cause BC break? It also has INLINE_PUBLIC configuration that default to false.

**Comment by TomasVotruba** [comment]
It did many docblock changes in one project. As we're trying to avoid docblocks since 0.15, this should be replaced by type declaration rules.

I'll check for exact examples.

**Comment by samsonasik** [comment]
No, it doesn't. I removed the docblock change in previous PR.

**Comment by samsonasik** [comment]
See this docblock change PR removal:

- https://github.com/rectorphp/rector-src/pull/3163

**Comment by samsonasik** [comment]
If you use latest dev-main, it won't change/remove the docblock, see the PR:

- https://github.com/rectorphp/rector-src/pull/3163

You can try latest dev-main:

```
composer update rector/rector:dev-main
```

**Comment by TomasVotruba** [comment]
I see. I've just released the 0.15.1 version, so that should help :+1: 

Thanks for checks

**Comment by samsonasik** [comment]
I am closing it then ;)

**Comment by TomasVotruba** [comment]
Yes :)

**Pull request closed without merging**
