### PR TITLE
[Core] Avoid hang on file has template-extends

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes rectorphp/rector#6758

### CODE REVIEW

**Comment by samsonasik** [comment]
@boesing this should tweak the PHPStan internal issue on https://github.com/rectorphp/rector/issues/6758 , I tried locally:

Screen Shot 2021-10-21 at 18 29 23

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review. 

I can't verify with unit tests, but it works on handling hang on `@template-extends` to use old stmts when there is a `@template-extends` usage.

Ref for PHPStan issue https://github.com/rectorphp/rector/issues/6758

**Comment by boesing** [comment]
Awesome, thanks for digging deeper into that rabbit hole! Really appreciated. 🙏🏼

**Comment by samsonasik** [comment]
I am merging it ;)

**Pull request merged**
