### PR TITLE
[Php81] Handle crash backed Enum not implemented on FirstClassCallableRector

### LINKED ISSUE #7370: Cannot process backed Enums - "Not implemented"
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | 0.13.10 |

Rector fails with `Could not process "[file]" file, due to: "System error: "Not implemented"` in the case of a backed enum.

I believe this is because the fork of better-reflection used by phpstan is out of date from upstream.

See https://github.com/ondrejmirtes/BetterReflection/blob/5.3.x/src/Reflection/Adapter/ReflectionClassConstant.php#L47 (forked) compared to https://github.com/Roave/BetterReflection/blob/5.8.x/src/Reflection/Adapter/ReflectionClassConstant.php#L41 (upstream.)

## Minimal PHP Code Causing Issue

https://getrector.org/demo/3872d465-cf35-420e-8907-128b13ac6969

## Expected Behaviour

Rector need not change this code but should be able to analyze and ignore it.

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #2787 Fixes https://github.com/rectorphp/rector/issues/7370

### CODE REVIEW

**Comment by samsonasik** [comment]
Ref https://getrector.org/demo/817966a1-373e-469f-a75c-1a9b2edfc33a

**Comment by samsonasik** [comment]
it seems still cause error in other test:

```diff

There was 1 failure:

1) Rector\Tests\TypeDeclaration\Rector\ClassMethod\ParamAnnotationIncorrectNullableRector\ParamAnnotationIncorrectNullableRectorTest::test with data set #10 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules-tests/TypeDeclaration/Rector/ClassMethod/ParamAnnotationIncorrectNullableRector/Fixture/param-annotation-missing-null-with-non-null-default-value-from-const.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
     private const FLAG_DEFAULT_VALUE = null;
 
     /**
-     * @param bool|null $flag
+     * @param bool $flag
      */
     public function setFlag(bool $flag = self::FLAG_DEFAULT_VALUE): self
```

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
Checking `ConstFetch` seems cause error in other test:

```diff
 There were 7 failures:

1) Rector\Tests\DeadCode\Rector\If_\UnwrapFutureCompatibleIfPhpVersionRector\UnwrapFutureCompatibleIfPhpVersionRectorTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules-tests/DeadCode/Rector/If_/UnwrapFutureCompatibleIfPhpVersionRector/Fixture/fixture.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
     public function run()
     {
         // current PHP: 7.2
-        return 'is PHP 7.2+';
+        if (version_compare(PHP_VERSION, '7.2', '<')) {
+            return 'is PHP 7.1-';
+        } else {
```

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you @samsonasik 🥳

**Comment by bradjones1** [comment]
Thank you all very much.

**Pull request merged**
