### PR TITLE
[TypeDeclaration] Skip implements mixed, and already has typed return on AddReturnTypeDeclarationRector

### LINKED ISSUE #7235: Incorrect behavior of `AddReturnTypeDeclarationRector`
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/912bde23-17a2-40f9-a990-c9c23b490d30

```php
<?php

namespace Symfony\Component\Form;

interface DataTransformerInterface
{
    /**
     * @return mixed
     */
    public function transform();
}

final class MyDataTransformer implements DataTransformerInterface
{
    public function transform(): string
    {
        return 'foo';
    }
}
```

### Responsible rules

* `AddReturnTypeDeclarationRector`

## Expected Behavior

As my return type is more explicit, it should be kept. Same occurs for Symfony normalizers

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7235

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @OskarStark

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by OskarStark** [comment]
Many thanks!

**Pull request merged**
