### PR TITLE
[BetterPhpDocParser] Enable textBetweenTagsBelongsToDescription on BetterPhpDocParser extends PhpDocParser

### PR DESCRIPTION
**Pull request by samsonasik**
Closes https://github.com/rectorphp/rector-src/pull/4482

### CODE REVIEW

**Comment by samsonasik** [comment]
It seems it cause error:

```diff
1m 2s
Run bin/rector process src tests rules-tests packages packages-tests --ansi
    0/1420 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
  160/1420 [▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░]  11%
  580/1420 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  40%
 1280/1420 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░]  90%

1 file with changes
===================

1) packages/BetterPhpDocParser/PhpDocParser/BetterPhpDocParser.php:3

    ---------- begin diff ----------
@@ @@

 namespace Rector\BetterPhpDocParser\PhpDocParser;

-use Nette\Utils\Strings;
 use PhpParser\Node;
 use PHPStan\PhpDocParser\Ast\PhpDoc\ParamTagValueNode;
 use PHPStan\PhpDocParser\Ast\PhpDoc\PhpDocChildNode;
    ----------- end diff -----------

                                                                                
 [ERROR] Could not process                                                      
         "/home/runner/work/rector-src/rector-src/packages/PhpDocParser/PhpDocPa
         rser/PhpDocNodeTraverser.php" file, due to:                            
         "System error: ""                                                      
         Run Rector with "--debug" option and post the report here: 
https://github.com/rectorphp/rector/issues/new
". On line:
         56                                                                     
```

Ref https://github.com/rectorphp/rector-src/actions/runs/5915943638/job/16042686926?pr=4817#step:6:31

**Comment by samsonasik** [comment]
@TomasVotruba it works 🎉 🎉 🎉

**Comment by samsonasik** [comment]
Finally works  🎉 🎉 🎉 All checks have passed 🎉 🎉 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
Rebased.

**Comment by samsonasik** [comment]
Rebased.

**Comment by TomasVotruba** [comment]
Let's ship this :+1:

**Pull request merged**
