### PR TITLE
[DeadCode] Handle crash on negation class const fetch with static:: and parent:: on RemoveDeadZeroAndOneOperationRector

### LINKED ISSUE #7321: Crash Unsupported operand types: string * int on RemoveDeadZeroAndOneOperationRector
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.13.9            |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/9caf7439-0dd0-45fe-998b-3d25dc9e6038

Given the following code:

```php
final class DemoFile
{
    protected const CSRF_HASH_BYTES      = 16;
    
    protected function derandomize(string $token): string
    {
        $key   = substr($token, -static::CSRF_HASH_BYTES * 2);
    }
}
```

It produce error:

```bash
 [ERROR] Could not process "DemoFile.php" file, due to:                                                 
         "System error: "Unsupported operand types: string * int"                                                       
                                                                                                                        
         Stack trace:                                                                                                   
         #0 vendor/rector/rector/vendor/nikic/php-parser/lib/PhpParser/ConstExprEvaluator.php(96):                      
         PhpParser\ConstExprEvaluator->evaluate(Object(PhpParser\Node\Expr\UnaryMinus))                                 
         #1 vendor/rector/rector/src/PhpParser/Node/Value/ValueResolver.php(105):          
```

## Expected Behaviour

should not error.

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
final class SkipNegationClassConstFetch
{
    protected const CSRF_HASH_BYTES      = 16;

    protected function derandomize(string $token): int
    {
        echo -static::CSRF_HASH_BYTES * 2;
    }
}
```

It currently produce error:

```bash
There was 1 error:

1) Rector\Tests\DeadCode\Rector\Plus\RemoveDeadZeroAndOneOperationRector\RemoveDeadZeroAndOneOperationRectorTest::test with data set #6 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
TypeError: Unsupported operand types: string * int
```

Fixes https://github.com/rectorphp/rector/issues/7321

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
Also handle `parent::` usage

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
