### PR TITLE
[TypeDeclaration] Skip Child return mixed on ReturnTypeDeclarationRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
abstract class AbstractClass
{
    /**
     * @param mixed[] $param
     * @return bool
     */
    public function getValue(array $param)
    {
        return rand(0, 1)
            ? true
            : false;
    }
}

class SkipChildReturnMixed extends AbstractClass
{
    /**
     * @param mixed[] $param
     * @return bool
     */
    public function getValue(array $param)
    {
        if (isset($param['data'])) {
            return $param['data'];
        }

        return false;
    }
}
```

It will only change parent return:

```diff
-     * @return bool
      */
-    public function getValue(array $param)
+    public function getValue(array $param): bool
     {
         return rand(0, 1)
```

that will make Fatal error: `Fatal error: Declaration of ExtendsParentClass::getValue(array $param) must be compatible with AbstractClass::getValue(array $param): bool` ref https://3v4l.org/PhZep

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
It somehow make invalid when child has return, added failing fixture https://github.com/rectorphp/rector-src/pull/843/commits/21f811796455df7734dc3961f6146b2222ac83aa

**Comment by samsonasik** [comment]
It seems if child has return, it should be skipped as well, as change it will cause another fatal error:

parent add return type: https://3v4l.org/KArsc Fatal Error
parent skip add return type: https://3v4l.org/M9K4l OK

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
