### PR TITLE
[Php82] Handle parent already readonly on ReadOnlyClassRector

### LINKED ISSUE #7665: Child non-readonly class doesnt refactor it into readonly when the parent was readonly class
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.15.0             |
| PHP Version | v8.2             |

i had issue when i extends the readonly class which child class doesnt have readonly

```php
readonly abstract class Action
{
}
```

child

```php
class Something extends Action
{
}
```

## Expected Behaviour

i expect this is will automatically add the readonly when the parent was readonly

```php
readonly abstract class Action
{
}
```

child

```php
readonly class Something extends Action
{
}
```

### PR DESCRIPTION
**Pull request by samsonasik**
If parent class already readonly, child (current class analyzed) must be readonly too, ref https://3v4l.org/D9N7A

Fixes https://github.com/rectorphp/rector/issues/7665

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @kevariable

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by kevariable** [comment]
Thank you for the great work @samsonasik

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
