### PR TITLE
Incorrect behavior of RemoveUnusedPrivateMethodRector

### PR DESCRIPTION
**Pull request by tugmaks**
Fixes https://github.com/rectorphp/rector/issues/6507

### CODE REVIEW

**Comment by samsonasik** [comment]
Please add 1 more test case for case insensitive:

```php
final class SkipArrayCallablesThisCaseInSensitiveMethodName
 {
     public function run()
     {
         $array  = [3, 2, 1];

         usort($array, [$this, 'sortCaseInSensitiveMethodName']);

         return $array;
     }

     private function sortCaseInSensitiveMETHODName($a, $b)
     {
         return $a <=> $b;
     }
 }
 ```

**Comment by tugmaks** [comment]
@samsonasik https://github.com/rectorphp/rector-src/blob/main/rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/skip_array_callables_this.php.inc

**Comment by samsonasik** [comment]
We need insencitive case one, which I tried your patch locally with insensitive "sortCaseInSensitiveMETHODName" and got failure.

**Comment by tugmaks** [comment]
@samsonasik done

**Review by samsonasik — APPROVED** [review]

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
