### PR TITLE
[Php80] Handle case mixed up default in first case+middle case on ChangeSwitchToMatchRector

### LINKED ISSUE #6880: Switch to match incorrect values
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v0.12.8             |

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec61847-6868-655e-aa37-7778e608b8d5

## Expected Behaviour

Don't break conditions or use the right default value ?

Thanks,
Alex

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #1537 Fixes rectorphp/rector#6880

### CODE REVIEW

**Comment by samsonasik** [comment]
@alexchuin this patch also handle if the `default` is in the middle and in the first without previous case.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by alexchuin** [comment]
Thanks, nice job @samsonasik ! 🔥

**Pull request merged**
