### PR TITLE
[DowngradePhp80] Allow Truthy with Ternary on DowngradeThrowExprRector

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Could you rebase on `main`?

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
Strange error in tests in different rule in CI:

```bash
1) Rector\Tests\DeadCode\Rector\ClassMethod\RemoveUnusedPromotedPropertyRector\RemoveUnusedPromotedPropertyRectorTest::test with data set #1 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPromotedPropertyRector/Fixture/skip_trait.php.inc
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 {
     use TraitA;
 
-    public function __construct(
-        private $usedDependency
-    ) {
+    public function __construct()
+    {
```

I can't reproduce locally even after composer update:

Screen Shot 2021-07-29 at 15 50 40

Probably a github action cache.

**Comment by samsonasik** [comment]
Finally, All checks have passed 🎉🎉🎉 with update fixture test on `RemoveUnusedPromotedPropertyRectorTest`,   

@TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
