### PR TITLE
Bump to PHPStan 1.12.2 and Fix test

### PR DESCRIPTION
**Pull request by samsonasik**
On PHPStan 1.12.2, currently cause error in test:

```diff
There was 1 failure:

1) Rector\Tests\TypeDeclaration\Rector\ClassMethod\ReturnTypeFromStrictTypedCallRector\Php80Test::test with data set #7 ('/Users/samsonasik/www/rector-...hp.inc')
Failed on fixture file "with_mixin.php.inc"
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
      * @throws GuzzleException
      * @throws JsonException
      */
-    protected function getOauthToken(string $key): mixed
+    protected function getOauthToken(string $key)
     {
                 return Cache::get($key);
```

Ref https://github.com/rectorphp/rector-src/actions/runs/10727420659/job/29749709717?pr=6289#step:5:96

This PR try to fix it.

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
It seems cause invalid rectify on call interface with mixed return without native return https://github.com/rectorphp/rector-src/pull/6289/commits/5044fa1e9d411d8faddead3063590a8ad7f49379

It seems phpstan no longer locate `ParametersAcceptor` by `@mixin`, it seems we can just skip the test :)

**Comment by samsonasik** [comment]
Fixed with the following summary:

- [x] Skip return type addition by `@mixin`, as it seems on PHPStan 1.12.2 it no longer lookup return type followed by `@mixin` correctly
- [x] Allow `mixed` return native type call
- [x] Skip `mixed` and other type, eg: `mixed|int` is invalid, see https://3v4l.org/ugpkM 

All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
