### PR TITLE
[TypeDeclaration] Skip mixed condition string on TypedPropertyFromStrictConstructorRector

### LINKED ISSUE #7840: Incorrect behavior of TypedPropertyFromStrictConstructorRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/613f6ed1-6961-4926-9878-82c0c48a8e41

```php
class Project {
    private $name;

    public function __construct(mixed $name) {
        if ($name === null) {
            $name = 'default';
        }
        $this->name = $name;
    }
}

$project = new Project(['name' => 123]);
```

### Responsible rules

* `TypedPropertyFromStrictConstructorRector`

## Expected Behavior

Rector is incorrectly assuming it's safe to convert the type of the property `$name` to `string, even though the constructor can take in any value. Setting the parameter type for the constructor to `mixed` or leaving it unspecified has the same incorrect behaviour.

This but doesn't occur if you
* change the `if` to `if ($name === null) { $this->name = 'default'; } else { $this->name = $name; }`
* change the `if` to a ternary `$this->name = $name === null ? 'default' : $name;`
* change the constructor to take a `$name` of type `int` (then it correctly changes the property `$name` to be `int | string`).

This obviously is concerning as this appears to do exactly what is specified wouldn't happen in https://getrector.com/blog/new-in-rector-015-complete-safe-and-known-type-declarations, namely that it won't add types it can't know are correct.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7840

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @aboyton

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by aboyton** [comment]
Thanks for the quick fix. As someone unfamiliar with the Rector codebase, can you explain why this was buggy? Bugs like this always decrease one's confidence in a tool so it's helpful to understand what exactly the issue is.

I guess my question is how hardcoded is a fix like this, or is this the type of bug that can be present in any rule? It's a little hard to tell how much there's a type inference engine running which these rules take the result of, or if instead each rule is pattern matching on specific things.

**Comment by samsonasik** [comment]
That was checking any assign var name, which should check property fetch and static property fetch only, you can read the doc for it https://github.com/rectorphp/php-parser-nodes-docs

**Pull request merged**
