### PR TITLE
[Scoper] Remove PHPStanStubLoader: move to dedicated file to define native classes

### PR DESCRIPTION
**Pull request by samsonasik**
Continue of https://github.com/rectorphp/rector-src/pull/2248, @TomasVotruba @ondrejmirtes this remove `PHPStanStubLoader` to move it up to dedicated file to avoid rely on require phpstan runtime from phpstan.phar.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
How do we test this behavior in build Rector?  http://github.com/rectorphp/rector

**Comment by TomasVotruba** [comment]
Feel free to merge and verify.

**Comment by samsonasik** [comment]
For `Attribute` class, I guess there is already test for it, ref

- https://github.com/rectorphp/rector/runs/6333407659?check_suite_focus=true#step:5:22
- https://github.com/rectorphp/rector/tree/main/e2e/attributes

I am merging it;)

**Comment by TomasVotruba** [comment]
@samsonasik I've just tried reverting this one in my project and it worked :+1: 
We should keep it :) 

Breakes https://github.com/rectorphp/rector/issues/7191

**Comment by samsonasik** [comment]
@TomasVotruba the current issue is custom bootstrap is not working, while stubs is working ok https://github.com/samsonasik/ci4-album/runs/6631694665?check_suite_focus=true#step:10:22

it load custom bootstrap bootstrap.php

**Comment by samsonasik** [comment]
[stub loader is now resolved](https://github.com/rectorphp/rector/commit/85ff7027f7e82ed995f8858040cf448a1ed161b1), the one that still issue is custom bootstrap https://github.com/samsonasik/ci4-album/runs/6631694665?check_suite_focus=true#step:10:22 which working ok on 0.13, which dedicated class already applied.

**Comment by TomasVotruba** [comment]
> [stub loader is now resolved](https://github.com/rectorphp/rector/commit/85ff7027f7e82ed995f8858040cf448a1ed161b1), the one that still issue is custom bootstrap [samsonasik/ci4-album/runs/6631694665?check_suite_focus=true#step:10:22](https://github.com/samsonasik/ci4-album/runs/6631694665?check_suite_focus=true#step:10:22) which working ok on 0.13, which dedicated class already applied.

Good, I've tried it and confirm it works on PHP 7.2 project

**Pull request merged**
