### PR TITLE
[IDE-refactoring cleanup] Remove rather custom PassFactoryToEntityRector and NewUniqueObjectToEntityFactoryRector rules, better use PHPStorm there

### PR DESCRIPTION
**Pull request by TomasVotruba**
Inversion of https://github.com/rectorphp/rector-src/commit/c0feeae39f39da423efa6362497a7a440cfb927b

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba It somehow broke package test sabbelasichon/typo3-rector https://github.com/rectorphp/rector-src/runs/3444197104#step:7:36

```diff
1) Ssch\TYPO3Rector\Tests\FileProcessor\TypoScript\TypoScriptProcessorTest::test with data set #5 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
tests/FileProcessor/TypoScript/Fixture/TypoScript/additional_headers_already_in_new_format.typoscript
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
                 header = Content-type: text/html
             }
             /*
-                This is a multiline comment
-            */
+Thisisamultilinecomment
+*/
         }
```

**Comment by sabbelasichon** [comment]
@samsonasik I am fixing this. Sorry.

**Comment by sabbelasichon** [comment]
@samsonasik Created a new release which fixed the test.

**Comment by samsonasik** [comment]
@sabbelasichon thank you 👍

**Pull request merged**
