### PR TITLE
Avoid scoping parameter provider to re-use, remove it from AbstractRector to ease the dependency tree

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba this is what I tried at https://github.com/rectorphp/rector-src/pull/2093, and it is not working, as it cause error:

```
 Cannot autowire service "Laminas\ServiceManager\Migration\Rector\Class_\ImplementsFactoryInterfaceToPsrFactoryRector": 
 
 argument "$parameterProvider" of method "__construct()" references class "Symplify\PackageBuilder\Parameter\ParameterProvider" but no such service exists.
```

even register manually via : 

```php
$services->set()
```

or : 

```php
$services->load()
```

that's why it rolled back at https://github.com/rectorphp/rector-src/pull/2095

**Comment by TomasVotruba** [comment]
It seems the scoper does not handle it correctly. It should work.

Where is the link to deployed rector/rector? I'll check

**Comment by TomasVotruba** [comment]
Let's try the merge, I'll see it more easily

**Comment by samsonasik** [comment]
@TomasVotruba it can be reproduced by :

```bash
git clone git@github.com:laminas/laminas-servicemanager-migration.git
cd laminas-servicemanager-migration
composer config minimum-stability dev
composer config prefer-stable true
echo "yes" | composer require --dev rector/rector:dev-main
vendor/bin/phpunit
```

**Comment by TomasVotruba** [comment]
I'll try that :+1:

**Comment by TomasVotruba** [comment]
I see. It's possible to completely unscope the ParameterProvider, but I see 2 problems with that:

* it would reveal full parameter API to the public - which is not what we want, but rather keep Rector API minimalistic and focused
* it would require lot of hacking of Scope, beause native class "unscoping" mean scoping + aliasing, that's why the original class cannot be found


I see a 2nd way, so provide configuration services, that wraps the API safely and also provides way to aks for configuraiton:
https://github.com/rectorphp/rector-src/pull/2187

**Pull request merged**
