### PR TITLE
[CodingStyle][EarlyReturn] Fix infinite if else on BinarySwitchToIfElseRector+RemoveAlwaysElseRector

### LINKED ISSUE #8220: Rector hangs indefinitely
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | Current master (884a47)  |

The following example hangs indefinitely. However, it doesn't even seem like it is transforming the code back and forth.

## Minimal PHP Code Causing Issue

https://getrector.com/demo/77ce4ebe-1776-4631-89c2-fec1d8773911

## Expected Behaviour

`BinarySwitchToIfElseRector` should convert the `switch` to `if-elseif`, then `RemoveAlwaysElseRector` should convert `elseif` to `if`. Then processing should end.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8220

### CODE REVIEW

**Comment by samsonasik** [comment]
@jlherren this should fix https://github.com/rectorphp/rector/issues/8220, the remove always else need on second run :)

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by TomasVotruba** [comment]
Thanks :+1: 

I still think the switch to if/else is kind of pointless with match. I recall it was my idea to add this rule to avoid switched back in PHP 7.4 :) but now match seem like much better logical choice, that this rule would skip.

**Comment by samsonasik** [comment]
switch to match is part of upgrade, while that can cause a different logic, as need default value:

```
$message = match ($statusCode) {
    200, 300 => null,
    400 => 'not found',
    500 => 'server error',
    default => 'unknown status code',
};
```

this code doesn't have default value to compare so mostly use if else.

**Comment by samsonasik** [comment]
Without default value, it will cause `UnhandledMatchError`, which if else is better for this case https://3v4l.org/52bgD

BinarySwitchToIfElse is to make if elseif works and the transformation keep working as expected.

**Comment by TomasVotruba** [comment]
Else is the default here, so it can be upgraded to `match` as well:

```php
        switch (mt_rand()) {
            case 1:
                return 10;
            case 2:
                return 20;
        }
        return 30;
```

↓

```php
return match(mt_rand()) {
    1 => 10,
    2 => 20,
    default => 30,
};
```

The `switch` should remain untouched, untill PHP 8.0 comes and offer better option. Whether manual or Rector is less important

**Comment by samsonasik** [comment]
I think that depends, if no last return, this rule still make sense, see https://getrector.com/demo/0412d7c9-b99a-4299-a945-7f735cbc9fd9

**Comment by TomasVotruba** [comment]
> I think that depends

Indeed, that's why PHPStan and developer should handle these.

In `switch()` cases I've seen in most projects there is another default value under it/above it or implicit `null` after the switch.

**Comment by samsonasik** [comment]
`switch` use case doesn't necessarily before return, it can be on middle of multiple statement, something like this assign is vaild https://getrector.com/demo/c23ff74a-0f2d-4306-8c9f-f6bb09d7cbdb

which change to if elseif is more valid.

**Pull request merged**
