### PR TITLE
 [CodeQuality] Skip not regex on SimplifyRegexPatternRector 

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://github.com/rectorphp/rector/issues/7993

@kenjis let's start with detect not regex type before check of unicode identifier.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by samsonasik** [comment]
@kenjis it seems `RegexPatternDetector::isRegexPattern()` doesn't check identifier, eg: `/u` or `/i` or `/anything`, so it will always skipped if regex contains identifier:

https://getrector.com/demo/4114fea0-ee00-4394-a714-b3e325a3dd8b

which regex identifier can be any of `imsxeADSUXJu`, it was exists in `ConsistentPregDelimiterRector`, just removed at 

https://github.com/rectorphp/rector-src/pull/3797/files#diff-b52d5691f8efd8fdd8b301dd7b8110eb3048ca332e76619f030a6a89f5764278

The logic of `ConsistentPregDelimiterRector` (that removed) should be bring back to verify that

**Comment by kenjis** [comment]
@samsonasik It seems the [delimiters](https://www.php.net/manual/en/regexp.reference.delimiters.php) are limited.
https://getrector.com/demo/01a2e742-ed67-4dde-9e66-d1ef58d6275c

**Comment by samsonasik** [comment]
Yes 👍

**Comment by samsonasik** [comment]
`RegexPatternDetector` was designed for common delimiter used, other than that, just skipped. I think we can focus on what more important part, the identifier usage: `imsxeADSUXJu`

**Comment by kenjis** [comment]
Yeah, identifiers are more important.

**Pull request merged**
