### PR TITLE
[DX] Replace deprecated danielstjules/stringy with Symfony\String

### PR DESCRIPTION
**Pull request by TomasVotruba**
- replacing with Symfony\String
- try removing dim fetch rename

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba typo3-rector seems needs to be updated as well https://github.com/sabbelasichon/typo3-rector/blob/9de803d00a9485cec79bb364e52eb85ab3613e03/src/Helper/StringUtility.php#L7

**Comment by samsonasik** [comment]
@TomasVotruba stringy seems still included https://github.com/rectorphp/rector/blob/main/vendor/danielstjules/stringy/src/Stringy.php and the `#[\ReturnTypeWillChange]` change is gone, probably due to `typo3-rector` still uses it.

**Comment by TomasVotruba** [comment]
Thanks for checking!

I also just removed it from Symplify, so maybe the tagging it is needed.

**Comment by samsonasik** [comment]
@TomasVotruba I created issue on typo3-rector for it https://github.com/sabbelasichon/typo3-rector/issues/2745

**Comment by samsonasik** [comment]
@TomasVotruba it seems stringy still required in rector-symfony,. ref https://github.com/rectorphp/rector-symfony/blob/5a24edfe3cf6f66766cbf2bc7eddc7340f06a800/composer.json#L9

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
