### PR TITLE
[DeadCode] Remove property comment same line on RemoveUnusedPrivatePropertyRector

### PR DESCRIPTION
**Pull request by samsonasik**
Closes #3539

### CODE REVIEW

**Comment by samsonasik** [comment]
@staabm this is a quick solution, the general solution probably on the `removeNode()` process, but that will make it require `next` node attribute usage

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
@staabm another general solution is probably create a dedicated rector rule to verify the Stmt just removed with next is Nop in the same line, eg: `RemoveJustRemovedSameLineCommentStmtRemovedRector`

that will work on usage on other rule as well :)

**Comment by staabm** [comment]
Thanks for working on it.

I can't tell which works best for rector. I have no experience with Nop AST nodes either.

**Comment by samsonasik** [comment]
I will create alternative PR for it 👍

**Comment by samsonasik** [comment]
Checking stmt just removed in loop of StmtsAwareInterface probably make memory hog as it will compare object in array, so probably not best solution.

**Comment by samsonasik** [comment]
@staabm I created alternative PR for it, nevertheles https://github.com/rectorphp/rector-src/pull/3548

**Pull request merged**
