### PR TITLE
[CodingStyle] Skip multiline already self and/or this on PreferThisOrSelfMethodCallRector

### LINKED ISSUE #7363: Incorrect behavior of PreferThisOrSelfMethodCallRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | 0.13.7     |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/0c8e9f4c-916f-43fb-962e-e50c6b290f95

```php
<?php

use PHPUnit\Framework\TestCase;

final class DemoFile extends TestCase
{
    /**
     * @test
     */
    public function sourcesWithoutRight()
    {
        $episode = new Episode();
        self::assertSame(
            ["hls" => [], "hds" => [], "smooth" => [], "dash" => [], "progressive_download" => []], 
            $this->sources->getSourcesByEpisode($episode)
        );
    }
}
```

### Responsible rules

* `PreferThisOrSelfMethodCallRector`

## Expected Behavior

I'm currently upgrading a legacy project which still uses a "max line length of 120" (PSR2 is ... old? wow). I do not want to sacrifice this rule, because there is ongoing development on this project - so I want to use best of both worlds. 

Rector should just skip it. There is effectively no change, since it's already "self".

Btw.: great job. I :heart: rector.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7363

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @mvhirsch

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Surpassed by https://github.com/rectorphp/rector-src/pull/2759

**Comment by mvhirsch** [comment]
Thanks! :partying_face:

**Comment by TomasVotruba** [comment]
You're welcome 🙂

**Pull request closed without merging**
