### PR TITLE
[Php81] Skip used as ArrayDimFetch on Arg on side effect FuncCall on ReadOnlyPropertyRector

### LINKED ISSUE #6987: Incorrect behavior of ReadOnlyPropertyRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec899b3-cbe2-677a-a5de-570eb39b9e63

```php
<?php

final class DemoFile
{
    /**
     * @param array<string, array<string>> $items
     */
    public function __construct(private array $items)
    {}
    
    public function popFooItem(): void
    {
        if (!empty($this->items) && array_key_exists('foo', $this->items)) {
            array_pop($this->items['foo']);
        }
    }
}
```

### Responsible rules

* `ReadOnlyPropertyRector`

## Expected Behavior

Rector should not add a `readonly` property modifier when this same property is modified in a class method.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6987

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by samsonasik** [comment]
I am merging it ;)

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
