### PR TITLE
[DX] Remove parent node from AbstractRector

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by samsonasik** [comment]
`RunTestsInSeparateProcesses` may need to be used in `RenameClasaRector` tests

**Comment by samsonasik** [comment]
`AutoImportNamesTest` need `RunTestsInSeparateProcesses` as well

**Comment by samsonasik** [comment]
Rename fixture usually solve it, but that will take try and errors, apply the `RunTestsInSeparateProcesses` into test classes is the fastest way to go, on this case, `AutoImportNamesTest` seems need to be updated as well

**Comment by samsonasik** [comment]
The removed fixtures should be rolled back to ensure no behaviour changed, I will check

**Comment by samsonasik** [comment]
I rolled back removed fixtures https://github.com/rectorphp/rector-src/pull/4465/commits/3b43f5941da9c97c7eb935934f0448c88eb9eabe

**Comment by TomasVotruba** [comment]
@samsonasik Gotta go dinner now :). Feel free to merge when this is ready :pray:  

We can test in the wild :muscle:

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba let's merge it ;)

**Pull request merged**
