### PR TITLE
[Core] Add Option::ALLOW_BC_BREAK option via --allow-bc-break

### LINKED ISSUE #6872: Add new namespaced rules under "BcBreak" namespace
# Feature Request

I think we can create new namespace, eg: "BcBreak" that can contains collection of rules that can make BC Break application, eg on framework to upgrade to major version.

The use case can be extended of TypedPropertyRector that allow BC Break without need check of modifiers.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6872

So it can be used in the rules to be used to upgrade application, eg: on `TypedPropertyRector`, using:

```bash
vendor/bin/rector --allow-bc-break
```

to update non-private property as well.

### CODE REVIEW

**Comment by samsonasik** [comment]
implemented 🎉 applied the example use case to `TypedPropertyRector`

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
I'm not sure about usefulness of this change, as any rule can be potentially BC break. Just 99.99 % cases isn't.

We would have to introduce huge level of complexity to maintain it to be reliable enough to be true. Otherwise it will loose trust and make it irrelevant. Same thing happened to PHP CS Fixer, where not-risky rules are breaking code and are not reliable.

İt should bee solved on rule level.

**Comment by samsonasik** [comment]
The BC-Break only applied when using `--allow-bc-break`, and it is optional, which requires change in the rules that potentially usefull for its use, eg: `TypedPropertyRector`, other won't.

I add its check https://github.com/rectorphp/rector-src/pull/1744/files#diff-cbdd57028cbf699819fb6adde8248728f712c6e75d0640239e089b5a1b73b8e8 before last checking for private and protected property only. Other previously skipped check verify still apply, eg: on interface, modified by trait, etc.

I think it is usefull for an application/library that requires a BC break major change, eg from version 1 to version 2.

Do you think the alternative is create a separate namespace like in original issue, eg: `BcBreak` namespace?

**Comment by TomasVotruba** [comment]
I understand the feature. Yet which is the complete list that are enabled/disabled by this flag, that is the hard question.
E.g. `AddParamTypeDeclarationRector` can break BC, but that's intentional as framework upgrade should follow.

The BC breaks should be avoided unless intentional on package upgrade.

Maybe this can be resolved on already existing level without marking each of ~600 rules as BC break/non BC break.

As for the typed property example, what change in code is needed?

**Comment by samsonasik** [comment]
Previously, before rector 0.12.9, eg on rector 0.12.8, there are 2 options: `classLikeTypeOnly = false` and `privatePropertyOnly = false`:

https://github.com/rectorphp/rector-src/blob/528d6dd6986c529246832f686e482c3f7bc46a40/rules/Php74/Rector/Property/TypedPropertyRector.php#L65-L71

which when user want to only update the code to update private property only, they can enable it via set in rector.php:

```php
    $services = $containerConfigurator->services();
    $services->set(TypedPropertyRector::class)
        ->call('configure', [[
            TypedPropertyRector::PRIVATE_PROPERTY_ONLY => true,
        ]]);
```

Start from 0.12.9, `TypedPropertyRector` is no longer configurable, above settings is removed at https://github.com/rectorphp/rector-src/pull/1496 and it only changes:

– private property
– protected property on final class without extends

which make user that want to upgrade the code for other modifiers except above is not possible.

**Comment by TomasVotruba** [comment]
Closing as separate rule is a better way: https://github.com/rectorphp/rector-src/pull/1745#issuecomment-1025239768

**Pull request closed without merging**
