### PR TITLE
[Php81] Skip param reassign on ReadOnlyPropertyRector

### LINKED ISSUE #7239: Incorrect behavior of `ReadOnlyPropertyRector`
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/cfc8955f-ecba-4a30-9563-d3abe1344fe3

```php
<?php

final class DemoFile
{
    public function __construct(private string $foo)
    {
        $foo = 'bar';
        
        $this->foo = $foo;
    }
}
```

### Responsible rules

* `ReadOnlyPropertyRector`

## Expected Behavior

This would result in an PHP error, it is not possible to make this property readonly in the constructor.

The following result would be possible:
```php
<?php

final class DemoFile
{
    private readonly string $foo;

    public function __construct(string $foo)
    {
        $foo = 'bar';
        
        $this->foo = $foo;
    }
}
```

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/7239

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @OskarStark

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by OskarStark** [comment]
Thanks 🙏 

Cc @mvhirsch

**Comment by OskarStark** [comment]
Cc @silasjoisten

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
rebased.

**Comment by samsonasik** [comment]
rebased.

**Review by TomasVotruba — APPROVED** [review]

**Comment by OskarStark** [comment]
Thanks for the merge, now it does not make an error, but it does not refactor it to use readonly, which can only be done by adding an explicit readonly class property.

WDYT @TomasVotruba ?

**Pull request merged**
