### PR TITLE
[CodeQuality] Skip used in next stmt on UnusedForeachValueToArrayKeysRector

### LINKED ISSUE #8753: `UnusedForeachValueToArrayKeysRector` removes values that are used
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | v1.2.1             |
| Rule | UnusedForeachValueToArrayKeysRector             |

This rule also removes values that are later used in that method ...

## Minimal PHP Code Causing Issue

Demo-page returns 500 error ... 

See 

- https://github.com/sreichel/magento-lts/pull/1/files#diff-f41ae70f01bb5969abbb4c815813e7393574ddb38562951b6012b0c1a8a84a5d (search for app/code/core/Mage/Core/Model/Date.php)
- https://github.com/sreichel/magento-lts/actions/runs/10020627174/job/27698413846

## Expected Behaviour

If the value is used lat,er it should be skipped.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8753

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉 /cc @sreichel

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Comment by sreichel** [comment]
WOW! Thanks. :100: 

I'll test it later.

**Comment by sreichel** [comment]
@samsonasik just a question ... is it possible to check HOW a value is used after `foreach`?

Eg ...
```
foreach ($array as $key => $unUsedValue) {
    ....
}

unset($key, $unUsedValue);
```

Could turn into 

```
foreach (array_keys($array) as $key) {
    ....
}

unset($key);
```

In this case the rule could be applied when `$unUsedValue` also gots removed from `unset()`.

Is it too complex to cover all possiblities?

**Comment by samsonasik** [comment]
this should already covered by this patch, but feel free to provide a failing test case if the issue persist.

**Comment by sreichel** [comment]
Time for me to learn "rectorphp" :)

Thanks for you work!

**Review by TomasVotruba — COMMENTED** [review]
👍

**Comment by sreichel** [comment]
> this should already covered by this patch, but feel free to provide a failing test case if the issue persist.

https://getrector.com/demo/e2d93df1-5c99-4ed6-912d-4ccebb276d8c

FYI. Its not an issue. Your change works as aspected.

**Pull request merged**
