### PR TITLE
WIP: Github-Actions: run tests on windows

### PR DESCRIPTION
**Pull request by staabm**
just to get a feeling what needs to be done

### CODE REVIEW

**Comment by staabm** [comment]
@TomasVotruba while working on windows ci builds to pass, I am stumbling over the `PHP_EOL` sensitive areas of `PhpDocInfoPrinter` and `*FileFormatterTest`.

what do you think about making these tests adhere to the a editor.config if present?

we could then use the https://github.com/rectorphp/rector-src/blob/main/.editorconfig as a base-config and adjust the tests to make them expect the EOL char, which is configured in the editor-config file, instead of relying on the platform dependent `PHP_EOL` or hardcode `\n` or similar.

this way tests, even when run on windows, would expect the line ending defined in the editor config (so tests running on windows would not necessarily error on ´\r\n` vs. `\n`.

another benefit, when taking e.g. `PhpDocInfoPrinter` into account, would be that the phpdoc beeing printed would adhere to a projects editor-config (if exists) and therefore newlines should automatically fit the project needs..?

is there an easy way to access the values from the rectors' editorconfig within these classes? what I found until now seem to be coupled to the `*FileFormatter*`-classes and is not widely accessible? or does the dependency contain already provide the current editor-config project config somewhere?

**Comment by TomasVotruba** [comment]
Hey, I'm not sure if I can help here.

My first though is: the `.editorconfig` should not be used for tests, as we don't test the `.editorconfig` functionality. Tests should test Rector printing behavior.

**Comment by staabm** [comment]
> My first though is: the `.editorconfig` should not be used for tests, as we don't test the `.editorconfig` functionality. Tests should test Rector printing behavior.

my though process was: when I use rector on a project which contains a `.editorconfig` I would expect the phpdoc printing behaviour to obey the rules of the editor config. (main use-case).

as a side effect this could be utilized on rector-src level to "configure" the EOLs in tests

**Comment by TomasVotruba** [comment]
I haven't worked with this feature in Rector, so I'm not sure. Maybe @sabbelasichon would know better as a `.editorconfig` feature contributor

**Comment by sabbelasichon** [comment]
I am gonna have a look tonight.

**Comment by staabm** [comment]
Side note: I just found that XmlFormatter already partly uses the EditorConfiguration.

In https://github.com/rectorphp/rector-src/pull/114 I am trying to make this more consistent, which goes into the same direction as my proposal above (just for a different class)

**Pull request closed without merging**
