### PR TITLE
[DowngradePhp73] Add DowngradePhp73JsonConstRector

### LINKED ISSUE #6931: Downgrade to PHP 7.2 and json_encode doesn't work well with JSON_THROW_ON_ERROR
# Bug Report

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e33afe6434a9707374815bb977cff09b6e57c199 |

There is no support for JsonException and JSON_THROW_ON_ERROR in PHP 7.2 and Rector does no conversion whatsoever on these calls, rendering refactored code inoperative

## Minimal PHP Code Causing Issue

https://getrector.org/demo/1ec73a9a-c6e9-69fe-99d3-57903e2998e7

## Expected Behaviour

JSON_THROW_ON_ERROR flasg should be dropped and JsonException replaced with Exception eventually.

### PR DESCRIPTION
**Pull request by samsonasik**
Add `DowngradePhp73JsonConstRector` for downgrade `JSON_THROW_ON_ERROR` constant.

Fixes https://github.com/rectorphp/rector/issues/6931

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by samsonasik** [comment]
I am merging it ;)

**Comment by samsonasik** [comment]
It seems we need to handling constant exists check, like:

```diff
2) vendor/clue/ndjson-react/src/Decoder.php:36
    ---------- begin diff ----------
@@ @@
             throw new \BadMethodCallException('Options parameter is only supported on PHP 5.4+');
         }
         if (\defined('JSON_THROW_ON_ERROR')) {
-            $options = $options & ~\JSON_THROW_ON_ERROR;
+            $options = $options & ~0;
         }
```

on current scoped downgrade, ref https://github.com/rectorphp/rector/commit/adcb702c28b7fc67c0af3432a955d01a02bb57d3#diff-5296e05dc788634e5de6fe389ae1bb99dd50ad8da693877b91bfde3ecf96c41a

**Comment by TomasVotruba** [comment]
Thanks :clap: :sunglasses:

**Comment by rs-ubaldi** [comment]
This is awesome thank you guys for finalizing this :-)

**Pull request merged**
