### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by bbrala**
Since we are developing 0.17, this should be updated. This also needs updating in rector.

https://github.com/rectorphp/rector/pull/8122

### CODE REVIEW

**Comment by bbrala** [comment]
Hmm, mr on rector is auto closed, also made an issue: https://github.com/rectorphp/rector/issues/8123

**Comment by TomasVotruba** [comment]
Hi, thanks for the update.

Actually, we don't need this alias, as we release quite often and latest tag should be always used instead. The dev is reserved only for experimental risky testing.

Could you remove the branch alias? Thanks

**Comment by bbrala** [comment]
But currently I then cannot develop against the experimental risky testing then, because i cannot require dev-main when current rector/rector is also a dependency (~0.17.0). So in order to test against head we'd then have to adjust main dependency also.

A minimal composer.json that gives me the error (which would be fixed with the branch alias on `rector/rector`:

```
{
    "name": "testing/package",
    "authors": [
        {
            "name": "DDEV User",
            "email": "nobody@example.com"
        }
    ],
    "require": {
        "rector/rector": "^0.17.10"
    },

    "require-dev": {
        "php": "^8.1",
        "cweagans/composer-patches": "^1.7.2",
        "phpstan/extension-installer": "^1.1",
        "phpstan/phpstan": "^1.0",
        "phpstan/phpstan-deprecation-rules": "^1.0",
        "phpunit/phpunit": "^10.0",
        "rector/rector-src": "dev-main",
        "symplify/vendor-patches": "^11.0",
        "symfony/yaml": "^5 || ^6"
    },

    "config": {
        "optimize-autoloader": true,
        "update-with-dependencies": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "phpstan/extension-installer": true,
            "rector/extension-installer": true,
            "cweagans/composer-patches": true
        }
    },

    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "enable-patching": true
    }
}
```

**Comment by bbrala** [comment]
So that is pretty annoying, if th rector-src alias is removed that is fine i think, but the alias on the main repository is kinda needed if we'd want to test against rector-src#dev-main

**Comment by TomasVotruba** [comment]
You should always use `rector/rector` package.

**Comment by bbrala** [comment]
Ok, lets try that.

```
{
    "name": "bjorn/html",
    "authors": [
        {
            "name": "DDEV User",
            "email": "nobody@example.com"
        }
    ],
    "require": {
        "rector/rector": "^0.17.10"
    },

    "require-dev": {
        "php": "^8.1",
        "cweagans/composer-patches": "^1.7.2",
        "phpstan/extension-installer": "^1.1",
        "phpstan/phpstan": "^1.0",
        "phpstan/phpstan-deprecation-rules": "^1.0",
        "phpunit/phpunit": "^10.0",
        "rector/rector": "dev-main",
        "symplify/vendor-patches": "^11.0",
        "symfony/yaml": "^5 || ^6"
    },

    "config": {
        "optimize-autoloader": true,
        "update-with-dependencies": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "phpstan/extension-installer": true,
            "rector/extension-installer": true,
            "cweagans/composer-patches": true
        }
    },

    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "enable-patching": true
    }
}
```

```
Your requirements can be resolved successfully when require-dev packages are present.
You may need to move packages from require-dev or some of their dependencies to require.

  Problem 1
    - Root composer.json requires rector/rector ^0.17.10, found rector/rector[dev-main, 0.15.x-dev (alias of dev-main)] but it does not match the constraint.
```

:x

**Comment by samsonasik** [comment]
You define rector in 2 places: require and require-dev, that's why it conflict

**Comment by samsonasik** [comment]
If branch alias need update, it also need update on build scoper as well

https://github.com/rectorphp/rector-src/blob/211deb44af8953bc0e67095d64aa45ec0e17d157/build/target-repository/composer.json#L20

**Comment by bbrala** [comment]
Well, it seems i do need rector-src to be able to use phpstan: 
https://github.com/palantirnet/drupal-rector/actions/runs/5798511775/job/15716428642?pr=234

Which is kinda weird since rector already loads those kinda, although in the rector vendor folder in the real vendor folder.

Tests are all green so that is good though

**Comment by TomasVotruba** [comment]
That's because PHPStan does not autolaod Rector's autoload. 

To make PHPStan aware of Rector, add it's autoload to bootstrap files - https://phpstan.org/config-reference#bootstrap -  in `phpstan.neon`. One of these 2:

* https://github.com/rectorphp/rector/blob/main/vendor/scoper-autoload.php
* https://github.com/rectorphp/rector/blob/main/vendor/autoload.php

**Comment by bbrala** [comment]
Thank you so much. ❤️

**Comment by bbrala** [comment]
This fixed phpstan so everything seems fine on .17 :)

**Comment by TomasVotruba** [comment]
Good job! Glad to hear that :muscle:

**Pull request closed without merging**
