### PR TITLE
[TypeDeclaration] Do not add return type on parent Closure for deep closure has return type on ReturnTypeFromStrictTypedCallRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
class App
{
    public static function init(): App
    {
        return new App;
    }
}

function () {

    function () {
        return App::init();
    };

};
```

It currently transformed to:

```diff
-function () {
+function (): App {    <--- invalid

-    function () {
+    function (): App {
         return App::init();
```

which the parent closure should not has `App` return type.

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
Also handle deep closure but parent has return type.

**Comment by samsonasik** [comment]
Now handle any inner function like 🎉

**Comment by TomasVotruba** [comment]
Thank you for this improvement :+1:

**Pull request merged**
