### PR TITLE
[DowngradePhp80] Handle variable $exception exists on DowngradeNonCapturingCatchesRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
        $exception = 'test';

        try {
            throw new Exception('message');
        } catch (\Exception) {
        }

        echo $exception;
```

it currently produce:

```diff
-} catch (\Exception) {
+} catch (\Exception $exception) {
```

which should be:

```diff
-} catch (\Exception) {
+} catch (\Exception $exception2) {
```

as already defined before and use `$exception` will replace existing variable.

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
@TomasVotruba phpunit error seems due to new PHPStan release 1.5.2

```bash

1) Rector\Tests\DowngradePhp56\Rector\CallLike\DowngradeArgumentUnpackingRector\DowngradeArgumentUnpackingRectorTest::test with data set #12 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
PHPStan\Reflection\MissingMethodFromReflectionException: Method chain() was not found in reflection of class Rector\Tests\DowngradePhp56\Rector\CallLike\DowngradeArgumentUnpackingRector\Fixture\SomeClass.

phar:///home/runner/work/rector-src/rector-src/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ClassReflection.php:389
```

**Review by TomasVotruba — APPROVED** [review]

**Comment by samsonasik** [comment]
@TomasVotruba pin to phpstan 1.5.1 seems working ok, the error in phpstan 1.5.2 seems due to class conflict in fixture files, I will check.

**Comment by samsonasik** [comment]
@TomasVotruba I renamed fixture classes in `Fixture` directories under rules-tests, it should be ok now https://github.com/rectorphp/rector-src/pull/1976/commits/aba5899329d2fd94424891e0b563c7bf44434ec6

**Comment by samsonasik** [comment]
@TomasVotruba it works 🎉 I am merging it ;)

**Comment by TomasVotruba** [comment]
> @TomasVotruba I renamed fixture classes in Fixture directories under rules-tests, it should be ok now https://github.com/rectorphp/rector-src/commit/aba5899329d2fd94424891e0b563c7bf44434ec6

@samsonasik That's how I usually solve these autoload naming conflicts :+1: It's the best to have unique class names :)

**Pull request merged**
