### PR TITLE
Re-Trigger build scopped as prev quoted commit message cause build failure and there is symplify update

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
Service not found error seems unrelated:

```
Run bin/rector process src tests rules-tests packages packages-tests --ansi --no-progress-bar
PHP Fatal error:  Uncaught _PHPStan_76800bfb5\Nette\DI\ServiceCreationException: Service of type Rector\PHPStanRules\NodeAnalyzer\SymfonyConfigMethodCallAnalyzer: Class Symplify\PHPStanRules\NodeAnalyzer\TypeAndNameAnalyzer needed by $typeAndNameAnalyzer in __construct() not found. Check type hint and 'use' statements. in phar:///home/runner/work/rector-src/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php:449
```

**Comment by samsonasik** [comment]
It seems due new symplify release https://github.com/symplify/symplify/commit/fe3531cfc88597aefa740e283a6cef0c9219115e

**Comment by samsonasik** [comment]
I created PR to phpstan-rules repo for this https://github.com/rectorphp/phpstan-rules/pull/14

**Comment by samsonasik** [comment]
It seems there is another error:

```bash
➜  rector-src git:(samsonasik-patch-1) ✗ bin/rector process src tests rules-tests packages packages-tests --ansi
PHP Fatal error:  Uncaught _PHPStan_76800bfb5\Nette\DI\ServiceCreationException: Service of type Rector\PHPStanRules\Rule\ForbiddenComplexArrayConfigInSetRule: Service of type Symplify\PHPStanRules\Symfony\NodeAnalyzer\SymfonyPhpConfigClosureAnalyzer needed by $symfonyPhpConfigClosureAnalyzer in __construct() not found. Did you add it to configuration file? in phar:///Users/samsonasik/www/rector-src/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Resolver.php:447
```

by try to use fork of PR https://github.com/rectorphp/phpstan-rules/pull/14

```diff
-        "rector/phpstan-rules": "^0.3.8",
+        "rector/phpstan-rules": "dev-patch-1 as 0.4.1",
         "rector/rector-generator": "^0.3",
         "spatie/enum": "^3.9",
         "symplify/coding-standard": "^9.4.65",
@@ -150,5 +150,11 @@
         "platform-check": false
     },
     "minimum-stability": "dev",
-    "prefer-stable": true
+    "prefer-stable": true,
+    "repositories" : [
+        {
+            "type" : "vcs",
+            "url" : "https://github.com/samsonasik/phpstan-rules"
+        }
+    ]
```

**Comment by samsonasik** [comment]
Ok, so the services config need to be registered to phpstan config:

```
- vendor/symplify/phpstan-rules/packages/symfony/config/services.neon
```

need to be included, added fork for PR https://github.com/rectorphp/phpstan-rules/pull/14 to show that it works.

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba the temporary change to composer.json can be reverted after PR rectorphp/phpstan-rules#14 merged and tagged.

**Comment by samsonasik** [comment]
composer.json reverted with update to use phpstan-rules ^0.4.2

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
