### PR TITLE
[Core] Fix ConfigurableCallValuesCollectingPhpFileLoader:load() return type

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Damn, Rector is putting it back :D

**Comment by TomasVotruba** [comment]
This should be handled by the downgrade rule though

**Comment by samsonasik** [comment]
The `DowngradeVoidTypeDeclarationRector` seems need to handle `vendor` dir locate, possibly need `ReflectionProvider`

**Comment by samsonasik** [comment]
@TomasVotruba it seems `DowngradeVoidTypeDeclarationRector` need to be registered to `build/config/config-downgrade.php`

**Comment by samsonasik** [comment]
@TomasVotruba it seems the `AddVoidReturnTypeWhereNoReturnRector` need handling for it:

```bash
1) src/DependencyInjection/Loader/ConfigurableCallValuesCollectingPhpFileLoader.php
    ---------- begin diff ----------
--- Original
+++ New
@@ @@
     /**
      * @param mixed $resource
      */
-    public function load($resource, string $type = null)
+    public function load($resource, string $type = null): void
     {
         // this call collects root values
         $this->collectConfigureCallsFromJustImportedConfigurableRectorDefinitions();
    ----------- end diff -----------
Applied rules:
27
 * AddVoidReturnTypeWhereNoReturnRector
 ```

**Comment by samsonasik** [comment]
Added failing fixture https://github.com/rectorphp/rector-src/pull/134/commits/8cbc99b8420a28f24e752ca701e02c2827432d86

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
@TomasVotruba the `string` type is somehow removed at : 
 
https://github.com/rectorphp/rector/blob/10ad6fa7782be2d5bb74111b595a112902e07214/src/DependencyInjection/Loader/ConfigurableCallValuesCollectingPhpFileLoader.php#L26-L27
 
 which should not, it seems happen during downgrade.

**Pull request merged**
