### PR TITLE
[Scoped] Fix build standalone and along other package on rector/rector

### PR DESCRIPTION
**Pull request by samsonasik**
@TomasVotruba as the PHPStan 1.0 not released yet, it seems it cause error on scoped build:

- https://github.com/rectorphp/rector/actions/runs/1391746451
- https://github.com/rectorphp/rector/actions/runs/1391746454

ref https://github.com/rectorphp/rector/issues/6776#issuecomment-953396494

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba let's give it a try to use PHPStan `^1.0` ?

**Comment by TomasVotruba** [comment]
Thank you ☺️

**Comment by samsonasik** [comment]
it seems still not working https://github.com/rectorphp/rector/runs/4034247679?check_suite_focus=true

**Comment by samsonasik** [comment]
I will temporary manually create branch in rector/rector repo and try to require it.

**Comment by samsonasik** [comment]
@TomasVotruba it seems for `^1.0`, it require to set config minimum-stability and prefer-stable first:

```
➜  prj composer config minimum-stability dev
➜  prj composer config prefer-stable true
```

I will create new PR for it.

**Comment by samsonasik** [comment]
@TomasVotruba the issue with seems mostly on along with other package, eg: phpstan itself:

```bash
➜  prj composer config minimum-stability dev                     
➜  prj composer config prefer-stable true                        
➜  prj composer require --dev rector/rector:dev-temp-phpstan1    
./composer.json has been updated
Running composer update rector/rector
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking phpstan/phpstan (dev-master 2d111cf)
  - Locking rector/rector (dev-temp-phpstan1 89359e2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing phpstan/phpstan (dev-master 2d111cf): Extracting archive
  - Installing rector/rector (dev-temp-phpstan1 89359e2): Extracting archive
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
➜  prj composer require --dev phpstan/phpstan:0.12.99        
./composer.json has been updated
Running composer update phpstan/phpstan
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - rector/rector is locked to version dev-temp-phpstan1 and an update of this package was not requested.
    - rector/rector dev-temp-phpstan1 requires phpstan/phpstan 1.0.x-dev as 0.12.99 -> found phpstan/phpstan[dev-master, 1.0.x-dev (alias of dev-master)] but it conflicts with your root composer.json require (0.12.99).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

that's even set conflict `"phpstan/phpstan": "<0.12.99",` and use alias on require `"phpstan/phpstan": "1.0.x-dev as 0.12.99"`

**Comment by TomasVotruba** [comment]
I used this alias in Symplify to solve it.  

https://github.com/symplify/symplify/blob/main/composer.json#L24

**Comment by samsonasik** [comment]
That's not solve the "along with other package" when user require another phpstan after it, eg:

```
composer require rector/rector:dev-main
composer require phpstan/phpstan:^0.12.99
```

**Comment by samsonasik** [comment]
Ok, it seems user needs to require `phpstan ^1.0` as well to use dev-main. If user already use phpstan 0.12.99, it will error as below, so existing user that not using phpstan ^1.0 can't consume it, and PHPStan 1.0 not yet released yet, so cannot use latest rector/rector without manually update their requirement to user `^1.0` with minimum-stability dev. 

```bash
➜  prj composer config minimum-stability dev      
➜  prj composer config prefer-stable true     
➜  prj composer require --dev rector/rector:"dev-temp-phpstan1#83ecf63049fc29800a1830d925ae337d4038a184"

./composer.json has been updated
Running composer update rector/rector
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking phpstan/phpstan (dev-master 2d111cf)
  - Locking rector/rector (dev-temp-phpstan1 83ecf63)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing phpstan/phpstan (dev-master 2d111cf): Extracting archive
  - Installing rector/rector (dev-temp-phpstan1 83ecf63): Extracting archive
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

➜  prj composer require --dev phpstan/phpstan
Using version ^0.12.99 for phpstan/phpstan
./composer.json has been updated
Running composer update phpstan/phpstan
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - rector/rector is locked to version dev-temp-phpstan1 and an update of this package was not requested.
    - rector/rector dev-temp-phpstan1 requires phpstan/phpstan 1.0.x-dev as 0.12.99 -> found phpstan/phpstan[dev-master, 1.0.x-dev (alias of dev-master)] but it conflicts with your root composer.json require (^0.12.99).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.


➜  prj composer require --dev phpstan/phpstan:^1.0
./composer.json has been updated
Running composer update phpstan/phpstan
Loading composer repositories with package information
https://repo.packagist.org could not be fully loaded (curl error 7 while downloading https://repo.packagist.org/p2/phpstan/phpstan.json: Failed to connect to repo.packagist.org port 443 after 296 ms: Connection refused), package information was loaded from the local cache and may be out of date
Updating dependencies
Nothing to modify in lock file
Writing lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

**Pull request merged**
