### PR TITLE
[Bc Break] [Alternative] Drop children class detection

### PR DESCRIPTION
**Pull request by samsonasik**
Children class detection is usefull, but collect class may cause side effect on performance, so this PR drop it, with caveat for add return type which may cause bug when class has child.

For win-win solution, I skip add return type on abstract class.

FYI:  @dorrogeray @staabm @chescos @X-Coder264 @mfn 

**Trade-off**: back to original functionality, that **cannot** detect child, but set skip on add return type on abstract class which mostly overridden.

Notes:
-------

For limit on final class, that probably needs separate PR for separate discussion, as they will need to check on param type addition rules as well.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba you decide ;)

**Comment by samsonasik** [comment]
Also @nuryagdym FYI

**Comment by TomasVotruba** [comment]
Thank you for fast work :clap:  Let's roll

**Comment by chescos** [comment]
Thanks! My runtime is back down from 16 minutes to 2 minutes after upgrading from v1.1.0 to v1.1.1.

**Comment by TomasVotruba** [comment]
@chescos Awesome, glad to hear that :clap:

**Pull request merged**
