### PR TITLE
[TypeDeclaration] Add If_ and ElseIf_ support on WhileNullableToInstanceofRector

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
This rule should only handle `while` nodes, to keep it simple and allow opt-out.

These should be handled in another rules: https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#fliptypecontroltouseexclusivetyperector

**Comment by samsonasik** [comment]
I see, I will check if that support ElseIf_, I am closing it then ;)

**Comment by samsonasik** [comment]
It seems `FlipTypeControlToUseExclusiveTypeRector` directly use `Identical` and `NotIdentical` node, I am wondering why that not support inside while and require another `WhileNullableToInstanceofRector`

**Pull request closed without merging**
