### PR TITLE
[Php82] Skip ReadOnlyClassRector on has parent non-readonly class

### LINKED ISSUE #7646: Incorrect behavior of ReadOnlyPropertyRector, ReadOnlyClassRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/9b44dfe4-8825-4ab9-a516-d3907f7e5a09

```php
class A
{
}

final class B extends A
{
    public function __construct(private readonly int $foo)
    {
    }

    public function compute(): int
    {
        return $this->foo * 3;
    }
}
```

### Responsible rules

* `ReadOnlyPropertyRector`

* `ReadOnlyClassRector`

## Expected Behavior

class B should not be defined as readonly because parent class is not.

This generate the following error 

```
PHP Fatal error:  Readonly class B cannot extend non-readonly class A in
```

### PR DESCRIPTION
**Pull request by Yoann-TYT**
Fixes https://github.com/rectorphp/rector/issues/7646

### CODE REVIEW

**Review by samsonasik — APPROVED** [review]

**Comment by samsonasik** [comment]
Please update PR title to something like:

```
[Php82] Skip ReadOnlyClassRector on has parent non-readonly class
```

**Review by samsonasik — APPROVED** [review]
nvm, I edited your PR title :)

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by Yoann-TYT** [comment]
@TomasVotruba and @samsonasik  
Thanks for your quickly merge ! 🚀

**Pull request merged**
