### PR TITLE
[Config] Use RectorConfig::configure() on rules-tests

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
The coding standard should be applied, with newline per method call.

**Comment by samsonasik** [comment]
I updated to use new line per-call

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba I am merging it ;)

**Pull request merged**
