### PR TITLE
Bump PHPStan to 1.10.20

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@samsonasik Let's try this one, how long it will last :) :+1: 
Thanks for exploring the topic!

**Comment by TomasVotruba** [comment]
CI seems failing for 2 projects and build :thinking: 

Gotta sleep now, will explore failing test fixture tomorrow.

**Comment by samsonasik** [comment]
as we discussed before, without extends phpstan printer, it will got error:

```
Call to undefined method BetterStandardPrinter::pPHPStan_Node_AlwaysRememberedExpr
`

**Comment by samsonasik** [comment]
I create new PR for extends PHPStan printer instead:

- https://github.com/rectorphp/rector-src/pull/4308

**Pull request merged**
