### PR TITLE
[PostRector] Skip remove unused use on used in Attribute in php 7.x

### PR DESCRIPTION
**Pull request by samsonasik**
I tried in kahlan in php 7.2, and it show removed 

```php
use ReturnTypeWillChange;
```

see https://github.com/kahlan/kahlan/actions/runs/4448615448/jobs/7811656219

which used in attribute. This PR try to not remove it when used in php 7.2

### CODE REVIEW

**Comment by samsonasik** [comment]
It somehow still removed, it possibly due to `ReturnTypeWillChange` not exists yet:

Screen Shot 2023-04-04 at 22 11 57

**Comment by samsonasik** [comment]
@staabm this one is what I discussed about remove unused use feature in php 7.x current limitation on attribute usage on php 7.x that marked as comment

**Comment by samsonasik** [comment]
@TomasVotruba ok, on php 7.x environment, the following attribute usage:

```php
   #[ReturnTypeWillChange]
    public function offsetGet($offset)
````

is not detected as `Attribute`, or `FullyQualified`, or even `Identifier`, so that pure a "comment".

Looking of Parser we use, we currently have:

- [RectorParser](https://github.com/rectorphp/rector-src/blob/1da22824edd107108e087d40233769817a2cbe25/src/PhpParser/Parser/RectorParser.php#L12)
- [SimplePhpParser](https://github.com/rectorphp/rector-src/blob/1da22824edd107108e087d40233769817a2cbe25/src/PhpParser/Parser/SimplePhpParser.php)
- [SmartPhpParser](https://github.com/rectorphp/rector-src/blob/1da22824edd107108e087d40233769817a2cbe25/packages/PhpDocParser/PhpParser/SmartPhpParser.php#L15)

Looking on parser config, we use: `@currentPhpVersionPhpParser` which probably the use of it, see:

https://github.com/rectorphp/rector-src/blob/1da22824edd107108e087d40233769817a2cbe25/config/phpstan/parser.neon#L20-L26

I will look manually on php 7.x environment regarding it.

**Comment by staabm** [comment]
php7 did not have attributes and one of the key features of attributes is, that they don't make php7 error, because for php7 they look like comments (because they start with a `#` sign).

thats also the reason why this works for php7
```php
   #[ReturnTypeWillChange]
    public function offsetGet($offset)
```

but this does not work for php7 (even though it works for php8)
```php   
    #[ReturnTypeWillChange] public function offsetGet($offset)
```

**Comment by samsonasik** [comment]
@staabm yes, that's pure comment, even not a docblock, If we can force set Lexer Emulative to php 8.x, that possibly will be detected.

**Comment by samsonasik** [comment]
I am closing it for now.

**Pull request closed without merging**
