### PR TITLE
[DowngradePhp74] Do not remove non-null default value on nullable on DowngradeTypedPropertyRector

### LINKED ISSUE #6925: Incorrect behavior of DowngradeTypedPropertyRector
Hello

The DowngradeTypedPropertyRector rule doesn't preserve the default value if the property is nullable.

I didn't find the right way to fix this code to PR but i believe that maybe the default value should not be overridden here 
https://github.com/rectorphp/rector-src/blob/main/rules/DowngradePhp74/Rector/Property/DowngradeTypedPropertyRector.php#L70
if there is a default value defined on the original property

Best

# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-master      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.org/demo/1ec72395-f107-68ec-9441-876a705acf57

```php
<?php
declare(strict_types=1);

class DemoFile
{
	protected ?string $test = "test";
}
```

### Responsible rules

* `DowngradeTypedPropertyRector`

* `DowngradeAttributeToAnnotationRector`

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/6925

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
