### PR TITLE
[Php55] Add StaticToSelfOnFinalClassRector

### PR DESCRIPTION
**Pull request by samsonasik**
To make `static::class` to `self::class` on final class.

### CODE REVIEW

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thanks!

Could you update rule name to include "final"? So its clear its only for this context.

**Comment by samsonasik** [comment]
@TomasVotruba I renamed to `StaticToSelfOnFinalClassRector` https://github.com/rectorphp/rector-src/pull/3629/commits/5d9655bf739ab0260a2e065ec1f799a52f2bc545

**Comment by samsonasik** [comment]
All checks have passed :tada: @TomasVotruba I think it is ready.

**Comment by TomasVotruba** [comment]
Thanks 👍😊

**Pull request merged**
