### PR TITLE
[DeadCode] Skip possible null Iterator with Array Dim Fetch on RemoveDeadInstanceOfRector

### LINKED ISSUE #8147: Incorrect behavior of RemoveDeadInstanceOfRector
# Bug Report

| Subject        | Details              |
| :------------- | :--------------------|
| Rector version | last dev-main      |
| Installed as   | composer dependency  |

## Minimal PHP Code Causing Issue

See https://getrector.com/demo/fbf6cb49-df93-4675-a172-75f4f2f73ef6

```php
<?php

final class DemoFile
{
    private function complementArticleData(Iterator $articles): void
    {
        $result = [
            'artikel' => $articles,
            'farben' => null,
            'artikel_ids' => [],
        ];

        // collect article ids
        foreach ($result['artikel'] as $article) {
            $result['artikel_ids'][] = 1;
        }

        if ($result['artikel_ids'] !== []) {
            $result['farben'] = new stdClass();
        }

        // $result['farben'] might be also null
        if ($result['farben'] instanceof stdClass) {
            echo '123';
        }
    }
}
```

### Responsible rules

* `RemoveDeadInstanceOfRector`

## Expected Behavior

I think `RemoveDeadInstanceOfRector` shouldn't modify this code and skip it.

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/rectorphp/rector/issues/8147

### CODE REVIEW

**Comment by samsonasik** [comment]
my current investigation, it probably a PHPStan bug on detecting type, on array, it skipped properly, see:

https://getrector.com/demo/4a02fd64-ffaf-4142-9746-6de2899c9f79

I think the proper way is currently add isset() check instead to the code, see:

https://getrector.com/demo/9631117d-aa73-488e-a68a-8d5e12362b89

that the instanceof will always correct. Closing for now.

**Comment by staabm** [comment]
PHPStan detects it properly, see https://phpstan.org/r/dcded1e7-0941-4d6b-9451-c33face0ff89

maybe its some kind of scope problem again?

**Comment by samsonasik** [comment]
@staabm no, the array is working ok, the issue is on Iterator, see https://phpstan.org/r/05fd1758-7df0-4307-b419-dc29bd867ae4

**Comment by samsonasik** [comment]
@staabm I created bug report issue on PHPStan https://github.com/phpstan/phpstan/issues/9784 on Iterator usage

**Comment by staabm** [comment]
I see, thanks

**Pull request closed without merging**
