### PR TITLE
[EarlyReturn][Php73] Handle JsonThrowOnErrorRector + ChangeAndIfToEarlyReturnRector

### PR DESCRIPTION
**Pull request by samsonasik**
Given the following code:

```php
function f()
{
    if (true && true) {
        json_decode($a);
    }
}
```

It produce error:

```bash
There was 1 failure:

1) Rector\Core\Tests\Issues\JsonThrowWithChangeAndIf\JsonThrowWithChangeAndIfTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
assert($itemStartPos >= 0 && $itemEndPos >= 0) in /Users/samsonasik/www/rector-src/vendor/nikic/php-parser/lib/PhpParser/PrettyPrinterAbstract.php:865
```

applied rules:

```php
Rector\EarlyReturn\Rector\If_\ChangeAndIfToEarlyReturnRector;
Rector\Php73\Rector\FuncCall\JsonThrowOnErrorRector;
```

Fixes https://github.com/rectorphp/rector/issues/6812

### CODE REVIEW

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
