### PR TITLE
[PHPStanStaticTypeMapper] Make use of toPhpDocNode() on ObjectTypeMapper

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://github.com/rectorphp/rector/issues/7959

### CODE REVIEW

**Comment by samsonasik** [comment]
closing for now, it seems the issue is on FQCNize type

**Comment by TomasVotruba** [comment]
> @samsonasik closing for now, it seems the issue is on FQCNize type

I came to the same conslussion.

**Comment by samsonasik** [comment]
@TomasVotruba I updated to use `TypeTraverser::map()` based on @ondrejmirtes suggestion at https://github.com/rectorphp/rector/issues/7959#issuecomment-1646818390

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba let's merge it to have faster feedback to test 👍

**Pull request merged**
