### PR TITLE
Fix broken scoped build with double quotes in commit messages

### PR DESCRIPTION
**Pull request by staabm**
blindly applying the fix from phpstan-src

https://github.com/phpstan/phpstan-src/blob/613c57c3d2301402ca474338959ad8e3bd204000/.github/workflows/phar.yml#L180-L186

-----

refs https://github.com/rectorphp/rector-src/pull/4164#issuecomment-1585862821

### CODE REVIEW

**Comment by staabm** [comment]
//cc @samsonasik

**Comment by samsonasik** [comment]
Could you rename commit with double quote?, eg: `Fix broken scoped build with "double quotes" in commit messages` so we can test on build.

**Comment by samsonasik** [comment]
I can rename your commit on squash merge to include double quote to test, let's give it a try.

**Comment by samsonasik** [comment]
Merged with include doubel quote in commit message https://github.com/rectorphp/rector-src/commit/3e43e54aa5e99a3952208734da68e8e22d00872a

**Comment by samsonasik** [comment]
@staabm it doesn't work, see https://github.com/rectorphp/rector-src/actions/runs/5234281911/jobs/9450314156#step:22:13

I will revert.

**Comment by samsonasik** [comment]
Reverting at https://github.com/rectorphp/rector-src/pull/4176

**Pull request merged**
