### PR TITLE
Update to nikic/php-parser 4.13.1

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
It seems cause error in tests:

```bash
1) Rector\Tests\Php74\Rector\Closure\ClosureToArrowFunctionRector\ClosureToArrowFunctionRectorTest::test with data set #2 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Undefined array key "expr"
```

**Comment by samsonasik** [comment]
Fixed 🎉

**Comment by samsonasik** [comment]
All checks have passed 🎉 @TomasVotruba it is ready for review.

**Comment by villfa** [comment]
Related to: https://github.com/nikic/PHP-Parser/pull/808

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
